{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAnswerCell"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"model"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackQAStruct","preciseIdentifier":"s:5Divar16FeedbackQAStructV","text":"FeedbackQAStruct"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAnswerCell","preciseIdentifier":"c:@M@Divar@objc(cs)FeedbackAnswerCell","text":"FeedbackAnswerCell"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/brandfeedbackcell\/getanswercell(_:indexpath:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BrandFeedbackCell\/getAnswerCell(_:indexPath:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","title":"getAnswerCell(_:indexPath:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAnswerCell"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FeedbackQAStruct","preciseIdentifier":"s:5Divar16FeedbackQAStructV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"FeedbackAnswerCell","preciseIdentifier":"c:@M@Divar@objc(cs)FeedbackAnswerCell"}],"symbolKind":"method","externalID":"s:5Divar17BrandFeedbackCellC09getAnswerD0_9indexPathAA0cfD0CAA0C8QAStructVSg_10Foundation05IndexH0VtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BrandFeedbackCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAnswerCell":{"role":"symbol","title":"FeedbackAnswerCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeedbackAnswerCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAnswerCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeedbackAnswerCell"}],"url":"\/documentation\/divar\/feedbackanswercell"},"doc://com.Divar.DivarClient/documentation/Divar/BrandFeedbackCell":{"role":"symbol","title":"BrandFeedbackCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrandFeedbackCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BrandFeedbackCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BrandFeedbackCell"}],"url":"\/documentation\/divar\/brandfeedbackcell"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackQAStruct":{"role":"symbol","title":"FeedbackQAStruct","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeedbackQAStruct"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackQAStruct","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeedbackQAStruct"}],"url":"\/documentation\/divar\/feedbackqastruct"},"doc://com.Divar.DivarClient/documentation/Divar/BrandFeedbackCell/getAnswerCell(_:indexPath:)":{"role":"symbol","title":"getAnswerCell(_:indexPath:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAnswerCell"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FeedbackQAStruct","preciseIdentifier":"s:5Divar16FeedbackQAStructV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"FeedbackAnswerCell","preciseIdentifier":"c:@M@Divar@objc(cs)FeedbackAnswerCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BrandFeedbackCell\/getAnswerCell(_:indexPath:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/brandfeedbackcell\/getanswercell(_:indexpath:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAnswerCell\/title","value":"FeedbackAnswerCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAnswerCell\/fragments","value":[{"kind":"identifier","text":"FeedbackAnswerCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BrandFeedbackCell\/title","value":"BrandFeedbackCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BrandFeedbackCell\/fragments","value":[{"kind":"identifier","text":"BrandFeedbackCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}