{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialPriceTools"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":" "},{"kind":"internalParam","text":"navigation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController","text":"NavigationController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"PriceToolsPage"}]}]},{"kind":"parameters","parameters":[{"name":"navigation","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"NavigationController where flow will push into it"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/priceflowcontroller\/initialpricetools(in:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceFlowController\/initialPriceTools(in:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"this mehtod generate "},{"type":"codeVoice","code":"PriceToolsPage"},{"type":"text","text":" which always is root of "},{"type":"codeVoice","code":"PriceFlowController"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialPriceTools"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"title":"initialPriceTools(in:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:5Divar19PriceFlowControllerC07initialB5Tools2inSo06UIViewD0CAA010NavigationD0C_tF","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceFlowController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PriceFlowController":{"role":"symbol","title":"PriceFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PriceFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PriceFlowController"}],"url":"\/documentation\/divar\/priceflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/NavigationController":{"role":"symbol","title":"NavigationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NavigationController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NavigationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NavigationController"}],"url":"\/documentation\/divar\/navigationcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PriceFlowController/initialPriceTools(in:)":{"role":"symbol","title":"initialPriceTools(in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialPriceTools"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[{"type":"text","text":"this mehtod generate "},{"type":"codeVoice","code":"PriceToolsPage"},{"type":"text","text":" which always is root of "},{"type":"codeVoice","code":"PriceFlowController"}],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceFlowController\/initialPriceTools(in:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/priceflowcontroller\/initialpricetools(in:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceFlowController\/title","value":"PriceFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceFlowController\/fragments","value":[{"kind":"identifier","text":"PriceFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NavigationController\/title","value":"NavigationController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NavigationController\/fragments","value":[{"kind":"identifier","text":"NavigationController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}