{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialEstimateUsedPrice"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":" "},{"kind":"internalParam","text":"navigation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController","text":"NavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"payload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BooleanRateRowFeedBackPayload","preciseIdentifier":"s:5Divar29BooleanRateRowFeedBackPayloadV","text":"BooleanRateRowFeedBackPayload"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/priceflowcontroller\/initialestimateusedprice(in:payload:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceFlowController\/initialEstimateUsedPrice(in:payload:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialEstimateUsedPrice"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"payload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BooleanRateRowFeedBackPayload","preciseIdentifier":"s:5Divar29BooleanRateRowFeedBackPayloadV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"title":"initialEstimateUsedPrice(in:payload:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:5Divar19PriceFlowControllerC019initialEstimateUsedB02in7payloadSo06UIViewD0CAA010NavigationD0C_AA29BooleanRateRowFeedBackPayloadVtF","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceFlowController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/NavigationController":{"role":"symbol","title":"NavigationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NavigationController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NavigationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NavigationController"}],"url":"\/documentation\/divar\/navigationcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PriceFlowController":{"role":"symbol","title":"PriceFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PriceFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PriceFlowController"}],"url":"\/documentation\/divar\/priceflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PriceFlowController/initialEstimateUsedPrice(in:payload:)":{"role":"symbol","title":"initialEstimateUsedPrice(in:payload:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialEstimateUsedPrice"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"payload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BooleanRateRowFeedBackPayload","preciseIdentifier":"s:5Divar29BooleanRateRowFeedBackPayloadV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceFlowController\/initialEstimateUsedPrice(in:payload:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/priceflowcontroller\/initialestimateusedprice(in:payload:)"},"doc://com.Divar.DivarClient/documentation/Divar/BooleanRateRowFeedBackPayload":{"role":"symbol","title":"BooleanRateRowFeedBackPayload","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BooleanRateRowFeedBackPayload"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BooleanRateRowFeedBackPayload","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BooleanRateRowFeedBackPayload"}],"url":"\/documentation\/divar\/booleanraterowfeedbackpayload"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NavigationController\/title","value":"NavigationController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NavigationController\/fragments","value":[{"kind":"identifier","text":"NavigationController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceFlowController\/title","value":"PriceFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceFlowController\/fragments","value":[{"kind":"identifier","text":"PriceFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}