{"variants":[{"paths":["\/documentation\/divar\/chatviewcontroller\/chatoptionactionprotocol-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/chatviewcontroller\/chatoptionactionprotocol-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/ChatOptionActionProtocol-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/blockUser(reason:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/getConfirmationOnDelete(conversationId:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/showBlockReasons()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/showSupport()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/unblockUser()"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"ChatOptionActionProtocol Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController":{"role":"symbol","title":"ChatViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatViewController"}],"url":"\/documentation\/divar\/chatviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/showBlockReasons()":{"role":"symbol","title":"showBlockReasons()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showBlockReasons"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/showBlockReasons()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showBlockReasons"}],"url":"\/documentation\/divar\/chatviewcontroller\/showblockreasons()"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/unblockUser()":{"role":"symbol","title":"unblockUser()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unblockUser"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/unblockUser()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/unblockuser()"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/blockUser(reason:)":{"role":"symbol","title":"blockUser(reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"blockUser"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/blockUser(reason:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/blockuser(reason:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/getConfirmationOnDelete(conversationId:)":{"role":"symbol","title":"getConfirmationOnDelete(conversationId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getConfirmationOnDelete"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/getConfirmationOnDelete(conversationId:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/getconfirmationondelete(conversationid:)"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/showSupport()":{"role":"symbol","title":"showSupport()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showSupport"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/showSupport()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/showsupport()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/blockUser(reason:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/getConfirmationOnDelete(conversationId:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/showBlockReasons()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/showSupport()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/unblockUser()"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/title","value":"ChatViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/fragments","value":[{"kind":"identifier","text":"ChatViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1showBlockReasons()\/title","value":"showBlockReasons"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1showBlockReasons()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showBlockReasons"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}