{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeButtonDidClick"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagePreviewBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MessagePreviewBarViewController","text":"MessagePreviewBarViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/chatviewcontroller\/closebuttondidclick(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/closeButtonDidClick(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"MessagePreviewBarViewControllerDelegate.closeButtonDidClick(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"closeButtonDidClick(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeButtonDidClick"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MessagePreviewBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MessagePreviewBarViewController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar18ChatViewControllerC19closeButtonDidClickyyAA017MessagePreviewBarcD0CF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/MessagePreviewBarViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/MessagePreviewBarViewController":{"role":"symbol","title":"MessagePreviewBarViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagePreviewBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagePreviewBarViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagePreviewBarViewController"}],"url":"\/documentation\/divar\/messagepreviewbarviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController":{"role":"symbol","title":"ChatViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatViewController"}],"url":"\/documentation\/divar\/chatviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/closeButtonDidClick(_:)":{"role":"symbol","title":"closeButtonDidClick(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeButtonDidClick"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MessagePreviewBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MessagePreviewBarViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/closeButtonDidClick(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/closebuttondidclick(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/MessagePreviewBarViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"MessagePreviewBarViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/MessagePreviewBarViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/messagepreviewbarviewcontrollerdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagePreviewBarViewController\/title","value":"MessagePreviewBarViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagePreviewBarViewController\/fragments","value":[{"kind":"identifier","text":"MessagePreviewBarViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/title","value":"ChatViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/fragments","value":[{"kind":"identifier","text":"ChatViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}