{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageInputArea"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController","preciseIdentifier":"c:@M@Divar@objc(cs)InputAreaViewController","text":"InputAreaViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestEditMessageWithText"},{"kind":"text","text":" "},{"kind":"internalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/chatviewcontroller\/messageinputarea(_:didrequesteditmessagewithtext:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/messageInputArea(_:didRequestEditMessageWithText:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"MessageInputAreaViewControllerDelegate.messageInputArea(_:didRequestEditMessageWithText:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"messageInputArea(_:didRequestEditMessageWithText:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageInputArea"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"InputAreaViewController","preciseIdentifier":"c:@M@Divar@objc(cs)InputAreaViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestEditMessageWithText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar18ChatViewControllerC16messageInputArea_29didRequestEditMessageWithTextyAA0fgcD0C_SStF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/MessageInputAreaViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/messageInputArea(_:didRequestEditMessageWithText:)":{"role":"symbol","title":"messageInputArea(_:didRequestEditMessageWithText:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageInputArea"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"InputAreaViewController","preciseIdentifier":"c:@M@Divar@objc(cs)InputAreaViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestEditMessageWithText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/messageInputArea(_:didRequestEditMessageWithText:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/messageinputarea(_:didrequesteditmessagewithtext:)"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController":{"role":"symbol","title":"InputAreaViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InputAreaViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InputAreaViewController"}],"url":"\/documentation\/divar\/inputareaviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/MessageInputAreaViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"MessageInputAreaViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/MessageInputAreaViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/messageinputareaviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController":{"role":"symbol","title":"ChatViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatViewController"}],"url":"\/documentation\/divar\/chatviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController\/title","value":"InputAreaViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController\/fragments","value":[{"kind":"identifier","text":"InputAreaViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/title","value":"ChatViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/fragments","value":[{"kind":"identifier","text":"ChatViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}