{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagePreviewBarViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagePreviewBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MessagePreviewBarViewController","text":"MessagePreviewBarViewController"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/chatviewcontroller\/messagepreviewbarviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/messagePreviewBarViewController","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagePreviewBarViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagePreviewBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MessagePreviewBarViewController"}],"title":"messagePreviewBarViewController","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar18ChatViewControllerC017messagePreviewBarcD0AA07MessagefgcD0Cvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/MessagePreviewBarViewController":{"role":"symbol","title":"MessagePreviewBarViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagePreviewBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagePreviewBarViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagePreviewBarViewController"}],"url":"\/documentation\/divar\/messagepreviewbarviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/messagePreviewBarViewController":{"role":"symbol","title":"messagePreviewBarViewController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagePreviewBarViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagePreviewBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MessagePreviewBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/messagePreviewBarViewController","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/messagepreviewbarviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController":{"role":"symbol","title":"ChatViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatViewController"}],"url":"\/documentation\/divar\/chatviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagePreviewBarViewController\/title","value":"MessagePreviewBarViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagePreviewBarViewController\/fragments","value":[{"kind":"identifier","text":"MessagePreviewBarViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/title","value":"ChatViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/fragments","value":[{"kind":"identifier","text":"ChatViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}