{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareMessagePreview"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV","text":"ChatConversationMessageTable"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forType"},{"kind":"text","text":" "},{"kind":"internalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagePreviewBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MessagePreviewBarViewController","text":"MessagePreviewBarViewController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagePreviewBarViewController\/MessagePreviewType","preciseIdentifier":"s:5Divar31MessagePreviewBarViewControllerC0bC4TypeO","text":"MessagePreviewType"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/chatviewcontroller\/preparemessagepreview(_:fortype:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/prepareMessagePreview(_:forType:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","title":"prepareMessagePreview(_:forType:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareMessagePreview"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagePreviewBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MessagePreviewBarViewController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"MessagePreviewType","preciseIdentifier":"s:5Divar31MessagePreviewBarViewControllerC0bC4TypeO"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar18ChatViewControllerC21prepareMessagePreview_7forTypeyAA0b12ConversationF5TableV_AA0fg3BarcD0C0fgI0OtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController":{"role":"symbol","title":"ChatViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatViewController"}],"url":"\/documentation\/divar\/chatviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/MessagePreviewBarViewController/MessagePreviewType":{"role":"symbol","title":"MessagePreviewBarViewController.MessagePreviewType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagePreviewType"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagePreviewBarViewController\/MessagePreviewType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagePreviewType"}],"url":"\/documentation\/divar\/messagepreviewbarviewcontroller\/messagepreviewtype"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/prepareMessagePreview(_:forType:)":{"role":"symbol","title":"prepareMessagePreview(_:forType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareMessagePreview"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagePreviewBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MessagePreviewBarViewController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"MessagePreviewType","preciseIdentifier":"s:5Divar31MessagePreviewBarViewControllerC0bC4TypeO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/prepareMessagePreview(_:forType:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/preparemessagepreview(_:fortype:)"},"doc://com.Divar.DivarClient/documentation/Divar/ChatConversationMessageTable":{"role":"symbol","title":"ChatConversationMessageTable","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatConversationMessageTable"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatConversationMessageTable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatConversationMessageTable"}],"url":"\/documentation\/divar\/chatconversationmessagetable"},"doc://com.Divar.DivarClient/documentation/Divar/MessagePreviewBarViewController":{"role":"symbol","title":"MessagePreviewBarViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagePreviewBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagePreviewBarViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagePreviewBarViewController"}],"url":"\/documentation\/divar\/messagepreviewbarviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/title","value":"ChatViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/fragments","value":[{"kind":"identifier","text":"ChatViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagePreviewBarViewController\/title","value":"MessagePreviewBarViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagePreviewBarViewController\/fragments","value":[{"kind":"identifier","text":"MessagePreviewBarViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}