{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"previewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoPreviewController","preciseIdentifier":"c:@M@Divar@objc(cs)VideoPreviewController","text":"VideoPreviewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didConfirmVideoWithURL"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/chatviewcontroller\/previewcontroller(_:didconfirmvideowithurl:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/previewController(_:didConfirmVideoWithURL:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"VideoPreviewControllerDelegate.previewController(_:didConfirmVideoWithURL:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"previewController(_:didConfirmVideoWithURL:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"VideoPreviewController","preciseIdentifier":"c:@M@Divar@objc(cs)VideoPreviewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didConfirmVideoWithURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar18ChatViewControllerC07previewD0_22didConfirmVideoWithURLyAA0h7PreviewD0C_10Foundation0J0VtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/VideoPreviewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/previewController(_:didConfirmVideoWithURL:)":{"role":"symbol","title":"previewController(_:didConfirmVideoWithURL:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"VideoPreviewController","preciseIdentifier":"c:@M@Divar@objc(cs)VideoPreviewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didConfirmVideoWithURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/previewController(_:didConfirmVideoWithURL:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/previewcontroller(_:didconfirmvideowithurl:)"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController":{"role":"symbol","title":"ChatViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatViewController"}],"url":"\/documentation\/divar\/chatviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/VideoPreviewController":{"role":"symbol","title":"VideoPreviewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPreviewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoPreviewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoPreviewController"}],"url":"\/documentation\/divar\/videopreviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/VideoPreviewControllerDelegate-Implementations":{"role":"collectionGroup","title":"VideoPreviewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/VideoPreviewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/videopreviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/title","value":"ChatViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/fragments","value":[{"kind":"identifier","text":"ChatViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VideoPreviewController\/title","value":"VideoPreviewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VideoPreviewController\/fragments","value":[{"kind":"identifier","text":"VideoPreviewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}