{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"safariViewControllerDidFinish"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SFSafariViewController","preciseIdentifier":"c:objc(cs)SFSafariViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/chatviewcontroller\/safariviewcontrollerdidfinish(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/chatviewcontroller\/safariviewcontrollerdidfinish(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/safariViewControllerDidFinish(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"SFSafariViewControllerDelegate.safariViewControllerDidFinish(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"safariViewControllerDidFinish"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SFSafariViewController","preciseIdentifier":"c:objc(cs)SFSafariViewController"},{"kind":"text","text":")"}],"title":"safariViewControllerDidFinish(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@Divar@objc(cs)ChatViewController(im)safariViewControllerDidFinish:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"safariViewControllerDidFinish:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/SFSafariViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/SFSafariViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"SFSafariViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/SFSafariViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/sfsafariviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController":{"role":"symbol","title":"ChatViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatViewController"}],"url":"\/documentation\/divar\/chatviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/safariViewControllerDidFinish(_:)":{"role":"symbol","title":"safariViewControllerDidFinish(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"safariViewControllerDidFinish"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SFSafariViewController","preciseIdentifier":"c:objc(cs)SFSafariViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/safariViewControllerDidFinish(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"safariViewControllerDidFinish:"}],"url":"\/documentation\/divar\/chatviewcontroller\/safariviewcontrollerdidfinish(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"safariViewControllerDidFinish:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"safariViewControllerDidFinish:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"safariViewControllerDidFinish:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SFSafariViewController","preciseIdentifier":"c:objc(cs)SFSafariViewController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"_"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/title","value":"ChatViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/fragments","value":[{"kind":"identifier","text":"ChatViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1safariViewControllerDidFinish(_:)\/title","value":"safariViewControllerDidFinish:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1safariViewControllerDidFinish(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"safariViewControllerDidFinish:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}