{"variants":[{"paths":["\/documentation\/divar\/chatviewcontroller\/sfsafariviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/chatviewcontroller\/sfsafariviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/SFSafariViewControllerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/safariViewControllerDidFinish(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"SFSafariViewControllerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/safariViewControllerDidFinish(_:)":{"role":"symbol","title":"safariViewControllerDidFinish(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"safariViewControllerDidFinish"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SFSafariViewController","preciseIdentifier":"c:objc(cs)SFSafariViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/safariViewControllerDidFinish(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"safariViewControllerDidFinish:"}],"url":"\/documentation\/divar\/chatviewcontroller\/safariviewcontrollerdidfinish(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController":{"role":"symbol","title":"ChatViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatViewController"}],"url":"\/documentation\/divar\/chatviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/safariViewControllerDidFinish(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1safariViewControllerDidFinish(_:)\/title","value":"safariViewControllerDidFinish:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1safariViewControllerDidFinish(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"safariViewControllerDidFinish:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/title","value":"ChatViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/fragments","value":[{"kind":"identifier","text":"ChatViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}