{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"suggestionsVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TagListViewController","text":"TagListViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/chatviewcontroller\/suggestionsvc"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/suggestionsVC","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"suggestionsVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagListViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TagListViewController"}],"title":"suggestionsVC","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar18ChatViewControllerC13suggestionsVCAA07TagListcD0Cvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/suggestionsVC":{"role":"symbol","title":"suggestionsVC","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"suggestionsVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagListViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TagListViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/suggestionsVC","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/suggestionsvc"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController":{"role":"symbol","title":"ChatViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatViewController"}],"url":"\/documentation\/divar\/chatviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/TagListViewController":{"role":"symbol","title":"TagListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagListViewController"}],"url":"\/documentation\/divar\/taglistviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/title","value":"ChatViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/fragments","value":[{"kind":"identifier","text":"ChatViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListViewController\/title","value":"TagListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListViewController\/fragments","value":[{"kind":"identifier","text":"TagListViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}