{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagListCell"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListCell","preciseIdentifier":"c:@M@Divar@objc(cs)TagListCell","text":"TagListCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectCloseButtonWithId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/taglistviewcontroller\/taglistcell(_:didselectclosebuttonwithid:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListViewController\/tagListCell(_:didSelectCloseButtonWithId:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"TagListCellDelegate.tagListCell(_:didSelectCloseButtonWithId:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"tagListCell(_:didSelectCloseButtonWithId:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagListCell"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TagListCell","preciseIdentifier":"c:@M@Divar@objc(cs)TagListCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectCloseButtonWithId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar21TagListViewControllerC03tagC4Cell_26didSelectCloseButtonWithIdyAA0bcG0C_SitF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListViewController\/TagListCellDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/TagListViewController/tagListCell(_:didSelectCloseButtonWithId:)":{"role":"symbol","title":"tagListCell(_:didSelectCloseButtonWithId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagListCell"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TagListCell","preciseIdentifier":"c:@M@Divar@objc(cs)TagListCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectCloseButtonWithId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListViewController\/tagListCell(_:didSelectCloseButtonWithId:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/taglistviewcontroller\/taglistcell(_:didselectclosebuttonwithid:)"},"doc://com.Divar.DivarClient/documentation/Divar/TagListViewController/TagListCellDelegate-Implementations":{"role":"collectionGroup","title":"TagListCellDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListViewController\/TagListCellDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/taglistviewcontroller\/taglistcelldelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/TagListCell":{"role":"symbol","title":"TagListCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagListCell"}],"url":"\/documentation\/divar\/taglistcell"},"doc://com.Divar.DivarClient/documentation/Divar/TagListViewController":{"role":"symbol","title":"TagListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagListViewController"}],"url":"\/documentation\/divar\/taglistviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListCell\/title","value":"TagListCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListCell\/fragments","value":[{"kind":"identifier","text":"TagListCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListViewController\/title","value":"TagListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListViewController\/fragments","value":[{"kind":"identifier","text":"TagListViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}