{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageComposeViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MFMessageComposeViewController","preciseIdentifier":"c:objc(cs)MFMessageComposeViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishWith"},{"kind":"text","text":" "},{"kind":"internalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageComposeResult","preciseIdentifier":"c:@E@MessageComposeResult"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/custommfmessagecomposeviewcontroller\/messagecomposeviewcontroller(_:didfinishwith:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/custommfmessagecomposeviewcontroller\/messagecomposeviewcontroller(_:didfinishwith:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomMFMessageComposeViewController\/messageComposeViewController(_:didFinishWith:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"MFMessageComposeViewControllerDelegate.messageComposeViewController(_:didFinishWith:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"messageComposeViewController:didFinishWithResult:"}],"role":"symbol","title":"messageComposeViewController(_:didFinishWith:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageComposeViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MFMessageComposeViewController","preciseIdentifier":"c:objc(cs)MFMessageComposeViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageComposeResult","preciseIdentifier":"c:@E@MessageComposeResult"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@Divar@objc(cs)CustomMFMessageComposeViewController(im)messageComposeViewController:didFinishWithResult:","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomMFMessageComposeViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomMFMessageComposeViewController\/MFMessageComposeViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/CustomMFMessageComposeViewController/messageComposeViewController(_:didFinishWith:)":{"role":"symbol","title":"messageComposeViewController(_:didFinishWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageComposeViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MFMessageComposeViewController","preciseIdentifier":"c:objc(cs)MFMessageComposeViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageComposeResult","preciseIdentifier":"c:@E@MessageComposeResult"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomMFMessageComposeViewController\/messageComposeViewController(_:didFinishWith:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageComposeViewController:didFinishWithResult:"}],"url":"\/documentation\/divar\/custommfmessagecomposeviewcontroller\/messagecomposeviewcontroller(_:didfinishwith:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/CustomMFMessageComposeViewController/MFMessageComposeViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"MFMessageComposeViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomMFMessageComposeViewController\/MFMessageComposeViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/custommfmessagecomposeviewcontroller\/mfmessagecomposeviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/CustomMFMessageComposeViewController":{"role":"symbol","title":"CustomMFMessageComposeViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomMFMessageComposeViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomMFMessageComposeViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomMFMessageComposeViewController"}],"url":"\/documentation\/divar\/custommfmessagecomposeviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"messageComposeViewController:didFinishWithResult:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageComposeViewController:didFinishWithResult:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"messageComposeViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MFMessageComposeViewController","preciseIdentifier":"c:objc(cs)MFMessageComposeViewController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishWithResult:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MessageComposeResult","preciseIdentifier":"c:@E@MessageComposeResult"},{"kind":"text","text":")"},{"kind":"internalParam","text":"result"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomMFMessageComposeViewController~1messageComposeViewController(_:didFinishWith:)\/title","value":"messageComposeViewController:didFinishWithResult:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomMFMessageComposeViewController~1messageComposeViewController(_:didFinishWith:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageComposeViewController:didFinishWithResult:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomMFMessageComposeViewController\/title","value":"CustomMFMessageComposeViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomMFMessageComposeViewController\/fragments","value":[{"kind":"identifier","text":"CustomMFMessageComposeViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}