{"variants":[{"paths":["\/documentation\/divar\/custommfmessagecomposeviewcontroller\/mfmessagecomposeviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/custommfmessagecomposeviewcontroller\/mfmessagecomposeviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomMFMessageComposeViewController\/MFMessageComposeViewControllerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomMFMessageComposeViewController\/messageComposeViewController(_:didFinishWith:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"MFMessageComposeViewControllerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomMFMessageComposeViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/CustomMFMessageComposeViewController":{"role":"symbol","title":"CustomMFMessageComposeViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomMFMessageComposeViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomMFMessageComposeViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomMFMessageComposeViewController"}],"url":"\/documentation\/divar\/custommfmessagecomposeviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/CustomMFMessageComposeViewController/messageComposeViewController(_:didFinishWith:)":{"role":"symbol","title":"messageComposeViewController(_:didFinishWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageComposeViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MFMessageComposeViewController","preciseIdentifier":"c:objc(cs)MFMessageComposeViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageComposeResult","preciseIdentifier":"c:@E@MessageComposeResult"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomMFMessageComposeViewController\/messageComposeViewController(_:didFinishWith:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageComposeViewController:didFinishWithResult:"}],"url":"\/documentation\/divar\/custommfmessagecomposeviewcontroller\/messagecomposeviewcontroller(_:didfinishwith:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomMFMessageComposeViewController\/messageComposeViewController(_:didFinishWith:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomMFMessageComposeViewController\/title","value":"CustomMFMessageComposeViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomMFMessageComposeViewController\/fragments","value":[{"kind":"identifier","text":"CustomMFMessageComposeViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomMFMessageComposeViewController~1messageComposeViewController(_:didFinishWith:)\/title","value":"messageComposeViewController:didFinishWithResult:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomMFMessageComposeViewController~1messageComposeViewController(_:didFinishWith:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageComposeViewController:didFinishWithResult:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}