{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAllResponseHeaders"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/xmlhttprequestprotocol\/getallresponseheaders()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/xmlhttprequestprotocol\/getallresponseheaders()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/getAllResponseHeaders()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"getAllResponseHeaders"}],"role":"symbol","title":"getAllResponseHeaders()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAllResponseHeaders"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"symbolKind":"method","externalID":"c:objc(pl)XMLHttpRequest(im)getAllResponseHeaders","required":true,"modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/XMLHttpRequestProtocol":{"role":"symbol","title":"XMLHttpRequestProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"XMLHttpRequestProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"XMLHttpRequestProtocol"}],"url":"\/documentation\/divar\/xmlhttprequestprotocol"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/XMLHttpRequestProtocol/getAllResponseHeaders()":{"navigatorTitle":[{"kind":"identifier","text":"getAllResponseHeaders"}],"role":"symbol","title":"getAllResponseHeaders()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAllResponseHeaders"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/getAllResponseHeaders()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/xmlhttprequestprotocol\/getallresponseheaders()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getAllResponseHeaders"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAllResponseHeaders"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getAllResponseHeaders"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol\/title","value":"XMLHttpRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol\/fragments","value":[{"kind":"identifier","text":"XMLHttpRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1getAllResponseHeaders()\/title","value":"getAllResponseHeaders"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1getAllResponseHeaders()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAllResponseHeaders"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}