{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onerror"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JSValue","preciseIdentifier":"c:objc(cs)JSValue"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/xmlhttprequestprotocol\/onerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/xmlhttprequestprotocol\/onerror"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/onerror","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"onerror"}],"role":"symbol","title":"onerror","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onerror"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JSValue","preciseIdentifier":"c:objc(cs)JSValue"},{"kind":"text","text":"!"}],"symbolKind":"property","externalID":"c:objc(pl)XMLHttpRequest(py)onerror","required":true,"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"7.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/XMLHttpRequestProtocol/onerror":{"navigatorTitle":[{"kind":"identifier","text":"onerror"}],"role":"symbol","title":"onerror","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onerror"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JSValue","preciseIdentifier":"c:objc(cs)JSValue"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/onerror","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/xmlhttprequestprotocol\/onerror"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/XMLHttpRequestProtocol":{"role":"symbol","title":"XMLHttpRequestProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"XMLHttpRequestProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"XMLHttpRequestProtocol"}],"url":"\/documentation\/divar\/xmlhttprequestprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"onerror"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"onerror"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"JSValue","preciseIdentifier":"c:objc(cs)JSValue"},{"kind":"text","text":" * "},{"kind":"identifier","text":"onerror"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1onerror\/title","value":"onerror"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1onerror\/fragments","value":[{"kind":"identifier","text":"onerror"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol\/title","value":"XMLHttpRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol\/fragments","value":[{"kind":"identifier","text":"XMLHttpRequest"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}