{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"annotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKAnnotation","preciseIdentifier":"c:objc(pl)MKAnnotation"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"reuseIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/districtannotationview\/init(annotation:reuseidentifier:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/districtannotationview\/init(annotation:reuseidentifier:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictAnnotationView\/init(annotation:reuseIdentifier:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"annotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKAnnotation","preciseIdentifier":"c:objc(pl)MKAnnotation"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"reuseIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"init(annotation:reuseIdentifier:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@Divar@objc(cs)DistrictAnnotationView(im)initWithAnnotation:reuseIdentifier:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"initWithAnnotation:reuseIdentifier:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictAnnotationView"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/DistrictAnnotationView/init(annotation:reuseIdentifier:)":{"role":"symbol","title":"init(annotation:reuseIdentifier:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"annotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKAnnotation","preciseIdentifier":"c:objc(pl)MKAnnotation"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"reuseIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictAnnotationView\/init(annotation:reuseIdentifier:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAnnotation:reuseIdentifier:"}],"url":"\/documentation\/divar\/districtannotationview\/init(annotation:reuseidentifier:)"},"doc://com.Divar.DivarClient/documentation/Divar/DistrictAnnotationView":{"role":"symbol","title":"DistrictAnnotationView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DistrictAnnotationView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictAnnotationView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DistrictAnnotationView"}],"url":"\/documentation\/divar\/districtannotationview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithAnnotation:reuseIdentifier:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAnnotation:reuseIdentifier:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAnnotation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<MKAnnotation>","preciseIdentifier":"c:Qoobjc(pl)MKAnnotation"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"annotation"},{"kind":"text","text":" "},{"kind":"identifier","text":"reuseIdentifier:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"reuseIdentifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictAnnotationView~1init(annotation:reuseIdentifier:)\/title","value":"initWithAnnotation:reuseIdentifier:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictAnnotationView~1init(annotation:reuseIdentifier:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAnnotation:reuseIdentifier:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictAnnotationView\/title","value":"DistrictAnnotationView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictAnnotationView\/fragments","value":[{"kind":"identifier","text":"DistrictAnnotationView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}