{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchOutlet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISwitch","preciseIdentifier":"c:objc(cs)UISwitch"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/switchview\/switchoutlet"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/switchview\/switchoutlet"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SwitchView\/switchOutlet","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchOutlet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISwitch","preciseIdentifier":"c:objc(cs)UISwitch"},{"kind":"text","text":"!"}],"title":"switchOutlet","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)SwitchView(py)switchOutlet","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"switchOutlet"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SwitchView"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/SwitchView/switchOutlet":{"role":"symbol","title":"switchOutlet","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchOutlet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISwitch","preciseIdentifier":"c:objc(cs)UISwitch"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SwitchView\/switchOutlet","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"switchOutlet"}],"url":"\/documentation\/divar\/switchview\/switchoutlet"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/SwitchView":{"role":"symbol","title":"SwitchView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SwitchView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SwitchView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SwitchView"}],"url":"\/documentation\/divar\/switchview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"switchOutlet"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"switchOutlet"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UISwitch","preciseIdentifier":"c:objc(cs)UISwitch"},{"kind":"text","text":" * "},{"kind":"identifier","text":"switchOutlet"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SwitchView~1switchOutlet\/title","value":"switchOutlet"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SwitchView~1switchOutlet\/fragments","value":[{"kind":"identifier","text":"switchOutlet"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SwitchView\/title","value":"SwitchView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SwitchView\/fragments","value":[{"kind":"identifier","text":"SwitchView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}