{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adaptivePresentationStyle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"traitCollection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIModalPresentationStyle","preciseIdentifier":"c:@E@UIModalPresentationStyle"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/panmodalpresentationdelegate\/adaptivepresentationstyle(for:traitcollection:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/panmodalpresentationdelegate\/adaptivepresentationstyle(for:traitcollection:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate\/adaptivePresentationStyle(for:traitCollection:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIAdaptivePresentationControllerDelegate.adaptivePresentationStyle(for:traitCollection:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adaptivePresentationStyle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"traitCollection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIModalPresentationStyle","preciseIdentifier":"c:@E@UIModalPresentationStyle"}],"title":"adaptivePresentationStyle(for:traitCollection:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@Divar@objc(cs)PanModalPresentationDelegate(im)adaptivePresentationStyleForPresentationController:traitCollection:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"adaptivePresentationStyleForPresentationController:traitCollection:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate\/UIAdaptivePresentationControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationDelegate/adaptivePresentationStyle(for:traitCollection:)":{"role":"symbol","title":"adaptivePresentationStyle(for:traitCollection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adaptivePresentationStyle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"traitCollection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIModalPresentationStyle","preciseIdentifier":"c:@E@UIModalPresentationStyle"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate\/adaptivePresentationStyle(for:traitCollection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adaptivePresentationStyleForPresentationController:traitCollection:"}],"url":"\/documentation\/divar\/panmodalpresentationdelegate\/adaptivepresentationstyle(for:traitcollection:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationDelegate":{"role":"symbol","title":"PanModalPresentationDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresentationDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresentationDelegate"}],"url":"\/documentation\/divar\/panmodalpresentationdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationDelegate/UIAdaptivePresentationControllerDelegate-Implementations":{"role":"collectionGroup","title":"UIAdaptivePresentationControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate\/UIAdaptivePresentationControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/panmodalpresentationdelegate\/uiadaptivepresentationcontrollerdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"adaptivePresentationStyleForPresentationController:traitCollection:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adaptivePresentationStyleForPresentationController:traitCollection:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIModalPresentationStyle","preciseIdentifier":"c:@E@UIModalPresentationStyle"},{"kind":"text","text":") "},{"kind":"identifier","text":"adaptivePresentationStyleForPresentationController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"kind":"identifier","text":"traitCollection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"traitCollection"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationDelegate~1adaptivePresentationStyle(for:traitCollection:)\/title","value":"adaptivePresentationStyleForPresentationController:traitCollection:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationDelegate~1adaptivePresentationStyle(for:traitCollection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adaptivePresentationStyleForPresentationController:traitCollection:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationDelegate\/title","value":"PanModalPresentationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationDelegate\/fragments","value":[{"kind":"identifier","text":"PanModalPresentationDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}