{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forPresented"},{"kind":"text","text":" "},{"kind":"internalParam","text":"presented"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"presenting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewControllerAnimatedTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerAnimatedTransitioning"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/panmodalpresentationdelegate\/animationcontroller(forpresented:presenting:source:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/panmodalpresentationdelegate\/animationcontroller(forpresented:presenting:source:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate\/animationController(forPresented:presenting:source:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIViewControllerTransitioningDelegate.animationController(forPresented:presenting:source:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"animationControllerForPresentedController:presentingController:sourceController:"}],"role":"symbol","title":"animationController(forPresented:presenting:source:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forPresented"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"presenting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewControllerAnimatedTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerAnimatedTransitioning"},{"kind":"text","text":"?"}],"symbolKind":"method","externalID":"c:@CM@Divar@objc(cs)PanModalPresentationDelegate(im)animationControllerForPresentedController:presentingController:sourceController:","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate\/UIViewControllerTransitioningDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationDelegate/UIViewControllerTransitioningDelegate-Implementations":{"role":"collectionGroup","title":"UIViewControllerTransitioningDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate\/UIViewControllerTransitioningDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/panmodalpresentationdelegate\/uiviewcontrollertransitioningdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationDelegate":{"role":"symbol","title":"PanModalPresentationDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresentationDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresentationDelegate"}],"url":"\/documentation\/divar\/panmodalpresentationdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationDelegate/animationController(forPresented:presenting:source:)":{"role":"symbol","title":"animationController(forPresented:presenting:source:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forPresented"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"presenting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewControllerAnimatedTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerAnimatedTransitioning"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate\/animationController(forPresented:presenting:source:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animationControllerForPresentedController:presentingController:sourceController:"}],"url":"\/documentation\/divar\/panmodalpresentationdelegate\/animationcontroller(forpresented:presenting:source:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"animationControllerForPresentedController:presentingController:sourceController:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animationControllerForPresentedController:presentingController:sourceController:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id<UIViewControllerAnimatedTransitioning>","preciseIdentifier":"c:Qoobjc(pl)UIViewControllerAnimatedTransitioning"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"animationControllerForPresentedController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"presented"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentingController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"presenting"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"source"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationDelegate\/title","value":"PanModalPresentationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationDelegate\/fragments","value":[{"kind":"identifier","text":"PanModalPresentationDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationDelegate~1animationController(forPresented:presenting:source:)\/title","value":"animationControllerForPresentedController:presentingController:sourceController:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationDelegate~1animationController(forPresented:presenting:source:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animationControllerForPresentedController:presentingController:sourceController:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}