{"variants":[{"paths":["\/documentation\/divar\/panmodalpresentationdelegate\/uiadaptivepresentationcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/panmodalpresentationdelegate\/uiadaptivepresentationcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate\/UIAdaptivePresentationControllerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate\/adaptivePresentationStyle(for:traitCollection:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"UIAdaptivePresentationControllerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationDelegate":{"role":"symbol","title":"PanModalPresentationDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresentationDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresentationDelegate"}],"url":"\/documentation\/divar\/panmodalpresentationdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationDelegate/adaptivePresentationStyle(for:traitCollection:)":{"role":"symbol","title":"adaptivePresentationStyle(for:traitCollection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adaptivePresentationStyle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"traitCollection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIModalPresentationStyle","preciseIdentifier":"c:@E@UIModalPresentationStyle"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate\/adaptivePresentationStyle(for:traitCollection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adaptivePresentationStyleForPresentationController:traitCollection:"}],"url":"\/documentation\/divar\/panmodalpresentationdelegate\/adaptivepresentationstyle(for:traitcollection:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate\/adaptivePresentationStyle(for:traitCollection:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationDelegate\/title","value":"PanModalPresentationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationDelegate\/fragments","value":[{"kind":"identifier","text":"PanModalPresentationDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationDelegate~1adaptivePresentationStyle(for:traitCollection:)\/title","value":"adaptivePresentationStyleForPresentationController:traitCollection:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationDelegate~1adaptivePresentationStyle(for:traitCollection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adaptivePresentationStyleForPresentationController:traitCollection:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}