{"variants":[{"paths":["\/documentation\/divar\/panmodalpresentationdelegate\/uiviewcontrollertransitioningdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/panmodalpresentationdelegate\/uiviewcontrollertransitioningdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate\/UIViewControllerTransitioningDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate\/animationController(forDismissed:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate\/animationController(forPresented:presenting:source:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate\/presentationController(forPresented:presenting:source:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"UIViewControllerTransitioningDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationDelegate/animationController(forPresented:presenting:source:)":{"role":"symbol","title":"animationController(forPresented:presenting:source:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forPresented"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"presenting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewControllerAnimatedTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerAnimatedTransitioning"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate\/animationController(forPresented:presenting:source:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animationControllerForPresentedController:presentingController:sourceController:"}],"url":"\/documentation\/divar\/panmodalpresentationdelegate\/animationcontroller(forpresented:presenting:source:)"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationDelegate/animationController(forDismissed:)":{"role":"symbol","title":"animationController(forDismissed:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forDismissed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewControllerAnimatedTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerAnimatedTransitioning"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate\/animationController(forDismissed:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animationControllerForDismissedController:"}],"url":"\/documentation\/divar\/panmodalpresentationdelegate\/animationcontroller(fordismissed:)"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationDelegate":{"role":"symbol","title":"PanModalPresentationDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresentationDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresentationDelegate"}],"url":"\/documentation\/divar\/panmodalpresentationdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationDelegate/presentationController(forPresented:presenting:source:)":{"role":"symbol","title":"presentationController(forPresented:presenting:source:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forPresented"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"presenting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate\/presentationController(forPresented:presenting:source:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentationControllerForPresentedViewController:presentingViewController:sourceViewController:"}],"url":"\/documentation\/divar\/panmodalpresentationdelegate\/presentationcontroller(forpresented:presenting:source:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate\/animationController(forDismissed:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate\/animationController(forPresented:presenting:source:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationDelegate\/presentationController(forPresented:presenting:source:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationDelegate~1animationController(forPresented:presenting:source:)\/title","value":"animationControllerForPresentedController:presentingController:sourceController:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationDelegate~1animationController(forPresented:presenting:source:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animationControllerForPresentedController:presentingController:sourceController:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationDelegate~1animationController(forDismissed:)\/title","value":"animationControllerForDismissedController:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationDelegate~1animationController(forDismissed:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animationControllerForDismissedController:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationDelegate\/title","value":"PanModalPresentationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationDelegate\/fragments","value":[{"kind":"identifier","text":"PanModalPresentationDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationDelegate~1presentationController(forPresented:presenting:source:)\/title","value":"presentationControllerForPresentedViewController:presentingViewController:sourceViewController:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationDelegate~1presentationController(forPresented:presenting:source:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentationControllerForPresentedViewController:presentingViewController:sourceViewController:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}