{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchCell"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SwitchTableViewCell","preciseIdentifier":"c:@M@Divar@objc(cs)SwitchTableViewCell","text":"SwitchTableViewCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"switchValueDidChange"},{"kind":"text","text":" "},{"kind":"internalParam","text":"newValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/transformablepriceviewcontroller\/switchcell(_:switchvaluedidchange:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/switchCell(_:switchValueDidChange:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"SwitchTableViewCellDelegate.switchCell(_:switchValueDidChange:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"switchCell(_:switchValueDidChange:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchCell"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SwitchTableViewCell","preciseIdentifier":"c:@M@Divar@objc(cs)SwitchTableViewCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"switchValueDidChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar32TransformablePriceViewControllerC10switchCell_0F14ValueDidChangeyAA011SwitchTabledG0C_SbtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/SwitchTableViewCellDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController":{"role":"symbol","title":"TransformablePriceViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransformablePriceViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TransformablePriceViewController"}],"url":"\/documentation\/divar\/transformablepriceviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/SwitchTableViewCellDelegate-Implementations":{"role":"collectionGroup","title":"SwitchTableViewCellDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/SwitchTableViewCellDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/switchtableviewcelldelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/switchCell(_:switchValueDidChange:)":{"role":"symbol","title":"switchCell(_:switchValueDidChange:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchCell"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SwitchTableViewCell","preciseIdentifier":"c:@M@Divar@objc(cs)SwitchTableViewCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"switchValueDidChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/switchCell(_:switchValueDidChange:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/switchcell(_:switchvaluedidchange:)"},"doc://com.Divar.DivarClient/documentation/Divar/SwitchTableViewCell":{"role":"symbol","title":"SwitchTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SwitchTableViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SwitchTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SwitchTableViewCell"}],"url":"\/documentation\/divar\/switchtableviewcell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TransformablePriceViewController\/title","value":"TransformablePriceViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TransformablePriceViewController\/fragments","value":[{"kind":"identifier","text":"TransformablePriceViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SwitchTableViewCell\/title","value":"SwitchTableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SwitchTableViewCell\/fragments","value":[{"kind":"identifier","text":"SwitchTableViewCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}