{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialCarSpecsHomePage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":" "},{"kind":"internalParam","text":"navigation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController","text":"NavigationController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"CarSpecsHomePage"}]}]},{"kind":"parameters","parameters":[{"name":"navigation","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"NavigationController where flow will push into it"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/carspecsflowcontroller\/initialcarspecshomepage(in:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarSpecsFlowController\/initialCarSpecsHomePage(in:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"this mehtod generate "},{"type":"codeVoice","code":"CarSpecsHomePage"},{"type":"text","text":" which always is root of "},{"type":"codeVoice","code":"CarSpecsFlowController"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialCarSpecsHomePage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"title":"initialCarSpecsHomePage(in:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:5Divar22CarSpecsFlowControllerC07initialbC8HomePage2inSo06UIViewE0CAA010NavigationE0C_tF","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarSpecsFlowController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/CarSpecsFlowController/initialCarSpecsHomePage(in:)":{"role":"symbol","title":"initialCarSpecsHomePage(in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialCarSpecsHomePage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[{"type":"text","text":"this mehtod generate "},{"type":"codeVoice","code":"CarSpecsHomePage"},{"type":"text","text":" which always is root of "},{"type":"codeVoice","code":"CarSpecsFlowController"}],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarSpecsFlowController\/initialCarSpecsHomePage(in:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/carspecsflowcontroller\/initialcarspecshomepage(in:)"},"doc://com.Divar.DivarClient/documentation/Divar/CarSpecsFlowController":{"role":"symbol","title":"CarSpecsFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarSpecsFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarSpecsFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarSpecsFlowController"}],"url":"\/documentation\/divar\/carspecsflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/NavigationController":{"role":"symbol","title":"NavigationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NavigationController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NavigationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NavigationController"}],"url":"\/documentation\/divar\/navigationcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarSpecsFlowController\/title","value":"CarSpecsFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarSpecsFlowController\/fragments","value":[{"kind":"identifier","text":"CarSpecsFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NavigationController\/title","value":"NavigationController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NavigationController\/fragments","value":[{"kind":"identifier","text":"NavigationController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}