{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerRowView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BannerRow","preciseIdentifier":"c:@M@Sonnat@objc(cs)BannerRow"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/bannerrowcollectionviewcell\/bannerrowview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/bannerrowcollectionviewcell\/bannerrowview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BannerRowCollectionViewCell\/bannerRowView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerRowView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BannerRow","preciseIdentifier":"c:@M@Sonnat@objc(cs)BannerRow"},{"kind":"text","text":"!"}],"title":"bannerRowView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)BannerRowCollectionViewCell(py)bannerRowView","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"bannerRowView"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BannerRowCollectionViewCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/BannerRowCollectionViewCell/bannerRowView":{"role":"symbol","title":"bannerRowView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerRowView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BannerRow","preciseIdentifier":"c:@M@Sonnat@objc(cs)BannerRow"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BannerRowCollectionViewCell\/bannerRowView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bannerRowView"}],"url":"\/documentation\/divar\/bannerrowcollectionviewcell\/bannerrowview"},"doc://com.Divar.DivarClient/documentation/Divar/BannerRowCollectionViewCell":{"role":"symbol","title":"BannerRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BannerRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BannerRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BannerRowCollectionViewCell"}],"url":"\/documentation\/divar\/bannerrowcollectionviewcell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"bannerRowView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"bannerRowView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BannerRow","preciseIdentifier":"c:objc(cs)BannerRow"},{"kind":"text","text":" * "},{"kind":"identifier","text":"bannerRowView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BannerRowCollectionViewCell~1bannerRowView\/title","value":"bannerRowView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BannerRowCollectionViewCell~1bannerRowView\/fragments","value":[{"kind":"identifier","text":"bannerRowView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BannerRowCollectionViewCell\/title","value":"BannerRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BannerRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"BannerRowCollectionViewCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}