{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openSupportAndTerms"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MyDivarHolderViewController","text":"MyDivarHolderViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/mydivarholderflowcontroller\/opensupportandterms(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/openSupportAndTerms(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"MyDivarHolderViewControllerDelegate.openSupportAndTerms(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"openSupportAndTerms(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openSupportAndTerms"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MyDivarHolderViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MyDivarHolderViewController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar02MyA20HolderFlowControllerC19openSupportAndTermsyyAA0bac4ViewE0CF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/MyDivarHolderViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderFlowController":{"role":"symbol","title":"MyDivarHolderFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyDivarHolderFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MyDivarHolderFlowController"}],"url":"\/documentation\/divar\/mydivarholderflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderFlowController/openSupportAndTerms(_:)":{"role":"symbol","title":"openSupportAndTerms(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openSupportAndTerms"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MyDivarHolderViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MyDivarHolderViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/openSupportAndTerms(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mydivarholderflowcontroller\/opensupportandterms(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderFlowController/MyDivarHolderViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"MyDivarHolderViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/MyDivarHolderViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/mydivarholderflowcontroller\/mydivarholderviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderViewController":{"role":"symbol","title":"MyDivarHolderViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyDivarHolderViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MyDivarHolderViewController"}],"url":"\/documentation\/divar\/mydivarholderviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MyDivarHolderFlowController\/title","value":"MyDivarHolderFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MyDivarHolderFlowController\/fragments","value":[{"kind":"identifier","text":"MyDivarHolderFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MyDivarHolderViewController\/title","value":"MyDivarHolderViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MyDivarHolderViewController\/fragments","value":[{"kind":"identifier","text":"MyDivarHolderViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}