{"variants":[{"paths":["\/documentation\/divar\/notewithbottombarviewcontroller\/uitextviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/notewithbottombarviewcontroller\/uitextviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController\/UITextViewDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController\/textView(_:shouldChangeTextIn:replacementText:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController\/textViewDidBeginEditing(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController\/textViewDidChange(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController\/textViewDidEndEditing(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"UITextViewDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/NoteWithBottomBarViewController/textViewDidBeginEditing(_:)":{"role":"symbol","title":"textViewDidBeginEditing(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textViewDidBeginEditing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController\/textViewDidBeginEditing(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textViewDidBeginEditing:"}],"url":"\/documentation\/divar\/notewithbottombarviewcontroller\/textviewdidbeginediting(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/NoteWithBottomBarViewController/textView(_:shouldChangeTextIn:replacementText:)":{"role":"symbol","title":"textView(_:shouldChangeTextIn:replacementText:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldChangeTextIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replacementText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController\/textView(_:shouldChangeTextIn:replacementText:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textView:shouldChangeTextInRange:replacementText:"}],"url":"\/documentation\/divar\/notewithbottombarviewcontroller\/textview(_:shouldchangetextin:replacementtext:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/NoteWithBottomBarViewController/textViewDidEndEditing(_:)":{"role":"symbol","title":"textViewDidEndEditing(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textViewDidEndEditing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController\/textViewDidEndEditing(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textViewDidEndEditing:"}],"url":"\/documentation\/divar\/notewithbottombarviewcontroller\/textviewdidendediting(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/NoteWithBottomBarViewController":{"role":"symbol","title":"NoteWithBottomBarViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NoteWithBottomBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NoteWithBottomBarViewController"}],"url":"\/documentation\/divar\/notewithbottombarviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/NoteWithBottomBarViewController/textViewDidChange(_:)":{"role":"symbol","title":"textViewDidChange(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textViewDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController\/textViewDidChange(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textViewDidChange:"}],"url":"\/documentation\/divar\/notewithbottombarviewcontroller\/textviewdidchange(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController\/textView(_:shouldChangeTextIn:replacementText:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController\/textViewDidBeginEditing(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController\/textViewDidChange(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController\/textViewDidEndEditing(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteWithBottomBarViewController~1textViewDidBeginEditing(_:)\/title","value":"textViewDidBeginEditing:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteWithBottomBarViewController~1textViewDidBeginEditing(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textViewDidBeginEditing:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteWithBottomBarViewController~1textView(_:shouldChangeTextIn:replacementText:)\/title","value":"textView:shouldChangeTextInRange:replacementText:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteWithBottomBarViewController~1textView(_:shouldChangeTextIn:replacementText:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textView:shouldChangeTextInRange:replacementText:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteWithBottomBarViewController~1textViewDidEndEditing(_:)\/title","value":"textViewDidEndEditing:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteWithBottomBarViewController~1textViewDidEndEditing(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textViewDidEndEditing:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteWithBottomBarViewController\/title","value":"NoteWithBottomBarViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteWithBottomBarViewController\/fragments","value":[{"kind":"identifier","text":"NoteWithBottomBarViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteWithBottomBarViewController~1textViewDidChange(_:)\/title","value":"textViewDidChange:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteWithBottomBarViewController~1textViewDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textViewDidChange:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}