{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"happyImageTap"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/raterowview\/happyimagetap()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/raterowview\/happyimagetap()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/happyImageTap()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"happyImageTap"},{"kind":"text","text":"()"}],"title":"happyImageTap()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Divar@objc(cs)RateRowView(im)happyImageTap","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"happyImageTap"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/RateRowView/happyImageTap()":{"role":"symbol","title":"happyImageTap()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"happyImageTap"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/happyImageTap()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"happyImageTap"}],"url":"\/documentation\/divar\/raterowview\/happyimagetap()"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/RateRowView":{"role":"symbol","title":"RateRowView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RateRowView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RateRowView"}],"url":"\/documentation\/divar\/raterowview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"happyImageTap"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"happyImageTap"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"happyImageTap"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1happyImageTap()\/title","value":"happyImageTap"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1happyImageTap()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"happyImageTap"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView\/title","value":"RateRowView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView\/fragments","value":[{"kind":"identifier","text":"RateRowView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}