{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setInterval"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"callback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JSValue","preciseIdentifier":"c:objc(cs)JSValue"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"ms"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/jscorewindowprotocol\/setinterval(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/jscorewindowprotocol\/setinterval(_:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreWindowProtocol\/setInterval(_:_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"setInterval::"}],"role":"symbol","title":"setInterval(_:_:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setInterval"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"JSValue","preciseIdentifier":"c:objc(cs)JSValue"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"symbolKind":"method","externalID":"c:objc(pl)JSCoreWindow(cm)setInterval::","required":true,"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"7.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreWindowProtocol"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/JSCoreWindowProtocol":{"role":"symbol","title":"JSCoreWindowProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSCoreWindowProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreWindowProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JSCoreWindowProtocol"}],"url":"\/documentation\/divar\/jscorewindowprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/JSCoreWindowProtocol/setInterval(_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"setInterval::"}],"role":"symbol","title":"setInterval(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setInterval"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"JSValue","preciseIdentifier":"c:objc(cs)JSValue"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreWindowProtocol\/setInterval(_:_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/jscorewindowprotocol\/setinterval(_:_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"setInterval::"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setInterval::"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"setInterval:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"JSValue","preciseIdentifier":"c:objc(cs)JSValue"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"callback"},{"kind":"text","text":" "},{"kind":"identifier","text":":"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":")"},{"kind":"internalParam","text":"ms"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreWindowProtocol\/title","value":"JSCoreWindow"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreWindowProtocol\/fragments","value":[{"kind":"identifier","text":"JSCoreWindow"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreWindowProtocol~1setInterval(_:_:)\/title","value":"setInterval::"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreWindowProtocol~1setInterval(_:_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setInterval::"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}