{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mapView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKMapView","preciseIdentifier":"c:objc(cs)MKMapView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"regionDidChangeAnimated"},{"kind":"text","text":" "},{"kind":"internalParam","text":"_"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/mapselectorviewcontroller\/mapview(_:regiondidchangeanimated:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/mapselectorviewcontroller\/mapview(_:regiondidchangeanimated:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapSelectorViewController\/mapView(_:regionDidChangeAnimated:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"MKMapViewDelegate.mapView(_:regionDidChangeAnimated:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"mapView:regionDidChangeAnimated:"}],"role":"symbol","title":"mapView(_:regionDidChangeAnimated:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapView","preciseIdentifier":"c:objc(cs)MKMapView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"regionDidChangeAnimated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@Divar@objc(cs)MapSelectorViewController(im)mapView:regionDidChangeAnimated:","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapSelectorViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapSelectorViewController\/MKMapViewDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/MapSelectorViewController/mapView(_:regionDidChangeAnimated:)":{"role":"symbol","title":"mapView(_:regionDidChangeAnimated:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapView","preciseIdentifier":"c:objc(cs)MKMapView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"regionDidChangeAnimated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapSelectorViewController\/mapView(_:regionDidChangeAnimated:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mapView:regionDidChangeAnimated:"}],"url":"\/documentation\/divar\/mapselectorviewcontroller\/mapview(_:regiondidchangeanimated:)"},"doc://com.Divar.DivarClient/documentation/Divar/MapSelectorViewController/MKMapViewDelegate-Implementations":{"role":"collectionGroup","title":"MKMapViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapSelectorViewController\/MKMapViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/mapselectorviewcontroller\/mkmapviewdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/MapSelectorViewController":{"role":"symbol","title":"MapSelectorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapSelectorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapSelectorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapSelectorViewController"}],"url":"\/documentation\/divar\/mapselectorviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"mapView:regionDidChangeAnimated:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mapView:regionDidChangeAnimated:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"mapView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapView","preciseIdentifier":"c:objc(cs)MKMapView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"mapView"},{"kind":"text","text":" "},{"kind":"identifier","text":"regionDidChangeAnimated:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"_"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapSelectorViewController~1mapView(_:regionDidChangeAnimated:)\/title","value":"mapView:regionDidChangeAnimated:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapSelectorViewController~1mapView(_:regionDidChangeAnimated:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mapView:regionDidChangeAnimated:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapSelectorViewController\/title","value":"MapSelectorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapSelectorViewController\/fragments","value":[{"kind":"identifier","text":"MapSelectorViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}