{"variants":[{"paths":["\/documentation\/divar\/mapselectorviewcontroller\/mkmapviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/mapselectorviewcontroller\/mkmapviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapSelectorViewController\/MKMapViewDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapSelectorViewController\/mapView(_:regionDidChangeAnimated:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"MKMapViewDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapSelectorViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/MapSelectorViewController/mapView(_:regionDidChangeAnimated:)":{"role":"symbol","title":"mapView(_:regionDidChangeAnimated:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapView","preciseIdentifier":"c:objc(cs)MKMapView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"regionDidChangeAnimated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapSelectorViewController\/mapView(_:regionDidChangeAnimated:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mapView:regionDidChangeAnimated:"}],"url":"\/documentation\/divar\/mapselectorviewcontroller\/mapview(_:regiondidchangeanimated:)"},"doc://com.Divar.DivarClient/documentation/Divar/MapSelectorViewController":{"role":"symbol","title":"MapSelectorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapSelectorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapSelectorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapSelectorViewController"}],"url":"\/documentation\/divar\/mapselectorviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapSelectorViewController\/mapView(_:regionDidChangeAnimated:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapSelectorViewController~1mapView(_:regionDidChangeAnimated:)\/title","value":"mapView:regionDidChangeAnimated:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapSelectorViewController~1mapView(_:regionDidChangeAnimated:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mapView:regionDidChangeAnimated:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapSelectorViewController\/title","value":"MapSelectorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapSelectorViewController\/fragments","value":[{"kind":"identifier","text":"MapSelectorViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}