{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptJobsTermsAndConditionBeforeRegister"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BeforeRegisterTermsAndConditionsVC","preciseIdentifier":"c:@M@Divar@objc(cs)BeforeRegisterTermsAndConditionsVC","text":"BeforeRegisterTermsAndConditionsVC"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/jobsflowcontroller\/acceptjobstermsandconditionbeforeregister(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JobsFlowController\/acceptJobsTermsAndConditionBeforeRegister(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","title":"acceptJobsTermsAndConditionBeforeRegister(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptJobsTermsAndConditionBeforeRegister"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BeforeRegisterTermsAndConditionsVC","preciseIdentifier":"c:@M@Divar@objc(cs)BeforeRegisterTermsAndConditionsVC"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"s:5Divar18JobsFlowControllerC06acceptB31TermsAndConditionBeforeRegisteryyAA0ijfG12ConditionsVCCSgF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JobsFlowController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/JobsFlowController":{"role":"symbol","title":"JobsFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JobsFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JobsFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JobsFlowController"}],"url":"\/documentation\/divar\/jobsflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BeforeRegisterTermsAndConditionsVC":{"role":"symbol","title":"BeforeRegisterTermsAndConditionsVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BeforeRegisterTermsAndConditionsVC"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BeforeRegisterTermsAndConditionsVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BeforeRegisterTermsAndConditionsVC"}],"url":"\/documentation\/divar\/beforeregistertermsandconditionsvc"},"doc://com.Divar.DivarClient/documentation/Divar/JobsFlowController/acceptJobsTermsAndConditionBeforeRegister(_:)":{"role":"symbol","title":"acceptJobsTermsAndConditionBeforeRegister(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptJobsTermsAndConditionBeforeRegister"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BeforeRegisterTermsAndConditionsVC","preciseIdentifier":"c:@M@Divar@objc(cs)BeforeRegisterTermsAndConditionsVC"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JobsFlowController\/acceptJobsTermsAndConditionBeforeRegister(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/jobsflowcontroller\/acceptjobstermsandconditionbeforeregister(_:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JobsFlowController\/title","value":"JobsFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JobsFlowController\/fragments","value":[{"kind":"identifier","text":"JobsFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BeforeRegisterTermsAndConditionsVC\/title","value":"BeforeRegisterTermsAndConditionsVC"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BeforeRegisterTermsAndConditionsVC\/fragments","value":[{"kind":"identifier","text":"BeforeRegisterTermsAndConditionsVC"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}