{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imagePickerImageSelectionCell"},{"kind":"text","text":"("},{"kind":"externalParam","text":"didRequestEditingFor"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell","preciseIdentifier":"c:@M@Divar@objc(cs)ImagePickerImageSelectionCell","text":"ImagePickerImageSelectionCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"atIndexPath"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/imagepickerimageselection\/imagepickerimageselectioncell(didrequesteditingfor:atindexpath:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelection\/imagePickerImageSelectionCell(didRequestEditingFor:atIndexPath:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ImagePickerImageSelectionCellDelegate.imagePickerImageSelectionCell(didRequestEditingFor:atIndexPath:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"imagePickerImageSelectionCell(didRequestEditingFor:atIndexPath:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imagePickerImageSelectionCell"},{"kind":"text","text":"("},{"kind":"externalParam","text":"didRequestEditingFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImagePickerImageSelectionCell","preciseIdentifier":"c:@M@Divar@objc(cs)ImagePickerImageSelectionCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"atIndexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar011ImagePickerB9SelectionC05imagecbD4Cell20didRequestEditingFor11atIndexPathyAA0bcbdF0C_10Foundation0lM0VtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelection","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelection\/ImagePickerImageSelectionCellDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ImagePickerImageSelection/ImagePickerImageSelectionCellDelegate-Implementations":{"role":"collectionGroup","title":"ImagePickerImageSelectionCellDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelection\/ImagePickerImageSelectionCellDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/imagepickerimageselection\/imagepickerimageselectioncelldelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/ImagePickerImageSelectionCell":{"deprecated":true,"role":"symbol","title":"ImagePickerImageSelectionCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImagePickerImageSelectionCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImagePickerImageSelectionCell"}],"url":"\/documentation\/divar\/imagepickerimageselectioncell"},"doc://com.Divar.DivarClient/documentation/Divar/ImagePickerImageSelection/imagePickerImageSelectionCell(didRequestEditingFor:atIndexPath:)":{"role":"symbol","title":"imagePickerImageSelectionCell(didRequestEditingFor:atIndexPath:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imagePickerImageSelectionCell"},{"kind":"text","text":"("},{"kind":"externalParam","text":"didRequestEditingFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImagePickerImageSelectionCell","preciseIdentifier":"c:@M@Divar@objc(cs)ImagePickerImageSelectionCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"atIndexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelection\/imagePickerImageSelectionCell(didRequestEditingFor:atIndexPath:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/imagepickerimageselection\/imagepickerimageselectioncell(didrequesteditingfor:atindexpath:)"},"doc://com.Divar.DivarClient/documentation/Divar/ImagePickerImageSelection":{"deprecated":true,"role":"symbol","title":"ImagePickerImageSelection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImagePickerImageSelection"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImagePickerImageSelection"}],"url":"\/documentation\/divar\/imagepickerimageselection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelectionCell\/title","value":"ImagePickerImageSelectionCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelectionCell\/fragments","value":[{"kind":"identifier","text":"ImagePickerImageSelectionCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelection\/title","value":"ImagePickerImageSelection"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelection\/fragments","value":[{"kind":"identifier","text":"ImagePickerImageSelection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}