{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"flowControl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController","preciseIdentifier":"c:@M@Divar@objc(cs)ChatFlowController","text":"ChatFlowController"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/conversationsviewcontroller\/flowcontrol"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConversationsViewController\/flowControl","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"flowControl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatFlowController","preciseIdentifier":"c:@M@Divar@objc(cs)ChatFlowController"},{"kind":"text","text":"?"}],"title":"flowControl","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar27ConversationsViewControllerC11flowControlAA08ChatFlowD0CSgvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConversationsViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ChatFlowController":{"role":"symbol","title":"ChatFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatFlowController"}],"url":"\/documentation\/divar\/chatflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/ConversationsViewController":{"role":"symbol","title":"ConversationsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConversationsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationsViewController"}],"url":"\/documentation\/divar\/conversationsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ConversationsViewController/flowControl":{"role":"symbol","title":"flowControl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"flowControl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatFlowController","preciseIdentifier":"c:@M@Divar@objc(cs)ChatFlowController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConversationsViewController\/flowControl","kind":"symbol","type":"topic","url":"\/documentation\/divar\/conversationsviewcontroller\/flowcontrol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatFlowController\/title","value":"ChatFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatFlowController\/fragments","value":[{"kind":"identifier","text":"ChatFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ConversationsViewController\/title","value":"ConversationsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ConversationsViewController\/fragments","value":[{"kind":"identifier","text":"ConversationsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}