{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDeleteVC"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MultiConversationDeleteViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MultiConversationDeleteViewController","text":"MultiConversationDeleteViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestDeleteConversations"},{"kind":"text","text":" "},{"kind":"internalParam","text":"conversations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatConversationTable","preciseIdentifier":"s:5Divar21ChatConversationTableV","text":"ChatConversationTable"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/conversationsviewcontroller\/multideletevc(_:didrequestdeleteconversations:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConversationsViewController\/multiDeleteVC(_:didRequestDeleteConversations:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"MultiConversationDeleteDelegate.multiDeleteVC(_:didRequestDeleteConversations:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"multiDeleteVC(_:didRequestDeleteConversations:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDeleteVC"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MultiConversationDeleteViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MultiConversationDeleteViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestDeleteConversations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatConversationTable","preciseIdentifier":"s:5Divar21ChatConversationTableV"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"s:5Divar27ConversationsViewControllerC13multiDeleteVC_010didRequestfB0yAA017MultiConversationfcD0C_SayAA04ChatK5TableVGtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConversationsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConversationsViewController\/MultiConversationDeleteDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ConversationsViewController":{"role":"symbol","title":"ConversationsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConversationsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationsViewController"}],"url":"\/documentation\/divar\/conversationsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatConversationTable":{"role":"symbol","title":"ChatConversationTable","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatConversationTable"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatConversationTable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatConversationTable"}],"url":"\/documentation\/divar\/chatconversationtable"},"doc://com.Divar.DivarClient/documentation/Divar/ConversationsViewController/multiDeleteVC(_:didRequestDeleteConversations:)":{"role":"symbol","title":"multiDeleteVC(_:didRequestDeleteConversations:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDeleteVC"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MultiConversationDeleteViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MultiConversationDeleteViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestDeleteConversations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatConversationTable","preciseIdentifier":"s:5Divar21ChatConversationTableV"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConversationsViewController\/multiDeleteVC(_:didRequestDeleteConversations:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/conversationsviewcontroller\/multideletevc(_:didrequestdeleteconversations:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/MultiConversationDeleteViewController":{"role":"symbol","title":"MultiConversationDeleteViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiConversationDeleteViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MultiConversationDeleteViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MultiConversationDeleteViewController"}],"url":"\/documentation\/divar\/multiconversationdeleteviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ConversationsViewController/MultiConversationDeleteDelegate-Implementations":{"role":"collectionGroup","title":"MultiConversationDeleteDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConversationsViewController\/MultiConversationDeleteDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/conversationsviewcontroller\/multiconversationdeletedelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ConversationsViewController\/title","value":"ConversationsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ConversationsViewController\/fragments","value":[{"kind":"identifier","text":"ConversationsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MultiConversationDeleteViewController\/title","value":"MultiConversationDeleteViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MultiConversationDeleteViewController\/fragments","value":[{"kind":"identifier","text":"MultiConversationDeleteViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}