{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedTableView","preciseIdentifier":"c:@M@Divar@objc(cs)AdvancedTableView","text":"AdvancedTableView"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/conversationsviewcontroller\/tableview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/conversationsviewcontroller\/tableview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConversationsViewController\/tableView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdvancedTableView","preciseIdentifier":"c:@M@Divar@objc(cs)AdvancedTableView"},{"kind":"text","text":"!"}],"title":"tableView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)ConversationsViewController(py)tableView","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"tableView"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConversationsViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ConversationsViewController/tableView":{"role":"symbol","title":"tableView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdvancedTableView","preciseIdentifier":"c:@M@Divar@objc(cs)AdvancedTableView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConversationsViewController\/tableView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView"}],"url":"\/documentation\/divar\/conversationsviewcontroller\/tableview"},"doc://com.Divar.DivarClient/documentation/Divar/ConversationsViewController":{"role":"symbol","title":"ConversationsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConversationsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationsViewController"}],"url":"\/documentation\/divar\/conversationsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedTableView":{"role":"symbol","title":"AdvancedTableView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdvancedTableView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedTableView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdvancedTableView"}],"url":"\/documentation\/divar\/advancedtableview"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"tableView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"tableView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedTableView","preciseIdentifier":"c:@M@Divar@objc(cs)AdvancedTableView","text":"AdvancedTableView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"tableView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ConversationsViewController~1tableView\/title","value":"tableView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ConversationsViewController~1tableView\/fragments","value":[{"kind":"identifier","text":"tableView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ConversationsViewController\/title","value":"ConversationsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ConversationsViewController\/fragments","value":[{"kind":"identifier","text":"ConversationsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedTableView\/title","value":"AdvancedTableView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedTableView\/fragments","value":[{"kind":"identifier","text":"AdvancedTableView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}