{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"submitButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SecondaryButton","preciseIdentifier":"c:@M@Divar@objc(cs)SecondaryButton","text":"SecondaryButton"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/feedbackalertviewcontroller\/submitbutton"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/feedbackalertviewcontroller\/submitbutton"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/submitButton","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"submitButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SecondaryButton","preciseIdentifier":"c:@M@Divar@objc(cs)SecondaryButton"},{"kind":"text","text":"!"}],"title":"submitButton","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)FeedbackAlertViewController(py)submitButton","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"submitButton"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController":{"role":"symbol","title":"FeedbackAlertViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeedbackAlertViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeedbackAlertViewController"}],"url":"\/documentation\/divar\/feedbackalertviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SecondaryButton":{"role":"symbol","title":"SecondaryButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SecondaryButton"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SecondaryButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SecondaryButton"}],"url":"\/documentation\/divar\/secondarybutton"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController/submitButton":{"role":"symbol","title":"submitButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"submitButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SecondaryButton","preciseIdentifier":"c:@M@Divar@objc(cs)SecondaryButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/submitButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"submitButton"}],"url":"\/documentation\/divar\/feedbackalertviewcontroller\/submitbutton"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"submitButton"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"submitButton"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SecondaryButton","preciseIdentifier":"c:@M@Divar@objc(cs)SecondaryButton","text":"SecondaryButton"},{"kind":"text","text":" * "},{"kind":"identifier","text":"submitButton"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController\/title","value":"FeedbackAlertViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController\/fragments","value":[{"kind":"identifier","text":"FeedbackAlertViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SecondaryButton\/title","value":"SecondaryButton"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SecondaryButton\/fragments","value":[{"kind":"identifier","text":"SecondaryButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController~1submitButton\/title","value":"submitButton"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController~1submitButton\/fragments","value":[{"kind":"identifier","text":"submitButton"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}