{"variants":[{"paths":["\/documentation\/divar\/feedbackalertviewcontroller\/uicollectionviewdelegateflowlayout-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/feedbackalertviewcontroller\/uicollectionviewdelegateflowlayout-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/UICollectionViewDelegateFlowLayout-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/collectionView(_:layout:insetForSectionAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/collectionView(_:layout:minimumInteritemSpacingForSectionAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/collectionView(_:layout:sizeForItemAt:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"UICollectionViewDelegateFlowLayout Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController/collectionView(_:layout:insetForSectionAt:)":{"role":"symbol","title":"collectionView(_:layout:insetForSectionAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":", "},{"kind":"externalParam","text":"insetForSectionAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/collectionView(_:layout:insetForSectionAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:layout:insetForSectionAtIndex:"}],"url":"\/documentation\/divar\/feedbackalertviewcontroller\/collectionview(_:layout:insetforsectionat:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController/collectionView(_:layout:minimumInteritemSpacingForSectionAt:)":{"role":"symbol","title":"collectionView(_:layout:minimumInteritemSpacingForSectionAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minimumInteritemSpacingForSectionAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/collectionView(_:layout:minimumInteritemSpacingForSectionAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:layout:minimumInteritemSpacingForSectionAtIndex:"}],"url":"\/documentation\/divar\/feedbackalertviewcontroller\/collectionview(_:layout:minimuminteritemspacingforsectionat:)"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController/collectionView(_:layout:sizeForItemAt:)":{"role":"symbol","title":"collectionView(_:layout:sizeForItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sizeForItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/collectionView(_:layout:sizeForItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:layout:sizeForItemAtIndexPath:"}],"url":"\/documentation\/divar\/feedbackalertviewcontroller\/collectionview(_:layout:sizeforitemat:)"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController":{"role":"symbol","title":"FeedbackAlertViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeedbackAlertViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeedbackAlertViewController"}],"url":"\/documentation\/divar\/feedbackalertviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/collectionView(_:layout:insetForSectionAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/collectionView(_:layout:minimumInteritemSpacingForSectionAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/collectionView(_:layout:sizeForItemAt:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController~1collectionView(_:layout:insetForSectionAt:)\/title","value":"collectionView:layout:insetForSectionAtIndex:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController~1collectionView(_:layout:insetForSectionAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:layout:insetForSectionAtIndex:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController~1collectionView(_:layout:minimumInteritemSpacingForSectionAt:)\/title","value":"collectionView:layout:minimumInteritemSpacingForSectionAtIndex:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController~1collectionView(_:layout:minimumInteritemSpacingForSectionAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:layout:minimumInteritemSpacingForSectionAtIndex:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController~1collectionView(_:layout:sizeForItemAt:)\/title","value":"collectionView:layout:sizeForItemAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController~1collectionView(_:layout:sizeForItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:layout:sizeForItemAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController\/title","value":"FeedbackAlertViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController\/fragments","value":[{"kind":"identifier","text":"FeedbackAlertViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}