{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"kind":"internalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController","preciseIdentifier":"c:@M@Divar@objc(cs)PanModalPresentationController","text":"PanModalPresentationController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/PresentationState","preciseIdentifier":"s:5Divar30PanModalPresentationControllerC0D5StateO","text":"PresentationState"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/feedbackalertviewcontroller\/willtransition(to:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/willTransition(to:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"PanModalPresentable.willTransition(to:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" inherits "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"willTransition(to:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PanModalPresentationController","preciseIdentifier":"c:@M@Divar@objc(cs)PanModalPresentationController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"PresentationState","preciseIdentifier":"s:5Divar30PanModalPresentationControllerC0D5StateO"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar19PanModalPresentablePAASo16UIViewControllerCRbzrlE14willTransition2toyAA0bc12PresentationF0C0J5StateO_tF::SYNTHESIZED::c:@M@Divar@objc(cs)FeedbackAlertViewController","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/PanModalPresentable-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController/PanModalPresentable-Implementations":{"role":"collectionGroup","title":"PanModalPresentable Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/PanModalPresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/feedbackalertviewcontroller\/panmodalpresentable-implementations"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationController":{"role":"symbol","title":"PanModalPresentationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresentationController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresentationController"}],"url":"\/documentation\/divar\/panmodalpresentationcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController":{"role":"symbol","title":"FeedbackAlertViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeedbackAlertViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeedbackAlertViewController"}],"url":"\/documentation\/divar\/feedbackalertviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController/willTransition(to:)":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" inherits "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"willTransition(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PanModalPresentationController","preciseIdentifier":"c:@M@Divar@objc(cs)PanModalPresentationController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"PresentationState","preciseIdentifier":"s:5Divar30PanModalPresentationControllerC0D5StateO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/willTransition(to:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/feedbackalertviewcontroller\/willtransition(to:)"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationController/PresentationState":{"role":"symbol","title":"PanModalPresentationController.PresentationState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationState"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/PresentationState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PresentationState"}],"url":"\/documentation\/divar\/panmodalpresentationcontroller\/presentationstate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationController\/title","value":"PanModalPresentationController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationController\/fragments","value":[{"kind":"identifier","text":"PanModalPresentationController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController\/title","value":"FeedbackAlertViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController\/fragments","value":[{"kind":"identifier","text":"FeedbackAlertViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}