{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegateAndDataSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListDelegateAndDataSource","preciseIdentifier":"c:@M@Divar@objc(cs)TagListDelegateAndDataSource","text":"TagListDelegateAndDataSource"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/taglistview\/delegateanddatasource"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListView\/delegateAndDataSource","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegateAndDataSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagListDelegateAndDataSource","preciseIdentifier":"c:@M@Divar@objc(cs)TagListDelegateAndDataSource"},{"kind":"text","text":"?"}],"title":"delegateAndDataSource","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar11TagListViewC21delegateAndDataSourceAA0bc8DelegatefgH0CSgvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListView"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/TagListDelegateAndDataSource":{"role":"symbol","title":"TagListDelegateAndDataSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListDelegateAndDataSource"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListDelegateAndDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagListDelegateAndDataSource"}],"url":"\/documentation\/divar\/taglistdelegateanddatasource"},"doc://com.Divar.DivarClient/documentation/Divar/TagListView/delegateAndDataSource":{"role":"symbol","title":"delegateAndDataSource","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegateAndDataSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagListDelegateAndDataSource","preciseIdentifier":"c:@M@Divar@objc(cs)TagListDelegateAndDataSource"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListView\/delegateAndDataSource","kind":"symbol","type":"topic","url":"\/documentation\/divar\/taglistview\/delegateanddatasource"},"doc://com.Divar.DivarClient/documentation/Divar/TagListView":{"role":"symbol","title":"TagListView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagListView"}],"url":"\/documentation\/divar\/taglistview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListDelegateAndDataSource\/title","value":"TagListDelegateAndDataSource"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListDelegateAndDataSource\/fragments","value":[{"kind":"identifier","text":"TagListDelegateAndDataSource"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListView\/title","value":"TagListView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListView\/fragments","value":[{"kind":"identifier","text":"TagListView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}