{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstTimeVC"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FirstTimeViewController","preciseIdentifier":"c:@M@Divar@objc(cs)FirstTimeViewController","text":"FirstTimeViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectCity"},{"kind":"text","text":" "},{"kind":"internalParam","text":"city"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Place","preciseIdentifier":"s:5Divar5PlaceV","text":"Place"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/mainflowcontroller\/firsttimevc(_:didselectcity:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/firstTimeVC(_:didSelectCity:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"FirstTimeViewControllerDelegate.firstTimeVC(_:didSelectCity:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"firstTimeVC(_:didSelectCity:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstTimeVC"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FirstTimeViewController","preciseIdentifier":"c:@M@Divar@objc(cs)FirstTimeViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectCity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Place","preciseIdentifier":"s:5Divar5PlaceV"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar18MainFlowControllerC11firstTimeVC_13didSelectCityyAA05Firstf4ViewD0C_AA5PlaceVtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/FirstTimeViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController":{"role":"symbol","title":"MainFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MainFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MainFlowController"}],"url":"\/documentation\/divar\/mainflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/firstTimeVC(_:didSelectCity:)":{"role":"symbol","title":"firstTimeVC(_:didSelectCity:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstTimeVC"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FirstTimeViewController","preciseIdentifier":"c:@M@Divar@objc(cs)FirstTimeViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectCity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Place","preciseIdentifier":"s:5Divar5PlaceV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/firstTimeVC(_:didSelectCity:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/firsttimevc(_:didselectcity:)"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/FirstTimeViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"FirstTimeViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/FirstTimeViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/firsttimeviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/FirstTimeViewController":{"role":"symbol","title":"FirstTimeViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FirstTimeViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FirstTimeViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FirstTimeViewController"}],"url":"\/documentation\/divar\/firsttimeviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/Place":{"role":"symbol","title":"Place","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Place"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Place","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Place"}],"url":"\/documentation\/divar\/place"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController\/title","value":"MainFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController\/fragments","value":[{"kind":"identifier","text":"MainFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FirstTimeViewController\/title","value":"FirstTimeViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FirstTimeViewController\/fragments","value":[{"kind":"identifier","text":"FirstTimeViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}