{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleChatNewMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"note"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/mainflowcontroller\/handlechatnewmessage(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/mainflowcontroller\/handlechatnewmessage(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/handleChatNewMessage(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"handleChatNewMessage:"}],"role":"symbol","title":"handleChatNewMessage(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleChatNewMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@Divar@objc(cs)MainFlowController(im)handleChatNewMessage:","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController":{"role":"symbol","title":"MainFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MainFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MainFlowController"}],"url":"\/documentation\/divar\/mainflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/handleChatNewMessage(_:)":{"role":"symbol","title":"handleChatNewMessage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleChatNewMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/handleChatNewMessage(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"handleChatNewMessage:"}],"url":"\/documentation\/divar\/mainflowcontroller\/handlechatnewmessage(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"handleChatNewMessage:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleChatNewMessage:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"handleChatNewMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"note"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController\/title","value":"MainFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController\/fragments","value":[{"kind":"identifier","text":"MainFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController~1handleChatNewMessage(_:)\/title","value":"handleChatNewMessage:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController~1handleChatNewMessage(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleChatNewMessage:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}