{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"splashView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView","preciseIdentifier":"c:@M@Divar@objc(cs)DivarSplashView","text":"DivarSplashView"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/mainflowcontroller\/splashview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/splashView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"splashView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DivarSplashView","preciseIdentifier":"c:@M@Divar@objc(cs)DivarSplashView"},{"kind":"text","text":"?"}],"title":"splashView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar18MainFlowControllerC10splashViewAA0a6SplashF0CSgvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/DivarSplashView":{"role":"symbol","title":"DivarSplashView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DivarSplashView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DivarSplashView"}],"url":"\/documentation\/divar\/divarsplashview"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController":{"role":"symbol","title":"MainFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MainFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MainFlowController"}],"url":"\/documentation\/divar\/mainflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/splashView":{"role":"symbol","title":"splashView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"splashView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DivarSplashView","preciseIdentifier":"c:@M@Divar@objc(cs)DivarSplashView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/splashView","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/splashview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DivarSplashView\/title","value":"DivarSplashView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DivarSplashView\/fragments","value":[{"kind":"identifier","text":"DivarSplashView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController\/title","value":"MainFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController\/fragments","value":[{"kind":"identifier","text":"MainFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}