{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabBarController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tabBarController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITabBarController","preciseIdentifier":"c:objc(cs)UITabBarController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldSelect"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/mainflowcontroller\/tabbarcontroller(_:shouldselect:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/mainflowcontroller\/tabbarcontroller(_:shouldselect:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/tabBarController(_:shouldSelect:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UITabBarControllerDelegate.tabBarController(_:shouldSelect:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"tabBarController:shouldSelectViewController:"}],"role":"symbol","title":"tabBarController(_:shouldSelect:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabBarController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITabBarController","preciseIdentifier":"c:objc(cs)UITabBarController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldSelect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","externalID":"c:@CM@Divar@objc(cs)MainFlowController(im)tabBarController:shouldSelectViewController:","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/UITabBarControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/tabBarController(_:shouldSelect:)":{"role":"symbol","title":"tabBarController(_:shouldSelect:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabBarController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITabBarController","preciseIdentifier":"c:objc(cs)UITabBarController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldSelect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/tabBarController(_:shouldSelect:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tabBarController:shouldSelectViewController:"}],"url":"\/documentation\/divar\/mainflowcontroller\/tabbarcontroller(_:shouldselect:)"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/UITabBarControllerDelegate-Implementations":{"role":"collectionGroup","title":"UITabBarControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/UITabBarControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/uitabbarcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController":{"role":"symbol","title":"MainFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MainFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MainFlowController"}],"url":"\/documentation\/divar\/mainflowcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"tabBarController:shouldSelectViewController:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tabBarController:shouldSelectViewController:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"tabBarController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITabBarController","preciseIdentifier":"c:objc(cs)UITabBarController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"tabBarController"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldSelectViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController~1tabBarController(_:shouldSelect:)\/title","value":"tabBarController:shouldSelectViewController:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController~1tabBarController(_:shouldSelect:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tabBarController:shouldSelectViewController:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController\/title","value":"MainFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController\/fragments","value":[{"kind":"identifier","text":"MainFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}