{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userRegisterationChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"notification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/mainflowcontroller\/userregisterationchanged(notification:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/mainflowcontroller\/userregisterationchanged(notification:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/userRegisterationChanged(notification:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userRegisterationChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"notification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":")"}],"title":"userRegisterationChanged(notification:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Divar@objc(cs)MainFlowController(im)userRegisterationChangedWithNotification:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"userRegisterationChangedWithNotification:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/userRegisterationChanged(notification:)":{"role":"symbol","title":"userRegisterationChanged(notification:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userRegisterationChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"notification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/userRegisterationChanged(notification:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userRegisterationChangedWithNotification:"}],"url":"\/documentation\/divar\/mainflowcontroller\/userregisterationchanged(notification:)"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController":{"role":"symbol","title":"MainFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MainFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MainFlowController"}],"url":"\/documentation\/divar\/mainflowcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"userRegisterationChangedWithNotification:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userRegisterationChangedWithNotification:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"userRegisterationChangedWithNotification:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"notification"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController~1userRegisterationChanged(notification:)\/title","value":"userRegisterationChangedWithNotification:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController~1userRegisterationChanged(notification:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userRegisterationChangedWithNotification:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController\/title","value":"MainFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController\/fragments","value":[{"kind":"identifier","text":"MainFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}