{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryButtonClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"splitButtonVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SplitButtonBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SplitButtonBarViewController","text":"SplitButtonBarViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/multiconversationdeleteviewcontroller\/primarybuttonclicked(_:action:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MultiConversationDeleteViewController\/primaryButtonClicked(_:action:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"SplitButtonBarViewControllerDelegate.primaryButtonClicked(_:action:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"primaryButtonClicked(_:action:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryButtonClicked"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SplitButtonBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SplitButtonBarViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"s:5Divar37MultiConversationDeleteViewControllerC20primaryButtonClicked_6actionyAA05Splith3BareF0C_0A14InterfaceSwift14Widgets_ActionVSgtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MultiConversationDeleteViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MultiConversationDeleteViewController\/SplitButtonBarViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/MultiConversationDeleteViewController/primaryButtonClicked(_:action:)":{"role":"symbol","title":"primaryButtonClicked(_:action:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryButtonClicked"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SplitButtonBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SplitButtonBarViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MultiConversationDeleteViewController\/primaryButtonClicked(_:action:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/multiconversationdeleteviewcontroller\/primarybuttonclicked(_:action:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/MultiConversationDeleteViewController":{"role":"symbol","title":"MultiConversationDeleteViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiConversationDeleteViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MultiConversationDeleteViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MultiConversationDeleteViewController"}],"url":"\/documentation\/divar\/multiconversationdeleteviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MultiConversationDeleteViewController/SplitButtonBarViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"SplitButtonBarViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MultiConversationDeleteViewController\/SplitButtonBarViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/multiconversationdeleteviewcontroller\/splitbuttonbarviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/SplitButtonBarViewController":{"role":"symbol","title":"SplitButtonBarViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SplitButtonBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SplitButtonBarViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SplitButtonBarViewController"}],"url":"\/documentation\/divar\/splitbuttonbarviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MultiConversationDeleteViewController\/title","value":"MultiConversationDeleteViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MultiConversationDeleteViewController\/fragments","value":[{"kind":"identifier","text":"MultiConversationDeleteViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SplitButtonBarViewController\/title","value":"SplitButtonBarViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SplitButtonBarViewController\/fragments","value":[{"kind":"identifier","text":"SplitButtonBarViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}