{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReportPost"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostReportDescriptionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)PostReportDescriptionViewController","text":"PostReportDescriptionViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/postarchiveviewcontroller\/didreportpost(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/didReportPost(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"PostReportDescriptionViewControllerDelegate.didReportPost(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"didReportPost(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReportPost"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PostReportDescriptionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)PostReportDescriptionViewController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar25PostArchiveViewControllerC09didReportB0yyAA0bg11DescriptiondE0CF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/PostReportDescriptionViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PostReportDescriptionViewController":{"role":"symbol","title":"PostReportDescriptionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostReportDescriptionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostReportDescriptionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostReportDescriptionViewController"}],"url":"\/documentation\/divar\/postreportdescriptionviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController":{"role":"symbol","title":"PostArchiveViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostArchiveViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostArchiveViewController"}],"url":"\/documentation\/divar\/postarchiveviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/PostReportDescriptionViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"PostReportDescriptionViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/PostReportDescriptionViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/postreportdescriptionviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/didReportPost(_:)":{"role":"symbol","title":"didReportPost(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReportPost"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PostReportDescriptionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)PostReportDescriptionViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/didReportPost(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/didreportpost(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostReportDescriptionViewController\/title","value":"PostReportDescriptionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostReportDescriptionViewController\/fragments","value":[{"kind":"identifier","text":"PostReportDescriptionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController\/title","value":"PostArchiveViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController\/fragments","value":[{"kind":"identifier","text":"PostArchiveViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}