{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HeaderBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)HeaderBarViewController","text":"HeaderBarViewController"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/postarchiveviewcontroller\/headervc"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/headerVC","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HeaderBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)HeaderBarViewController"}],"title":"headerVC","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar25PostArchiveViewControllerC8headerVCAA09HeaderBardE0Cvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController":{"role":"symbol","title":"PostArchiveViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostArchiveViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostArchiveViewController"}],"url":"\/documentation\/divar\/postarchiveviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/HeaderBarViewController":{"role":"symbol","title":"HeaderBarViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeaderBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HeaderBarViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeaderBarViewController"}],"url":"\/documentation\/divar\/headerbarviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/headerVC":{"role":"symbol","title":"headerVC","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HeaderBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)HeaderBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/headerVC","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/headervc"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController\/title","value":"PostArchiveViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController\/fragments","value":[{"kind":"identifier","text":"PostArchiveViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1HeaderBarViewController\/title","value":"HeaderBarViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1HeaderBarViewController\/fragments","value":[{"kind":"identifier","text":"HeaderBarViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}