{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestShowChildren"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"singleMultiVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleMultiBaseViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SingleMultiBaseViewController","text":"SingleMultiBaseViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"children"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleMultiModel","preciseIdentifier":"s:5Divar16SingleMultiModelV","text":"SingleMultiModel"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/postarchiveviewcontroller\/requestshowchildren(_:children:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/requestShowChildren(_:children:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"SingleMultiBaseViewControllerDelegate.requestShowChildren(_:children:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"requestShowChildren(_:children:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestShowChildren"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SingleMultiBaseViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SingleMultiBaseViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"children"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SingleMultiModel","preciseIdentifier":"s:5Divar16SingleMultiModelV"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"s:5Divar25PostArchiveViewControllerC19requestShowChildren_8childrenyAA015SingleMultiBasedE0C_SayAA0jK5ModelVGtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/SingleMultiBaseViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/SingleMultiBaseViewController":{"role":"symbol","title":"SingleMultiBaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleMultiBaseViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleMultiBaseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SingleMultiBaseViewController"}],"url":"\/documentation\/divar\/singlemultibaseviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SingleMultiModel":{"role":"symbol","title":"SingleMultiModel","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleMultiModel"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleMultiModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SingleMultiModel"}],"url":"\/documentation\/divar\/singlemultimodel"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController":{"role":"symbol","title":"PostArchiveViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostArchiveViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostArchiveViewController"}],"url":"\/documentation\/divar\/postarchiveviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/SingleMultiBaseViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"SingleMultiBaseViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/SingleMultiBaseViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/singlemultibaseviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/requestShowChildren(_:children:)":{"role":"symbol","title":"requestShowChildren(_:children:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestShowChildren"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SingleMultiBaseViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SingleMultiBaseViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"children"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SingleMultiModel","preciseIdentifier":"s:5Divar16SingleMultiModelV"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/requestShowChildren(_:children:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/requestshowchildren(_:children:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleMultiBaseViewController\/title","value":"SingleMultiBaseViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleMultiBaseViewController\/fragments","value":[{"kind":"identifier","text":"SingleMultiBaseViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController\/title","value":"PostArchiveViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController\/fragments","value":[{"kind":"identifier","text":"PostArchiveViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}