{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchResultView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchResultRow","preciseIdentifier":"c:@M@Sonnat@objc(cs)SearchResultRow"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/searchresultrowtablecell\/searchresultview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/searchresultrowtablecell\/searchresultview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchResultRowTableCell\/searchResultView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchResultView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchResultRow","preciseIdentifier":"c:@M@Sonnat@objc(cs)SearchResultRow"},{"kind":"text","text":"!"}],"title":"searchResultView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)SearchResultRowTableCell(py)searchResultView","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"searchResultView"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchResultRowTableCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/SearchResultRowTableCell":{"role":"symbol","title":"SearchResultRowTableCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchResultRowTableCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchResultRowTableCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchResultRowTableCell"}],"url":"\/documentation\/divar\/searchresultrowtablecell"},"doc://com.Divar.DivarClient/documentation/Divar/SearchResultRowTableCell/searchResultView":{"role":"symbol","title":"searchResultView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchResultView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchResultRow","preciseIdentifier":"c:@M@Sonnat@objc(cs)SearchResultRow"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchResultRowTableCell\/searchResultView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"searchResultView"}],"url":"\/documentation\/divar\/searchresultrowtablecell\/searchresultview"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"searchResultView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"searchResultView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"SearchResultRow","preciseIdentifier":"c:objc(cs)SearchResultRow"},{"kind":"text","text":" * "},{"kind":"identifier","text":"searchResultView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchResultRowTableCell\/title","value":"SearchResultRowTableCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchResultRowTableCell\/fragments","value":[{"kind":"identifier","text":"SearchResultRowTableCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchResultRowTableCell~1searchResultView\/title","value":"searchResultView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchResultRowTableCell~1searchResultView\/fragments","value":[{"kind":"identifier","text":"searchResultView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}