{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedFilterViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedFilterViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedFilterViewController","text":"WidgetBasedFilterViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetTag","preciseIdentifier":"s:5Divar9WidgetTagV","text":"WidgetTag"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/bulkladderbaseflowcontroller\/widgetbasedfilterviewcontroller(_:data:tag:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BulkLadderBaseFlowController\/widgetBasedFilterViewController(_:data:tag:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"WidgetBasedFilterViewControllerDelegate.widgetBasedFilterViewController(_:data:tag:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"widgetBasedFilterViewController(_:data:tag:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedFilterViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedFilterViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedFilterViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WidgetTag","preciseIdentifier":"s:5Divar9WidgetTagV"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar28BulkLadderBaseFlowControllerC021widgetBasedFilterViewF0_4data3tagyAA06WidgethijF0C_SDySSypGAA0M3TagVtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BulkLadderBaseFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BulkLadderBaseFlowController\/WidgetBasedFilterViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/BulkLadderBaseFlowController/widgetBasedFilterViewController(_:data:tag:)":{"role":"symbol","title":"widgetBasedFilterViewController(_:data:tag:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedFilterViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedFilterViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedFilterViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WidgetTag","preciseIdentifier":"s:5Divar9WidgetTagV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BulkLadderBaseFlowController\/widgetBasedFilterViewController(_:data:tag:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bulkladderbaseflowcontroller\/widgetbasedfilterviewcontroller(_:data:tag:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/BulkLadderBaseFlowController/WidgetBasedFilterViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"WidgetBasedFilterViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BulkLadderBaseFlowController\/WidgetBasedFilterViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/bulkladderbaseflowcontroller\/widgetbasedfilterviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetTag":{"role":"symbol","title":"WidgetTag","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetTag"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetTag","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetTag"}],"url":"\/documentation\/divar\/widgettag"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedFilterViewController":{"role":"symbol","title":"WidgetBasedFilterViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedFilterViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedFilterViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedFilterViewController"}],"url":"\/documentation\/divar\/widgetbasedfilterviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BulkLadderBaseFlowController":{"role":"symbol","title":"BulkLadderBaseFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BulkLadderBaseFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BulkLadderBaseFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BulkLadderBaseFlowController"}],"url":"\/documentation\/divar\/bulkladderbaseflowcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedFilterViewController\/title","value":"WidgetBasedFilterViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedFilterViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedFilterViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BulkLadderBaseFlowController\/title","value":"BulkLadderBaseFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BulkLadderBaseFlowController\/fragments","value":[{"kind":"identifier","text":"BulkLadderBaseFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}