{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WideButtonViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WideButtonViewController","text":"WideButtonViewController"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/numbertextfieldpagecontroller\/buttonbar"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberTextFieldPageController\/buttonBar","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WideButtonViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WideButtonViewController"}],"title":"buttonBar","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar29NumberTextFieldPageControllerC9buttonBarAA014WideButtonViewF0Cvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberTextFieldPageController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/WideButtonViewController":{"role":"symbol","title":"WideButtonViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WideButtonViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WideButtonViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WideButtonViewController"}],"url":"\/documentation\/divar\/widebuttonviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/NumberTextFieldPageController":{"role":"symbol","title":"NumberTextFieldPageController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NumberTextFieldPageController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberTextFieldPageController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NumberTextFieldPageController"}],"url":"\/documentation\/divar\/numbertextfieldpagecontroller"},"doc://com.Divar.DivarClient/documentation/Divar/NumberTextFieldPageController/buttonBar":{"role":"symbol","title":"buttonBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WideButtonViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WideButtonViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberTextFieldPageController\/buttonBar","kind":"symbol","type":"topic","url":"\/documentation\/divar\/numbertextfieldpagecontroller\/buttonbar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WideButtonViewController\/title","value":"WideButtonViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WideButtonViewController\/fragments","value":[{"kind":"identifier","text":"WideButtonViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NumberTextFieldPageController\/title","value":"NumberTextFieldPageController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NumberTextFieldPageController\/fragments","value":[{"kind":"identifier","text":"NumberTextFieldPageController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}