{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stackViewBottomConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/numbertextfieldpagecontroller\/stackviewbottomconstraint"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/numbertextfieldpagecontroller\/stackviewbottomconstraint"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberTextFieldPageController\/stackViewBottomConstraint","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stackViewBottomConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"!"}],"title":"stackViewBottomConstraint","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)NumberTextFieldPageController(py)stackViewBottomConstraint","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"stackViewBottomConstraint"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberTextFieldPageController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/NumberTextFieldPageController":{"role":"symbol","title":"NumberTextFieldPageController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NumberTextFieldPageController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberTextFieldPageController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NumberTextFieldPageController"}],"url":"\/documentation\/divar\/numbertextfieldpagecontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/NumberTextFieldPageController/stackViewBottomConstraint":{"role":"symbol","title":"stackViewBottomConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stackViewBottomConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberTextFieldPageController\/stackViewBottomConstraint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stackViewBottomConstraint"}],"url":"\/documentation\/divar\/numbertextfieldpagecontroller\/stackviewbottomconstraint"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"stackViewBottomConstraint"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"stackViewBottomConstraint"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":" * "},{"kind":"identifier","text":"stackViewBottomConstraint"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NumberTextFieldPageController\/title","value":"NumberTextFieldPageController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NumberTextFieldPageController\/fragments","value":[{"kind":"identifier","text":"NumberTextFieldPageController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NumberTextFieldPageController~1stackViewBottomConstraint\/title","value":"stackViewBottomConstraint"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NumberTextFieldPageController~1stackViewBottomConstraint\/fragments","value":[{"kind":"identifier","text":"stackViewBottomConstraint"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}