{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/postsviewcontroller\/refresh()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/postsviewcontroller\/refresh()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/refresh()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"()"}],"title":"refresh()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@Divar@objc(cs)PostsViewController(im)refresh","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"refresh"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController/refresh()":{"role":"symbol","title":"refresh()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/refresh()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"refresh"}],"url":"\/documentation\/divar\/postsviewcontroller\/refresh()"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController":{"role":"symbol","title":"PostsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostsViewController"}],"url":"\/documentation\/divar\/postsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"refresh"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refresh"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostsViewController~1refresh()\/title","value":"refresh"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostsViewController~1refresh()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refresh"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostsViewController\/title","value":"PostsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostsViewController\/fragments","value":[{"kind":"identifier","text":"PostsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}