{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/customuiactivity\/activityimage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/customuiactivity\/activityimage"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/activityImage","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"title":"activityImage","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)CustomUIActivity(py)activityImage","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"activityImage"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivity/activityImage":{"role":"symbol","title":"activityImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/activityImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"activityImage"}],"url":"\/documentation\/divar\/customuiactivity\/activityimage"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivity":{"role":"symbol","title":"CustomUIActivity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomUIActivity"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomUIActivity"}],"url":"\/documentation\/divar\/customuiactivity"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"activityImage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"activityImage"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" * "},{"kind":"identifier","text":"activityImage"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity~1activityImage\/title","value":"activityImage"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity~1activityImage\/fragments","value":[{"kind":"identifier","text":"activityImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity\/title","value":"CustomUIActivity"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity\/fragments","value":[{"kind":"identifier","text":"CustomUIActivity"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}