{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityCategory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIActivity","preciseIdentifier":"c:objc(cs)UIActivity"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Category","preciseIdentifier":"c:@E@UIActivityCategory"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/customuiactivity\/activitycategory"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/customuiactivity\/activitycategory"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/activityCategory","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityCategory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIActivity","preciseIdentifier":"c:objc(cs)UIActivity"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Category","preciseIdentifier":"c:@E@UIActivityCategory"}],"title":"activityCategory","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)CustomUIActivity(cpy)activityCategory","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"activityCategory"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivity/activityCategory":{"role":"symbol","title":"activityCategory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityCategory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIActivity","preciseIdentifier":"c:objc(cs)UIActivity"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Category","preciseIdentifier":"c:@E@UIActivityCategory"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/activityCategory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"activityCategory"}],"url":"\/documentation\/divar\/customuiactivity\/activitycategory"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivity":{"role":"symbol","title":"CustomUIActivity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomUIActivity"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomUIActivity"}],"url":"\/documentation\/divar\/customuiactivity"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"activityCategory"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"activityCategory"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIActivityCategory","preciseIdentifier":"c:@E@UIActivityCategory"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityCategory"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity~1activityCategory\/title","value":"activityCategory"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity~1activityCategory\/fragments","value":[{"kind":"identifier","text":"activityCategory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity\/title","value":"CustomUIActivity"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity\/fragments","value":[{"kind":"identifier","text":"CustomUIActivity"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}