{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPerform"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withActivityItems"},{"kind":"text","text":" "},{"kind":"internalParam","text":"activityItems"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/customuiactivity\/canperform(withactivityitems:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/customuiactivity\/canperform(withactivityitems:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/canPerform(withActivityItems:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPerform"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withActivityItems"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"canPerform(withActivityItems:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Divar@objc(cs)CustomUIActivity(im)canPerformWithActivityItems:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"canPerformWithActivityItems:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivity/canPerform(withActivityItems:)":{"role":"symbol","title":"canPerform(withActivityItems:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPerform"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withActivityItems"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/canPerform(withActivityItems:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canPerformWithActivityItems:"}],"url":"\/documentation\/divar\/customuiactivity\/canperform(withactivityitems:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivity":{"role":"symbol","title":"CustomUIActivity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomUIActivity"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomUIActivity"}],"url":"\/documentation\/divar\/customuiactivity"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"canPerformWithActivityItems:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canPerformWithActivityItems:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"canPerformWithActivityItems:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"activityItems"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity~1canPerform(withActivityItems:)\/title","value":"canPerformWithActivityItems:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity~1canPerform(withActivityItems:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canPerformWithActivityItems:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity\/title","value":"CustomUIActivity"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity\/fragments","value":[{"kind":"identifier","text":"CustomUIActivity"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}