{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepare"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withActivityItems"},{"kind":"text","text":" "},{"kind":"internalParam","text":"activityItems"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/customuiactivity\/prepare(withactivityitems:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/customuiactivity\/prepare(withactivityitems:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/prepare(withActivityItems:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepare"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withActivityItems"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"title":"prepare(withActivityItems:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Divar@objc(cs)CustomUIActivity(im)prepareWithActivityItems:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"prepareWithActivityItems:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivity/prepare(withActivityItems:)":{"role":"symbol","title":"prepare(withActivityItems:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepare"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withActivityItems"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/prepare(withActivityItems:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prepareWithActivityItems:"}],"url":"\/documentation\/divar\/customuiactivity\/prepare(withactivityitems:)"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivity":{"role":"symbol","title":"CustomUIActivity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomUIActivity"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomUIActivity"}],"url":"\/documentation\/divar\/customuiactivity"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"prepareWithActivityItems:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareWithActivityItems:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"prepareWithActivityItems:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"activityItems"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity~1prepare(withActivityItems:)\/title","value":"prepareWithActivityItems:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity~1prepare(withActivityItems:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareWithActivityItems:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity\/title","value":"CustomUIActivity"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity\/fragments","value":[{"kind":"identifier","text":"CustomUIActivity"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}