{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteAgent"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/createandeditoperatorviewcontroller\/deleteagent()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/createandeditoperatorviewcontroller\/deleteagent()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CreateAndEditOperatorViewController\/deleteAgent()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteAgent"},{"kind":"text","text":"()"}],"title":"deleteAgent()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Divar@objc(cs)CreateAndEditOperatorViewController(im)deleteAgent","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"deleteAgent"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CreateAndEditOperatorViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/CreateAndEditOperatorViewController/deleteAgent()":{"role":"symbol","title":"deleteAgent()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteAgent"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CreateAndEditOperatorViewController\/deleteAgent()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteAgent"}],"url":"\/documentation\/divar\/createandeditoperatorviewcontroller\/deleteagent()"},"doc://com.Divar.DivarClient/documentation/Divar/CreateAndEditOperatorViewController":{"role":"symbol","title":"CreateAndEditOperatorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateAndEditOperatorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CreateAndEditOperatorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CreateAndEditOperatorViewController"}],"url":"\/documentation\/divar\/createandeditoperatorviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"deleteAgent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteAgent"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"deleteAgent"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CreateAndEditOperatorViewController~1deleteAgent()\/title","value":"deleteAgent"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CreateAndEditOperatorViewController~1deleteAgent()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteAgent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CreateAndEditOperatorViewController\/title","value":"CreateAndEditOperatorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CreateAndEditOperatorViewController\/fragments","value":[{"kind":"identifier","text":"CreateAndEditOperatorViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}