{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scoreRowView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScoreRowView","preciseIdentifier":"c:@M@Divar@objc(cs)ScoreRowView","text":"ScoreRowView"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/scorerowcollectionviewcell\/scorerowview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/scorerowcollectionviewcell\/scorerowview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScoreRowCollectionViewCell\/scoreRowView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scoreRowView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ScoreRowView","preciseIdentifier":"c:@M@Divar@objc(cs)ScoreRowView"},{"kind":"text","text":"!"}],"title":"scoreRowView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)ScoreRowCollectionViewCell(py)scoreRowView","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"scoreRowView"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScoreRowCollectionViewCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ScoreRowCollectionViewCell/scoreRowView":{"role":"symbol","title":"scoreRowView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scoreRowView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ScoreRowView","preciseIdentifier":"c:@M@Divar@objc(cs)ScoreRowView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScoreRowCollectionViewCell\/scoreRowView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scoreRowView"}],"url":"\/documentation\/divar\/scorerowcollectionviewcell\/scorerowview"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/ScoreRowView":{"role":"symbol","title":"ScoreRowView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScoreRowView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScoreRowView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScoreRowView"}],"url":"\/documentation\/divar\/scorerowview"},"doc://com.Divar.DivarClient/documentation/Divar/ScoreRowCollectionViewCell":{"role":"symbol","title":"ScoreRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScoreRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScoreRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScoreRowCollectionViewCell"}],"url":"\/documentation\/divar\/scorerowcollectionviewcell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"scoreRowView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"scoreRowView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScoreRowView","preciseIdentifier":"c:@M@Divar@objc(cs)ScoreRowView","text":"ScoreRowView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"scoreRowView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScoreRowCollectionViewCell~1scoreRowView\/title","value":"scoreRowView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScoreRowCollectionViewCell~1scoreRowView\/fragments","value":[{"kind":"identifier","text":"scoreRowView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScoreRowView\/title","value":"ScoreRowView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScoreRowView\/fragments","value":[{"kind":"identifier","text":"ScoreRowView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScoreRowCollectionViewCell\/title","value":"ScoreRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScoreRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"ScoreRowCollectionViewCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}