{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"bar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarPositioning","preciseIdentifier":"c:objc(pl)UIBarPositioning"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIBarPosition","preciseIdentifier":"c:@E@UIBarPosition"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/tabbedpageviewcontroller\/position(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/tabbedpageviewcontroller\/position(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TabbedPageViewController\/position(for:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIBarPositioningDelegate.position(for:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarPositioning","preciseIdentifier":"c:objc(pl)UIBarPositioning"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIBarPosition","preciseIdentifier":"c:@E@UIBarPosition"}],"title":"position(for:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@Divar@objc(cs)TabbedPageViewController(im)positionForBar:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"positionForBar:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TabbedPageViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TabbedPageViewController\/UIBarPositioningDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/TabbedPageViewController":{"role":"symbol","title":"TabbedPageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TabbedPageViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TabbedPageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TabbedPageViewController"}],"url":"\/documentation\/divar\/tabbedpageviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/TabbedPageViewController/position(for:)":{"role":"symbol","title":"position(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarPositioning","preciseIdentifier":"c:objc(pl)UIBarPositioning"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIBarPosition","preciseIdentifier":"c:@E@UIBarPosition"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TabbedPageViewController\/position(for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"positionForBar:"}],"url":"\/documentation\/divar\/tabbedpageviewcontroller\/position(for:)"},"doc://com.Divar.DivarClient/documentation/Divar/TabbedPageViewController/UIBarPositioningDelegate-Implementations":{"role":"collectionGroup","title":"UIBarPositioningDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TabbedPageViewController\/UIBarPositioningDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/tabbedpageviewcontroller\/uibarpositioningdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"positionForBar:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"positionForBar:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIBarPosition","preciseIdentifier":"c:@E@UIBarPosition"},{"kind":"text","text":") "},{"kind":"identifier","text":"positionForBar:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<UIBarPositioning>","preciseIdentifier":"c:Qoobjc(pl)UIBarPositioning"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"bar"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TabbedPageViewController\/title","value":"TabbedPageViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TabbedPageViewController\/fragments","value":[{"kind":"identifier","text":"TabbedPageViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TabbedPageViewController~1position(for:)\/title","value":"positionForBar:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TabbedPageViewController~1position(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"positionForBar:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}