{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabsViewHolder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIToolbar","preciseIdentifier":"c:objc(cs)UIToolbar"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/tabbedpageviewcontroller\/tabsviewholder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/tabbedpageviewcontroller\/tabsviewholder"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TabbedPageViewController\/tabsViewHolder","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabsViewHolder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIToolbar","preciseIdentifier":"c:objc(cs)UIToolbar"},{"kind":"text","text":"!"}],"title":"tabsViewHolder","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)TabbedPageViewController(py)tabsViewHolder","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"tabsViewHolder"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TabbedPageViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/TabbedPageViewController":{"role":"symbol","title":"TabbedPageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TabbedPageViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TabbedPageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TabbedPageViewController"}],"url":"\/documentation\/divar\/tabbedpageviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/TabbedPageViewController/tabsViewHolder":{"role":"symbol","title":"tabsViewHolder","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabsViewHolder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIToolbar","preciseIdentifier":"c:objc(cs)UIToolbar"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TabbedPageViewController\/tabsViewHolder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tabsViewHolder"}],"url":"\/documentation\/divar\/tabbedpageviewcontroller\/tabsviewholder"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"tabsViewHolder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"tabsViewHolder"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIToolbar","preciseIdentifier":"c:objc(cs)UIToolbar"},{"kind":"text","text":" * "},{"kind":"identifier","text":"tabsViewHolder"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TabbedPageViewController\/title","value":"TabbedPageViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TabbedPageViewController\/fragments","value":[{"kind":"identifier","text":"TabbedPageViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TabbedPageViewController~1tabsViewHolder\/title","value":"tabsViewHolder"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TabbedPageViewController~1tabsViewHolder\/fragments","value":[{"kind":"identifier","text":"tabsViewHolder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}