{"variants":[{"paths":["\/documentation\/divar\/tabbedpageviewcontroller\/uibarpositioningdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/tabbedpageviewcontroller\/uibarpositioningdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TabbedPageViewController\/UIBarPositioningDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TabbedPageViewController\/position(for:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"UIBarPositioningDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TabbedPageViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/TabbedPageViewController/position(for:)":{"role":"symbol","title":"position(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarPositioning","preciseIdentifier":"c:objc(pl)UIBarPositioning"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIBarPosition","preciseIdentifier":"c:@E@UIBarPosition"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TabbedPageViewController\/position(for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"positionForBar:"}],"url":"\/documentation\/divar\/tabbedpageviewcontroller\/position(for:)"},"doc://com.Divar.DivarClient/documentation/Divar/TabbedPageViewController":{"role":"symbol","title":"TabbedPageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TabbedPageViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TabbedPageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TabbedPageViewController"}],"url":"\/documentation\/divar\/tabbedpageviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TabbedPageViewController\/position(for:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TabbedPageViewController~1position(for:)\/title","value":"positionForBar:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TabbedPageViewController~1position(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"positionForBar:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TabbedPageViewController\/title","value":"TabbedPageViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TabbedPageViewController\/fragments","value":[{"kind":"identifier","text":"TabbedPageViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}