{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"indicatorView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GaugeView","preciseIdentifier":"c:@M@Divar@objc(cs)GaugeView","text":"GaugeView"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/gaugechartitemcollectionviewcell\/indicatorview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/gaugechartitemcollectionviewcell\/indicatorview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GaugeChartItemCollectionViewCell\/indicatorView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"indicatorView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GaugeView","preciseIdentifier":"c:@M@Divar@objc(cs)GaugeView"},{"kind":"text","text":"!"}],"title":"indicatorView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)GaugeChartItemCollectionViewCell(py)indicatorView","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"indicatorView"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GaugeChartItemCollectionViewCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/GaugeChartItemCollectionViewCell":{"role":"symbol","title":"GaugeChartItemCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GaugeChartItemCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GaugeChartItemCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GaugeChartItemCollectionViewCell"}],"url":"\/documentation\/divar\/gaugechartitemcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/GaugeChartItemCollectionViewCell/indicatorView":{"role":"symbol","title":"indicatorView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"indicatorView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GaugeView","preciseIdentifier":"c:@M@Divar@objc(cs)GaugeView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GaugeChartItemCollectionViewCell\/indicatorView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"indicatorView"}],"url":"\/documentation\/divar\/gaugechartitemcollectionviewcell\/indicatorview"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/GaugeView":{"role":"symbol","title":"GaugeView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GaugeView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GaugeView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GaugeView"}],"url":"\/documentation\/divar\/gaugeview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"indicatorView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"indicatorView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GaugeView","preciseIdentifier":"c:@M@Divar@objc(cs)GaugeView","text":"GaugeView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"indicatorView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GaugeChartItemCollectionViewCell\/title","value":"GaugeChartItemCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GaugeChartItemCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"GaugeChartItemCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GaugeChartItemCollectionViewCell~1indicatorView\/title","value":"indicatorView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GaugeChartItemCollectionViewCell~1indicatorView\/fragments","value":[{"kind":"identifier","text":"indicatorView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GaugeView\/title","value":"GaugeView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GaugeView\/fragments","value":[{"kind":"identifier","text":"GaugeView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}