{"variants":[{"paths":["\/documentation\/divar\/abstracttableviewcontroller\/uitableviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/abstracttableviewcontroller\/uitableviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/UITableViewDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/tableView(_:didDeselectRowAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/tableView(_:didSelectRowAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/tableView(_:estimatedHeightForRowAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/tableView(_:heightForRowAt:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"UITableViewDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController/tableView(_:didDeselectRowAt:)":{"role":"symbol","title":"tableView(_:didDeselectRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDeselectRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/tableView(_:didDeselectRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:didDeselectRowAtIndexPath:"}],"url":"\/documentation\/divar\/abstracttableviewcontroller\/tableview(_:diddeselectrowat:)"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController":{"role":"symbol","title":"AbstractTableViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractTableViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AbstractTableViewController"}],"url":"\/documentation\/divar\/abstracttableviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController/tableView(_:heightForRowAt:)":{"role":"symbol","title":"tableView(_:heightForRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"heightForRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/tableView(_:heightForRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:heightForRowAtIndexPath:"}],"url":"\/documentation\/divar\/abstracttableviewcontroller\/tableview(_:heightforrowat:)"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController/tableView(_:didSelectRowAt:)":{"role":"symbol","title":"tableView(_:didSelectRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/tableView(_:didSelectRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:didSelectRowAtIndexPath:"}],"url":"\/documentation\/divar\/abstracttableviewcontroller\/tableview(_:didselectrowat:)"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController/tableView(_:estimatedHeightForRowAt:)":{"role":"symbol","title":"tableView(_:estimatedHeightForRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"estimatedHeightForRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/tableView(_:estimatedHeightForRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:estimatedHeightForRowAtIndexPath:"}],"url":"\/documentation\/divar\/abstracttableviewcontroller\/tableview(_:estimatedheightforrowat:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/tableView(_:didDeselectRowAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/tableView(_:didSelectRowAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/tableView(_:estimatedHeightForRowAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/tableView(_:heightForRowAt:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController~1tableView(_:didDeselectRowAt:)\/title","value":"tableView:didDeselectRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController~1tableView(_:didDeselectRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:didDeselectRowAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController\/title","value":"AbstractTableViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController\/fragments","value":[{"kind":"identifier","text":"AbstractTableViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController~1tableView(_:heightForRowAt:)\/title","value":"tableView:heightForRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController~1tableView(_:heightForRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:heightForRowAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController~1tableView(_:didSelectRowAt:)\/title","value":"tableView:didSelectRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController~1tableView(_:didSelectRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:didSelectRowAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController~1tableView(_:estimatedHeightForRowAt:)\/title","value":"tableView:estimatedHeightForRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController~1tableView(_:estimatedHeightForRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:estimatedHeightForRowAtIndexPath:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}