{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"continue"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userActivity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUserActivity","preciseIdentifier":"c:objc(cs)NSUserActivity"},{"kind":"text","text":", "},{"kind":"externalParam","text":"restorationHandler"},{"kind":"text","text":" "},{"kind":"internalParam","text":"_"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (["},{"kind":"typeIdentifier","text":"UIUserActivityRestoring","preciseIdentifier":"c:objc(pl)UIUserActivityRestoring"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/appdelegate\/application(_:continue:restorationhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/appdelegate\/application(_:continue:restorationhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:continue:restorationHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIApplicationDelegate.application(_:continue:restorationHandler:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"continue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUserActivity","preciseIdentifier":"c:objc(cs)NSUserActivity"},{"kind":"text","text":", "},{"kind":"externalParam","text":"restorationHandler"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","text":"UIUserActivityRestoring","preciseIdentifier":"c:objc(pl)UIUserActivityRestoring"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"application(_:continue:restorationHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@Divar@objc(cs)AppDelegate(im)application:continueUserActivity:restorationHandler:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"application:continueUserActivity:restorationHandler:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/UIApplicationDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/application(_:continue:restorationHandler:)":{"role":"symbol","title":"application(_:continue:restorationHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"continue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUserActivity","preciseIdentifier":"c:objc(cs)NSUserActivity"},{"kind":"text","text":", "},{"kind":"externalParam","text":"restorationHandler"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","text":"UIUserActivityRestoring","preciseIdentifier":"c:objc(pl)UIUserActivityRestoring"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:continue:restorationHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"application:continueUserActivity:restorationHandler:"}],"url":"\/documentation\/divar\/appdelegate\/application(_:continue:restorationhandler:)"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate":{"role":"symbol","title":"AppDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppDelegate"}],"url":"\/documentation\/divar\/appdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/UIApplicationDelegate-Implementations":{"role":"collectionGroup","title":"UIApplicationDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/UIApplicationDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/appdelegate\/uiapplicationdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"application:continueUserActivity:restorationHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:continueUserActivity:restorationHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"application:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"_"},{"kind":"text","text":" "},{"kind":"identifier","text":"continueUserActivity:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUserActivity","preciseIdentifier":"c:objc(cs)NSUserActivity"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"userActivity"},{"kind":"text","text":" "},{"kind":"identifier","text":"restorationHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSArray<id<UIUserActivityRestoring>> *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"_"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1application(_:continue:restorationHandler:)\/title","value":"application:continueUserActivity:restorationHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1application(_:continue:restorationHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:continueUserActivity:restorationHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate\/title","value":"AppDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate\/fragments","value":[{"kind":"identifier","text":"AppDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}