{"variants":[{"paths":["\/documentation\/divar\/appdelegate\/uiapplicationdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/appdelegate\/uiapplicationdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/UIApplicationDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:continue:restorationHandler:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:didFailToRegisterForRemoteNotificationsWithError:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:didRegisterForRemoteNotificationsWithDeviceToken:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:open:options:)"],"generated":true},{"title":"Type Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/main()"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"UIApplicationDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)":{"role":"symbol","title":"application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveRemoteNotification"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"fetchCompletionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UIBackgroundFetchResult","preciseIdentifier":"c:@E@UIBackgroundFetchResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"application:didReceiveRemoteNotification:fetchCompletionHandler:"}],"url":"\/documentation\/divar\/appdelegate\/application(_:didreceiveremotenotification:fetchcompletionhandler:)"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/application(_:didRegisterForRemoteNotificationsWithDeviceToken:)":{"role":"symbol","title":"application(_:didRegisterForRemoteNotificationsWithDeviceToken:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRegisterForRemoteNotificationsWithDeviceToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:didRegisterForRemoteNotificationsWithDeviceToken:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"application:didRegisterForRemoteNotificationsWithDeviceToken:"}],"url":"\/documentation\/divar\/appdelegate\/application(_:didregisterforremotenotificationswithdevicetoken:)"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/application(_:didFailToRegisterForRemoteNotificationsWithError:)":{"role":"symbol","title":"application(_:didFailToRegisterForRemoteNotificationsWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToRegisterForRemoteNotificationsWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:didFailToRegisterForRemoteNotificationsWithError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"application:didFailToRegisterForRemoteNotificationsWithError:"}],"url":"\/documentation\/divar\/appdelegate\/application(_:didfailtoregisterforremotenotificationswitherror:)"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/application(_:open:options:)":{"role":"symbol","title":"application(_:open:options:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"open"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"OpenURLOptionsKey","preciseIdentifier":"c:@T@UIApplicationOpenURLOptionsKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:open:options:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"application:openURL:options:"}],"url":"\/documentation\/divar\/appdelegate\/application(_:open:options:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate":{"role":"symbol","title":"AppDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppDelegate"}],"url":"\/documentation\/divar\/appdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/application(_:continue:restorationHandler:)":{"role":"symbol","title":"application(_:continue:restorationHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"continue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUserActivity","preciseIdentifier":"c:objc(cs)NSUserActivity"},{"kind":"text","text":", "},{"kind":"externalParam","text":"restorationHandler"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","text":"UIUserActivityRestoring","preciseIdentifier":"c:objc(pl)UIUserActivityRestoring"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:continue:restorationHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"application:continueUserActivity:restorationHandler:"}],"url":"\/documentation\/divar\/appdelegate\/application(_:continue:restorationhandler:)"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/main()":{"role":"symbol","title":"main()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"main"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/main()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/appdelegate\/main()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:continue:restorationHandler:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:didFailToRegisterForRemoteNotificationsWithError:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:didRegisterForRemoteNotificationsWithDeviceToken:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:open:options:)"],"generated":true},{"title":"Type Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/main()"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1application(_:didReceiveRemoteNotification:fetchCompletionHandler:)\/title","value":"application:didReceiveRemoteNotification:fetchCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1application(_:didReceiveRemoteNotification:fetchCompletionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:didReceiveRemoteNotification:fetchCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1application(_:didRegisterForRemoteNotificationsWithDeviceToken:)\/title","value":"application:didRegisterForRemoteNotificationsWithDeviceToken:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1application(_:didRegisterForRemoteNotificationsWithDeviceToken:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:didRegisterForRemoteNotificationsWithDeviceToken:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1application(_:didFailToRegisterForRemoteNotificationsWithError:)\/title","value":"application:didFailToRegisterForRemoteNotificationsWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1application(_:didFailToRegisterForRemoteNotificationsWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:didFailToRegisterForRemoteNotificationsWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1application(_:open:options:)\/title","value":"application:openURL:options:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1application(_:open:options:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:openURL:options:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate\/title","value":"AppDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate\/fragments","value":[{"kind":"identifier","text":"AppDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1application(_:continue:restorationHandler:)\/title","value":"application:continueUserActivity:restorationHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1application(_:continue:restorationHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:continueUserActivity:restorationHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}