{"variants":[{"paths":["\/documentation\/divar\/appdelegate\/unusernotificationcenterdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/appdelegate\/unusernotificationcenterdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/UNUserNotificationCenterDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/userNotificationCenter(_:didReceive:withCompletionHandler:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/userNotificationCenter(_:willPresent:withCompletionHandler:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"UNUserNotificationCenterDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/userNotificationCenter(_:didReceive:withCompletionHandler:)":{"role":"symbol","title":"userNotificationCenter(_:didReceive:withCompletionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userNotificationCenter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UNUserNotificationCenter","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNNotificationResponse","preciseIdentifier":"c:objc(cs)UNNotificationResponse"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCompletionHandler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/userNotificationCenter(_:didReceive:withCompletionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"}],"url":"\/documentation\/divar\/appdelegate\/usernotificationcenter(_:didreceive:withcompletionhandler:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/userNotificationCenter(_:willPresent:withCompletionHandler:)":{"role":"symbol","title":"userNotificationCenter(_:willPresent:withCompletionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userNotificationCenter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UNUserNotificationCenter","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willPresent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCompletionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UNNotificationPresentationOptions","preciseIdentifier":"c:@E@UNNotificationPresentationOptions"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/userNotificationCenter(_:willPresent:withCompletionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userNotificationCenter:willPresentNotification:withCompletionHandler:"}],"url":"\/documentation\/divar\/appdelegate\/usernotificationcenter(_:willpresent:withcompletionhandler:)"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate":{"role":"symbol","title":"AppDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppDelegate"}],"url":"\/documentation\/divar\/appdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/userNotificationCenter(_:didReceive:withCompletionHandler:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/userNotificationCenter(_:willPresent:withCompletionHandler:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1userNotificationCenter(_:didReceive:withCompletionHandler:)\/title","value":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1userNotificationCenter(_:didReceive:withCompletionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1userNotificationCenter(_:willPresent:withCompletionHandler:)\/title","value":"userNotificationCenter:willPresentNotification:withCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1userNotificationCenter(_:willPresent:withCompletionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userNotificationCenter:willPresentNotification:withCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate\/title","value":"AppDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate\/fragments","value":[{"kind":"identifier","text":"AppDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}