{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SwitchView","preciseIdentifier":"c:@M@Divar@objc(cs)SwitchView","text":"SwitchView"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/categorycontroller\/switchview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/categorycontroller\/switchview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CategoryController\/switchView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SwitchView","preciseIdentifier":"c:@M@Divar@objc(cs)SwitchView"},{"kind":"text","text":"!"}],"title":"switchView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)CategoryController(py)switchView","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"switchView"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CategoryController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/CategoryController/switchView":{"role":"symbol","title":"switchView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SwitchView","preciseIdentifier":"c:@M@Divar@objc(cs)SwitchView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CategoryController\/switchView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"switchView"}],"url":"\/documentation\/divar\/categorycontroller\/switchview"},"doc://com.Divar.DivarClient/documentation/Divar/CategoryController":{"role":"symbol","title":"CategoryController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CategoryController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CategoryController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CategoryController"}],"url":"\/documentation\/divar\/categorycontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SwitchView":{"role":"symbol","title":"SwitchView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SwitchView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SwitchView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SwitchView"}],"url":"\/documentation\/divar\/switchview"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"switchView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"switchView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SwitchView","preciseIdentifier":"c:@M@Divar@objc(cs)SwitchView","text":"SwitchView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"switchView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CategoryController~1switchView\/title","value":"switchView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CategoryController~1switchView\/fragments","value":[{"kind":"identifier","text":"switchView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CategoryController\/title","value":"CategoryController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CategoryController\/fragments","value":[{"kind":"identifier","text":"CategoryController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SwitchView\/title","value":"SwitchView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SwitchView\/fragments","value":[{"kind":"identifier","text":"SwitchView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}