{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"string"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromByteCount"},{"kind":"text","text":" "},{"kind":"internalParam","text":"byteCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/custombyteformatter\/string(frombytecount:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/custombyteformatter\/string(frombytecount:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomByteFormatter\/string(fromByteCount:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"string"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromByteCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"string(fromByteCount:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Divar@objc(cs)CustomByteFormatter(im)stringFromByteCount:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"stringFromByteCount:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomByteFormatter"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/CustomByteFormatter/string(fromByteCount:)":{"role":"symbol","title":"string(fromByteCount:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"string"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromByteCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomByteFormatter\/string(fromByteCount:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stringFromByteCount:"}],"url":"\/documentation\/divar\/custombyteformatter\/string(frombytecount:)"},"doc://com.Divar.DivarClient/documentation/Divar/CustomByteFormatter":{"role":"symbol","title":"CustomByteFormatter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomByteFormatter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomByteFormatter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomByteFormatter"}],"url":"\/documentation\/divar\/custombyteformatter"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"stringFromByteCount:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stringFromByteCount:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"stringFromByteCount:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"kind":"text","text":")"},{"kind":"internalParam","text":"byteCount"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomByteFormatter~1string(fromByteCount:)\/title","value":"stringFromByteCount:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomByteFormatter~1string(fromByteCount:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stringFromByteCount:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomByteFormatter\/title","value":"CustomByteFormatter"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomByteFormatter\/fragments","value":[{"kind":"identifier","text":"CustomByteFormatter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}