{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewWillBeginDragging"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"scrollView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/widgetbasedcollectionviewcontroller\/scrollviewwillbegindragging(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/widgetbasedcollectionviewcontroller\/scrollviewwillbegindragging(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController\/scrollViewWillBeginDragging(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIScrollViewDelegate.scrollViewWillBeginDragging(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"scrollViewWillBeginDragging:"}],"role":"symbol","title":"scrollViewWillBeginDragging(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewWillBeginDragging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@Divar@objc(cs)WidgetBasedCollectionViewController(im)scrollViewWillBeginDragging:","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController\/UIScrollViewDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewController/UIScrollViewDelegate-Implementations":{"role":"collectionGroup","title":"UIScrollViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController\/UIScrollViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/widgetbasedcollectionviewcontroller\/uiscrollviewdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewController":{"role":"symbol","title":"WidgetBasedCollectionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedCollectionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedCollectionViewController"}],"url":"\/documentation\/divar\/widgetbasedcollectionviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewController/scrollViewWillBeginDragging(_:)":{"role":"symbol","title":"scrollViewWillBeginDragging(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewWillBeginDragging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController\/scrollViewWillBeginDragging(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewWillBeginDragging:"}],"url":"\/documentation\/divar\/widgetbasedcollectionviewcontroller\/scrollviewwillbegindragging(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"scrollViewWillBeginDragging:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewWillBeginDragging:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"scrollViewWillBeginDragging:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"scrollView"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedCollectionViewController\/title","value":"WidgetBasedCollectionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedCollectionViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedCollectionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedCollectionViewController~1scrollViewWillBeginDragging(_:)\/title","value":"scrollViewWillBeginDragging:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedCollectionViewController~1scrollViewWillBeginDragging(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewWillBeginDragging:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}