{"variants":[{"paths":["\/documentation\/divar\/widgetbasedcollectionviewcontroller\/uiscrollviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/widgetbasedcollectionviewcontroller\/uiscrollviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController\/UIScrollViewDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController\/scrollViewDidScroll(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController\/scrollViewWillBeginDragging(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController\/scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"UIScrollViewDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewController/scrollViewDidScroll(_:)":{"role":"symbol","title":"scrollViewDidScroll(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidScroll"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController\/scrollViewDidScroll(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidScroll:"}],"url":"\/documentation\/divar\/widgetbasedcollectionviewcontroller\/scrollviewdidscroll(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewController/scrollViewWillBeginDragging(_:)":{"role":"symbol","title":"scrollViewWillBeginDragging(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewWillBeginDragging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController\/scrollViewWillBeginDragging(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewWillBeginDragging:"}],"url":"\/documentation\/divar\/widgetbasedcollectionviewcontroller\/scrollviewwillbegindragging(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewController":{"role":"symbol","title":"WidgetBasedCollectionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedCollectionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedCollectionViewController"}],"url":"\/documentation\/divar\/widgetbasedcollectionviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewController/scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)":{"role":"symbol","title":"scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewWillEndDragging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withVelocity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"targetContentOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":">)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController\/scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewWillEndDragging:withVelocity:targetContentOffset:"}],"url":"\/documentation\/divar\/widgetbasedcollectionviewcontroller\/scrollviewwillenddragging(_:withvelocity:targetcontentoffset:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController\/scrollViewDidScroll(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController\/scrollViewWillBeginDragging(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController\/scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedCollectionViewController~1scrollViewDidScroll(_:)\/title","value":"scrollViewDidScroll:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedCollectionViewController~1scrollViewDidScroll(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidScroll:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedCollectionViewController~1scrollViewWillBeginDragging(_:)\/title","value":"scrollViewWillBeginDragging:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedCollectionViewController~1scrollViewWillBeginDragging(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewWillBeginDragging:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedCollectionViewController\/title","value":"WidgetBasedCollectionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedCollectionViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedCollectionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedCollectionViewController~1scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)\/title","value":"scrollViewWillEndDragging:withVelocity:targetContentOffset:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedCollectionViewController~1scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewWillEndDragging:withVelocity:targetContentOffset:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}