{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"commit"},{"kind":"text","text":" "},{"kind":"internalParam","text":"editingStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"EditingStyle","preciseIdentifier":"c:@E@UITableViewCellEditingStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forRowAt"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/netshearsignorelistviewcontroller\/tableview(_:commit:forrowat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/netshearsignorelistviewcontroller\/tableview(_:commit:forrowat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController\/tableView(_:commit:forRowAt:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UITableViewDataSource.tableView(_:commit:forRowAt:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"commit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"EditingStyle","preciseIdentifier":"c:@E@UITableViewCellEditingStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"title":"tableView(_:commit:forRowAt:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@Divar@objc(cs)NetShearsIgnoreListViewController(im)tableView:commitEditingStyle:forRowAtIndexPath:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"tableView:commitEditingStyle:forRowAtIndexPath:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController\/UITableViewDataSource-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/NetShearsIgnoreListViewController":{"role":"symbol","title":"NetShearsIgnoreListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetShearsIgnoreListViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetShearsIgnoreListViewController"}],"url":"\/documentation\/divar\/netshearsignorelistviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/NetShearsIgnoreListViewController/UITableViewDataSource-Implementations":{"role":"collectionGroup","title":"UITableViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController\/UITableViewDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/netshearsignorelistviewcontroller\/uitableviewdatasource-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/NetShearsIgnoreListViewController/tableView(_:commit:forRowAt:)":{"role":"symbol","title":"tableView(_:commit:forRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"commit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"EditingStyle","preciseIdentifier":"c:@E@UITableViewCellEditingStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController\/tableView(_:commit:forRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:commitEditingStyle:forRowAtIndexPath:"}],"url":"\/documentation\/divar\/netshearsignorelistviewcontroller\/tableview(_:commit:forrowat:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"tableView:commitEditingStyle:forRowAtIndexPath:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:commitEditingStyle:forRowAtIndexPath:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"tableView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":" "},{"kind":"identifier","text":"commitEditingStyle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableViewCellEditingStyle","preciseIdentifier":"c:@E@UITableViewCellEditingStyle"},{"kind":"text","text":")"},{"kind":"internalParam","text":"editingStyle"},{"kind":"text","text":" "},{"kind":"identifier","text":"forRowAtIndexPath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NetShearsIgnoreListViewController\/title","value":"NetShearsIgnoreListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NetShearsIgnoreListViewController\/fragments","value":[{"kind":"identifier","text":"NetShearsIgnoreListViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NetShearsIgnoreListViewController~1tableView(_:commit:forRowAt:)\/title","value":"tableView:commitEditingStyle:forRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NetShearsIgnoreListViewController~1tableView(_:commit:forRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:commitEditingStyle:forRowAtIndexPath:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}