{"variants":[{"paths":["\/documentation\/divar\/netshearsignorelistviewcontroller\/uitableviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/netshearsignorelistviewcontroller\/uitableviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController\/UITableViewDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController\/tableView(_:editingStyleForRowAt:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"UITableViewDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/NetShearsIgnoreListViewController":{"role":"symbol","title":"NetShearsIgnoreListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetShearsIgnoreListViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetShearsIgnoreListViewController"}],"url":"\/documentation\/divar\/netshearsignorelistviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/NetShearsIgnoreListViewController/tableView(_:editingStyleForRowAt:)":{"role":"symbol","title":"tableView(_:editingStyleForRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"editingStyleForRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"EditingStyle","preciseIdentifier":"c:@E@UITableViewCellEditingStyle"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController\/tableView(_:editingStyleForRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:editingStyleForRowAtIndexPath:"}],"url":"\/documentation\/divar\/netshearsignorelistviewcontroller\/tableview(_:editingstyleforrowat:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController\/tableView(_:editingStyleForRowAt:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NetShearsIgnoreListViewController\/title","value":"NetShearsIgnoreListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NetShearsIgnoreListViewController\/fragments","value":[{"kind":"identifier","text":"NetShearsIgnoreListViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NetShearsIgnoreListViewController~1tableView(_:editingStyleForRowAt:)\/title","value":"tableView:editingStyleForRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NetShearsIgnoreListViewController~1tableView(_:editingStyleForRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:editingStyleForRowAtIndexPath:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}