{"variants":[{"paths":["\/documentation\/divar\/netshearsignorelistviewcontroller\/uitableviewdatasource-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/netshearsignorelistviewcontroller\/uitableviewdatasource-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController\/UITableViewDataSource-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController\/tableView(_:canEditRowAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController\/tableView(_:cellForRowAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController\/tableView(_:commit:forRowAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController\/tableView(_:numberOfRowsInSection:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"UITableViewDataSource Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/NetShearsIgnoreListViewController/tableView(_:cellForRowAt:)":{"role":"symbol","title":"tableView(_:cellForRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellForRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController\/tableView(_:cellForRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}],"url":"\/documentation\/divar\/netshearsignorelistviewcontroller\/tableview(_:cellforrowat:)"},"doc://com.Divar.DivarClient/documentation/Divar/NetShearsIgnoreListViewController":{"role":"symbol","title":"NetShearsIgnoreListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetShearsIgnoreListViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetShearsIgnoreListViewController"}],"url":"\/documentation\/divar\/netshearsignorelistviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/NetShearsIgnoreListViewController/tableView(_:numberOfRowsInSection:)":{"role":"symbol","title":"tableView(_:numberOfRowsInSection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfRowsInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController\/tableView(_:numberOfRowsInSection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}],"url":"\/documentation\/divar\/netshearsignorelistviewcontroller\/tableview(_:numberofrowsinsection:)"},"doc://com.Divar.DivarClient/documentation/Divar/NetShearsIgnoreListViewController/tableView(_:canEditRowAt:)":{"role":"symbol","title":"tableView(_:canEditRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"canEditRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController\/tableView(_:canEditRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:canEditRowAtIndexPath:"}],"url":"\/documentation\/divar\/netshearsignorelistviewcontroller\/tableview(_:caneditrowat:)"},"doc://com.Divar.DivarClient/documentation/Divar/NetShearsIgnoreListViewController/tableView(_:commit:forRowAt:)":{"role":"symbol","title":"tableView(_:commit:forRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"commit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"EditingStyle","preciseIdentifier":"c:@E@UITableViewCellEditingStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController\/tableView(_:commit:forRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:commitEditingStyle:forRowAtIndexPath:"}],"url":"\/documentation\/divar\/netshearsignorelistviewcontroller\/tableview(_:commit:forrowat:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController\/tableView(_:canEditRowAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController\/tableView(_:cellForRowAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController\/tableView(_:commit:forRowAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NetShearsIgnoreListViewController\/tableView(_:numberOfRowsInSection:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NetShearsIgnoreListViewController~1tableView(_:cellForRowAt:)\/title","value":"tableView:cellForRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NetShearsIgnoreListViewController~1tableView(_:cellForRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NetShearsIgnoreListViewController\/title","value":"NetShearsIgnoreListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NetShearsIgnoreListViewController\/fragments","value":[{"kind":"identifier","text":"NetShearsIgnoreListViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NetShearsIgnoreListViewController~1tableView(_:numberOfRowsInSection:)\/title","value":"tableView:numberOfRowsInSection:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NetShearsIgnoreListViewController~1tableView(_:numberOfRowsInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NetShearsIgnoreListViewController~1tableView(_:canEditRowAt:)\/title","value":"tableView:canEditRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NetShearsIgnoreListViewController~1tableView(_:canEditRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:canEditRowAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NetShearsIgnoreListViewController~1tableView(_:commit:forRowAt:)\/title","value":"tableView:commitEditingStyle:forRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NetShearsIgnoreListViewController~1tableView(_:commit:forRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:commitEditingStyle:forRowAtIndexPath:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}