{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hintView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HintView","preciseIdentifier":"c:@M@Divar@objc(cs)HintView","text":"HintView"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/textfieldhintview\/hintview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/textfieldhintview\/hintview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldHintView\/hintView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hintView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HintView","preciseIdentifier":"c:@M@Divar@objc(cs)HintView"},{"kind":"text","text":"!"}],"title":"hintView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)TextFieldHintView(py)hintView","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"hintView"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldHintView"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/TextFieldHintView/hintView":{"role":"symbol","title":"hintView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hintView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HintView","preciseIdentifier":"c:@M@Divar@objc(cs)HintView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldHintView\/hintView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hintView"}],"url":"\/documentation\/divar\/textfieldhintview\/hintview"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/TextFieldHintView":{"role":"symbol","title":"TextFieldHintView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextFieldHintView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldHintView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TextFieldHintView"}],"url":"\/documentation\/divar\/textfieldhintview"},"doc://com.Divar.DivarClient/documentation/Divar/HintView":{"role":"symbol","title":"HintView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HintView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HintView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HintView"}],"url":"\/documentation\/divar\/hintview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"hintView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"hintView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HintView","preciseIdentifier":"c:@M@Divar@objc(cs)HintView","text":"HintView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"hintView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TextFieldHintView~1hintView\/title","value":"hintView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TextFieldHintView~1hintView\/fragments","value":[{"kind":"identifier","text":"hintView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TextFieldHintView\/title","value":"TextFieldHintView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TextFieldHintView\/fragments","value":[{"kind":"identifier","text":"TextFieldHintView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1HintView\/title","value":"HintView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1HintView\/fragments","value":[{"kind":"identifier","text":"HintView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}