{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldView","preciseIdentifier":"c:@M@Divar@objc(cs)TextFieldView","text":"TextFieldView"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/textfieldhintview\/textfieldview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/textfieldhintview\/textfieldview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldHintView\/textFieldView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TextFieldView","preciseIdentifier":"c:@M@Divar@objc(cs)TextFieldView"},{"kind":"text","text":"!"}],"title":"textFieldView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)TextFieldHintView(py)textFieldView","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"textFieldView"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldHintView"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/TextFieldHintView":{"role":"symbol","title":"TextFieldHintView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextFieldHintView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldHintView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TextFieldHintView"}],"url":"\/documentation\/divar\/textfieldhintview"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/TextFieldView":{"role":"symbol","title":"TextFieldView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextFieldView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TextFieldView"}],"url":"\/documentation\/divar\/textfieldview"},"doc://com.Divar.DivarClient/documentation/Divar/TextFieldHintView/textFieldView":{"role":"symbol","title":"textFieldView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TextFieldView","preciseIdentifier":"c:@M@Divar@objc(cs)TextFieldView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldHintView\/textFieldView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldView"}],"url":"\/documentation\/divar\/textfieldhintview\/textfieldview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"textFieldView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"textFieldView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldView","preciseIdentifier":"c:@M@Divar@objc(cs)TextFieldView","text":"TextFieldView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"textFieldView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TextFieldHintView\/title","value":"TextFieldHintView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TextFieldHintView\/fragments","value":[{"kind":"identifier","text":"TextFieldHintView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TextFieldView\/title","value":"TextFieldView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TextFieldView\/fragments","value":[{"kind":"identifier","text":"TextFieldView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TextFieldHintView~1textFieldView\/title","value":"textFieldView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TextFieldHintView~1textFieldView\/fragments","value":[{"kind":"identifier","text":"textFieldView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}