{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberEnteredSuccessfully"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberInputViewController","preciseIdentifier":"c:@M@Divar@objc(cs)NumberInputViewController","text":"NumberInputViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"number"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"needsVerify"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/landlineverificationflowcontroller\/numberenteredsuccessfully(_:with:needsverify:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowController\/numberEnteredSuccessfully(_:with:needsVerify:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"NumberInputViewControllerDelegate.numberEnteredSuccessfully(_:with:needsVerify:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"numberEnteredSuccessfully(_:with:needsVerify:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberEnteredSuccessfully"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NumberInputViewController","preciseIdentifier":"c:@M@Divar@objc(cs)NumberInputViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"needsVerify"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar34LandlineVerificationFlowControllerC25numberEnteredSuccessfully_4with11needsVerifyyAA015NumberInputViewE0C_SSSbtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowController\/NumberInputViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/NumberInputViewController":{"role":"symbol","title":"NumberInputViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NumberInputViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberInputViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NumberInputViewController"}],"url":"\/documentation\/divar\/numberinputviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/LandlineVerificationFlowController":{"role":"symbol","title":"LandlineVerificationFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandlineVerificationFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandlineVerificationFlowController"}],"url":"\/documentation\/divar\/landlineverificationflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/LandlineVerificationFlowController/numberEnteredSuccessfully(_:with:needsVerify:)":{"role":"symbol","title":"numberEnteredSuccessfully(_:with:needsVerify:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberEnteredSuccessfully"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NumberInputViewController","preciseIdentifier":"c:@M@Divar@objc(cs)NumberInputViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"needsVerify"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowController\/numberEnteredSuccessfully(_:with:needsVerify:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/landlineverificationflowcontroller\/numberenteredsuccessfully(_:with:needsverify:)"},"doc://com.Divar.DivarClient/documentation/Divar/LandlineVerificationFlowController/NumberInputViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"NumberInputViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowController\/NumberInputViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/landlineverificationflowcontroller\/numberinputviewcontrollerdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NumberInputViewController\/title","value":"NumberInputViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NumberInputViewController\/fragments","value":[{"kind":"identifier","text":"NumberInputViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandlineVerificationFlowController\/title","value":"LandlineVerificationFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandlineVerificationFlowController\/fragments","value":[{"kind":"identifier","text":"LandlineVerificationFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}