{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryButtonClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"splitButtonVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SplitButtonBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SplitButtonBarViewController","text":"SplitButtonBarViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/baseformcontroller\/primarybuttonclicked(_:action:)-5hp0y"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormController\/primaryButtonClicked(_:action:)-5hp0y","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"SplitButtonBarViewControllerDelegate.primaryButtonClicked(_:action:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryButtonClicked"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SplitButtonBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SplitButtonBarViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":"?)"}],"title":"primaryButtonClicked(_:action:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:5Divar18BaseFormControllerC20primaryButtonClicked_6actionyAA05Splitf7BarViewD0C_0A14InterfaceSwift14Widgets_ActionVSgtF","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/BaseFormController/primaryButtonClicked(_:action:)-5hp0y":{"role":"symbol","title":"primaryButtonClicked(_:action:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryButtonClicked"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SplitButtonBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SplitButtonBarViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormController\/primaryButtonClicked(_:action:)-5hp0y","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformcontroller\/primarybuttonclicked(_:action:)-5hp0y"},"doc://com.Divar.DivarClient/documentation/Divar/SplitButtonBarViewController":{"role":"symbol","title":"SplitButtonBarViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SplitButtonBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SplitButtonBarViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SplitButtonBarViewController"}],"url":"\/documentation\/divar\/splitbuttonbarviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormController":{"role":"symbol","title":"BaseFormController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFormController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseFormController"}],"url":"\/documentation\/divar\/baseformcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SplitButtonBarViewController\/title","value":"SplitButtonBarViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SplitButtonBarViewController\/fragments","value":[{"kind":"identifier","text":"SplitButtonBarViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFormController\/title","value":"BaseFormController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFormController\/fragments","value":[{"kind":"identifier","text":"BaseFormController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}