{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"divider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/featurerowcollectionviewcell\/divider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/featurerowcollectionviewcell\/divider"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/divider","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"divider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"title":"divider","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)FeatureRowCollectionViewCell(py)divider","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"divider"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/FeatureRowCollectionViewCell":{"role":"symbol","title":"FeatureRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeatureRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeatureRowCollectionViewCell"}],"url":"\/documentation\/divar\/featurerowcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/FeatureRowCollectionViewCell/divider":{"role":"symbol","title":"divider","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"divider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/divider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"divider"}],"url":"\/documentation\/divar\/featurerowcollectionviewcell\/divider"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"divider"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"divider"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"divider"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell\/title","value":"FeatureRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"FeatureRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell~1divider\/title","value":"divider"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell~1divider\/fragments","value":[{"kind":"identifier","text":"divider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}