{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","preciseIdentifier":"c:@M@Divar@objc(cs)ChatViewController","text":"ChatViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestShowInConversationActionsWidget"},{"kind":"text","text":" "},{"kind":"internalParam","text":"widget"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_BottomSheet","preciseIdentifier":"s:19DivarInterfaceSwift19Widgets_BottomSheetV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/chatflowcontroller\/chatviewcontroller(_:didrequestshowinconversationactionswidget:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController\/chatViewController(_:didRequestShowInConversationActionsWidget:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ChatViewControllerDelegate.chatViewController(_:didRequestShowInConversationActionsWidget:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"chatViewController(_:didRequestShowInConversationActionsWidget:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatViewController","preciseIdentifier":"c:@M@Divar@objc(cs)ChatViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestShowInConversationActionsWidget"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_BottomSheet","preciseIdentifier":"s:19DivarInterfaceSwift19Widgets_BottomSheetV"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar18ChatFlowControllerC08chatViewD0_41didRequestShowInConversationActionsWidgetyAA0bfD0C_0A14InterfaceSwift19Widgets_BottomSheetVtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController\/ChatViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ChatFlowController/ChatViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"ChatViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController\/ChatViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/chatflowcontroller\/chatviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/ChatFlowController":{"role":"symbol","title":"ChatFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatFlowController"}],"url":"\/documentation\/divar\/chatflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController":{"role":"symbol","title":"ChatViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatViewController"}],"url":"\/documentation\/divar\/chatviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatFlowController/chatViewController(_:didRequestShowInConversationActionsWidget:)":{"role":"symbol","title":"chatViewController(_:didRequestShowInConversationActionsWidget:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatViewController","preciseIdentifier":"c:@M@Divar@objc(cs)ChatViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestShowInConversationActionsWidget"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_BottomSheet","preciseIdentifier":"s:19DivarInterfaceSwift19Widgets_BottomSheetV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController\/chatViewController(_:didRequestShowInConversationActionsWidget:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatflowcontroller\/chatviewcontroller(_:didrequestshowinconversationactionswidget:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatFlowController\/title","value":"ChatFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatFlowController\/fragments","value":[{"kind":"identifier","text":"ChatFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/title","value":"ChatViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/fragments","value":[{"kind":"identifier","text":"ChatViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}