{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","preciseIdentifier":"c:@M@Divar@objc(cs)ChatViewController","text":"ChatViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestShowForwardListForConversations"},{"kind":"text","text":" "},{"kind":"internalParam","text":"conversations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatConversationStructure","preciseIdentifier":"s:5Divar25ChatConversationStructureC","text":"ChatConversationStructure"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"withMessage"},{"kind":"text","text":" "},{"kind":"internalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV","text":"ChatConversationMessageTable"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/chatflowcontroller\/chatviewcontroller(_:didrequestshowforwardlistforconversations:withmessage:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController\/chatViewController(_:didRequestShowForwardListForConversations:withMessage:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ChatViewControllerDelegate.chatViewController(_:didRequestShowForwardListForConversations:withMessage:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"chatViewController(_:didRequestShowForwardListForConversations:withMessage:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatViewController","preciseIdentifier":"c:@M@Divar@objc(cs)ChatViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestShowForwardListForConversations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatConversationStructure","preciseIdentifier":"s:5Divar25ChatConversationStructureC"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"withMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar18ChatFlowControllerC08chatViewD0_41didRequestShowForwardListForConversations11withMessageyAA0bfD0C_SayAA0B21ConversationStructureCGAA0bpO5TableVtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController\/ChatViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ChatFlowController/chatViewController(_:didRequestShowForwardListForConversations:withMessage:)":{"role":"symbol","title":"chatViewController(_:didRequestShowForwardListForConversations:withMessage:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatViewController","preciseIdentifier":"c:@M@Divar@objc(cs)ChatViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestShowForwardListForConversations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatConversationStructure","preciseIdentifier":"s:5Divar25ChatConversationStructureC"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"withMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController\/chatViewController(_:didRequestShowForwardListForConversations:withMessage:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatflowcontroller\/chatviewcontroller(_:didrequestshowforwardlistforconversations:withmessage:)"},"doc://com.Divar.DivarClient/documentation/Divar/ChatFlowController/ChatViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"ChatViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController\/ChatViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/chatflowcontroller\/chatviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/ChatFlowController":{"role":"symbol","title":"ChatFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatFlowController"}],"url":"\/documentation\/divar\/chatflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatConversationStructure":{"role":"symbol","title":"ChatConversationStructure","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatConversationStructure"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatConversationStructure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatConversationStructure"}],"url":"\/documentation\/divar\/chatconversationstructure"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController":{"role":"symbol","title":"ChatViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatViewController"}],"url":"\/documentation\/divar\/chatviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatConversationMessageTable":{"role":"symbol","title":"ChatConversationMessageTable","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatConversationMessageTable"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatConversationMessageTable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatConversationMessageTable"}],"url":"\/documentation\/divar\/chatconversationmessagetable"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatFlowController\/title","value":"ChatFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatFlowController\/fragments","value":[{"kind":"identifier","text":"ChatFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/title","value":"ChatViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/fragments","value":[{"kind":"identifier","text":"ChatViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}