{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationViewControllerDidRequestOpeninMultiDelete"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"conversations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatConversationTable","preciseIdentifier":"s:5Divar21ChatConversationTableV","text":"ChatConversationTable"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConversationsViewController","preciseIdentifier":"c:@M@Divar@objc(cs)ConversationsViewController","text":"ConversationsViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/chatflowcontroller\/conversationviewcontrollerdidrequestopeninmultidelete(_:vc:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController\/conversationViewControllerDidRequestOpeninMultiDelete(_:vc:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ConversationsViewControllerDelegate.conversationViewControllerDidRequestOpeninMultiDelete(_:vc:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"conversationViewControllerDidRequestOpeninMultiDelete(_:vc:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationViewControllerDidRequestOpeninMultiDelete"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"ChatConversationTable","preciseIdentifier":"s:5Divar21ChatConversationTableV"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationsViewController","preciseIdentifier":"c:@M@Divar@objc(cs)ConversationsViewController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar18ChatFlowControllerC016conversationViewD27DidRequestOpeninMultiDelete_2vcySayAA0B17ConversationTableVG_AA013ConversationsfD0CtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController\/ConversationsViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ChatFlowController/conversationViewControllerDidRequestOpeninMultiDelete(_:vc:)":{"role":"symbol","title":"conversationViewControllerDidRequestOpeninMultiDelete(_:vc:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationViewControllerDidRequestOpeninMultiDelete"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"ChatConversationTable","preciseIdentifier":"s:5Divar21ChatConversationTableV"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationsViewController","preciseIdentifier":"c:@M@Divar@objc(cs)ConversationsViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController\/conversationViewControllerDidRequestOpeninMultiDelete(_:vc:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatflowcontroller\/conversationviewcontrollerdidrequestopeninmultidelete(_:vc:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/ChatFlowController/ConversationsViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"ConversationsViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController\/ConversationsViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/chatflowcontroller\/conversationsviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/ChatConversationTable":{"role":"symbol","title":"ChatConversationTable","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatConversationTable"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatConversationTable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatConversationTable"}],"url":"\/documentation\/divar\/chatconversationtable"},"doc://com.Divar.DivarClient/documentation/Divar/ChatFlowController":{"role":"symbol","title":"ChatFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatFlowController"}],"url":"\/documentation\/divar\/chatflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ConversationsViewController":{"role":"symbol","title":"ConversationsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConversationsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationsViewController"}],"url":"\/documentation\/divar\/conversationsviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatFlowController\/title","value":"ChatFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatFlowController\/fragments","value":[{"kind":"identifier","text":"ChatFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ConversationsViewController\/title","value":"ConversationsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ConversationsViewController\/fragments","value":[{"kind":"identifier","text":"ConversationsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}