{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRequestLogin"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatInstructLoginViewController","preciseIdentifier":"c:@M@Divar@objc(cs)ChatInstructLoginViewController","text":"ChatInstructLoginViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/chatflowcontroller\/didrequestlogin(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController\/didRequestLogin(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ChatInstructLoginViewControllerDelegate.didRequestLogin(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"didRequestLogin(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRequestLogin"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatInstructLoginViewController","preciseIdentifier":"c:@M@Divar@objc(cs)ChatInstructLoginViewController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar18ChatFlowControllerC15didRequestLoginyyAA0b8Instructg4ViewD0CF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController\/ChatInstructLoginViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ChatFlowController/ChatInstructLoginViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"ChatInstructLoginViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController\/ChatInstructLoginViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/chatflowcontroller\/chatinstructloginviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/ChatFlowController":{"role":"symbol","title":"ChatFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatFlowController"}],"url":"\/documentation\/divar\/chatflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatInstructLoginViewController":{"role":"symbol","title":"ChatInstructLoginViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatInstructLoginViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatInstructLoginViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatInstructLoginViewController"}],"url":"\/documentation\/divar\/chatinstructloginviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatFlowController/didRequestLogin(_:)":{"role":"symbol","title":"didRequestLogin(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRequestLogin"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatInstructLoginViewController","preciseIdentifier":"c:@M@Divar@objc(cs)ChatInstructLoginViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController\/didRequestLogin(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatflowcontroller\/didrequestlogin(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatFlowController\/title","value":"ChatFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatFlowController\/fragments","value":[{"kind":"identifier","text":"ChatFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatInstructLoginViewController\/title","value":"ChatInstructLoginViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatInstructLoginViewController\/fragments","value":[{"kind":"identifier","text":"ChatInstructLoginViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}