{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"forwardViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ForwardViewController","preciseIdentifier":"c:@M@Divar@objc(cs)ForwardViewController","text":"ForwardViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestForwardMessage"},{"kind":"text","text":" "},{"kind":"internalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV","text":"ChatConversationMessageTable"},{"kind":"text","text":", "},{"kind":"externalParam","text":"toConversation"},{"kind":"text","text":" "},{"kind":"internalParam","text":"conversation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatConversationStructure","preciseIdentifier":"s:5Divar25ChatConversationStructureC","text":"ChatConversationStructure"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/chatflowcontroller\/forwardviewcontroller(_:didrequestforwardmessage:toconversation:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController\/forwardViewController(_:didRequestForwardMessage:toConversation:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ForwardViewControllerDelegate.forwardViewController(_:didRequestForwardMessage:toConversation:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"forwardViewController(_:didRequestForwardMessage:toConversation:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"forwardViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ForwardViewController","preciseIdentifier":"c:@M@Divar@objc(cs)ForwardViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestForwardMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"toConversation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatConversationStructure","preciseIdentifier":"s:5Divar25ChatConversationStructureC"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar18ChatFlowControllerC011forwardViewD0_24didRequestForwardMessage14toConversationyAA0ifD0C_AA0blJ5TableVAA0bL9StructureCtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController\/ForwardViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ChatFlowController/ForwardViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"ForwardViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController\/ForwardViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/chatflowcontroller\/forwardviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/ChatFlowController/forwardViewController(_:didRequestForwardMessage:toConversation:)":{"role":"symbol","title":"forwardViewController(_:didRequestForwardMessage:toConversation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"forwardViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ForwardViewController","preciseIdentifier":"c:@M@Divar@objc(cs)ForwardViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestForwardMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"toConversation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatConversationStructure","preciseIdentifier":"s:5Divar25ChatConversationStructureC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController\/forwardViewController(_:didRequestForwardMessage:toConversation:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatflowcontroller\/forwardviewcontroller(_:didrequestforwardmessage:toconversation:)"},"doc://com.Divar.DivarClient/documentation/Divar/ForwardViewController":{"role":"symbol","title":"ForwardViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ForwardViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ForwardViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ForwardViewController"}],"url":"\/documentation\/divar\/forwardviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatFlowController":{"role":"symbol","title":"ChatFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatFlowController"}],"url":"\/documentation\/divar\/chatflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatConversationStructure":{"role":"symbol","title":"ChatConversationStructure","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatConversationStructure"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatConversationStructure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatConversationStructure"}],"url":"\/documentation\/divar\/chatconversationstructure"},"doc://com.Divar.DivarClient/documentation/Divar/ChatConversationMessageTable":{"role":"symbol","title":"ChatConversationMessageTable","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatConversationMessageTable"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatConversationMessageTable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatConversationMessageTable"}],"url":"\/documentation\/divar\/chatconversationmessagetable"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ForwardViewController\/title","value":"ForwardViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ForwardViewController\/fragments","value":[{"kind":"identifier","text":"ForwardViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatFlowController\/title","value":"ChatFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatFlowController\/fragments","value":[{"kind":"identifier","text":"ChatFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}