{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userRegisteredSuccessfully"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":" "},{"kind":"internalParam","text":"flow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UserRegisterFlowController","preciseIdentifier":"c:@M@Divar@objc(cs)UserRegisterFlowController","text":"UserRegisterFlowController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"phoneNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/chatflowcontroller\/userregisteredsuccessfully(in:with:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController\/userRegisteredSuccessfully(in:with:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UserRegisterFlowControllerDelegate.userRegisteredSuccessfully(in:with:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userRegisteredSuccessfully"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserRegisterFlowController","preciseIdentifier":"c:@M@Divar@objc(cs)UserRegisterFlowController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"userRegisteredSuccessfully(in:with:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:5Divar18ChatFlowControllerC26userRegisteredSuccessfully2in4withyAA012UserRegistercD0C_SStF","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ChatFlowController":{"role":"symbol","title":"ChatFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatFlowController"}],"url":"\/documentation\/divar\/chatflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatFlowController/userRegisteredSuccessfully(in:with:)":{"role":"symbol","title":"userRegisteredSuccessfully(in:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userRegisteredSuccessfully"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserRegisterFlowController","preciseIdentifier":"c:@M@Divar@objc(cs)UserRegisterFlowController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController\/userRegisteredSuccessfully(in:with:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatflowcontroller\/userregisteredsuccessfully(in:with:)"},"doc://com.Divar.DivarClient/documentation/Divar/UserRegisterFlowController":{"role":"symbol","title":"UserRegisterFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserRegisterFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UserRegisterFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserRegisterFlowController"}],"url":"\/documentation\/divar\/userregisterflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatFlowController\/title","value":"ChatFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatFlowController\/fragments","value":[{"kind":"identifier","text":"ChatFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1UserRegisterFlowController\/title","value":"UserRegisterFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1UserRegisterFlowController\/fragments","value":[{"kind":"identifier","text":"UserRegisterFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}