{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchHistoryRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchHistoryRow","preciseIdentifier":"c:@M@Sonnat@objc(cs)SearchHistoryRow"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/searchhistoryrowtablecell\/searchhistoryrow"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/searchhistoryrowtablecell\/searchhistoryrow"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchHistoryRowTableCell\/searchHistoryRow","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchHistoryRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchHistoryRow","preciseIdentifier":"c:@M@Sonnat@objc(cs)SearchHistoryRow"},{"kind":"text","text":"!"}],"title":"searchHistoryRow","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)SearchHistoryRowTableCell(py)searchHistoryRow","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"searchHistoryRow"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchHistoryRowTableCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/SearchHistoryRowTableCell/searchHistoryRow":{"role":"symbol","title":"searchHistoryRow","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchHistoryRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchHistoryRow","preciseIdentifier":"c:@M@Sonnat@objc(cs)SearchHistoryRow"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchHistoryRowTableCell\/searchHistoryRow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"searchHistoryRow"}],"url":"\/documentation\/divar\/searchhistoryrowtablecell\/searchhistoryrow"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/SearchHistoryRowTableCell":{"role":"symbol","title":"SearchHistoryRowTableCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchHistoryRowTableCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchHistoryRowTableCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchHistoryRowTableCell"}],"url":"\/documentation\/divar\/searchhistoryrowtablecell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"searchHistoryRow"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"searchHistoryRow"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"SearchHistoryRow","preciseIdentifier":"c:objc(cs)SearchHistoryRow"},{"kind":"text","text":" * "},{"kind":"identifier","text":"searchHistoryRow"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchHistoryRowTableCell~1searchHistoryRow\/title","value":"searchHistoryRow"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchHistoryRowTableCell~1searchHistoryRow\/fragments","value":[{"kind":"identifier","text":"searchHistoryRow"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchHistoryRowTableCell\/title","value":"SearchHistoryRowTableCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchHistoryRowTableCell\/fragments","value":[{"kind":"identifier","text":"SearchHistoryRowTableCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}