{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondaryButtonClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"twinButtonsVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TwinButtonsViewController","text":"TwinButtonsViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/beforeregistertermsandconditionsvc\/secondarybuttonclicked(_:action:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BeforeRegisterTermsAndConditionsVC\/secondaryButtonClicked(_:action:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"TwinButtonsViewControllerDelegate.secondaryButtonClicked(_:action:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"secondaryButtonClicked(_:action:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondaryButtonClicked"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TwinButtonsViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TwinButtonsViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"s:5Divar34BeforeRegisterTermsAndConditionsVCC22secondaryButtonClicked_6actionyAA25TwinButtonsViewControllerC_0A14InterfaceSwift14Widgets_ActionVSgtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BeforeRegisterTermsAndConditionsVC","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BeforeRegisterTermsAndConditionsVC\/TwinButtonsViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewController":{"role":"symbol","title":"TwinButtonsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TwinButtonsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TwinButtonsViewController"}],"url":"\/documentation\/divar\/twinbuttonsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BeforeRegisterTermsAndConditionsVC":{"role":"symbol","title":"BeforeRegisterTermsAndConditionsVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BeforeRegisterTermsAndConditionsVC"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BeforeRegisterTermsAndConditionsVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BeforeRegisterTermsAndConditionsVC"}],"url":"\/documentation\/divar\/beforeregistertermsandconditionsvc"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/BeforeRegisterTermsAndConditionsVC/secondaryButtonClicked(_:action:)":{"role":"symbol","title":"secondaryButtonClicked(_:action:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondaryButtonClicked"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TwinButtonsViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TwinButtonsViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BeforeRegisterTermsAndConditionsVC\/secondaryButtonClicked(_:action:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/beforeregistertermsandconditionsvc\/secondarybuttonclicked(_:action:)"},"doc://com.Divar.DivarClient/documentation/Divar/BeforeRegisterTermsAndConditionsVC/TwinButtonsViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"TwinButtonsViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BeforeRegisterTermsAndConditionsVC\/TwinButtonsViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/beforeregistertermsandconditionsvc\/twinbuttonsviewcontrollerdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TwinButtonsViewController\/title","value":"TwinButtonsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TwinButtonsViewController\/fragments","value":[{"kind":"identifier","text":"TwinButtonsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BeforeRegisterTermsAndConditionsVC\/title","value":"BeforeRegisterTermsAndConditionsVC"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BeforeRegisterTermsAndConditionsVC\/fragments","value":[{"kind":"identifier","text":"BeforeRegisterTermsAndConditionsVC"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}