{"variants":[{"paths":["\/documentation\/divar\/beforeregistertermsandconditionsvc\/wknavigationdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/beforeregistertermsandconditionsvc\/wknavigationdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BeforeRegisterTermsAndConditionsVC\/WKNavigationDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BeforeRegisterTermsAndConditionsVC\/webView(_:didFinish:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"WKNavigationDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BeforeRegisterTermsAndConditionsVC"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/BeforeRegisterTermsAndConditionsVC/webView(_:didFinish:)":{"role":"symbol","title":"webView(_:didFinish:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinish"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BeforeRegisterTermsAndConditionsVC\/webView(_:didFinish:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"webView:didFinishNavigation:"}],"url":"\/documentation\/divar\/beforeregistertermsandconditionsvc\/webview(_:didfinish:)"},"doc://com.Divar.DivarClient/documentation/Divar/BeforeRegisterTermsAndConditionsVC":{"role":"symbol","title":"BeforeRegisterTermsAndConditionsVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BeforeRegisterTermsAndConditionsVC"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BeforeRegisterTermsAndConditionsVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BeforeRegisterTermsAndConditionsVC"}],"url":"\/documentation\/divar\/beforeregistertermsandconditionsvc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BeforeRegisterTermsAndConditionsVC\/webView(_:didFinish:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BeforeRegisterTermsAndConditionsVC~1webView(_:didFinish:)\/title","value":"webView:didFinishNavigation:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BeforeRegisterTermsAndConditionsVC~1webView(_:didFinish:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:didFinishNavigation:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BeforeRegisterTermsAndConditionsVC\/title","value":"BeforeRegisterTermsAndConditionsVC"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BeforeRegisterTermsAndConditionsVC\/fragments","value":[{"kind":"identifier","text":"BeforeRegisterTermsAndConditionsVC"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}