{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cityFilterView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CityFilterView","preciseIdentifier":"c:@M@Divar@objc(cs)CityFilterView","text":"CityFilterView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/postlistviewcontroller\/cityfilterview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/cityFilterView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cityFilterView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CityFilterView","preciseIdentifier":"c:@M@Divar@objc(cs)CityFilterView"}],"title":"cityFilterView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar22PostListViewControllerC010cityFilterD0AA04CitygD0Cvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/cityFilterView":{"role":"symbol","title":"cityFilterView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cityFilterView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CityFilterView","preciseIdentifier":"c:@M@Divar@objc(cs)CityFilterView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/cityFilterView","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/cityfilterview"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController":{"role":"symbol","title":"PostListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostListViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostListViewController"}],"url":"\/documentation\/divar\/postlistviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CityFilterView":{"role":"symbol","title":"CityFilterView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CityFilterView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CityFilterView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CityFilterView"}],"url":"\/documentation\/divar\/cityfilterview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListViewController\/title","value":"PostListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListViewController\/fragments","value":[{"kind":"identifier","text":"PostListViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CityFilterView\/title","value":"CityFilterView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CityFilterView\/fragments","value":[{"kind":"identifier","text":"CityFilterView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}