{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didClose"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"updateVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UpdateViewController","preciseIdentifier":"c:@M@Divar@objc(cs)UpdateViewController","text":"UpdateViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/postlistviewcontroller\/didclose(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/didClose(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UpdateViewControllerDelegate.didClose(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"didClose(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didClose"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UpdateViewController","preciseIdentifier":"c:@M@Divar@objc(cs)UpdateViewController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar22PostListViewControllerC8didCloseyyAA06UpdatedE0CF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/UpdateViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController":{"role":"symbol","title":"PostListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostListViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostListViewController"}],"url":"\/documentation\/divar\/postlistviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/UpdateViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"UpdateViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/UpdateViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/updateviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/didClose(_:)":{"role":"symbol","title":"didClose(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didClose"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UpdateViewController","preciseIdentifier":"c:@M@Divar@objc(cs)UpdateViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/didClose(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/didclose(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/UpdateViewController":{"role":"symbol","title":"UpdateViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UpdateViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UpdateViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UpdateViewController"}],"url":"\/documentation\/divar\/updateviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListViewController\/title","value":"PostListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListViewController\/fragments","value":[{"kind":"identifier","text":"PostListViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1UpdateViewController\/title","value":"UpdateViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1UpdateViewController\/fragments","value":[{"kind":"identifier","text":"UpdateViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}