{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"postListTabbedVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListTabbedViewController","preciseIdentifier":"c:@M@Divar@objc(cs)PostListTabbedViewController","text":"PostListTabbedViewController"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/postlistviewcontroller\/postlisttabbedvc"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/postListTabbedVC","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"postListTabbedVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostListTabbedViewController","preciseIdentifier":"c:@M@Divar@objc(cs)PostListTabbedViewController"},{"kind":"text","text":"!"}],"title":"postListTabbedVC","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar22PostListViewControllerC04postC8TabbedVCAA0bcgdE0CSgvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController":{"role":"symbol","title":"PostListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostListViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostListViewController"}],"url":"\/documentation\/divar\/postlistviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/postListTabbedVC":{"role":"symbol","title":"postListTabbedVC","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"postListTabbedVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostListTabbedViewController","preciseIdentifier":"c:@M@Divar@objc(cs)PostListTabbedViewController"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/postListTabbedVC","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/postlisttabbedvc"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PostListTabbedViewController":{"role":"symbol","title":"PostListTabbedViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostListTabbedViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListTabbedViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostListTabbedViewController"}],"url":"\/documentation\/divar\/postlisttabbedviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListViewController\/title","value":"PostListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListViewController\/fragments","value":[{"kind":"identifier","text":"PostListViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListTabbedViewController\/title","value":"PostListTabbedViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListTabbedViewController\/fragments","value":[{"kind":"identifier","text":"PostListTabbedViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}