{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SearchViewController","text":"SearchViewController"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/postlistviewcontroller\/searchvc"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/searchVC","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SearchViewController"},{"kind":"text","text":"?"}],"title":"searchVC","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar22PostListViewControllerC8searchVCAA06SearchdE0CSgvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/searchVC":{"role":"symbol","title":"searchVC","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SearchViewController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/searchVC","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/searchvc"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/SearchViewController":{"role":"symbol","title":"SearchViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchViewController"}],"url":"\/documentation\/divar\/searchviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController":{"role":"symbol","title":"PostListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostListViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostListViewController"}],"url":"\/documentation\/divar\/postlistviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchViewController\/title","value":"SearchViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchViewController\/fragments","value":[{"kind":"identifier","text":"SearchViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListViewController\/title","value":"PostListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListViewController\/fragments","value":[{"kind":"identifier","text":"PostListViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}