{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayerEndInterruption"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"player"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVAudioPlayer","preciseIdentifier":"c:objc(cs)AVAudioPlayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withOptions"},{"kind":"text","text":" "},{"kind":"internalParam","text":"flags"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/audioplaymanager\/audioplayerendinterruption(_:withoptions:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/audioplaymanager\/audioplayerendinterruption(_:withoptions:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/audioPlayerEndInterruption(_:withOptions:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AVAudioPlayerDelegate.audioPlayerEndInterruption(_:withOptions:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"audioPlayerEndInterruption:withOptions:"}],"role":"symbol","title":"audioPlayerEndInterruption(_:withOptions:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayerEndInterruption"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVAudioPlayer","preciseIdentifier":"c:objc(cs)AVAudioPlayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@Divar@objc(cs)AudioPlayManager(im)audioPlayerEndInterruption:withOptions:","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/AVAudioPlayerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/AudioPlayManager/audioPlayerEndInterruption(_:withOptions:)":{"role":"symbol","title":"audioPlayerEndInterruption(_:withOptions:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayerEndInterruption"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVAudioPlayer","preciseIdentifier":"c:objc(cs)AVAudioPlayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/audioPlayerEndInterruption(_:withOptions:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioPlayerEndInterruption:withOptions:"}],"url":"\/documentation\/divar\/audioplaymanager\/audioplayerendinterruption(_:withoptions:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/AudioPlayManager/AVAudioPlayerDelegate-Implementations":{"role":"collectionGroup","title":"AVAudioPlayerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/AVAudioPlayerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/audioplaymanager\/avaudioplayerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/AudioPlayManager":{"role":"symbol","title":"AudioPlayManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioPlayManager"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AudioPlayManager"}],"url":"\/documentation\/divar\/audioplaymanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"audioPlayerEndInterruption:withOptions:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"audioPlayerEndInterruption:withOptions:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"audioPlayerEndInterruption:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVAudioPlayer","preciseIdentifier":"c:objc(cs)AVAudioPlayer"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"player"},{"kind":"text","text":" "},{"kind":"identifier","text":"withOptions:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"flags"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AudioPlayManager~1audioPlayerEndInterruption(_:withOptions:)\/title","value":"audioPlayerEndInterruption:withOptions:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AudioPlayManager~1audioPlayerEndInterruption(_:withOptions:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"audioPlayerEndInterruption:withOptions:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AudioPlayManager\/title","value":"AudioPlayManager"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AudioPlayManager\/fragments","value":[{"kind":"identifier","text":"AudioPlayManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}