{"variants":[{"paths":["\/documentation\/divar\/audioplaymanager\/avaudioplayerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/audioplaymanager\/avaudioplayerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/AVAudioPlayerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/audioPlayerBeginInterruption(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/audioPlayerDecodeErrorDidOccur(_:error:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/audioPlayerDidFinishPlaying(_:successfully:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/audioPlayerEndInterruption(_:withOptions:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"AVAudioPlayerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/AudioPlayManager/audioPlayerEndInterruption(_:withOptions:)":{"role":"symbol","title":"audioPlayerEndInterruption(_:withOptions:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayerEndInterruption"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVAudioPlayer","preciseIdentifier":"c:objc(cs)AVAudioPlayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/audioPlayerEndInterruption(_:withOptions:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioPlayerEndInterruption:withOptions:"}],"url":"\/documentation\/divar\/audioplaymanager\/audioplayerendinterruption(_:withoptions:)"},"doc://com.Divar.DivarClient/documentation/Divar/AudioPlayManager/audioPlayerDidFinishPlaying(_:successfully:)":{"role":"symbol","title":"audioPlayerDidFinishPlaying(_:successfully:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayerDidFinishPlaying"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVAudioPlayer","preciseIdentifier":"c:objc(cs)AVAudioPlayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"successfully"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/audioPlayerDidFinishPlaying(_:successfully:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioPlayerDidFinishPlaying:successfully:"}],"url":"\/documentation\/divar\/audioplaymanager\/audioplayerdidfinishplaying(_:successfully:)"},"doc://com.Divar.DivarClient/documentation/Divar/AudioPlayManager":{"role":"symbol","title":"AudioPlayManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioPlayManager"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AudioPlayManager"}],"url":"\/documentation\/divar\/audioplaymanager"},"doc://com.Divar.DivarClient/documentation/Divar/AudioPlayManager/audioPlayerBeginInterruption(_:)":{"role":"symbol","title":"audioPlayerBeginInterruption(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayerBeginInterruption"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVAudioPlayer","preciseIdentifier":"c:objc(cs)AVAudioPlayer"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/audioPlayerBeginInterruption(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioPlayerBeginInterruption:"}],"url":"\/documentation\/divar\/audioplaymanager\/audioplayerbegininterruption(_:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/AudioPlayManager/audioPlayerDecodeErrorDidOccur(_:error:)":{"role":"symbol","title":"audioPlayerDecodeErrorDidOccur(_:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayerDecodeErrorDidOccur"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVAudioPlayer","preciseIdentifier":"c:objc(cs)AVAudioPlayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/audioPlayerDecodeErrorDidOccur(_:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioPlayerDecodeErrorDidOccur:error:"}],"url":"\/documentation\/divar\/audioplaymanager\/audioplayerdecodeerrordidoccur(_:error:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/audioPlayerBeginInterruption(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/audioPlayerDecodeErrorDidOccur(_:error:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/audioPlayerDidFinishPlaying(_:successfully:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/audioPlayerEndInterruption(_:withOptions:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AudioPlayManager~1audioPlayerEndInterruption(_:withOptions:)\/title","value":"audioPlayerEndInterruption:withOptions:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AudioPlayManager~1audioPlayerEndInterruption(_:withOptions:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"audioPlayerEndInterruption:withOptions:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AudioPlayManager~1audioPlayerDidFinishPlaying(_:successfully:)\/title","value":"audioPlayerDidFinishPlaying:successfully:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AudioPlayManager~1audioPlayerDidFinishPlaying(_:successfully:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"audioPlayerDidFinishPlaying:successfully:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AudioPlayManager\/title","value":"AudioPlayManager"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AudioPlayManager\/fragments","value":[{"kind":"identifier","text":"AudioPlayManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AudioPlayManager~1audioPlayerBeginInterruption(_:)\/title","value":"audioPlayerBeginInterruption:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AudioPlayManager~1audioPlayerBeginInterruption(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"audioPlayerBeginInterruption:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AudioPlayManager~1audioPlayerDecodeErrorDidOccur(_:error:)\/title","value":"audioPlayerDecodeErrorDidOccur:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AudioPlayManager~1audioPlayerDecodeErrorDidOccur(_:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"audioPlayerDecodeErrorDidOccur:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}