{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"blockingView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BlockingView","preciseIdentifier":"c:@M@Divar@objc(cs)BlockingView","text":"BlockingView"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/chatinstructloginviewcontroller\/blockingview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/chatinstructloginviewcontroller\/blockingview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatInstructLoginViewController\/blockingView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"blockingView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BlockingView","preciseIdentifier":"c:@M@Divar@objc(cs)BlockingView"},{"kind":"text","text":"!"}],"title":"blockingView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)ChatInstructLoginViewController(py)blockingView","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"blockingView"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatInstructLoginViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ChatInstructLoginViewController":{"role":"symbol","title":"ChatInstructLoginViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatInstructLoginViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatInstructLoginViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatInstructLoginViewController"}],"url":"\/documentation\/divar\/chatinstructloginviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatInstructLoginViewController/blockingView":{"role":"symbol","title":"blockingView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"blockingView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BlockingView","preciseIdentifier":"c:@M@Divar@objc(cs)BlockingView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatInstructLoginViewController\/blockingView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"blockingView"}],"url":"\/documentation\/divar\/chatinstructloginviewcontroller\/blockingview"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/BlockingView":{"role":"symbol","title":"BlockingView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BlockingView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BlockingView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BlockingView"}],"url":"\/documentation\/divar\/blockingview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"blockingView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"blockingView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BlockingView","preciseIdentifier":"c:@M@Divar@objc(cs)BlockingView","text":"BlockingView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"blockingView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatInstructLoginViewController\/title","value":"ChatInstructLoginViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatInstructLoginViewController\/fragments","value":[{"kind":"identifier","text":"ChatInstructLoginViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatInstructLoginViewController~1blockingView\/title","value":"blockingView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatInstructLoginViewController~1blockingView\/fragments","value":[{"kind":"identifier","text":"blockingView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BlockingView\/title","value":"BlockingView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BlockingView\/fragments","value":[{"kind":"identifier","text":"BlockingView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}