{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expandableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InfoRowExpandable","preciseIdentifier":"c:@M@Sonnat@objc(cs)InfoRowExpandable"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/inforowexpandablecollectionviewcell\/expandableview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/inforowexpandablecollectionviewcell\/expandableview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InfoRowExpandableCollectionViewCell\/expandableView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expandableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InfoRowExpandable","preciseIdentifier":"c:@M@Sonnat@objc(cs)InfoRowExpandable"},{"kind":"text","text":"!"}],"title":"expandableView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)InfoRowExpandableCollectionViewCell(py)expandableView","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"expandableView"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InfoRowExpandableCollectionViewCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/InfoRowExpandableCollectionViewCell/expandableView":{"role":"symbol","title":"expandableView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expandableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InfoRowExpandable","preciseIdentifier":"c:@M@Sonnat@objc(cs)InfoRowExpandable"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InfoRowExpandableCollectionViewCell\/expandableView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"expandableView"}],"url":"\/documentation\/divar\/inforowexpandablecollectionviewcell\/expandableview"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/InfoRowExpandableCollectionViewCell":{"role":"symbol","title":"InfoRowExpandableCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InfoRowExpandableCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InfoRowExpandableCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InfoRowExpandableCollectionViewCell"}],"url":"\/documentation\/divar\/inforowexpandablecollectionviewcell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"expandableView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"expandableView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"InfoRowExpandable","preciseIdentifier":"c:objc(cs)InfoRowExpandable"},{"kind":"text","text":" * "},{"kind":"identifier","text":"expandableView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InfoRowExpandableCollectionViewCell~1expandableView\/title","value":"expandableView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InfoRowExpandableCollectionViewCell~1expandableView\/fragments","value":[{"kind":"identifier","text":"expandableView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InfoRowExpandableCollectionViewCell\/title","value":"InfoRowExpandableCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InfoRowExpandableCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"InfoRowExpandableCollectionViewCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}