{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedTableView","preciseIdentifier":"c:@M@Divar@objc(cs)AdvancedTableView","text":"AdvancedTableView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/singlemultibaseviewcontroller\/tableview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleMultiBaseViewController\/tableView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdvancedTableView","preciseIdentifier":"c:@M@Divar@objc(cs)AdvancedTableView"}],"title":"tableView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar29SingleMultiBaseViewControllerC05tableE0AA013AdvancedTableE0Cvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleMultiBaseViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/AdvancedTableView":{"role":"symbol","title":"AdvancedTableView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdvancedTableView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedTableView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdvancedTableView"}],"url":"\/documentation\/divar\/advancedtableview"},"doc://com.Divar.DivarClient/documentation/Divar/SingleMultiBaseViewController/tableView":{"role":"symbol","title":"tableView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdvancedTableView","preciseIdentifier":"c:@M@Divar@objc(cs)AdvancedTableView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleMultiBaseViewController\/tableView","kind":"symbol","type":"topic","url":"\/documentation\/divar\/singlemultibaseviewcontroller\/tableview"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/SingleMultiBaseViewController":{"role":"symbol","title":"SingleMultiBaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleMultiBaseViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleMultiBaseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SingleMultiBaseViewController"}],"url":"\/documentation\/divar\/singlemultibaseviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedTableView\/title","value":"AdvancedTableView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedTableView\/fragments","value":[{"kind":"identifier","text":"AdvancedTableView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleMultiBaseViewController\/title","value":"SingleMultiBaseViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleMultiBaseViewController\/fragments","value":[{"kind":"identifier","text":"SingleMultiBaseViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}