{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraOverlayDidRequestStartRecording"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cameraOverlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView","preciseIdentifier":"c:@M@Divar@objc(cs)CameraOverlayView","text":"CameraOverlayView"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/ivvideorecorderviewcontroller\/cameraoverlaydidrequeststartrecording(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVVideoRecorderViewController\/cameraOverlayDidRequestStartRecording(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CameraOverlayDelegate.cameraOverlayDidRequestStartRecording(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"cameraOverlayDidRequestStartRecording(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraOverlayDidRequestStartRecording"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CameraOverlayView","preciseIdentifier":"c:@M@Divar@objc(cs)CameraOverlayView"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar29IVVideoRecorderViewControllerC37cameraOverlayDidRequestStartRecordingyyAA06CameragD0CF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVVideoRecorderViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVVideoRecorderViewController\/CameraOverlayDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayView":{"role":"symbol","title":"CameraOverlayView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraOverlayView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraOverlayView"}],"url":"\/documentation\/divar\/cameraoverlayview"},"doc://com.Divar.DivarClient/documentation/Divar/IVVideoRecorderViewController/cameraOverlayDidRequestStartRecording(_:)":{"role":"symbol","title":"cameraOverlayDidRequestStartRecording(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraOverlayDidRequestStartRecording"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CameraOverlayView","preciseIdentifier":"c:@M@Divar@objc(cs)CameraOverlayView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVVideoRecorderViewController\/cameraOverlayDidRequestStartRecording(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/ivvideorecorderviewcontroller\/cameraoverlaydidrequeststartrecording(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/IVVideoRecorderViewController/CameraOverlayDelegate-Implementations":{"role":"collectionGroup","title":"CameraOverlayDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVVideoRecorderViewController\/CameraOverlayDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/ivvideorecorderviewcontroller\/cameraoverlaydelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/IVVideoRecorderViewController":{"role":"symbol","title":"IVVideoRecorderViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IVVideoRecorderViewController"}],"abstract":[{"type":"text","text":"Present this controller to record video from camera"}],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVVideoRecorderViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IVVideoRecorderViewController"}],"url":"\/documentation\/divar\/ivvideorecorderviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CameraOverlayView\/title","value":"CameraOverlayView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CameraOverlayView\/fragments","value":[{"kind":"identifier","text":"CameraOverlayView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1IVVideoRecorderViewController\/title","value":"IVVideoRecorderViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1IVVideoRecorderViewController\/fragments","value":[{"kind":"identifier","text":"IVVideoRecorderViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}