{"variants":[{"paths":["\/documentation\/divar\/ivvideorecorderviewcontroller\/uiimagepickercontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/ivvideorecorderviewcontroller\/uiimagepickercontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVVideoRecorderViewController\/UIImagePickerControllerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVVideoRecorderViewController\/imagePickerController(_:didFinishPickingMediaWithInfo:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"UIImagePickerControllerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVVideoRecorderViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/IVVideoRecorderViewController":{"role":"symbol","title":"IVVideoRecorderViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IVVideoRecorderViewController"}],"abstract":[{"type":"text","text":"Present this controller to record video from camera"}],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVVideoRecorderViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IVVideoRecorderViewController"}],"url":"\/documentation\/divar\/ivvideorecorderviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/IVVideoRecorderViewController/imagePickerController(_:didFinishPickingMediaWithInfo:)":{"role":"symbol","title":"imagePickerController(_:didFinishPickingMediaWithInfo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imagePickerController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishPickingMediaWithInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"InfoKey","preciseIdentifier":"c:@T@UIImagePickerControllerInfoKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVVideoRecorderViewController\/imagePickerController(_:didFinishPickingMediaWithInfo:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imagePickerController:didFinishPickingMediaWithInfo:"}],"url":"\/documentation\/divar\/ivvideorecorderviewcontroller\/imagepickercontroller(_:didfinishpickingmediawithinfo:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVVideoRecorderViewController\/imagePickerController(_:didFinishPickingMediaWithInfo:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1IVVideoRecorderViewController\/title","value":"IVVideoRecorderViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1IVVideoRecorderViewController\/fragments","value":[{"kind":"identifier","text":"IVVideoRecorderViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1IVVideoRecorderViewController~1imagePickerController(_:didFinishPickingMediaWithInfo:)\/title","value":"imagePickerController:didFinishPickingMediaWithInfo:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1IVVideoRecorderViewController~1imagePickerController(_:didFinishPickingMediaWithInfo:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imagePickerController:didFinishPickingMediaWithInfo:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}