{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TitleView","preciseIdentifier":"c:@M@Divar@objc(cs)TitleView","text":"TitleView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/verificationcodeinputviewcontroller\/titleview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/titleView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TitleView","preciseIdentifier":"c:@M@Divar@objc(cs)TitleView"}],"title":"titleView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar35VerificationCodeInputViewControllerC05titleE0AA05TitleE0Cvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController":{"role":"symbol","title":"VerificationCodeInputViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VerificationCodeInputViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VerificationCodeInputViewController"}],"url":"\/documentation\/divar\/verificationcodeinputviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/titleView":{"role":"symbol","title":"titleView","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TitleView","preciseIdentifier":"c:@M@Divar@objc(cs)TitleView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/titleView","kind":"symbol","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/titleview"},"doc://com.Divar.DivarClient/documentation/Divar/TitleView":{"role":"symbol","title":"TitleView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TitleView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TitleView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TitleView"}],"url":"\/documentation\/divar\/titleview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VerificationCodeInputViewController\/title","value":"VerificationCodeInputViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VerificationCodeInputViewController\/fragments","value":[{"kind":"identifier","text":"VerificationCodeInputViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TitleView\/title","value":"TitleView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TitleView\/fragments","value":[{"kind":"identifier","text":"TitleView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}