{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TitleView","preciseIdentifier":"c:@M@Divar@objc(cs)TitleView","text":"TitleView"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/noterowcollectionviewcell\/titleview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/noterowcollectionviewcell\/titleview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteRowCollectionViewCell\/titleView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TitleView","preciseIdentifier":"c:@M@Divar@objc(cs)TitleView"},{"kind":"text","text":"!"}],"title":"titleView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)NoteRowCollectionViewCell(py)titleView","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"titleView"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteRowCollectionViewCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/NoteRowCollectionViewCell":{"role":"symbol","title":"NoteRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NoteRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NoteRowCollectionViewCell"}],"url":"\/documentation\/divar\/noterowcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/TitleView":{"role":"symbol","title":"TitleView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TitleView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TitleView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TitleView"}],"url":"\/documentation\/divar\/titleview"},"doc://com.Divar.DivarClient/documentation/Divar/NoteRowCollectionViewCell/titleView":{"role":"symbol","title":"titleView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TitleView","preciseIdentifier":"c:@M@Divar@objc(cs)TitleView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteRowCollectionViewCell\/titleView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleView"}],"url":"\/documentation\/divar\/noterowcollectionviewcell\/titleview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"titleView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"titleView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TitleView","preciseIdentifier":"c:@M@Divar@objc(cs)TitleView","text":"TitleView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"titleView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteRowCollectionViewCell\/title","value":"NoteRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"NoteRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TitleView\/title","value":"TitleView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TitleView\/fragments","value":[{"kind":"identifier","text":"TitleView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteRowCollectionViewCell~1titleView\/title","value":"titleView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteRowCollectionViewCell~1titleView\/fragments","value":[{"kind":"identifier","text":"titleView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}