{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"wideButtonBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WideButtonViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WideButtonViewController","text":"WideButtonViewController"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/widgetbasedviewcontroller\/widebuttonbar"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/wideButtonBar","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"wideButtonBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WideButtonViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WideButtonViewController"}],"title":"wideButtonBar","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar25WidgetBasedViewControllerC13wideButtonBarAA04WidegdE0Cvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController":{"role":"symbol","title":"WidgetBasedViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedViewController"}],"url":"\/documentation\/divar\/widgetbasedviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/wideButtonBar":{"role":"symbol","title":"wideButtonBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"wideButtonBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WideButtonViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WideButtonViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/wideButtonBar","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetbasedviewcontroller\/widebuttonbar"},"doc://com.Divar.DivarClient/documentation/Divar/WideButtonViewController":{"role":"symbol","title":"WideButtonViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WideButtonViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WideButtonViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WideButtonViewController"}],"url":"\/documentation\/divar\/widebuttonviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedViewController\/title","value":"WidgetBasedViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WideButtonViewController\/title","value":"WideButtonViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WideButtonViewController\/fragments","value":[{"kind":"identifier","text":"WideButtonViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}