{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rateRowView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView","preciseIdentifier":"c:@M@Divar@objc(cs)RateRowView","text":"RateRowView"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/raterowcollectionviewcell\/raterowview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/raterowcollectionviewcell\/raterowview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowCollectionViewCell\/rateRowView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rateRowView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RateRowView","preciseIdentifier":"c:@M@Divar@objc(cs)RateRowView"},{"kind":"text","text":"!"}],"title":"rateRowView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)RateRowCollectionViewCell(py)rateRowView","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"rateRowView"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowCollectionViewCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/RateRowCollectionViewCell/rateRowView":{"role":"symbol","title":"rateRowView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rateRowView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RateRowView","preciseIdentifier":"c:@M@Divar@objc(cs)RateRowView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowCollectionViewCell\/rateRowView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rateRowView"}],"url":"\/documentation\/divar\/raterowcollectionviewcell\/raterowview"},"doc://com.Divar.DivarClient/documentation/Divar/RateRowCollectionViewCell":{"role":"symbol","title":"RateRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RateRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RateRowCollectionViewCell"}],"url":"\/documentation\/divar\/raterowcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/RateRowView":{"role":"symbol","title":"RateRowView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RateRowView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RateRowView"}],"url":"\/documentation\/divar\/raterowview"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"rateRowView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"rateRowView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView","preciseIdentifier":"c:@M@Divar@objc(cs)RateRowView","text":"RateRowView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"rateRowView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowCollectionViewCell~1rateRowView\/title","value":"rateRowView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowCollectionViewCell~1rateRowView\/fragments","value":[{"kind":"identifier","text":"rateRowView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowCollectionViewCell\/title","value":"RateRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"RateRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView\/title","value":"RateRowView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView\/fragments","value":[{"kind":"identifier","text":"RateRowView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}