{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SonnatHTMLLabel","preciseIdentifier":"c:@M@Sonnat@objc(cs)SonnatHTMLLabel"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/privacycell\/textmessage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/privacycell\/textmessage"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PrivacyCell\/textMessage","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SonnatHTMLLabel","preciseIdentifier":"c:@M@Sonnat@objc(cs)SonnatHTMLLabel"},{"kind":"text","text":"!"}],"title":"textMessage","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)PrivacyCell(py)textMessage","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"textMessage"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PrivacyCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PrivacyCell/textMessage":{"role":"symbol","title":"textMessage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SonnatHTMLLabel","preciseIdentifier":"c:@M@Sonnat@objc(cs)SonnatHTMLLabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PrivacyCell\/textMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textMessage"}],"url":"\/documentation\/divar\/privacycell\/textmessage"},"doc://com.Divar.DivarClient/documentation/Divar/PrivacyCell":{"role":"symbol","title":"PrivacyCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrivacyCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PrivacyCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PrivacyCell"}],"url":"\/documentation\/divar\/privacycell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"textMessage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"textMessage"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"SonnatHTMLLabel","preciseIdentifier":"c:objc(cs)SonnatHTMLLabel"},{"kind":"text","text":" * "},{"kind":"identifier","text":"textMessage"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PrivacyCell~1textMessage\/title","value":"textMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PrivacyCell~1textMessage\/fragments","value":[{"kind":"identifier","text":"textMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PrivacyCell\/title","value":"PrivacyCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PrivacyCell\/fragments","value":[{"kind":"identifier","text":"PrivacyCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}