{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"settingsViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"didSelectLogout"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SettingsViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SettingsViewController","text":"SettingsViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/settingsflowcontroller\/settingsviewcontroller(didselectlogout:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SettingsFlowController\/settingsViewController(didSelectLogout:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"SettingsViewControllerDelegate.settingsViewController(didSelectLogout:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"settingsViewController(didSelectLogout:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"settingsViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"didSelectLogout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SettingsViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SettingsViewController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar22SettingsFlowControllerC012settingsViewD015didSelectLogoutyAA0bfD0C_tF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SettingsFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SettingsFlowController\/SettingsViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/SettingsFlowController/settingsViewController(didSelectLogout:)":{"role":"symbol","title":"settingsViewController(didSelectLogout:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"settingsViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"didSelectLogout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SettingsViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SettingsViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SettingsFlowController\/settingsViewController(didSelectLogout:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/settingsflowcontroller\/settingsviewcontroller(didselectlogout:)"},"doc://com.Divar.DivarClient/documentation/Divar/SettingsFlowController/SettingsViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"SettingsViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SettingsFlowController\/SettingsViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/settingsflowcontroller\/settingsviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/SettingsFlowController":{"role":"symbol","title":"SettingsFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SettingsFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SettingsFlowController"}],"url":"\/documentation\/divar\/settingsflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SettingsViewController":{"role":"symbol","title":"SettingsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SettingsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SettingsViewController"}],"url":"\/documentation\/divar\/settingsviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SettingsFlowController\/title","value":"SettingsFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SettingsFlowController\/fragments","value":[{"kind":"identifier","text":"SettingsFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SettingsViewController\/title","value":"SettingsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SettingsViewController\/fragments","value":[{"kind":"identifier","text":"SettingsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}