{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialRegisterStoreDetail"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"navigationController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController","text":"NavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"landlineInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineState","preciseIdentifier":"s:5Divar13LandlineStateV","text":"LandlineState"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/marketplaceregisterflowcontroller\/initialregisterstoredetail(with:landlineinfo:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceRegisterFlowController\/initialRegisterStoreDetail(with:landlineInfo:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialRegisterStoreDetail"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"landlineInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LandlineState","preciseIdentifier":"s:5Divar13LandlineStateV"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"title":"initialRegisterStoreDetail(with:landlineInfo:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:5Divar33MarketplaceRegisterFlowControllerC07initialC11StoreDetail4with12landlineInfoSo06UIViewE0CAA010NavigationE0C_AA13LandlineStateVSgtF","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceRegisterFlowController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/MarketplaceRegisterFlowController":{"role":"symbol","title":"MarketplaceRegisterFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketplaceRegisterFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceRegisterFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketplaceRegisterFlowController"}],"url":"\/documentation\/divar\/marketplaceregisterflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/NavigationController":{"role":"symbol","title":"NavigationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NavigationController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NavigationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NavigationController"}],"url":"\/documentation\/divar\/navigationcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/LandlineState":{"role":"symbol","title":"LandlineState","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandlineState"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandlineState"}],"url":"\/documentation\/divar\/landlinestate"},"doc://com.Divar.DivarClient/documentation/Divar/MarketplaceRegisterFlowController/initialRegisterStoreDetail(with:landlineInfo:)":{"role":"symbol","title":"initialRegisterStoreDetail(with:landlineInfo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialRegisterStoreDetail"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"landlineInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LandlineState","preciseIdentifier":"s:5Divar13LandlineStateV"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceRegisterFlowController\/initialRegisterStoreDetail(with:landlineInfo:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/marketplaceregisterflowcontroller\/initialregisterstoredetail(with:landlineinfo:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceRegisterFlowController\/title","value":"MarketplaceRegisterFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceRegisterFlowController\/fragments","value":[{"kind":"identifier","text":"MarketplaceRegisterFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NavigationController\/title","value":"NavigationController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NavigationController\/fragments","value":[{"kind":"identifier","text":"NavigationController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}