{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableList"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"SelectableItem"},{"kind":"text","text":">("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"disbaleList"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisableListViewController","preciseIdentifier":"c:@M@Divar@objc(cs)DisableListViewController","text":"DisableListViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"stateChanged"},{"kind":"text","text":" "},{"kind":"internalParam","text":"items"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"SelectableItem","preciseIdentifier":"s:5Divar25DisablePageViewControllerC11disableList_12stateChangedyAA0bgdE0C_ShyxGtAA015SelectablePostsG4ItemRzlF0jL0L_xmfp"},{"kind":"text","text":">) "},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SelectableItem"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SelectablePostsListItem","preciseIdentifier":"s:5Divar23SelectablePostsListItemP","text":"SelectablePostsListItem"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/disablepageviewcontroller\/disablelist(_:statechanged:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/disableList(_:stateChanged:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"DisableListViewControllerDelegate.disableList(_:stateChanged:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"disableList(_:stateChanged:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableList"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"SelectableItem"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"DisableListViewController","preciseIdentifier":"c:@M@Divar@objc(cs)DisableListViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"stateChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"SelectableItem","preciseIdentifier":"s:5Divar25DisablePageViewControllerC11disableList_12stateChangedyAA0bgdE0C_ShyxGtAA015SelectablePostsG4ItemRzlF0jL0L_xmfp"},{"kind":"text","text":">)"}],"symbolKind":"method","externalID":"s:5Divar25DisablePageViewControllerC11disableList_12stateChangedyAA0bgdE0C_ShyxGtAA015SelectablePostsG4ItemRzlF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/DisableListViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/DisablePageViewController":{"role":"symbol","title":"DisablePageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisablePageViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DisablePageViewController"}],"url":"\/documentation\/divar\/disablepageviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/DisablePageViewController/disableList(_:stateChanged:)":{"role":"symbol","title":"disableList(_:stateChanged:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableList"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"SelectableItem"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"DisableListViewController","preciseIdentifier":"c:@M@Divar@objc(cs)DisableListViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"stateChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"SelectableItem","preciseIdentifier":"s:5Divar25DisablePageViewControllerC11disableList_12stateChangedyAA0bgdE0C_ShyxGtAA015SelectablePostsG4ItemRzlF0jL0L_xmfp"},{"kind":"text","text":">)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/disableList(_:stateChanged:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/disablepageviewcontroller\/disablelist(_:statechanged:)"},"doc://com.Divar.DivarClient/documentation/Divar/SelectablePostsListItem":{"role":"symbol","title":"SelectablePostsListItem","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SelectablePostsListItem"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SelectablePostsListItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SelectablePostsListItem"}],"url":"\/documentation\/divar\/selectablepostslistitem"},"doc://com.Divar.DivarClient/documentation/Divar/DisablePageViewController/DisableListViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"DisableListViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/DisableListViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/disablepageviewcontroller\/disablelistviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/DisableListViewController":{"role":"symbol","title":"DisableListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisableListViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisableListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DisableListViewController"}],"url":"\/documentation\/divar\/disablelistviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DisablePageViewController\/title","value":"DisablePageViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DisablePageViewController\/fragments","value":[{"kind":"identifier","text":"DisablePageViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DisableListViewController\/title","value":"DisableListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DisableListViewController\/fragments","value":[{"kind":"identifier","text":"DisableListViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}