{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationTransitionWillBegin"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/panmodalpresentationcontroller\/presentationtransitionwillbegin()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/panmodalpresentationcontroller\/presentationtransitionwillbegin()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/presentationTransitionWillBegin()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationTransitionWillBegin"},{"kind":"text","text":"()"}],"title":"presentationTransitionWillBegin()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Divar@objc(cs)PanModalPresentationController(im)presentationTransitionWillBegin","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"presentationTransitionWillBegin"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationController":{"role":"symbol","title":"PanModalPresentationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresentationController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresentationController"}],"url":"\/documentation\/divar\/panmodalpresentationcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationController/presentationTransitionWillBegin()":{"role":"symbol","title":"presentationTransitionWillBegin()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationTransitionWillBegin"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/presentationTransitionWillBegin()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentationTransitionWillBegin"}],"url":"\/documentation\/divar\/panmodalpresentationcontroller\/presentationtransitionwillbegin()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"presentationTransitionWillBegin"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentationTransitionWillBegin"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"presentationTransitionWillBegin"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationController\/title","value":"PanModalPresentationController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationController\/fragments","value":[{"kind":"identifier","text":"PanModalPresentationController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationController~1presentationTransitionWillBegin()\/title","value":"presentationTransitionWillBegin"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationController~1presentationTransitionWillBegin()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentationTransitionWillBegin"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}