{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"priceView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceEstimationView","preciseIdentifier":"c:@M@Divar@objc(cs)PriceEstimationView","text":"PriceEstimationView"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/priceestimationcollectionviewcell\/priceview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/priceestimationcollectionviewcell\/priceview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceEstimationCollectionViewCell\/priceView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"priceView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PriceEstimationView","preciseIdentifier":"c:@M@Divar@objc(cs)PriceEstimationView"},{"kind":"text","text":"!"}],"title":"priceView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)PriceEstimationCollectionViewCell(py)priceView","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"priceView"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceEstimationCollectionViewCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PriceEstimationView":{"role":"symbol","title":"PriceEstimationView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PriceEstimationView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceEstimationView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PriceEstimationView"}],"url":"\/documentation\/divar\/priceestimationview"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PriceEstimationCollectionViewCell":{"role":"symbol","title":"PriceEstimationCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PriceEstimationCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceEstimationCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PriceEstimationCollectionViewCell"}],"url":"\/documentation\/divar\/priceestimationcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/PriceEstimationCollectionViewCell/priceView":{"role":"symbol","title":"priceView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"priceView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PriceEstimationView","preciseIdentifier":"c:@M@Divar@objc(cs)PriceEstimationView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceEstimationCollectionViewCell\/priceView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"priceView"}],"url":"\/documentation\/divar\/priceestimationcollectionviewcell\/priceview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"priceView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"priceView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceEstimationView","preciseIdentifier":"c:@M@Divar@objc(cs)PriceEstimationView","text":"PriceEstimationView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"priceView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceEstimationView\/title","value":"PriceEstimationView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceEstimationView\/fragments","value":[{"kind":"identifier","text":"PriceEstimationView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceEstimationCollectionViewCell\/title","value":"PriceEstimationCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceEstimationCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"PriceEstimationCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceEstimationCollectionViewCell~1priceView\/title","value":"priceView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceEstimationCollectionViewCell~1priceView\/fragments","value":[{"kind":"identifier","text":"priceView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}