{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rotateAction"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/gaugechartcollectionviewcell\/rotateaction()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/gaugechartcollectionviewcell\/rotateaction()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GaugeChartCollectionViewCell\/rotateAction()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rotateAction"},{"kind":"text","text":"()"}],"title":"rotateAction()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Divar@objc(cs)GaugeChartCollectionViewCell(im)rotateAction","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"rotateAction"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GaugeChartCollectionViewCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/GaugeChartCollectionViewCell":{"role":"symbol","title":"GaugeChartCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GaugeChartCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GaugeChartCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GaugeChartCollectionViewCell"}],"url":"\/documentation\/divar\/gaugechartcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/GaugeChartCollectionViewCell/rotateAction()":{"role":"symbol","title":"rotateAction()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rotateAction"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GaugeChartCollectionViewCell\/rotateAction()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rotateAction"}],"url":"\/documentation\/divar\/gaugechartcollectionviewcell\/rotateaction()"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"rotateAction"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rotateAction"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"rotateAction"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GaugeChartCollectionViewCell\/title","value":"GaugeChartCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GaugeChartCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"GaugeChartCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GaugeChartCollectionViewCell~1rotateAction()\/title","value":"rotateAction"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GaugeChartCollectionViewCell~1rotateAction()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rotateAction"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}