{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mapView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKMapView","preciseIdentifier":"c:objc(cs)MKMapView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewFor"},{"kind":"text","text":" "},{"kind":"internalParam","text":"annotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKAnnotation","preciseIdentifier":"c:objc(pl)MKAnnotation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MKAnnotationView","preciseIdentifier":"c:objc(cs)MKAnnotationView"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/mapdetailsviewcontroller\/mapview(_:viewfor:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/mapdetailsviewcontroller\/mapview(_:viewfor:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController\/mapView(_:viewFor:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"MKMapViewDelegate.mapView(_:viewFor:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"mapView:viewForAnnotation:"}],"role":"symbol","title":"mapView(_:viewFor:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapView","preciseIdentifier":"c:objc(cs)MKMapView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKAnnotation","preciseIdentifier":"c:objc(pl)MKAnnotation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MKAnnotationView","preciseIdentifier":"c:objc(cs)MKAnnotationView"},{"kind":"text","text":"?"}],"symbolKind":"method","externalID":"c:@CM@Divar@objc(cs)MapDetailsViewController(im)mapView:viewForAnnotation:","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController\/MKMapViewDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/MapDetailsViewController/MKMapViewDelegate-Implementations":{"role":"collectionGroup","title":"MKMapViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController\/MKMapViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/mapdetailsviewcontroller\/mkmapviewdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/MapDetailsViewController/mapView(_:viewFor:)":{"role":"symbol","title":"mapView(_:viewFor:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapView","preciseIdentifier":"c:objc(cs)MKMapView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKAnnotation","preciseIdentifier":"c:objc(pl)MKAnnotation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MKAnnotationView","preciseIdentifier":"c:objc(cs)MKAnnotationView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController\/mapView(_:viewFor:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mapView:viewForAnnotation:"}],"url":"\/documentation\/divar\/mapdetailsviewcontroller\/mapview(_:viewfor:)"},"doc://com.Divar.DivarClient/documentation/Divar/MapDetailsViewController":{"role":"symbol","title":"MapDetailsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapDetailsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapDetailsViewController"}],"url":"\/documentation\/divar\/mapdetailsviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"mapView:viewForAnnotation:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mapView:viewForAnnotation:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"MKAnnotationView","preciseIdentifier":"c:objc(cs)MKAnnotationView"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"mapView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapView","preciseIdentifier":"c:objc(cs)MKMapView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"mapView"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewForAnnotation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<MKAnnotation>","preciseIdentifier":"c:Qoobjc(pl)MKAnnotation"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"annotation"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDetailsViewController~1mapView(_:viewFor:)\/title","value":"mapView:viewForAnnotation:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDetailsViewController~1mapView(_:viewFor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mapView:viewForAnnotation:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDetailsViewController\/title","value":"MapDetailsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDetailsViewController\/fragments","value":[{"kind":"identifier","text":"MapDetailsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}