{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mapView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKMapView","preciseIdentifier":"c:objc(cs)MKMapView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rendererFor"},{"kind":"text","text":" "},{"kind":"internalParam","text":"overlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKOverlay","preciseIdentifier":"c:objc(pl)MKOverlay"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MKOverlayRenderer","preciseIdentifier":"c:objc(cs)MKOverlayRenderer"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/mapdetailsviewcontroller\/mapview(_:rendererfor:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/mapdetailsviewcontroller\/mapview(_:rendererfor:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController\/mapView(_:rendererFor:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"MKMapViewDelegate.mapView(_:rendererFor:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"mapView:rendererForOverlay:"}],"role":"symbol","title":"mapView(_:rendererFor:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapView","preciseIdentifier":"c:objc(cs)MKMapView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rendererFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKOverlay","preciseIdentifier":"c:objc(pl)MKOverlay"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MKOverlayRenderer","preciseIdentifier":"c:objc(cs)MKOverlayRenderer"}],"symbolKind":"method","externalID":"c:@CM@Divar@objc(cs)MapDetailsViewController(im)mapView:rendererForOverlay:","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController\/MKMapViewDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/MapDetailsViewController/MKMapViewDelegate-Implementations":{"role":"collectionGroup","title":"MKMapViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController\/MKMapViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/mapdetailsviewcontroller\/mkmapviewdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/MapDetailsViewController/mapView(_:rendererFor:)":{"role":"symbol","title":"mapView(_:rendererFor:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapView","preciseIdentifier":"c:objc(cs)MKMapView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rendererFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKOverlay","preciseIdentifier":"c:objc(pl)MKOverlay"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MKOverlayRenderer","preciseIdentifier":"c:objc(cs)MKOverlayRenderer"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController\/mapView(_:rendererFor:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mapView:rendererForOverlay:"}],"url":"\/documentation\/divar\/mapdetailsviewcontroller\/mapview(_:rendererfor:)"},"doc://com.Divar.DivarClient/documentation/Divar/MapDetailsViewController":{"role":"symbol","title":"MapDetailsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapDetailsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapDetailsViewController"}],"url":"\/documentation\/divar\/mapdetailsviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"mapView:rendererForOverlay:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mapView:rendererForOverlay:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"MKOverlayRenderer","preciseIdentifier":"c:objc(cs)MKOverlayRenderer"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"mapView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapView","preciseIdentifier":"c:objc(cs)MKMapView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"mapView"},{"kind":"text","text":" "},{"kind":"identifier","text":"rendererForOverlay:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<MKOverlay>","preciseIdentifier":"c:Qoobjc(pl)MKOverlay"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"overlay"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDetailsViewController~1mapView(_:rendererFor:)\/title","value":"mapView:rendererForOverlay:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDetailsViewController~1mapView(_:rendererFor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mapView:rendererForOverlay:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDetailsViewController\/title","value":"MapDetailsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDetailsViewController\/fragments","value":[{"kind":"identifier","text":"MapDetailsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}