{"variants":[{"paths":["\/documentation\/divar\/mapdetailsviewcontroller\/mkmapviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/mapdetailsviewcontroller\/mkmapviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController\/MKMapViewDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController\/mapView(_:rendererFor:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController\/mapView(_:viewFor:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"MKMapViewDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/MapDetailsViewController/mapView(_:rendererFor:)":{"role":"symbol","title":"mapView(_:rendererFor:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapView","preciseIdentifier":"c:objc(cs)MKMapView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rendererFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKOverlay","preciseIdentifier":"c:objc(pl)MKOverlay"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MKOverlayRenderer","preciseIdentifier":"c:objc(cs)MKOverlayRenderer"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController\/mapView(_:rendererFor:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mapView:rendererForOverlay:"}],"url":"\/documentation\/divar\/mapdetailsviewcontroller\/mapview(_:rendererfor:)"},"doc://com.Divar.DivarClient/documentation/Divar/MapDetailsViewController/mapView(_:viewFor:)":{"role":"symbol","title":"mapView(_:viewFor:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapView","preciseIdentifier":"c:objc(cs)MKMapView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKAnnotation","preciseIdentifier":"c:objc(pl)MKAnnotation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MKAnnotationView","preciseIdentifier":"c:objc(cs)MKAnnotationView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController\/mapView(_:viewFor:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mapView:viewForAnnotation:"}],"url":"\/documentation\/divar\/mapdetailsviewcontroller\/mapview(_:viewfor:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/MapDetailsViewController":{"role":"symbol","title":"MapDetailsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapDetailsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapDetailsViewController"}],"url":"\/documentation\/divar\/mapdetailsviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController\/mapView(_:rendererFor:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController\/mapView(_:viewFor:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDetailsViewController~1mapView(_:rendererFor:)\/title","value":"mapView:rendererForOverlay:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDetailsViewController~1mapView(_:rendererFor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mapView:rendererForOverlay:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDetailsViewController~1mapView(_:viewFor:)\/title","value":"mapView:viewForAnnotation:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDetailsViewController~1mapView(_:viewFor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mapView:viewForAnnotation:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDetailsViewController\/title","value":"MapDetailsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDetailsViewController\/fragments","value":[{"kind":"identifier","text":"MapDetailsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}