{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"wideButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WideButtonViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WideButtonViewController","text":"WideButtonViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/mapdetailsviewcontroller\/widebutton"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController\/wideButton","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"wideButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WideButtonViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WideButtonViewController"}],"title":"wideButton","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar24MapDetailsViewControllerC10wideButtonAA04WidegdE0Cvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/MapDetailsViewController/wideButton":{"role":"symbol","title":"wideButton","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"wideButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WideButtonViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WideButtonViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController\/wideButton","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mapdetailsviewcontroller\/widebutton"},"doc://com.Divar.DivarClient/documentation/Divar/WideButtonViewController":{"role":"symbol","title":"WideButtonViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WideButtonViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WideButtonViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WideButtonViewController"}],"url":"\/documentation\/divar\/widebuttonviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/MapDetailsViewController":{"role":"symbol","title":"MapDetailsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapDetailsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapDetailsViewController"}],"url":"\/documentation\/divar\/mapdetailsviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WideButtonViewController\/title","value":"WideButtonViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WideButtonViewController\/fragments","value":[{"kind":"identifier","text":"WideButtonViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDetailsViewController\/title","value":"MapDetailsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDetailsViewController\/fragments","value":[{"kind":"identifier","text":"MapDetailsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}