{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagView","preciseIdentifier":"c:@M@Divar@objc(cs)TagView","text":"TagView"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/tagviewcollectionviewcell\/tagview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/tagviewcollectionviewcell\/tagview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagViewCollectionViewCell\/tagView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagView","preciseIdentifier":"c:@M@Divar@objc(cs)TagView"},{"kind":"text","text":"!"}],"title":"tagView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)TagViewCollectionViewCell(py)tagView","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"tagView"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagViewCollectionViewCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/TagViewCollectionViewCell":{"role":"symbol","title":"TagViewCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagViewCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagViewCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagViewCollectionViewCell"}],"url":"\/documentation\/divar\/tagviewcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/TagView":{"role":"symbol","title":"TagView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagView"}],"url":"\/documentation\/divar\/tagview"},"doc://com.Divar.DivarClient/documentation/Divar/TagViewCollectionViewCell/tagView":{"role":"symbol","title":"tagView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagView","preciseIdentifier":"c:@M@Divar@objc(cs)TagView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagViewCollectionViewCell\/tagView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tagView"}],"url":"\/documentation\/divar\/tagviewcollectionviewcell\/tagview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"tagView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"tagView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagView","preciseIdentifier":"c:@M@Divar@objc(cs)TagView","text":"TagView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"tagView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagViewCollectionViewCell\/title","value":"TagViewCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagViewCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"TagViewCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagView\/title","value":"TagView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagView\/fragments","value":[{"kind":"identifier","text":"TagView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagViewCollectionViewCell~1tagView\/title","value":"tagView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagViewCollectionViewCell~1tagView\/fragments","value":[{"kind":"identifier","text":"tagView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}