{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionSheet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController","preciseIdentifier":"c:@M@Divar@objc(cs)BottomSheetViewController","text":"BottomSheetViewController"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/rangeselecttableviewcell\/actionsheet"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/actionSheet","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionSheet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BottomSheetViewController","preciseIdentifier":"c:@M@Divar@objc(cs)BottomSheetViewController"},{"kind":"text","text":"?"}],"title":"actionSheet","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar24RangeSelectTableViewCellC11actionSheetAA06BottomhE10ControllerCSgvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController":{"role":"symbol","title":"BottomSheetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BottomSheetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BottomSheetViewController"}],"url":"\/documentation\/divar\/bottomsheetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell/actionSheet":{"role":"symbol","title":"actionSheet","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionSheet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BottomSheetViewController","preciseIdentifier":"c:@M@Divar@objc(cs)BottomSheetViewController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/actionSheet","kind":"symbol","type":"topic","url":"\/documentation\/divar\/rangeselecttableviewcell\/actionsheet"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell":{"role":"symbol","title":"RangeSelectTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RangeSelectTableViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RangeSelectTableViewCell"}],"url":"\/documentation\/divar\/rangeselecttableviewcell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetViewController\/title","value":"BottomSheetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetViewController\/fragments","value":[{"kind":"identifier","text":"BottomSheetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RangeSelectTableViewCell\/title","value":"RangeSelectTableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RangeSelectTableViewCell\/fragments","value":[{"kind":"identifier","text":"RangeSelectTableViewCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}