{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostfixTextField","preciseIdentifier":"c:@M@Divar@objc(cs)PostfixTextField","text":"PostfixTextField"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/rangeselecttableviewcell\/textfield"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/rangeselecttableviewcell\/textfield"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/textField","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostfixTextField","preciseIdentifier":"c:@M@Divar@objc(cs)PostfixTextField"},{"kind":"text","text":"!"}],"title":"textField","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)RangeSelectTableViewCell(py)textField","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"textField"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell":{"role":"symbol","title":"RangeSelectTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RangeSelectTableViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RangeSelectTableViewCell"}],"url":"\/documentation\/divar\/rangeselecttableviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell/textField":{"role":"symbol","title":"textField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostfixTextField","preciseIdentifier":"c:@M@Divar@objc(cs)PostfixTextField"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/textField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textField"}],"url":"\/documentation\/divar\/rangeselecttableviewcell\/textfield"},"doc://com.Divar.DivarClient/documentation/Divar/PostfixTextField":{"role":"symbol","title":"PostfixTextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostfixTextField"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostfixTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostfixTextField"}],"url":"\/documentation\/divar\/postfixtextfield"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"textField"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"textField"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostfixTextField","preciseIdentifier":"c:@M@Divar@objc(cs)PostfixTextField","text":"PostfixTextField"},{"kind":"text","text":" * "},{"kind":"identifier","text":"textField"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RangeSelectTableViewCell\/title","value":"RangeSelectTableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RangeSelectTableViewCell\/fragments","value":[{"kind":"identifier","text":"RangeSelectTableViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RangeSelectTableViewCell~1textField\/title","value":"textField"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RangeSelectTableViewCell~1textField\/fragments","value":[{"kind":"identifier","text":"textField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostfixTextField\/title","value":"PostfixTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostfixTextField\/fragments","value":[{"kind":"identifier","text":"PostfixTextField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}