{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pickerView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectRow"},{"kind":"text","text":" "},{"kind":"internalParam","text":"row"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inComponent"},{"kind":"text","text":" "},{"kind":"internalParam","text":"_"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/custompickerhandler\/pickerview(_:didselectrow:incomponent:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/custompickerhandler\/pickerview(_:didselectrow:incomponent:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/pickerView(_:didSelectRow:inComponent:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIPickerViewDelegate.pickerView(_:didSelectRow:inComponent:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pickerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"pickerView(_:didSelectRow:inComponent:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Divar@objc(cs)CustomPickerHandler(im)pickerView:didSelectRow:inComponent:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"pickerView:didSelectRow:inComponent:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/CustomPickerHandler/pickerView(_:didSelectRow:inComponent:)":{"role":"symbol","title":"pickerView(_:didSelectRow:inComponent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pickerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/pickerView(_:didSelectRow:inComponent:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pickerView:didSelectRow:inComponent:"}],"url":"\/documentation\/divar\/custompickerhandler\/pickerview(_:didselectrow:incomponent:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/CustomPickerHandler":{"role":"symbol","title":"CustomPickerHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomPickerHandler"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomPickerHandler"}],"url":"\/documentation\/divar\/custompickerhandler"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"pickerView:didSelectRow:inComponent:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pickerView:didSelectRow:inComponent:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"pickerView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"_"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSelectRow:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"row"},{"kind":"text","text":" "},{"kind":"identifier","text":"inComponent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"_"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomPickerHandler~1pickerView(_:didSelectRow:inComponent:)\/title","value":"pickerView:didSelectRow:inComponent:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomPickerHandler~1pickerView(_:didSelectRow:inComponent:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pickerView:didSelectRow:inComponent:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomPickerHandler\/title","value":"CustomPickerHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomPickerHandler\/fragments","value":[{"kind":"identifier","text":"CustomPickerHandler"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}