{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"manager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailWithError"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/locationmanager\/locationmanager(_:didfailwitherror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/locationmanager\/locationmanager(_:didfailwitherror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationManager\/locationManager(_:didFailWithError:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CLLocationManagerDelegate.locationManager(_:didFailWithError:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"title":"locationManager(_:didFailWithError:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Divar@objc(cs)LocationManager(im)locationManager:didFailWithError:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"locationManager:didFailWithError:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationManager"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/LocationManager":{"role":"symbol","title":"LocationManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationManager"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationManager"}],"url":"\/documentation\/divar\/locationmanager"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/LocationManager/locationManager(_:didFailWithError:)":{"role":"symbol","title":"locationManager(_:didFailWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationManager\/locationManager(_:didFailWithError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"locationManager:didFailWithError:"}],"url":"\/documentation\/divar\/locationmanager\/locationmanager(_:didfailwitherror:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"locationManager:didFailWithError:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationManager:didFailWithError:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"locationManager:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"manager"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFailWithError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LocationManager\/title","value":"LocationManager"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LocationManager\/fragments","value":[{"kind":"identifier","text":"LocationManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LocationManager~1locationManager(_:didFailWithError:)\/title","value":"locationManager:didFailWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LocationManager~1locationManager(_:didFailWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationManager:didFailWithError:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}