{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"descriptionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionView","preciseIdentifier":"c:@M@Divar@objc(cs)DescriptionView","text":"DescriptionView"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/descriptiontextrow\/descriptionview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/descriptiontextrow\/descriptionview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionTextRow\/descriptionView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"descriptionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DescriptionView","preciseIdentifier":"c:@M@Divar@objc(cs)DescriptionView"},{"kind":"text","text":"!"}],"title":"descriptionView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)DescriptionTextRow(py)descriptionView","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"descriptionView"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionTextRow"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/DescriptionTextRow":{"role":"symbol","title":"DescriptionTextRow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DescriptionTextRow"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionTextRow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DescriptionTextRow"}],"url":"\/documentation\/divar\/descriptiontextrow"},"doc://com.Divar.DivarClient/documentation/Divar/DescriptionTextRow/descriptionView":{"role":"symbol","title":"descriptionView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"descriptionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DescriptionView","preciseIdentifier":"c:@M@Divar@objc(cs)DescriptionView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionTextRow\/descriptionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"descriptionView"}],"url":"\/documentation\/divar\/descriptiontextrow\/descriptionview"},"doc://com.Divar.DivarClient/documentation/Divar/DescriptionView":{"role":"symbol","title":"DescriptionView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DescriptionView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DescriptionView"}],"url":"\/documentation\/divar\/descriptionview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"descriptionView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"descriptionView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionView","preciseIdentifier":"c:@M@Divar@objc(cs)DescriptionView","text":"DescriptionView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"descriptionView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DescriptionTextRow\/title","value":"DescriptionTextRow"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DescriptionTextRow\/fragments","value":[{"kind":"identifier","text":"DescriptionTextRow"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DescriptionTextRow~1descriptionView\/title","value":"descriptionView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DescriptionTextRow~1descriptionView\/fragments","value":[{"kind":"identifier","text":"descriptionView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DescriptionView\/title","value":"DescriptionView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DescriptionView\/fragments","value":[{"kind":"identifier","text":"DescriptionView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}