{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapExpand"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"descriptionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionView","preciseIdentifier":"c:@M@Divar@objc(cs)DescriptionView","text":"DescriptionView"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/descriptiontextrow\/didtapexpand(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionTextRow\/didTapExpand(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"DescriptionViewProtocol.didTapExpand(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapExpand"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DescriptionView","preciseIdentifier":"c:@M@Divar@objc(cs)DescriptionView"},{"kind":"text","text":")"}],"title":"didTapExpand(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:5Divar18DescriptionTextRowC12didTapExpandyyAA0B4ViewCF","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionTextRow"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/DescriptionTextRow/didTapExpand(_:)":{"role":"symbol","title":"didTapExpand(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapExpand"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DescriptionView","preciseIdentifier":"c:@M@Divar@objc(cs)DescriptionView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionTextRow\/didTapExpand(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/descriptiontextrow\/didtapexpand(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/DescriptionView":{"role":"symbol","title":"DescriptionView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DescriptionView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DescriptionView"}],"url":"\/documentation\/divar\/descriptionview"},"doc://com.Divar.DivarClient/documentation/Divar/DescriptionTextRow":{"role":"symbol","title":"DescriptionTextRow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DescriptionTextRow"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionTextRow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DescriptionTextRow"}],"url":"\/documentation\/divar\/descriptiontextrow"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DescriptionView\/title","value":"DescriptionView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DescriptionView\/fragments","value":[{"kind":"identifier","text":"DescriptionView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DescriptionTextRow\/title","value":"DescriptionTextRow"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DescriptionTextRow\/fragments","value":[{"kind":"identifier","text":"DescriptionTextRow"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}