{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FileInfo","preciseIdentifier":"c:@M@Divar@objc(cs)FileInfo","text":"FileInfo"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/quicklookviewcontroller\/fileinfo"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/fileInfo","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"FileInfo","preciseIdentifier":"c:@M@Divar@objc(cs)FileInfo"},{"kind":"text","text":"]"}],"title":"fileInfo","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar23QuickLookViewControllerC8fileInfoSayAA04FileG0CGvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/FileInfo":{"role":"symbol","title":"FileInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileInfo"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FileInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FileInfo"}],"url":"\/documentation\/divar\/fileinfo"},"doc://com.Divar.DivarClient/documentation/Divar/QuickLookViewController/fileInfo":{"role":"symbol","title":"fileInfo","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"FileInfo","preciseIdentifier":"c:@M@Divar@objc(cs)FileInfo"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/fileInfo","kind":"symbol","type":"topic","url":"\/documentation\/divar\/quicklookviewcontroller\/fileinfo"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/QuickLookViewController":{"role":"symbol","title":"QuickLookViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QuickLookViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QuickLookViewController"}],"url":"\/documentation\/divar\/quicklookviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FileInfo\/title","value":"FileInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FileInfo\/fragments","value":[{"kind":"identifier","text":"FileInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1QuickLookViewController\/title","value":"QuickLookViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1QuickLookViewController\/fragments","value":[{"kind":"identifier","text":"QuickLookViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}