{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fileInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FileInfo","preciseIdentifier":"c:@M@Divar@objc(cs)FileInfo","text":"FileInfo"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/quicklookviewcontroller\/init(fileinfo:index:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/init(fileInfo:index:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fileInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"FileInfo","preciseIdentifier":"c:@M@Divar@objc(cs)FileInfo"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"init(fileInfo:index:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:5Divar23QuickLookViewControllerC8fileInfo5indexACSayAA04FileG0CG_Sitcfc","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/QuickLookViewController":{"role":"symbol","title":"QuickLookViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QuickLookViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QuickLookViewController"}],"url":"\/documentation\/divar\/quicklookviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/QuickLookViewController/init(fileInfo:index:)":{"role":"symbol","title":"init(fileInfo:index:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fileInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"FileInfo","preciseIdentifier":"c:@M@Divar@objc(cs)FileInfo"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/init(fileInfo:index:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/quicklookviewcontroller\/init(fileinfo:index:)"},"doc://com.Divar.DivarClient/documentation/Divar/FileInfo":{"role":"symbol","title":"FileInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileInfo"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FileInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FileInfo"}],"url":"\/documentation\/divar\/fileinfo"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1QuickLookViewController\/title","value":"QuickLookViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1QuickLookViewController\/fragments","value":[{"kind":"identifier","text":"QuickLookViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FileInfo\/title","value":"FileInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FileInfo\/fragments","value":[{"kind":"identifier","text":"FileInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}