{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previewItemAt"},{"kind":"text","text":" "},{"kind":"internalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"QLPreviewItem","preciseIdentifier":"c:objc(pl)QLPreviewItem"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/quicklookviewcontroller\/previewcontroller(_:previewitemat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/quicklookviewcontroller\/previewcontroller(_:previewitemat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/previewController(_:previewItemAt:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"QLPreviewControllerDataSource.previewController(_:previewItemAt:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previewItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"QLPreviewItem","preciseIdentifier":"c:objc(pl)QLPreviewItem"}],"title":"previewController(_:previewItemAt:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Divar@objc(cs)QuickLookViewController(im)previewController:previewItemAtIndex:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"previewController:previewItemAtIndex:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/QuickLookViewController":{"role":"symbol","title":"QuickLookViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QuickLookViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QuickLookViewController"}],"url":"\/documentation\/divar\/quicklookviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/QuickLookViewController/previewController(_:previewItemAt:)":{"role":"symbol","title":"previewController(_:previewItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previewItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"QLPreviewItem","preciseIdentifier":"c:objc(pl)QLPreviewItem"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/previewController(_:previewItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"previewController:previewItemAtIndex:"}],"url":"\/documentation\/divar\/quicklookviewcontroller\/previewcontroller(_:previewitemat:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"previewController:previewItemAtIndex:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"previewController:previewItemAtIndex:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id<QLPreviewItem>","preciseIdentifier":"c:Qoobjc(pl)QLPreviewItem"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"previewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"_"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewItemAtIndex:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"index"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1QuickLookViewController\/title","value":"QuickLookViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1QuickLookViewController\/fragments","value":[{"kind":"identifier","text":"QuickLookViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1QuickLookViewController~1previewController(_:previewItemAt:)\/title","value":"previewController:previewItemAtIndex:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1QuickLookViewController~1previewController(_:previewItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"previewController:previewItemAtIndex:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}