{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mainImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SonnatImageView","preciseIdentifier":"c:@M@Sonnat@objc(cs)SonnatImageView"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/imagecarouselcell\/mainimage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/imagecarouselcell\/mainimage"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImageCarouselCell\/mainImage","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mainImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SonnatImageView","preciseIdentifier":"c:@M@Sonnat@objc(cs)SonnatImageView"},{"kind":"text","text":"!"}],"title":"mainImage","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)ImageCarouselCell(py)mainImage","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"mainImage"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImageCarouselCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ImageCarouselCell":{"role":"symbol","title":"ImageCarouselCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageCarouselCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImageCarouselCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageCarouselCell"}],"url":"\/documentation\/divar\/imagecarouselcell"},"doc://com.Divar.DivarClient/documentation/Divar/ImageCarouselCell/mainImage":{"role":"symbol","title":"mainImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mainImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SonnatImageView","preciseIdentifier":"c:@M@Sonnat@objc(cs)SonnatImageView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImageCarouselCell\/mainImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mainImage"}],"url":"\/documentation\/divar\/imagecarouselcell\/mainimage"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"mainImage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mainImage"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"SonnatImageView","preciseIdentifier":"c:objc(cs)SonnatImageView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"mainImage"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImageCarouselCell\/title","value":"ImageCarouselCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImageCarouselCell\/fragments","value":[{"kind":"identifier","text":"ImageCarouselCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImageCarouselCell~1mainImage\/title","value":"mainImage"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImageCarouselCell~1mainImage\/fragments","value":[{"kind":"identifier","text":"mainImage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}