{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaSlider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MediaSlider","preciseIdentifier":"c:@M@Sonnat@objc(cs)MediaSlider"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/imageslidercollectionviewcell\/mediaslider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/imageslidercollectionviewcell\/mediaslider"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImageSliderCollectionViewCell\/mediaSlider","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaSlider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MediaSlider","preciseIdentifier":"c:@M@Sonnat@objc(cs)MediaSlider"},{"kind":"text","text":"!"}],"title":"mediaSlider","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)ImageSliderCollectionViewCell(py)mediaSlider","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"mediaSlider"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImageSliderCollectionViewCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ImageSliderCollectionViewCell/mediaSlider":{"role":"symbol","title":"mediaSlider","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaSlider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MediaSlider","preciseIdentifier":"c:@M@Sonnat@objc(cs)MediaSlider"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImageSliderCollectionViewCell\/mediaSlider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mediaSlider"}],"url":"\/documentation\/divar\/imageslidercollectionviewcell\/mediaslider"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/ImageSliderCollectionViewCell":{"role":"symbol","title":"ImageSliderCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSliderCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImageSliderCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageSliderCollectionViewCell"}],"url":"\/documentation\/divar\/imageslidercollectionviewcell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"mediaSlider"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mediaSlider"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"MediaSlider","preciseIdentifier":"c:objc(cs)MediaSlider"},{"kind":"text","text":" * "},{"kind":"identifier","text":"mediaSlider"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImageSliderCollectionViewCell~1mediaSlider\/title","value":"mediaSlider"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImageSliderCollectionViewCell~1mediaSlider\/fragments","value":[{"kind":"identifier","text":"mediaSlider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImageSliderCollectionViewCell\/title","value":"ImageSliderCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImageSliderCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"ImageSliderCollectionViewCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}