{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRequestSearch"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchAndSelectStringViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SearchAndSelectStringViewController","text":"SearchAndSelectStringViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/realestatelocationselectorviewcontroller\/didrequestsearch(_:query:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateLocationSelectorViewController\/didRequestSearch(_:query:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"SearchAndSelectStringViewControllerDelegate.didRequestSearch(_:query:completion:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"didRequestSearch(_:query:completion:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRequestSearch"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SearchAndSelectStringViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SearchAndSelectStringViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar40RealEstateLocationSelectorViewControllerC16didRequestSearch_5query10completionyAA0j15AndSelectStringfG0C_SSySaySSGctF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateLocationSelectorViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateLocationSelectorViewController\/SearchAndSelectStringViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/RealEstateLocationSelectorViewController/didRequestSearch(_:query:completion:)":{"role":"symbol","title":"didRequestSearch(_:query:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRequestSearch"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SearchAndSelectStringViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SearchAndSelectStringViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateLocationSelectorViewController\/didRequestSearch(_:query:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/realestatelocationselectorviewcontroller\/didrequestsearch(_:query:completion:)"},"doc://com.Divar.DivarClient/documentation/Divar/RealEstateLocationSelectorViewController":{"deprecated":true,"role":"symbol","title":"RealEstateLocationSelectorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RealEstateLocationSelectorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateLocationSelectorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RealEstateLocationSelectorViewController"}],"url":"\/documentation\/divar\/realestatelocationselectorviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/RealEstateLocationSelectorViewController/SearchAndSelectStringViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"SearchAndSelectStringViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateLocationSelectorViewController\/SearchAndSelectStringViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/realestatelocationselectorviewcontroller\/searchandselectstringviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/SearchAndSelectStringViewController":{"role":"symbol","title":"SearchAndSelectStringViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchAndSelectStringViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchAndSelectStringViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchAndSelectStringViewController"}],"url":"\/documentation\/divar\/searchandselectstringviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateLocationSelectorViewController\/title","value":"RealEstateLocationSelectorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateLocationSelectorViewController\/fragments","value":[{"kind":"identifier","text":"RealEstateLocationSelectorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchAndSelectStringViewController\/title","value":"SearchAndSelectStringViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchAndSelectStringViewController\/fragments","value":[{"kind":"identifier","text":"SearchAndSelectStringViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}