{"variants":[{"paths":["\/documentation\/divar\/realestatelocationselectorviewcontroller\/uicollectionviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/realestatelocationselectorviewcontroller\/uicollectionviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateLocationSelectorViewController\/UICollectionViewDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateLocationSelectorViewController\/collectionView(_:didSelectItemAt:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"UICollectionViewDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateLocationSelectorViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/RealEstateLocationSelectorViewController/collectionView(_:didSelectItemAt:)":{"role":"symbol","title":"collectionView(_:didSelectItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateLocationSelectorViewController\/collectionView(_:didSelectItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:didSelectItemAtIndexPath:"}],"url":"\/documentation\/divar\/realestatelocationselectorviewcontroller\/collectionview(_:didselectitemat:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/RealEstateLocationSelectorViewController":{"deprecated":true,"role":"symbol","title":"RealEstateLocationSelectorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RealEstateLocationSelectorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateLocationSelectorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RealEstateLocationSelectorViewController"}],"url":"\/documentation\/divar\/realestatelocationselectorviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateLocationSelectorViewController\/collectionView(_:didSelectItemAt:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateLocationSelectorViewController~1collectionView(_:didSelectItemAt:)\/title","value":"collectionView:didSelectItemAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateLocationSelectorViewController~1collectionView(_:didSelectItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:didSelectItemAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateLocationSelectorViewController\/title","value":"RealEstateLocationSelectorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateLocationSelectorViewController\/fragments","value":[{"kind":"identifier","text":"RealEstateLocationSelectorViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}