{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"wideButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WideButtonViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WideButtonViewController","text":"WideButtonViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/realestatelocationselectorviewcontroller\/widebutton"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateLocationSelectorViewController\/wideButton","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","title":"wideButton","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"wideButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WideButtonViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WideButtonViewController"}],"symbolKind":"property","externalID":"s:5Divar40RealEstateLocationSelectorViewControllerC10wideButtonAA04WideifG0Cvp","modules":[{"name":"Divar"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateLocationSelectorViewController"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"use LimitedLocationSelectorViewController instead"}]}],"references":{"doc://com.Divar.DivarClient/documentation/Divar/RealEstateLocationSelectorViewController":{"deprecated":true,"role":"symbol","title":"RealEstateLocationSelectorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RealEstateLocationSelectorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateLocationSelectorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RealEstateLocationSelectorViewController"}],"url":"\/documentation\/divar\/realestatelocationselectorviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/WideButtonViewController":{"role":"symbol","title":"WideButtonViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WideButtonViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WideButtonViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WideButtonViewController"}],"url":"\/documentation\/divar\/widebuttonviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/RealEstateLocationSelectorViewController/wideButton":{"role":"symbol","title":"wideButton","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"wideButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WideButtonViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WideButtonViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateLocationSelectorViewController\/wideButton","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/divar\/realestatelocationselectorviewcontroller\/widebutton"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateLocationSelectorViewController\/title","value":"RealEstateLocationSelectorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateLocationSelectorViewController\/fragments","value":[{"kind":"identifier","text":"RealEstateLocationSelectorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WideButtonViewController\/title","value":"WideButtonViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WideButtonViewController\/fragments","value":[{"kind":"identifier","text":"WideButtonViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}