{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"myPosts"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/savedpostlisttype\/myposts"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/savedpostlisttype\/myposts"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType\/myPosts","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"myPosts"}],"title":"SavedPostListType.myPosts","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@Divar@E@SavedPostListType@SavedPostListTypeMyPosts","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"SavedPostListTypeMyPosts"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/SavedPostListType/myPosts":{"role":"symbol","title":"SavedPostListType.myPosts","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"myPosts"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType\/myPosts","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SavedPostListTypeMyPosts"}],"url":"\/documentation\/divar\/savedpostlisttype\/myposts"},"doc://com.Divar.DivarClient/documentation/Divar/SavedPostListType":{"role":"symbol","title":"SavedPostListType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SavedPostListType"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SavedPostListType"}],"url":"\/documentation\/divar\/savedpostlisttype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SavedPostListTypeMyPosts"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SavedPostListTypeMyPosts"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SavedPostListTypeMyPosts"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SavedPostListType~1myPosts\/title","value":"SavedPostListTypeMyPosts"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SavedPostListType~1myPosts\/fragments","value":[{"kind":"identifier","text":"SavedPostListTypeMyPosts"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SavedPostListType\/title","value":"SavedPostListType"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SavedPostListType\/fragments","value":[{"kind":"identifier","text":"SavedPostListType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}