{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"segmentSelected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"segmentControl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISegmentedControl","preciseIdentifier":"c:objc(cs)UISegmentedControl"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/mydivarholderviewcontroller\/segmentselected(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/mydivarholderviewcontroller\/segmentselected(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderViewController\/segmentSelected(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"segmentSelected"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UISegmentedControl","preciseIdentifier":"c:objc(cs)UISegmentedControl"},{"kind":"text","text":")"}],"title":"segmentSelected(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Divar@objc(cs)MyDivarHolderViewController(im)segmentSelected:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"segmentSelected:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderViewController/segmentSelected(_:)":{"role":"symbol","title":"segmentSelected(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"segmentSelected"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UISegmentedControl","preciseIdentifier":"c:objc(cs)UISegmentedControl"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderViewController\/segmentSelected(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"segmentSelected:"}],"url":"\/documentation\/divar\/mydivarholderviewcontroller\/segmentselected(_:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderViewController":{"role":"symbol","title":"MyDivarHolderViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyDivarHolderViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MyDivarHolderViewController"}],"url":"\/documentation\/divar\/mydivarholderviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"segmentSelected:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"segmentSelected:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"segmentSelected:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UISegmentedControl","preciseIdentifier":"c:objc(cs)UISegmentedControl"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"segmentControl"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MyDivarHolderViewController~1segmentSelected(_:)\/title","value":"segmentSelected:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MyDivarHolderViewController~1segmentSelected(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"segmentSelected:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MyDivarHolderViewController\/title","value":"MyDivarHolderViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MyDivarHolderViewController\/fragments","value":[{"kind":"identifier","text":"MyDivarHolderViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}