{"variants":[{"paths":["\/documentation\/divar\/mydivarholderviewcontroller\/sfsafariviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/mydivarholderviewcontroller\/sfsafariviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderViewController\/SFSafariViewControllerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderViewController\/safariViewControllerDidFinish(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"SFSafariViewControllerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderViewController":{"role":"symbol","title":"MyDivarHolderViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyDivarHolderViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MyDivarHolderViewController"}],"url":"\/documentation\/divar\/mydivarholderviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderViewController/safariViewControllerDidFinish(_:)":{"role":"symbol","title":"safariViewControllerDidFinish(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"safariViewControllerDidFinish"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SFSafariViewController","preciseIdentifier":"c:objc(cs)SFSafariViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderViewController\/safariViewControllerDidFinish(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"safariViewControllerDidFinish:"}],"url":"\/documentation\/divar\/mydivarholderviewcontroller\/safariviewcontrollerdidfinish(_:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderViewController\/safariViewControllerDidFinish(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MyDivarHolderViewController\/title","value":"MyDivarHolderViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MyDivarHolderViewController\/fragments","value":[{"kind":"identifier","text":"MyDivarHolderViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MyDivarHolderViewController~1safariViewControllerDidFinish(_:)\/title","value":"safariViewControllerDidFinish:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MyDivarHolderViewController~1safariViewControllerDidFinish(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"safariViewControllerDidFinish:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}