{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialMarketplaceRegisterViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"navigationController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController","text":"NavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"section"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_MarketplaceRegisterStorePayload","preciseIdentifier":"s:19DivarInterfaceSwift39Widgets_MarketplaceRegisterStorePayloadV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Source","preciseIdentifier":"s:19DivarInterfaceSwift39Widgets_MarketplaceRegisterStorePayloadV6SourceO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/marketplaceformflowcontroller\/initialmarketplaceregisterviewcontroller(with:section:source:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceFormFlowController\/initialMarketplaceRegisterViewController(with:section:source:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialMarketplaceRegisterViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"section"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_MarketplaceRegisterStorePayload","preciseIdentifier":"s:19DivarInterfaceSwift39Widgets_MarketplaceRegisterStorePayloadV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Source","preciseIdentifier":"s:19DivarInterfaceSwift39Widgets_MarketplaceRegisterStorePayloadV6SourceO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"title":"initialMarketplaceRegisterViewController(with:section:source:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:5Divar29MarketplaceFormFlowControllerC07initialb12RegisterViewE04with7section6sourceSo06UIViewE0CAA010NavigationE0C_s5Int32V0A14InterfaceSwift08Widgets_bG12StorePayloadV6SourceOtF","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceFormFlowController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/MarketplaceFormFlowController/initialMarketplaceRegisterViewController(with:section:source:)":{"role":"symbol","title":"initialMarketplaceRegisterViewController(with:section:source:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialMarketplaceRegisterViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"section"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_MarketplaceRegisterStorePayload","preciseIdentifier":"s:19DivarInterfaceSwift39Widgets_MarketplaceRegisterStorePayloadV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Source","preciseIdentifier":"s:19DivarInterfaceSwift39Widgets_MarketplaceRegisterStorePayloadV6SourceO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceFormFlowController\/initialMarketplaceRegisterViewController(with:section:source:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/marketplaceformflowcontroller\/initialmarketplaceregisterviewcontroller(with:section:source:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/MarketplaceFormFlowController":{"role":"symbol","title":"MarketplaceFormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketplaceFormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceFormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketplaceFormFlowController"}],"url":"\/documentation\/divar\/marketplaceformflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/NavigationController":{"role":"symbol","title":"NavigationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NavigationController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NavigationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NavigationController"}],"url":"\/documentation\/divar\/navigationcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceFormFlowController\/title","value":"MarketplaceFormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceFormFlowController\/fragments","value":[{"kind":"identifier","text":"MarketplaceFormFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NavigationController\/title","value":"NavigationController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NavigationController\/fragments","value":[{"kind":"identifier","text":"NavigationController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}