{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didInnerCell"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractTableViewController","text":"AbstractTableViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"change"},{"kind":"text","text":" "},{"kind":"internalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConfigurableCellEnum","preciseIdentifier":"s:5Divar20ConfigurableCellEnumO","text":"ConfigurableCellEnum"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/postreportdescriptionviewcontroller\/didinnercell(_:with:change:value:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostReportDescriptionViewController\/didInnerCell(_:with:change:value:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AbstractTableViewControllerDelegate.didInnerCell(_:with:change:value:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"didInnerCell(_:with:change:value:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didInnerCell"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AbstractTableViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractTableViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"change"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConfigurableCellEnum","preciseIdentifier":"s:5Divar20ConfigurableCellEnumO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar35PostReportDescriptionViewControllerC12didInnerCell_4with6change5valueyAA013AbstractTableeF0C_10Foundation9IndexPathVSgAA012ConfigurableI4EnumOyptF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostReportDescriptionViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostReportDescriptionViewController\/AbstractTableViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController":{"role":"symbol","title":"AbstractTableViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractTableViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AbstractTableViewController"}],"url":"\/documentation\/divar\/abstracttableviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostReportDescriptionViewController/didInnerCell(_:with:change:value:)":{"role":"symbol","title":"didInnerCell(_:with:change:value:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didInnerCell"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AbstractTableViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractTableViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"change"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConfigurableCellEnum","preciseIdentifier":"s:5Divar20ConfigurableCellEnumO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostReportDescriptionViewController\/didInnerCell(_:with:change:value:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postreportdescriptionviewcontroller\/didinnercell(_:with:change:value:)"},"doc://com.Divar.DivarClient/documentation/Divar/PostReportDescriptionViewController/AbstractTableViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"AbstractTableViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostReportDescriptionViewController\/AbstractTableViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/postreportdescriptionviewcontroller\/abstracttableviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/PostReportDescriptionViewController":{"role":"symbol","title":"PostReportDescriptionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostReportDescriptionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostReportDescriptionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostReportDescriptionViewController"}],"url":"\/documentation\/divar\/postreportdescriptionviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ConfigurableCellEnum":{"role":"symbol","title":"ConfigurableCellEnum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConfigurableCellEnum"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConfigurableCellEnum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConfigurableCellEnum"}],"url":"\/documentation\/divar\/configurablecellenum"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController\/title","value":"AbstractTableViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController\/fragments","value":[{"kind":"identifier","text":"AbstractTableViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostReportDescriptionViewController\/title","value":"PostReportDescriptionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostReportDescriptionViewController\/fragments","value":[{"kind":"identifier","text":"PostReportDescriptionViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}