{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteBookmark"},{"kind":"text","text":"("},{"kind":"externalParam","text":"postToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/bookmarksviewcontroller\/deletebookmark(posttoken:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/bookmarksviewcontroller\/deletebookmark(posttoken:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController\/deleteBookmark(postToken:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteBookmark"},{"kind":"text","text":"("},{"kind":"externalParam","text":"postToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"deleteBookmark(postToken:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Divar@objc(cs)BookmarksViewController(im)deleteBookmarkWithPostToken:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"deleteBookmarkWithPostToken:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/BookmarksViewController/deleteBookmark(postToken:)":{"role":"symbol","title":"deleteBookmark(postToken:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteBookmark"},{"kind":"text","text":"("},{"kind":"externalParam","text":"postToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController\/deleteBookmark(postToken:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteBookmarkWithPostToken:"}],"url":"\/documentation\/divar\/bookmarksviewcontroller\/deletebookmark(posttoken:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarksViewController":{"role":"symbol","title":"BookmarksViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BookmarksViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BookmarksViewController"}],"url":"\/documentation\/divar\/bookmarksviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"deleteBookmarkWithPostToken:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteBookmarkWithPostToken:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"deleteBookmarkWithPostToken:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"postToken"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarksViewController~1deleteBookmark(postToken:)\/title","value":"deleteBookmarkWithPostToken:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarksViewController~1deleteBookmark(postToken:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteBookmarkWithPostToken:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarksViewController\/title","value":"BookmarksViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarksViewController\/fragments","value":[{"kind":"identifier","text":"BookmarksViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}