{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nibName"},{"kind":"text","text":" "},{"kind":"internalParam","text":"nibNameOrNil"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"bundle"},{"kind":"text","text":" "},{"kind":"internalParam","text":"nibBundleOrNil"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bundle","preciseIdentifier":"c:objc(cs)NSBundle"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/searchhistoryviewcontroller\/init(nibname:bundle:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/searchhistoryviewcontroller\/init(nibname:bundle:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchHistoryViewController\/init(nibName:bundle:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nibName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"bundle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bundle","preciseIdentifier":"c:objc(cs)NSBundle"},{"kind":"text","text":"?)"}],"title":"init(nibName:bundle:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@Divar@objc(cs)SearchHistoryViewController(im)initWithNibName:bundle:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchHistoryViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/SearchHistoryViewController/init(nibName:bundle:)":{"role":"symbol","title":"init(nibName:bundle:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nibName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"bundle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bundle","preciseIdentifier":"c:objc(cs)NSBundle"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchHistoryViewController\/init(nibName:bundle:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/divar\/searchhistoryviewcontroller\/init(nibname:bundle:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/SearchHistoryViewController":{"role":"symbol","title":"SearchHistoryViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchHistoryViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchHistoryViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchHistoryViewController"}],"url":"\/documentation\/divar\/searchhistoryviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithNibName:bundle:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithNibName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"nibNameOrNil"},{"kind":"text","text":" "},{"kind":"identifier","text":"bundle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSBundle","preciseIdentifier":"c:objc(cs)NSBundle"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"nibBundleOrNil"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchHistoryViewController~1init(nibName:bundle:)\/title","value":"initWithNibName:bundle:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchHistoryViewController~1init(nibName:bundle:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchHistoryViewController\/title","value":"SearchHistoryViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchHistoryViewController\/fragments","value":[{"kind":"identifier","text":"SearchHistoryViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}