{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"districts"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictPolygon","preciseIdentifier":"c:@M@Divar@objc(cs)DistrictPolygon","text":"DistrictPolygon"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/districtmultipolygon\/init(districts:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictMultiPolygon\/init(districts:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","title":"init(districts:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"districts"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DistrictPolygon","preciseIdentifier":"c:@M@Divar@objc(cs)DistrictPolygon"},{"kind":"text","text":"])"}],"symbolKind":"init","externalID":"s:5Divar20DistrictMultiPolygonC9districtsACSayAA0bD0CG_tcfc","modules":[{"name":"Divar"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictMultiPolygon"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/DistrictPolygon":{"role":"symbol","title":"DistrictPolygon","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DistrictPolygon"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictPolygon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DistrictPolygon"}],"url":"\/documentation\/divar\/districtpolygon"},"doc://com.Divar.DivarClient/documentation/Divar/DistrictMultiPolygon/init(districts:)":{"role":"symbol","title":"init(districts:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"districts"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DistrictPolygon","preciseIdentifier":"c:@M@Divar@objc(cs)DistrictPolygon"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictMultiPolygon\/init(districts:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/districtmultipolygon\/init(districts:)"},"doc://com.Divar.DivarClient/documentation/Divar/DistrictMultiPolygon":{"role":"symbol","title":"DistrictMultiPolygon","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DistrictMultiPolygon"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictMultiPolygon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DistrictMultiPolygon"}],"url":"\/documentation\/divar\/districtmultipolygon"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictPolygon\/title","value":"DistrictPolygon"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictPolygon\/fragments","value":[{"kind":"identifier","text":"DistrictPolygon"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictMultiPolygon\/title","value":"DistrictMultiPolygon"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictMultiPolygon\/fragments","value":[{"kind":"identifier","text":"DistrictMultiPolygon"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}