{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"districtedMap"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"map"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController","preciseIdentifier":"c:@M@Divar@objc(cs)DistrictedMapViewController","text":"DistrictedMapViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeSelectedData"},{"kind":"text","text":" "},{"kind":"internalParam","text":"selectedData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleMultiModel","preciseIdentifier":"s:5Divar16SingleMultiModelV","text":"SingleMultiModel"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/mapdistrictselectorviewcontroller\/districtedmap(_:didchangeselecteddata:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDistrictSelectorViewController\/districtedMap(_:didChangeSelectedData:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"DistrictedMapViewControllerDelegate.districtedMap(_:didChangeSelectedData:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"districtedMap(_:didChangeSelectedData:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"districtedMap"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DistrictedMapViewController","preciseIdentifier":"c:@M@Divar@objc(cs)DistrictedMapViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeSelectedData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SingleMultiModel","preciseIdentifier":"s:5Divar16SingleMultiModelV"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"s:5Divar33MapDistrictSelectorViewControllerC010districtedB0_21didChangeSelectedDatayAA010DistrictedbeF0C_SayAA16SingleMultiModelVGtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDistrictSelectorViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDistrictSelectorViewController\/DistrictedMapViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/MapDistrictSelectorViewController":{"role":"symbol","title":"MapDistrictSelectorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapDistrictSelectorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDistrictSelectorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapDistrictSelectorViewController"}],"url":"\/documentation\/divar\/mapdistrictselectorviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/SingleMultiModel":{"role":"symbol","title":"SingleMultiModel","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleMultiModel"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleMultiModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SingleMultiModel"}],"url":"\/documentation\/divar\/singlemultimodel"},"doc://com.Divar.DivarClient/documentation/Divar/MapDistrictSelectorViewController/districtedMap(_:didChangeSelectedData:)":{"role":"symbol","title":"districtedMap(_:didChangeSelectedData:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"districtedMap"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DistrictedMapViewController","preciseIdentifier":"c:@M@Divar@objc(cs)DistrictedMapViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeSelectedData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SingleMultiModel","preciseIdentifier":"s:5Divar16SingleMultiModelV"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDistrictSelectorViewController\/districtedMap(_:didChangeSelectedData:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mapdistrictselectorviewcontroller\/districtedmap(_:didchangeselecteddata:)"},"doc://com.Divar.DivarClient/documentation/Divar/DistrictedMapViewController":{"role":"symbol","title":"DistrictedMapViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DistrictedMapViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DistrictedMapViewController"}],"url":"\/documentation\/divar\/districtedmapviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MapDistrictSelectorViewController/DistrictedMapViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"DistrictedMapViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDistrictSelectorViewController\/DistrictedMapViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/mapdistrictselectorviewcontroller\/districtedmapviewcontrollerdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDistrictSelectorViewController\/title","value":"MapDistrictSelectorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDistrictSelectorViewController\/fragments","value":[{"kind":"identifier","text":"MapDistrictSelectorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictedMapViewController\/title","value":"DistrictedMapViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictedMapViewController\/fragments","value":[{"kind":"identifier","text":"DistrictedMapViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}