{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController","preciseIdentifier":"c:@M@Divar@objc(cs)DistrictedMapViewController","text":"DistrictedMapViewController"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/mapdistrictselectorviewcontroller\/mapvc"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDistrictSelectorViewController\/mapVC","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DistrictedMapViewController","preciseIdentifier":"c:@M@Divar@objc(cs)DistrictedMapViewController"}],"title":"mapVC","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar33MapDistrictSelectorViewControllerC5mapVCAA010DistrictedbeF0Cvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDistrictSelectorViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/MapDistrictSelectorViewController/mapVC":{"role":"symbol","title":"mapVC","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DistrictedMapViewController","preciseIdentifier":"c:@M@Divar@objc(cs)DistrictedMapViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDistrictSelectorViewController\/mapVC","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mapdistrictselectorviewcontroller\/mapvc"},"doc://com.Divar.DivarClient/documentation/Divar/MapDistrictSelectorViewController":{"role":"symbol","title":"MapDistrictSelectorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapDistrictSelectorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDistrictSelectorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapDistrictSelectorViewController"}],"url":"\/documentation\/divar\/mapdistrictselectorviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/DistrictedMapViewController":{"role":"symbol","title":"DistrictedMapViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DistrictedMapViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DistrictedMapViewController"}],"url":"\/documentation\/divar\/districtedmapviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDistrictSelectorViewController\/title","value":"MapDistrictSelectorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDistrictSelectorViewController\/fragments","value":[{"kind":"identifier","text":"MapDistrictSelectorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictedMapViewController\/title","value":"DistrictedMapViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictedMapViewController\/fragments","value":[{"kind":"identifier","text":"DistrictedMapViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}