{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"taglistCell"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListCell","preciseIdentifier":"c:@M@Divar@objc(cs)TagListCell","text":"TagListCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListItem","preciseIdentifier":"s:5Divar11TagListItemP","text":"TagListItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRemoveItemAtIndex"},{"kind":"text","text":" "},{"kind":"internalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/mapdistrictselectorviewcontroller\/taglistcell(_:tag:didremoveitematindex:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDistrictSelectorViewController\/taglistCell(_:tag:didRemoveItemAtIndex:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"TagListViewControllerDelegate.taglistCell(_:tag:didRemoveItemAtIndex:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"taglistCell(_:tag:didRemoveItemAtIndex:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"taglistCell"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TagListCell","preciseIdentifier":"c:@M@Divar@objc(cs)TagListCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagListItem","preciseIdentifier":"s:5Divar11TagListItemP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRemoveItemAtIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar33MapDistrictSelectorViewControllerC11taglistCell_3tag20didRemoveItemAtIndexyAA07TagListH0C_AA0opL0_pSitF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDistrictSelectorViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDistrictSelectorViewController\/TagListViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/MapDistrictSelectorViewController/TagListViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"TagListViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDistrictSelectorViewController\/TagListViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/mapdistrictselectorviewcontroller\/taglistviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/TagListCell":{"role":"symbol","title":"TagListCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagListCell"}],"url":"\/documentation\/divar\/taglistcell"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/MapDistrictSelectorViewController":{"role":"symbol","title":"MapDistrictSelectorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapDistrictSelectorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDistrictSelectorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapDistrictSelectorViewController"}],"url":"\/documentation\/divar\/mapdistrictselectorviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MapDistrictSelectorViewController/taglistCell(_:tag:didRemoveItemAtIndex:)":{"role":"symbol","title":"taglistCell(_:tag:didRemoveItemAtIndex:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"taglistCell"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TagListCell","preciseIdentifier":"c:@M@Divar@objc(cs)TagListCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagListItem","preciseIdentifier":"s:5Divar11TagListItemP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRemoveItemAtIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDistrictSelectorViewController\/taglistCell(_:tag:didRemoveItemAtIndex:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mapdistrictselectorviewcontroller\/taglistcell(_:tag:didremoveitematindex:)"},"doc://com.Divar.DivarClient/documentation/Divar/TagListItem":{"role":"symbol","title":"TagListItem","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListItem"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagListItem"}],"url":"\/documentation\/divar\/taglistitem"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListCell\/title","value":"TagListCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListCell\/fragments","value":[{"kind":"identifier","text":"TagListCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDistrictSelectorViewController\/title","value":"MapDistrictSelectorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDistrictSelectorViewController\/fragments","value":[{"kind":"identifier","text":"MapDistrictSelectorViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}