{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagList"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TagListViewController","text":"TagListViewController"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/mapdistrictselectorviewcontroller\/taglist"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDistrictSelectorViewController\/tagList","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagList"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagListViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TagListViewController"}],"title":"tagList","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar33MapDistrictSelectorViewControllerC7tagListAA03TagheF0Cvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDistrictSelectorViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/TagListViewController":{"role":"symbol","title":"TagListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagListViewController"}],"url":"\/documentation\/divar\/taglistviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MapDistrictSelectorViewController/tagList":{"role":"symbol","title":"tagList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagList"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagListViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TagListViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDistrictSelectorViewController\/tagList","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mapdistrictselectorviewcontroller\/taglist"},"doc://com.Divar.DivarClient/documentation/Divar/MapDistrictSelectorViewController":{"role":"symbol","title":"MapDistrictSelectorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapDistrictSelectorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDistrictSelectorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapDistrictSelectorViewController"}],"url":"\/documentation\/divar\/mapdistrictselectorviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListViewController\/title","value":"TagListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListViewController\/fragments","value":[{"kind":"identifier","text":"TagListViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDistrictSelectorViewController\/title","value":"MapDistrictSelectorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDistrictSelectorViewController\/fragments","value":[{"kind":"identifier","text":"MapDistrictSelectorViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}