{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trailingSwipeActionsConfigurationForRowAt"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UISwipeActionsConfiguration","preciseIdentifier":"c:objc(cs)UISwipeActionsConfiguration"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/angoolakresponseviewcontroller\/tableview(_:trailingswipeactionsconfigurationforrowat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/angoolakresponseviewcontroller\/tableview(_:trailingswipeactionsconfigurationforrowat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseViewController\/tableView(_:trailingSwipeActionsConfigurationForRowAt:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UITableViewDelegate.tableView(_:trailingSwipeActionsConfigurationForRowAt:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"tableView:trailingSwipeActionsConfigurationForRowAtIndexPath:"}],"role":"symbol","title":"tableView(_:trailingSwipeActionsConfigurationForRowAt:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trailingSwipeActionsConfigurationForRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UISwipeActionsConfiguration","preciseIdentifier":"c:objc(cs)UISwipeActionsConfiguration"},{"kind":"text","text":"?"}],"symbolKind":"method","externalID":"c:@CM@Divar@objc(cs)AngoolakResponseViewController(im)tableView:trailingSwipeActionsConfigurationForRowAtIndexPath:","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseViewController\/UITableViewDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/AngoolakResponseViewController":{"role":"symbol","title":"AngoolakResponseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AngoolakResponseViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AngoolakResponseViewController"}],"url":"\/documentation\/divar\/angoolakresponseviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AngoolakResponseViewController/UITableViewDelegate-Implementations":{"role":"collectionGroup","title":"UITableViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseViewController\/UITableViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/angoolakresponseviewcontroller\/uitableviewdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/AngoolakResponseViewController/tableView(_:trailingSwipeActionsConfigurationForRowAt:)":{"role":"symbol","title":"tableView(_:trailingSwipeActionsConfigurationForRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trailingSwipeActionsConfigurationForRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UISwipeActionsConfiguration","preciseIdentifier":"c:objc(cs)UISwipeActionsConfiguration"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseViewController\/tableView(_:trailingSwipeActionsConfigurationForRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:trailingSwipeActionsConfigurationForRowAtIndexPath:"}],"url":"\/documentation\/divar\/angoolakresponseviewcontroller\/tableview(_:trailingswipeactionsconfigurationforrowat:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"tableView:trailingSwipeActionsConfigurationForRowAtIndexPath:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:trailingSwipeActionsConfigurationForRowAtIndexPath:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UISwipeActionsConfiguration","preciseIdentifier":"c:objc(cs)UISwipeActionsConfiguration"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"tableView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":" "},{"kind":"identifier","text":"trailingSwipeActionsConfigurationForRowAtIndexPath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakResponseViewController\/title","value":"AngoolakResponseViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakResponseViewController\/fragments","value":[{"kind":"identifier","text":"AngoolakResponseViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakResponseViewController~1tableView(_:trailingSwipeActionsConfigurationForRowAt:)\/title","value":"tableView:trailingSwipeActionsConfigurationForRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakResponseViewController~1tableView(_:trailingSwipeActionsConfigurationForRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:trailingSwipeActionsConfigurationForRowAtIndexPath:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}