{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"editingStyleForRowAt"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"EditingStyle","preciseIdentifier":"c:@E@UITableViewCellEditingStyle"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/angoolakresponseviewcontroller\/tableview(_:editingstyleforrowat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/angoolakresponseviewcontroller\/tableview(_:editingstyleforrowat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseViewController\/tableView(_:editingStyleForRowAt:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UITableViewDelegate.tableView(_:editingStyleForRowAt:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"editingStyleForRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"EditingStyle","preciseIdentifier":"c:@E@UITableViewCellEditingStyle"}],"title":"tableView(_:editingStyleForRowAt:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@Divar@objc(cs)AngoolakResponseViewController(im)tableView:editingStyleForRowAtIndexPath:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"tableView:editingStyleForRowAtIndexPath:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseViewController\/UITableViewDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/AngoolakResponseViewController":{"role":"symbol","title":"AngoolakResponseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AngoolakResponseViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AngoolakResponseViewController"}],"url":"\/documentation\/divar\/angoolakresponseviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AngoolakResponseViewController/tableView(_:editingStyleForRowAt:)":{"role":"symbol","title":"tableView(_:editingStyleForRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"editingStyleForRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"EditingStyle","preciseIdentifier":"c:@E@UITableViewCellEditingStyle"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseViewController\/tableView(_:editingStyleForRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:editingStyleForRowAtIndexPath:"}],"url":"\/documentation\/divar\/angoolakresponseviewcontroller\/tableview(_:editingstyleforrowat:)"},"doc://com.Divar.DivarClient/documentation/Divar/AngoolakResponseViewController/UITableViewDelegate-Implementations":{"role":"collectionGroup","title":"UITableViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseViewController\/UITableViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/angoolakresponseviewcontroller\/uitableviewdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"tableView:editingStyleForRowAtIndexPath:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:editingStyleForRowAtIndexPath:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UITableViewCellEditingStyle","preciseIdentifier":"c:@E@UITableViewCellEditingStyle"},{"kind":"text","text":") "},{"kind":"identifier","text":"tableView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":" "},{"kind":"identifier","text":"editingStyleForRowAtIndexPath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakResponseViewController\/title","value":"AngoolakResponseViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakResponseViewController\/fragments","value":[{"kind":"identifier","text":"AngoolakResponseViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakResponseViewController~1tableView(_:editingStyleForRowAt:)\/title","value":"tableView:editingStyleForRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakResponseViewController~1tableView(_:editingStyleForRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:editingStyleForRowAtIndexPath:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}