{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"videPlayerDidStopView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"videoPlayer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoPlayerView","preciseIdentifier":"c:@M@Divar@objc(cs)VideoPlayerView","text":"VideoPlayerView"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/videopreviewcontroller\/videplayerdidstopview(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoPreviewController\/videPlayerDidStopView(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"VideoPlayerViewDelegate.videPlayerDidStopView(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"videPlayerDidStopView(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"videPlayerDidStopView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"VideoPlayerView","preciseIdentifier":"c:@M@Divar@objc(cs)VideoPlayerView"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar22VideoPreviewControllerC21videPlayerDidStopViewyyAA0bfI0CF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoPreviewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoPreviewController\/VideoPlayerViewDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/VideoPreviewController/VideoPlayerViewDelegate-Implementations":{"role":"collectionGroup","title":"VideoPlayerViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoPreviewController\/VideoPlayerViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/videopreviewcontroller\/videoplayerviewdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/VideoPreviewController/videPlayerDidStopView(_:)":{"role":"symbol","title":"videPlayerDidStopView(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"videPlayerDidStopView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"VideoPlayerView","preciseIdentifier":"c:@M@Divar@objc(cs)VideoPlayerView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoPreviewController\/videPlayerDidStopView(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/videopreviewcontroller\/videplayerdidstopview(_:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/VideoPreviewController":{"role":"symbol","title":"VideoPreviewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPreviewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoPreviewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoPreviewController"}],"url":"\/documentation\/divar\/videopreviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/VideoPlayerView":{"role":"symbol","title":"VideoPlayerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPlayerView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoPlayerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoPlayerView"}],"url":"\/documentation\/divar\/videoplayerview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VideoPreviewController\/title","value":"VideoPreviewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VideoPreviewController\/fragments","value":[{"kind":"identifier","text":"VideoPreviewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VideoPlayerView\/title","value":"VideoPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VideoPlayerView\/fragments","value":[{"kind":"identifier","text":"VideoPlayerView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}