{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultDoneAction"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/baseformviewcontroller\/defaultdoneaction()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/baseformviewcontroller\/defaultdoneaction()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/defaultDoneAction()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultDoneAction"},{"kind":"text","text":"()"}],"title":"defaultDoneAction()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Divar@objc(cs)BaseFormViewController(im)defaultDoneAction","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"defaultDoneAction"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController":{"role":"symbol","title":"BaseFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseFormViewController"}],"url":"\/documentation\/divar\/baseformviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/defaultDoneAction()":{"role":"symbol","title":"defaultDoneAction()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultDoneAction"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/defaultDoneAction()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultDoneAction"}],"url":"\/documentation\/divar\/baseformviewcontroller\/defaultdoneaction()"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"defaultDoneAction"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"defaultDoneAction"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"defaultDoneAction"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFormViewController\/title","value":"BaseFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFormViewController\/fragments","value":[{"kind":"identifier","text":"BaseFormViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFormViewController~1defaultDoneAction()\/title","value":"defaultDoneAction"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFormViewController~1defaultDoneAction()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"defaultDoneAction"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}