{"variants":[{"paths":["\/documentation\/divar\/angoolakresponseeditorviewcontroller\/uidocumentpickerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/angoolakresponseeditorviewcontroller\/uidocumentpickerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseEditorViewController\/UIDocumentPickerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseEditorViewController\/documentPicker(_:didPickDocumentsAt:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"UIDocumentPickerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseEditorViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/AngoolakResponseEditorViewController/documentPicker(_:didPickDocumentsAt:)":{"role":"symbol","title":"documentPicker(_:didPickDocumentsAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentPicker"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIDocumentPickerViewController","preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didPickDocumentsAt"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseEditorViewController\/documentPicker(_:didPickDocumentsAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"documentPicker:didPickDocumentsAtURLs:"}],"url":"\/documentation\/divar\/angoolakresponseeditorviewcontroller\/documentpicker(_:didpickdocumentsat:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/AngoolakResponseEditorViewController":{"role":"symbol","title":"AngoolakResponseEditorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AngoolakResponseEditorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseEditorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AngoolakResponseEditorViewController"}],"url":"\/documentation\/divar\/angoolakresponseeditorviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseEditorViewController\/documentPicker(_:didPickDocumentsAt:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakResponseEditorViewController~1documentPicker(_:didPickDocumentsAt:)\/title","value":"documentPicker:didPickDocumentsAtURLs:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakResponseEditorViewController~1documentPicker(_:didPickDocumentsAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentPicker:didPickDocumentsAtURLs:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakResponseEditorViewController\/title","value":"AngoolakResponseEditorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakResponseEditorViewController\/fragments","value":[{"kind":"identifier","text":"AngoolakResponseEditorViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}