{"variants":[{"paths":["\/documentation\/divar\/angoolakresponseeditorviewcontroller\/uitextviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/angoolakresponseeditorviewcontroller\/uitextviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseEditorViewController\/UITextViewDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseEditorViewController\/textView(_:shouldChangeTextIn:replacementText:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseEditorViewController\/textViewDidChange(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"UITextViewDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseEditorViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/AngoolakResponseEditorViewController/textViewDidChange(_:)":{"role":"symbol","title":"textViewDidChange(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textViewDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseEditorViewController\/textViewDidChange(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textViewDidChange:"}],"url":"\/documentation\/divar\/angoolakresponseeditorviewcontroller\/textviewdidchange(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/AngoolakResponseEditorViewController":{"role":"symbol","title":"AngoolakResponseEditorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AngoolakResponseEditorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseEditorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AngoolakResponseEditorViewController"}],"url":"\/documentation\/divar\/angoolakresponseeditorviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AngoolakResponseEditorViewController/textView(_:shouldChangeTextIn:replacementText:)":{"role":"symbol","title":"textView(_:shouldChangeTextIn:replacementText:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldChangeTextIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replacementText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseEditorViewController\/textView(_:shouldChangeTextIn:replacementText:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textView:shouldChangeTextInRange:replacementText:"}],"url":"\/documentation\/divar\/angoolakresponseeditorviewcontroller\/textview(_:shouldchangetextin:replacementtext:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseEditorViewController\/textView(_:shouldChangeTextIn:replacementText:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseEditorViewController\/textViewDidChange(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakResponseEditorViewController~1textViewDidChange(_:)\/title","value":"textViewDidChange:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakResponseEditorViewController~1textViewDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textViewDidChange:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakResponseEditorViewController\/title","value":"AngoolakResponseEditorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakResponseEditorViewController\/fragments","value":[{"kind":"identifier","text":"AngoolakResponseEditorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakResponseEditorViewController~1textView(_:shouldChangeTextIn:replacementText:)\/title","value":"textView:shouldChangeTextInRange:replacementText:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakResponseEditorViewController~1textView(_:shouldChangeTextIn:replacementText:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textView:shouldChangeTextInRange:replacementText:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}