{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"textView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldChangeTextIn"},{"kind":"text","text":" "},{"kind":"internalParam","text":"range"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replacementText"},{"kind":"text","text":" "},{"kind":"internalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/descriptionfieldview\/textview(_:shouldchangetextin:replacementtext:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/descriptionfieldview\/textview(_:shouldchangetextin:replacementtext:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionFieldView\/textView(_:shouldChangeTextIn:replacementText:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UITextViewDelegate.textView(_:shouldChangeTextIn:replacementText:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldChangeTextIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replacementText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"textView(_:shouldChangeTextIn:replacementText:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@Divar@objc(cs)DescriptionFieldView(im)textView:shouldChangeTextInRange:replacementText:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"textView:shouldChangeTextInRange:replacementText:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionFieldView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionFieldView\/UITextViewDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/DescriptionFieldView/UITextViewDelegate-Implementations":{"role":"collectionGroup","title":"UITextViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionFieldView\/UITextViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/descriptionfieldview\/uitextviewdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/DescriptionFieldView":{"role":"symbol","title":"DescriptionFieldView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DescriptionFieldView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionFieldView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DescriptionFieldView"}],"url":"\/documentation\/divar\/descriptionfieldview"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/DescriptionFieldView/textView(_:shouldChangeTextIn:replacementText:)":{"role":"symbol","title":"textView(_:shouldChangeTextIn:replacementText:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldChangeTextIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replacementText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionFieldView\/textView(_:shouldChangeTextIn:replacementText:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textView:shouldChangeTextInRange:replacementText:"}],"url":"\/documentation\/divar\/descriptionfieldview\/textview(_:shouldchangetextin:replacementtext:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"textView:shouldChangeTextInRange:replacementText:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textView:shouldChangeTextInRange:replacementText:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"textView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"textView"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldChangeTextInRange:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@S@_NSRange"},{"kind":"text","text":")"},{"kind":"internalParam","text":"range"},{"kind":"text","text":" "},{"kind":"identifier","text":"replacementText:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"text"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DescriptionFieldView\/title","value":"DescriptionFieldView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DescriptionFieldView\/fragments","value":[{"kind":"identifier","text":"DescriptionFieldView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DescriptionFieldView~1textView(_:shouldChangeTextIn:replacementText:)\/title","value":"textView:shouldChangeTextInRange:replacementText:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DescriptionFieldView~1textView(_:shouldChangeTextIn:replacementText:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textView:shouldChangeTextInRange:replacementText:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}