{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"categoryHierarchyDidSelectCategory"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CategoryHierarchyController","preciseIdentifier":"c:@M@Divar@objc(cs)CategoryHierarchyController","text":"CategoryHierarchyController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"item"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UIOptionsDataStruct","preciseIdentifier":"s:5Divar19UIOptionsDataStructV","text":"UIOptionsDataStruct"},{"kind":"text","text":", "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActionLog_SingleSelectedHierarchyItemSelectionActionInfo","preciseIdentifier":"s:19DivarInterfaceSwift046ActionLog_SingleSelectedHierarchyItemSelectionD4InfoV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Source","preciseIdentifier":"s:19DivarInterfaceSwift046ActionLog_SingleSelectedHierarchyItemSelectionD4InfoV6SourceO"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/baseflowcontroller\/categoryhierarchydidselectcategory(_:item:source:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/categoryHierarchyDidSelectCategory(_:item:source:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CategoryHierarchyControllerDelegate.categoryHierarchyDidSelectCategory(_:item:source:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"categoryHierarchyDidSelectCategory(_:item:source:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"categoryHierarchyDidSelectCategory"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CategoryHierarchyController","preciseIdentifier":"c:@M@Divar@objc(cs)CategoryHierarchyController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"item"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIOptionsDataStruct","preciseIdentifier":"s:5Divar19UIOptionsDataStructV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActionLog_SingleSelectedHierarchyItemSelectionActionInfo","preciseIdentifier":"s:19DivarInterfaceSwift046ActionLog_SingleSelectedHierarchyItemSelectionD4InfoV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Source","preciseIdentifier":"s:19DivarInterfaceSwift046ActionLog_SingleSelectedHierarchyItemSelectionD4InfoV6SourceO"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar18BaseFlowControllerC34categoryHierarchyDidSelectCategory_4item6sourceyAA0ifD0C_AA19UIOptionsDataStructV0A14InterfaceSwift024ActionLog_SingleSelectedf13ItemSelectionQ4InfoV6SourceOtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/CategoryHierarchyControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/UIOptionsDataStruct":{"role":"symbol","title":"UIOptionsDataStruct","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIOptionsDataStruct"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UIOptionsDataStruct","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIOptionsDataStruct"}],"url":"\/documentation\/divar\/uioptionsdatastruct"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/CategoryHierarchyControllerDelegate-Implementations":{"role":"collectionGroup","title":"CategoryHierarchyControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/CategoryHierarchyControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/categoryhierarchycontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/categoryHierarchyDidSelectCategory(_:item:source:)":{"role":"symbol","title":"categoryHierarchyDidSelectCategory(_:item:source:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"categoryHierarchyDidSelectCategory"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CategoryHierarchyController","preciseIdentifier":"c:@M@Divar@objc(cs)CategoryHierarchyController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"item"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIOptionsDataStruct","preciseIdentifier":"s:5Divar19UIOptionsDataStructV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActionLog_SingleSelectedHierarchyItemSelectionActionInfo","preciseIdentifier":"s:19DivarInterfaceSwift046ActionLog_SingleSelectedHierarchyItemSelectionD4InfoV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Source","preciseIdentifier":"s:19DivarInterfaceSwift046ActionLog_SingleSelectedHierarchyItemSelectionD4InfoV6SourceO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/categoryHierarchyDidSelectCategory(_:item:source:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/categoryhierarchydidselectcategory(_:item:source:)"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController":{"role":"symbol","title":"BaseFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseFlowController"}],"url":"\/documentation\/divar\/baseflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CategoryHierarchyController":{"role":"symbol","title":"CategoryHierarchyController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CategoryHierarchyController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CategoryHierarchyController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CategoryHierarchyController"}],"url":"\/documentation\/divar\/categoryhierarchycontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/title","value":"BaseFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/fragments","value":[{"kind":"identifier","text":"BaseFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CategoryHierarchyController\/title","value":"CategoryHierarchyController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CategoryHierarchyController\/fragments","value":[{"kind":"identifier","text":"CategoryHierarchyController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}