{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"categoryHierarchySelectorDidCancel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CategoryHierarchyController","preciseIdentifier":"c:@M@Divar@objc(cs)CategoryHierarchyController","text":"CategoryHierarchyController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/baseflowcontroller\/categoryhierarchyselectordidcancel(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/categoryHierarchySelectorDidCancel(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CategoryHierarchyControllerDelegate.categoryHierarchySelectorDidCancel(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"categoryHierarchySelectorDidCancel(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"categoryHierarchySelectorDidCancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CategoryHierarchyController","preciseIdentifier":"c:@M@Divar@objc(cs)CategoryHierarchyController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar18BaseFlowControllerC34categoryHierarchySelectorDidCancelyyAA08CategoryfD0CF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/CategoryHierarchyControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/categoryHierarchySelectorDidCancel(_:)":{"role":"symbol","title":"categoryHierarchySelectorDidCancel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"categoryHierarchySelectorDidCancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CategoryHierarchyController","preciseIdentifier":"c:@M@Divar@objc(cs)CategoryHierarchyController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/categoryHierarchySelectorDidCancel(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/categoryhierarchyselectordidcancel(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/CategoryHierarchyController":{"role":"symbol","title":"CategoryHierarchyController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CategoryHierarchyController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CategoryHierarchyController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CategoryHierarchyController"}],"url":"\/documentation\/divar\/categoryhierarchycontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController":{"role":"symbol","title":"BaseFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseFlowController"}],"url":"\/documentation\/divar\/baseflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/CategoryHierarchyControllerDelegate-Implementations":{"role":"collectionGroup","title":"CategoryHierarchyControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/CategoryHierarchyControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/categoryhierarchycontrollerdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CategoryHierarchyController\/title","value":"CategoryHierarchyController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CategoryHierarchyController\/fragments","value":[{"kind":"identifier","text":"CategoryHierarchyController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/title","value":"BaseFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/fragments","value":[{"kind":"identifier","text":"BaseFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}