{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"navigationController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController","text":"NavigationController"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Self"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/baseflowcontroller\/navigationcontroller(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/navigationController(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","title":"navigationController(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Self"}],"symbolKind":"method","externalID":"s:5Divar18BaseFlowControllerC010navigationD0yACXDAA010NavigationD0CSgF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/NavigationController":{"role":"symbol","title":"NavigationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NavigationController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NavigationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NavigationController"}],"url":"\/documentation\/divar\/navigationcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/navigationController(_:)":{"role":"symbol","title":"navigationController(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/navigationController(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/navigationcontroller(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController":{"role":"symbol","title":"BaseFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseFlowController"}],"url":"\/documentation\/divar\/baseflowcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NavigationController\/title","value":"NavigationController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NavigationController\/fragments","value":[{"kind":"identifier","text":"NavigationController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/title","value":"BaseFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/fragments","value":[{"kind":"identifier","text":"BaseFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}