{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postCreateDidUpdateFailOnGettingData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"postCreaeVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewController","preciseIdentifier":"c:@M@Divar@objc(cs)PostCreateViewController","text":"PostCreateViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/baseflowcontroller\/postcreatedidupdatefailongettingdata(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/postCreateDidUpdateFailOnGettingData(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"PostCreateViewControllerDelegate.postCreateDidUpdateFailOnGettingData(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"postCreateDidUpdateFailOnGettingData(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postCreateDidUpdateFailOnGettingData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PostCreateViewController","preciseIdentifier":"c:@M@Divar@objc(cs)PostCreateViewController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar18BaseFlowControllerC36postCreateDidUpdateFailOnGettingDatayyAA04Postf4ViewD0CF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/PostCreateViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/postCreateDidUpdateFailOnGettingData(_:)":{"role":"symbol","title":"postCreateDidUpdateFailOnGettingData(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postCreateDidUpdateFailOnGettingData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PostCreateViewController","preciseIdentifier":"c:@M@Divar@objc(cs)PostCreateViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/postCreateDidUpdateFailOnGettingData(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/postcreatedidupdatefailongettingdata(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/PostCreateViewController":{"role":"symbol","title":"PostCreateViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostCreateViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostCreateViewController"}],"url":"\/documentation\/divar\/postcreateviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController":{"role":"symbol","title":"BaseFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseFlowController"}],"url":"\/documentation\/divar\/baseflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/PostCreateViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"PostCreateViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/PostCreateViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/postcreateviewcontrollerdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostCreateViewController\/title","value":"PostCreateViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostCreateViewController\/fragments","value":[{"kind":"identifier","text":"PostCreateViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/title","value":"BaseFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/fragments","value":[{"kind":"identifier","text":"BaseFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}