{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postArchiveDidArchivePost"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"postArchiveVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController","preciseIdentifier":"c:@M@Divar@objc(cs)PostArchiveViewController","text":"PostArchiveViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"post"},{"kind":"text","text":" "},{"kind":"internalParam","text":"_"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostViewStructure","preciseIdentifier":"s:5Divar17PostViewStructureV","text":"PostViewStructure"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/baseflowcontroller\/postarchivedidarchivepost(_:post:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/postArchiveDidArchivePost(_:post:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"PostArchiveViewControllerDelegate.postArchiveDidArchivePost(_:post:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"postArchiveDidArchivePost(_:post:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postArchiveDidArchivePost"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PostArchiveViewController","preciseIdentifier":"c:@M@Divar@objc(cs)PostArchiveViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"post"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostViewStructure","preciseIdentifier":"s:5Divar17PostViewStructureV"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar18BaseFlowControllerC014postArchiveDidF4Post_0E0yAA0hf4ViewD0C_AA0hI9StructureVtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/PostArchiveViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController":{"role":"symbol","title":"PostArchiveViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostArchiveViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostArchiveViewController"}],"url":"\/documentation\/divar\/postarchiveviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController":{"role":"symbol","title":"BaseFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseFlowController"}],"url":"\/documentation\/divar\/baseflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/PostArchiveViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"PostArchiveViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/PostArchiveViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/postarchiveviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/postArchiveDidArchivePost(_:post:)":{"role":"symbol","title":"postArchiveDidArchivePost(_:post:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postArchiveDidArchivePost"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PostArchiveViewController","preciseIdentifier":"c:@M@Divar@objc(cs)PostArchiveViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"post"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostViewStructure","preciseIdentifier":"s:5Divar17PostViewStructureV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/postArchiveDidArchivePost(_:post:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/postarchivedidarchivepost(_:post:)"},"doc://com.Divar.DivarClient/documentation/Divar/PostViewStructure":{"role":"symbol","title":"PostViewStructure","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostViewStructure"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostViewStructure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostViewStructure"}],"url":"\/documentation\/divar\/postviewstructure"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController\/title","value":"PostArchiveViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController\/fragments","value":[{"kind":"identifier","text":"PostArchiveViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/title","value":"BaseFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/fragments","value":[{"kind":"identifier","text":"BaseFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}