{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postArchiveDidRequestShowChildren"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController","preciseIdentifier":"c:@M@Divar@objc(cs)PostArchiveViewController","text":"PostArchiveViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"children"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleMultiModel","preciseIdentifier":"s:5Divar16SingleMultiModelV","text":"SingleMultiModel"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/baseflowcontroller\/postarchivedidrequestshowchildren(_:children:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/postArchiveDidRequestShowChildren(_:children:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"PostArchiveViewControllerDelegate.postArchiveDidRequestShowChildren(_:children:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"postArchiveDidRequestShowChildren(_:children:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postArchiveDidRequestShowChildren"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PostArchiveViewController","preciseIdentifier":"c:@M@Divar@objc(cs)PostArchiveViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"children"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SingleMultiModel","preciseIdentifier":"s:5Divar16SingleMultiModelV"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"s:5Divar18BaseFlowControllerC33postArchiveDidRequestShowChildren_8childrenyAA04Postf4ViewD0C_SayAA16SingleMultiModelVGtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/PostArchiveViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/PostArchiveViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"PostArchiveViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/PostArchiveViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/postarchiveviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController":{"role":"symbol","title":"PostArchiveViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostArchiveViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostArchiveViewController"}],"url":"\/documentation\/divar\/postarchiveviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController":{"role":"symbol","title":"BaseFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseFlowController"}],"url":"\/documentation\/divar\/baseflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/postArchiveDidRequestShowChildren(_:children:)":{"role":"symbol","title":"postArchiveDidRequestShowChildren(_:children:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postArchiveDidRequestShowChildren"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PostArchiveViewController","preciseIdentifier":"c:@M@Divar@objc(cs)PostArchiveViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"children"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SingleMultiModel","preciseIdentifier":"s:5Divar16SingleMultiModelV"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/postArchiveDidRequestShowChildren(_:children:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/postarchivedidrequestshowchildren(_:children:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/SingleMultiModel":{"role":"symbol","title":"SingleMultiModel","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleMultiModel"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleMultiModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SingleMultiModel"}],"url":"\/documentation\/divar\/singlemultimodel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController\/title","value":"PostArchiveViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController\/fragments","value":[{"kind":"identifier","text":"PostArchiveViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/title","value":"BaseFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/fragments","value":[{"kind":"identifier","text":"BaseFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}