{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchFilterVCDidRequestFilteringPosts"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchFilterViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SearchFilterViewController","text":"SearchFilterViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"filters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchFilterHistory","preciseIdentifier":"s:5Divar19SearchFilterHistoryV","text":"SearchFilterHistory"},{"kind":"text","text":", "},{"kind":"externalParam","text":"categoryChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/baseflowcontroller\/searchfiltervcdidrequestfilteringposts(_:filters:categorychanged:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/searchFilterVCDidRequestFilteringPosts(_:filters:categoryChanged:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"SearchFilterViewControllerDelegate.searchFilterVCDidRequestFilteringPosts(_:filters:categoryChanged:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"searchFilterVCDidRequestFilteringPosts(_:filters:categoryChanged:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchFilterVCDidRequestFilteringPosts"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SearchFilterViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SearchFilterViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"filters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchFilterHistory","preciseIdentifier":"s:5Divar19SearchFilterHistoryV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"categoryChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar18BaseFlowControllerC38searchFilterVCDidRequestFilteringPosts_7filters15categoryChangedyAA06Searchf4ViewD0C_AA0nF7HistoryVSbtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/SearchFilterViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController":{"role":"symbol","title":"BaseFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseFlowController"}],"url":"\/documentation\/divar\/baseflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SearchFilterHistory":{"role":"symbol","title":"SearchFilterHistory","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchFilterHistory"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchFilterHistory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchFilterHistory"}],"url":"\/documentation\/divar\/searchfilterhistory"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/SearchFilterViewController":{"role":"symbol","title":"SearchFilterViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchFilterViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchFilterViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchFilterViewController"}],"url":"\/documentation\/divar\/searchfilterviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/searchFilterVCDidRequestFilteringPosts(_:filters:categoryChanged:)":{"role":"symbol","title":"searchFilterVCDidRequestFilteringPosts(_:filters:categoryChanged:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchFilterVCDidRequestFilteringPosts"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SearchFilterViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SearchFilterViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"filters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchFilterHistory","preciseIdentifier":"s:5Divar19SearchFilterHistoryV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"categoryChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/searchFilterVCDidRequestFilteringPosts(_:filters:categoryChanged:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/searchfiltervcdidrequestfilteringposts(_:filters:categorychanged:)"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/SearchFilterViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"SearchFilterViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/SearchFilterViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/searchfilterviewcontrollerdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/title","value":"BaseFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/fragments","value":[{"kind":"identifier","text":"BaseFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchFilterViewController\/title","value":"SearchFilterViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchFilterViewController\/fragments","value":[{"kind":"identifier","text":"SearchFilterViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}