{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"savePost"},{"kind":"text","text":"("},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"postType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType","preciseIdentifier":"c:@M@Divar@E@SavedPostListType","text":"SavedPostListType"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/postcreateviewcontroller\/savepost(token:posttype:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewController\/savePost(token:postType:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"savePost"},{"kind":"text","text":"("},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"postType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SavedPostListType","preciseIdentifier":"c:@M@Divar@E@SavedPostListType"},{"kind":"text","text":")"}],"title":"savePost(token:postType:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:5Divar24PostCreateViewControllerC04saveB05token8postTypeySS_AA05Savedb4ListI0OtF","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PostCreateViewController/savePost(token:postType:)":{"role":"symbol","title":"savePost(token:postType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"savePost"},{"kind":"text","text":"("},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"postType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SavedPostListType","preciseIdentifier":"c:@M@Divar@E@SavedPostListType"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewController\/savePost(token:postType:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postcreateviewcontroller\/savepost(token:posttype:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PostCreateViewController":{"role":"symbol","title":"PostCreateViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostCreateViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostCreateViewController"}],"url":"\/documentation\/divar\/postcreateviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SavedPostListType":{"role":"symbol","title":"SavedPostListType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SavedPostListType"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SavedPostListType"}],"url":"\/documentation\/divar\/savedpostlisttype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostCreateViewController\/title","value":"PostCreateViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostCreateViewController\/fragments","value":[{"kind":"identifier","text":"PostCreateViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SavedPostListType\/title","value":"SavedPostListType"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SavedPostListType\/fragments","value":[{"kind":"identifier","text":"SavedPostListType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}