{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"valueHasBeenChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractFormViewController","text":"AbstractFormViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"row"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseRow","preciseIdentifier":"s:6Eureka7BaseRowC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"oldValue"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"newValue"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/postcreateviewcontroller\/valuehasbeenchanged(_:for:oldvalue:newvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewController\/valueHasBeenChanged(_:for:oldValue:newValue:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"valueHasBeenChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AbstractFormViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractFormViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseRow","preciseIdentifier":"s:6Eureka7BaseRowC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"oldValue"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"newValue"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"title":"valueHasBeenChanged(_:for:oldValue:newValue:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:5Divar24PostCreateViewControllerC19valueHasBeenChanged_3for8oldValue03newL0yAA012AbstractFormdE0C_6Eureka7BaseRowCypSgAMtF","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PostCreateViewController":{"role":"symbol","title":"PostCreateViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostCreateViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostCreateViewController"}],"url":"\/documentation\/divar\/postcreateviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController":{"role":"symbol","title":"AbstractFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AbstractFormViewController"}],"url":"\/documentation\/divar\/abstractformviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostCreateViewController/valueHasBeenChanged(_:for:oldValue:newValue:)":{"role":"symbol","title":"valueHasBeenChanged(_:for:oldValue:newValue:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"valueHasBeenChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AbstractFormViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractFormViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseRow","preciseIdentifier":"s:6Eureka7BaseRowC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"oldValue"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"newValue"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewController\/valueHasBeenChanged(_:for:oldValue:newValue:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postcreateviewcontroller\/valuehasbeenchanged(_:for:oldvalue:newvalue:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostCreateViewController\/title","value":"PostCreateViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostCreateViewController\/fragments","value":[{"kind":"identifier","text":"PostCreateViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController\/title","value":"AbstractFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController\/fragments","value":[{"kind":"identifier","text":"AbstractFormViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}