{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"abstractTable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController","text":"WidgetBasedCollectionViewController"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/dealersubscriptionviewcontroller\/abstracttable"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionViewController\/abstractTable","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"abstractTable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"}],"title":"abstractTable","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar32DealerSubscriptionViewControllerC13abstractTableAA021WidgetBasedCollectiondE0Cvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewController":{"role":"symbol","title":"WidgetBasedCollectionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedCollectionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedCollectionViewController"}],"url":"\/documentation\/divar\/widgetbasedcollectionviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/DealerSubscriptionViewController":{"role":"symbol","title":"DealerSubscriptionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DealerSubscriptionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DealerSubscriptionViewController"}],"url":"\/documentation\/divar\/dealersubscriptionviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/DealerSubscriptionViewController/abstractTable":{"role":"symbol","title":"abstractTable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"abstractTable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionViewController\/abstractTable","kind":"symbol","type":"topic","url":"\/documentation\/divar\/dealersubscriptionviewcontroller\/abstracttable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedCollectionViewController\/title","value":"WidgetBasedCollectionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedCollectionViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedCollectionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubscriptionViewController\/title","value":"DealerSubscriptionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubscriptionViewController\/fragments","value":[{"kind":"identifier","text":"DealerSubscriptionViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}