{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"segmentValueChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"segmentedBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SegmentedBar","preciseIdentifier":"c:@M@Divar@objc(cs)SegmentedBar","text":"SegmentedBar"},{"kind":"text","text":", "},{"kind":"externalParam","text":"selectedIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/dealersubscriptionviewcontroller\/segmentvaluechanged(_:selectedindex:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionViewController\/segmentValueChanged(_:selectedIndex:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"SegmentedBarDelegate.segmentValueChanged(_:selectedIndex:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"segmentValueChanged(_:selectedIndex:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"segmentValueChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SegmentedBar","preciseIdentifier":"c:@M@Divar@objc(cs)SegmentedBar"},{"kind":"text","text":", "},{"kind":"externalParam","text":"selectedIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar32DealerSubscriptionViewControllerC19segmentValueChanged_13selectedIndexyAA12SegmentedBarC_SitF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionViewController\/SegmentedBarDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/DealerSubscriptionViewController/SegmentedBarDelegate-Implementations":{"role":"collectionGroup","title":"SegmentedBarDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionViewController\/SegmentedBarDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/dealersubscriptionviewcontroller\/segmentedbardelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/DealerSubscriptionViewController":{"role":"symbol","title":"DealerSubscriptionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DealerSubscriptionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DealerSubscriptionViewController"}],"url":"\/documentation\/divar\/dealersubscriptionviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/DealerSubscriptionViewController/segmentValueChanged(_:selectedIndex:)":{"role":"symbol","title":"segmentValueChanged(_:selectedIndex:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"segmentValueChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SegmentedBar","preciseIdentifier":"c:@M@Divar@objc(cs)SegmentedBar"},{"kind":"text","text":", "},{"kind":"externalParam","text":"selectedIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionViewController\/segmentValueChanged(_:selectedIndex:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/dealersubscriptionviewcontroller\/segmentvaluechanged(_:selectedindex:)"},"doc://com.Divar.DivarClient/documentation/Divar/SegmentedBar":{"role":"symbol","title":"SegmentedBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SegmentedBar"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SegmentedBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SegmentedBar"}],"url":"\/documentation\/divar\/segmentedbar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubscriptionViewController\/title","value":"DealerSubscriptionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubscriptionViewController\/fragments","value":[{"kind":"identifier","text":"DealerSubscriptionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SegmentedBar\/title","value":"SegmentedBar"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SegmentedBar\/fragments","value":[{"kind":"identifier","text":"SegmentedBar"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}