{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController","text":"WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willDisplay"},{"kind":"text","text":" "},{"kind":"internalParam","text":"widget"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Widget","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_WidgetV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forIndexPath"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/dealersubscriptionviewcontroller\/widgetbasedcollectionviewcontroller(_:willdisplay:forindexpath:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionViewController\/widgetBasedCollectionViewController(_:willDisplay:forIndexPath:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"WidgetBasedCollectionViewControllerDelegate.widgetBasedCollectionViewController(_:willDisplay:forIndexPath:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"widgetBasedCollectionViewController(_:willDisplay:forIndexPath:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willDisplay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Widget","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_WidgetV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forIndexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar32DealerSubscriptionViewControllerC021widgetBasedCollectiondE0_11willDisplay12forIndexPathyAA06WidgetghdE0C_0A14InterfaceSwift08Widgets_N0V10Foundation0lM0VtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionViewController\/WidgetBasedCollectionViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/DealerSubscriptionViewController":{"role":"symbol","title":"DealerSubscriptionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DealerSubscriptionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DealerSubscriptionViewController"}],"url":"\/documentation\/divar\/dealersubscriptionviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewController":{"role":"symbol","title":"WidgetBasedCollectionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedCollectionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedCollectionViewController"}],"url":"\/documentation\/divar\/widgetbasedcollectionviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/DealerSubscriptionViewController/widgetBasedCollectionViewController(_:willDisplay:forIndexPath:)":{"role":"symbol","title":"widgetBasedCollectionViewController(_:willDisplay:forIndexPath:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willDisplay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Widget","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_WidgetV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forIndexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionViewController\/widgetBasedCollectionViewController(_:willDisplay:forIndexPath:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/dealersubscriptionviewcontroller\/widgetbasedcollectionviewcontroller(_:willdisplay:forindexpath:)"},"doc://com.Divar.DivarClient/documentation/Divar/DealerSubscriptionViewController/WidgetBasedCollectionViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"WidgetBasedCollectionViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionViewController\/WidgetBasedCollectionViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/dealersubscriptionviewcontroller\/widgetbasedcollectionviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubscriptionViewController\/title","value":"DealerSubscriptionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubscriptionViewController\/fragments","value":[{"kind":"identifier","text":"DealerSubscriptionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedCollectionViewController\/title","value":"WidgetBasedCollectionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedCollectionViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedCollectionViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}