{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapSelectorController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapSelectorViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MapSelectorViewController","text":"MapSelectorViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectLocation"},{"kind":"text","text":" "},{"kind":"internalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Location","preciseIdentifier":"s:5Divar8LocationV","text":"Location"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/limitedlocationselectorviewcontroller\/mapselectorcontroller(_:didselectlocation:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LimitedLocationSelectorViewController\/mapSelectorController(_:didSelectLocation:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"MapSelectorViewControllerDelegate.mapSelectorController(_:didSelectLocation:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"mapSelectorController(_:didSelectLocation:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapSelectorController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MapSelectorViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MapSelectorViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Location","preciseIdentifier":"s:5Divar8LocationV"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar37LimitedLocationSelectorViewControllerC03mapdF0_09didSelectC0yAA03MapdeF0C_AA0C0VtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LimitedLocationSelectorViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LimitedLocationSelectorViewController\/MapSelectorViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/LimitedLocationSelectorViewController/MapSelectorViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"MapSelectorViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LimitedLocationSelectorViewController\/MapSelectorViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/limitedlocationselectorviewcontroller\/mapselectorviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/MapSelectorViewController":{"role":"symbol","title":"MapSelectorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapSelectorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapSelectorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapSelectorViewController"}],"url":"\/documentation\/divar\/mapselectorviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/LimitedLocationSelectorViewController":{"role":"symbol","title":"LimitedLocationSelectorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LimitedLocationSelectorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LimitedLocationSelectorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LimitedLocationSelectorViewController"}],"url":"\/documentation\/divar\/limitedlocationselectorviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/LimitedLocationSelectorViewController/mapSelectorController(_:didSelectLocation:)":{"role":"symbol","title":"mapSelectorController(_:didSelectLocation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapSelectorController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MapSelectorViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MapSelectorViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Location","preciseIdentifier":"s:5Divar8LocationV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LimitedLocationSelectorViewController\/mapSelectorController(_:didSelectLocation:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/limitedlocationselectorviewcontroller\/mapselectorcontroller(_:didselectlocation:)"},"doc://com.Divar.DivarClient/documentation/Divar/Location":{"role":"symbol","title":"Location","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Location"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Location","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Location"}],"url":"\/documentation\/divar\/location"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapSelectorViewController\/title","value":"MapSelectorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapSelectorViewController\/fragments","value":[{"kind":"identifier","text":"MapSelectorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LimitedLocationSelectorViewController\/title","value":"LimitedLocationSelectorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LimitedLocationSelectorViewController\/fragments","value":[{"kind":"identifier","text":"LimitedLocationSelectorViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}