{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TextField","preciseIdentifier":"c:@M@Sonnat@objc(cs)TextField"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/textfieldtableviewcell\/textfield"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/textfieldtableviewcell\/textfield"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldTableViewCell\/textField","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TextField","preciseIdentifier":"c:@M@Sonnat@objc(cs)TextField"},{"kind":"text","text":"!"}],"title":"textField","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)TextFieldTableViewCell(py)textField","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"textField"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldTableViewCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/TextFieldTableViewCell":{"role":"symbol","title":"TextFieldTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextFieldTableViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TextFieldTableViewCell"}],"url":"\/documentation\/divar\/textfieldtableviewcell"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/TextFieldTableViewCell/textField":{"role":"symbol","title":"textField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TextField","preciseIdentifier":"c:@M@Sonnat@objc(cs)TextField"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldTableViewCell\/textField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textField"}],"url":"\/documentation\/divar\/textfieldtableviewcell\/textfield"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"textField"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"textField"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"TextField","preciseIdentifier":"c:objc(cs)TextField"},{"kind":"text","text":" * "},{"kind":"identifier","text":"textField"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TextFieldTableViewCell\/title","value":"TextFieldTableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TextFieldTableViewCell\/fragments","value":[{"kind":"identifier","text":"TextFieldTableViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TextFieldTableViewCell~1textField\/title","value":"textField"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TextFieldTableViewCell~1textField\/fragments","value":[{"kind":"identifier","text":"textField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}