{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didStartSubmitingForm"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractFormViewController","text":"AbstractFormViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currentPage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currentData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"previousData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/marketpalcefeedbackviewcontroller\/didstartsubmitingform(_:currentpage:currentdata:previousdata:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketpalceFeedbackViewController\/didStartSubmitingForm(_:currentPage:currentData:previousData:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didStartSubmitingForm"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AbstractFormViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractFormViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currentPage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currentData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"previousData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"title":"didStartSubmitingForm(_:currentPage:currentData:previousData:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:5Divar33MarketpalceFeedbackViewControllerC21didStartSubmitingForm_11currentPage0J4Data08previousL0yAA08AbstractidE0C_SiSDySSypGAJtF","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketpalceFeedbackViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/MarketpalceFeedbackViewController/didStartSubmitingForm(_:currentPage:currentData:previousData:)":{"role":"symbol","title":"didStartSubmitingForm(_:currentPage:currentData:previousData:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didStartSubmitingForm"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AbstractFormViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractFormViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currentPage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currentData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"previousData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketpalceFeedbackViewController\/didStartSubmitingForm(_:currentPage:currentData:previousData:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/marketpalcefeedbackviewcontroller\/didstartsubmitingform(_:currentpage:currentdata:previousdata:)"},"doc://com.Divar.DivarClient/documentation/Divar/MarketpalceFeedbackViewController":{"role":"symbol","title":"MarketpalceFeedbackViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketpalceFeedbackViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketpalceFeedbackViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketpalceFeedbackViewController"}],"url":"\/documentation\/divar\/marketpalcefeedbackviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController":{"role":"symbol","title":"AbstractFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AbstractFormViewController"}],"url":"\/documentation\/divar\/abstractformviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketpalceFeedbackViewController\/title","value":"MarketpalceFeedbackViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketpalceFeedbackViewController\/fragments","value":[{"kind":"identifier","text":"MarketpalceFeedbackViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController\/title","value":"AbstractFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController\/fragments","value":[{"kind":"identifier","text":"AbstractFormViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}