{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didStartInfiniteScroll"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractTableViewController","text":"AbstractTableViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scrollView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/dealersubscriptiondetailsviewcontroller\/didstartinfinitescroll(_:scrollview:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionDetailsViewController\/didStartInfiniteScroll(_:scrollView:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AbstractTableViewControllerDelegate.didStartInfiniteScroll(_:scrollView:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"didStartInfiniteScroll(_:scrollView:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didStartInfiniteScroll"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AbstractTableViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractTableViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scrollView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"s:5Divar39DealerSubscriptionDetailsViewControllerC22didStartInfiniteScroll_06scrollE0yAA013AbstractTableeF0C_So08UIScrollE0CSgtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionDetailsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionDetailsViewController\/AbstractTableViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController":{"role":"symbol","title":"AbstractTableViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractTableViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AbstractTableViewController"}],"url":"\/documentation\/divar\/abstracttableviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/DealerSubscriptionDetailsViewController":{"role":"symbol","title":"DealerSubscriptionDetailsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DealerSubscriptionDetailsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionDetailsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DealerSubscriptionDetailsViewController"}],"url":"\/documentation\/divar\/dealersubscriptiondetailsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/DealerSubscriptionDetailsViewController/didStartInfiniteScroll(_:scrollView:)":{"role":"symbol","title":"didStartInfiniteScroll(_:scrollView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didStartInfiniteScroll"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AbstractTableViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractTableViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scrollView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionDetailsViewController\/didStartInfiniteScroll(_:scrollView:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/dealersubscriptiondetailsviewcontroller\/didstartinfinitescroll(_:scrollview:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/DealerSubscriptionDetailsViewController/AbstractTableViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"AbstractTableViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionDetailsViewController\/AbstractTableViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/dealersubscriptiondetailsviewcontroller\/abstracttableviewcontrollerdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController\/title","value":"AbstractTableViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController\/fragments","value":[{"kind":"identifier","text":"AbstractTableViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubscriptionDetailsViewController\/title","value":"DealerSubscriptionDetailsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubscriptionDetailsViewController\/fragments","value":[{"kind":"identifier","text":"DealerSubscriptionDetailsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}