{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mainTable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractTableViewController","text":"AbstractTableViewController"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/dealersubscriptiondetailsviewcontroller\/maintable"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionDetailsViewController\/mainTable","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mainTable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AbstractTableViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractTableViewController"}],"title":"mainTable","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar39DealerSubscriptionDetailsViewControllerC9mainTableAA08AbstractheF0Cvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionDetailsViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/DealerSubscriptionDetailsViewController/mainTable":{"role":"symbol","title":"mainTable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mainTable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AbstractTableViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractTableViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionDetailsViewController\/mainTable","kind":"symbol","type":"topic","url":"\/documentation\/divar\/dealersubscriptiondetailsviewcontroller\/maintable"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController":{"role":"symbol","title":"AbstractTableViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractTableViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AbstractTableViewController"}],"url":"\/documentation\/divar\/abstracttableviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/DealerSubscriptionDetailsViewController":{"role":"symbol","title":"DealerSubscriptionDetailsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DealerSubscriptionDetailsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionDetailsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DealerSubscriptionDetailsViewController"}],"url":"\/documentation\/divar\/dealersubscriptiondetailsviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController\/title","value":"AbstractTableViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController\/fragments","value":[{"kind":"identifier","text":"AbstractTableViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubscriptionDetailsViewController\/title","value":"DealerSubscriptionDetailsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubscriptionDetailsViewController\/fragments","value":[{"kind":"identifier","text":"DealerSubscriptionDetailsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}