{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stringForValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"axis"},{"kind":"text","text":" "},{"kind":"internalParam","text":"_"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AxisBase","preciseIdentifier":"c:@M@Charts@objc(cs)ChartAxisBase"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/formatter\/stringforvalue(_:axis:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/formatter\/stringforvalue(_:axis:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Formatter\/stringForValue(_:axis:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AxisValueFormatter.stringForValue(_:axis:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stringForValue"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"axis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AxisBase","preciseIdentifier":"c:@M@Charts@objc(cs)ChartAxisBase"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"stringForValue(_:axis:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Divar@objc(cs)Formatter(im)stringForValue:axis:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"stringForValue:axis:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Formatter"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/Formatter/stringForValue(_:axis:)":{"role":"symbol","title":"stringForValue(_:axis:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stringForValue"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"axis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AxisBase","preciseIdentifier":"c:@M@Charts@objc(cs)ChartAxisBase"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Formatter\/stringForValue(_:axis:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stringForValue:axis:"}],"url":"\/documentation\/divar\/formatter\/stringforvalue(_:axis:)"},"doc://com.Divar.DivarClient/documentation/Divar/Formatter":{"role":"symbol","title":"Formatter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Formatter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Formatter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Formatter"}],"url":"\/documentation\/divar\/formatter"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"stringForValue:axis:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stringForValue:axis:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"stringForValue:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":")"},{"kind":"internalParam","text":"value"},{"kind":"text","text":" "},{"kind":"identifier","text":"axis:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChartAxisBase","preciseIdentifier":"c:@M@Charts@objc(cs)ChartAxisBase"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"_"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1Formatter~1stringForValue(_:axis:)\/title","value":"stringForValue:axis:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1Formatter~1stringForValue(_:axis:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stringForValue:axis:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1Formatter\/title","value":"Formatter"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1Formatter\/fragments","value":[{"kind":"identifier","text":"Formatter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}