{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"urlSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/xmlhttprequest-swift.class\/init(urlsession:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/xmlhttprequest-swift.class\/init(urlsession:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequest-swift.class\/init(urlSession:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"urlSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":"!)"}],"title":"init(urlSession:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)XMLHttpRequest(im)initWithURLSession:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"initWithURLSession:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequest-swift.class"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/XMLHttpRequest-swift.class":{"role":"symbol","title":"XMLHttpRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"XMLHttpRequest"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequest-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"XMLHttpRequest"}],"url":"\/documentation\/divar\/xmlhttprequest-swift.class"},"doc://com.Divar.DivarClient/documentation/Divar/XMLHttpRequest-swift.class/init(urlSession:)":{"role":"symbol","title":"init(urlSession:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"urlSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequest-swift.class\/init(urlSession:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithURLSession:"}],"url":"\/documentation\/divar\/xmlhttprequest-swift.class\/init(urlsession:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithURLSession:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithURLSession:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithURLSession:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"urlSession"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequest-swift.class\/title","value":"XMLHttpRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequest-swift.class\/fragments","value":[{"kind":"identifier","text":"XMLHttpRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequest-swift.class~1init(urlSession:)\/title","value":"initWithURLSession:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequest-swift.class~1init(urlSession:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithURLSession:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}