{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HeaderBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)HeaderBarViewController","text":"HeaderBarViewController"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/archivenoteviewcontroller\/headerbar"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ArchiveNoteViewController\/headerBar","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HeaderBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)HeaderBarViewController"}],"title":"headerBar","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar25ArchiveNoteViewControllerC9headerBarAA06HeadergdE0Cvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ArchiveNoteViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ArchiveNoteViewController":{"role":"symbol","title":"ArchiveNoteViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArchiveNoteViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ArchiveNoteViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ArchiveNoteViewController"}],"url":"\/documentation\/divar\/archivenoteviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ArchiveNoteViewController/headerBar":{"role":"symbol","title":"headerBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HeaderBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)HeaderBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ArchiveNoteViewController\/headerBar","kind":"symbol","type":"topic","url":"\/documentation\/divar\/archivenoteviewcontroller\/headerbar"},"doc://com.Divar.DivarClient/documentation/Divar/HeaderBarViewController":{"role":"symbol","title":"HeaderBarViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeaderBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HeaderBarViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeaderBarViewController"}],"url":"\/documentation\/divar\/headerbarviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ArchiveNoteViewController\/title","value":"ArchiveNoteViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ArchiveNoteViewController\/fragments","value":[{"kind":"identifier","text":"ArchiveNoteViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1HeaderBarViewController\/title","value":"HeaderBarViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1HeaderBarViewController\/fragments","value":[{"kind":"identifier","text":"HeaderBarViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}