{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"noteWithBottomBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)NoteWithBottomBarViewController","text":"NoteWithBottomBarViewController"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/archivenoteviewcontroller\/notewithbottombar"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ArchiveNoteViewController\/noteWithBottomBar","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"noteWithBottomBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NoteWithBottomBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)NoteWithBottomBarViewController"}],"title":"noteWithBottomBar","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar25ArchiveNoteViewControllerC17noteWithBottomBarAA0cghidE0Cvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ArchiveNoteViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ArchiveNoteViewController":{"role":"symbol","title":"ArchiveNoteViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArchiveNoteViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ArchiveNoteViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ArchiveNoteViewController"}],"url":"\/documentation\/divar\/archivenoteviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ArchiveNoteViewController/noteWithBottomBar":{"role":"symbol","title":"noteWithBottomBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"noteWithBottomBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NoteWithBottomBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)NoteWithBottomBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ArchiveNoteViewController\/noteWithBottomBar","kind":"symbol","type":"topic","url":"\/documentation\/divar\/archivenoteviewcontroller\/notewithbottombar"},"doc://com.Divar.DivarClient/documentation/Divar/NoteWithBottomBarViewController":{"role":"symbol","title":"NoteWithBottomBarViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NoteWithBottomBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NoteWithBottomBarViewController"}],"url":"\/documentation\/divar\/notewithbottombarviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ArchiveNoteViewController\/title","value":"ArchiveNoteViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ArchiveNoteViewController\/fragments","value":[{"kind":"identifier","text":"ArchiveNoteViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteWithBottomBarViewController\/title","value":"NoteWithBottomBarViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteWithBottomBarViewController\/fragments","value":[{"kind":"identifier","text":"NoteWithBottomBarViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}