{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"noteWithBottomBar"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"noteWithBottomBarVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)NoteWithBottomBarViewController","text":"NoteWithBottomBarViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSubmitNote"},{"kind":"text","text":" "},{"kind":"internalParam","text":"note"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/archivenoteviewcontroller\/notewithbottombar(_:didsubmitnote:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ArchiveNoteViewController\/noteWithBottomBar(_:didSubmitNote:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"NoteWithBottomBarDelegate.noteWithBottomBar(_:didSubmitNote:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"noteWithBottomBar(_:didSubmitNote:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"noteWithBottomBar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NoteWithBottomBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)NoteWithBottomBarViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSubmitNote"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar25ArchiveNoteViewControllerC17noteWithBottomBar_09didSubmitC0yAA0cghidE0C_SStF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ArchiveNoteViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ArchiveNoteViewController\/NoteWithBottomBarDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ArchiveNoteViewController/noteWithBottomBar(_:didSubmitNote:)":{"role":"symbol","title":"noteWithBottomBar(_:didSubmitNote:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"noteWithBottomBar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NoteWithBottomBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)NoteWithBottomBarViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSubmitNote"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ArchiveNoteViewController\/noteWithBottomBar(_:didSubmitNote:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/archivenoteviewcontroller\/notewithbottombar(_:didsubmitnote:)"},"doc://com.Divar.DivarClient/documentation/Divar/ArchiveNoteViewController/NoteWithBottomBarDelegate-Implementations":{"role":"collectionGroup","title":"NoteWithBottomBarDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ArchiveNoteViewController\/NoteWithBottomBarDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/archivenoteviewcontroller\/notewithbottombardelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/NoteWithBottomBarViewController":{"role":"symbol","title":"NoteWithBottomBarViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NoteWithBottomBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NoteWithBottomBarViewController"}],"url":"\/documentation\/divar\/notewithbottombarviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ArchiveNoteViewController":{"role":"symbol","title":"ArchiveNoteViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArchiveNoteViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ArchiveNoteViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ArchiveNoteViewController"}],"url":"\/documentation\/divar\/archivenoteviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteWithBottomBarViewController\/title","value":"NoteWithBottomBarViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteWithBottomBarViewController\/fragments","value":[{"kind":"identifier","text":"NoteWithBottomBarViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ArchiveNoteViewController\/title","value":"ArchiveNoteViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ArchiveNoteViewController\/fragments","value":[{"kind":"identifier","text":"ArchiveNoteViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}