{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parentVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController","preciseIdentifier":"c:@M@Divar@objc(cs)PostArchiveViewController","text":"PostArchiveViewController"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/archivenoteviewcontroller\/parentvc"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ArchiveNoteViewController\/parentVC","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parentVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostArchiveViewController","preciseIdentifier":"c:@M@Divar@objc(cs)PostArchiveViewController"},{"kind":"text","text":"?"}],"title":"parentVC","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar25ArchiveNoteViewControllerC8parentVCAA04PostbdE0CSgvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ArchiveNoteViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ArchiveNoteViewController/parentVC":{"role":"symbol","title":"parentVC","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parentVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostArchiveViewController","preciseIdentifier":"c:@M@Divar@objc(cs)PostArchiveViewController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ArchiveNoteViewController\/parentVC","kind":"symbol","type":"topic","url":"\/documentation\/divar\/archivenoteviewcontroller\/parentvc"},"doc://com.Divar.DivarClient/documentation/Divar/ArchiveNoteViewController":{"role":"symbol","title":"ArchiveNoteViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArchiveNoteViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ArchiveNoteViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ArchiveNoteViewController"}],"url":"\/documentation\/divar\/archivenoteviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController":{"role":"symbol","title":"PostArchiveViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostArchiveViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostArchiveViewController"}],"url":"\/documentation\/divar\/postarchiveviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ArchiveNoteViewController\/title","value":"ArchiveNoteViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ArchiveNoteViewController\/fragments","value":[{"kind":"identifier","text":"ArchiveNoteViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController\/title","value":"PostArchiveViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController\/fragments","value":[{"kind":"identifier","text":"PostArchiveViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}