{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBAction"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"editAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/imagepickerimageselectioncell\/editaction(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/imagepickerimageselectioncell\/editaction(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/editAction(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"editAction:"}],"role":"symbol","title":"editAction(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"editAction"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@Divar@objc(cs)ImagePickerImageSelectionCell(im)editAction:","modules":[{"name":"Divar"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use IV Module Instead"}]}],"references":{"doc://com.Divar.DivarClient/documentation/Divar/ImagePickerImageSelectionCell":{"deprecated":true,"role":"symbol","title":"ImagePickerImageSelectionCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImagePickerImageSelectionCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImagePickerImageSelectionCell"}],"url":"\/documentation\/divar\/imagepickerimageselectioncell"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/ImagePickerImageSelectionCell/editAction(_:)":{"deprecated":true,"role":"symbol","title":"editAction(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"editAction"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/editAction(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"editAction:"}],"url":"\/documentation\/divar\/imagepickerimageselectioncell\/editaction(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"editAction:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"editAction:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"editAction:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":")"},{"kind":"internalParam","text":"sender"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelectionCell\/title","value":"ImagePickerImageSelectionCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelectionCell\/fragments","value":[{"kind":"identifier","text":"ImagePickerImageSelectionCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelectionCell~1editAction(_:)\/title","value":"editAction:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelectionCell~1editAction(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"editAction:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}