{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"priceView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/EvaluationView","preciseIdentifier":"c:@M@Divar@objc(cs)EvaluationView","text":"EvaluationView"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/evaluationrowcollectionviewcell\/priceview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/evaluationrowcollectionviewcell\/priceview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/EvaluationRowCollectionViewCell\/priceView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"priceView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EvaluationView","preciseIdentifier":"c:@M@Divar@objc(cs)EvaluationView"},{"kind":"text","text":"!"}],"title":"priceView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)EvaluationRowCollectionViewCell(py)priceView","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"priceView"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/EvaluationRowCollectionViewCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/EvaluationRowCollectionViewCell":{"role":"symbol","title":"EvaluationRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EvaluationRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/EvaluationRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EvaluationRowCollectionViewCell"}],"url":"\/documentation\/divar\/evaluationrowcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/EvaluationView":{"role":"symbol","title":"EvaluationView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EvaluationView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/EvaluationView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EvaluationView"}],"url":"\/documentation\/divar\/evaluationview"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/EvaluationRowCollectionViewCell/priceView":{"role":"symbol","title":"priceView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"priceView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EvaluationView","preciseIdentifier":"c:@M@Divar@objc(cs)EvaluationView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/EvaluationRowCollectionViewCell\/priceView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"priceView"}],"url":"\/documentation\/divar\/evaluationrowcollectionviewcell\/priceview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"priceView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"priceView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/EvaluationView","preciseIdentifier":"c:@M@Divar@objc(cs)EvaluationView","text":"EvaluationView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"priceView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1EvaluationRowCollectionViewCell\/title","value":"EvaluationRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1EvaluationRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"EvaluationRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1EvaluationView\/title","value":"EvaluationView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1EvaluationView\/fragments","value":[{"kind":"identifier","text":"EvaluationView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1EvaluationRowCollectionViewCell~1priceView\/title","value":"priceView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1EvaluationRowCollectionViewCell~1priceView\/fragments","value":[{"kind":"identifier","text":"priceView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}