{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager","preciseIdentifier":"c:@M@Divar@objc(cs)AudioPlayManager","text":"AudioPlayManager"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/messagingviewcontroller\/audioplayer"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/audioPlayer","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioPlayManager","preciseIdentifier":"c:@M@Divar@objc(cs)AudioPlayManager"}],"title":"audioPlayer","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar23MessagingViewControllerC11audioPlayerAA16AudioPlayManagerCvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/AudioPlayManager":{"role":"symbol","title":"AudioPlayManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioPlayManager"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AudioPlayManager"}],"url":"\/documentation\/divar\/audioplaymanager"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/audioPlayer":{"role":"symbol","title":"audioPlayer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioPlayManager","preciseIdentifier":"c:@M@Divar@objc(cs)AudioPlayManager"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/audioPlayer","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/audioplayer"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController":{"role":"symbol","title":"MessagingViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagingViewController"}],"url":"\/documentation\/divar\/messagingviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AudioPlayManager\/title","value":"AudioPlayManager"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AudioPlayManager\/fragments","value":[{"kind":"identifier","text":"AudioPlayManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController\/title","value":"MessagingViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController\/fragments","value":[{"kind":"identifier","text":"MessagingViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}