{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewControllerDidDismiss"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/messagingviewcontroller\/previewcontrollerdiddismiss(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/messagingviewcontroller\/previewcontrollerdiddismiss(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/previewControllerDidDismiss(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"QLPreviewControllerDelegate.previewControllerDidDismiss(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewControllerDidDismiss"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"kind":"text","text":")"}],"title":"previewControllerDidDismiss(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@Divar@objc(cs)MessagingViewController(im)previewControllerDidDismiss:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"previewControllerDidDismiss:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/QLPreviewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/previewControllerDidDismiss(_:)":{"role":"symbol","title":"previewControllerDidDismiss(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewControllerDidDismiss"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/previewControllerDidDismiss(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"previewControllerDidDismiss:"}],"url":"\/documentation\/divar\/messagingviewcontroller\/previewcontrollerdiddismiss(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/QLPreviewControllerDelegate-Implementations":{"role":"collectionGroup","title":"QLPreviewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/QLPreviewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/qlpreviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController":{"role":"symbol","title":"MessagingViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagingViewController"}],"url":"\/documentation\/divar\/messagingviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"previewControllerDidDismiss:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"previewControllerDidDismiss:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"previewControllerDidDismiss:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController~1previewControllerDidDismiss(_:)\/title","value":"previewControllerDidDismiss:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController~1previewControllerDidDismiss(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"previewControllerDidDismiss:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController\/title","value":"MessagingViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController\/fragments","value":[{"kind":"identifier","text":"MessagingViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}