{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previewItemAt"},{"kind":"text","text":" "},{"kind":"internalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"QLPreviewItem","preciseIdentifier":"c:objc(pl)QLPreviewItem"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/messagingviewcontroller\/previewcontroller(_:previewitemat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/messagingviewcontroller\/previewcontroller(_:previewitemat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/previewController(_:previewItemAt:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"QLPreviewControllerDataSource.previewController(_:previewItemAt:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"previewController:previewItemAtIndex:"}],"role":"symbol","title":"previewController(_:previewItemAt:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previewItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"QLPreviewItem","preciseIdentifier":"c:objc(pl)QLPreviewItem"}],"symbolKind":"method","externalID":"c:@CM@Divar@objc(cs)MessagingViewController(im)previewController:previewItemAtIndex:","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/QLPreviewControllerDataSource-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController":{"role":"symbol","title":"MessagingViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagingViewController"}],"url":"\/documentation\/divar\/messagingviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/previewController(_:previewItemAt:)":{"role":"symbol","title":"previewController(_:previewItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previewItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"QLPreviewItem","preciseIdentifier":"c:objc(pl)QLPreviewItem"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/previewController(_:previewItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"previewController:previewItemAtIndex:"}],"url":"\/documentation\/divar\/messagingviewcontroller\/previewcontroller(_:previewitemat:)"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/QLPreviewControllerDataSource-Implementations":{"role":"collectionGroup","title":"QLPreviewControllerDataSource Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/QLPreviewControllerDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/qlpreviewcontrollerdatasource-implementations"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"previewController:previewItemAtIndex:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"previewController:previewItemAtIndex:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id<QLPreviewItem>","preciseIdentifier":"c:Qoobjc(pl)QLPreviewItem"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"previewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewItemAtIndex:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"index"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController\/title","value":"MessagingViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController\/fragments","value":[{"kind":"identifier","text":"MessagingViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController~1previewController(_:previewItemAt:)\/title","value":"previewController:previewItemAtIndex:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController~1previewController(_:previewItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"previewController:previewItemAtIndex:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}