{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"privacyCell"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PrivacyCell","preciseIdentifier":"c:@M@Divar@objc(cs)PrivacyCell","text":"PrivacyCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapOnUrl"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/messagingviewcontroller\/privacycell(_:didtaponurl:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/privacyCell(_:didTapOnUrl:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"PrivacyCellDelegate.privacyCell(_:didTapOnUrl:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"privacyCell(_:didTapOnUrl:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"privacyCell"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PrivacyCell","preciseIdentifier":"c:@M@Divar@objc(cs)PrivacyCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapOnUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar23MessagingViewControllerC11privacyCell_11didTapOnUrlyAA07PrivacyF0C_10Foundation3URLVtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/PrivacyCellDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PrivacyCell":{"role":"symbol","title":"PrivacyCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrivacyCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PrivacyCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PrivacyCell"}],"url":"\/documentation\/divar\/privacycell"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController":{"role":"symbol","title":"MessagingViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagingViewController"}],"url":"\/documentation\/divar\/messagingviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/PrivacyCellDelegate-Implementations":{"role":"collectionGroup","title":"PrivacyCellDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/PrivacyCellDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/privacycelldelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/privacyCell(_:didTapOnUrl:)":{"role":"symbol","title":"privacyCell(_:didTapOnUrl:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"privacyCell"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PrivacyCell","preciseIdentifier":"c:@M@Divar@objc(cs)PrivacyCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapOnUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/privacyCell(_:didTapOnUrl:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/privacycell(_:didtaponurl:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PrivacyCell\/title","value":"PrivacyCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PrivacyCell\/fragments","value":[{"kind":"identifier","text":"PrivacyCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController\/title","value":"MessagingViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController\/fragments","value":[{"kind":"identifier","text":"MessagingViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}