{"variants":[{"paths":["\/documentation\/divar\/ivcollectionassetselectorviewcontroller\/uicollectionviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/ivcollectionassetselectorviewcontroller\/uicollectionviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVCollectionAssetSelectorViewController\/UICollectionViewDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVCollectionAssetSelectorViewController\/collectionView(_:didSelectItemAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVCollectionAssetSelectorViewController\/collectionView(_:willDisplay:forItemAt:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"UICollectionViewDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVCollectionAssetSelectorViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/IVCollectionAssetSelectorViewController/collectionView(_:willDisplay:forItemAt:)":{"role":"symbol","title":"collectionView(_:willDisplay:forItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willDisplay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVCollectionAssetSelectorViewController\/collectionView(_:willDisplay:forItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:willDisplayCell:forItemAtIndexPath:"}],"url":"\/documentation\/divar\/ivcollectionassetselectorviewcontroller\/collectionview(_:willdisplay:foritemat:)"},"doc://com.Divar.DivarClient/documentation/Divar/IVCollectionAssetSelectorViewController/collectionView(_:didSelectItemAt:)":{"role":"symbol","title":"collectionView(_:didSelectItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVCollectionAssetSelectorViewController\/collectionView(_:didSelectItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:didSelectItemAtIndexPath:"}],"url":"\/documentation\/divar\/ivcollectionassetselectorviewcontroller\/collectionview(_:didselectitemat:)"},"doc://com.Divar.DivarClient/documentation/Divar/IVCollectionAssetSelectorViewController":{"role":"symbol","title":"IVCollectionAssetSelectorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IVCollectionAssetSelectorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVCollectionAssetSelectorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IVCollectionAssetSelectorViewController"}],"url":"\/documentation\/divar\/ivcollectionassetselectorviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVCollectionAssetSelectorViewController\/collectionView(_:didSelectItemAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVCollectionAssetSelectorViewController\/collectionView(_:willDisplay:forItemAt:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1IVCollectionAssetSelectorViewController~1collectionView(_:willDisplay:forItemAt:)\/title","value":"collectionView:willDisplayCell:forItemAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1IVCollectionAssetSelectorViewController~1collectionView(_:willDisplay:forItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:willDisplayCell:forItemAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1IVCollectionAssetSelectorViewController~1collectionView(_:didSelectItemAt:)\/title","value":"collectionView:didSelectItemAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1IVCollectionAssetSelectorViewController~1collectionView(_:didSelectItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:didSelectItemAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1IVCollectionAssetSelectorViewController\/title","value":"IVCollectionAssetSelectorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1IVCollectionAssetSelectorViewController\/fragments","value":[{"kind":"identifier","text":"IVCollectionAssetSelectorViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}