{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"indicatorIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SonnatImageView","preciseIdentifier":"c:@M@Sonnat@objc(cs)SonnatImageView"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/subscriptionrowcollectionviewcell\/indicatoricon"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/subscriptionrowcollectionviewcell\/indicatoricon"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SubscriptionRowCollectionViewCell\/indicatorIcon","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"indicatorIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SonnatImageView","preciseIdentifier":"c:@M@Sonnat@objc(cs)SonnatImageView"},{"kind":"text","text":"!"}],"title":"indicatorIcon","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)SubscriptionRowCollectionViewCell(py)indicatorIcon","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"indicatorIcon"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SubscriptionRowCollectionViewCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/SubscriptionRowCollectionViewCell/indicatorIcon":{"role":"symbol","title":"indicatorIcon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"indicatorIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SonnatImageView","preciseIdentifier":"c:@M@Sonnat@objc(cs)SonnatImageView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SubscriptionRowCollectionViewCell\/indicatorIcon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"indicatorIcon"}],"url":"\/documentation\/divar\/subscriptionrowcollectionviewcell\/indicatoricon"},"doc://com.Divar.DivarClient/documentation/Divar/SubscriptionRowCollectionViewCell":{"role":"symbol","title":"SubscriptionRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubscriptionRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SubscriptionRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SubscriptionRowCollectionViewCell"}],"url":"\/documentation\/divar\/subscriptionrowcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"indicatorIcon"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"indicatorIcon"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"SonnatImageView","preciseIdentifier":"c:objc(cs)SonnatImageView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"indicatorIcon"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SubscriptionRowCollectionViewCell~1indicatorIcon\/title","value":"indicatorIcon"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SubscriptionRowCollectionViewCell~1indicatorIcon\/fragments","value":[{"kind":"identifier","text":"indicatorIcon"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SubscriptionRowCollectionViewCell\/title","value":"SubscriptionRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SubscriptionRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"SubscriptionRowCollectionViewCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}