{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageUpload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WideImageUpload","preciseIdentifier":"c:@M@Divar@objc(cs)WideImageUpload","text":"WideImageUpload"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/mapselectorrowcollectionviewcell\/imageupload"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/mapselectorrowcollectionviewcell\/imageupload"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapSelectorRowCollectionViewCell\/imageUpload","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageUpload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WideImageUpload","preciseIdentifier":"c:@M@Divar@objc(cs)WideImageUpload"},{"kind":"text","text":"!"}],"title":"imageUpload","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)MapSelectorRowCollectionViewCell(py)imageUpload","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"imageUpload"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapSelectorRowCollectionViewCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/MapSelectorRowCollectionViewCell/imageUpload":{"role":"symbol","title":"imageUpload","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageUpload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WideImageUpload","preciseIdentifier":"c:@M@Divar@objc(cs)WideImageUpload"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapSelectorRowCollectionViewCell\/imageUpload","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageUpload"}],"url":"\/documentation\/divar\/mapselectorrowcollectionviewcell\/imageupload"},"doc://com.Divar.DivarClient/documentation/Divar/MapSelectorRowCollectionViewCell":{"role":"symbol","title":"MapSelectorRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapSelectorRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapSelectorRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapSelectorRowCollectionViewCell"}],"url":"\/documentation\/divar\/mapselectorrowcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/WideImageUpload":{"role":"symbol","title":"WideImageUpload","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WideImageUpload"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WideImageUpload","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WideImageUpload"}],"url":"\/documentation\/divar\/wideimageupload"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"imageUpload"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"imageUpload"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WideImageUpload","preciseIdentifier":"c:@M@Divar@objc(cs)WideImageUpload","text":"WideImageUpload"},{"kind":"text","text":" * "},{"kind":"identifier","text":"imageUpload"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapSelectorRowCollectionViewCell~1imageUpload\/title","value":"imageUpload"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapSelectorRowCollectionViewCell~1imageUpload\/fragments","value":[{"kind":"identifier","text":"imageUpload"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapSelectorRowCollectionViewCell\/title","value":"MapSelectorRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapSelectorRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"MapSelectorRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WideImageUpload\/title","value":"WideImageUpload"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WideImageUpload\/fragments","value":[{"kind":"identifier","text":"WideImageUpload"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}