{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageSelectorRow"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"row"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImageSelectorRow","preciseIdentifier":"s:5Divar16ImageSelectorRowC","text":"ImageSelectorRow"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestOpenCameraController"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePicker","preciseIdentifier":"c:@M@Divar@objc(cs)ImagePicker","text":"ImagePicker"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/abstractformviewcontroller\/imageselectorrow(_:didrequestopencameracontroller:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/imageSelectorRow(_:didRequestOpenCameraController:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ImageSelectorRowDelegate.imageSelectorRow(_:didRequestOpenCameraController:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"imageSelectorRow(_:didRequestOpenCameraController:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageSelectorRow"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ImageSelectorRow","preciseIdentifier":"s:5Divar16ImageSelectorRowC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestOpenCameraController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImagePicker","preciseIdentifier":"c:@M@Divar@objc(cs)ImagePicker"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar26AbstractFormViewControllerC16imageSelectorRow_020didRequestOpenCameraE0yAA05ImagegH0C_AA0M6PickerCtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/ImageSelectorRowDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/imageSelectorRow(_:didRequestOpenCameraController:)":{"role":"symbol","title":"imageSelectorRow(_:didRequestOpenCameraController:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageSelectorRow"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ImageSelectorRow","preciseIdentifier":"s:5Divar16ImageSelectorRowC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestOpenCameraController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImagePicker","preciseIdentifier":"c:@M@Divar@objc(cs)ImagePicker"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/imageSelectorRow(_:didRequestOpenCameraController:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstractformviewcontroller\/imageselectorrow(_:didrequestopencameracontroller:)"},"doc://com.Divar.DivarClient/documentation/Divar/ImagePicker":{"deprecated":true,"role":"symbol","title":"ImagePicker","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImagePicker"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePicker","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImagePicker"}],"url":"\/documentation\/divar\/imagepicker"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/ImageSelectorRowDelegate-Implementations":{"role":"collectionGroup","title":"ImageSelectorRowDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/ImageSelectorRowDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/abstractformviewcontroller\/imageselectorrowdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController":{"role":"symbol","title":"AbstractFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AbstractFormViewController"}],"url":"\/documentation\/divar\/abstractformviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/ImageSelectorRow":{"role":"symbol","title":"ImageSelectorRow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSelectorRow"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImageSelectorRow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageSelectorRow"}],"url":"\/documentation\/divar\/imageselectorrow"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePicker\/title","value":"ImagePicker"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePicker\/fragments","value":[{"kind":"identifier","text":"ImagePicker"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController\/title","value":"AbstractFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController\/fragments","value":[{"kind":"identifier","text":"AbstractFormViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}