{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBAction"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectCityWithoutDistrict"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/locationselectorviewcontroller\/selectcitywithoutdistrict(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/locationselectorviewcontroller\/selectcitywithoutdistrict(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationSelectorViewController\/selectCityWithoutDistrict(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"selectCityWithoutDistrict:"}],"role":"symbol","title":"selectCityWithoutDistrict(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectCityWithoutDistrict"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@Divar@objc(cs)LocationSelectorViewController(im)selectCityWithoutDistrict:","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationSelectorViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/LocationSelectorViewController/selectCityWithoutDistrict(_:)":{"role":"symbol","title":"selectCityWithoutDistrict(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectCityWithoutDistrict"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationSelectorViewController\/selectCityWithoutDistrict(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectCityWithoutDistrict:"}],"url":"\/documentation\/divar\/locationselectorviewcontroller\/selectcitywithoutdistrict(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/LocationSelectorViewController":{"role":"symbol","title":"LocationSelectorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationSelectorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationSelectorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationSelectorViewController"}],"url":"\/documentation\/divar\/locationselectorviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"selectCityWithoutDistrict:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectCityWithoutDistrict:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"selectCityWithoutDistrict:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":")"},{"kind":"internalParam","text":"_"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LocationSelectorViewController~1selectCityWithoutDistrict(_:)\/title","value":"selectCityWithoutDistrict:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LocationSelectorViewController~1selectCityWithoutDistrict(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectCityWithoutDistrict:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LocationSelectorViewController\/title","value":"LocationSelectorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LocationSelectorViewController\/fragments","value":[{"kind":"identifier","text":"LocationSelectorViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}