{"variants":[{"paths":["\/documentation\/divar\/locationselectorviewcontroller\/uiscrollviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/locationselectorviewcontroller\/uiscrollviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationSelectorViewController\/UIScrollViewDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationSelectorViewController\/scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"UIScrollViewDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationSelectorViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/LocationSelectorViewController":{"role":"symbol","title":"LocationSelectorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationSelectorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationSelectorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationSelectorViewController"}],"url":"\/documentation\/divar\/locationselectorviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/LocationSelectorViewController/scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)":{"role":"symbol","title":"scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewWillEndDragging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withVelocity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"targetContentOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":">)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationSelectorViewController\/scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewWillEndDragging:withVelocity:targetContentOffset:"}],"url":"\/documentation\/divar\/locationselectorviewcontroller\/scrollviewwillenddragging(_:withvelocity:targetcontentoffset:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationSelectorViewController\/scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LocationSelectorViewController\/title","value":"LocationSelectorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LocationSelectorViewController\/fragments","value":[{"kind":"identifier","text":"LocationSelectorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LocationSelectorViewController~1scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)\/title","value":"scrollViewWillEndDragging:withVelocity:targetContentOffset:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LocationSelectorViewController~1scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewWillEndDragging:withVelocity:targetContentOffset:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}