{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"flipsHorizontallyInOppositeLayoutDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/horizontalcollectionflowlayout\/flipshorizontallyinoppositelayoutdirection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/horizontalcollectionflowlayout\/flipshorizontallyinoppositelayoutdirection"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HorizontalCollectionFlowLayout\/flipsHorizontallyInOppositeLayoutDirection","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"flipsHorizontallyInOppositeLayoutDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"flipsHorizontallyInOppositeLayoutDirection","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)HorizontalCollectionFlowLayout(py)flipsHorizontallyInOppositeLayoutDirection","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"flipsHorizontallyInOppositeLayoutDirection"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HorizontalCollectionFlowLayout"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/HorizontalCollectionFlowLayout/flipsHorizontallyInOppositeLayoutDirection":{"role":"symbol","title":"flipsHorizontallyInOppositeLayoutDirection","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"flipsHorizontallyInOppositeLayoutDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HorizontalCollectionFlowLayout\/flipsHorizontallyInOppositeLayoutDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"flipsHorizontallyInOppositeLayoutDirection"}],"url":"\/documentation\/divar\/horizontalcollectionflowlayout\/flipshorizontallyinoppositelayoutdirection"},"doc://com.Divar.DivarClient/documentation/Divar/HorizontalCollectionFlowLayout":{"role":"symbol","title":"HorizontalCollectionFlowLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HorizontalCollectionFlowLayout"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HorizontalCollectionFlowLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HorizontalCollectionFlowLayout"}],"url":"\/documentation\/divar\/horizontalcollectionflowlayout"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"flipsHorizontallyInOppositeLayoutDirection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"flipsHorizontallyInOppositeLayoutDirection"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"flipsHorizontallyInOppositeLayoutDirection"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1HorizontalCollectionFlowLayout~1flipsHorizontallyInOppositeLayoutDirection\/title","value":"flipsHorizontallyInOppositeLayoutDirection"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1HorizontalCollectionFlowLayout~1flipsHorizontallyInOppositeLayoutDirection\/fragments","value":[{"kind":"identifier","text":"flipsHorizontallyInOppositeLayoutDirection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1HorizontalCollectionFlowLayout\/title","value":"HorizontalCollectionFlowLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1HorizontalCollectionFlowLayout\/fragments","value":[{"kind":"identifier","text":"HorizontalCollectionFlowLayout"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}