{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"taglistVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TagListViewController","text":"TagListViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/brandmultihierarchyviewcontroller\/taglistvc"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BrandMultiHierarchyViewController\/taglistVC","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"taglistVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagListViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TagListViewController"}],"title":"taglistVC","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar33BrandMultiHierarchyViewControllerC9taglistVCAA07TagListeF0Cvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BrandMultiHierarchyViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/TagListViewController":{"role":"symbol","title":"TagListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagListViewController"}],"url":"\/documentation\/divar\/taglistviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/BrandMultiHierarchyViewController/taglistVC":{"role":"symbol","title":"taglistVC","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"taglistVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagListViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TagListViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BrandMultiHierarchyViewController\/taglistVC","kind":"symbol","type":"topic","url":"\/documentation\/divar\/brandmultihierarchyviewcontroller\/taglistvc"},"doc://com.Divar.DivarClient/documentation/Divar/BrandMultiHierarchyViewController":{"role":"symbol","title":"BrandMultiHierarchyViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrandMultiHierarchyViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BrandMultiHierarchyViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BrandMultiHierarchyViewController"}],"url":"\/documentation\/divar\/brandmultihierarchyviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListViewController\/title","value":"TagListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListViewController\/fragments","value":[{"kind":"identifier","text":"TagListViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BrandMultiHierarchyViewController\/title","value":"BrandMultiHierarchyViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BrandMultiHierarchyViewController\/fragments","value":[{"kind":"identifier","text":"BrandMultiHierarchyViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}