{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"menu"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIMenu","preciseIdentifier":"c:objc(cs)UIMenu"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/backbarbuttonitem\/menu"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/backbarbuttonitem\/menu"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BackBarButtonItem\/menu","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"menu"}],"role":"symbol","title":"menu","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"menu"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIMenu","preciseIdentifier":"c:objc(cs)UIMenu"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"c:@M@Divar@objc(cs)BackBarButtonItem(py)menu","modules":[{"name":"Divar"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"14.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BackBarButtonItem"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/BackBarButtonItem/menu":{"role":"symbol","title":"menu","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"menu"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIMenu","preciseIdentifier":"c:objc(cs)UIMenu"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BackBarButtonItem\/menu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"menu"}],"url":"\/documentation\/divar\/backbarbuttonitem\/menu"},"doc://com.Divar.DivarClient/documentation/Divar/BackBarButtonItem":{"role":"symbol","title":"BackBarButtonItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BackBarButtonItem"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BackBarButtonItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BackBarButtonItem"}],"url":"\/documentation\/divar\/backbarbuttonitem"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"14.0","deprecated":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"menu"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"menu"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIMenu","preciseIdentifier":"c:objc(cs)UIMenu"},{"kind":"text","text":" * "},{"kind":"identifier","text":"menu"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BackBarButtonItem~1menu\/title","value":"menu"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BackBarButtonItem~1menu\/fragments","value":[{"kind":"identifier","text":"menu"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BackBarButtonItem\/title","value":"BackBarButtonItem"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BackBarButtonItem\/fragments","value":[{"kind":"identifier","text":"BackBarButtonItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}