{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stepIndicatorBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/StepIndicatorBar","preciseIdentifier":"c:@M@Divar@objc(cs)StepIndicatorBar","text":"StepIndicatorBar"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/stepindicatorrowcollectionviewcell\/stepindicatorbar"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/stepindicatorrowcollectionviewcell\/stepindicatorbar"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/StepIndicatorRowCollectionViewCell\/stepIndicatorBar","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stepIndicatorBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StepIndicatorBar","preciseIdentifier":"c:@M@Divar@objc(cs)StepIndicatorBar"},{"kind":"text","text":"!"}],"title":"stepIndicatorBar","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)StepIndicatorRowCollectionViewCell(py)stepIndicatorBar","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"stepIndicatorBar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/StepIndicatorRowCollectionViewCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/StepIndicatorRowCollectionViewCell":{"role":"symbol","title":"StepIndicatorRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StepIndicatorRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/StepIndicatorRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StepIndicatorRowCollectionViewCell"}],"url":"\/documentation\/divar\/stepindicatorrowcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/StepIndicatorRowCollectionViewCell/stepIndicatorBar":{"role":"symbol","title":"stepIndicatorBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stepIndicatorBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StepIndicatorBar","preciseIdentifier":"c:@M@Divar@objc(cs)StepIndicatorBar"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/StepIndicatorRowCollectionViewCell\/stepIndicatorBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stepIndicatorBar"}],"url":"\/documentation\/divar\/stepindicatorrowcollectionviewcell\/stepindicatorbar"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/StepIndicatorBar":{"role":"symbol","title":"StepIndicatorBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StepIndicatorBar"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/StepIndicatorBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StepIndicatorBar"}],"url":"\/documentation\/divar\/stepindicatorbar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"stepIndicatorBar"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"stepIndicatorBar"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/StepIndicatorBar","preciseIdentifier":"c:@M@Divar@objc(cs)StepIndicatorBar","text":"StepIndicatorBar"},{"kind":"text","text":" * "},{"kind":"identifier","text":"stepIndicatorBar"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1StepIndicatorRowCollectionViewCell\/title","value":"StepIndicatorRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1StepIndicatorRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"StepIndicatorRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1StepIndicatorRowCollectionViewCell~1stepIndicatorBar\/title","value":"stepIndicatorBar"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1StepIndicatorRowCollectionViewCell~1stepIndicatorBar\/fragments","value":[{"kind":"identifier","text":"stepIndicatorBar"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1StepIndicatorBar\/title","value":"StepIndicatorBar"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1StepIndicatorBar\/fragments","value":[{"kind":"identifier","text":"StepIndicatorBar"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}