{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statefulView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/StatefulView","preciseIdentifier":"c:@M@Divar@objc(cs)StatefulView","text":"StatefulView"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/statefultableviewcell\/statefulview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/statefultableviewcell\/statefulview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/StatefulTableViewCell\/statefulView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statefulView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StatefulView","preciseIdentifier":"c:@M@Divar@objc(cs)StatefulView"},{"kind":"text","text":"!"}],"title":"statefulView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)StatefulTableViewCell(py)statefulView","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"statefulView"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/StatefulTableViewCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/StatefulTableViewCell/statefulView":{"role":"symbol","title":"statefulView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statefulView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StatefulView","preciseIdentifier":"c:@M@Divar@objc(cs)StatefulView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/StatefulTableViewCell\/statefulView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"statefulView"}],"url":"\/documentation\/divar\/statefultableviewcell\/statefulview"},"doc://com.Divar.DivarClient/documentation/Divar/StatefulTableViewCell":{"role":"symbol","title":"StatefulTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatefulTableViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/StatefulTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatefulTableViewCell"}],"url":"\/documentation\/divar\/statefultableviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/StatefulView":{"role":"symbol","title":"StatefulView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatefulView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/StatefulView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatefulView"}],"url":"\/documentation\/divar\/statefulview"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"statefulView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"statefulView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/StatefulView","preciseIdentifier":"c:@M@Divar@objc(cs)StatefulView","text":"StatefulView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"statefulView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1StatefulTableViewCell~1statefulView\/title","value":"statefulView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1StatefulTableViewCell~1statefulView\/fragments","value":[{"kind":"identifier","text":"statefulView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1StatefulTableViewCell\/title","value":"StatefulTableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1StatefulTableViewCell\/fragments","value":[{"kind":"identifier","text":"StatefulTableViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1StatefulView\/title","value":"StatefulView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1StatefulView\/fragments","value":[{"kind":"identifier","text":"StatefulView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}