{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"booleanRateRowView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BooleanRateRow","preciseIdentifier":"c:@M@Sonnat@objc(cs)BooleanRateRow"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/booleanraterowcollectionviewcell\/booleanraterowview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/booleanraterowcollectionviewcell\/booleanraterowview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BooleanRateRowCollectionViewCell\/booleanRateRowView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"booleanRateRowView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BooleanRateRow","preciseIdentifier":"c:@M@Sonnat@objc(cs)BooleanRateRow"},{"kind":"text","text":"!"}],"title":"booleanRateRowView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)BooleanRateRowCollectionViewCell(py)booleanRateRowView","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"booleanRateRowView"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BooleanRateRowCollectionViewCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/BooleanRateRowCollectionViewCell/booleanRateRowView":{"role":"symbol","title":"booleanRateRowView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"booleanRateRowView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BooleanRateRow","preciseIdentifier":"c:@M@Sonnat@objc(cs)BooleanRateRow"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BooleanRateRowCollectionViewCell\/booleanRateRowView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"booleanRateRowView"}],"url":"\/documentation\/divar\/booleanraterowcollectionviewcell\/booleanraterowview"},"doc://com.Divar.DivarClient/documentation/Divar/BooleanRateRowCollectionViewCell":{"role":"symbol","title":"BooleanRateRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BooleanRateRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BooleanRateRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BooleanRateRowCollectionViewCell"}],"url":"\/documentation\/divar\/booleanraterowcollectionviewcell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"booleanRateRowView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"booleanRateRowView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BooleanRateRow","preciseIdentifier":"c:objc(cs)BooleanRateRow"},{"kind":"text","text":" * "},{"kind":"identifier","text":"booleanRateRowView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BooleanRateRowCollectionViewCell~1booleanRateRowView\/title","value":"booleanRateRowView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BooleanRateRowCollectionViewCell~1booleanRateRowView\/fragments","value":[{"kind":"identifier","text":"booleanRateRowView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BooleanRateRowCollectionViewCell\/title","value":"BooleanRateRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BooleanRateRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"BooleanRateRowCollectionViewCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}