{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"toolbar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIToolbar","preciseIdentifier":"c:objc(cs)UIToolbar"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/segmentedbar\/toolbar"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/segmentedbar\/toolbar"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SegmentedBar\/toolbar","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"toolbar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIToolbar","preciseIdentifier":"c:objc(cs)UIToolbar"},{"kind":"text","text":"!"}],"title":"toolbar","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)SegmentedBar(py)toolbar","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"toolbar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SegmentedBar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/SegmentedBar/toolbar":{"role":"symbol","title":"toolbar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"toolbar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIToolbar","preciseIdentifier":"c:objc(cs)UIToolbar"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SegmentedBar\/toolbar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"toolbar"}],"url":"\/documentation\/divar\/segmentedbar\/toolbar"},"doc://com.Divar.DivarClient/documentation/Divar/SegmentedBar":{"role":"symbol","title":"SegmentedBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SegmentedBar"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SegmentedBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SegmentedBar"}],"url":"\/documentation\/divar\/segmentedbar"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"toolbar"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"toolbar"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIToolbar","preciseIdentifier":"c:objc(cs)UIToolbar"},{"kind":"text","text":" * "},{"kind":"identifier","text":"toolbar"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SegmentedBar~1toolbar\/title","value":"toolbar"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SegmentedBar~1toolbar\/fragments","value":[{"kind":"identifier","text":"toolbar"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SegmentedBar\/title","value":"SegmentedBar"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SegmentedBar\/fragments","value":[{"kind":"identifier","text":"SegmentedBar"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}