{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialPersonalSubmitViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"navigationController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController","text":"NavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"editID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/formflowcontroller\/initialpersonalsubmitviewcontroller(with:editid:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialPersonalSubmitViewController(with:editID:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialPersonalSubmitViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"editID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"title":"initialPersonalSubmitViewController(with:editID:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:5Divar18FormFlowControllerC025initialPersonalSubmitViewD04with6editIDSo06UIViewD0CAA010NavigationD0C_SSSgtF","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/initialPersonalSubmitViewController(with:editID:)":{"role":"symbol","title":"initialPersonalSubmitViewController(with:editID:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialPersonalSubmitViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"editID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialPersonalSubmitViewController(with:editID:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/initialpersonalsubmitviewcontroller(with:editid:)"},"doc://com.Divar.DivarClient/documentation/Divar/NavigationController":{"role":"symbol","title":"NavigationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NavigationController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NavigationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NavigationController"}],"url":"\/documentation\/divar\/navigationcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController":{"role":"symbol","title":"FormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FormFlowController"}],"url":"\/documentation\/divar\/formflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NavigationController\/title","value":"NavigationController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NavigationController\/fragments","value":[{"kind":"identifier","text":"NavigationController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FormFlowController\/title","value":"FormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FormFlowController\/fragments","value":[{"kind":"identifier","text":"FormFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}