{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialScreenWidgetViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"schema"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Schema","preciseIdentifier":"s:5Divar6SchemaV","text":"Schema"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"] = [:]) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScreenWidgetViewController","preciseIdentifier":"c:@M@Divar@objc(cs)ScreenWidgetViewController","text":"ScreenWidgetViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/formflowcontroller\/initialscreenwidgetviewcontroller(schema:data:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialScreenWidgetViewController(schema:data:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialScreenWidgetViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"schema"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"ScreenWidgetViewController","preciseIdentifier":"c:@M@Divar@objc(cs)ScreenWidgetViewController"}],"title":"initialScreenWidgetViewController(schema:data:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:5Divar18FormFlowControllerC023initialScreenWidgetViewD06schema4dataAA0fghD0CAA6SchemaVSg_SDySSypGtF","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/Schema":{"role":"symbol","title":"Schema","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Schema"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Schema","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Schema"}],"url":"\/documentation\/divar\/schema"},"doc://com.Divar.DivarClient/documentation/Divar/ScreenWidgetViewController":{"role":"symbol","title":"ScreenWidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScreenWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScreenWidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScreenWidgetViewController"}],"url":"\/documentation\/divar\/screenwidgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/initialScreenWidgetViewController(schema:data:)":{"role":"symbol","title":"initialScreenWidgetViewController(schema:data:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialScreenWidgetViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"schema"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"ScreenWidgetViewController","preciseIdentifier":"c:@M@Divar@objc(cs)ScreenWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialScreenWidgetViewController(schema:data:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/initialscreenwidgetviewcontroller(schema:data:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController":{"role":"symbol","title":"FormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FormFlowController"}],"url":"\/documentation\/divar\/formflowcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScreenWidgetViewController\/title","value":"ScreenWidgetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScreenWidgetViewController\/fragments","value":[{"kind":"identifier","text":"ScreenWidgetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FormFlowController\/title","value":"FormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FormFlowController\/fragments","value":[{"kind":"identifier","text":"FormFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}