{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialOfflineFormViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"schema"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Schema","preciseIdentifier":"s:5Divar6SchemaV","text":"Schema"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"] = [:]) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OfflineFormViewController","preciseIdentifier":"c:@M@Divar@objc(cs)OfflineFormViewController","text":"OfflineFormViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/formflowcontroller\/initialofflineformviewcontroller(schema:data:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialOfflineFormViewController(schema:data:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialOfflineFormViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"schema"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"OfflineFormViewController","preciseIdentifier":"c:@M@Divar@objc(cs)OfflineFormViewController"}],"title":"initialOfflineFormViewController(schema:data:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:5Divar18FormFlowControllerC014initialOfflineb4ViewD06schema4dataAA0fbgD0CAA6SchemaVSg_SDySSypGtF","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/initialOfflineFormViewController(schema:data:)":{"role":"symbol","title":"initialOfflineFormViewController(schema:data:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialOfflineFormViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"schema"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"OfflineFormViewController","preciseIdentifier":"c:@M@Divar@objc(cs)OfflineFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialOfflineFormViewController(schema:data:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/initialofflineformviewcontroller(schema:data:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController":{"role":"symbol","title":"FormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FormFlowController"}],"url":"\/documentation\/divar\/formflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/Schema":{"role":"symbol","title":"Schema","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Schema"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Schema","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Schema"}],"url":"\/documentation\/divar\/schema"},"doc://com.Divar.DivarClient/documentation/Divar/OfflineFormViewController":{"role":"symbol","title":"OfflineFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OfflineFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OfflineFormViewController"}],"url":"\/documentation\/divar\/offlineformviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FormFlowController\/title","value":"FormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FormFlowController\/fragments","value":[{"kind":"identifier","text":"FormFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OfflineFormViewController\/title","value":"OfflineFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OfflineFormViewController\/fragments","value":[{"kind":"identifier","text":"OfflineFormViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}