{"variants":[{"paths":["\/documentation\/divar\/postgetcontactsviewcontroller\/cxcallobserverdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/postgetcontactsviewcontroller\/cxcallobserverdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostGetContactsViewController\/CXCallObserverDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostGetContactsViewController\/callObserver(_:callChanged:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"CXCallObserverDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostGetContactsViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PostGetContactsViewController/callObserver(_:callChanged:)":{"role":"symbol","title":"callObserver(_:callChanged:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"callObserver"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CXCallObserver","preciseIdentifier":"c:objc(cs)CXCallObserver"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CXCall","preciseIdentifier":"c:objc(cs)CXCall"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostGetContactsViewController\/callObserver(_:callChanged:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"callObserver:callChanged:"}],"url":"\/documentation\/divar\/postgetcontactsviewcontroller\/callobserver(_:callchanged:)"},"doc://com.Divar.DivarClient/documentation/Divar/PostGetContactsViewController":{"role":"symbol","title":"PostGetContactsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostGetContactsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostGetContactsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostGetContactsViewController"}],"url":"\/documentation\/divar\/postgetcontactsviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostGetContactsViewController\/callObserver(_:callChanged:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostGetContactsViewController~1callObserver(_:callChanged:)\/title","value":"callObserver:callChanged:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostGetContactsViewController~1callObserver(_:callChanged:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"callObserver:callChanged:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostGetContactsViewController\/title","value":"PostGetContactsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostGetContactsViewController\/fragments","value":[{"kind":"identifier","text":"PostGetContactsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}