{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mailComposeController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MFMailComposeViewController","preciseIdentifier":"c:objc(cs)MFMailComposeViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishWith"},{"kind":"text","text":" "},{"kind":"internalParam","text":"_"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MFMailComposeResult","preciseIdentifier":"c:@E@MFMailComposeResult"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":" "},{"kind":"internalParam","text":"_"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/postgetcontactsviewcontroller\/mailcomposecontroller(_:didfinishwith:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/postgetcontactsviewcontroller\/mailcomposecontroller(_:didfinishwith:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostGetContactsViewController\/mailComposeController(_:didFinishWith:error:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"MFMailComposeViewControllerDelegate.mailComposeController(_:didFinishWith:error:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mailComposeController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MFMailComposeViewController","preciseIdentifier":"c:objc(cs)MFMailComposeViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MFMailComposeResult","preciseIdentifier":"c:@E@MFMailComposeResult"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"title":"mailComposeController(_:didFinishWith:error:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@Divar@objc(cs)PostGetContactsViewController(im)mailComposeController:didFinishWithResult:error:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"mailComposeController:didFinishWithResult:error:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostGetContactsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostGetContactsViewController\/MFMailComposeViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PostGetContactsViewController/MFMailComposeViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"MFMailComposeViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostGetContactsViewController\/MFMailComposeViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/postgetcontactsviewcontroller\/mfmailcomposeviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PostGetContactsViewController":{"role":"symbol","title":"PostGetContactsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostGetContactsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostGetContactsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostGetContactsViewController"}],"url":"\/documentation\/divar\/postgetcontactsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostGetContactsViewController/mailComposeController(_:didFinishWith:error:)":{"role":"symbol","title":"mailComposeController(_:didFinishWith:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mailComposeController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MFMailComposeViewController","preciseIdentifier":"c:objc(cs)MFMailComposeViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MFMailComposeResult","preciseIdentifier":"c:@E@MFMailComposeResult"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostGetContactsViewController\/mailComposeController(_:didFinishWith:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mailComposeController:didFinishWithResult:error:"}],"url":"\/documentation\/divar\/postgetcontactsviewcontroller\/mailcomposecontroller(_:didfinishwith:error:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"mailComposeController:didFinishWithResult:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mailComposeController:didFinishWithResult:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"mailComposeController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MFMailComposeViewController","preciseIdentifier":"c:objc(cs)MFMailComposeViewController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"_"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishWithResult:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MFMailComposeResult","preciseIdentifier":"c:@E@MFMailComposeResult"},{"kind":"text","text":")"},{"kind":"internalParam","text":"_"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"_"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostGetContactsViewController\/title","value":"PostGetContactsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostGetContactsViewController\/fragments","value":[{"kind":"identifier","text":"PostGetContactsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostGetContactsViewController~1mailComposeController(_:didFinishWith:error:)\/title","value":"mailComposeController:didFinishWithResult:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostGetContactsViewController~1mailComposeController(_:didFinishWith:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mailComposeController:didFinishWithResult:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}