{"variants":[{"paths":["\/documentation\/divar\/postgetcontactsviewcontroller\/mfmessagecomposeviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/postgetcontactsviewcontroller\/mfmessagecomposeviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostGetContactsViewController\/MFMessageComposeViewControllerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostGetContactsViewController\/messageComposeViewController(_:didFinishWith:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"MFMessageComposeViewControllerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostGetContactsViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PostGetContactsViewController":{"role":"symbol","title":"PostGetContactsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostGetContactsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostGetContactsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostGetContactsViewController"}],"url":"\/documentation\/divar\/postgetcontactsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostGetContactsViewController/messageComposeViewController(_:didFinishWith:)":{"role":"symbol","title":"messageComposeViewController(_:didFinishWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageComposeViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MFMessageComposeViewController","preciseIdentifier":"c:objc(cs)MFMessageComposeViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageComposeResult","preciseIdentifier":"c:@E@MessageComposeResult"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostGetContactsViewController\/messageComposeViewController(_:didFinishWith:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageComposeViewController:didFinishWithResult:"}],"url":"\/documentation\/divar\/postgetcontactsviewcontroller\/messagecomposeviewcontroller(_:didfinishwith:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostGetContactsViewController\/messageComposeViewController(_:didFinishWith:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostGetContactsViewController\/title","value":"PostGetContactsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostGetContactsViewController\/fragments","value":[{"kind":"identifier","text":"PostGetContactsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostGetContactsViewController~1messageComposeViewController(_:didFinishWith:)\/title","value":"messageComposeViewController:didFinishWithResult:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostGetContactsViewController~1messageComposeViewController(_:didFinishWith:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageComposeViewController:didFinishWithResult:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}