{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondaryButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SecondaryButton","preciseIdentifier":"c:@M@Divar@objc(cs)SecondaryButton","text":"SecondaryButton"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/secondarybuttontableviewcell\/secondarybutton"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/secondarybuttontableviewcell\/secondarybutton"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SecondaryButtonTableViewCell\/secondaryButton","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondaryButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SecondaryButton","preciseIdentifier":"c:@M@Divar@objc(cs)SecondaryButton"},{"kind":"text","text":"!"}],"title":"secondaryButton","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)SecondaryButtonTableViewCell(py)secondaryButton","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"secondaryButton"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SecondaryButtonTableViewCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/SecondaryButtonTableViewCell":{"role":"symbol","title":"SecondaryButtonTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SecondaryButtonTableViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SecondaryButtonTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SecondaryButtonTableViewCell"}],"url":"\/documentation\/divar\/secondarybuttontableviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/SecondaryButton":{"role":"symbol","title":"SecondaryButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SecondaryButton"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SecondaryButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SecondaryButton"}],"url":"\/documentation\/divar\/secondarybutton"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/SecondaryButtonTableViewCell/secondaryButton":{"role":"symbol","title":"secondaryButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondaryButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SecondaryButton","preciseIdentifier":"c:@M@Divar@objc(cs)SecondaryButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SecondaryButtonTableViewCell\/secondaryButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"secondaryButton"}],"url":"\/documentation\/divar\/secondarybuttontableviewcell\/secondarybutton"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"secondaryButton"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"secondaryButton"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SecondaryButton","preciseIdentifier":"c:@M@Divar@objc(cs)SecondaryButton","text":"SecondaryButton"},{"kind":"text","text":" * "},{"kind":"identifier","text":"secondaryButton"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SecondaryButtonTableViewCell\/title","value":"SecondaryButtonTableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SecondaryButtonTableViewCell\/fragments","value":[{"kind":"identifier","text":"SecondaryButtonTableViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SecondaryButton\/title","value":"SecondaryButton"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SecondaryButton\/fragments","value":[{"kind":"identifier","text":"SecondaryButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SecondaryButtonTableViewCell~1secondaryButton\/title","value":"secondaryButton"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SecondaryButtonTableViewCell~1secondaryButton\/fragments","value":[{"kind":"identifier","text":"secondaryButton"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}