{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractTableViewControllerDelegate"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/abstracttableviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionDetailsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostReportDescriptionViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewControllerDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewControllerDelegate\/abstractTableView(_:selectedIndexesChanges:)-441ri","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewControllerDelegate\/convertList(from:)-320hj","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewControllerDelegate\/didInnerCell(_:with:change:value:)-2pgd7","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewControllerDelegate\/didInnerCell(_:with:select:)-25px4","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewControllerDelegate\/didSelectCell(_:with:)-2ebng","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewControllerDelegate\/didStartInfiniteScroll(_:scrollView:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewControllerDelegate\/didStartPullToRefresh(_:scrollView:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewControllerDelegate\/scrollViewDidScroll(_:)-n43f","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewControllerDelegate\/scrollViewShouldScrollToTop()-1leo2","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewControllerDelegate\/scrollViewWillEndDragging(withVelocity:)-79mnk"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractTableViewControllerDelegate"}],"title":"AbstractTableViewControllerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar35AbstractTableViewControllerDelegateP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"AbstractTableViewControllerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewControllerDelegate/didSelectCell(_:with:)-2ebng":{"defaultImplementations":1,"role":"symbol","title":"didSelectCell(_:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSelectCell"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AbstractTableViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractTableViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewControllerDelegate\/didSelectCell(_:with:)-2ebng","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstracttableviewcontrollerdelegate\/didselectcell(_:with:)-2ebng"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewControllerDelegate/didStartInfiniteScroll(_:scrollView:)":{"role":"symbol","title":"didStartInfiniteScroll(_:scrollView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didStartInfiniteScroll"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AbstractTableViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractTableViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scrollView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewControllerDelegate\/didStartInfiniteScroll(_:scrollView:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstracttableviewcontrollerdelegate\/didstartinfinitescroll(_:scrollview:)"},"doc://com.Divar.DivarClient/documentation/Divar/NoteViewController":{"role":"symbol","title":"NoteViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NoteViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NoteViewController"}],"url":"\/documentation\/divar\/noteviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/DealerSubscriptionDetailsViewController":{"role":"symbol","title":"DealerSubscriptionDetailsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DealerSubscriptionDetailsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionDetailsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DealerSubscriptionDetailsViewController"}],"url":"\/documentation\/divar\/dealersubscriptiondetailsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewControllerDelegate/didInnerCell(_:with:select:)-25px4":{"defaultImplementations":1,"role":"symbol","title":"didInnerCell(_:with:select:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didInnerCell"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AbstractTableViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractTableViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"select"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConfigurableCellEnum","preciseIdentifier":"s:5Divar20ConfigurableCellEnumO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewControllerDelegate\/didInnerCell(_:with:select:)-25px4","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstracttableviewcontrollerdelegate\/didinnercell(_:with:select:)-25px4"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewControllerDelegate/scrollViewShouldScrollToTop()-1leo2":{"defaultImplementations":1,"role":"symbol","title":"scrollViewShouldScrollToTop()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewShouldScrollToTop"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewControllerDelegate\/scrollViewShouldScrollToTop()-1leo2","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstracttableviewcontrollerdelegate\/scrollviewshouldscrolltotop()-1leo2"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewControllerDelegate/didStartPullToRefresh(_:scrollView:)":{"role":"symbol","title":"didStartPullToRefresh(_:scrollView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didStartPullToRefresh"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AbstractTableViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractTableViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scrollView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewControllerDelegate\/didStartPullToRefresh(_:scrollView:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstracttableviewcontrollerdelegate\/didstartpulltorefresh(_:scrollview:)"},"doc://com.Divar.DivarClient/documentation/Divar/PostReportDescriptionViewController":{"role":"symbol","title":"PostReportDescriptionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostReportDescriptionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostReportDescriptionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostReportDescriptionViewController"}],"url":"\/documentation\/divar\/postreportdescriptionviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewControllerDelegate/scrollViewWillEndDragging(withVelocity:)-79mnk":{"defaultImplementations":1,"role":"symbol","title":"scrollViewWillEndDragging(withVelocity:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewWillEndDragging"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withVelocity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewControllerDelegate\/scrollViewWillEndDragging(withVelocity:)-79mnk","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstracttableviewcontrollerdelegate\/scrollviewwillenddragging(withvelocity:)-79mnk"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewControllerDelegate":{"role":"symbol","title":"AbstractTableViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractTableViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AbstractTableViewControllerDelegate"}],"url":"\/documentation\/divar\/abstracttableviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewControllerDelegate/didInnerCell(_:with:change:value:)-2pgd7":{"defaultImplementations":1,"role":"symbol","title":"didInnerCell(_:with:change:value:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didInnerCell"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AbstractTableViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractTableViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"change"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConfigurableCellEnum","preciseIdentifier":"s:5Divar20ConfigurableCellEnumO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewControllerDelegate\/didInnerCell(_:with:change:value:)-2pgd7","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstracttableviewcontrollerdelegate\/didinnercell(_:with:change:value:)-2pgd7"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewControllerDelegate/scrollViewDidScroll(_:)-n43f":{"defaultImplementations":1,"role":"symbol","title":"scrollViewDidScroll(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidScroll"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewControllerDelegate\/scrollViewDidScroll(_:)-n43f","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstracttableviewcontrollerdelegate\/scrollviewdidscroll(_:)-n43f"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewControllerDelegate/abstractTableView(_:selectedIndexesChanges:)-441ri":{"defaultImplementations":1,"role":"symbol","title":"abstractTableView(_:selectedIndexesChanges:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"abstractTableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AbstractTableViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractTableViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"selectedIndexesChanges"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewControllerDelegate\/abstractTableView(_:selectedIndexesChanges:)-441ri","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstracttableviewcontrollerdelegate\/abstracttableview(_:selectedindexeschanges:)-441ri"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewControllerDelegate/convertList(from:)-320hj":{"defaultImplementations":1,"role":"symbol","title":"convertList(from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertList"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AbstractTableList","preciseIdentifier":"s:5Divar17AbstractTableListV"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"CellConfigurator","preciseIdentifier":"s:5Divar16CellConfiguratorP"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewControllerDelegate\/convertList(from:)-320hj","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstracttableviewcontrollerdelegate\/convertlist(from:)-320hj"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteViewController\/title","value":"NoteViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteViewController\/fragments","value":[{"kind":"identifier","text":"NoteViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubscriptionDetailsViewController\/title","value":"DealerSubscriptionDetailsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubscriptionDetailsViewController\/fragments","value":[{"kind":"identifier","text":"DealerSubscriptionDetailsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostReportDescriptionViewController\/title","value":"PostReportDescriptionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostReportDescriptionViewController\/fragments","value":[{"kind":"identifier","text":"PostReportDescriptionViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}