{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractFormViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/abstractformviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/abstractformviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AlakBaseRowToParentDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ComponentProtocol","doc:\/\/com.Divar.DivarClient\/6Eureka12FormDelegateP","doc:\/\/com.Divar.DivarClient\/6Eureka26FormViewControllerProtocolP","doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImageSelectorRowDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIScrollViewDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDataSource","doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoSelectorWidgetRowToParentControllerDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/init(container:previousData:shouldAddButtonRow:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/delegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/formAccessoryViewSttribute","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/previousData","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/shouldAddButtonRow","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/slug"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/didGetLocalValidationErrors(errors:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/executeField(withKey:completion:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/generateForm(with:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/handleStandardError(error:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/implementSubmitValidationErrors(properties:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/refreshForm(form:metaVeriosn:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/removeFocusedRowValue()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/resetForm()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/saveDraft(on:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/submitForm(form:draft:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/tableView(_:didSelectRowAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/tableView(_:heightForRowAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/valueHasBeenChanged(for:oldValue:newValue:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/viewDidLayoutSubviews()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/viewDidLoad()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/viewWillDisappear(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/AlakBaseRowToParentDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/ImageSelectorRowDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/VideoSelectorWidgetRowToParentControllerDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractFormViewController"}],"title":"AbstractFormViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)AbstractFormViewController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"AbstractFormViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/generateForm(with:)":{"role":"symbol","title":"generateForm(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateForm"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Form","preciseIdentifier":"s:6Eureka4FormC"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/generateForm(with:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstractformviewcontroller\/generateform(with:)"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/executeField(withKey:completion:)":{"role":"symbol","title":"executeField(withKey:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"executeField"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"row"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseRow","preciseIdentifier":"s:6Eureka7BaseRowC"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/executeField(withKey:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstractformviewcontroller\/executefield(withkey:completion:)"},"doc://com.Divar.DivarClient/6Eureka12FormDelegateP":{"type":"unresolvable","title":"Eureka.FormDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/6Eureka12FormDelegateP"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/slug":{"role":"symbol","title":"slug","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"slug"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/slug","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstractformviewcontroller\/slug"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController":{"role":"symbol","title":"AbstractFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AbstractFormViewController"}],"url":"\/documentation\/divar\/abstractformviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/removeFocusedRowValue()":{"role":"symbol","title":"removeFocusedRowValue()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeFocusedRowValue"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/removeFocusedRowValue()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeFocusedRowValue"}],"url":"\/documentation\/divar\/abstractformviewcontroller\/removefocusedrowvalue()"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/handleStandardError(error:)":{"role":"symbol","title":"handleStandardError(error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleStandardError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Base_BadRequestJsonSchemaData","preciseIdentifier":"s:19DivarInterfaceSwift29Base_BadRequestJsonSchemaDataV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/handleStandardError(error:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstractformviewcontroller\/handlestandarderror(error:)"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/tableView(_:heightForRowAt:)":{"role":"symbol","title":"tableView(_:heightForRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"heightForRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/tableView(_:heightForRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:heightForRowAtIndexPath:"}],"url":"\/documentation\/divar\/abstractformviewcontroller\/tableview(_:heightforrowat:)"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/formAccessoryViewSttribute":{"role":"symbol","title":"formAccessoryViewSttribute","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"formAccessoryViewSttribute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormAccessoryViewAttribute","preciseIdentifier":"s:5Divar26FormAccessoryViewAttributeV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/formAccessoryViewSttribute","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstractformviewcontroller\/formaccessoryviewsttribute"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AbstractFormViewContorllerDelegate","preciseIdentifier":"s:5Divar34AbstractFormViewContorllerDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstractformviewcontroller\/delegate"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/ImageSelectorRowDelegate-Implementations":{"role":"collectionGroup","title":"ImageSelectorRowDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/ImageSelectorRowDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/abstractformviewcontroller\/imageselectorrowdelegate-implementations"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/init(container:previousData:shouldAddButtonRow:)":{"role":"symbol","title":"init(container:previousData:shouldAddButtonRow:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AbstractFormViewControllerDIContainer","preciseIdentifier":"s:5Divar37AbstractFormViewControllerDIContainera"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previousData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"shouldAddButtonRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/init(container:previousData:shouldAddButtonRow:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstractformviewcontroller\/init(container:previousdata:shouldaddbuttonrow:)"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/objc(pl)UITableViewDataSource":{"type":"unresolvable","title":"UIKit.UITableViewDataSource","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDataSource"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/AlakBaseRowToParentDelegate-Implementations":{"role":"collectionGroup","title":"AlakBaseRowToParentDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/AlakBaseRowToParentDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/abstractformviewcontroller\/alakbaserowtoparentdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/implementSubmitValidationErrors(properties:)":{"role":"symbol","title":"implementSubmitValidationErrors(properties:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"implementSubmitValidationErrors"},{"kind":"text","text":"("},{"kind":"externalParam","text":"properties"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"SubmitValidationError","preciseIdentifier":"s:5Divar21SubmitValidationErrorV"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/implementSubmitValidationErrors(properties:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstractformviewcontroller\/implementsubmitvalidationerrors(properties:)"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/abstractformviewcontroller\/init(coder:)"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/shouldAddButtonRow":{"role":"symbol","title":"shouldAddButtonRow","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldAddButtonRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/shouldAddButtonRow","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstractformviewcontroller\/shouldaddbuttonrow"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/valueHasBeenChanged(for:oldValue:newValue:)":{"role":"symbol","title":"valueHasBeenChanged(for:oldValue:newValue:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"valueHasBeenChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseRow","preciseIdentifier":"s:6Eureka7BaseRowC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"oldValue"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"newValue"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/valueHasBeenChanged(for:oldValue:newValue:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstractformviewcontroller\/valuehasbeenchanged(for:oldvalue:newvalue:)"},"doc://com.Divar.DivarClient/objc(pl)UITableViewDelegate":{"type":"unresolvable","title":"UIKit.UITableViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/previousData":{"role":"symbol","title":"previousData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previousData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/previousData","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstractformviewcontroller\/previousdata"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/refreshForm(form:metaVeriosn:)":{"role":"symbol","title":"refreshForm(form:metaVeriosn:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshForm"},{"kind":"text","text":"("},{"kind":"externalParam","text":"form"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Form","preciseIdentifier":"s:6Eureka4FormC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metaVeriosn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/refreshForm(form:metaVeriosn:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstractformviewcontroller\/refreshform(form:metaveriosn:)"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/submitForm(form:draft:)":{"role":"symbol","title":"submitForm(form:draft:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"submitForm"},{"kind":"text","text":"("},{"kind":"externalParam","text":"form"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Form","preciseIdentifier":"s:6Eureka4FormC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"draft"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/submitForm(form:draft:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstractformviewcontroller\/submitform(form:draft:)"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/saveDraft(on:)":{"role":"symbol","title":"saveDraft(on:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"saveDraft"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentHelperProtocol","preciseIdentifier":"s:5Divar22DocumentHelperProtocolP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/saveDraft(on:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstractformviewcontroller\/savedraft(on:)"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/tableView(_:didSelectRowAt:)":{"role":"symbol","title":"tableView(_:didSelectRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/tableView(_:didSelectRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:didSelectRowAtIndexPath:"}],"url":"\/documentation\/divar\/abstractformviewcontroller\/tableview(_:didselectrowat:)"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/resetForm()":{"role":"symbol","title":"resetForm()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetForm"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/resetForm()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstractformviewcontroller\/resetform()"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController":{"role":"symbol","title":"BaseFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseFormViewController"}],"url":"\/documentation\/divar\/baseformviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/viewWillDisappear(_:)":{"role":"symbol","title":"viewWillDisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/viewWillDisappear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillDisappear:"}],"url":"\/documentation\/divar\/abstractformviewcontroller\/viewwilldisappear(_:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIScrollViewDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/VideoSelectorWidgetRowToParentControllerDelegate":{"role":"symbol","title":"VideoSelectorWidgetRowToParentControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoSelectorWidgetRowToParentControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoSelectorWidgetRowToParentControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoSelectorWidgetRowToParentControllerDelegate"}],"url":"\/documentation\/divar\/videoselectorwidgetrowtoparentcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/ImageSelectorRowDelegate":{"role":"symbol","title":"ImageSelectorRowDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSelectorRowDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImageSelectorRowDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageSelectorRowDelegate"}],"url":"\/documentation\/divar\/imageselectorrowdelegate"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/ComponentProtocol":{"role":"symbol","title":"ComponentProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComponentProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ComponentProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ComponentProtocol"}],"url":"\/documentation\/divar\/componentprotocol"},"doc://com.Divar.DivarClient/6Eureka26FormViewControllerProtocolP":{"type":"unresolvable","title":"Eureka.FormViewControllerProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/6Eureka26FormViewControllerProtocolP"},"doc://com.Divar.DivarClient/documentation/Divar/ShowErrorProtocol":{"role":"symbol","title":"ShowErrorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowErrorProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowErrorProtocol"}],"url":"\/documentation\/divar\/showerrorprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/VideoSelectorWidgetRowToParentControllerDelegate-Implementations":{"role":"collectionGroup","title":"VideoSelectorWidgetRowToParentControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/VideoSelectorWidgetRowToParentControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/abstractformviewcontroller\/videoselectorwidgetrowtoparentcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/abstractformviewcontroller\/viewdidload()"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/didGetLocalValidationErrors(errors:)":{"role":"symbol","title":"didGetLocalValidationErrors(errors:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didGetLocalValidationErrors"},{"kind":"text","text":"("},{"kind":"externalParam","text":"errors"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"BaseRow","preciseIdentifier":"s:6Eureka7BaseRowC"},{"kind":"text","text":" : ["},{"kind":"typeIdentifier","text":"ValidationError","preciseIdentifier":"s:6Eureka15ValidationErrorV"},{"kind":"text","text":"]])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/didGetLocalValidationErrors(errors:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstractformviewcontroller\/didgetlocalvalidationerrors(errors:)"},"doc://com.Divar.DivarClient/documentation/Divar/AlakBaseRowToParentDelegate":{"role":"symbol","title":"AlakBaseRowToParentDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlakBaseRowToParentDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AlakBaseRowToParentDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AlakBaseRowToParentDelegate"}],"url":"\/documentation\/divar\/alakbaserowtoparentdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/ShowMessageProtocol":{"role":"symbol","title":"ShowMessageProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowMessageProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowMessageProtocol"}],"url":"\/documentation\/divar\/showmessageprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController/viewDidLayoutSubviews()":{"role":"symbol","title":"viewDidLayoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLayoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/viewDidLayoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLayoutSubviews"}],"url":"\/documentation\/divar\/abstractformviewcontroller\/viewdidlayoutsubviews()"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AbstractFormViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AbstractFormViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AbstractFormViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/removeFocusedRowValue()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/tableView(_:didSelectRowAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/tableView(_:heightForRowAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/viewDidLayoutSubviews()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/viewDidLoad()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController\/viewWillDisappear(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractFormViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController","preciseIdentifier":"c:@M@Divar@objc(cs)BaseFormViewController","text":"BaseFormViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController\/title","value":"AbstractFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController\/fragments","value":[{"kind":"identifier","text":"AbstractFormViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController~1removeFocusedRowValue()\/title","value":"removeFocusedRowValue"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController~1removeFocusedRowValue()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeFocusedRowValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController~1tableView(_:heightForRowAt:)\/title","value":"tableView:heightForRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController~1tableView(_:heightForRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:heightForRowAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController~1tableView(_:didSelectRowAt:)\/title","value":"tableView:didSelectRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController~1tableView(_:didSelectRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:didSelectRowAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFormViewController\/title","value":"BaseFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFormViewController\/fragments","value":[{"kind":"identifier","text":"BaseFormViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController~1viewWillDisappear(_:)\/title","value":"viewWillDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController~1viewWillDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillDisappear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController~1viewDidLayoutSubviews()\/title","value":"viewDidLayoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController~1viewDidLayoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLayoutSubviews"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}