{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractTableViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/abstracttableviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/abstracttableviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ComponentProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConfigurableCellDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIScrollViewDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDataSource","doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/init()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/init(coder:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/delegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/offset","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/page","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/posts","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/setupUI","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/table"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/addNewPage(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/deselect(at:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/refresh()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/reloadData()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/setupPullToRefresh()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/ConfigurableCellDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/UIScrollViewDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/UITableViewDataSource-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/UITableViewDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractTableViewController"}],"title":"AbstractTableViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)AbstractTableViewController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"AbstractTableViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController/page":{"role":"symbol","title":"page","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"page"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/page","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstracttableviewcontroller\/page"},"doc://com.Divar.DivarClient/documentation/Divar/ConfigurableCellDelegate":{"role":"symbol","title":"ConfigurableCellDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConfigurableCellDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConfigurableCellDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConfigurableCellDelegate"}],"url":"\/documentation\/divar\/configurablecelldelegate"},"doc://com.Divar.DivarClient/documentation/Divar/ComponentProtocol":{"role":"symbol","title":"ComponentProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComponentProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ComponentProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ComponentProtocol"}],"url":"\/documentation\/divar\/componentprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController/setupUI":{"role":"symbol","title":"setupUI","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupUI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/setupUI","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstracttableviewcontroller\/setupui"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController/ConfigurableCellDelegate-Implementations":{"role":"collectionGroup","title":"ConfigurableCellDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/ConfigurableCellDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/abstracttableviewcontroller\/configurablecelldelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController/refresh()":{"role":"symbol","title":"refresh()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/refresh()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"refresh"}],"url":"\/documentation\/divar\/abstracttableviewcontroller\/refresh()"},"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController/reloadData()":{"role":"symbol","title":"reloadData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reloadData"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/reloadData()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstracttableviewcontroller\/reloaddata()"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/abstracttableviewcontroller\/viewdidload()"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController/offset":{"role":"symbol","title":"offset","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"offset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLongLong","preciseIdentifier":"s:s9CLongLonga"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/offset","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstracttableviewcontroller\/offset"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController/UITableViewDelegate-Implementations":{"role":"collectionGroup","title":"UITableViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/UITableViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/abstracttableviewcontroller\/uitableviewdelegate-implementations"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController/setupPullToRefresh()":{"role":"symbol","title":"setupPullToRefresh()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupPullToRefresh"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/setupPullToRefresh()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstracttableviewcontroller\/setuppulltorefresh()"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController/deselect(at:)":{"role":"symbol","title":"deselect(at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deselect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/deselect(at:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstracttableviewcontroller\/deselect(at:)"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController/table":{"role":"symbol","title":"table","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"table"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdvancedTableView","preciseIdentifier":"c:@M@Divar@objc(cs)AdvancedTableView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/table","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"table"}],"url":"\/documentation\/divar\/abstracttableviewcontroller\/table"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/abstracttableviewcontroller\/init(coder:)"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIScrollViewDelegate"},"doc://com.Divar.DivarClient/objc(pl)UITableViewDelegate":{"type":"unresolvable","title":"UIKit.UITableViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDelegate"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController/UIScrollViewDelegate-Implementations":{"role":"collectionGroup","title":"UIScrollViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/UIScrollViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/abstracttableviewcontroller\/uiscrollviewdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController/UITableViewDataSource-Implementations":{"role":"collectionGroup","title":"UITableViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/UITableViewDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/abstracttableviewcontroller\/uitableviewdatasource-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController/addNewPage(_:)":{"role":"symbol","title":"addNewPage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addNewPage"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"CellConfigurator","preciseIdentifier":"s:5Divar16CellConfiguratorP"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/addNewPage(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstracttableviewcontroller\/addnewpage(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController":{"role":"symbol","title":"AbstractTableViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractTableViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AbstractTableViewController"}],"url":"\/documentation\/divar\/abstracttableviewcontroller"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AbstractTableViewControllerDelegate","preciseIdentifier":"s:5Divar35AbstractTableViewControllerDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstracttableviewcontroller\/delegate"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)UIViewController"},"doc://com.Divar.DivarClient/objc(pl)UITableViewDataSource":{"type":"unresolvable","title":"UIKit.UITableViewDataSource","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDataSource"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController/posts":{"role":"symbol","title":"posts","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"posts"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CellConfigurator","preciseIdentifier":"s:5Divar16CellConfiguratorP"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/posts","kind":"symbol","type":"topic","url":"\/documentation\/divar\/abstracttableviewcontroller\/posts"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/divar\/abstracttableviewcontroller\/init()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AbstractTableViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AbstractTableViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AbstractTableViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/table"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/init()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/refresh()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/UIScrollViewDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/UITableViewDataSource-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController\/UITableViewDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractTableViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController~1refresh()\/title","value":"refresh"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController~1refresh()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refresh"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController~1table\/title","value":"table"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController~1table\/fragments","value":[{"kind":"identifier","text":"table"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController\/title","value":"AbstractTableViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController\/fragments","value":[{"kind":"identifier","text":"AbstractTableViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}