{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractFormActionDelegate"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/abstractformactiondelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentFormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarPriceFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerFormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JobsFormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceFormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateFormFlowController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormActionDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormActionDelegate\/didClickSecondaryButton(_:)-8kwfr","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormActionDelegate\/didClickSubmit(_:)-hzva","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormActionDelegate\/didFinishGetSchema(_:failureWithError:refreshOnError:)-54wmn","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormActionDelegate\/didFinishGetSchema(_:schema:prefillData:completion:)-8u216","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormActionDelegate\/didFinishSubmit(_:successWithData:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormActionDelegate\/didRequestRefresh(_:)-v7kd","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormActionDelegate\/didRequestResetForm(_:)-1bf4e","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormActionDelegate\/submitDidFail(_:withError:)-5zkiy","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormActionDelegate\/submitDidFail(_:withValidationError:)-1c8it"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractFormActionDelegate"}],"title":"AbstractFormActionDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar26AbstractFormActionDelegateP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"AbstractFormActionDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/CarPriceFlowController":{"role":"symbol","title":"CarPriceFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarPriceFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarPriceFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarPriceFlowController"}],"url":"\/documentation\/divar\/carpriceflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormActionDelegate/didClickSubmit(_:)-hzva":{"defaultImplementations":1,"role":"symbol","title":"didClickSubmit(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didClickSubmit"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseFormController","preciseIdentifier":"c:@M@Divar@objc(cs)BaseFormController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormActionDelegate\/didClickSubmit(_:)-hzva","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstractformactiondelegate\/didclicksubmit(_:)-hzva"},"doc://com.Divar.DivarClient/documentation/Divar/JobsFormFlowController":{"role":"symbol","title":"JobsFormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JobsFormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JobsFormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JobsFormFlowController"}],"url":"\/documentation\/divar\/jobsformflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormActionDelegate/didFinishGetSchema(_:failureWithError:refreshOnError:)-54wmn":{"defaultImplementations":1,"role":"symbol","title":"didFinishGetSchema(_:failureWithError:refreshOnError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishGetSchema"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseFormViewProtocol","preciseIdentifier":"s:5Divar20BaseFormViewProtocola"},{"kind":"text","text":", "},{"kind":"externalParam","text":"failureWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DError","preciseIdentifier":"s:5Divar6DErrorV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"refreshOnError"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormActionDelegate\/didFinishGetSchema(_:failureWithError:refreshOnError:)-54wmn","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstractformactiondelegate\/didfinishgetschema(_:failurewitherror:refreshonerror:)-54wmn"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormActionDelegate/didFinishGetSchema(_:schema:prefillData:completion:)-8u216":{"defaultImplementations":1,"role":"symbol","title":"didFinishGetSchema(_:schema:prefillData:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishGetSchema"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseFormViewProtocol","preciseIdentifier":"s:5Divar20BaseFormViewProtocola"},{"kind":"text","text":", "},{"kind":"externalParam","text":"schema"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"prefillData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CompletionHandlerType","preciseIdentifier":"s:5Divar21CompletionHandlerTypea"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormActionDelegate\/didFinishGetSchema(_:schema:prefillData:completion:)-8u216","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstractformactiondelegate\/didfinishgetschema(_:schema:prefilldata:completion:)-8u216"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormActionDelegate/submitDidFail(_:withError:)-5zkiy":{"defaultImplementations":1,"role":"symbol","title":"submitDidFail(_:withError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"submitDidFail"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseFormViewProtocol","preciseIdentifier":"s:5Divar20BaseFormViewProtocola"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormActionDelegate\/submitDidFail(_:withError:)-5zkiy","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstractformactiondelegate\/submitdidfail(_:witherror:)-5zkiy"},"doc://com.Divar.DivarClient/documentation/Divar/DealerFormFlowController":{"role":"symbol","title":"DealerFormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DealerFormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerFormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DealerFormFlowController"}],"url":"\/documentation\/divar\/dealerformflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormActionDelegate/didRequestResetForm(_:)-1bf4e":{"defaultImplementations":1,"role":"symbol","title":"didRequestResetForm(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRequestResetForm"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseFormController","preciseIdentifier":"c:@M@Divar@objc(cs)BaseFormController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormActionDelegate\/didRequestResetForm(_:)-1bf4e","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstractformactiondelegate\/didrequestresetform(_:)-1bf4e"},"doc://com.Divar.DivarClient/documentation/Divar/CarAgentFormFlowController":{"role":"symbol","title":"CarAgentFormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarAgentFormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentFormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarAgentFormFlowController"}],"url":"\/documentation\/divar\/caragentformflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PriceFlowController":{"role":"symbol","title":"PriceFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PriceFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PriceFlowController"}],"url":"\/documentation\/divar\/priceflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormActionDelegate":{"role":"symbol","title":"AbstractFormActionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractFormActionDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormActionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AbstractFormActionDelegate"}],"url":"\/documentation\/divar\/abstractformactiondelegate"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormActionDelegate/didRequestRefresh(_:)-v7kd":{"defaultImplementations":1,"role":"symbol","title":"didRequestRefresh(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRequestRefresh"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseFormController","preciseIdentifier":"c:@M@Divar@objc(cs)BaseFormController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormActionDelegate\/didRequestRefresh(_:)-v7kd","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstractformactiondelegate\/didrequestrefresh(_:)-v7kd"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController":{"role":"symbol","title":"FormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FormFlowController"}],"url":"\/documentation\/divar\/formflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/RealEstateFormFlowController":{"role":"symbol","title":"RealEstateFormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RealEstateFormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateFormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RealEstateFormFlowController"}],"url":"\/documentation\/divar\/realestateformflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MarketplaceFormFlowController":{"role":"symbol","title":"MarketplaceFormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketplaceFormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceFormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketplaceFormFlowController"}],"url":"\/documentation\/divar\/marketplaceformflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormActionDelegate/didFinishSubmit(_:successWithData:)":{"role":"symbol","title":"didFinishSubmit(_:successWithData:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishSubmit"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseFormViewProtocol","preciseIdentifier":"s:5Divar20BaseFormViewProtocola"},{"kind":"text","text":", "},{"kind":"externalParam","text":"successWithData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SubmitRequestStruct","preciseIdentifier":"s:5Divar19SubmitRequestStructV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormActionDelegate\/didFinishSubmit(_:successWithData:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstractformactiondelegate\/didfinishsubmit(_:successwithdata:)"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormActionDelegate/didClickSecondaryButton(_:)-8kwfr":{"defaultImplementations":1,"role":"symbol","title":"didClickSecondaryButton(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didClickSecondaryButton"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseFormController","preciseIdentifier":"c:@M@Divar@objc(cs)BaseFormController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormActionDelegate\/didClickSecondaryButton(_:)-8kwfr","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstractformactiondelegate\/didclicksecondarybutton(_:)-8kwfr"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormActionDelegate/submitDidFail(_:withValidationError:)-1c8it":{"defaultImplementations":1,"role":"symbol","title":"submitDidFail(_:withValidationError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"submitDidFail"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseFormViewProtocol","preciseIdentifier":"s:5Divar20BaseFormViewProtocola"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withValidationError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SubmitValidationError","preciseIdentifier":"s:5Divar21SubmitValidationErrorV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormActionDelegate\/submitDidFail(_:withValidationError:)-1c8it","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstractformactiondelegate\/submitdidfail(_:withvalidationerror:)-1c8it"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarPriceFlowController\/title","value":"CarPriceFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarPriceFlowController\/fragments","value":[{"kind":"identifier","text":"CarPriceFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JobsFormFlowController\/title","value":"JobsFormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JobsFormFlowController\/fragments","value":[{"kind":"identifier","text":"JobsFormFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerFormFlowController\/title","value":"DealerFormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerFormFlowController\/fragments","value":[{"kind":"identifier","text":"DealerFormFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentFormFlowController\/title","value":"CarAgentFormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentFormFlowController\/fragments","value":[{"kind":"identifier","text":"CarAgentFormFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceFlowController\/title","value":"PriceFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceFlowController\/fragments","value":[{"kind":"identifier","text":"PriceFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FormFlowController\/title","value":"FormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FormFlowController\/fragments","value":[{"kind":"identifier","text":"FormFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateFormFlowController\/title","value":"RealEstateFormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateFormFlowController\/fragments","value":[{"kind":"identifier","text":"RealEstateFormFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceFormFlowController\/title","value":"MarketplaceFormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceFormFlowController\/fragments","value":[{"kind":"identifier","text":"MarketplaceFormFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}