{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractFormViewContorllerDelegate"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/abstractformviewcontorllerdelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddEditAgentViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddSalesmanViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddStoreManagerViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddUserTransactionFormViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddVRViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BooleanRateFormViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BusinessSubscriptionViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BuyBulkLadderViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentBuyLadderPackageViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentBuyPackageViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentSubmitViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarInspectionRegisterViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarInspectionSubmitViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CreateAndEditOperatorViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubmitViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/EditMarketplaceStoreViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JobsSubmitViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketpalceFeedbackViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceEditAssistantViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceQuickEditPostVC","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceSubmitViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceSubscriptionViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OfflineFormViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateRegistrationViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateSubmitViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RegisterAgentViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RegisterDealerViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RegisterMarketplaceViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SchemaFormViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScreenWidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchFilterViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SendFeedbackViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UsedPriceFormViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedFilterViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewContorllerDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewContorllerDelegate\/actionDelegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewContorllerDelegate\/didRemoveFocusedRowValue(_:row:)-5f7bz","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewContorllerDelegate\/didSetupTableView(_:for:)-lqfn","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewContorllerDelegate\/didStartLoadingData(_:for:)-1vkd","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewContorllerDelegate\/didStartRefreshingForm(_:currentPage:currentData:previousData:)-4ryqq","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewContorllerDelegate\/didStartSubmitingForm(_:currentPage:currentData:previousData:)-8ccfm","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewContorllerDelegate\/formController(_:didGetLocalValidationErrors:)-63efe","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewContorllerDelegate\/formController(_:didRequestChangeSubmitButtonState:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewContorllerDelegate\/formController(_:didSelect:)-1csjl","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewContorllerDelegate\/valueHasBeenChanged(_:for:oldValue:newValue:)-582kn"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractFormViewContorllerDelegate"}],"title":"AbstractFormViewContorllerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar34AbstractFormViewContorllerDelegateP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"AbstractFormViewContorllerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/JobsSubmitViewController":{"role":"symbol","title":"JobsSubmitViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JobsSubmitViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JobsSubmitViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JobsSubmitViewController"}],"url":"\/documentation\/divar\/jobssubmitviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewContorllerDelegate/didStartSubmitingForm(_:currentPage:currentData:previousData:)-8ccfm":{"defaultImplementations":1,"role":"symbol","title":"didStartSubmitingForm(_:currentPage:currentData:previousData:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didStartSubmitingForm"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AbstractFormViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractFormViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currentPage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currentData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"previousData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewContorllerDelegate\/didStartSubmitingForm(_:currentPage:currentData:previousData:)-8ccfm","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstractformviewcontorllerdelegate\/didstartsubmitingform(_:currentpage:currentdata:previousdata:)-8ccfm"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewContorllerDelegate/didSetupTableView(_:for:)-lqfn":{"defaultImplementations":1,"role":"symbol","title":"didSetupTableView(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSetupTableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AbstractFormViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractFormViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewContorllerDelegate\/didSetupTableView(_:for:)-lqfn","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstractformviewcontorllerdelegate\/didsetuptableview(_:for:)-lqfn"},"doc://com.Divar.DivarClient/documentation/Divar/SendFeedbackViewController":{"role":"symbol","title":"SendFeedbackViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SendFeedbackViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SendFeedbackViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SendFeedbackViewController"}],"url":"\/documentation\/divar\/sendfeedbackviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BuyBulkLadderViewController":{"role":"symbol","title":"BuyBulkLadderViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BuyBulkLadderViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BuyBulkLadderViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BuyBulkLadderViewController"}],"url":"\/documentation\/divar\/buybulkladderviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewContorllerDelegate/valueHasBeenChanged(_:for:oldValue:newValue:)-582kn":{"defaultImplementations":1,"role":"symbol","title":"valueHasBeenChanged(_:for:oldValue:newValue:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"valueHasBeenChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AbstractFormViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractFormViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseRow","preciseIdentifier":"s:6Eureka7BaseRowC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"oldValue"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"newValue"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewContorllerDelegate\/valueHasBeenChanged(_:for:oldValue:newValue:)-582kn","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstractformviewcontorllerdelegate\/valuehasbeenchanged(_:for:oldvalue:newvalue:)-582kn"},"doc://com.Divar.DivarClient/documentation/Divar/RegisterAgentViewController":{"role":"symbol","title":"RegisterAgentViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RegisterAgentViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RegisterAgentViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RegisterAgentViewController"}],"url":"\/documentation\/divar\/registeragentviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewContorllerDelegate/didRemoveFocusedRowValue(_:row:)-5f7bz":{"defaultImplementations":1,"role":"symbol","title":"didRemoveFocusedRowValue(_:row:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRemoveFocusedRowValue"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AbstractFormViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractFormViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"row"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseRow","preciseIdentifier":"s:6Eureka7BaseRowC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewContorllerDelegate\/didRemoveFocusedRowValue(_:row:)-5f7bz","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstractformviewcontorllerdelegate\/didremovefocusedrowvalue(_:row:)-5f7bz"},"doc://com.Divar.DivarClient/documentation/Divar/AddStoreManagerViewController":{"role":"symbol","title":"AddStoreManagerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddStoreManagerViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddStoreManagerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddStoreManagerViewController"}],"url":"\/documentation\/divar\/addstoremanagerviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewContorllerDelegate/didStartLoadingData(_:for:)-1vkd":{"defaultImplementations":1,"role":"symbol","title":"didStartLoadingData(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didStartLoadingData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AbstractFormViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractFormViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewContorllerDelegate\/didStartLoadingData(_:for:)-1vkd","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstractformviewcontorllerdelegate\/didstartloadingdata(_:for:)-1vkd"},"doc://com.Divar.DivarClient/documentation/Divar/RealEstateSubmitViewController":{"role":"symbol","title":"RealEstateSubmitViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RealEstateSubmitViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateSubmitViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RealEstateSubmitViewController"}],"url":"\/documentation\/divar\/realestatesubmitviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/RegisterDealerViewController":{"role":"symbol","title":"RegisterDealerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RegisterDealerViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RegisterDealerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RegisterDealerViewController"}],"url":"\/documentation\/divar\/registerdealerviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarInspectionSubmitViewController":{"role":"symbol","title":"CarInspectionSubmitViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarInspectionSubmitViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarInspectionSubmitViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarInspectionSubmitViewController"}],"url":"\/documentation\/divar\/carinspectionsubmitviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AddVRViewController":{"role":"symbol","title":"AddVRViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddVRViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddVRViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddVRViewController"}],"url":"\/documentation\/divar\/addvrviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AddUserTransactionFormViewController":{"role":"symbol","title":"AddUserTransactionFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddUserTransactionFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddUserTransactionFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddUserTransactionFormViewController"}],"url":"\/documentation\/divar\/addusertransactionformviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostCreateViewController":{"role":"symbol","title":"PostCreateViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostCreateViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostCreateViewController"}],"url":"\/documentation\/divar\/postcreateviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SearchFilterViewController":{"role":"symbol","title":"SearchFilterViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchFilterViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchFilterViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchFilterViewController"}],"url":"\/documentation\/divar\/searchfilterviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/EditMarketplaceStoreViewController":{"role":"symbol","title":"EditMarketplaceStoreViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EditMarketplaceStoreViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/EditMarketplaceStoreViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EditMarketplaceStoreViewController"}],"url":"\/documentation\/divar\/editmarketplacestoreviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/UsedPriceFormViewController":{"role":"symbol","title":"UsedPriceFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsedPriceFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UsedPriceFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UsedPriceFormViewController"}],"url":"\/documentation\/divar\/usedpriceformviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewContorllerDelegate/actionDelegate":{"role":"symbol","title":"actionDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AbstractFormActionDelegate","preciseIdentifier":"s:5Divar26AbstractFormActionDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewContorllerDelegate\/actionDelegate","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstractformviewcontorllerdelegate\/actiondelegate"},"doc://com.Divar.DivarClient/documentation/Divar/OfflineFormViewController":{"role":"symbol","title":"OfflineFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OfflineFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OfflineFormViewController"}],"url":"\/documentation\/divar\/offlineformviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BusinessSubscriptionViewController":{"role":"symbol","title":"BusinessSubscriptionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BusinessSubscriptionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BusinessSubscriptionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BusinessSubscriptionViewController"}],"url":"\/documentation\/divar\/businesssubscriptionviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarAgentBuyPackageViewController":{"role":"symbol","title":"CarAgentBuyPackageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarAgentBuyPackageViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentBuyPackageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarAgentBuyPackageViewController"}],"url":"\/documentation\/divar\/caragentbuypackageviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarInspectionRegisterViewController":{"role":"symbol","title":"CarInspectionRegisterViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarInspectionRegisterViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarInspectionRegisterViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarInspectionRegisterViewController"}],"url":"\/documentation\/divar\/carinspectionregisterviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CreateAndEditOperatorViewController":{"role":"symbol","title":"CreateAndEditOperatorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateAndEditOperatorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CreateAndEditOperatorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CreateAndEditOperatorViewController"}],"url":"\/documentation\/divar\/createandeditoperatorviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MarketplaceSubmitViewController":{"role":"symbol","title":"MarketplaceSubmitViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketplaceSubmitViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceSubmitViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketplaceSubmitViewController"}],"url":"\/documentation\/divar\/marketplacesubmitviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ScreenWidgetViewController":{"role":"symbol","title":"ScreenWidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScreenWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScreenWidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScreenWidgetViewController"}],"url":"\/documentation\/divar\/screenwidgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormController":{"role":"symbol","title":"BaseFormController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFormController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseFormController"}],"url":"\/documentation\/divar\/baseformcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MarketplaceSubscriptionViewController":{"role":"symbol","title":"MarketplaceSubscriptionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketplaceSubscriptionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceSubscriptionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketplaceSubscriptionViewController"}],"url":"\/documentation\/divar\/marketplacesubscriptionviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/RealEstateRegistrationViewController":{"role":"symbol","title":"RealEstateRegistrationViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RealEstateRegistrationViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateRegistrationViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RealEstateRegistrationViewController"}],"url":"\/documentation\/divar\/realestateregistrationviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SchemaFormViewController":{"role":"symbol","title":"SchemaFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SchemaFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SchemaFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SchemaFormViewController"}],"url":"\/documentation\/divar\/schemaformviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewContorllerDelegate/formController(_:didRequestChangeSubmitButtonState:)":{"role":"symbol","title":"formController(_:didRequestChangeSubmitButtonState:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"formController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AbstractFormViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractFormViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestChangeSubmitButtonState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewContorllerDelegate\/formController(_:didRequestChangeSubmitButtonState:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstractformviewcontorllerdelegate\/formcontroller(_:didrequestchangesubmitbuttonstate:)"},"doc://com.Divar.DivarClient/documentation/Divar/CarAgentSubmitViewController":{"role":"symbol","title":"CarAgentSubmitViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarAgentSubmitViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentSubmitViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarAgentSubmitViewController"}],"url":"\/documentation\/divar\/caragentsubmitviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewContorllerDelegate/formController(_:didSelect:)-1csjl":{"defaultImplementations":1,"role":"symbol","title":"formController(_:didSelect:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"formController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AbstractFormViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractFormViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseRow","preciseIdentifier":"s:6Eureka7BaseRowC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewContorllerDelegate\/formController(_:didSelect:)-1csjl","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstractformviewcontorllerdelegate\/formcontroller(_:didselect:)-1csjl"},"doc://com.Divar.DivarClient/documentation/Divar/DealerSubmitViewController":{"role":"symbol","title":"DealerSubmitViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DealerSubmitViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubmitViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DealerSubmitViewController"}],"url":"\/documentation\/divar\/dealersubmitviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarAgentBuyLadderPackageViewController":{"role":"symbol","title":"CarAgentBuyLadderPackageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarAgentBuyLadderPackageViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentBuyLadderPackageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarAgentBuyLadderPackageViewController"}],"url":"\/documentation\/divar\/caragentbuyladderpackageviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BooleanRateFormViewController":{"role":"symbol","title":"BooleanRateFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BooleanRateFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BooleanRateFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BooleanRateFormViewController"}],"url":"\/documentation\/divar\/booleanrateformviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/RegisterMarketplaceViewController":{"role":"symbol","title":"RegisterMarketplaceViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RegisterMarketplaceViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RegisterMarketplaceViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RegisterMarketplaceViewController"}],"url":"\/documentation\/divar\/registermarketplaceviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewContorllerDelegate":{"role":"symbol","title":"AbstractFormViewContorllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractFormViewContorllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewContorllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AbstractFormViewContorllerDelegate"}],"url":"\/documentation\/divar\/abstractformviewcontorllerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/MarketplaceQuickEditPostVC":{"role":"symbol","title":"MarketplaceQuickEditPostVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketplaceQuickEditPostVC"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceQuickEditPostVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketplaceQuickEditPostVC"}],"url":"\/documentation\/divar\/marketplacequickeditpostvc"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedFilterViewController":{"role":"symbol","title":"WidgetBasedFilterViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedFilterViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedFilterViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedFilterViewController"}],"url":"\/documentation\/divar\/widgetbasedfilterviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MarketpalceFeedbackViewController":{"role":"symbol","title":"MarketpalceFeedbackViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketpalceFeedbackViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketpalceFeedbackViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketpalceFeedbackViewController"}],"url":"\/documentation\/divar\/marketpalcefeedbackviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AddEditAgentViewController":{"role":"symbol","title":"AddEditAgentViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddEditAgentViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddEditAgentViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddEditAgentViewController"}],"url":"\/documentation\/divar\/addeditagentviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewContorllerDelegate/didStartRefreshingForm(_:currentPage:currentData:previousData:)-4ryqq":{"defaultImplementations":1,"role":"symbol","title":"didStartRefreshingForm(_:currentPage:currentData:previousData:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didStartRefreshingForm"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AbstractFormViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractFormViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currentPage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currentData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"previousData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewContorllerDelegate\/didStartRefreshingForm(_:currentPage:currentData:previousData:)-4ryqq","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstractformviewcontorllerdelegate\/didstartrefreshingform(_:currentpage:currentdata:previousdata:)-4ryqq"},"doc://com.Divar.DivarClient/documentation/Divar/AddSalesmanViewController":{"role":"symbol","title":"AddSalesmanViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddSalesmanViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddSalesmanViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddSalesmanViewController"}],"url":"\/documentation\/divar\/addsalesmanviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewContorllerDelegate/formController(_:didGetLocalValidationErrors:)-63efe":{"defaultImplementations":1,"role":"symbol","title":"formController(_:didGetLocalValidationErrors:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"formController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AbstractFormViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractFormViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didGetLocalValidationErrors"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"BaseRow","preciseIdentifier":"s:6Eureka7BaseRowC"},{"kind":"text","text":" : ["},{"kind":"typeIdentifier","text":"ValidationError","preciseIdentifier":"s:6Eureka15ValidationErrorV"},{"kind":"text","text":"]]?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewContorllerDelegate\/formController(_:didGetLocalValidationErrors:)-63efe","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/abstractformviewcontorllerdelegate\/formcontroller(_:didgetlocalvalidationerrors:)-63efe"},"doc://com.Divar.DivarClient/documentation/Divar/MarketplaceEditAssistantViewController":{"role":"symbol","title":"MarketplaceEditAssistantViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketplaceEditAssistantViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceEditAssistantViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketplaceEditAssistantViewController"}],"url":"\/documentation\/divar\/marketplaceeditassistantviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JobsSubmitViewController\/title","value":"JobsSubmitViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JobsSubmitViewController\/fragments","value":[{"kind":"identifier","text":"JobsSubmitViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SendFeedbackViewController\/title","value":"SendFeedbackViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SendFeedbackViewController\/fragments","value":[{"kind":"identifier","text":"SendFeedbackViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BuyBulkLadderViewController\/title","value":"BuyBulkLadderViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BuyBulkLadderViewController\/fragments","value":[{"kind":"identifier","text":"BuyBulkLadderViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RegisterAgentViewController\/title","value":"RegisterAgentViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RegisterAgentViewController\/fragments","value":[{"kind":"identifier","text":"RegisterAgentViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddStoreManagerViewController\/title","value":"AddStoreManagerViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddStoreManagerViewController\/fragments","value":[{"kind":"identifier","text":"AddStoreManagerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateSubmitViewController\/title","value":"RealEstateSubmitViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateSubmitViewController\/fragments","value":[{"kind":"identifier","text":"RealEstateSubmitViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RegisterDealerViewController\/title","value":"RegisterDealerViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RegisterDealerViewController\/fragments","value":[{"kind":"identifier","text":"RegisterDealerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarInspectionSubmitViewController\/title","value":"CarInspectionSubmitViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarInspectionSubmitViewController\/fragments","value":[{"kind":"identifier","text":"CarInspectionSubmitViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddVRViewController\/title","value":"AddVRViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddVRViewController\/fragments","value":[{"kind":"identifier","text":"AddVRViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddUserTransactionFormViewController\/title","value":"AddUserTransactionFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddUserTransactionFormViewController\/fragments","value":[{"kind":"identifier","text":"AddUserTransactionFormViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostCreateViewController\/title","value":"PostCreateViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostCreateViewController\/fragments","value":[{"kind":"identifier","text":"PostCreateViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchFilterViewController\/title","value":"SearchFilterViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchFilterViewController\/fragments","value":[{"kind":"identifier","text":"SearchFilterViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1EditMarketplaceStoreViewController\/title","value":"EditMarketplaceStoreViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1EditMarketplaceStoreViewController\/fragments","value":[{"kind":"identifier","text":"EditMarketplaceStoreViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1UsedPriceFormViewController\/title","value":"UsedPriceFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1UsedPriceFormViewController\/fragments","value":[{"kind":"identifier","text":"UsedPriceFormViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OfflineFormViewController\/title","value":"OfflineFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OfflineFormViewController\/fragments","value":[{"kind":"identifier","text":"OfflineFormViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BusinessSubscriptionViewController\/title","value":"BusinessSubscriptionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BusinessSubscriptionViewController\/fragments","value":[{"kind":"identifier","text":"BusinessSubscriptionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentBuyPackageViewController\/title","value":"CarAgentBuyPackageViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentBuyPackageViewController\/fragments","value":[{"kind":"identifier","text":"CarAgentBuyPackageViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarInspectionRegisterViewController\/title","value":"CarInspectionRegisterViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarInspectionRegisterViewController\/fragments","value":[{"kind":"identifier","text":"CarInspectionRegisterViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CreateAndEditOperatorViewController\/title","value":"CreateAndEditOperatorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CreateAndEditOperatorViewController\/fragments","value":[{"kind":"identifier","text":"CreateAndEditOperatorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceSubmitViewController\/title","value":"MarketplaceSubmitViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceSubmitViewController\/fragments","value":[{"kind":"identifier","text":"MarketplaceSubmitViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScreenWidgetViewController\/title","value":"ScreenWidgetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScreenWidgetViewController\/fragments","value":[{"kind":"identifier","text":"ScreenWidgetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFormController\/title","value":"BaseFormController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFormController\/fragments","value":[{"kind":"identifier","text":"BaseFormController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceSubscriptionViewController\/title","value":"MarketplaceSubscriptionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceSubscriptionViewController\/fragments","value":[{"kind":"identifier","text":"MarketplaceSubscriptionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateRegistrationViewController\/title","value":"RealEstateRegistrationViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateRegistrationViewController\/fragments","value":[{"kind":"identifier","text":"RealEstateRegistrationViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SchemaFormViewController\/title","value":"SchemaFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SchemaFormViewController\/fragments","value":[{"kind":"identifier","text":"SchemaFormViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentSubmitViewController\/title","value":"CarAgentSubmitViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentSubmitViewController\/fragments","value":[{"kind":"identifier","text":"CarAgentSubmitViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubmitViewController\/title","value":"DealerSubmitViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubmitViewController\/fragments","value":[{"kind":"identifier","text":"DealerSubmitViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentBuyLadderPackageViewController\/title","value":"CarAgentBuyLadderPackageViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentBuyLadderPackageViewController\/fragments","value":[{"kind":"identifier","text":"CarAgentBuyLadderPackageViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BooleanRateFormViewController\/title","value":"BooleanRateFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BooleanRateFormViewController\/fragments","value":[{"kind":"identifier","text":"BooleanRateFormViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RegisterMarketplaceViewController\/title","value":"RegisterMarketplaceViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RegisterMarketplaceViewController\/fragments","value":[{"kind":"identifier","text":"RegisterMarketplaceViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceQuickEditPostVC\/title","value":"MarketplaceQuickEditPostVC"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceQuickEditPostVC\/fragments","value":[{"kind":"identifier","text":"MarketplaceQuickEditPostVC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedFilterViewController\/title","value":"WidgetBasedFilterViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedFilterViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedFilterViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketpalceFeedbackViewController\/title","value":"MarketpalceFeedbackViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketpalceFeedbackViewController\/fragments","value":[{"kind":"identifier","text":"MarketpalceFeedbackViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddEditAgentViewController\/title","value":"AddEditAgentViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddEditAgentViewController\/fragments","value":[{"kind":"identifier","text":"AddEditAgentViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddSalesmanViewController\/title","value":"AddSalesmanViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddSalesmanViewController\/fragments","value":[{"kind":"identifier","text":"AddSalesmanViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceEditAssistantViewController\/title","value":"MarketplaceEditAssistantViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceEditAssistantViewController\/fragments","value":[{"kind":"identifier","text":"MarketplaceEditAssistantViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}