{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdvancedWidgetViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/advancedwidgetviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/advancedwidgetviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandscapeWidgetViewController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ClaimPostProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ComponentProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterableWidgetBased","doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LoginRequiredProtocol","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RefreshableProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Returnable","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Searchable","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","doc:\/\/com.Divar.DivarClient\/6Sonnat17SearchBoxDelegateP","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SplitButtonBarViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UIScrollViewDirectionDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UserRegisterFlowControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WideButtonViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBaseCollectionPerformanceLogDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedNavigationBarPresenterProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewControllerProtocol"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/init(viewModel:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/identifier","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/isEmbeded","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/isSearchActive","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/navigationBarItems","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/performanceMonitor","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/searchBox","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/shouldReloadOnAppear","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/stackHolder"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/handle(error:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/setupStackHolder()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/update(emptyStateMessage:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/update(searchBox:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/update(stickyWidgets:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/update(tagList:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/update(title:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/update(viewState:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/update(widgetList:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/viewDidLoad()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/viewWillAppear(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/widgetBasedCollectionViewController(_:canStartInfiniteScroll:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/widgetBasedCollectionViewController(_:didStartInfiniteScroll:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/widgetBasedCollectionViewController(_:didStartPullToRefresh:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/widgetViewChildFinish(event:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/widgetViewChildStarted(event:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/widgetViewEventFinished(event:reason:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/widgetViewEventStarted(event:eventPayload:customData:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/FilterableWidgetBased-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/SearchBoxDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/TagListViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/UIScrollViewDirectionDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/WidgetBaseCollectionPerformanceLogDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/WidgetBasedNavigationBarPresenterProtocol-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdvancedWidgetViewController"}],"title":"AdvancedWidgetViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)AdvancedWidgetViewController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"AdvancedWidgetViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/handle(error:)":{"role":"symbol","title":"handle(error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DError","preciseIdentifier":"s:5Divar6DErrorV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/handle(error:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/handle(error:)"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/stackHolder":{"role":"symbol","title":"stackHolder","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stackHolder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/stackHolder","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/stackholder"},"doc://com.Divar.DivarClient/documentation/Divar/Searchable":{"role":"symbol","title":"Searchable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Searchable"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Searchable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Searchable"}],"url":"\/documentation\/divar\/searchable"},"doc://com.Divar.DivarClient/documentation/Divar/ShowMessageProtocol":{"role":"symbol","title":"ShowMessageProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowMessageProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowMessageProtocol"}],"url":"\/documentation\/divar\/showmessageprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewControllerDelegate":{"role":"symbol","title":"TwinButtonsViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TwinButtonsViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TwinButtonsViewControllerDelegate"}],"url":"\/documentation\/divar\/twinbuttonsviewcontrollerdelegate"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedNavigationBarPresenterProtocol":{"role":"symbol","title":"WidgetBasedNavigationBarPresenterProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedNavigationBarPresenterProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedNavigationBarPresenterProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedNavigationBarPresenterProtocol"}],"url":"\/documentation\/divar\/widgetbasednavigationbarpresenterprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/ClaimPostProtocol":{"role":"symbol","title":"ClaimPostProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClaimPostProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ClaimPostProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClaimPostProtocol"}],"url":"\/documentation\/divar\/claimpostprotocol"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/PaymentSystemProtocol":{"role":"symbol","title":"PaymentSystemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSystemProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaymentSystemProtocol"}],"url":"\/documentation\/divar\/paymentsystemprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/SearchBoxDelegate-Implementations":{"role":"collectionGroup","title":"SearchBoxDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/SearchBoxDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/searchboxdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewControllerDelegate":{"role":"symbol","title":"WidgetBasedCollectionViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedCollectionViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedCollectionViewControllerDelegate"}],"url":"\/documentation\/divar\/widgetbasedcollectionviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/isSearchActive":{"role":"symbol","title":"isSearchActive","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSearchActive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/isSearchActive","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/issearchactive"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBaseCollectionPerformanceLogDelegate":{"role":"symbol","title":"WidgetBaseCollectionPerformanceLogDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBaseCollectionPerformanceLogDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBaseCollectionPerformanceLogDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBaseCollectionPerformanceLogDelegate"}],"url":"\/documentation\/divar\/widgetbasecollectionperformancelogdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/ErrorMessageHandler":{"role":"symbol","title":"ErrorMessageHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorMessageHandler"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorMessageHandler"}],"url":"\/documentation\/divar\/errormessagehandler"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController":{"role":"symbol","title":"AdvancedWidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdvancedWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdvancedWidgetViewController"}],"url":"\/documentation\/divar\/advancedwidgetviewcontroller"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/UIScrollViewDirectionDelegate-Implementations":{"role":"collectionGroup","title":"UIScrollViewDirectionDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/UIScrollViewDirectionDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/uiscrollviewdirectiondelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewControllerProtocol":{"role":"symbol","title":"WidgetBasedViewControllerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedViewControllerProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewControllerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedViewControllerProtocol"}],"url":"\/documentation\/divar\/widgetbasedviewcontrollerprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/init(viewModel:)":{"role":"symbol","title":"init(viewModel:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"viewModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WidgetViewModelProtocol","preciseIdentifier":"s:5Divar23WidgetViewModelProtocolP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/init(viewModel:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/init(viewmodel:)"},"doc://com.Divar.DivarClient/documentation/Divar/UserRegisterFlowControllerDelegate":{"role":"symbol","title":"UserRegisterFlowControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserRegisterFlowControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UserRegisterFlowControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserRegisterFlowControllerDelegate"}],"url":"\/documentation\/divar\/userregisterflowcontrollerdelegate"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/WidgetBaseCollectionPerformanceLogDelegate-Implementations":{"role":"collectionGroup","title":"WidgetBaseCollectionPerformanceLogDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/WidgetBaseCollectionPerformanceLogDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/widgetbasecollectionperformancelogdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/TagListViewControllerDelegate":{"role":"symbol","title":"TagListViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagListViewControllerDelegate"}],"url":"\/documentation\/divar\/taglistviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/update(emptyStateMessage:)":{"role":"symbol","title":"update(emptyStateMessage:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"externalParam","text":"emptyStateMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/update(emptyStateMessage:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/update(emptystatemessage:)"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/widgetViewChildStarted(event:)":{"role":"symbol","title":"widgetViewChildStarted(event:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetViewChildStarted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WidgetViewControllerPerformaceHelper","preciseIdentifier":"s:5Divar36WidgetViewControllerPerformaceHelperV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"WidgetViewControllerChildEvents","preciseIdentifier":"s:5Divar36WidgetViewControllerPerformaceHelperV0bcD11ChildEventsO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/widgetViewChildStarted(event:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/widgetviewchildstarted(event:)"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/isEmbeded":{"role":"symbol","title":"isEmbeded","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEmbeded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/isEmbeded","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/isembeded"},"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/update(widgetList:)":{"role":"symbol","title":"update(widgetList:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"externalParam","text":"widgetList"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WidgetList","preciseIdentifier":"s:5Divar10WidgetListO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/update(widgetList:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/update(widgetlist:)"},"doc://com.Divar.DivarClient/documentation/Divar/SplitButtonBarViewControllerDelegate":{"role":"symbol","title":"SplitButtonBarViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SplitButtonBarViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SplitButtonBarViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SplitButtonBarViewControllerDelegate"}],"url":"\/documentation\/divar\/splitbuttonbarviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/update(stickyWidgets:)":{"role":"symbol","title":"update(stickyWidgets:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"externalParam","text":"stickyWidgets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StickyWidgetActionWrapper","preciseIdentifier":"s:5Divar25StickyWidgetActionWrapperV"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/update(stickyWidgets:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/update(stickywidgets:)"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/searchBox":{"role":"symbol","title":"searchBox","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBox"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchBox","preciseIdentifier":"c:@M@Sonnat@objc(cs)SearchBox"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/searchBox","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/searchbox"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController":{"role":"symbol","title":"WidgetBasedViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedViewController"}],"url":"\/documentation\/divar\/widgetbasedviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/viewWillAppear(_:)":{"role":"symbol","title":"viewWillAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/viewWillAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"url":"\/documentation\/divar\/advancedwidgetviewcontroller\/viewwillappear(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/update(tagList:)":{"role":"symbol","title":"update(tagList:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tagList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"TagListItem","preciseIdentifier":"s:5Divar11TagListItemP"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/update(tagList:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/update(taglist:)"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/documentation/Divar/LandscapeWidgetViewController":{"role":"symbol","title":"LandscapeWidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandscapeWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandscapeWidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandscapeWidgetViewController"}],"url":"\/documentation\/divar\/landscapewidgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/update(searchBox:)":{"role":"symbol","title":"update(searchBox:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"externalParam","text":"searchBox"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchBoxViewModel","preciseIdentifier":"s:5Divar18SearchBoxViewModelV"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/update(searchBox:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/update(searchbox:)"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/shouldReloadOnAppear":{"role":"symbol","title":"shouldReloadOnAppear","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldReloadOnAppear"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/shouldReloadOnAppear","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/shouldreloadonappear"},"doc://com.Divar.DivarClient/documentation/Divar/LoginRequiredProtocol":{"role":"symbol","title":"LoginRequiredProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoginRequiredProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LoginRequiredProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LoginRequiredProtocol"}],"url":"\/documentation\/divar\/loginrequiredprotocol"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/navigationBarItems":{"role":"symbol","title":"navigationBarItems","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationBarItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Widgets_NavigationBar","preciseIdentifier":"s:19DivarInterfaceSwift21Widgets_NavigationBarV"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/navigationBarItems","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/navigationbaritems"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/advancedwidgetviewcontroller\/init(coder:)"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/widgetBasedCollectionViewController(_:canStartInfiniteScroll:)":{"role":"symbol","title":"widgetBasedCollectionViewController(_:canStartInfiniteScroll:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"canStartInfiniteScroll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdvancedCollectionView","preciseIdentifier":"c:@M@Divar@objc(cs)AdvancedCollectionView"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/widgetBasedCollectionViewController(_:canStartInfiniteScroll:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/widgetbasedcollectionviewcontroller(_:canstartinfinitescroll:)"},"doc://com.Divar.DivarClient/documentation/Divar/FilterableWidgetBased":{"role":"symbol","title":"FilterableWidgetBased","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FilterableWidgetBased"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterableWidgetBased","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FilterableWidgetBased"}],"url":"\/documentation\/divar\/filterablewidgetbased"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/widgetViewEventStarted(event:eventPayload:customData:)":{"role":"symbol","title":"widgetViewEventStarted(event:eventPayload:customData:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetViewEventStarted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"eventPayload"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"customData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/widgetViewEventStarted(event:eventPayload:customData:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/widgetvieweventstarted(event:eventpayload:customdata:)"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/TagListViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"TagListViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/TagListViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/taglistviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/widgetBasedCollectionViewController(_:didStartInfiniteScroll:)":{"role":"symbol","title":"widgetBasedCollectionViewController(_:didStartInfiniteScroll:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartInfiniteScroll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdvancedCollectionView","preciseIdentifier":"c:@M@Divar@objc(cs)AdvancedCollectionView"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/widgetBasedCollectionViewController(_:didStartInfiniteScroll:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/widgetbasedcollectionviewcontroller(_:didstartinfinitescroll:)"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/advancedwidgetviewcontroller\/viewdidload()"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/ComponentProtocol":{"role":"symbol","title":"ComponentProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComponentProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ComponentProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ComponentProtocol"}],"url":"\/documentation\/divar\/componentprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/RefreshableProtocol":{"role":"symbol","title":"RefreshableProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RefreshableProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RefreshableProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RefreshableProtocol"}],"url":"\/documentation\/divar\/refreshableprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/WidgetBasedNavigationBarPresenterProtocol-Implementations":{"role":"collectionGroup","title":"WidgetBasedNavigationBarPresenterProtocol Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/WidgetBasedNavigationBarPresenterProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/widgetbasednavigationbarpresenterprotocol-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/FilterableWidgetBased-Implementations":{"role":"collectionGroup","title":"FilterableWidgetBased Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/FilterableWidgetBased-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/filterablewidgetbased-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/setupStackHolder()":{"role":"symbol","title":"setupStackHolder()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupStackHolder"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/setupStackHolder()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/setupstackholder()"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/Returnable":{"role":"symbol","title":"Returnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Returnable"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Returnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Returnable"}],"url":"\/documentation\/divar\/returnable"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/documentation/Divar/UIScrollViewDirectionDelegate":{"role":"symbol","title":"UIScrollViewDirectionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIScrollViewDirectionDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UIScrollViewDirectionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIScrollViewDirectionDelegate"}],"url":"\/documentation\/divar\/uiscrollviewdirectiondelegate"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/identifier":{"role":"symbol","title":"identifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PageIdentifier","preciseIdentifier":"s:5Divar14PageIdentifierO"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/identifier","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/identifier"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/widgetViewChildFinish(event:)":{"role":"symbol","title":"widgetViewChildFinish(event:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetViewChildFinish"},{"kind":"text","text":"("},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WidgetViewControllerPerformaceHelper","preciseIdentifier":"s:5Divar36WidgetViewControllerPerformaceHelperV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"WidgetViewControllerChildEvents","preciseIdentifier":"s:5Divar36WidgetViewControllerPerformaceHelperV0bcD11ChildEventsO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/widgetViewChildFinish(event:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/widgetviewchildfinish(event:)"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/performanceMonitor":{"role":"symbol","title":"performanceMonitor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"performanceMonitor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PerformanceMonitorProtocol","preciseIdentifier":"s:5Divar26PerformanceMonitorProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/performanceMonitor","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/performancemonitor"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/widgetViewEventFinished(event:reason:)":{"role":"symbol","title":"widgetViewEventFinished(event:reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetViewEventFinished"},{"kind":"text","text":"("},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PerformaceEventFinishReason","preciseIdentifier":"s:5Divar27PerformaceEventFinishReasonO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/widgetViewEventFinished(event:reason:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/widgetvieweventfinished(event:reason:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/update(title:)":{"role":"symbol","title":"update(title:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/update(title:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/update(title:)"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/update(viewState:)":{"role":"symbol","title":"update(viewState:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"externalParam","text":"viewState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WidgetViewState","preciseIdentifier":"s:5Divar15WidgetViewStateO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/update(viewState:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/update(viewstate:)"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/documentation/Divar/TooltipPresenter":{"role":"symbol","title":"TooltipPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TooltipPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TooltipPresenter"}],"url":"\/documentation\/divar\/tooltippresenter"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/documentation/Divar/WideButtonViewControllerDelegate":{"role":"symbol","title":"WideButtonViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WideButtonViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WideButtonViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WideButtonViewControllerDelegate"}],"url":"\/documentation\/divar\/widebuttonviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/ShowErrorProtocol":{"role":"symbol","title":"ShowErrorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowErrorProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowErrorProtocol"}],"url":"\/documentation\/divar\/showerrorprotocol"},"doc://com.Divar.DivarClient/6Sonnat17SearchBoxDelegateP":{"type":"unresolvable","title":"Sonnat.SearchBoxDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat17SearchBoxDelegateP"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/widgetBasedCollectionViewController(_:didStartPullToRefresh:)":{"role":"symbol","title":"widgetBasedCollectionViewController(_:didStartPullToRefresh:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartPullToRefresh"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/widgetBasedCollectionViewController(_:didStartPullToRefresh:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/widgetbasedcollectionviewcontroller(_:didstartpulltorefresh:)"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AdvancedWidgetViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AdvancedWidgetViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AdvancedWidgetViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/viewDidLoad()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/viewWillAppear(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandscapeWidgetViewController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdvancedWidgetViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedViewController","text":"WidgetBasedViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController\/title","value":"AdvancedWidgetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController\/fragments","value":[{"kind":"identifier","text":"AdvancedWidgetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedViewController\/title","value":"WidgetBasedViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandscapeWidgetViewController\/title","value":"LandscapeWidgetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandscapeWidgetViewController\/fragments","value":[{"kind":"identifier","text":"LandscapeWidgetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}