{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/appdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/appdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIResponder"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIApplicationDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UNUserNotificationCenterDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/configurations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/container","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/enterBackgroundTimer","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/launchOptions","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/mainFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/qaConfigs","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/socketConnectivityLogger","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/window"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/addRoutes()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:didChangeStatusBarFrame:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:didFinishLaunchingWithOptions:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:supportedInterfaceOrientationsFor:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/applicationDidBecomeActive(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/applicationDidEnterBackground(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/applicationWillEnterForeground(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/applicationWillResignActive(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/defineCarBrandModel()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/defineCarSpecs()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/initMainFlowController()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/logNotification(payload:state:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/setupForegroundNotification()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/startObserveSocketSession()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/validateLogin(phoneNumber:completion:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/UIApplicationDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/UNUserNotificationCenterDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppDelegate"}],"title":"AppDelegate","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)AppDelegate","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"AppDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/launchOptions":{"role":"symbol","title":"launchOptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"launchOptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"LaunchOptionsKey","preciseIdentifier":"c:@T@UIApplicationLaunchOptionsKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/launchOptions","kind":"symbol","type":"topic","url":"\/documentation\/divar\/appdelegate\/launchoptions"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/application(_:didChangeStatusBarFrame:)":{"role":"symbol","title":"application(_:didChangeStatusBarFrame:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeStatusBarFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:didChangeStatusBarFrame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"application:didChangeStatusBarFrame:"}],"url":"\/documentation\/divar\/appdelegate\/application(_:didchangestatusbarframe:)"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/applicationWillEnterForeground(_:)":{"role":"symbol","title":"applicationWillEnterForeground(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationWillEnterForeground"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/applicationWillEnterForeground(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applicationWillEnterForeground:"}],"url":"\/documentation\/divar\/appdelegate\/applicationwillenterforeground(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/defineCarBrandModel()":{"role":"symbol","title":"defineCarBrandModel()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"defineCarBrandModel"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/defineCarBrandModel()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/appdelegate\/definecarbrandmodel()"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/applicationWillResignActive(_:)":{"role":"symbol","title":"applicationWillResignActive(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationWillResignActive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/applicationWillResignActive(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applicationWillResignActive:"}],"url":"\/documentation\/divar\/appdelegate\/applicationwillresignactive(_:)"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate":{"role":"symbol","title":"AppDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppDelegate"}],"url":"\/documentation\/divar\/appdelegate"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/configurations":{"role":"symbol","title":"configurations","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurations"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AppConfigurations","preciseIdentifier":"s:5Divar17AppConfigurationsa"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/configurations","kind":"symbol","type":"topic","url":"\/documentation\/divar\/appdelegate\/configurations"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/divar\/appdelegate\/init"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/socketConnectivityLogger":{"role":"symbol","title":"socketConnectivityLogger","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"socketConnectivityLogger"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SocketConnectivityLogHelper","preciseIdentifier":"s:5Divar27SocketConnectivityLogHelperC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/socketConnectivityLogger","kind":"symbol","type":"topic","url":"\/documentation\/divar\/appdelegate\/socketconnectivitylogger"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/applicationDidBecomeActive(_:)":{"role":"symbol","title":"applicationDidBecomeActive(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationDidBecomeActive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/applicationDidBecomeActive(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applicationDidBecomeActive:"}],"url":"\/documentation\/divar\/appdelegate\/applicationdidbecomeactive(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/mainFlowController":{"role":"symbol","title":"mainFlowController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mainFlowController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MainFlowController","preciseIdentifier":"c:@M@Divar@objc(cs)MainFlowController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/mainFlowController","kind":"symbol","type":"topic","url":"\/documentation\/divar\/appdelegate\/mainflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/validateLogin(phoneNumber:completion:)":{"role":"symbol","title":"validateLogin(phoneNumber:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validateLogin"},{"kind":"text","text":"("},{"kind":"externalParam","text":"phoneNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/validateLogin(phoneNumber:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/appdelegate\/validatelogin(phonenumber:completion:)"},"doc://com.Divar.DivarClient/objc(pl)UNUserNotificationCenterDelegate":{"type":"unresolvable","title":"UserNotifications.UNUserNotificationCenterDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UNUserNotificationCenterDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/UIApplicationDelegate-Implementations":{"role":"collectionGroup","title":"UIApplicationDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/UIApplicationDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/appdelegate\/uiapplicationdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/container":{"role":"symbol","title":"container","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DIContainer","preciseIdentifier":"s:5Divar11DIContainerC"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/container","kind":"symbol","type":"topic","url":"\/documentation\/divar\/appdelegate\/container"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/startObserveSocketSession()":{"role":"symbol","title":"startObserveSocketSession()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startObserveSocketSession"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/startObserveSocketSession()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/appdelegate\/startobservesocketsession()"},"doc://com.Divar.DivarClient/objc(cs)UIResponder":{"type":"unresolvable","title":"UIResponder","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)UIResponder"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/addRoutes()":{"role":"symbol","title":"addRoutes()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addRoutes"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/addRoutes()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/appdelegate\/addroutes()"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/setupForegroundNotification()":{"role":"symbol","title":"setupForegroundNotification()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupForegroundNotification"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/setupForegroundNotification()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/appdelegate\/setupforegroundnotification()"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/application(_:didFinishLaunchingWithOptions:)":{"role":"symbol","title":"application(_:didFinishLaunchingWithOptions:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishLaunchingWithOptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"LaunchOptionsKey","preciseIdentifier":"c:@T@UIApplicationLaunchOptionsKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:didFinishLaunchingWithOptions:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"application:didFinishLaunchingWithOptions:"}],"url":"\/documentation\/divar\/appdelegate\/application(_:didfinishlaunchingwithoptions:)"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/UNUserNotificationCenterDelegate-Implementations":{"role":"collectionGroup","title":"UNUserNotificationCenterDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/UNUserNotificationCenterDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/appdelegate\/unusernotificationcenterdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/qaConfigs":{"role":"symbol","title":"qaConfigs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"qaConfigs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"QAConfigurations","preciseIdentifier":"s:5Divar16QAConfigurationsa"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/qaConfigs","kind":"symbol","type":"topic","url":"\/documentation\/divar\/appdelegate\/qaconfigs"},"doc://com.Divar.DivarClient/objc(pl)UIApplicationDelegate":{"type":"unresolvable","title":"UIApplicationDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIApplicationDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/defineCarSpecs()":{"role":"symbol","title":"defineCarSpecs()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"defineCarSpecs"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/defineCarSpecs()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/appdelegate\/definecarspecs()"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/initMainFlowController()":{"role":"symbol","title":"initMainFlowController()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initMainFlowController"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/initMainFlowController()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/appdelegate\/initmainflowcontroller()"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/logNotification(payload:state:)":{"role":"symbol","title":"logNotification(payload:state:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logNotification"},{"kind":"text","text":"("},{"kind":"externalParam","text":"payload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UniversalNotificationPayload","preciseIdentifier":"s:5Divar28UniversalNotificationPayloadV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIApplicationState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/logNotification(payload:state:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/appdelegate\/lognotification(payload:state:)"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/application(_:supportedInterfaceOrientationsFor:)":{"role":"symbol","title":"application(_:supportedInterfaceOrientationsFor:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"supportedInterfaceOrientationsFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIInterfaceOrientationMask","preciseIdentifier":"c:@E@UIInterfaceOrientationMask"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:supportedInterfaceOrientationsFor:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"application:supportedInterfaceOrientationsForWindow:"}],"url":"\/documentation\/divar\/appdelegate\/application(_:supportedinterfaceorientationsfor:)"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/window":{"role":"symbol","title":"window","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"window"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/window","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"window"}],"url":"\/documentation\/divar\/appdelegate\/window"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/applicationDidEnterBackground(_:)":{"role":"symbol","title":"applicationDidEnterBackground(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationDidEnterBackground"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/applicationDidEnterBackground(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applicationDidEnterBackground:"}],"url":"\/documentation\/divar\/appdelegate\/applicationdidenterbackground(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/AppDelegate/enterBackgroundTimer":{"role":"symbol","title":"enterBackgroundTimer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enterBackgroundTimer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/enterBackgroundTimer","kind":"symbol","type":"topic","url":"\/documentation\/divar\/appdelegate\/enterbackgroundtimer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AppDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AppDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AppDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/window"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:didChangeStatusBarFrame:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:didFinishLaunchingWithOptions:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/application(_:supportedInterfaceOrientationsFor:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/applicationDidBecomeActive(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/applicationDidEnterBackground(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/applicationWillEnterForeground(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/applicationWillResignActive(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/init"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/UIApplicationDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppDelegate\/UNUserNotificationCenterDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIResponder"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)UIApplicationDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIResponder","preciseIdentifier":"c:objc(cs)UIResponder"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1application(_:didChangeStatusBarFrame:)\/title","value":"application:didChangeStatusBarFrame:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1application(_:didChangeStatusBarFrame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:didChangeStatusBarFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1applicationWillEnterForeground(_:)\/title","value":"applicationWillEnterForeground:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1applicationWillEnterForeground(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationWillEnterForeground:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1applicationWillResignActive(_:)\/title","value":"applicationWillResignActive:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1applicationWillResignActive(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationWillResignActive:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate\/title","value":"AppDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate\/fragments","value":[{"kind":"identifier","text":"AppDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1applicationDidBecomeActive(_:)\/title","value":"applicationDidBecomeActive:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1applicationDidBecomeActive(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationDidBecomeActive:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1application(_:didFinishLaunchingWithOptions:)\/title","value":"application:didFinishLaunchingWithOptions:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1application(_:didFinishLaunchingWithOptions:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:didFinishLaunchingWithOptions:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1application(_:supportedInterfaceOrientationsFor:)\/title","value":"application:supportedInterfaceOrientationsForWindow:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1application(_:supportedInterfaceOrientationsFor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:supportedInterfaceOrientationsForWindow:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1window\/title","value":"window"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1window\/fragments","value":[{"kind":"identifier","text":"window"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1applicationDidEnterBackground(_:)\/title","value":"applicationDidEnterBackground:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AppDelegate~1applicationDidEnterBackground(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationDidEnterBackground:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}