{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioPlayManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/audioplaymanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/audioplaymanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)AVAudioPlayerDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/init()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/init(service:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/delegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/service"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/destroyPlayer()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/playMp3Sound(url:needsRepeat:playsOnSpeaker:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/playWavSound(url:needsRepeat:playsOnSpeaker:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/startPlaying(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/stopPlayer()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/AVAudioPlayerDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioPlayManager"}],"title":"AudioPlayManager","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)AudioPlayManager","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"AudioPlayManager"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/AudioPlayManager":{"role":"symbol","title":"AudioPlayManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioPlayManager"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AudioPlayManager"}],"url":"\/documentation\/divar\/audioplaymanager"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/AudioPlayManager/playMp3Sound(url:needsRepeat:playsOnSpeaker:)":{"role":"symbol","title":"playMp3Sound(url:needsRepeat:playsOnSpeaker:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playMp3Sound"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"needsRepeat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"playsOnSpeaker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/playMp3Sound(url:needsRepeat:playsOnSpeaker:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/audioplaymanager\/playmp3sound(url:needsrepeat:playsonspeaker:)"},"doc://com.Divar.DivarClient/documentation/Divar/AudioPlayManager/init(service:)":{"role":"symbol","title":"init(service:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"service"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatServiceProtocol","preciseIdentifier":"s:5Divar19ChatServiceProtocolP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/init(service:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/audioplaymanager\/init(service:)"},"doc://com.Divar.DivarClient/documentation/Divar/AudioPlayManager/service":{"role":"symbol","title":"service","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"service"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatServiceProtocol","preciseIdentifier":"s:5Divar19ChatServiceProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/service","kind":"symbol","type":"topic","url":"\/documentation\/divar\/audioplaymanager\/service"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/AudioPlayManager/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/divar\/audioplaymanager\/init()"},"doc://com.Divar.DivarClient/documentation/Divar/AudioPlayManager/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlayAudioDelegate","preciseIdentifier":"s:5Divar17PlayAudioDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/audioplaymanager\/delegate"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/AudioPlayManager/destroyPlayer()":{"role":"symbol","title":"destroyPlayer()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"destroyPlayer"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/destroyPlayer()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/audioplaymanager\/destroyplayer()"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/AudioPlayManager/stopPlayer()":{"role":"symbol","title":"stopPlayer()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopPlayer"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/stopPlayer()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/audioplaymanager\/stopplayer()"},"doc://com.Divar.DivarClient/documentation/Divar/AudioPlayManager/startPlaying(_:)":{"role":"symbol","title":"startPlaying(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startPlaying"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatFileMessageStructure","preciseIdentifier":"s:5Divar24ChatFileMessageStructureV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/startPlaying(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/audioplaymanager\/startplaying(_:)"},"doc://com.Divar.DivarClient/objc(pl)AVAudioPlayerDelegate":{"type":"unresolvable","title":"AVFAudio.AVAudioPlayerDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)AVAudioPlayerDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/AudioPlayManager/AVAudioPlayerDelegate-Implementations":{"role":"collectionGroup","title":"AVAudioPlayerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/AVAudioPlayerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/audioplaymanager\/avaudioplayerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/AudioPlayManager/playWavSound(url:needsRepeat:playsOnSpeaker:)":{"role":"symbol","title":"playWavSound(url:needsRepeat:playsOnSpeaker:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playWavSound"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"needsRepeat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"playsOnSpeaker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/playWavSound(url:needsRepeat:playsOnSpeaker:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/audioplaymanager\/playwavsound(url:needsrepeat:playsonspeaker:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AudioPlayManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AudioPlayManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AudioPlayManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/init()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioPlayManager\/AVAudioPlayerDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioPlayManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AudioPlayManager\/title","value":"AudioPlayManager"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AudioPlayManager\/fragments","value":[{"kind":"identifier","text":"AudioPlayManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AudioPlayManager~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AudioPlayManager~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}