{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/baseviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/baseviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakSandBoxViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ArchiveNoteViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseSegmentedViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BeforeRegisterTermsAndConditionsVC","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BrandMultiHierarchyViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BulkLadderViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatInstructLoginViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatSettingsController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CityMultiSelectViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CitySelectViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConversationsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionDetailsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisableListViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FirstTimeViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ForceUpdateViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ForwardViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GeneralBulkLadderViewControllerProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GetContactViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVCollectionAssetSelectorViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVCollectionSelectorViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVVideoRecorderViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelection","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LimitedLocationSelectorViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationSelectorViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDistrictSelectorViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapSelectorViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MultiConversationDeleteViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyPostsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NickNameViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NotesViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberInputViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberTextFieldDialogWidgetController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberTextFieldPageController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostFeedBackViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostGetContactsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostPaymentHistoryViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostReportDescriptionViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QATableViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateLocationSelectorViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RecentVisitsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchAndSelectStringViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SelectablePostsListViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SelectorWithSearchBarViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SettingsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleMultiBaseViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleMultiEurekaViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ValidatorRowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewControllerProtocol"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/init()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/init(withNib:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/canBecomeFirstResponder","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/orderId","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/shouldShowCloseButton","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/swiftMessageError","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/swiftMessageLoading","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/swiftMessageToast"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/showCancelButton()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/viewDidDisappear(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/viewDidLoad()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/viewWillAppear(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/TooltipPresenter-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseViewController"}],"title":"BaseViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)BaseViewController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"BaseViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ShowErrorProtocol":{"role":"symbol","title":"ShowErrorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowErrorProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowErrorProtocol"}],"url":"\/documentation\/divar\/showerrorprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController":{"role":"symbol","title":"InputAreaViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InputAreaViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InputAreaViewController"}],"url":"\/documentation\/divar\/inputareaviewcontroller"},"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController/swiftMessageToast":{"role":"symbol","title":"swiftMessageToast","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"swiftMessageToast"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SwiftMessages","preciseIdentifier":"s:13SwiftMessagesAAC"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/swiftMessageToast","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseviewcontroller\/swiftmessagetoast"},"doc://com.Divar.DivarClient/documentation/Divar/MultiConversationDeleteViewController":{"role":"symbol","title":"MultiConversationDeleteViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiConversationDeleteViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MultiConversationDeleteViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MultiConversationDeleteViewController"}],"url":"\/documentation\/divar\/multiconversationdeleteviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController":{"role":"symbol","title":"ChatViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatViewController"}],"url":"\/documentation\/divar\/chatviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarksViewController":{"role":"symbol","title":"BookmarksViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BookmarksViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BookmarksViewController"}],"url":"\/documentation\/divar\/bookmarksviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/documentation/Divar/NoteWithBottomBarViewController":{"role":"symbol","title":"NoteWithBottomBarViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NoteWithBottomBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NoteWithBottomBarViewController"}],"url":"\/documentation\/divar\/notewithbottombarviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/divar\/baseviewcontroller\/init()"},"doc://com.Divar.DivarClient/documentation/Divar/MapDistrictSelectorViewController":{"role":"symbol","title":"MapDistrictSelectorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapDistrictSelectorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDistrictSelectorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapDistrictSelectorViewController"}],"url":"\/documentation\/divar\/mapdistrictselectorviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController":{"role":"symbol","title":"MessagingViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagingViewController"}],"url":"\/documentation\/divar\/messagingviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController/showCancelButton()":{"role":"symbol","title":"showCancelButton()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showCancelButton"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/showCancelButton()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseviewcontroller\/showcancelbutton()"},"doc://com.Divar.DivarClient/documentation/Divar/ForceUpdateViewController":{"role":"symbol","title":"ForceUpdateViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ForceUpdateViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ForceUpdateViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ForceUpdateViewController"}],"url":"\/documentation\/divar\/forceupdateviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController":{"role":"symbol","title":"WidgetBasedViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedViewController"}],"url":"\/documentation\/divar\/widgetbasedviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SelectablePostsListViewController":{"role":"symbol","title":"SelectablePostsListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SelectablePostsListViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SelectablePostsListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SelectablePostsListViewController"}],"url":"\/documentation\/divar\/selectablepostslistviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/NumberTextFieldDialogWidgetController":{"role":"symbol","title":"NumberTextFieldDialogWidgetController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NumberTextFieldDialogWidgetController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberTextFieldDialogWidgetController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NumberTextFieldDialogWidgetController"}],"url":"\/documentation\/divar\/numbertextfielddialogwidgetcontroller"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/documentation/Divar/CityMultiSelectViewController":{"role":"symbol","title":"CityMultiSelectViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CityMultiSelectViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CityMultiSelectViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CityMultiSelectViewController"}],"url":"\/documentation\/divar\/citymultiselectviewcontroller"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/documentation/Divar/ImagePickerImageSelection":{"deprecated":true,"role":"symbol","title":"ImagePickerImageSelection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImagePickerImageSelection"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImagePickerImageSelection"}],"url":"\/documentation\/divar\/imagepickerimageselection"},"doc://com.Divar.DivarClient/documentation/Divar/NickNameViewController":{"role":"symbol","title":"NickNameViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NickNameViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NickNameViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NickNameViewController"}],"url":"\/documentation\/divar\/nicknameviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MapDetailsViewController":{"role":"symbol","title":"MapDetailsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapDetailsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapDetailsViewController"}],"url":"\/documentation\/divar\/mapdetailsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/DisableListViewController":{"role":"symbol","title":"DisableListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisableListViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisableListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DisableListViewController"}],"url":"\/documentation\/divar\/disablelistviewcontroller"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController/shouldShowCloseButton":{"role":"symbol","title":"shouldShowCloseButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldShowCloseButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/shouldShowCloseButton","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseviewcontroller\/shouldshowclosebutton"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormController":{"role":"symbol","title":"BaseFormController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFormController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseFormController"}],"url":"\/documentation\/divar\/baseformcontroller"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/IVCollectionSelectorViewController":{"role":"symbol","title":"IVCollectionSelectorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IVCollectionSelectorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVCollectionSelectorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IVCollectionSelectorViewController"}],"url":"\/documentation\/divar\/ivcollectionselectorviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController/orderId":{"role":"symbol","title":"orderId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orderId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/orderId","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseviewcontroller\/orderid"},"doc://com.Divar.DivarClient/documentation/Divar/MyPostsViewController":{"role":"symbol","title":"MyPostsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyPostsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyPostsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MyPostsViewController"}],"url":"\/documentation\/divar\/mypostsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SearchAndSelectStringViewController":{"role":"symbol","title":"SearchAndSelectStringViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchAndSelectStringViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchAndSelectStringViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchAndSelectStringViewController"}],"url":"\/documentation\/divar\/searchandselectstringviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController/TooltipPresenter-Implementations":{"role":"collectionGroup","title":"TooltipPresenter Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/TooltipPresenter-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/baseviewcontroller\/tooltippresenter-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/ForwardViewController":{"role":"symbol","title":"ForwardViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ForwardViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ForwardViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ForwardViewController"}],"url":"\/documentation\/divar\/forwardviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CitySelectViewController":{"role":"symbol","title":"CitySelectViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CitySelectViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CitySelectViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CitySelectViewController"}],"url":"\/documentation\/divar\/cityselectviewcontroller"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/LocationSelectorViewController":{"role":"symbol","title":"LocationSelectorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationSelectorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationSelectorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationSelectorViewController"}],"url":"\/documentation\/divar\/locationselectorviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseSegmentedViewController":{"role":"symbol","title":"BaseSegmentedViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseSegmentedViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseSegmentedViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseSegmentedViewController"}],"url":"\/documentation\/divar\/basesegmentedviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController/swiftMessageLoading":{"role":"symbol","title":"swiftMessageLoading","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"swiftMessageLoading"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SwiftMessages","preciseIdentifier":"s:13SwiftMessagesAAC"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/swiftMessageLoading","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseviewcontroller\/swiftmessageloading"},"doc://com.Divar.DivarClient/documentation/Divar/AngoolakSandBoxViewController":{"role":"symbol","title":"AngoolakSandBoxViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AngoolakSandBoxViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakSandBoxViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AngoolakSandBoxViewController"}],"url":"\/documentation\/divar\/angoolaksandboxviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/DealerSubscriptionDetailsViewController":{"role":"symbol","title":"DealerSubscriptionDetailsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DealerSubscriptionDetailsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionDetailsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DealerSubscriptionDetailsViewController"}],"url":"\/documentation\/divar\/dealersubscriptiondetailsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController":{"role":"symbol","title":"PostListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostListViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostListViewController"}],"url":"\/documentation\/divar\/postlistviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostFeedBackViewController":{"role":"symbol","title":"PostFeedBackViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostFeedBackViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostFeedBackViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostFeedBackViewController"}],"url":"\/documentation\/divar\/postfeedbackviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SingleMultiBaseViewController":{"role":"symbol","title":"SingleMultiBaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleMultiBaseViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleMultiBaseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SingleMultiBaseViewController"}],"url":"\/documentation\/divar\/singlemultibaseviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController/viewWillAppear(_:)":{"role":"symbol","title":"viewWillAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/viewWillAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"url":"\/documentation\/divar\/baseviewcontroller\/viewwillappear(_:)"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController":{"role":"symbol","title":"PostArchiveViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostArchiveViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostArchiveViewController"}],"url":"\/documentation\/divar\/postarchiveviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/LimitedLocationSelectorViewController":{"role":"symbol","title":"LimitedLocationSelectorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LimitedLocationSelectorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LimitedLocationSelectorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LimitedLocationSelectorViewController"}],"url":"\/documentation\/divar\/limitedlocationselectorviewcontroller"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/SingleMultiEurekaViewController":{"role":"symbol","title":"SingleMultiEurekaViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleMultiEurekaViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleMultiEurekaViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SingleMultiEurekaViewController"}],"url":"\/documentation\/divar\/singlemultieurekaviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/TooltipPresenter":{"role":"symbol","title":"TooltipPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TooltipPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TooltipPresenter"}],"url":"\/documentation\/divar\/tooltippresenter"},"doc://com.Divar.DivarClient/documentation/Divar/SelectorWithSearchBarViewController":{"role":"symbol","title":"SelectorWithSearchBarViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SelectorWithSearchBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SelectorWithSearchBarViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SelectorWithSearchBarViewController"}],"url":"\/documentation\/divar\/selectorwithsearchbarviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/GeneralBulkLadderViewControllerProtocol":{"role":"symbol","title":"GeneralBulkLadderViewControllerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeneralBulkLadderViewControllerProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GeneralBulkLadderViewControllerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GeneralBulkLadderViewControllerProtocol"}],"url":"\/documentation\/divar\/generalbulkladderviewcontrollerprotocol"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/documentation/Divar/PostReportDescriptionViewController":{"role":"symbol","title":"PostReportDescriptionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostReportDescriptionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostReportDescriptionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostReportDescriptionViewController"}],"url":"\/documentation\/divar\/postreportdescriptionviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController":{"role":"symbol","title":"SingleHierarchyBaseController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleHierarchyBaseController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SingleHierarchyBaseController"}],"url":"\/documentation\/divar\/singlehierarchybasecontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BrandMultiHierarchyViewController":{"role":"symbol","title":"BrandMultiHierarchyViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrandMultiHierarchyViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BrandMultiHierarchyViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BrandMultiHierarchyViewController"}],"url":"\/documentation\/divar\/brandmultihierarchyviewcontroller"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/IVCollectionAssetSelectorViewController":{"role":"symbol","title":"IVCollectionAssetSelectorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IVCollectionAssetSelectorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVCollectionAssetSelectorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IVCollectionAssetSelectorViewController"}],"url":"\/documentation\/divar\/ivcollectionassetselectorviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/DealerSubscriptionViewController":{"role":"symbol","title":"DealerSubscriptionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DealerSubscriptionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DealerSubscriptionViewController"}],"url":"\/documentation\/divar\/dealersubscriptionviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController":{"role":"symbol","title":"VerificationCodeInputViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VerificationCodeInputViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VerificationCodeInputViewController"}],"url":"\/documentation\/divar\/verificationcodeinputviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BulkLadderViewController":{"role":"symbol","title":"BulkLadderViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BulkLadderViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BulkLadderViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BulkLadderViewController"}],"url":"\/documentation\/divar\/bulkladderviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/QATableViewController":{"role":"symbol","title":"QATableViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QATableViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QATableViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QATableViewController"}],"url":"\/documentation\/divar\/qatableviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/NumberInputViewController":{"role":"symbol","title":"NumberInputViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NumberInputViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberInputViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NumberInputViewController"}],"url":"\/documentation\/divar\/numberinputviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PaymentSystemProtocol":{"role":"symbol","title":"PaymentSystemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSystemProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaymentSystemProtocol"}],"url":"\/documentation\/divar\/paymentsystemprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/RecentVisitsViewController":{"role":"symbol","title":"RecentVisitsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecentVisitsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RecentVisitsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RecentVisitsViewController"}],"url":"\/documentation\/divar\/recentvisitsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostGetContactsViewController":{"role":"symbol","title":"PostGetContactsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostGetContactsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostGetContactsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostGetContactsViewController"}],"url":"\/documentation\/divar\/postgetcontactsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController":{"role":"symbol","title":"BaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseViewController"}],"url":"\/documentation\/divar\/baseviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController/canBecomeFirstResponder":{"role":"symbol","title":"canBecomeFirstResponder","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canBecomeFirstResponder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/canBecomeFirstResponder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canBecomeFirstResponder"}],"url":"\/documentation\/divar\/baseviewcontroller\/canbecomefirstresponder"},"doc://com.Divar.DivarClient/documentation/Divar/ArchiveNoteViewController":{"role":"symbol","title":"ArchiveNoteViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArchiveNoteViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ArchiveNoteViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ArchiveNoteViewController"}],"url":"\/documentation\/divar\/archivenoteviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MapSelectorViewController":{"role":"symbol","title":"MapSelectorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapSelectorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapSelectorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapSelectorViewController"}],"url":"\/documentation\/divar\/mapselectorviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/baseviewcontroller\/viewdidload()"},"doc://com.Divar.DivarClient/documentation/Divar/FirstTimeViewController":{"role":"symbol","title":"FirstTimeViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FirstTimeViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FirstTimeViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FirstTimeViewController"}],"url":"\/documentation\/divar\/firsttimeviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatSettingsController":{"role":"symbol","title":"ChatSettingsController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatSettingsController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatSettingsController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatSettingsController"}],"url":"\/documentation\/divar\/chatsettingscontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BeforeRegisterTermsAndConditionsVC":{"role":"symbol","title":"BeforeRegisterTermsAndConditionsVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BeforeRegisterTermsAndConditionsVC"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BeforeRegisterTermsAndConditionsVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BeforeRegisterTermsAndConditionsVC"}],"url":"\/documentation\/divar\/beforeregistertermsandconditionsvc"},"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController/swiftMessageError":{"role":"symbol","title":"swiftMessageError","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"swiftMessageError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SwiftMessages","preciseIdentifier":"s:13SwiftMessagesAAC"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/swiftMessageError","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseviewcontroller\/swiftmessageerror"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/ErrorMessageHandler":{"role":"symbol","title":"ErrorMessageHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorMessageHandler"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorMessageHandler"}],"url":"\/documentation\/divar\/errormessagehandler"},"doc://com.Divar.DivarClient/documentation/Divar/DistrictedMapViewController":{"role":"symbol","title":"DistrictedMapViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DistrictedMapViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DistrictedMapViewController"}],"url":"\/documentation\/divar\/districtedmapviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ConversationsViewController":{"role":"symbol","title":"ConversationsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConversationsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationsViewController"}],"url":"\/documentation\/divar\/conversationsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ShowMessageProtocol":{"role":"symbol","title":"ShowMessageProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowMessageProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowMessageProtocol"}],"url":"\/documentation\/divar\/showmessageprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController/init(withNib:)":{"role":"symbol","title":"init(withNib:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withNib"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/init(withNib:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseviewcontroller\/init(withnib:)"},"doc://com.Divar.DivarClient/documentation/Divar/RealEstateLocationSelectorViewController":{"deprecated":true,"role":"symbol","title":"RealEstateLocationSelectorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RealEstateLocationSelectorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateLocationSelectorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RealEstateLocationSelectorViewController"}],"url":"\/documentation\/divar\/realestatelocationselectorviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/documentation/Divar/PostPaymentHistoryViewController":{"role":"symbol","title":"PostPaymentHistoryViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostPaymentHistoryViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostPaymentHistoryViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostPaymentHistoryViewController"}],"url":"\/documentation\/divar\/postpaymenthistoryviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatInstructLoginViewController":{"role":"symbol","title":"ChatInstructLoginViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatInstructLoginViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatInstructLoginViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatInstructLoginViewController"}],"url":"\/documentation\/divar\/chatinstructloginviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/GetContactViewController":{"role":"symbol","title":"GetContactViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetContactViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GetContactViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GetContactViewController"}],"url":"\/documentation\/divar\/getcontactviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController/viewDidDisappear(_:)":{"role":"symbol","title":"viewDidDisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/viewDidDisappear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidDisappear:"}],"url":"\/documentation\/divar\/baseviewcontroller\/viewdiddisappear(_:)"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewControllerProtocol":{"role":"symbol","title":"WidgetBasedViewControllerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedViewControllerProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewControllerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedViewControllerProtocol"}],"url":"\/documentation\/divar\/widgetbasedviewcontrollerprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/NotesViewController":{"role":"symbol","title":"NotesViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotesViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NotesViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NotesViewController"}],"url":"\/documentation\/divar\/notesviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController":{"role":"symbol","title":"TransformablePriceViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransformablePriceViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TransformablePriceViewController"}],"url":"\/documentation\/divar\/transformablepriceviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/NoteViewController":{"role":"symbol","title":"NoteViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NoteViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NoteViewController"}],"url":"\/documentation\/divar\/noteviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SettingsViewController":{"role":"symbol","title":"SettingsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SettingsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SettingsViewController"}],"url":"\/documentation\/divar\/settingsviewcontroller"},"doc://com.Divar.DivarClient/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)UIViewController"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/baseviewcontroller\/init(coder:)"},"doc://com.Divar.DivarClient/documentation/Divar/RateViewController":{"role":"symbol","title":"RateViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RateViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RateViewController"}],"url":"\/documentation\/divar\/rateviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ValidatorRowController":{"role":"symbol","title":"ValidatorRowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidatorRowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ValidatorRowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ValidatorRowController"}],"url":"\/documentation\/divar\/validatorrowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/IVVideoRecorderViewController":{"role":"symbol","title":"IVVideoRecorderViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IVVideoRecorderViewController"}],"abstract":[{"type":"text","text":"Present this controller to record video from camera"}],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVVideoRecorderViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IVVideoRecorderViewController"}],"url":"\/documentation\/divar\/ivvideorecorderviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/NumberTextFieldPageController":{"role":"symbol","title":"NumberTextFieldPageController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NumberTextFieldPageController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberTextFieldPageController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NumberTextFieldPageController"}],"url":"\/documentation\/divar\/numbertextfieldpagecontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"BaseViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"BaseViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"BaseViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/canBecomeFirstResponder"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/init()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/viewDidDisappear(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/viewDidLoad()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController\/viewWillAppear(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakSandBoxViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ArchiveNoteViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseSegmentedViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BeforeRegisterTermsAndConditionsVC","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BrandMultiHierarchyViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatInstructLoginViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatSettingsController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CityMultiSelectViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CitySelectViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConversationsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionDetailsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisableListViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FirstTimeViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ForceUpdateViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ForwardViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GetContactViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVCollectionAssetSelectorViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVCollectionSelectorViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVVideoRecorderViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelection","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LimitedLocationSelectorViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationSelectorViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDetailsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDistrictSelectorViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapSelectorViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MultiConversationDeleteViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyPostsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NickNameViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NotesViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberInputViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberTextFieldDialogWidgetController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberTextFieldPageController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostFeedBackViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostGetContactsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostPaymentHistoryViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostReportDescriptionViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QATableViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateLocationSelectorViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RecentVisitsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchAndSelectStringViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SelectorWithSearchBarViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SettingsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleMultiBaseViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ValidatorRowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController\/title","value":"InputAreaViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController\/fragments","value":[{"kind":"identifier","text":"InputAreaViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MultiConversationDeleteViewController\/title","value":"MultiConversationDeleteViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MultiConversationDeleteViewController\/fragments","value":[{"kind":"identifier","text":"MultiConversationDeleteViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/title","value":"ChatViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/fragments","value":[{"kind":"identifier","text":"ChatViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarksViewController\/title","value":"BookmarksViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarksViewController\/fragments","value":[{"kind":"identifier","text":"BookmarksViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteWithBottomBarViewController\/title","value":"NoteWithBottomBarViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteWithBottomBarViewController\/fragments","value":[{"kind":"identifier","text":"NoteWithBottomBarViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDistrictSelectorViewController\/title","value":"MapDistrictSelectorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDistrictSelectorViewController\/fragments","value":[{"kind":"identifier","text":"MapDistrictSelectorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController\/title","value":"MessagingViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController\/fragments","value":[{"kind":"identifier","text":"MessagingViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ForceUpdateViewController\/title","value":"ForceUpdateViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ForceUpdateViewController\/fragments","value":[{"kind":"identifier","text":"ForceUpdateViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedViewController\/title","value":"WidgetBasedViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NumberTextFieldDialogWidgetController\/title","value":"NumberTextFieldDialogWidgetController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NumberTextFieldDialogWidgetController\/fragments","value":[{"kind":"identifier","text":"NumberTextFieldDialogWidgetController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CityMultiSelectViewController\/title","value":"CityMultiSelectViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CityMultiSelectViewController\/fragments","value":[{"kind":"identifier","text":"CityMultiSelectViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelection\/title","value":"ImagePickerImageSelection"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelection\/fragments","value":[{"kind":"identifier","text":"ImagePickerImageSelection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NickNameViewController\/title","value":"NickNameViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NickNameViewController\/fragments","value":[{"kind":"identifier","text":"NickNameViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDetailsViewController\/title","value":"MapDetailsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDetailsViewController\/fragments","value":[{"kind":"identifier","text":"MapDetailsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DisableListViewController\/title","value":"DisableListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DisableListViewController\/fragments","value":[{"kind":"identifier","text":"DisableListViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFormController\/title","value":"BaseFormController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFormController\/fragments","value":[{"kind":"identifier","text":"BaseFormController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1IVCollectionSelectorViewController\/title","value":"IVCollectionSelectorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1IVCollectionSelectorViewController\/fragments","value":[{"kind":"identifier","text":"IVCollectionSelectorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MyPostsViewController\/title","value":"MyPostsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MyPostsViewController\/fragments","value":[{"kind":"identifier","text":"MyPostsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchAndSelectStringViewController\/title","value":"SearchAndSelectStringViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchAndSelectStringViewController\/fragments","value":[{"kind":"identifier","text":"SearchAndSelectStringViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ForwardViewController\/title","value":"ForwardViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ForwardViewController\/fragments","value":[{"kind":"identifier","text":"ForwardViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CitySelectViewController\/title","value":"CitySelectViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CitySelectViewController\/fragments","value":[{"kind":"identifier","text":"CitySelectViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LocationSelectorViewController\/title","value":"LocationSelectorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LocationSelectorViewController\/fragments","value":[{"kind":"identifier","text":"LocationSelectorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseSegmentedViewController\/title","value":"BaseSegmentedViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseSegmentedViewController\/fragments","value":[{"kind":"identifier","text":"BaseSegmentedViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakSandBoxViewController\/title","value":"AngoolakSandBoxViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakSandBoxViewController\/fragments","value":[{"kind":"identifier","text":"AngoolakSandBoxViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubscriptionDetailsViewController\/title","value":"DealerSubscriptionDetailsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubscriptionDetailsViewController\/fragments","value":[{"kind":"identifier","text":"DealerSubscriptionDetailsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListViewController\/title","value":"PostListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListViewController\/fragments","value":[{"kind":"identifier","text":"PostListViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostFeedBackViewController\/title","value":"PostFeedBackViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostFeedBackViewController\/fragments","value":[{"kind":"identifier","text":"PostFeedBackViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleMultiBaseViewController\/title","value":"SingleMultiBaseViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleMultiBaseViewController\/fragments","value":[{"kind":"identifier","text":"SingleMultiBaseViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController\/title","value":"PostArchiveViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController\/fragments","value":[{"kind":"identifier","text":"PostArchiveViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LimitedLocationSelectorViewController\/title","value":"LimitedLocationSelectorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LimitedLocationSelectorViewController\/fragments","value":[{"kind":"identifier","text":"LimitedLocationSelectorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SelectorWithSearchBarViewController\/title","value":"SelectorWithSearchBarViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SelectorWithSearchBarViewController\/fragments","value":[{"kind":"identifier","text":"SelectorWithSearchBarViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostReportDescriptionViewController\/title","value":"PostReportDescriptionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostReportDescriptionViewController\/fragments","value":[{"kind":"identifier","text":"PostReportDescriptionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleHierarchyBaseController\/title","value":"SingleHierarchyBaseController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleHierarchyBaseController\/fragments","value":[{"kind":"identifier","text":"SingleHierarchyBaseController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BrandMultiHierarchyViewController\/title","value":"BrandMultiHierarchyViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BrandMultiHierarchyViewController\/fragments","value":[{"kind":"identifier","text":"BrandMultiHierarchyViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1IVCollectionAssetSelectorViewController\/title","value":"IVCollectionAssetSelectorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1IVCollectionAssetSelectorViewController\/fragments","value":[{"kind":"identifier","text":"IVCollectionAssetSelectorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubscriptionViewController\/title","value":"DealerSubscriptionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubscriptionViewController\/fragments","value":[{"kind":"identifier","text":"DealerSubscriptionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VerificationCodeInputViewController\/title","value":"VerificationCodeInputViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VerificationCodeInputViewController\/fragments","value":[{"kind":"identifier","text":"VerificationCodeInputViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1QATableViewController\/title","value":"QATableViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1QATableViewController\/fragments","value":[{"kind":"identifier","text":"QATableViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NumberInputViewController\/title","value":"NumberInputViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NumberInputViewController\/fragments","value":[{"kind":"identifier","text":"NumberInputViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RecentVisitsViewController\/title","value":"RecentVisitsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RecentVisitsViewController\/fragments","value":[{"kind":"identifier","text":"RecentVisitsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostGetContactsViewController\/title","value":"PostGetContactsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostGetContactsViewController\/fragments","value":[{"kind":"identifier","text":"PostGetContactsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController\/title","value":"BaseViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController\/fragments","value":[{"kind":"identifier","text":"BaseViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController~1canBecomeFirstResponder\/title","value":"canBecomeFirstResponder"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController~1canBecomeFirstResponder\/fragments","value":[{"kind":"identifier","text":"canBecomeFirstResponder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ArchiveNoteViewController\/title","value":"ArchiveNoteViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ArchiveNoteViewController\/fragments","value":[{"kind":"identifier","text":"ArchiveNoteViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapSelectorViewController\/title","value":"MapSelectorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapSelectorViewController\/fragments","value":[{"kind":"identifier","text":"MapSelectorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FirstTimeViewController\/title","value":"FirstTimeViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FirstTimeViewController\/fragments","value":[{"kind":"identifier","text":"FirstTimeViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatSettingsController\/title","value":"ChatSettingsController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatSettingsController\/fragments","value":[{"kind":"identifier","text":"ChatSettingsController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BeforeRegisterTermsAndConditionsVC\/title","value":"BeforeRegisterTermsAndConditionsVC"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BeforeRegisterTermsAndConditionsVC\/fragments","value":[{"kind":"identifier","text":"BeforeRegisterTermsAndConditionsVC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictedMapViewController\/title","value":"DistrictedMapViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictedMapViewController\/fragments","value":[{"kind":"identifier","text":"DistrictedMapViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ConversationsViewController\/title","value":"ConversationsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ConversationsViewController\/fragments","value":[{"kind":"identifier","text":"ConversationsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateLocationSelectorViewController\/title","value":"RealEstateLocationSelectorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateLocationSelectorViewController\/fragments","value":[{"kind":"identifier","text":"RealEstateLocationSelectorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostPaymentHistoryViewController\/title","value":"PostPaymentHistoryViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostPaymentHistoryViewController\/fragments","value":[{"kind":"identifier","text":"PostPaymentHistoryViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatInstructLoginViewController\/title","value":"ChatInstructLoginViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatInstructLoginViewController\/fragments","value":[{"kind":"identifier","text":"ChatInstructLoginViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GetContactViewController\/title","value":"GetContactViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GetContactViewController\/fragments","value":[{"kind":"identifier","text":"GetContactViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController~1viewDidDisappear(_:)\/title","value":"viewDidDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController~1viewDidDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidDisappear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NotesViewController\/title","value":"NotesViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NotesViewController\/fragments","value":[{"kind":"identifier","text":"NotesViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TransformablePriceViewController\/title","value":"TransformablePriceViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TransformablePriceViewController\/fragments","value":[{"kind":"identifier","text":"TransformablePriceViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteViewController\/title","value":"NoteViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteViewController\/fragments","value":[{"kind":"identifier","text":"NoteViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SettingsViewController\/title","value":"SettingsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SettingsViewController\/fragments","value":[{"kind":"identifier","text":"SettingsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateViewController\/title","value":"RateViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateViewController\/fragments","value":[{"kind":"identifier","text":"RateViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ValidatorRowController\/title","value":"ValidatorRowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ValidatorRowController\/fragments","value":[{"kind":"identifier","text":"ValidatorRowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1IVVideoRecorderViewController\/title","value":"IVVideoRecorderViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1IVVideoRecorderViewController\/fragments","value":[{"kind":"identifier","text":"IVVideoRecorderViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NumberTextFieldPageController\/title","value":"NumberTextFieldPageController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NumberTextFieldPageController\/fragments","value":[{"kind":"identifier","text":"NumberTextFieldPageController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}