{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFormViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/baseformviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/baseformviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/@M@Eureka@objc(cs)EurekaFormViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostPaymentViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostRedeemCodeController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/6Eureka12FormDelegateP","doc:\/\/com.Divar.DivarClient\/6Eureka26FormViewControllerProtocolP","doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIScrollViewDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDataSource","doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/init(container:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/customNavigationAccessoryView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/formAccessoryViewSttribute","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/isSettingValues","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/property","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/swiftMessageError","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/swiftMessageLoading","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/swiftMessageToast"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/changeRowDetailTextLabelColor(for:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/defaultDoneAction()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/deleteAnimation(forRows:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/deleteAnimation(forSections:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/disableRowsForSubmit(_:bool:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/getDependenciesToRemove(keys:schemas:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/getRow(with:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/getRowsToBeAdded(for:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/getSchemasToBeAdded(for:dependencySchemas:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/handleRowsDependency(with:row:newData:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/removeAllErrorsFromForm(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/removeFocusedRowValue()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/removeRowValue(from:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/removeRows(for:in:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/removeSectionsRowSeparators(_:option:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/setValue(_:_:_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/setValueForRow(_:values:_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/setValueForSection(_:_:isFillingDraft:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/showCancelButton()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/validate(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/valueHasBeenChanged(for:oldValue:newValue:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/viewDidLoad()"]},{"title":"Type Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/getBarButton(_:title:action:tintColor:labelAlignment:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/getFormHolder(from:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFormViewController"}],"title":"BaseFormViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)BaseFormViewController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"BaseFormViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/6Eureka12FormDelegateP":{"type":"unresolvable","title":"Eureka.FormDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/6Eureka12FormDelegateP"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/setValueForSection(_:_:isFillingDraft:)":{"role":"symbol","title":"setValueForSection(_:_:isFillingDraft:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setValueForSection"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"typeIdentifier","text":"Form","preciseIdentifier":"s:6Eureka4FormC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isFillingDraft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/setValueForSection(_:_:isFillingDraft:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/setvalueforsection(_:_:isfillingdraft:)"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/removeAllErrorsFromForm(_:)":{"role":"symbol","title":"removeAllErrorsFromForm(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAllErrorsFromForm"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Form","preciseIdentifier":"s:6Eureka4FormC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/removeAllErrorsFromForm(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/removeallerrorsfromform(_:)"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/getRow(with:)":{"role":"symbol","title":"getRow(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRow"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"BaseRow","preciseIdentifier":"s:6Eureka7BaseRowC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/getRow(with:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/getrow(with:)"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/getDependenciesToRemove(keys:schemas:)":{"role":"symbol","title":"getDependenciesToRemove(keys:schemas:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDependenciesToRemove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keys"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"schemas"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":"]?) -> ["},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/getDependenciesToRemove(keys:schemas:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/getdependenciestoremove(keys:schemas:)"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/customNavigationAccessoryView":{"role":"symbol","title":"customNavigationAccessoryView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customNavigationAccessoryView"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"NavigationAccessory","preciseIdentifier":"s:6Eureka19NavigationAccessoryP"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/customNavigationAccessoryView","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/customnavigationaccessoryview"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/init(container:)":{"role":"symbol","title":"init(container:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseFormViewControllerDIContainer","preciseIdentifier":"s:5Divar33BaseFormViewControllerDIContainera"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/init(container:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/init(container:)"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/deleteAnimation(forSections:)":{"role":"symbol","title":"deleteAnimation(forSections:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteAnimation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forSections"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Section","preciseIdentifier":"s:6Eureka7SectionC"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"RowAnimation","preciseIdentifier":"c:@E@UITableViewRowAnimation"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/deleteAnimation(forSections:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/deleteanimation(forsections:)"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController":{"role":"symbol","title":"BaseFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseFormViewController"}],"url":"\/documentation\/divar\/baseformviewcontroller"},"doc://com.Divar.DivarClient/objc(pl)UITableViewDataSource":{"type":"unresolvable","title":"UIKit.UITableViewDataSource","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDataSource"},"doc://com.Divar.DivarClient/documentation/Divar/PostPaymentViewController":{"role":"symbol","title":"PostPaymentViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostPaymentViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostPaymentViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostPaymentViewController"}],"url":"\/documentation\/divar\/postpaymentviewcontroller"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/removeRowValue(from:)":{"role":"symbol","title":"removeRowValue(from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeRowValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseRow","preciseIdentifier":"s:6Eureka7BaseRowC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/removeRowValue(from:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/removerowvalue(from:)"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/showCancelButton()":{"role":"symbol","title":"showCancelButton()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showCancelButton"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/showCancelButton()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/showcancelbutton()"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/removeFocusedRowValue()":{"role":"symbol","title":"removeFocusedRowValue()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeFocusedRowValue"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/removeFocusedRowValue()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeFocusedRowValue"}],"url":"\/documentation\/divar\/baseformviewcontroller\/removefocusedrowvalue()"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/isSettingValues":{"role":"symbol","title":"isSettingValues","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSettingValues"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/isSettingValues","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/issettingvalues"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/swiftMessageLoading":{"role":"symbol","title":"swiftMessageLoading","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"swiftMessageLoading"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SwiftMessages","preciseIdentifier":"s:13SwiftMessagesAAC"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/swiftMessageLoading","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/swiftmessageloading"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/property":{"role":"symbol","title":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"property"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/property","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/property"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/6Eureka26FormViewControllerProtocolP":{"type":"unresolvable","title":"Eureka.FormViewControllerProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/6Eureka26FormViewControllerProtocolP"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/setValueForRow(_:values:_:)":{"role":"symbol","title":"setValueForRow(_:values:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setValueForRow"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseRow","preciseIdentifier":"s:6Eureka7BaseRowC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"values"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/setValueForRow(_:values:_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/setvalueforrow(_:values:_:)"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/baseformviewcontroller\/viewdidload()"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/disableRowsForSubmit(_:bool:)":{"role":"symbol","title":"disableRowsForSubmit(_:bool:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableRowsForSubmit"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Form","preciseIdentifier":"s:6Eureka4FormC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bool"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/disableRowsForSubmit(_:bool:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/disablerowsforsubmit(_:bool:)"},"doc://com.Divar.DivarClient/@M@Eureka@objc(cs)EurekaFormViewController":{"type":"unresolvable","title":"EurekaFormViewController","identifier":"doc:\/\/com.Divar.DivarClient\/@M@Eureka@objc(cs)EurekaFormViewController"},"doc://com.Divar.DivarClient/documentation/Divar/PostRedeemCodeController":{"role":"symbol","title":"PostRedeemCodeController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostRedeemCodeController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostRedeemCodeController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostRedeemCodeController"}],"url":"\/documentation\/divar\/postredeemcodecontroller"},"doc://com.Divar.DivarClient/objc(pl)UITableViewDelegate":{"type":"unresolvable","title":"UIKit.UITableViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/deleteAnimation(forRows:)":{"role":"symbol","title":"deleteAnimation(forRows:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteAnimation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forRows"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"BaseRow","preciseIdentifier":"s:6Eureka7BaseRowC"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"RowAnimation","preciseIdentifier":"c:@E@UITableViewRowAnimation"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/deleteAnimation(forRows:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/deleteanimation(forrows:)"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/getRowsToBeAdded(for:)":{"role":"symbol","title":"getRowsToBeAdded(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRowsToBeAdded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":"]?) -> [("},{"kind":"typeIdentifier","text":"BaseRow","preciseIdentifier":"s:6Eureka7BaseRowC"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/getRowsToBeAdded(for:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/getrowstobeadded(for:)"},"doc://com.Divar.DivarClient/documentation/Divar/ShowMessageProtocol":{"role":"symbol","title":"ShowMessageProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowMessageProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowMessageProtocol"}],"url":"\/documentation\/divar\/showmessageprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/getSchemasToBeAdded(for:dependencySchemas:)":{"role":"symbol","title":"getSchemasToBeAdded(for:dependencySchemas:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSchemasToBeAdded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseRow","preciseIdentifier":"s:6Eureka7BaseRowC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dependencySchemas"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":"]?) -> ["},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/getSchemasToBeAdded(for:dependencySchemas:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/getschemastobeadded(for:dependencyschemas:)"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/swiftMessageToast":{"role":"symbol","title":"swiftMessageToast","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"swiftMessageToast"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SwiftMessages","preciseIdentifier":"s:13SwiftMessagesAAC"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/swiftMessageToast","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/swiftmessagetoast"},"doc://com.Divar.DivarClient/documentation/Divar/ShowErrorProtocol":{"role":"symbol","title":"ShowErrorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowErrorProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowErrorProtocol"}],"url":"\/documentation\/divar\/showerrorprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/defaultDoneAction()":{"role":"symbol","title":"defaultDoneAction()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultDoneAction"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/defaultDoneAction()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultDoneAction"}],"url":"\/documentation\/divar\/baseformviewcontroller\/defaultdoneaction()"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/swiftMessageError":{"role":"symbol","title":"swiftMessageError","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"swiftMessageError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SwiftMessages","preciseIdentifier":"s:13SwiftMessagesAAC"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/swiftMessageError","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/swiftmessageerror"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/setValue(_:_:_:)":{"role":"symbol","title":"setValue(_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setValue"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"typeIdentifier","text":"Form","preciseIdentifier":"s:6Eureka4FormC"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/setValue(_:_:_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/setvalue(_:_:_:)"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController":{"role":"symbol","title":"AbstractFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AbstractFormViewController"}],"url":"\/documentation\/divar\/abstractformviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/changeRowDetailTextLabelColor(for:)":{"role":"symbol","title":"changeRowDetailTextLabelColor(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeRowDetailTextLabelColor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseRow","preciseIdentifier":"s:6Eureka7BaseRowC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/changeRowDetailTextLabelColor(for:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/changerowdetailtextlabelcolor(for:)"},"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/valueHasBeenChanged(for:oldValue:newValue:)":{"role":"symbol","title":"valueHasBeenChanged(for:oldValue:newValue:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"valueHasBeenChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseRow","preciseIdentifier":"s:6Eureka7BaseRowC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"oldValue"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"newValue"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/valueHasBeenChanged(for:oldValue:newValue:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/valuehasbeenchanged(for:oldvalue:newvalue:)"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIScrollViewDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/validate(_:)":{"role":"symbol","title":"validate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseRow","preciseIdentifier":"s:6Eureka7BaseRowC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/validate(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/validate(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/getFormHolder(from:)":{"role":"symbol","title":"getFormHolder(from:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFormHolder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/getFormHolder(from:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/getformholder(from:)"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/baseformviewcontroller\/init(coder:)"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/removeSectionsRowSeparators(_:option:)":{"role":"symbol","title":"removeSectionsRowSeparators(_:option:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeSectionsRowSeparators"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"Section","preciseIdentifier":"s:6Eureka7SectionC"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"option"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SeparatorHideStyle","preciseIdentifier":"s:5Divar18SeparatorHideStyleO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/removeSectionsRowSeparators(_:option:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/removesectionsrowseparators(_:option:)"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/removeRows(for:in:)":{"role":"symbol","title":"removeRows(for:in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeRows"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Section","preciseIdentifier":"s:6Eureka7SectionC"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/removeRows(for:in:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/removerows(for:in:)"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/handleRowsDependency(with:row:newData:)":{"role":"symbol","title":"handleRowsDependency(with:row:newData:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleRowsDependency"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"row"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseRow","preciseIdentifier":"s:6Eureka7BaseRowC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/handleRowsDependency(with:row:newData:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/handlerowsdependency(with:row:newdata:)"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/getBarButton(_:title:action:tintColor:labelAlignment:)":{"role":"symbol","title":"getBarButton(_:title:action:tintColor:labelAlignment:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBarButton"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tintColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"labelAlignment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ContentHorizontalAlignment","preciseIdentifier":"c:@E@UIControlContentHorizontalAlignment"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/getBarButton(_:title:action:tintColor:labelAlignment:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/getbarbutton(_:title:action:tintcolor:labelalignment:)"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormViewController/formAccessoryViewSttribute":{"role":"symbol","title":"formAccessoryViewSttribute","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"formAccessoryViewSttribute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormAccessoryViewAttribute","preciseIdentifier":"s:5Divar26FormAccessoryViewAttributeV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/formAccessoryViewSttribute","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseformviewcontroller\/formaccessoryviewsttribute"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"BaseFormViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"BaseFormViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"BaseFormViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/defaultDoneAction()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/removeFocusedRowValue()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/@M@Eureka@objc(cs)EurekaFormViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostPaymentViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostRedeemCodeController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFormViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"EurekaFormViewController","preciseIdentifier":"c:@M@Eureka@objc(cs)EurekaFormViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFormViewController\/title","value":"BaseFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFormViewController\/fragments","value":[{"kind":"identifier","text":"BaseFormViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostPaymentViewController\/title","value":"PostPaymentViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostPaymentViewController\/fragments","value":[{"kind":"identifier","text":"PostPaymentViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFormViewController~1removeFocusedRowValue()\/title","value":"removeFocusedRowValue"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFormViewController~1removeFocusedRowValue()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeFocusedRowValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFormViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFormViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostRedeemCodeController\/title","value":"PostRedeemCodeController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostRedeemCodeController\/fragments","value":[{"kind":"identifier","text":"PostRedeemCodeController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFormViewController~1defaultDoneAction()\/title","value":"defaultDoneAction"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFormViewController~1defaultDoneAction()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"defaultDoneAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController\/title","value":"AbstractFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController\/fragments","value":[{"kind":"identifier","text":"AbstractFormViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFormViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFormViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}