{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFlowController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/baseflowcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/baseflowcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AgentManagementFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BrowseFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BulkLadderBaseFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarInspectionFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarSpecsFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealershipGetContactFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeaturedPostsFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JobsFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/KalaDetailsFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandingPageFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LinkFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MFMessageFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplacePriceFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceQuickEditPostFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceRegisterFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NationalIdVerificationFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OpenPageFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OperatorManagementFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostDetailsFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SaleAssistantFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SettingsFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShahkarLandlineVerificationFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SubmitPromotionFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TestPhoneNumberFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransactionFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UserRegisterFlowController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CategoryHierarchyControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CityMultiSelectViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LoginRequiredProtocol","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchFilterViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedActionDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/init(container:configuration:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/actionDispatcher","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/configuration","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/container","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/navigationController"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/initialQaWidget(url:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/initialViewController()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/logCustomerInspectionSecondaryButton(postToken:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/logInspectionReportSecondaryButton(postToken:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/navigationController(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/openBooleanRateFeedback(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/openRateFeedback(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/performCustomAction(action:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/CategoryHierarchyControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/CityMultiSelectViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/LandlineVerificationFlowControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/PostArchiveViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/PostCreateViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/RateViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/SearchFilterViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/WidgetBasedActionDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFlowController"}],"title":"BaseFlowController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)BaseFlowController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"BaseFlowController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewControllerDelegate":{"role":"symbol","title":"PostArchiveViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostArchiveViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostArchiveViewControllerDelegate"}],"url":"\/documentation\/divar\/postarchiveviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/LandlineVerificationFlowControllerDelegate-Implementations":{"role":"collectionGroup","title":"LandlineVerificationFlowControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/LandlineVerificationFlowControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/landlineverificationflowcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderFlowController":{"role":"symbol","title":"MyDivarHolderFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyDivarHolderFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MyDivarHolderFlowController"}],"url":"\/documentation\/divar\/mydivarholderflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/openBooleanRateFeedback(_:)":{"role":"symbol","title":"openBooleanRateFeedback(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openBooleanRateFeedback"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CustomAction","preciseIdentifier":"s:5Divar12CustomActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/openBooleanRateFeedback(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/openbooleanratefeedback(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/LandlineVerificationFlowController":{"role":"symbol","title":"LandlineVerificationFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandlineVerificationFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandlineVerificationFlowController"}],"url":"\/documentation\/divar\/landlineverificationflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/OperatorManagementFlowController":{"role":"symbol","title":"OperatorManagementFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OperatorManagementFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OperatorManagementFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OperatorManagementFlowController"}],"url":"\/documentation\/divar\/operatormanagementflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/SearchFilterViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"SearchFilterViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/SearchFilterViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/searchfilterviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/openRateFeedback(_:)":{"role":"symbol","title":"openRateFeedback(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openRateFeedback"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CustomAction","preciseIdentifier":"s:5Divar12CustomActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/openRateFeedback(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/openratefeedback(_:)"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/MarketplaceQuickEditPostFlowController":{"role":"symbol","title":"MarketplaceQuickEditPostFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketplaceQuickEditPostFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceQuickEditPostFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketplaceQuickEditPostFlowController"}],"url":"\/documentation\/divar\/marketplacequickeditpostflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarAgentFlowController":{"role":"symbol","title":"CarAgentFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarAgentFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarAgentFlowController"}],"url":"\/documentation\/divar\/caragentflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MarketplaceRegisterFlowController":{"role":"symbol","title":"MarketplaceRegisterFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketplaceRegisterFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceRegisterFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketplaceRegisterFlowController"}],"url":"\/documentation\/divar\/marketplaceregisterflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/init(container:configuration:)":{"role":"symbol","title":"init(container:configuration:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseFlowDIContainer","preciseIdentifier":"s:5Divar19BaseFlowDIContainera"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IntroConfig","preciseIdentifier":"s:5Divar11IntroConfigV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/init(container:configuration:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/init(container:configuration:)"},"doc://com.Divar.DivarClient/documentation/Divar/PostManageFlowController":{"role":"symbol","title":"PostManageFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostManageFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostManageFlowController"}],"url":"\/documentation\/divar\/postmanageflowcontroller"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/ChatFlowController":{"role":"symbol","title":"ChatFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatFlowController"}],"url":"\/documentation\/divar\/chatflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedActionDelegate":{"role":"symbol","title":"WidgetBasedActionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedActionDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedActionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedActionDelegate"}],"url":"\/documentation\/divar\/widgetbasedactiondelegate"},"doc://com.Divar.DivarClient/documentation/Divar/UserRegisterFlowController":{"role":"symbol","title":"UserRegisterFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserRegisterFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UserRegisterFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserRegisterFlowController"}],"url":"\/documentation\/divar\/userregisterflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SearchFilterViewControllerDelegate":{"role":"symbol","title":"SearchFilterViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchFilterViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchFilterViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchFilterViewControllerDelegate"}],"url":"\/documentation\/divar\/searchfilterviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/KalaDetailsFlowController":{"role":"symbol","title":"KalaDetailsFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KalaDetailsFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/KalaDetailsFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KalaDetailsFlowController"}],"url":"\/documentation\/divar\/kaladetailsflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CityMultiSelectViewControllerDelegate":{"role":"symbol","title":"CityMultiSelectViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CityMultiSelectViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CityMultiSelectViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CityMultiSelectViewControllerDelegate"}],"url":"\/documentation\/divar\/citymultiselectviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/initialQaWidget(url:)":{"role":"symbol","title":"initialQaWidget(url:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialQaWidget"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/initialQaWidget(url:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/initialqawidget(url:)"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/RateViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"RateViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/RateViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/rateviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/SettingsFlowController":{"role":"symbol","title":"SettingsFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SettingsFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SettingsFlowController"}],"url":"\/documentation\/divar\/settingsflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ShahkarLandlineVerificationFlowController":{"role":"symbol","title":"ShahkarLandlineVerificationFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShahkarLandlineVerificationFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShahkarLandlineVerificationFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShahkarLandlineVerificationFlowController"}],"url":"\/documentation\/divar\/shahkarlandlineverificationflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarBusinessFlowController":{"role":"symbol","title":"CarBusinessFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarBusinessFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarBusinessFlowController"}],"url":"\/documentation\/divar\/carbusinessflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/LoginRequiredProtocol":{"role":"symbol","title":"LoginRequiredProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoginRequiredProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LoginRequiredProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LoginRequiredProtocol"}],"url":"\/documentation\/divar\/loginrequiredprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/logCustomerInspectionSecondaryButton(postToken:)":{"role":"symbol","title":"logCustomerInspectionSecondaryButton(postToken:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logCustomerInspectionSecondaryButton"},{"kind":"text","text":"("},{"kind":"externalParam","text":"postToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/logCustomerInspectionSecondaryButton(postToken:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/logcustomerinspectionsecondarybutton(posttoken:)"},"doc://com.Divar.DivarClient/documentation/Divar/DealerFlowController":{"role":"symbol","title":"DealerFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DealerFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DealerFlowController"}],"url":"\/documentation\/divar\/dealerflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MarketPlaceFlowController":{"role":"symbol","title":"MarketPlaceFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketPlaceFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketPlaceFlowController"}],"url":"\/documentation\/divar\/marketplaceflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/logInspectionReportSecondaryButton(postToken:)":{"role":"symbol","title":"logInspectionReportSecondaryButton(postToken:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logInspectionReportSecondaryButton"},{"kind":"text","text":"("},{"kind":"externalParam","text":"postToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/logInspectionReportSecondaryButton(postToken:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/loginspectionreportsecondarybutton(posttoken:)"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/IVFlowController":{"role":"symbol","title":"IVFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IVFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IVFlowController"}],"url":"\/documentation\/divar\/ivflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/NationalIdVerificationFlowController":{"role":"symbol","title":"NationalIdVerificationFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NationalIdVerificationFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NationalIdVerificationFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NationalIdVerificationFlowController"}],"url":"\/documentation\/divar\/nationalidverificationflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostDetailsFlowController":{"role":"symbol","title":"PostDetailsFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostDetailsFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostDetailsFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostDetailsFlowController"}],"url":"\/documentation\/divar\/postdetailsflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/RateViewControllerDelegate":{"role":"symbol","title":"RateViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RateViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RateViewControllerDelegate"}],"url":"\/documentation\/divar\/rateviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/CarSpecsFlowController":{"role":"symbol","title":"CarSpecsFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarSpecsFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarSpecsFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarSpecsFlowController"}],"url":"\/documentation\/divar\/carspecsflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController":{"role":"symbol","title":"FormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FormFlowController"}],"url":"\/documentation\/divar\/formflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/navigationController":{"role":"symbol","title":"navigationController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/navigationController","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/navigationcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController":{"role":"symbol","title":"BaseFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseFlowController"}],"url":"\/documentation\/divar\/baseflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CategoryHierarchyControllerDelegate":{"role":"symbol","title":"CategoryHierarchyControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CategoryHierarchyControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CategoryHierarchyControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CategoryHierarchyControllerDelegate"}],"url":"\/documentation\/divar\/categoryhierarchycontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/TestPhoneNumberFlowController":{"role":"symbol","title":"TestPhoneNumberFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TestPhoneNumberFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TestPhoneNumberFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TestPhoneNumberFlowController"}],"url":"\/documentation\/divar\/testphonenumberflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/container":{"role":"symbol","title":"container","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseFlowDIContainer","preciseIdentifier":"s:5Divar19BaseFlowDIContainera"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/container","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/container"},"doc://com.Divar.DivarClient/documentation/Divar/LandingPageFlowController":{"role":"symbol","title":"LandingPageFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandingPageFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandingPageFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandingPageFlowController"}],"url":"\/documentation\/divar\/landingpageflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/configuration":{"role":"symbol","title":"configuration","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IntroConfig","preciseIdentifier":"s:5Divar11IntroConfigV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/configuration","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/configuration"},"doc://com.Divar.DivarClient/documentation/Divar/CarInspectionFlowController":{"role":"symbol","title":"CarInspectionFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarInspectionFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarInspectionFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarInspectionFlowController"}],"url":"\/documentation\/divar\/carinspectionflowcontroller"},"doc://com.Divar.DivarClient/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/MarketplacePriceFlowController":{"role":"symbol","title":"MarketplacePriceFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketplacePriceFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplacePriceFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketplacePriceFlowController"}],"url":"\/documentation\/divar\/marketplacepriceflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MFMessageFlowController":{"role":"symbol","title":"MFMessageFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MFMessageFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MFMessageFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MFMessageFlowController"}],"url":"\/documentation\/divar\/mfmessageflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SaleAssistantFlowController":{"role":"symbol","title":"SaleAssistantFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SaleAssistantFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SaleAssistantFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SaleAssistantFlowController"}],"url":"\/documentation\/divar\/saleassistantflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AgentManagementFlowController":{"role":"symbol","title":"AgentManagementFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgentManagementFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AgentManagementFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgentManagementFlowController"}],"url":"\/documentation\/divar\/agentmanagementflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/CategoryHierarchyControllerDelegate-Implementations":{"role":"collectionGroup","title":"CategoryHierarchyControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/CategoryHierarchyControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/categoryhierarchycontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/LandlineVerificationFlowControllerDelegate":{"role":"symbol","title":"LandlineVerificationFlowControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandlineVerificationFlowControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandlineVerificationFlowControllerDelegate"}],"url":"\/documentation\/divar\/landlineverificationflowcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/BrowseFlowController":{"role":"symbol","title":"BrowseFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrowseFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BrowseFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BrowseFlowController"}],"url":"\/documentation\/divar\/browseflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BulkLadderBaseFlowController":{"role":"symbol","title":"BulkLadderBaseFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BulkLadderBaseFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BulkLadderBaseFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BulkLadderBaseFlowController"}],"url":"\/documentation\/divar\/bulkladderbaseflowcontroller"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/OpenPageFlowController":{"role":"symbol","title":"OpenPageFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenPageFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OpenPageFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenPageFlowController"}],"url":"\/documentation\/divar\/openpageflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/LinkFlowController":{"role":"symbol","title":"LinkFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LinkFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LinkFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LinkFlowController"}],"url":"\/documentation\/divar\/linkflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SubmitPromotionFlowController":{"role":"symbol","title":"SubmitPromotionFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubmitPromotionFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SubmitPromotionFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SubmitPromotionFlowController"}],"url":"\/documentation\/divar\/submitpromotionflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostListFlowController":{"role":"symbol","title":"PostListFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostListFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostListFlowController"}],"url":"\/documentation\/divar\/postlistflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/PostCreateViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"PostCreateViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/PostCreateViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/postcreateviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/TransactionFlowController":{"role":"symbol","title":"TransactionFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransactionFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransactionFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TransactionFlowController"}],"url":"\/documentation\/divar\/transactionflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/DealershipGetContactFlowController":{"role":"symbol","title":"DealershipGetContactFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DealershipGetContactFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealershipGetContactFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DealershipGetContactFlowController"}],"url":"\/documentation\/divar\/dealershipgetcontactflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/RealEstateFlowController":{"role":"symbol","title":"RealEstateFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RealEstateFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RealEstateFlowController"}],"url":"\/documentation\/divar\/realestateflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/actionDispatcher":{"role":"symbol","title":"actionDispatcher","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionDispatcher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActionDispatcherProtocol","preciseIdentifier":"s:5Divar24ActionDispatcherProtocolP"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/actionDispatcher","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/actiondispatcher"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/WidgetBasedActionDelegate-Implementations":{"role":"collectionGroup","title":"WidgetBasedActionDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/WidgetBasedActionDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/widgetbasedactiondelegate-implementations"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/initialViewController()":{"role":"symbol","title":"initialViewController()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialViewController"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/initialViewController()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/initialviewcontroller()"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/CityMultiSelectViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"CityMultiSelectViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/CityMultiSelectViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/citymultiselectviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/navigationController(_:)":{"role":"symbol","title":"navigationController(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/navigationController(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/navigationcontroller(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/PostArchiveViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"PostArchiveViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/PostArchiveViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/baseflowcontroller\/postarchiveviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/FeaturedPostsFlowController":{"role":"symbol","title":"FeaturedPostsFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeaturedPostsFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeaturedPostsFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeaturedPostsFlowController"}],"url":"\/documentation\/divar\/featuredpostsflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostCreateViewControllerDelegate":{"role":"symbol","title":"PostCreateViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostCreateViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostCreateViewControllerDelegate"}],"url":"\/documentation\/divar\/postcreateviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/JobsFlowController":{"role":"symbol","title":"JobsFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JobsFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JobsFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JobsFlowController"}],"url":"\/documentation\/divar\/jobsflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController/performCustomAction(action:)":{"role":"symbol","title":"performCustomAction(action:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"performCustomAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CustomAction","preciseIdentifier":"s:5Divar12CustomActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController\/performCustomAction(action:)","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/divar\/baseflowcontroller\/performcustomaction(action:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"BaseFlowController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"BaseFlowController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"BaseFlowController"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AgentManagementFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BrowseFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BulkLadderBaseFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarInspectionFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarSpecsFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealershipGetContactFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeaturedPostsFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JobsFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/KalaDetailsFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandingPageFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LinkFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MFMessageFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplacePriceFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceQuickEditPostFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceRegisterFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NationalIdVerificationFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OpenPageFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OperatorManagementFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostDetailsFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SaleAssistantFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SettingsFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShahkarLandlineVerificationFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SubmitPromotionFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TestPhoneNumberFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransactionFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UserRegisterFlowController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFlowController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MyDivarHolderFlowController\/title","value":"MyDivarHolderFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MyDivarHolderFlowController\/fragments","value":[{"kind":"identifier","text":"MyDivarHolderFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandlineVerificationFlowController\/title","value":"LandlineVerificationFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandlineVerificationFlowController\/fragments","value":[{"kind":"identifier","text":"LandlineVerificationFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OperatorManagementFlowController\/title","value":"OperatorManagementFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OperatorManagementFlowController\/fragments","value":[{"kind":"identifier","text":"OperatorManagementFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceQuickEditPostFlowController\/title","value":"MarketplaceQuickEditPostFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceQuickEditPostFlowController\/fragments","value":[{"kind":"identifier","text":"MarketplaceQuickEditPostFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentFlowController\/title","value":"CarAgentFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentFlowController\/fragments","value":[{"kind":"identifier","text":"CarAgentFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceRegisterFlowController\/title","value":"MarketplaceRegisterFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceRegisterFlowController\/fragments","value":[{"kind":"identifier","text":"MarketplaceRegisterFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostManageFlowController\/title","value":"PostManageFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostManageFlowController\/fragments","value":[{"kind":"identifier","text":"PostManageFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatFlowController\/title","value":"ChatFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatFlowController\/fragments","value":[{"kind":"identifier","text":"ChatFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1UserRegisterFlowController\/title","value":"UserRegisterFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1UserRegisterFlowController\/fragments","value":[{"kind":"identifier","text":"UserRegisterFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1KalaDetailsFlowController\/title","value":"KalaDetailsFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1KalaDetailsFlowController\/fragments","value":[{"kind":"identifier","text":"KalaDetailsFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SettingsFlowController\/title","value":"SettingsFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SettingsFlowController\/fragments","value":[{"kind":"identifier","text":"SettingsFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ShahkarLandlineVerificationFlowController\/title","value":"ShahkarLandlineVerificationFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ShahkarLandlineVerificationFlowController\/fragments","value":[{"kind":"identifier","text":"ShahkarLandlineVerificationFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarBusinessFlowController\/title","value":"CarBusinessFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarBusinessFlowController\/fragments","value":[{"kind":"identifier","text":"CarBusinessFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerFlowController\/title","value":"DealerFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerFlowController\/fragments","value":[{"kind":"identifier","text":"DealerFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketPlaceFlowController\/title","value":"MarketPlaceFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketPlaceFlowController\/fragments","value":[{"kind":"identifier","text":"MarketPlaceFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1IVFlowController\/title","value":"IVFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1IVFlowController\/fragments","value":[{"kind":"identifier","text":"IVFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NationalIdVerificationFlowController\/title","value":"NationalIdVerificationFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NationalIdVerificationFlowController\/fragments","value":[{"kind":"identifier","text":"NationalIdVerificationFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostDetailsFlowController\/title","value":"PostDetailsFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostDetailsFlowController\/fragments","value":[{"kind":"identifier","text":"PostDetailsFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarSpecsFlowController\/title","value":"CarSpecsFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarSpecsFlowController\/fragments","value":[{"kind":"identifier","text":"CarSpecsFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FormFlowController\/title","value":"FormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FormFlowController\/fragments","value":[{"kind":"identifier","text":"FormFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/title","value":"BaseFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/fragments","value":[{"kind":"identifier","text":"BaseFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TestPhoneNumberFlowController\/title","value":"TestPhoneNumberFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TestPhoneNumberFlowController\/fragments","value":[{"kind":"identifier","text":"TestPhoneNumberFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandingPageFlowController\/title","value":"LandingPageFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandingPageFlowController\/fragments","value":[{"kind":"identifier","text":"LandingPageFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarInspectionFlowController\/title","value":"CarInspectionFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarInspectionFlowController\/fragments","value":[{"kind":"identifier","text":"CarInspectionFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplacePriceFlowController\/title","value":"MarketplacePriceFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplacePriceFlowController\/fragments","value":[{"kind":"identifier","text":"MarketplacePriceFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MFMessageFlowController\/title","value":"MFMessageFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MFMessageFlowController\/fragments","value":[{"kind":"identifier","text":"MFMessageFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SaleAssistantFlowController\/title","value":"SaleAssistantFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SaleAssistantFlowController\/fragments","value":[{"kind":"identifier","text":"SaleAssistantFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AgentManagementFlowController\/title","value":"AgentManagementFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AgentManagementFlowController\/fragments","value":[{"kind":"identifier","text":"AgentManagementFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BrowseFlowController\/title","value":"BrowseFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BrowseFlowController\/fragments","value":[{"kind":"identifier","text":"BrowseFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BulkLadderBaseFlowController\/title","value":"BulkLadderBaseFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BulkLadderBaseFlowController\/fragments","value":[{"kind":"identifier","text":"BulkLadderBaseFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OpenPageFlowController\/title","value":"OpenPageFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OpenPageFlowController\/fragments","value":[{"kind":"identifier","text":"OpenPageFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LinkFlowController\/title","value":"LinkFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LinkFlowController\/fragments","value":[{"kind":"identifier","text":"LinkFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SubmitPromotionFlowController\/title","value":"SubmitPromotionFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SubmitPromotionFlowController\/fragments","value":[{"kind":"identifier","text":"SubmitPromotionFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListFlowController\/title","value":"PostListFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListFlowController\/fragments","value":[{"kind":"identifier","text":"PostListFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TransactionFlowController\/title","value":"TransactionFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TransactionFlowController\/fragments","value":[{"kind":"identifier","text":"TransactionFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealershipGetContactFlowController\/title","value":"DealershipGetContactFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealershipGetContactFlowController\/fragments","value":[{"kind":"identifier","text":"DealershipGetContactFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateFlowController\/title","value":"RealEstateFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateFlowController\/fragments","value":[{"kind":"identifier","text":"RealEstateFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeaturedPostsFlowController\/title","value":"FeaturedPostsFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeaturedPostsFlowController\/fragments","value":[{"kind":"identifier","text":"FeaturedPostsFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JobsFlowController\/title","value":"JobsFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JobsFlowController\/fragments","value":[{"kind":"identifier","text":"JobsFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}