{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFormControllerProtocol"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/baseformcontrollerprotocol"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddEditAgentViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddSalesmanViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddStoreManagerViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddUserTransactionFormViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddVRViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BooleanRateFormViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BusinessSubscriptionViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BuyBulkLadderViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentBuyLadderPackageViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentBuyPackageViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentSubmitViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarInspectionRegisterViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarInspectionSubmitViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CreateAndEditOperatorViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubmitViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/EditMarketplaceStoreViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JobsSubmitViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketpalceFeedbackViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceEditAssistantViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceQuickEditPostVC","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceSubmitViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceSubscriptionViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OfflineFormViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateRegistrationViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateSubmitViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RegisterAgentViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RegisterDealerViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RegisterMarketplaceViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SchemaFormViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScreenWidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchFilterViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SendFeedbackViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UsedPriceFormViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedFilterViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/bottomBarType","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/documentHelper-25h9o","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/draft-6x4ea","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/finishActionType-21gr2","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/needsDependencyRefresh-4t827","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/needsResetButton-5u9d3","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/nextButtonTitle-5lqan","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/reloadFormTitle-8v1og","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/shouldCloseOnFinish-5a94z","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/shouldDraft-9c451","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/shouldShowSuccessMessage-7w5j9","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/submitButtonTitle-g0xm","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/successEditMessage-91ns0","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/successSubmitMessage-74ywf","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/twinSecondaryTitle-41v5r"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/saveDraft()-6xltc","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/setupBottomStackView()-8mpp5"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFormControllerProtocol"}],"title":"BaseFormControllerProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar26BaseFormControllerProtocolP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"BaseFormControllerProtocol"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/BooleanRateFormViewController":{"role":"symbol","title":"BooleanRateFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BooleanRateFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BooleanRateFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BooleanRateFormViewController"}],"url":"\/documentation\/divar\/booleanrateformviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormControllerProtocol/nextButtonTitle-5lqan":{"defaultImplementations":1,"role":"symbol","title":"nextButtonTitle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextButtonTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/nextButtonTitle-5lqan","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/baseformcontrollerprotocol\/nextbuttontitle-5lqan"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormControllerProtocol/needsDependencyRefresh-4t827":{"defaultImplementations":1,"role":"symbol","title":"needsDependencyRefresh","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"needsDependencyRefresh"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/needsDependencyRefresh-4t827","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/baseformcontrollerprotocol\/needsdependencyrefresh-4t827"},"doc://com.Divar.DivarClient/documentation/Divar/CreateAndEditOperatorViewController":{"role":"symbol","title":"CreateAndEditOperatorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateAndEditOperatorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CreateAndEditOperatorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CreateAndEditOperatorViewController"}],"url":"\/documentation\/divar\/createandeditoperatorviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormControllerProtocol":{"role":"symbol","title":"BaseFormControllerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFormControllerProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseFormControllerProtocol"}],"url":"\/documentation\/divar\/baseformcontrollerprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/JobsSubmitViewController":{"role":"symbol","title":"JobsSubmitViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JobsSubmitViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JobsSubmitViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JobsSubmitViewController"}],"url":"\/documentation\/divar\/jobssubmitviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MarketplaceSubscriptionViewController":{"role":"symbol","title":"MarketplaceSubscriptionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketplaceSubscriptionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceSubscriptionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketplaceSubscriptionViewController"}],"url":"\/documentation\/divar\/marketplacesubscriptionviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormControllerProtocol/finishActionType-21gr2":{"defaultImplementations":1,"role":"symbol","title":"finishActionType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"finishActionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormActionType","preciseIdentifier":"s:5Divar14FormActionTypeO"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/finishActionType-21gr2","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/baseformcontrollerprotocol\/finishactiontype-21gr2"},"doc://com.Divar.DivarClient/documentation/Divar/RegisterDealerViewController":{"role":"symbol","title":"RegisterDealerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RegisterDealerViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RegisterDealerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RegisterDealerViewController"}],"url":"\/documentation\/divar\/registerdealerviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BusinessSubscriptionViewController":{"role":"symbol","title":"BusinessSubscriptionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BusinessSubscriptionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BusinessSubscriptionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BusinessSubscriptionViewController"}],"url":"\/documentation\/divar\/businesssubscriptionviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormControllerProtocol/reloadFormTitle-8v1og":{"defaultImplementations":1,"role":"symbol","title":"reloadFormTitle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reloadFormTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/reloadFormTitle-8v1og","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/baseformcontrollerprotocol\/reloadformtitle-8v1og"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormControllerProtocol/documentHelper-25h9o":{"defaultImplementations":1,"role":"symbol","title":"documentHelper","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentHelper"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentHelperProtocol","preciseIdentifier":"s:5Divar22DocumentHelperProtocolP"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/documentHelper-25h9o","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/baseformcontrollerprotocol\/documenthelper-25h9o"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormControllerProtocol/successEditMessage-91ns0":{"defaultImplementations":1,"role":"symbol","title":"successEditMessage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"successEditMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/successEditMessage-91ns0","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/baseformcontrollerprotocol\/successeditmessage-91ns0"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedFilterViewController":{"role":"symbol","title":"WidgetBasedFilterViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedFilterViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedFilterViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedFilterViewController"}],"url":"\/documentation\/divar\/widgetbasedfilterviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BuyBulkLadderViewController":{"role":"symbol","title":"BuyBulkLadderViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BuyBulkLadderViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BuyBulkLadderViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BuyBulkLadderViewController"}],"url":"\/documentation\/divar\/buybulkladderviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarAgentBuyLadderPackageViewController":{"role":"symbol","title":"CarAgentBuyLadderPackageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarAgentBuyLadderPackageViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentBuyLadderPackageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarAgentBuyLadderPackageViewController"}],"url":"\/documentation\/divar\/caragentbuyladderpackageviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormControllerProtocol/saveDraft()-6xltc":{"defaultImplementations":1,"role":"symbol","title":"saveDraft()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"saveDraft"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/saveDraft()-6xltc","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/baseformcontrollerprotocol\/savedraft()-6xltc"},"doc://com.Divar.DivarClient/documentation/Divar/SchemaFormViewController":{"role":"symbol","title":"SchemaFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SchemaFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SchemaFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SchemaFormViewController"}],"url":"\/documentation\/divar\/schemaformviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarAgentSubmitViewController":{"role":"symbol","title":"CarAgentSubmitViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarAgentSubmitViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentSubmitViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarAgentSubmitViewController"}],"url":"\/documentation\/divar\/caragentsubmitviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormControllerProtocol/shouldCloseOnFinish-5a94z":{"defaultImplementations":1,"role":"symbol","title":"shouldCloseOnFinish","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldCloseOnFinish"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/shouldCloseOnFinish-5a94z","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/baseformcontrollerprotocol\/shouldcloseonfinish-5a94z"},"doc://com.Divar.DivarClient/documentation/Divar/MarketplaceEditAssistantViewController":{"role":"symbol","title":"MarketplaceEditAssistantViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketplaceEditAssistantViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceEditAssistantViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketplaceEditAssistantViewController"}],"url":"\/documentation\/divar\/marketplaceeditassistantviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormControllerProtocol/shouldDraft-9c451":{"defaultImplementations":1,"role":"symbol","title":"shouldDraft","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldDraft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/shouldDraft-9c451","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/baseformcontrollerprotocol\/shoulddraft-9c451"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormControllerProtocol/submitButtonTitle-g0xm":{"defaultImplementations":1,"role":"symbol","title":"submitButtonTitle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"submitButtonTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/submitButtonTitle-g0xm","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/baseformcontrollerprotocol\/submitbuttontitle-g0xm"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormControllerProtocol/setupBottomStackView()-8mpp5":{"defaultImplementations":1,"role":"symbol","title":"setupBottomStackView()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupBottomStackView"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/setupBottomStackView()-8mpp5","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/baseformcontrollerprotocol\/setupbottomstackview()-8mpp5"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormControllerProtocol/successSubmitMessage-74ywf":{"defaultImplementations":1,"role":"symbol","title":"successSubmitMessage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"successSubmitMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/successSubmitMessage-74ywf","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/baseformcontrollerprotocol\/successsubmitmessage-74ywf"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormControllerProtocol/twinSecondaryTitle-41v5r":{"defaultImplementations":1,"role":"symbol","title":"twinSecondaryTitle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"twinSecondaryTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/twinSecondaryTitle-41v5r","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/baseformcontrollerprotocol\/twinsecondarytitle-41v5r"},"doc://com.Divar.DivarClient/documentation/Divar/CarAgentBuyPackageViewController":{"role":"symbol","title":"CarAgentBuyPackageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarAgentBuyPackageViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentBuyPackageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarAgentBuyPackageViewController"}],"url":"\/documentation\/divar\/caragentbuypackageviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormControllerProtocol/shouldShowSuccessMessage-7w5j9":{"defaultImplementations":1,"role":"symbol","title":"shouldShowSuccessMessage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldShowSuccessMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/shouldShowSuccessMessage-7w5j9","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/baseformcontrollerprotocol\/shouldshowsuccessmessage-7w5j9"},"doc://com.Divar.DivarClient/documentation/Divar/ScreenWidgetViewController":{"role":"symbol","title":"ScreenWidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScreenWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScreenWidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScreenWidgetViewController"}],"url":"\/documentation\/divar\/screenwidgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AddStoreManagerViewController":{"role":"symbol","title":"AddStoreManagerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddStoreManagerViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddStoreManagerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddStoreManagerViewController"}],"url":"\/documentation\/divar\/addstoremanagerviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AddEditAgentViewController":{"role":"symbol","title":"AddEditAgentViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddEditAgentViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddEditAgentViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddEditAgentViewController"}],"url":"\/documentation\/divar\/addeditagentviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/RegisterAgentViewController":{"role":"symbol","title":"RegisterAgentViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RegisterAgentViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RegisterAgentViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RegisterAgentViewController"}],"url":"\/documentation\/divar\/registeragentviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AddUserTransactionFormViewController":{"role":"symbol","title":"AddUserTransactionFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddUserTransactionFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddUserTransactionFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddUserTransactionFormViewController"}],"url":"\/documentation\/divar\/addusertransactionformviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/RealEstateSubmitViewController":{"role":"symbol","title":"RealEstateSubmitViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RealEstateSubmitViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateSubmitViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RealEstateSubmitViewController"}],"url":"\/documentation\/divar\/realestatesubmitviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/DealerSubmitViewController":{"role":"symbol","title":"DealerSubmitViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DealerSubmitViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubmitViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DealerSubmitViewController"}],"url":"\/documentation\/divar\/dealersubmitviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarInspectionSubmitViewController":{"role":"symbol","title":"CarInspectionSubmitViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarInspectionSubmitViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarInspectionSubmitViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarInspectionSubmitViewController"}],"url":"\/documentation\/divar\/carinspectionsubmitviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarInspectionRegisterViewController":{"role":"symbol","title":"CarInspectionRegisterViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarInspectionRegisterViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarInspectionRegisterViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarInspectionRegisterViewController"}],"url":"\/documentation\/divar\/carinspectionregisterviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/EditMarketplaceStoreViewController":{"role":"symbol","title":"EditMarketplaceStoreViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EditMarketplaceStoreViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/EditMarketplaceStoreViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EditMarketplaceStoreViewController"}],"url":"\/documentation\/divar\/editmarketplacestoreviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/RealEstateRegistrationViewController":{"role":"symbol","title":"RealEstateRegistrationViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RealEstateRegistrationViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateRegistrationViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RealEstateRegistrationViewController"}],"url":"\/documentation\/divar\/realestateregistrationviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormControllerProtocol/draft-6x4ea":{"defaultImplementations":1,"role":"symbol","title":"draft","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"draft"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/draft-6x4ea","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/baseformcontrollerprotocol\/draft-6x4ea"},"doc://com.Divar.DivarClient/documentation/Divar/SearchFilterViewController":{"role":"symbol","title":"SearchFilterViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchFilterViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchFilterViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchFilterViewController"}],"url":"\/documentation\/divar\/searchfilterviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MarketplaceQuickEditPostVC":{"role":"symbol","title":"MarketplaceQuickEditPostVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketplaceQuickEditPostVC"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceQuickEditPostVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketplaceQuickEditPostVC"}],"url":"\/documentation\/divar\/marketplacequickeditpostvc"},"doc://com.Divar.DivarClient/documentation/Divar/MarketplaceSubmitViewController":{"role":"symbol","title":"MarketplaceSubmitViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketplaceSubmitViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceSubmitViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketplaceSubmitViewController"}],"url":"\/documentation\/divar\/marketplacesubmitviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MarketpalceFeedbackViewController":{"role":"symbol","title":"MarketpalceFeedbackViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketpalceFeedbackViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketpalceFeedbackViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketpalceFeedbackViewController"}],"url":"\/documentation\/divar\/marketpalcefeedbackviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AddSalesmanViewController":{"role":"symbol","title":"AddSalesmanViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddSalesmanViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddSalesmanViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddSalesmanViewController"}],"url":"\/documentation\/divar\/addsalesmanviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/RegisterMarketplaceViewController":{"role":"symbol","title":"RegisterMarketplaceViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RegisterMarketplaceViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RegisterMarketplaceViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RegisterMarketplaceViewController"}],"url":"\/documentation\/divar\/registermarketplaceviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostCreateViewController":{"role":"symbol","title":"PostCreateViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostCreateViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostCreateViewController"}],"url":"\/documentation\/divar\/postcreateviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SendFeedbackViewController":{"role":"symbol","title":"SendFeedbackViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SendFeedbackViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SendFeedbackViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SendFeedbackViewController"}],"url":"\/documentation\/divar\/sendfeedbackviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/UsedPriceFormViewController":{"role":"symbol","title":"UsedPriceFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsedPriceFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UsedPriceFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UsedPriceFormViewController"}],"url":"\/documentation\/divar\/usedpriceformviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/OfflineFormViewController":{"role":"symbol","title":"OfflineFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OfflineFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OfflineFormViewController"}],"url":"\/documentation\/divar\/offlineformviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormControllerProtocol/bottomBarType":{"role":"symbol","title":"bottomBarType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomBarType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseFormBottomBarType","preciseIdentifier":"s:5Divar21BaseFormBottomBarTypeO"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/bottomBarType","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/baseformcontrollerprotocol\/bottombartype"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormControllerProtocol/needsResetButton-5u9d3":{"defaultImplementations":1,"role":"symbol","title":"needsResetButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"needsResetButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormControllerProtocol\/needsResetButton-5u9d3","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/baseformcontrollerprotocol\/needsresetbutton-5u9d3"},"doc://com.Divar.DivarClient/documentation/Divar/AddVRViewController":{"role":"symbol","title":"AddVRViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddVRViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddVRViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddVRViewController"}],"url":"\/documentation\/divar\/addvrviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BooleanRateFormViewController\/title","value":"BooleanRateFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BooleanRateFormViewController\/fragments","value":[{"kind":"identifier","text":"BooleanRateFormViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CreateAndEditOperatorViewController\/title","value":"CreateAndEditOperatorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CreateAndEditOperatorViewController\/fragments","value":[{"kind":"identifier","text":"CreateAndEditOperatorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JobsSubmitViewController\/title","value":"JobsSubmitViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JobsSubmitViewController\/fragments","value":[{"kind":"identifier","text":"JobsSubmitViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceSubscriptionViewController\/title","value":"MarketplaceSubscriptionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceSubscriptionViewController\/fragments","value":[{"kind":"identifier","text":"MarketplaceSubscriptionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RegisterDealerViewController\/title","value":"RegisterDealerViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RegisterDealerViewController\/fragments","value":[{"kind":"identifier","text":"RegisterDealerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BusinessSubscriptionViewController\/title","value":"BusinessSubscriptionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BusinessSubscriptionViewController\/fragments","value":[{"kind":"identifier","text":"BusinessSubscriptionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedFilterViewController\/title","value":"WidgetBasedFilterViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedFilterViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedFilterViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BuyBulkLadderViewController\/title","value":"BuyBulkLadderViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BuyBulkLadderViewController\/fragments","value":[{"kind":"identifier","text":"BuyBulkLadderViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentBuyLadderPackageViewController\/title","value":"CarAgentBuyLadderPackageViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentBuyLadderPackageViewController\/fragments","value":[{"kind":"identifier","text":"CarAgentBuyLadderPackageViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SchemaFormViewController\/title","value":"SchemaFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SchemaFormViewController\/fragments","value":[{"kind":"identifier","text":"SchemaFormViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentSubmitViewController\/title","value":"CarAgentSubmitViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentSubmitViewController\/fragments","value":[{"kind":"identifier","text":"CarAgentSubmitViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceEditAssistantViewController\/title","value":"MarketplaceEditAssistantViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceEditAssistantViewController\/fragments","value":[{"kind":"identifier","text":"MarketplaceEditAssistantViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentBuyPackageViewController\/title","value":"CarAgentBuyPackageViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentBuyPackageViewController\/fragments","value":[{"kind":"identifier","text":"CarAgentBuyPackageViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScreenWidgetViewController\/title","value":"ScreenWidgetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScreenWidgetViewController\/fragments","value":[{"kind":"identifier","text":"ScreenWidgetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddStoreManagerViewController\/title","value":"AddStoreManagerViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddStoreManagerViewController\/fragments","value":[{"kind":"identifier","text":"AddStoreManagerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddEditAgentViewController\/title","value":"AddEditAgentViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddEditAgentViewController\/fragments","value":[{"kind":"identifier","text":"AddEditAgentViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RegisterAgentViewController\/title","value":"RegisterAgentViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RegisterAgentViewController\/fragments","value":[{"kind":"identifier","text":"RegisterAgentViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddUserTransactionFormViewController\/title","value":"AddUserTransactionFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddUserTransactionFormViewController\/fragments","value":[{"kind":"identifier","text":"AddUserTransactionFormViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateSubmitViewController\/title","value":"RealEstateSubmitViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateSubmitViewController\/fragments","value":[{"kind":"identifier","text":"RealEstateSubmitViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubmitViewController\/title","value":"DealerSubmitViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubmitViewController\/fragments","value":[{"kind":"identifier","text":"DealerSubmitViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarInspectionSubmitViewController\/title","value":"CarInspectionSubmitViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarInspectionSubmitViewController\/fragments","value":[{"kind":"identifier","text":"CarInspectionSubmitViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarInspectionRegisterViewController\/title","value":"CarInspectionRegisterViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarInspectionRegisterViewController\/fragments","value":[{"kind":"identifier","text":"CarInspectionRegisterViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1EditMarketplaceStoreViewController\/title","value":"EditMarketplaceStoreViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1EditMarketplaceStoreViewController\/fragments","value":[{"kind":"identifier","text":"EditMarketplaceStoreViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateRegistrationViewController\/title","value":"RealEstateRegistrationViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateRegistrationViewController\/fragments","value":[{"kind":"identifier","text":"RealEstateRegistrationViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchFilterViewController\/title","value":"SearchFilterViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchFilterViewController\/fragments","value":[{"kind":"identifier","text":"SearchFilterViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceQuickEditPostVC\/title","value":"MarketplaceQuickEditPostVC"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceQuickEditPostVC\/fragments","value":[{"kind":"identifier","text":"MarketplaceQuickEditPostVC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceSubmitViewController\/title","value":"MarketplaceSubmitViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceSubmitViewController\/fragments","value":[{"kind":"identifier","text":"MarketplaceSubmitViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketpalceFeedbackViewController\/title","value":"MarketpalceFeedbackViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketpalceFeedbackViewController\/fragments","value":[{"kind":"identifier","text":"MarketpalceFeedbackViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddSalesmanViewController\/title","value":"AddSalesmanViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddSalesmanViewController\/fragments","value":[{"kind":"identifier","text":"AddSalesmanViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RegisterMarketplaceViewController\/title","value":"RegisterMarketplaceViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RegisterMarketplaceViewController\/fragments","value":[{"kind":"identifier","text":"RegisterMarketplaceViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostCreateViewController\/title","value":"PostCreateViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostCreateViewController\/fragments","value":[{"kind":"identifier","text":"PostCreateViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SendFeedbackViewController\/title","value":"SendFeedbackViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SendFeedbackViewController\/fragments","value":[{"kind":"identifier","text":"SendFeedbackViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1UsedPriceFormViewController\/title","value":"UsedPriceFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1UsedPriceFormViewController\/fragments","value":[{"kind":"identifier","text":"UsedPriceFormViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OfflineFormViewController\/title","value":"OfflineFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OfflineFormViewController\/fragments","value":[{"kind":"identifier","text":"OfflineFormViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddVRViewController\/title","value":"AddVRViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddVRViewController\/fragments","value":[{"kind":"identifier","text":"AddVRViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}