{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BlockingViewDelegate"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/blockingviewdelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatInstructLoginViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ForceUpdateViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BlockingViewDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BlockingViewDelegate\/didTap(onBlockingView:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BlockingViewDelegate"}],"title":"BlockingViewDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar20BlockingViewDelegateP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"BlockingViewDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/ForceUpdateViewController":{"role":"symbol","title":"ForceUpdateViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ForceUpdateViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ForceUpdateViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ForceUpdateViewController"}],"url":"\/documentation\/divar\/forceupdateviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatInstructLoginViewController":{"role":"symbol","title":"ChatInstructLoginViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatInstructLoginViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatInstructLoginViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatInstructLoginViewController"}],"url":"\/documentation\/divar\/chatinstructloginviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BlockingViewDelegate/didTap(onBlockingView:)":{"role":"symbol","title":"didTap(onBlockingView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTap"},{"kind":"text","text":"("},{"kind":"externalParam","text":"onBlockingView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BlockingViewDelegate\/didTap(onBlockingView:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/blockingviewdelegate\/didtap(onblockingview:)"},"doc://com.Divar.DivarClient/documentation/Divar/BlockingViewDelegate":{"role":"symbol","title":"BlockingViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BlockingViewDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BlockingViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BlockingViewDelegate"}],"url":"\/documentation\/divar\/blockingviewdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ForceUpdateViewController\/title","value":"ForceUpdateViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ForceUpdateViewController\/fragments","value":[{"kind":"identifier","text":"ForceUpdateViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatInstructLoginViewController\/title","value":"ChatInstructLoginViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatInstructLoginViewController\/fragments","value":[{"kind":"identifier","text":"ChatInstructLoginViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}