{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BookmarksViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/bookmarksviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/bookmarksviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","doc:\/\/com.Divar.DivarClient\/6Sonnat0A22CollectionViewDelegateP","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController\/init(container:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController\/deleteBookmark(postToken:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController\/handleLongPress(gestureRecognizer:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController\/logOpeningPost(index:token:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController\/viewDidLoad()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController\/viewWillAppear(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController\/SonnatCollectionViewDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BookmarksViewController"}],"title":"BookmarksViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)BookmarksViewController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"BookmarksViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarksViewController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BookmarksViewControllerDelegate","preciseIdentifier":"s:5Divar31BookmarksViewControllerDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bookmarksviewcontroller\/delegate"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarksViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/bookmarksviewcontroller\/viewdidload()"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarksViewController/logOpeningPost(index:token:)":{"role":"symbol","title":"logOpeningPost(index:token:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logOpeningPost"},{"kind":"text","text":"("},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController\/logOpeningPost(index:token:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bookmarksviewcontroller\/logopeningpost(index:token:)"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/documentation/Divar/TooltipPresenter":{"role":"symbol","title":"TooltipPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TooltipPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TooltipPresenter"}],"url":"\/documentation\/divar\/tooltippresenter"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/ShowMessageProtocol":{"role":"symbol","title":"ShowMessageProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowMessageProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowMessageProtocol"}],"url":"\/documentation\/divar\/showmessageprotocol"},"doc://com.Divar.DivarClient/objc(pl)UIGestureRecognizerDelegate":{"type":"unresolvable","title":"UIKit.UIGestureRecognizerDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIGestureRecognizerDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController":{"role":"symbol","title":"BaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseViewController"}],"url":"\/documentation\/divar\/baseviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarksViewController":{"role":"symbol","title":"BookmarksViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BookmarksViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BookmarksViewController"}],"url":"\/documentation\/divar\/bookmarksviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ErrorMessageHandler":{"role":"symbol","title":"ErrorMessageHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorMessageHandler"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorMessageHandler"}],"url":"\/documentation\/divar\/errormessagehandler"},"doc://com.Divar.DivarClient/6Sonnat0A22CollectionViewDelegateP":{"type":"unresolvable","title":"Sonnat.SonnatCollectionViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat0A22CollectionViewDelegateP"},"doc://com.Divar.DivarClient/documentation/Divar/PaymentSystemProtocol":{"role":"symbol","title":"PaymentSystemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSystemProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaymentSystemProtocol"}],"url":"\/documentation\/divar\/paymentsystemprotocol"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarksViewController/handleLongPress(gestureRecognizer:)":{"role":"symbol","title":"handleLongPress(gestureRecognizer:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleLongPress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"gestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILongPressGestureRecognizer","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController\/handleLongPress(gestureRecognizer:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"handleLongPressWithGestureRecognizer:"}],"url":"\/documentation\/divar\/bookmarksviewcontroller\/handlelongpress(gesturerecognizer:)"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarksViewController/deleteBookmark(postToken:)":{"role":"symbol","title":"deleteBookmark(postToken:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteBookmark"},{"kind":"text","text":"("},{"kind":"externalParam","text":"postToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController\/deleteBookmark(postToken:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteBookmarkWithPostToken:"}],"url":"\/documentation\/divar\/bookmarksviewcontroller\/deletebookmark(posttoken:)"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarksViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/bookmarksviewcontroller\/init(coder:)"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarksViewController/init(container:)":{"role":"symbol","title":"init(container:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BookmarksViewControllerDIContainer","preciseIdentifier":"s:5Divar34BookmarksViewControllerDIContainera"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController\/init(container:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bookmarksviewcontroller\/init(container:)"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarksViewController/SonnatCollectionViewDelegate-Implementations":{"role":"collectionGroup","title":"SonnatCollectionViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController\/SonnatCollectionViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/bookmarksviewcontroller\/sonnatcollectionviewdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/ShowErrorProtocol":{"role":"symbol","title":"ShowErrorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowErrorProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowErrorProtocol"}],"url":"\/documentation\/divar\/showerrorprotocol"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarksViewController/viewWillAppear(_:)":{"role":"symbol","title":"viewWillAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController\/viewWillAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"url":"\/documentation\/divar\/bookmarksviewcontroller\/viewwillappear(_:)"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"BookmarksViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"BookmarksViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"BookmarksViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController\/deleteBookmark(postToken:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController\/handleLongPress(gestureRecognizer:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController\/viewDidLoad()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewController\/viewWillAppear(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"BookmarksViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController","preciseIdentifier":"c:@M@Divar@objc(cs)BaseViewController","text":"BaseViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarksViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarksViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController\/title","value":"BaseViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController\/fragments","value":[{"kind":"identifier","text":"BaseViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarksViewController\/title","value":"BookmarksViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarksViewController\/fragments","value":[{"kind":"identifier","text":"BookmarksViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarksViewController~1handleLongPress(gestureRecognizer:)\/title","value":"handleLongPressWithGestureRecognizer:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarksViewController~1handleLongPress(gestureRecognizer:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleLongPressWithGestureRecognizer:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarksViewController~1deleteBookmark(postToken:)\/title","value":"deleteBookmarkWithPostToken:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarksViewController~1deleteBookmark(postToken:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteBookmarkWithPostToken:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarksViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarksViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarksViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarksViewController~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}