{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BookmarkView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/bookmarkview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/bookmarkview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/objc(pl)CAAnimationDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)CALayerDelegate","doc:\/\/com.Divar.DivarClient\/6Sonnat23WithInitializerProtocolP","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearance","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UICoordinateSpace","doc:\/\/com.Divar.DivarClient\/objc(pl)UIDynamicItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItemContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UILargeContentViewerItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/init(frame:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/animationGroup","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/delegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/filledBookmarkShape","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/insideBookmarkShape"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/addAction(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/animationDidStop(_:finished:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/bookmarkToInProgress(duration:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/changeColor(from:to:duration:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/drawBookMark()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/filledScaleUpAndDown(duration:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/inProgressToBookmark(isBookmark:duration:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/insideView(hidden:duration:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/setBookmark(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/traitCollectionDidChange(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/unBookmarkToInprogress(duration:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BookmarkView"}],"title":"BookmarkView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)BookmarkView","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"BookmarkView"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarkView/animationDidStop(_:finished:)":{"role":"symbol","title":"animationDidStop(_:finished:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationDidStop"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CAAnimation","preciseIdentifier":"c:objc(cs)CAAnimation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"finished"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/animationDidStop(_:finished:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animationDidStop:finished:"}],"url":"\/documentation\/divar\/bookmarkview\/animationdidstop(_:finished:)"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIDynamicItem"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarkView/setBookmark(_:)":{"role":"symbol","title":"setBookmark(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBookmark"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/setBookmark(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bookmarkview\/setbookmark(_:)"},"doc://com.Divar.DivarClient/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.Divar.DivarClient/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAccessibilityIdentification"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarkView":{"role":"symbol","title":"BookmarkView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BookmarkView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BookmarkView"}],"url":"\/documentation\/divar\/bookmarkview"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarkView/filledScaleUpAndDown(duration:)":{"role":"symbol","title":"filledScaleUpAndDown(duration:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"filledScaleUpAndDown"},{"kind":"text","text":"("},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/filledScaleUpAndDown(duration:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bookmarkview\/filledscaleupanddown(duration:)"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarkView/insideBookmarkShape":{"role":"symbol","title":"insideBookmarkShape","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"insideBookmarkShape"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CAShapeLayer","preciseIdentifier":"c:objc(cs)CAShapeLayer"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/insideBookmarkShape","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bookmarkview\/insidebookmarkshape"},"doc://com.Divar.DivarClient/6Sonnat23WithInitializerProtocolP":{"type":"unresolvable","title":"Sonnat.WithInitializerProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat23WithInitializerProtocolP"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarkView/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BookmarkViewDelegate","preciseIdentifier":"s:5Divar20BookmarkViewDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bookmarkview\/delegate"},"doc://com.Divar.DivarClient/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearance"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarkView/init(frame:)":{"role":"symbol","title":"init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/init(frame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/divar\/bookmarkview\/init(frame:)"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarkView/addAction(_:)":{"role":"symbol","title":"addAction(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addAction"},{"kind":"text","text":"(() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/addAction(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bookmarkview\/addaction(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarkView/filledBookmarkShape":{"role":"symbol","title":"filledBookmarkShape","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"filledBookmarkShape"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CAShapeLayer","preciseIdentifier":"c:objc(cs)CAShapeLayer"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/filledBookmarkShape","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bookmarkview\/filledbookmarkshape"},"doc://com.Divar.DivarClient/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)UIView"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarkView/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/bookmarkview\/init(coder:)"},"doc://com.Divar.DivarClient/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)CALayerDelegate"},"doc://com.Divar.DivarClient/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UICoordinateSpace"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarkView/insideView(hidden:duration:)":{"role":"symbol","title":"insideView(hidden:duration:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insideView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hidden"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/insideView(hidden:duration:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bookmarkview\/insideview(hidden:duration:)"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarkView/drawBookMark()":{"role":"symbol","title":"drawBookMark()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"drawBookMark"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/drawBookMark()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bookmarkview\/drawbookmark()"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarkView/unBookmarkToInprogress(duration:)":{"role":"symbol","title":"unBookmarkToInprogress(duration:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unBookmarkToInprogress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/unBookmarkToInprogress(duration:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bookmarkview\/unbookmarktoinprogress(duration:)"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarkView/inProgressToBookmark(isBookmark:duration:)":{"role":"symbol","title":"inProgressToBookmark(isBookmark:duration:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"inProgressToBookmark"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isBookmark"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/inProgressToBookmark(isBookmark:duration:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bookmarkview\/inprogresstobookmark(isbookmark:duration:)"},"doc://com.Divar.DivarClient/objc(pl)CAAnimationDelegate":{"type":"unresolvable","title":"CAAnimationDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)CAAnimationDelegate"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItem"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UILargeContentViewerItem"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarkView/animationGroup":{"role":"symbol","title":"animationGroup","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationGroup"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DispatchGroup","preciseIdentifier":"c:objc(cs)OS_dispatch_group"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/animationGroup","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bookmarkview\/animationgroup"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarkView/changeColor(from:to:duration:)":{"role":"symbol","title":"changeColor(from:to:duration:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeColor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/changeColor(from:to:duration:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bookmarkview\/changecolor(from:to:duration:)"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarkView/bookmarkToInProgress(duration:)":{"role":"symbol","title":"bookmarkToInProgress(duration:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bookmarkToInProgress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/bookmarkToInProgress(duration:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bookmarkview\/bookmarktoinprogress(duration:)"},"doc://com.Divar.DivarClient/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItemContainer"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarkView/traitCollectionDidChange(_:)":{"role":"symbol","title":"traitCollectionDidChange(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"traitCollectionDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/traitCollectionDidChange(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"traitCollectionDidChange:"}],"url":"\/documentation\/divar\/bookmarkview\/traitcollectiondidchange(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"BookmarkView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"BookmarkView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"BookmarkView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/animationDidStop(_:finished:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/init(frame:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView\/traitCollectionDidChange(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)CAAnimationDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"BookmarkView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarkView~1animationDidStop(_:finished:)\/title","value":"animationDidStop:finished:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarkView~1animationDidStop(_:finished:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animationDidStop:finished:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarkView\/title","value":"BookmarkView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarkView\/fragments","value":[{"kind":"identifier","text":"BookmarkView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarkView~1init(frame:)\/title","value":"initWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarkView~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarkView~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarkView~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarkView~1traitCollectionDidChange(_:)\/title","value":"traitCollectionDidChange:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarkView~1traitCollectionDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"traitCollectionDidChange:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}