{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BottomSheetViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/bottomsheetviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/bottomsheetviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetEurekaViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedBottomSheetViewController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/6Sonnat32FlowLayoutWithAnimationsDelegateP","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UICollectionViewDataSource","doc:\/\/com.Divar.DivarClient\/objc(pl)UICollectionViewDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIScrollViewDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/init(title:bannerModel:alignment:allowTapToDismiss:allowDragToDismiss:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/allowsDragToDismiss-3i6m2","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/allowsTapToDismiss-99g8g","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/banner-6zw81","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/collectionView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/cornerRadius-7r1rl","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/headerView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/longFormHeight-4qrja","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/panScrollable","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/shortFormHeight-rgoh","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/shouldRoundTopCorners-1pmv","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/titleLabel","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/titleStringHeight","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/titleView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/addItem(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/addItems(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/traitCollectionDidChange(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/FlowLayoutWithAnimationsDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/PanModalPresentable-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/UICollectionViewDataSource-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/UICollectionViewDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BottomSheetViewController"}],"title":"BottomSheetViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)BottomSheetViewController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"BottomSheetViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController/allowsDragToDismiss-3i6m2":{"role":"symbol","title":"allowsDragToDismiss","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsDragToDismiss"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/allowsDragToDismiss-3i6m2","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bottomsheetviewcontroller\/allowsdragtodismiss-3i6m2"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController/panScrollable":{"role":"symbol","title":"panScrollable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"panScrollable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/panScrollable","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bottomsheetviewcontroller\/panscrollable"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController/shouldRoundTopCorners-1pmv":{"role":"symbol","title":"shouldRoundTopCorners","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldRoundTopCorners"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/shouldRoundTopCorners-1pmv","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bottomsheetviewcontroller\/shouldroundtopcorners-1pmv"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable":{"role":"symbol","title":"PanModalPresentable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresentable"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresentable"}],"url":"\/documentation\/divar\/panmodalpresentable"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetEurekaViewController":{"role":"symbol","title":"BottomSheetEurekaViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BottomSheetEurekaViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetEurekaViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BottomSheetEurekaViewController"}],"url":"\/documentation\/divar\/bottomsheeteurekaviewcontroller"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController/cornerRadius-7r1rl":{"role":"symbol","title":"cornerRadius","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/cornerRadius-7r1rl","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bottomsheetviewcontroller\/cornerradius-7r1rl"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController/longFormHeight-4qrja":{"role":"symbol","title":"longFormHeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"longFormHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PanModalHeight","preciseIdentifier":"s:5Divar14PanModalHeightO"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/longFormHeight-4qrja","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bottomsheetviewcontroller\/longformheight-4qrja"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController/titleLabel":{"role":"symbol","title":"titleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/titleLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleLabel"}],"url":"\/documentation\/divar\/bottomsheetviewcontroller\/titlelabel"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController/FlowLayoutWithAnimationsDelegate-Implementations":{"role":"collectionGroup","title":"FlowLayoutWithAnimationsDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/FlowLayoutWithAnimationsDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/bottomsheetviewcontroller\/flowlayoutwithanimationsdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController/shortFormHeight-rgoh":{"role":"symbol","title":"shortFormHeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shortFormHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PanModalHeight","preciseIdentifier":"s:5Divar14PanModalHeightO"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/shortFormHeight-rgoh","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bottomsheetviewcontroller\/shortformheight-rgoh"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController/UICollectionViewDelegate-Implementations":{"role":"collectionGroup","title":"UICollectionViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/UICollectionViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/bottomsheetviewcontroller\/uicollectionviewdelegate-implementations"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController/collectionView":{"role":"symbol","title":"collectionView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/collectionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView"}],"url":"\/documentation\/divar\/bottomsheetviewcontroller\/collectionview"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController/titleStringHeight":{"role":"symbol","title":"titleStringHeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleStringHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/titleStringHeight","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bottomsheetviewcontroller\/titlestringheight"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController/banner-6zw81":{"role":"symbol","title":"banner","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"banner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PanModalBannerCompatible","preciseIdentifier":"s:5Divar24PanModalBannerCompatibleP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/banner-6zw81","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bottomsheetviewcontroller\/banner-6zw81"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/objc(pl)UICollectionViewDelegate":{"type":"unresolvable","title":"UIKit.UICollectionViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UICollectionViewDelegate"},"doc://com.Divar.DivarClient/6Sonnat32FlowLayoutWithAnimationsDelegateP":{"type":"unresolvable","title":"Sonnat.FlowLayoutWithAnimationsDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat32FlowLayoutWithAnimationsDelegateP"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/bottomsheetviewcontroller\/init(coder:)"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController/allowsTapToDismiss-99g8g":{"role":"symbol","title":"allowsTapToDismiss","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsTapToDismiss"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/allowsTapToDismiss-99g8g","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bottomsheetviewcontroller\/allowstaptodismiss-99g8g"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController/headerView":{"role":"symbol","title":"headerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/headerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"headerView"}],"url":"\/documentation\/divar\/bottomsheetviewcontroller\/headerview"},"doc://com.Divar.DivarClient/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIScrollViewDelegate"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedBottomSheetViewController":{"role":"symbol","title":"WidgetBasedBottomSheetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedBottomSheetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedBottomSheetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedBottomSheetViewController"}],"url":"\/documentation\/divar\/widgetbasedbottomsheetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController/init(title:bannerModel:alignment:allowTapToDismiss:allowDragToDismiss:)":{"role":"symbol","title":"init(title:bannerModel:alignment:allowTapToDismiss:allowDragToDismiss:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"bannerModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SheetBannerModel","preciseIdentifier":"s:5Divar16SheetBannerModelV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"alignment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSTextAlignment","preciseIdentifier":"c:@E@NSTextAlignment"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowTapToDismiss"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowDragToDismiss"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/init(title:bannerModel:alignment:allowTapToDismiss:allowDragToDismiss:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bottomsheetviewcontroller\/init(title:bannermodel:alignment:allowtaptodismiss:allowdragtodismiss:)"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController/addItem(_:)":{"role":"symbol","title":"addItem(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addItem"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SheetItem","preciseIdentifier":"s:5Divar9SheetItemV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/addItem(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bottomsheetviewcontroller\/additem(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController/traitCollectionDidChange(_:)":{"role":"symbol","title":"traitCollectionDidChange(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"traitCollectionDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/traitCollectionDidChange(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"traitCollectionDidChange:"}],"url":"\/documentation\/divar\/bottomsheetviewcontroller\/traitcollectiondidchange(_:)"},"doc://com.Divar.DivarClient/objc(pl)UICollectionViewDataSource":{"type":"unresolvable","title":"UIKit.UICollectionViewDataSource","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UICollectionViewDataSource"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/bottomsheetviewcontroller\/viewdidload()"},"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController/titleView":{"role":"symbol","title":"titleView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/titleView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleView"}],"url":"\/documentation\/divar\/bottomsheetviewcontroller\/titleview"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController/UICollectionViewDataSource-Implementations":{"role":"collectionGroup","title":"UICollectionViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/UICollectionViewDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/bottomsheetviewcontroller\/uicollectionviewdatasource-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController":{"role":"symbol","title":"BottomSheetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BottomSheetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BottomSheetViewController"}],"url":"\/documentation\/divar\/bottomsheetviewcontroller"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)UIViewController"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController/addItems(_:)":{"role":"symbol","title":"addItems(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addItems"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"SheetItem","preciseIdentifier":"s:5Divar9SheetItemV"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/addItems(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bottomsheetviewcontroller\/additems(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController/PanModalPresentable-Implementations":{"role":"collectionGroup","title":"PanModalPresentable Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/PanModalPresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/bottomsheetviewcontroller\/panmodalpresentable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"BottomSheetViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"BottomSheetViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"BottomSheetViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/collectionView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/headerView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/titleLabel","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/titleView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/traitCollectionDidChange(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/UICollectionViewDataSource-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController\/UICollectionViewDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetEurekaViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedBottomSheetViewController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"BottomSheetViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetEurekaViewController\/title","value":"BottomSheetEurekaViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetEurekaViewController\/fragments","value":[{"kind":"identifier","text":"BottomSheetEurekaViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetViewController~1titleLabel\/title","value":"titleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetViewController~1titleLabel\/fragments","value":[{"kind":"identifier","text":"titleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetViewController~1collectionView\/title","value":"collectionView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetViewController~1collectionView\/fragments","value":[{"kind":"identifier","text":"collectionView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetViewController~1headerView\/title","value":"headerView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetViewController~1headerView\/fragments","value":[{"kind":"identifier","text":"headerView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedBottomSheetViewController\/title","value":"WidgetBasedBottomSheetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedBottomSheetViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedBottomSheetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetViewController~1traitCollectionDidChange(_:)\/title","value":"traitCollectionDidChange:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetViewController~1traitCollectionDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"traitCollectionDidChange:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetViewController~1titleView\/title","value":"titleView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetViewController~1titleView\/fragments","value":[{"kind":"identifier","text":"titleView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetViewController\/title","value":"BottomSheetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetViewController\/fragments","value":[{"kind":"identifier","text":"BottomSheetViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}