{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallObserverServiceImpl"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/callobserverserviceimpl"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/callobserverserviceimpl"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)CXCallObserverDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CallObserverService","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CallObserverServiceImpl","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CallObserverServiceImpl\/init(callObserver:initialCallState:initialCallComplementaryState:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CallObserverServiceImpl\/stateChangePublisher"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CallObserverServiceImpl\/callObserver(_:callChanged:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CallObserverServiceImpl\/detectComplementaryState(from:newState:last:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallObserverServiceImpl"}],"title":"CallObserverServiceImpl","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)CallObserverServiceImpl","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"CallObserverServiceImpl"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/objc(pl)CXCallObserverDelegate":{"type":"unresolvable","title":"CXCallObserverDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)CXCallObserverDelegate"},"doc://com.Divar.DivarClient/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/CallObserverServiceImpl/callObserver(_:callChanged:)":{"role":"symbol","title":"callObserver(_:callChanged:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"callObserver"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CXCallObserver","preciseIdentifier":"c:objc(cs)CXCallObserver"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CXCall","preciseIdentifier":"c:objc(cs)CXCall"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CallObserverServiceImpl\/callObserver(_:callChanged:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"callObserver:callChanged:"}],"url":"\/documentation\/divar\/callobserverserviceimpl\/callobserver(_:callchanged:)"},"doc://com.Divar.DivarClient/documentation/Divar/CallObserverServiceImpl/init(callObserver:initialCallState:initialCallComplementaryState:)":{"role":"symbol","title":"init(callObserver:initialCallState:initialCallComplementaryState:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callObserver"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CXCallObserver","preciseIdentifier":"c:objc(cs)CXCallObserver"},{"kind":"text","text":", "},{"kind":"externalParam","text":"initialCallState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CallObserverServiceCallState","preciseIdentifier":"s:5Divar019CallObserverServiceB5StateO"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"initialCallComplementaryState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CallObserverServiceComplementaryState","preciseIdentifier":"s:5Divar37CallObserverServiceComplementaryStateO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CallObserverServiceImpl\/init(callObserver:initialCallState:initialCallComplementaryState:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/callobserverserviceimpl\/init(callobserver:initialcallstate:initialcallcomplementarystate:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/CallObserverServiceImpl":{"role":"symbol","title":"CallObserverServiceImpl","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallObserverServiceImpl"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CallObserverServiceImpl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallObserverServiceImpl"}],"url":"\/documentation\/divar\/callobserverserviceimpl"},"doc://com.Divar.DivarClient/documentation/Divar/CallObserverServiceImpl/stateChangePublisher":{"role":"symbol","title":"stateChangePublisher","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stateChangePublisher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CallObserverServiceStateChangeResult","preciseIdentifier":"s:5Divar36CallObserverServiceStateChangeResultV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CallObserverServiceImpl\/stateChangePublisher","kind":"symbol","type":"topic","url":"\/documentation\/divar\/callobserverserviceimpl\/statechangepublisher"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/CallObserverService":{"role":"symbol","title":"CallObserverService","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallObserverService"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CallObserverService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallObserverService"}],"url":"\/documentation\/divar\/callobserverservice"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/CallObserverServiceImpl/detectComplementaryState(from:newState:last:)":{"role":"symbol","title":"detectComplementaryState(from:newState:last:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectComplementaryState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CallObserverServiceCallState","preciseIdentifier":"s:5Divar019CallObserverServiceB5StateO"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"newState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CallObserverServiceCallState","preciseIdentifier":"s:5Divar019CallObserverServiceB5StateO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"last"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CallObserverServiceComplementaryState","preciseIdentifier":"s:5Divar37CallObserverServiceComplementaryStateO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CallObserverServiceComplementaryState","preciseIdentifier":"s:5Divar37CallObserverServiceComplementaryStateO"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CallObserverServiceImpl\/detectComplementaryState(from:newState:last:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/callobserverserviceimpl\/detectcomplementarystate(from:newstate:last:)"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CallObserverServiceImpl"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CallObserverServiceImpl"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CallObserverServiceImpl"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CallObserverServiceImpl\/callObserver(_:callChanged:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)CXCallObserverDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallObserverServiceImpl"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CallObserverServiceImpl~1callObserver(_:callChanged:)\/title","value":"callObserver:callChanged:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CallObserverServiceImpl~1callObserver(_:callChanged:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"callObserver:callChanged:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CallObserverServiceImpl\/title","value":"CallObserverServiceImpl"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CallObserverServiceImpl\/fragments","value":[{"kind":"identifier","text":"CallObserverServiceImpl"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}