{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraOverlayView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/cameraoverlayview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/cameraoverlayview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/objc(pl)CALayerDelegate","doc:\/\/com.Divar.DivarClient\/6Sonnat23WithInitializerProtocolP","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearance","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UICoordinateSpace","doc:\/\/com.Divar.DivarClient\/objc(pl)UIDynamicItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItemContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UILargeContentViewerItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/init(frame:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/init(frame:initialRemainingTime:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/closeButton","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/contentView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/countdownTimer","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/delegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/flashButton","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/isFlashOn","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/isRecording","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/recordButton","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/remainingTime","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/timerLabel","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/timerView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/startCountdownTimer()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/stopCountdownTimer()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/timerTicks()"]},{"title":"Enumerations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/TapSound"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraOverlayView"}],"title":"CameraOverlayView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)CameraOverlayView","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"CameraOverlayView"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayView/remainingTime":{"role":"symbol","title":"remainingTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remainingTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/remainingTime","kind":"symbol","type":"topic","url":"\/documentation\/divar\/cameraoverlayview\/remainingtime"},"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayView/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraOverlayDelegate","preciseIdentifier":"s:5Divar21CameraOverlayDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/cameraoverlayview\/delegate"},"doc://com.Divar.DivarClient/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItemContainer"},"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayView/countdownTimer":{"role":"symbol","title":"countdownTimer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"countdownTimer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SwiftTimer","preciseIdentifier":"s:5Divar10SwiftTimerC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/countdownTimer","kind":"symbol","type":"topic","url":"\/documentation\/divar\/cameraoverlayview\/countdowntimer"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayView/TapSound":{"role":"symbol","title":"CameraOverlayView.TapSound","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TapSound"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/TapSound","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TapSound"}],"url":"\/documentation\/divar\/cameraoverlayview\/tapsound"},"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayView/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/cameraoverlayview\/init(coder:)"},"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayView/flashButton":{"role":"symbol","title":"flashButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"flashButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/flashButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"flashButton"}],"url":"\/documentation\/divar\/cameraoverlayview\/flashbutton"},"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayView/isFlashOn":{"role":"symbol","title":"isFlashOn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFlashOn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/isFlashOn","kind":"symbol","type":"topic","url":"\/documentation\/divar\/cameraoverlayview\/isflashon"},"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayView":{"role":"symbol","title":"CameraOverlayView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraOverlayView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraOverlayView"}],"url":"\/documentation\/divar\/cameraoverlayview"},"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayView/timerView":{"role":"symbol","title":"timerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/timerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"timerView"}],"url":"\/documentation\/divar\/cameraoverlayview\/timerview"},"doc://com.Divar.DivarClient/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIDynamicItem"},"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayView/recordButton":{"role":"symbol","title":"recordButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/recordButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"recordButton"}],"url":"\/documentation\/divar\/cameraoverlayview\/recordbutton"},"doc://com.Divar.DivarClient/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)CALayerDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayView/contentView":{"role":"symbol","title":"contentView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/contentView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contentView"}],"url":"\/documentation\/divar\/cameraoverlayview\/contentview"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayView/timerLabel":{"role":"symbol","title":"timerLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timerLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/timerLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"timerLabel"}],"url":"\/documentation\/divar\/cameraoverlayview\/timerlabel"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayView/init(frame:initialRemainingTime:)":{"role":"symbol","title":"init(frame:initialRemainingTime:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"initialRemainingTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/init(frame:initialRemainingTime:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/cameraoverlayview\/init(frame:initialremainingtime:)"},"doc://com.Divar.DivarClient/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UILargeContentViewerItem"},"doc://com.Divar.DivarClient/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearance"},"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayView/closeButton":{"role":"symbol","title":"closeButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/closeButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"closeButton"}],"url":"\/documentation\/divar\/cameraoverlayview\/closebutton"},"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayView/init(frame:)":{"role":"symbol","title":"init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/init(frame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/divar\/cameraoverlayview\/init(frame:)"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItem"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UICoordinateSpace"},"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayView/isRecording":{"role":"symbol","title":"isRecording","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRecording"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/isRecording","kind":"symbol","type":"topic","url":"\/documentation\/divar\/cameraoverlayview\/isrecording"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/6Sonnat23WithInitializerProtocolP":{"type":"unresolvable","title":"Sonnat.WithInitializerProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat23WithInitializerProtocolP"},"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayView/stopCountdownTimer()":{"role":"symbol","title":"stopCountdownTimer()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopCountdownTimer"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/stopCountdownTimer()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/cameraoverlayview\/stopcountdowntimer()"},"doc://com.Divar.DivarClient/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAccessibilityIdentification"},"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayView/timerTicks()":{"role":"symbol","title":"timerTicks()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"timerTicks"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/timerTicks()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/cameraoverlayview\/timerticks()"},"doc://com.Divar.DivarClient/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)UIView"},"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayView/startCountdownTimer()":{"role":"symbol","title":"startCountdownTimer()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCountdownTimer"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/startCountdownTimer()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/cameraoverlayview\/startcountdowntimer()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CameraOverlayView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CameraOverlayView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CameraOverlayView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/closeButton","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/contentView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/flashButton","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/recordButton","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/timerLabel","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/timerView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView\/init(frame:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraOverlayView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CameraOverlayView~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CameraOverlayView~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CameraOverlayView~1flashButton\/title","value":"flashButton"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CameraOverlayView~1flashButton\/fragments","value":[{"kind":"identifier","text":"flashButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CameraOverlayView\/title","value":"CameraOverlayView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CameraOverlayView\/fragments","value":[{"kind":"identifier","text":"CameraOverlayView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CameraOverlayView~1timerView\/title","value":"timerView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CameraOverlayView~1timerView\/fragments","value":[{"kind":"identifier","text":"timerView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CameraOverlayView~1recordButton\/title","value":"recordButton"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CameraOverlayView~1recordButton\/fragments","value":[{"kind":"identifier","text":"recordButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CameraOverlayView~1contentView\/title","value":"contentView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CameraOverlayView~1contentView\/fragments","value":[{"kind":"identifier","text":"contentView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CameraOverlayView~1timerLabel\/title","value":"timerLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CameraOverlayView~1timerLabel\/fragments","value":[{"kind":"identifier","text":"timerLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CameraOverlayView~1closeButton\/title","value":"closeButton"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CameraOverlayView~1closeButton\/fragments","value":[{"kind":"identifier","text":"closeButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CameraOverlayView~1init(frame:)\/title","value":"initWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CameraOverlayView~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}