{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraOverlayDelegate"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/cameraoverlaydelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVVideoRecorderViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoRecorder"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayDelegate\/cameraOverlay(_:didRequestChangeFlashState:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayDelegate\/cameraOverlayDidRequestClose(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayDelegate\/cameraOverlayDidRequestStartRecording(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayDelegate\/cameraOverlayDidRequestStopRecording(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraOverlayDelegate"}],"title":"CameraOverlayDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar21CameraOverlayDelegateP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"CameraOverlayDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayDelegate/cameraOverlay(_:didRequestChangeFlashState:)":{"role":"symbol","title":"cameraOverlay(_:didRequestChangeFlashState:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraOverlay"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CameraOverlayView","preciseIdentifier":"c:@M@Divar@objc(cs)CameraOverlayView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestChangeFlashState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayDelegate\/cameraOverlay(_:didRequestChangeFlashState:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/cameraoverlaydelegate\/cameraoverlay(_:didrequestchangeflashstate:)"},"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayDelegate/cameraOverlayDidRequestClose(_:)":{"role":"symbol","title":"cameraOverlayDidRequestClose(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraOverlayDidRequestClose"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CameraOverlayView","preciseIdentifier":"c:@M@Divar@objc(cs)CameraOverlayView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayDelegate\/cameraOverlayDidRequestClose(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/cameraoverlaydelegate\/cameraoverlaydidrequestclose(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/VideoRecorder":{"deprecated":true,"role":"symbol","title":"VideoRecorder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoRecorder"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoRecorder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoRecorder"}],"url":"\/documentation\/divar\/videorecorder"},"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayDelegate/cameraOverlayDidRequestStopRecording(_:)":{"role":"symbol","title":"cameraOverlayDidRequestStopRecording(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraOverlayDidRequestStopRecording"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CameraOverlayView","preciseIdentifier":"c:@M@Divar@objc(cs)CameraOverlayView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayDelegate\/cameraOverlayDidRequestStopRecording(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/cameraoverlaydelegate\/cameraoverlaydidrequeststoprecording(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayDelegate/cameraOverlayDidRequestStartRecording(_:)":{"role":"symbol","title":"cameraOverlayDidRequestStartRecording(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraOverlayDidRequestStartRecording"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CameraOverlayView","preciseIdentifier":"c:@M@Divar@objc(cs)CameraOverlayView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayDelegate\/cameraOverlayDidRequestStartRecording(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/cameraoverlaydelegate\/cameraoverlaydidrequeststartrecording(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayDelegate":{"role":"symbol","title":"CameraOverlayDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraOverlayDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraOverlayDelegate"}],"url":"\/documentation\/divar\/cameraoverlaydelegate"},"doc://com.Divar.DivarClient/documentation/Divar/IVVideoRecorderViewController":{"role":"symbol","title":"IVVideoRecorderViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IVVideoRecorderViewController"}],"abstract":[{"type":"text","text":"Present this controller to record video from camera"}],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVVideoRecorderViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IVVideoRecorderViewController"}],"url":"\/documentation\/divar\/ivvideorecorderviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VideoRecorder\/title","value":"VideoRecorder"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VideoRecorder\/fragments","value":[{"kind":"identifier","text":"VideoRecorder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1IVVideoRecorderViewController\/title","value":"IVVideoRecorderViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1IVVideoRecorderViewController\/fragments","value":[{"kind":"identifier","text":"IVVideoRecorderViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}