{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarBusinessFlowController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/carbusinessflowcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/carbusinessflowcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessActionHandler","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CategoryHierarchyControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CityMultiSelectViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionDetailsViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LoginRequiredProtocol","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchFilterViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedActionDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController\/openCarConciergeSaleRegisterPromotion(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController\/openCarDealersDisablePostsPage(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController\/openDealerBulkLadder(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController\/openDealershipCarDealersList(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController\/openPlanDetails(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController\/openPriceReport(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController\/openPurchaseSubscription(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController\/openSubscriptionManagement(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController\/DealerSubscriptionDetailsViewControllerDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarBusinessFlowController"}],"title":"CarBusinessFlowController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)CarBusinessFlowController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"CarBusinessFlowController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController":{"role":"symbol","title":"BaseFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseFlowController"}],"url":"\/documentation\/divar\/baseflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarBusinessFlowController/openSubscriptionManagement(_:)":{"role":"symbol","title":"openSubscriptionManagement(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openSubscriptionManagement"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController\/openSubscriptionManagement(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/carbusinessflowcontroller\/opensubscriptionmanagement(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/CarBusinessActionHandler":{"role":"symbol","title":"CarBusinessActionHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarBusinessActionHandler"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessActionHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarBusinessActionHandler"}],"url":"\/documentation\/divar\/carbusinessactionhandler"},"doc://com.Divar.DivarClient/documentation/Divar/LandlineVerificationFlowControllerDelegate":{"role":"symbol","title":"LandlineVerificationFlowControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandlineVerificationFlowControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandlineVerificationFlowControllerDelegate"}],"url":"\/documentation\/divar\/landlineverificationflowcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedActionDelegate":{"role":"symbol","title":"WidgetBasedActionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedActionDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedActionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedActionDelegate"}],"url":"\/documentation\/divar\/widgetbasedactiondelegate"},"doc://com.Divar.DivarClient/documentation/Divar/CarBusinessFlowController/DealerSubscriptionDetailsViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"DealerSubscriptionDetailsViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController\/DealerSubscriptionDetailsViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/carbusinessflowcontroller\/dealersubscriptiondetailsviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PostCreateViewControllerDelegate":{"role":"symbol","title":"PostCreateViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostCreateViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostCreateViewControllerDelegate"}],"url":"\/documentation\/divar\/postcreateviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewControllerDelegate":{"role":"symbol","title":"PostArchiveViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostArchiveViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostArchiveViewControllerDelegate"}],"url":"\/documentation\/divar\/postarchiveviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/CarBusinessFlowController":{"role":"symbol","title":"CarBusinessFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarBusinessFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarBusinessFlowController"}],"url":"\/documentation\/divar\/carbusinessflowcontroller"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/CarBusinessFlowController/openPlanDetails(_:)":{"role":"symbol","title":"openPlanDetails(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openPlanDetails"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController\/openPlanDetails(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/carbusinessflowcontroller\/openplandetails(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/SearchFilterViewControllerDelegate":{"role":"symbol","title":"SearchFilterViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchFilterViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchFilterViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchFilterViewControllerDelegate"}],"url":"\/documentation\/divar\/searchfilterviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/CityMultiSelectViewControllerDelegate":{"role":"symbol","title":"CityMultiSelectViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CityMultiSelectViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CityMultiSelectViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CityMultiSelectViewControllerDelegate"}],"url":"\/documentation\/divar\/citymultiselectviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/CarBusinessFlowController/openCarConciergeSaleRegisterPromotion(_:)":{"role":"symbol","title":"openCarConciergeSaleRegisterPromotion(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openCarConciergeSaleRegisterPromotion"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController\/openCarConciergeSaleRegisterPromotion(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/carbusinessflowcontroller\/opencarconciergesaleregisterpromotion(_:)"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/DealerSubscriptionDetailsViewControllerDelegate":{"role":"symbol","title":"DealerSubscriptionDetailsViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DealerSubscriptionDetailsViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionDetailsViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DealerSubscriptionDetailsViewControllerDelegate"}],"url":"\/documentation\/divar\/dealersubscriptiondetailsviewcontrollerdelegate"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/CarBusinessFlowController/openPurchaseSubscription(_:)":{"role":"symbol","title":"openPurchaseSubscription(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openPurchaseSubscription"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController\/openPurchaseSubscription(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/carbusinessflowcontroller\/openpurchasesubscription(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/RateViewControllerDelegate":{"role":"symbol","title":"RateViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RateViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RateViewControllerDelegate"}],"url":"\/documentation\/divar\/rateviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/CarBusinessFlowController/openDealershipCarDealersList(_:)":{"role":"symbol","title":"openDealershipCarDealersList(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openDealershipCarDealersList"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController\/openDealershipCarDealersList(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/carbusinessflowcontroller\/opendealershipcardealerslist(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/CarBusinessFlowController/openCarDealersDisablePostsPage(_:)":{"role":"symbol","title":"openCarDealersDisablePostsPage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openCarDealersDisablePostsPage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController\/openCarDealersDisablePostsPage(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/carbusinessflowcontroller\/opencardealersdisablepostspage(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/CarBusinessFlowController/openDealerBulkLadder(_:)":{"role":"symbol","title":"openDealerBulkLadder(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openDealerBulkLadder"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController\/openDealerBulkLadder(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/carbusinessflowcontroller\/opendealerbulkladder(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/CarBusinessFlowController/openPriceReport(_:)":{"role":"symbol","title":"openPriceReport(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openPriceReport"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController\/openPriceReport(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/carbusinessflowcontroller\/openpricereport(_:)"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/CategoryHierarchyControllerDelegate":{"role":"symbol","title":"CategoryHierarchyControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CategoryHierarchyControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CategoryHierarchyControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CategoryHierarchyControllerDelegate"}],"url":"\/documentation\/divar\/categoryhierarchycontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/LoginRequiredProtocol":{"role":"symbol","title":"LoginRequiredProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoginRequiredProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LoginRequiredProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LoginRequiredProtocol"}],"url":"\/documentation\/divar\/loginrequiredprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CarBusinessFlowController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CarBusinessFlowController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CarBusinessFlowController"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarBusinessFlowController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","preciseIdentifier":"c:@M@Divar@objc(cs)BaseFlowController","text":"BaseFlowController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/title","value":"BaseFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/fragments","value":[{"kind":"identifier","text":"BaseFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarBusinessFlowController\/title","value":"CarBusinessFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarBusinessFlowController\/fragments","value":[{"kind":"identifier","text":"CarBusinessFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}