{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/chatviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/chatviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdViewViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatOptionActionProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GetSuggestionProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapSelectorViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessageInputAreaViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagePreviewBarViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RefreshableProtocol","doc:\/\/com.Divar.DivarClient\/objc(pl)SFSafariViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SplitButtonBarViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIDocumentPickerDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIImagePickerControllerDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UINavigationControllerDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoPreviewControllerDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/init(container:conversationID:isShowingPostchi:configuration:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/adVC","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/chatTitleView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/configuration","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/container","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/conversation","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/conversationDeactivatedCondition","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/conversationID","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/delegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/getStatusWorkItem","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/isBlocked","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/isConversationNew","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/isInPreviewMode","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/isShowingPostchi","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/messageInputAreaVC","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/messagePreviewBarViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/messagingVC","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/openningViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/post","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/previewingMessage","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/splitBar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/splitBarConfig","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/stackView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/stackViewBottomConstraint","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/suggestions","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/suggestionsVC"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/UserRegisterationChanged()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/closeMessagePreviewBar()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/deleteConversation(conversationId:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/deleteMessageRequest(_:completion:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/didRequestDismissingKeyboard()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/editMessageRequest(_:completion:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/forwardMessage(forwardingMessage:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/getForwardListRequest(_:completion:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/getInitConversation()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/getOnlineStatus(completion:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/getSuggesionRequest()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/handleBlockUnblockEvent()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/handleKeyboardStatus(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/logMenuClickAction()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/logUnblockAction()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/makeCallButtonAction(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/pop()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/prepareMessagePreview(_:forType:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/requestUnblockUser()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/sendMessageRequest(message:image:filePath:location:completion:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/sendTypingEvent(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/setPeerName()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/setupChilds()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/setupConnectionStatusPrompt()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/setupNavigationBarItems()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/setupObservers()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/setupUI()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/showFileSendConfirmationAlert(forURL:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/showOptions()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/showWarning(for:warning:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/showWarningIfExists()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/toggleConnectionStatus()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/togglePeerTypingStatus()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/toggleSplitBar()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/viewDidAppear(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/viewDidLayoutSubviews()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/viewDidLoad()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/viewWillAppear(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/AdViewViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/ChatOptionActionProtocol-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/GetSuggestionProtocol-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/ImagePickerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/MapSelectorViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/MessageInputAreaViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/MessagePreviewBarViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/MessagingViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/RefreshableProtocol-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/SFSafariViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/SplitButtonBarViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/TagListViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/UIDocumentPickerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/UIImagePickerControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/VideoPreviewControllerDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatViewController"}],"title":"ChatViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)ChatViewController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"ChatViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/objc(pl)UINavigationControllerDelegate":{"type":"unresolvable","title":"UIKit.UINavigationControllerDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UINavigationControllerDelegate"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/chatviewcontroller\/init(coder:)"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/configuration":{"role":"symbol","title":"configuration","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IntroConfig","preciseIdentifier":"s:5Divar11IntroConfigV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/configuration","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/configuration"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/chatTitleView":{"role":"symbol","title":"chatTitleView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatTitleView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatNavigationTitleView","preciseIdentifier":"c:@M@Divar@objc(cs)ChatNavigationTitleView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/chatTitleView","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/chattitleview"},"doc://com.Divar.DivarClient/documentation/Divar/ErrorMessageHandler":{"role":"symbol","title":"ErrorMessageHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorMessageHandler"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorMessageHandler"}],"url":"\/documentation\/divar\/errormessagehandler"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/TagListViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"TagListViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/TagListViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/taglistviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/post":{"role":"symbol","title":"post","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"post"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostViewStructure","preciseIdentifier":"s:5Divar17PostViewStructureV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/post","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/post"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatViewControllerDelegate","preciseIdentifier":"s:5Divar26ChatViewControllerDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/delegate"},"doc://com.Divar.DivarClient/documentation/Divar/MessagePreviewBarViewControllerDelegate":{"role":"symbol","title":"MessagePreviewBarViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagePreviewBarViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagePreviewBarViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagePreviewBarViewControllerDelegate"}],"url":"\/documentation\/divar\/messagepreviewbarviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/PaymentSystemProtocol":{"role":"symbol","title":"PaymentSystemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSystemProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaymentSystemProtocol"}],"url":"\/documentation\/divar\/paymentsystemprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewControllerDelegate":{"role":"symbol","title":"MessagingViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagingViewControllerDelegate"}],"url":"\/documentation\/divar\/messagingviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/setupConnectionStatusPrompt()":{"role":"symbol","title":"setupConnectionStatusPrompt()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupConnectionStatusPrompt"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/setupConnectionStatusPrompt()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupConnectionStatusPrompt"}],"url":"\/documentation\/divar\/chatviewcontroller\/setupconnectionstatusprompt()"},"doc://com.Divar.DivarClient/documentation/Divar/VideoPreviewControllerDelegate":{"role":"symbol","title":"VideoPreviewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPreviewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoPreviewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoPreviewControllerDelegate"}],"url":"\/documentation\/divar\/videopreviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/MessageInputAreaViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"MessageInputAreaViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/MessageInputAreaViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/messageinputareaviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/container":{"role":"symbol","title":"container","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatViewControllerDIContainer","preciseIdentifier":"s:5Divar29ChatViewControllerDIContainera"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/container","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/container"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/viewDidLayoutSubviews()":{"role":"symbol","title":"viewDidLayoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLayoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/viewDidLayoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLayoutSubviews"}],"url":"\/documentation\/divar\/chatviewcontroller\/viewdidlayoutsubviews()"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/isInPreviewMode":{"role":"symbol","title":"isInPreviewMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInPreviewMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/isInPreviewMode","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/isinpreviewmode"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/getStatusWorkItem":{"role":"symbol","title":"getStatusWorkItem","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"getStatusWorkItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DispatchWorkItem","preciseIdentifier":"s:8Dispatch0A8WorkItemC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/getStatusWorkItem","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/getstatusworkitem"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/deleteConversation(conversationId:)":{"role":"symbol","title":"deleteConversation(conversationId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteConversation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/deleteConversation(conversationId:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/deleteconversation(conversationid:)"},"doc://com.Divar.DivarClient/objc(pl)SFSafariViewControllerDelegate":{"type":"unresolvable","title":"SafariServices.SFSafariViewControllerDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)SFSafariViewControllerDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/MapSelectorViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"MapSelectorViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/MapSelectorViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/mapselectorviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/SplitButtonBarViewControllerDelegate":{"role":"symbol","title":"SplitButtonBarViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SplitButtonBarViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SplitButtonBarViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SplitButtonBarViewControllerDelegate"}],"url":"\/documentation\/divar\/splitbuttonbarviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/setupChilds()":{"role":"symbol","title":"setupChilds()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupChilds"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/setupChilds()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/setupchilds()"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/isConversationNew":{"role":"symbol","title":"isConversationNew","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isConversationNew"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/isConversationNew","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/isconversationnew"},"doc://com.Divar.DivarClient/documentation/Divar/MessageInputAreaViewControllerDelegate":{"role":"symbol","title":"MessageInputAreaViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageInputAreaViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessageInputAreaViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageInputAreaViewControllerDelegate"}],"url":"\/documentation\/divar\/messageinputareaviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/suggestionsVC":{"role":"symbol","title":"suggestionsVC","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"suggestionsVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagListViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TagListViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/suggestionsVC","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/suggestionsvc"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/isShowingPostchi":{"role":"symbol","title":"isShowingPostchi","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isShowingPostchi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/isShowingPostchi","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/isshowingpostchi"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/deleteMessageRequest(_:completion:)":{"role":"symbol","title":"deleteMessageRequest(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteMessageRequest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CompletionHandlerType","preciseIdentifier":"s:5Divar21CompletionHandlerTypea"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/deleteMessageRequest(_:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/deletemessagerequest(_:completion:)"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/isBlocked":{"role":"symbol","title":"isBlocked","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isBlocked"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/isBlocked","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/isblocked"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/closeMessagePreviewBar()":{"role":"symbol","title":"closeMessagePreviewBar()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeMessagePreviewBar"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/closeMessagePreviewBar()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/closemessagepreviewbar()"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/toggleConnectionStatus()":{"role":"symbol","title":"toggleConnectionStatus()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toggleConnectionStatus"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/toggleConnectionStatus()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"toggleConnectionStatus"}],"url":"\/documentation\/divar\/chatviewcontroller\/toggleconnectionstatus()"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/editMessageRequest(_:completion:)":{"role":"symbol","title":"editMessageRequest(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"editMessageRequest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CompletionHandlerType","preciseIdentifier":"s:5Divar21CompletionHandlerTypea"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/editMessageRequest(_:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/editmessagerequest(_:completion:)"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/getInitConversation()":{"role":"symbol","title":"getInitConversation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getInitConversation"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/getInitConversation()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/getinitconversation()"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/RefreshableProtocol-Implementations":{"role":"collectionGroup","title":"RefreshableProtocol Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/RefreshableProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/refreshableprotocol-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/getSuggesionRequest()":{"role":"symbol","title":"getSuggesionRequest()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSuggesionRequest"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/getSuggesionRequest()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/getsuggesionrequest()"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/MessagingViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"MessagingViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/MessagingViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/messagingviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/ShowMessageProtocol":{"role":"symbol","title":"ShowMessageProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowMessageProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowMessageProtocol"}],"url":"\/documentation\/divar\/showmessageprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/togglePeerTypingStatus()":{"role":"symbol","title":"togglePeerTypingStatus()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"togglePeerTypingStatus"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/togglePeerTypingStatus()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"togglePeerTypingStatus"}],"url":"\/documentation\/divar\/chatviewcontroller\/togglepeertypingstatus()"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/suggestions":{"role":"symbol","title":"suggestions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"suggestions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Suggestion","preciseIdentifier":"s:5Divar10SuggestionV"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/suggestions","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/suggestions"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/AdViewViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"AdViewViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/AdViewViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/adviewviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/sendMessageRequest(message:image:filePath:location:completion:)":{"role":"symbol","title":"sendMessageRequest(message:image:filePath:location:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendMessageRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"filePath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Location","preciseIdentifier":"s:5Divar8LocationV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CompletionHandlerType","preciseIdentifier":"s:5Divar21CompletionHandlerTypea"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/sendMessageRequest(message:image:filePath:location:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/sendmessagerequest(message:image:filepath:location:completion:)"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/MessagePreviewBarViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"MessagePreviewBarViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/MessagePreviewBarViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/messagepreviewbarviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/splitBarConfig":{"role":"symbol","title":"splitBarConfig","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"splitBarConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SplitButtonBarConfig","preciseIdentifier":"s:5Divar20SplitButtonBarConfigV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/splitBarConfig","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/splitbarconfig"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/UIImagePickerControllerDelegate-Implementations":{"role":"collectionGroup","title":"UIImagePickerControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/UIImagePickerControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/uiimagepickercontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/forwardMessage(forwardingMessage:)":{"role":"symbol","title":"forwardMessage(forwardingMessage:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"forwardMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forwardingMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/forwardMessage(forwardingMessage:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/forwardmessage(forwardingmessage:)"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/showWarning(for:warning:)":{"role":"symbol","title":"showWarning(for:warning:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showWarning"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"warning"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/showWarning(for:warning:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/showwarning(for:warning:)"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController":{"role":"symbol","title":"ChatViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatViewController"}],"url":"\/documentation\/divar\/chatviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/stackView":{"role":"symbol","title":"stackView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/stackView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stackView"}],"url":"\/documentation\/divar\/chatviewcontroller\/stackview"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/viewDidAppear(_:)":{"role":"symbol","title":"viewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/viewDidAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"url":"\/documentation\/divar\/chatviewcontroller\/viewdidappear(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/messagingVC":{"role":"symbol","title":"messagingVC","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagingVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagingViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MessagingViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/messagingVC","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/messagingvc"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/getOnlineStatus(completion:)":{"role":"symbol","title":"getOnlineStatus(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getOnlineStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RequestCompletionHandlerType","preciseIdentifier":"s:5Divar28RequestCompletionHandlerTypea"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":">)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/getOnlineStatus(completion:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/getonlinestatus(completion:)"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/logUnblockAction()":{"role":"symbol","title":"logUnblockAction()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logUnblockAction"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/logUnblockAction()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/logunblockaction()"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/setupNavigationBarItems()":{"role":"symbol","title":"setupNavigationBarItems()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupNavigationBarItems"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/setupNavigationBarItems()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/setupnavigationbaritems()"},"doc://com.Divar.DivarClient/documentation/Divar/GetSuggestionProtocol":{"role":"symbol","title":"GetSuggestionProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetSuggestionProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GetSuggestionProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GetSuggestionProtocol"}],"url":"\/documentation\/divar\/getsuggestionprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/setupObservers()":{"role":"symbol","title":"setupObservers()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupObservers"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/setupObservers()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/setupobservers()"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/pop()":{"role":"symbol","title":"pop()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pop"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/pop()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/pop()"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/setupUI()":{"role":"symbol","title":"setupUI()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupUI"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/setupUI()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/setupui()"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/toggleSplitBar()":{"role":"symbol","title":"toggleSplitBar()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toggleSplitBar"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/toggleSplitBar()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/togglesplitbar()"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/sendTypingEvent(_:)":{"role":"symbol","title":"sendTypingEvent(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendTypingEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/sendTypingEvent(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/sendtypingevent(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/prepareMessagePreview(_:forType:)":{"role":"symbol","title":"prepareMessagePreview(_:forType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareMessagePreview"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagePreviewBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MessagePreviewBarViewController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"MessagePreviewType","preciseIdentifier":"s:5Divar31MessagePreviewBarViewControllerC0bC4TypeO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/prepareMessagePreview(_:forType:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/preparemessagepreview(_:fortype:)"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/conversationDeactivatedCondition":{"role":"symbol","title":"conversationDeactivatedCondition","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationDeactivatedCondition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/conversationDeactivatedCondition","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/conversationdeactivatedcondition"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/messageInputAreaVC":{"role":"symbol","title":"messageInputAreaVC","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageInputAreaVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InputAreaViewController","preciseIdentifier":"c:@M@Divar@objc(cs)InputAreaViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/messageInputAreaVC","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/messageinputareavc"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/GetSuggestionProtocol-Implementations":{"role":"collectionGroup","title":"GetSuggestionProtocol Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/GetSuggestionProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/getsuggestionprotocol-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController":{"role":"symbol","title":"BaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseViewController"}],"url":"\/documentation\/divar\/baseviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ShowErrorProtocol":{"role":"symbol","title":"ShowErrorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowErrorProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowErrorProtocol"}],"url":"\/documentation\/divar\/showerrorprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/showOptions()":{"role":"symbol","title":"showOptions()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showOptions"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/showOptions()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showOptions"}],"url":"\/documentation\/divar\/chatviewcontroller\/showoptions()"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/requestUnblockUser()":{"role":"symbol","title":"requestUnblockUser()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestUnblockUser"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/requestUnblockUser()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestUnblockUser"}],"url":"\/documentation\/divar\/chatviewcontroller\/requestunblockuser()"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/VideoPreviewControllerDelegate-Implementations":{"role":"collectionGroup","title":"VideoPreviewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/VideoPreviewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/videopreviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/handleKeyboardStatus(_:)":{"role":"symbol","title":"handleKeyboardStatus(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleKeyboardStatus"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/handleKeyboardStatus(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"handleKeyboardStatus:"}],"url":"\/documentation\/divar\/chatviewcontroller\/handlekeyboardstatus(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/init(container:conversationID:isShowingPostchi:configuration:)":{"role":"symbol","title":"init(container:conversationID:isShowingPostchi:configuration:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatViewControllerDIContainer","preciseIdentifier":"s:5Divar29ChatViewControllerDIContainera"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isShowingPostchi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IntroConfig","preciseIdentifier":"s:5Divar11IntroConfigV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/init(container:conversationID:isShowingPostchi:configuration:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/init(container:conversationid:isshowingpostchi:configuration:)"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/showFileSendConfirmationAlert(forURL:)":{"role":"symbol","title":"showFileSendConfirmationAlert(forURL:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showFileSendConfirmationAlert"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/showFileSendConfirmationAlert(forURL:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/showfilesendconfirmationalert(forurl:)"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/conversation":{"role":"symbol","title":"conversation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatConversationTable","preciseIdentifier":"s:5Divar21ChatConversationTableV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/conversation","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/conversation"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/ImagePickerDelegate-Implementations":{"role":"collectionGroup","title":"ImagePickerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/ImagePickerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/imagepickerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/AdViewViewControllerDelegate":{"role":"symbol","title":"AdViewViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdViewViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdViewViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdViewViewControllerDelegate"}],"url":"\/documentation\/divar\/adviewviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/stackViewBottomConstraint":{"role":"symbol","title":"stackViewBottomConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stackViewBottomConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/stackViewBottomConstraint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stackViewBottomConstraint"}],"url":"\/documentation\/divar\/chatviewcontroller\/stackviewbottomconstraint"},"doc://com.Divar.DivarClient/documentation/Divar/ImagePickerDelegate":{"deprecated":true,"role":"symbol","title":"ImagePickerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImagePickerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImagePickerDelegate"}],"url":"\/documentation\/divar\/imagepickerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/TooltipPresenter":{"role":"symbol","title":"TooltipPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TooltipPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TooltipPresenter"}],"url":"\/documentation\/divar\/tooltippresenter"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/splitBar":{"role":"symbol","title":"splitBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"splitBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SplitButtonBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SplitButtonBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/splitBar","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/splitbar"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/UserRegisterationChanged()":{"role":"symbol","title":"UserRegisterationChanged()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserRegisterationChanged"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/UserRegisterationChanged()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserRegisterationChanged"}],"url":"\/documentation\/divar\/chatviewcontroller\/userregisterationchanged()"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/showWarningIfExists()":{"role":"symbol","title":"showWarningIfExists()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showWarningIfExists"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/showWarningIfExists()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showWarningIfExists"}],"url":"\/documentation\/divar\/chatviewcontroller\/showwarningifexists()"},"doc://com.Divar.DivarClient/documentation/Divar/RefreshableProtocol":{"role":"symbol","title":"RefreshableProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RefreshableProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RefreshableProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RefreshableProtocol"}],"url":"\/documentation\/divar\/refreshableprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/adVC":{"role":"symbol","title":"adVC","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdViewViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AdViewViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/adVC","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/advc"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/previewingMessage":{"role":"symbol","title":"previewingMessage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewingMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/previewingMessage","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/previewingmessage"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/documentation/Divar/ChatOptionActionProtocol":{"role":"symbol","title":"ChatOptionActionProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatOptionActionProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatOptionActionProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatOptionActionProtocol"}],"url":"\/documentation\/divar\/chatoptionactionprotocol"},"doc://com.Divar.DivarClient/objc(pl)UIImagePickerControllerDelegate":{"type":"unresolvable","title":"UIKit.UIImagePickerControllerDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIImagePickerControllerDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/TagListViewControllerDelegate":{"role":"symbol","title":"TagListViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagListViewControllerDelegate"}],"url":"\/documentation\/divar\/taglistviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/ChatOptionActionProtocol-Implementations":{"role":"collectionGroup","title":"ChatOptionActionProtocol Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/ChatOptionActionProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/chatoptionactionprotocol-implementations"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/openningViewController":{"role":"symbol","title":"openningViewController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"openningViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/openningViewController","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/openningviewcontroller"},"doc://com.Divar.DivarClient/objc(pl)UIDocumentPickerDelegate":{"type":"unresolvable","title":"UIKit.UIDocumentPickerDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIDocumentPickerDelegate"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/MapSelectorViewControllerDelegate":{"role":"symbol","title":"MapSelectorViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapSelectorViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapSelectorViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapSelectorViewControllerDelegate"}],"url":"\/documentation\/divar\/mapselectorviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/SplitButtonBarViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"SplitButtonBarViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/SplitButtonBarViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/splitbuttonbarviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/UIDocumentPickerDelegate-Implementations":{"role":"collectionGroup","title":"UIDocumentPickerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/UIDocumentPickerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/uidocumentpickerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/SFSafariViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"SFSafariViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/SFSafariViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/sfsafariviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/conversationID":{"role":"symbol","title":"conversationID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/conversationID","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/conversationid"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/logMenuClickAction()":{"role":"symbol","title":"logMenuClickAction()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logMenuClickAction"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/logMenuClickAction()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/logmenuclickaction()"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/setPeerName()":{"role":"symbol","title":"setPeerName()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPeerName"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/setPeerName()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/setpeername()"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/makeCallButtonAction(_:)":{"role":"symbol","title":"makeCallButtonAction(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeCallButtonAction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/makeCallButtonAction(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"makeCallButtonAction:"}],"url":"\/documentation\/divar\/chatviewcontroller\/makecallbuttonaction(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/didRequestDismissingKeyboard()":{"role":"symbol","title":"didRequestDismissingKeyboard()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRequestDismissingKeyboard"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/didRequestDismissingKeyboard()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/didrequestdismissingkeyboard()"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/viewWillAppear(_:)":{"role":"symbol","title":"viewWillAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/viewWillAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"url":"\/documentation\/divar\/chatviewcontroller\/viewwillappear(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/messagePreviewBarViewController":{"role":"symbol","title":"messagePreviewBarViewController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagePreviewBarViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagePreviewBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MessagePreviewBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/messagePreviewBarViewController","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/messagepreviewbarviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/chatviewcontroller\/viewdidload()"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/handleBlockUnblockEvent()":{"role":"symbol","title":"handleBlockUnblockEvent()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleBlockUnblockEvent"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/handleBlockUnblockEvent()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"handleBlockUnblockEvent"}],"url":"\/documentation\/divar\/chatviewcontroller\/handleblockunblockevent()"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController/getForwardListRequest(_:completion:)":{"role":"symbol","title":"getForwardListRequest(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getForwardListRequest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"ChatConversationStructure","preciseIdentifier":"s:5Divar25ChatConversationStructureC"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/getForwardListRequest(_:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/chatviewcontroller\/getforwardlistrequest(_:completion:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ChatViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChatViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ChatViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/stackView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/stackViewBottomConstraint"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/UserRegisterationChanged()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/handleBlockUnblockEvent()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/handleKeyboardStatus(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/makeCallButtonAction(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/requestUnblockUser()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/setupConnectionStatusPrompt()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/showOptions()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/showWarningIfExists()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/toggleConnectionStatus()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/togglePeerTypingStatus()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/viewDidAppear(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/viewDidLayoutSubviews()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/viewDidLoad()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/viewWillAppear(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/ChatOptionActionProtocol-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/SFSafariViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/UIDocumentPickerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController\/UIImagePickerControllerDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController","preciseIdentifier":"c:@M@Divar@objc(cs)BaseViewController","text":"BaseViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1setupConnectionStatusPrompt()\/title","value":"setupConnectionStatusPrompt"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1setupConnectionStatusPrompt()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupConnectionStatusPrompt"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1viewDidLayoutSubviews()\/title","value":"viewDidLayoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1viewDidLayoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLayoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1toggleConnectionStatus()\/title","value":"toggleConnectionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1toggleConnectionStatus()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toggleConnectionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1togglePeerTypingStatus()\/title","value":"togglePeerTypingStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1togglePeerTypingStatus()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"togglePeerTypingStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/title","value":"ChatViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/fragments","value":[{"kind":"identifier","text":"ChatViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1stackView\/title","value":"stackView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1stackView\/fragments","value":[{"kind":"identifier","text":"stackView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController\/title","value":"BaseViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController\/fragments","value":[{"kind":"identifier","text":"BaseViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1showOptions()\/title","value":"showOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1showOptions()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1requestUnblockUser()\/title","value":"requestUnblockUser"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1requestUnblockUser()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestUnblockUser"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1handleKeyboardStatus(_:)\/title","value":"handleKeyboardStatus:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1handleKeyboardStatus(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleKeyboardStatus:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1stackViewBottomConstraint\/title","value":"stackViewBottomConstraint"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1stackViewBottomConstraint\/fragments","value":[{"kind":"identifier","text":"stackViewBottomConstraint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1UserRegisterationChanged()\/title","value":"UserRegisterationChanged"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1UserRegisterationChanged()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"UserRegisterationChanged"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1showWarningIfExists()\/title","value":"showWarningIfExists"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1showWarningIfExists()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showWarningIfExists"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1makeCallButtonAction(_:)\/title","value":"makeCallButtonAction:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1makeCallButtonAction(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"makeCallButtonAction:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1handleBlockUnblockEvent()\/title","value":"handleBlockUnblockEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController~1handleBlockUnblockEvent()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleBlockUnblockEvent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}