{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClaimPostProtocol"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/claimpostprotocol"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetContactViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BusinessGetContactViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FinalizeMarketplaceRegister","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandscapeWidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MobileZeroPriceViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OfflinePageViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostDetailsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostPreviewViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ClaimPostProtocol","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ClaimPostProtocol\/claimToken"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ClaimPostProtocol\/openLoginPage(phone:dataProvider:)-2gqav"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClaimPostProtocol"}],"title":"ClaimPostProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar17ClaimPostProtocolP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"ClaimPostProtocol"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedPostDetailsViewController":{"role":"symbol","title":"WidgetBasedPostDetailsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedPostDetailsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostDetailsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedPostDetailsViewController"}],"url":"\/documentation\/divar\/widgetbasedpostdetailsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController":{"role":"symbol","title":"ZeroPriceViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZeroPriceViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZeroPriceViewController"}],"url":"\/documentation\/divar\/zeropriceviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/FinalizeMarketplaceRegister":{"role":"symbol","title":"FinalizeMarketplaceRegister","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FinalizeMarketplaceRegister"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FinalizeMarketplaceRegister","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FinalizeMarketplaceRegister"}],"url":"\/documentation\/divar\/finalizemarketplaceregister"},"doc://com.Divar.DivarClient/documentation/Divar/ClaimPostProtocol/openLoginPage(phone:dataProvider:)-2gqav":{"defaultImplementations":1,"role":"symbol","title":"openLoginPage(phone:dataProvider:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openLoginPage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"phone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dataProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DataProviderProtocol","preciseIdentifier":"s:5Divar20DataProviderProtocolP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ClaimPostProtocol\/openLoginPage(phone:dataProvider:)-2gqav","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/claimpostprotocol\/openloginpage(phone:dataprovider:)-2gqav"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController":{"role":"symbol","title":"WidgetBasedViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedViewController"}],"url":"\/documentation\/divar\/widgetbasedviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MobileZeroPriceViewController":{"role":"symbol","title":"MobileZeroPriceViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MobileZeroPriceViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MobileZeroPriceViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MobileZeroPriceViewController"}],"url":"\/documentation\/divar\/mobilezeropriceviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/OfflinePageViewController":{"role":"symbol","title":"OfflinePageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflinePageViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OfflinePageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OfflinePageViewController"}],"url":"\/documentation\/divar\/offlinepageviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedPostPreviewViewController":{"role":"symbol","title":"WidgetBasedPostPreviewViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedPostPreviewViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostPreviewViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedPostPreviewViewController"}],"url":"\/documentation\/divar\/widgetbasedpostpreviewviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ClaimPostProtocol":{"role":"symbol","title":"ClaimPostProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClaimPostProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ClaimPostProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClaimPostProtocol"}],"url":"\/documentation\/divar\/claimpostprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetViewController":{"role":"symbol","title":"WidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetViewController"}],"url":"\/documentation\/divar\/widgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetContactViewController":{"role":"symbol","title":"BottomSheetContactViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BottomSheetContactViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetContactViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BottomSheetContactViewController"}],"url":"\/documentation\/divar\/bottomsheetcontactviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController":{"role":"symbol","title":"AdvancedWidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdvancedWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdvancedWidgetViewController"}],"url":"\/documentation\/divar\/advancedwidgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/LandscapeWidgetViewController":{"role":"symbol","title":"LandscapeWidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandscapeWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandscapeWidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandscapeWidgetViewController"}],"url":"\/documentation\/divar\/landscapewidgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BusinessGetContactViewController":{"role":"symbol","title":"BusinessGetContactViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BusinessGetContactViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BusinessGetContactViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BusinessGetContactViewController"}],"url":"\/documentation\/divar\/businessgetcontactviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ClaimPostProtocol/claimToken":{"role":"symbol","title":"claimToken","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"claimToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ClaimPostProtocol\/claimToken","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/claimpostprotocol\/claimtoken"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedPostDetailsViewController\/title","value":"WidgetBasedPostDetailsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedPostDetailsViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedPostDetailsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ZeroPriceViewController\/title","value":"ZeroPriceViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ZeroPriceViewController\/fragments","value":[{"kind":"identifier","text":"ZeroPriceViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedViewController\/title","value":"WidgetBasedViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MobileZeroPriceViewController\/title","value":"MobileZeroPriceViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MobileZeroPriceViewController\/fragments","value":[{"kind":"identifier","text":"MobileZeroPriceViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OfflinePageViewController\/title","value":"OfflinePageViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OfflinePageViewController\/fragments","value":[{"kind":"identifier","text":"OfflinePageViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedPostPreviewViewController\/title","value":"WidgetBasedPostPreviewViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedPostPreviewViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedPostPreviewViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetContactViewController\/title","value":"BottomSheetContactViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetContactViewController\/fragments","value":[{"kind":"identifier","text":"BottomSheetContactViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController\/title","value":"AdvancedWidgetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController\/fragments","value":[{"kind":"identifier","text":"AdvancedWidgetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandscapeWidgetViewController\/title","value":"LandscapeWidgetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandscapeWidgetViewController\/fragments","value":[{"kind":"identifier","text":"LandscapeWidgetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BusinessGetContactViewController\/title","value":"BusinessGetContactViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BusinessGetContactViewController\/fragments","value":[{"kind":"identifier","text":"BusinessGetContactViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}