{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComponentProtocol"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/componentprotocol"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ButtonComponentProtocol"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CategoryHierarchyController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FinalizeMarketplaceRegister","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HeaderBarViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandscapeWidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagePreviewBarViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberTextFieldDialogWidgetController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberTextFieldPageController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OfflinePageViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListTabbedViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchHistoryViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchSuggestionsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SegmentedBar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SelectablePostsListViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleMultiBaseViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleMultiLocationViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SplitButtonBarViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SwitchBarViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TabbedPageViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UpdateViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ValidatorRowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoPreviewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WideButtonViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ComponentProtocol","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComponentProtocol"}],"title":"ComponentProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar17ComponentProtocolP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"ComponentProtocol"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/SearchSuggestionsViewController":{"role":"symbol","title":"SearchSuggestionsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchSuggestionsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchSuggestionsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchSuggestionsViewController"}],"url":"\/documentation\/divar\/searchsuggestionsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/DistrictedMapViewController":{"role":"symbol","title":"DistrictedMapViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DistrictedMapViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DistrictedMapViewController"}],"url":"\/documentation\/divar\/districtedmapviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SearchHistoryViewController":{"role":"symbol","title":"SearchHistoryViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchHistoryViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchHistoryViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchHistoryViewController"}],"url":"\/documentation\/divar\/searchhistoryviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ButtonComponentProtocol":{"role":"symbol","title":"ButtonComponentProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ButtonComponentProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ButtonComponentProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ButtonComponentProtocol"}],"url":"\/documentation\/divar\/buttoncomponentprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController":{"role":"symbol","title":"AdvancedWidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdvancedWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdvancedWidgetViewController"}],"url":"\/documentation\/divar\/advancedwidgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/FinalizeMarketplaceRegister":{"role":"symbol","title":"FinalizeMarketplaceRegister","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FinalizeMarketplaceRegister"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FinalizeMarketplaceRegister","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FinalizeMarketplaceRegister"}],"url":"\/documentation\/divar\/finalizemarketplaceregister"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetViewController":{"role":"symbol","title":"WidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetViewController"}],"url":"\/documentation\/divar\/widgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/UpdateViewController":{"role":"symbol","title":"UpdateViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UpdateViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UpdateViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UpdateViewController"}],"url":"\/documentation\/divar\/updateviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/TagListViewController":{"role":"symbol","title":"TagListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagListViewController"}],"url":"\/documentation\/divar\/taglistviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SplitButtonBarViewController":{"role":"symbol","title":"SplitButtonBarViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SplitButtonBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SplitButtonBarViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SplitButtonBarViewController"}],"url":"\/documentation\/divar\/splitbuttonbarviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/HeaderBarViewController":{"role":"symbol","title":"HeaderBarViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeaderBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HeaderBarViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeaderBarViewController"}],"url":"\/documentation\/divar\/headerbarviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController":{"role":"symbol","title":"AbstractFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AbstractFormViewController"}],"url":"\/documentation\/divar\/abstractformviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SegmentedBar":{"role":"symbol","title":"SegmentedBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SegmentedBar"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SegmentedBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SegmentedBar"}],"url":"\/documentation\/divar\/segmentedbar"},"doc://com.Divar.DivarClient/documentation/Divar/WideButtonViewController":{"role":"symbol","title":"WideButtonViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WideButtonViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WideButtonViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WideButtonViewController"}],"url":"\/documentation\/divar\/widebuttonviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController":{"role":"symbol","title":"TransformablePriceViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransformablePriceViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TransformablePriceViewController"}],"url":"\/documentation\/divar\/transformablepriceviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SingleMultiLocationViewController":{"role":"symbol","title":"SingleMultiLocationViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleMultiLocationViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleMultiLocationViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SingleMultiLocationViewController"}],"url":"\/documentation\/divar\/singlemultilocationviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ComponentProtocol":{"role":"symbol","title":"ComponentProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComponentProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ComponentProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ComponentProtocol"}],"url":"\/documentation\/divar\/componentprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/TabbedPageViewController":{"role":"symbol","title":"TabbedPageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TabbedPageViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TabbedPageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TabbedPageViewController"}],"url":"\/documentation\/divar\/tabbedpageviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SearchViewController":{"role":"symbol","title":"SearchViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchViewController"}],"url":"\/documentation\/divar\/searchviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/NoteWithBottomBarViewController":{"role":"symbol","title":"NoteWithBottomBarViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NoteWithBottomBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NoteWithBottomBarViewController"}],"url":"\/documentation\/divar\/notewithbottombarviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ValidatorRowController":{"role":"symbol","title":"ValidatorRowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidatorRowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ValidatorRowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ValidatorRowController"}],"url":"\/documentation\/divar\/validatorrowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SelectablePostsListViewController":{"role":"symbol","title":"SelectablePostsListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SelectablePostsListViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SelectablePostsListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SelectablePostsListViewController"}],"url":"\/documentation\/divar\/selectablepostslistviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyController":{"role":"symbol","title":"SingleHierarchyController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleHierarchyController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SingleHierarchyController"}],"url":"\/documentation\/divar\/singlehierarchycontroller"},"doc://com.Divar.DivarClient/documentation/Divar/NumberTextFieldPageController":{"role":"symbol","title":"NumberTextFieldPageController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NumberTextFieldPageController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberTextFieldPageController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NumberTextFieldPageController"}],"url":"\/documentation\/divar\/numbertextfieldpagecontroller"},"doc://com.Divar.DivarClient/documentation/Divar/LandscapeWidgetViewController":{"role":"symbol","title":"LandscapeWidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandscapeWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandscapeWidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandscapeWidgetViewController"}],"url":"\/documentation\/divar\/landscapewidgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractTableViewController":{"role":"symbol","title":"AbstractTableViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractTableViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractTableViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AbstractTableViewController"}],"url":"\/documentation\/divar\/abstracttableviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostListTabbedViewController":{"role":"symbol","title":"PostListTabbedViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostListTabbedViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListTabbedViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostListTabbedViewController"}],"url":"\/documentation\/divar\/postlisttabbedviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/NumberTextFieldDialogWidgetController":{"role":"symbol","title":"NumberTextFieldDialogWidgetController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NumberTextFieldDialogWidgetController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberTextFieldDialogWidgetController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NumberTextFieldDialogWidgetController"}],"url":"\/documentation\/divar\/numbertextfielddialogwidgetcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController":{"role":"symbol","title":"InputAreaViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InputAreaViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InputAreaViewController"}],"url":"\/documentation\/divar\/inputareaviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/VideoPreviewController":{"role":"symbol","title":"VideoPreviewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPreviewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoPreviewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoPreviewController"}],"url":"\/documentation\/divar\/videopreviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MessagePreviewBarViewController":{"role":"symbol","title":"MessagePreviewBarViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagePreviewBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagePreviewBarViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagePreviewBarViewController"}],"url":"\/documentation\/divar\/messagepreviewbarviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/OfflinePageViewController":{"role":"symbol","title":"OfflinePageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflinePageViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OfflinePageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OfflinePageViewController"}],"url":"\/documentation\/divar\/offlinepageviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewController":{"role":"symbol","title":"WidgetBasedCollectionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedCollectionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedCollectionViewController"}],"url":"\/documentation\/divar\/widgetbasedcollectionviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController":{"role":"symbol","title":"SingleHierarchyBaseController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleHierarchyBaseController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SingleHierarchyBaseController"}],"url":"\/documentation\/divar\/singlehierarchybasecontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SingleMultiBaseViewController":{"role":"symbol","title":"SingleMultiBaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleMultiBaseViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleMultiBaseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SingleMultiBaseViewController"}],"url":"\/documentation\/divar\/singlemultibaseviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewController":{"role":"symbol","title":"TwinButtonsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TwinButtonsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TwinButtonsViewController"}],"url":"\/documentation\/divar\/twinbuttonsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CategoryHierarchyController":{"role":"symbol","title":"CategoryHierarchyController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CategoryHierarchyController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CategoryHierarchyController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CategoryHierarchyController"}],"url":"\/documentation\/divar\/categoryhierarchycontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SwitchBarViewController":{"role":"symbol","title":"SwitchBarViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SwitchBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SwitchBarViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SwitchBarViewController"}],"url":"\/documentation\/divar\/switchbarviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController":{"role":"symbol","title":"PostsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostsViewController"}],"url":"\/documentation\/divar\/postsviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchSuggestionsViewController\/title","value":"SearchSuggestionsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchSuggestionsViewController\/fragments","value":[{"kind":"identifier","text":"SearchSuggestionsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictedMapViewController\/title","value":"DistrictedMapViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictedMapViewController\/fragments","value":[{"kind":"identifier","text":"DistrictedMapViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchHistoryViewController\/title","value":"SearchHistoryViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchHistoryViewController\/fragments","value":[{"kind":"identifier","text":"SearchHistoryViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController\/title","value":"AdvancedWidgetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController\/fragments","value":[{"kind":"identifier","text":"AdvancedWidgetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1UpdateViewController\/title","value":"UpdateViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1UpdateViewController\/fragments","value":[{"kind":"identifier","text":"UpdateViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListViewController\/title","value":"TagListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListViewController\/fragments","value":[{"kind":"identifier","text":"TagListViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SplitButtonBarViewController\/title","value":"SplitButtonBarViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SplitButtonBarViewController\/fragments","value":[{"kind":"identifier","text":"SplitButtonBarViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1HeaderBarViewController\/title","value":"HeaderBarViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1HeaderBarViewController\/fragments","value":[{"kind":"identifier","text":"HeaderBarViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController\/title","value":"AbstractFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController\/fragments","value":[{"kind":"identifier","text":"AbstractFormViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SegmentedBar\/title","value":"SegmentedBar"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SegmentedBar\/fragments","value":[{"kind":"identifier","text":"SegmentedBar"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WideButtonViewController\/title","value":"WideButtonViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WideButtonViewController\/fragments","value":[{"kind":"identifier","text":"WideButtonViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TransformablePriceViewController\/title","value":"TransformablePriceViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TransformablePriceViewController\/fragments","value":[{"kind":"identifier","text":"TransformablePriceViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleMultiLocationViewController\/title","value":"SingleMultiLocationViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleMultiLocationViewController\/fragments","value":[{"kind":"identifier","text":"SingleMultiLocationViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TabbedPageViewController\/title","value":"TabbedPageViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TabbedPageViewController\/fragments","value":[{"kind":"identifier","text":"TabbedPageViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchViewController\/title","value":"SearchViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchViewController\/fragments","value":[{"kind":"identifier","text":"SearchViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteWithBottomBarViewController\/title","value":"NoteWithBottomBarViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteWithBottomBarViewController\/fragments","value":[{"kind":"identifier","text":"NoteWithBottomBarViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ValidatorRowController\/title","value":"ValidatorRowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ValidatorRowController\/fragments","value":[{"kind":"identifier","text":"ValidatorRowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleHierarchyController\/title","value":"SingleHierarchyController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleHierarchyController\/fragments","value":[{"kind":"identifier","text":"SingleHierarchyController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NumberTextFieldPageController\/title","value":"NumberTextFieldPageController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NumberTextFieldPageController\/fragments","value":[{"kind":"identifier","text":"NumberTextFieldPageController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandscapeWidgetViewController\/title","value":"LandscapeWidgetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandscapeWidgetViewController\/fragments","value":[{"kind":"identifier","text":"LandscapeWidgetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController\/title","value":"AbstractTableViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractTableViewController\/fragments","value":[{"kind":"identifier","text":"AbstractTableViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListTabbedViewController\/title","value":"PostListTabbedViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListTabbedViewController\/fragments","value":[{"kind":"identifier","text":"PostListTabbedViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NumberTextFieldDialogWidgetController\/title","value":"NumberTextFieldDialogWidgetController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NumberTextFieldDialogWidgetController\/fragments","value":[{"kind":"identifier","text":"NumberTextFieldDialogWidgetController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController\/title","value":"InputAreaViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController\/fragments","value":[{"kind":"identifier","text":"InputAreaViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VideoPreviewController\/title","value":"VideoPreviewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VideoPreviewController\/fragments","value":[{"kind":"identifier","text":"VideoPreviewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagePreviewBarViewController\/title","value":"MessagePreviewBarViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagePreviewBarViewController\/fragments","value":[{"kind":"identifier","text":"MessagePreviewBarViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OfflinePageViewController\/title","value":"OfflinePageViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OfflinePageViewController\/fragments","value":[{"kind":"identifier","text":"OfflinePageViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedCollectionViewController\/title","value":"WidgetBasedCollectionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedCollectionViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedCollectionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleHierarchyBaseController\/title","value":"SingleHierarchyBaseController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleHierarchyBaseController\/fragments","value":[{"kind":"identifier","text":"SingleHierarchyBaseController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleMultiBaseViewController\/title","value":"SingleMultiBaseViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleMultiBaseViewController\/fragments","value":[{"kind":"identifier","text":"SingleMultiBaseViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TwinButtonsViewController\/title","value":"TwinButtonsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TwinButtonsViewController\/fragments","value":[{"kind":"identifier","text":"TwinButtonsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CategoryHierarchyController\/title","value":"CategoryHierarchyController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CategoryHierarchyController\/fragments","value":[{"kind":"identifier","text":"CategoryHierarchyController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SwitchBarViewController\/title","value":"SwitchBarViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SwitchBarViewController\/fragments","value":[{"kind":"identifier","text":"SwitchBarViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostsViewController\/title","value":"PostsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostsViewController\/fragments","value":[{"kind":"identifier","text":"PostsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}