{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConfigurableCell"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/configurablecell"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionFieldTableViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionPrimaryTableViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionSecondaryTableViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InfoRowTableViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LegendTitleTableViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteRowTableViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldTableViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TitleRowTableViewCell"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConfigurableCell","interfaceLanguage":"swift"},"topicSections":[{"title":"Associated Types","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConfigurableCell\/DataType","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConfigurableCell\/ReturnType"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConfigurableCell\/cellHeight","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConfigurableCell\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConfigurableCell\/fill(with:indexPath:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConfigurableCell\/returnData()-1vox2"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConfigurableCell"}],"title":"ConfigurableCell","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar16ConfigurableCellP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"ConfigurableCell"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ConfigurableCell":{"role":"symbol","title":"ConfigurableCell","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConfigurableCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConfigurableCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConfigurableCell"}],"url":"\/documentation\/divar\/configurablecell"},"doc://com.Divar.DivarClient/documentation/Divar/ConfigurableCell/ReturnType":{"role":"symbol","title":"ReturnType","fragments":[{"kind":"keyword","text":"associatedtype"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReturnType"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConfigurableCell\/ReturnType","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/configurablecell\/returntype"},"doc://com.Divar.DivarClient/documentation/Divar/ConfigurableCell/cellHeight":{"role":"symbol","title":"cellHeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConfigurableCell\/cellHeight","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/configurablecell\/cellheight"},"doc://com.Divar.DivarClient/documentation/Divar/LegendTitleTableViewCell":{"role":"symbol","title":"LegendTitleTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LegendTitleTableViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LegendTitleTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LegendTitleTableViewCell"}],"url":"\/documentation\/divar\/legendtitletableviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/DescriptionPrimaryTableViewCell":{"role":"symbol","title":"DescriptionPrimaryTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DescriptionPrimaryTableViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionPrimaryTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DescriptionPrimaryTableViewCell"}],"url":"\/documentation\/divar\/descriptionprimarytableviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/TitleRowTableViewCell":{"role":"symbol","title":"TitleRowTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TitleRowTableViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TitleRowTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TitleRowTableViewCell"}],"url":"\/documentation\/divar\/titlerowtableviewcell"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/DescriptionSecondaryTableViewCell":{"role":"symbol","title":"DescriptionSecondaryTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DescriptionSecondaryTableViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionSecondaryTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DescriptionSecondaryTableViewCell"}],"url":"\/documentation\/divar\/descriptionsecondarytableviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/ConfigurableCell/DataType":{"role":"symbol","title":"DataType","fragments":[{"kind":"keyword","text":"associatedtype"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataType"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConfigurableCell\/DataType","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/configurablecell\/datatype"},"doc://com.Divar.DivarClient/documentation/Divar/InfoRowTableViewCell":{"role":"symbol","title":"InfoRowTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InfoRowTableViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InfoRowTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InfoRowTableViewCell"}],"url":"\/documentation\/divar\/inforowtableviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/ConfigurableCell/returnData()-1vox2":{"defaultImplementations":1,"role":"symbol","title":"returnData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnData"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"ReturnType","preciseIdentifier":"s:5Divar16ConfigurableCellP10ReturnTypeQa"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConfigurableCell\/returnData()-1vox2","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/configurablecell\/returndata()-1vox2"},"doc://com.Divar.DivarClient/documentation/Divar/TextFieldTableViewCell":{"role":"symbol","title":"TextFieldTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextFieldTableViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TextFieldTableViewCell"}],"url":"\/documentation\/divar\/textfieldtableviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/ConfigurableCell/fill(with:indexPath:)":{"role":"symbol","title":"fill(with:indexPath:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fill"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DataType","preciseIdentifier":"s:5Divar16ConfigurableCellP8DataTypeQa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConfigurableCell\/fill(with:indexPath:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/configurablecell\/fill(with:indexpath:)"},"doc://com.Divar.DivarClient/documentation/Divar/ConfigurableCell/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConfigurableCellDelegate","preciseIdentifier":"s:5Divar24ConfigurableCellDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConfigurableCell\/delegate","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/configurablecell\/delegate"},"doc://com.Divar.DivarClient/documentation/Divar/NoteRowTableViewCell":{"role":"symbol","title":"NoteRowTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NoteRowTableViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteRowTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NoteRowTableViewCell"}],"url":"\/documentation\/divar\/noterowtableviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/DescriptionFieldTableViewCell":{"role":"symbol","title":"DescriptionFieldTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DescriptionFieldTableViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionFieldTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DescriptionFieldTableViewCell"}],"url":"\/documentation\/divar\/descriptionfieldtableviewcell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LegendTitleTableViewCell\/title","value":"LegendTitleTableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LegendTitleTableViewCell\/fragments","value":[{"kind":"identifier","text":"LegendTitleTableViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DescriptionPrimaryTableViewCell\/title","value":"DescriptionPrimaryTableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DescriptionPrimaryTableViewCell\/fragments","value":[{"kind":"identifier","text":"DescriptionPrimaryTableViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TitleRowTableViewCell\/title","value":"TitleRowTableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TitleRowTableViewCell\/fragments","value":[{"kind":"identifier","text":"TitleRowTableViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DescriptionSecondaryTableViewCell\/title","value":"DescriptionSecondaryTableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DescriptionSecondaryTableViewCell\/fragments","value":[{"kind":"identifier","text":"DescriptionSecondaryTableViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InfoRowTableViewCell\/title","value":"InfoRowTableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InfoRowTableViewCell\/fragments","value":[{"kind":"identifier","text":"InfoRowTableViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TextFieldTableViewCell\/title","value":"TextFieldTableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TextFieldTableViewCell\/fragments","value":[{"kind":"identifier","text":"TextFieldTableViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteRowTableViewCell\/title","value":"NoteRowTableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteRowTableViewCell\/fragments","value":[{"kind":"identifier","text":"NoteRowTableViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DescriptionFieldTableViewCell\/title","value":"DescriptionFieldTableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DescriptionFieldTableViewCell\/fragments","value":[{"kind":"identifier","text":"DescriptionFieldTableViewCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}