{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomUIActivity"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/customuiactivity"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/customuiactivity"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIActivity"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/init(title:image:performAction:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/activityImage","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/activityName","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/activitySonnatImage","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/activityTitle","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/activityType","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/customActionWhenTapped","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/customActivityType"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/canPerform(withActivityItems:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/perform()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/prepare(withActivityItems:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/activityCategory"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomUIActivity"}],"title":"CustomUIActivity","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)CustomUIActivity","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"CustomUIActivity"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivity/perform()":{"role":"symbol","title":"perform()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"perform"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/perform()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"performActivity"}],"url":"\/documentation\/divar\/customuiactivity\/perform()"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivity/init(title:image:performAction:)":{"role":"symbol","title":"init(title:image:performAction:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SonnatImages","preciseIdentifier":"s:6Sonnat0A6Imagesa"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"performAction"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/init(title:image:performAction:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/customuiactivity\/init(title:image:performaction:)"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivity/activityCategory":{"role":"symbol","title":"activityCategory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityCategory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIActivity","preciseIdentifier":"c:objc(cs)UIActivity"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Category","preciseIdentifier":"c:@E@UIActivityCategory"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/activityCategory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"activityCategory"}],"url":"\/documentation\/divar\/customuiactivity\/activitycategory"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivity/customActivityType":{"role":"symbol","title":"customActivityType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customActivityType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIActivity","preciseIdentifier":"c:objc(cs)UIActivity"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ActivityType","preciseIdentifier":"c:@T@UIActivityType"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/customActivityType","kind":"symbol","type":"topic","url":"\/documentation\/divar\/customuiactivity\/customactivitytype"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivity/activityName":{"role":"symbol","title":"activityName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/activityName","kind":"symbol","type":"topic","url":"\/documentation\/divar\/customuiactivity\/activityname"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivity":{"role":"symbol","title":"CustomUIActivity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomUIActivity"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomUIActivity"}],"url":"\/documentation\/divar\/customuiactivity"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivity/activityImage":{"role":"symbol","title":"activityImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/activityImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"activityImage"}],"url":"\/documentation\/divar\/customuiactivity\/activityimage"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivity/activityTitle":{"role":"symbol","title":"activityTitle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/activityTitle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"activityTitle"}],"url":"\/documentation\/divar\/customuiactivity\/activitytitle"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivity/activityType":{"role":"symbol","title":"activityType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIActivity","preciseIdentifier":"c:objc(cs)UIActivity"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ActivityType","preciseIdentifier":"c:@T@UIActivityType"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/activityType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"activityType"}],"url":"\/documentation\/divar\/customuiactivity\/activitytype"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/objc(cs)UIActivity":{"type":"unresolvable","title":"UIActivity","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)UIActivity"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivity/activitySonnatImage":{"role":"symbol","title":"activitySonnatImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activitySonnatImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SonnatImages","preciseIdentifier":"s:6Sonnat0A6Imagesa"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/activitySonnatImage","kind":"symbol","type":"topic","url":"\/documentation\/divar\/customuiactivity\/activitysonnatimage"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivity/prepare(withActivityItems:)":{"role":"symbol","title":"prepare(withActivityItems:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepare"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withActivityItems"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/prepare(withActivityItems:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prepareWithActivityItems:"}],"url":"\/documentation\/divar\/customuiactivity\/prepare(withactivityitems:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivity/canPerform(withActivityItems:)":{"role":"symbol","title":"canPerform(withActivityItems:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPerform"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withActivityItems"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/canPerform(withActivityItems:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canPerformWithActivityItems:"}],"url":"\/documentation\/divar\/customuiactivity\/canperform(withactivityitems:)"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivity/customActionWhenTapped":{"role":"symbol","title":"customActionWhenTapped","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customActionWhenTapped"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/customActionWhenTapped","kind":"symbol","type":"topic","url":"\/documentation\/divar\/customuiactivity\/customactionwhentapped"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CustomUIActivity"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CustomUIActivity"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CustomUIActivity"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/activityImage","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/activityTitle","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/activityType"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/canPerform(withActivityItems:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/perform()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/prepare(withActivityItems:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivity\/activityCategory"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIActivity"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomUIActivity"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIActivity","preciseIdentifier":"c:objc(cs)UIActivity"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity~1perform()\/title","value":"performActivity"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity~1perform()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"performActivity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity~1activityCategory\/title","value":"activityCategory"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity~1activityCategory\/fragments","value":[{"kind":"identifier","text":"activityCategory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity\/title","value":"CustomUIActivity"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity\/fragments","value":[{"kind":"identifier","text":"CustomUIActivity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity~1activityImage\/title","value":"activityImage"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity~1activityImage\/fragments","value":[{"kind":"identifier","text":"activityImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity~1activityTitle\/title","value":"activityTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity~1activityTitle\/fragments","value":[{"kind":"identifier","text":"activityTitle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity~1activityType\/title","value":"activityType"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity~1activityType\/fragments","value":[{"kind":"identifier","text":"activityType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity~1prepare(withActivityItems:)\/title","value":"prepareWithActivityItems:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity~1prepare(withActivityItems:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareWithActivityItems:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity~1canPerform(withActivityItems:)\/title","value":"canPerformWithActivityItems:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivity~1canPerform(withActivityItems:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canPerformWithActivityItems:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}