{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomUIActivityViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/customuiactivityviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/customuiactivityviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIActivityViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/init(container:activityItems:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/init(container:activityItems:applicationActivities:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/init(container:image:activities:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/init(container:text:activities:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/init(container:url:activities:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/fadeInDuration","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/fadeOutDuration","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/postToken","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/previewBottomMargin","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/previewCornerRadius","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/previewFont","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/previewImageCornerRadius","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/previewImageSideLength","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/previewLinkColor","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/previewNumberOfLines","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/previewPadding","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/previewTopMargin"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/viewDidAppear(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/viewDidLoad()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/viewWillDisappear(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomUIActivityViewController"}],"title":"CustomUIActivityViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)CustomUIActivityViewController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"CustomUIActivityViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivityViewController/previewLinkColor":{"role":"symbol","title":"previewLinkColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewLinkColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"The preview color for URL activity items"}],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/previewLinkColor","kind":"symbol","type":"topic","url":"\/documentation\/divar\/customuiactivityviewcontroller\/previewlinkcolor"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/objc(cs)UIActivityViewController":{"type":"unresolvable","title":"UIActivityViewController","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)UIActivityViewController"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivityViewController/previewImageCornerRadius":{"role":"symbol","title":"previewImageCornerRadius","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewImageCornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"The corner radius of the preview image"}],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/previewImageCornerRadius","kind":"symbol","type":"topic","url":"\/documentation\/divar\/customuiactivityviewcontroller\/previewimagecornerradius"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivityViewController/previewTopMargin":{"role":"symbol","title":"previewTopMargin","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewTopMargin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"The margin from the top of the viewController’s superview"}],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/previewTopMargin","kind":"symbol","type":"topic","url":"\/documentation\/divar\/customuiactivityviewcontroller\/previewtopmargin"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivityViewController/init(container:text:activities:)":{"role":"symbol","title":"init(container:text:activities:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CustomUIActivityViewControllerDIContainer","preciseIdentifier":"s:5Divar41CustomUIActivityViewControllerDIContainera"},{"kind":"text","text":", "},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"activities"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIActivity","preciseIdentifier":"c:objc(cs)UIActivity"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/init(container:text:activities:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/customuiactivityviewcontroller\/init(container:text:activities:)"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivityViewController/previewBottomMargin":{"role":"symbol","title":"previewBottomMargin","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewBottomMargin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"The margin from the top of the viewController’s view"}],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/previewBottomMargin","kind":"symbol","type":"topic","url":"\/documentation\/divar\/customuiactivityviewcontroller\/previewbottommargin"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivityViewController/previewImageSideLength":{"role":"symbol","title":"previewImageSideLength","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewImageSideLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"The side length of the preview image"}],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/previewImageSideLength","kind":"symbol","type":"topic","url":"\/documentation\/divar\/customuiactivityviewcontroller\/previewimagesidelength"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivityViewController/init(container:image:activities:)":{"role":"symbol","title":"init(container:image:activities:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CustomUIActivityViewControllerDIContainer","preciseIdentifier":"s:5Divar41CustomUIActivityViewControllerDIContainera"},{"kind":"text","text":", "},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"activities"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIActivity","preciseIdentifier":"c:objc(cs)UIActivity"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/init(container:image:activities:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/customuiactivityviewcontroller\/init(container:image:activities:)"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivityViewController/init(container:activityItems:applicationActivities:)":{"role":"symbol","title":"init(container:activityItems:applicationActivities:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CustomUIActivityViewControllerDIContainer","preciseIdentifier":"s:5Divar41CustomUIActivityViewControllerDIContainera"},{"kind":"text","text":", "},{"kind":"externalParam","text":"activityItems"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"applicationActivities"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIActivity","preciseIdentifier":"c:objc(cs)UIActivity"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/init(container:activityItems:applicationActivities:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/customuiactivityviewcontroller\/init(container:activityitems:applicationactivities:)"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivityViewController/init(container:url:activities:)":{"role":"symbol","title":"init(container:url:activities:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CustomUIActivityViewControllerDIContainer","preciseIdentifier":"s:5Divar41CustomUIActivityViewControllerDIContainera"},{"kind":"text","text":", "},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"activities"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIActivity","preciseIdentifier":"c:objc(cs)UIActivity"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/init(container:url:activities:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/customuiactivityviewcontroller\/init(container:url:activities:)"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivityViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/customuiactivityviewcontroller\/viewdidload()"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivityViewController/viewWillDisappear(_:)":{"role":"symbol","title":"viewWillDisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/viewWillDisappear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillDisappear:"}],"url":"\/documentation\/divar\/customuiactivityviewcontroller\/viewwilldisappear(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivityViewController/fadeOutDuration":{"role":"symbol","title":"fadeOutDuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fadeOutDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[{"type":"text","text":"The duration for the preview fading out"}],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/fadeOutDuration","kind":"symbol","type":"topic","url":"\/documentation\/divar\/customuiactivityviewcontroller\/fadeoutduration"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivityViewController":{"role":"symbol","title":"CustomUIActivityViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomUIActivityViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomUIActivityViewController"}],"url":"\/documentation\/divar\/customuiactivityviewcontroller"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivityViewController/init(container:activityItems:)":{"role":"symbol","title":"init(container:activityItems:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CustomUIActivityViewControllerDIContainer","preciseIdentifier":"s:5Divar41CustomUIActivityViewControllerDIContainera"},{"kind":"text","text":", "},{"kind":"externalParam","text":"activityItems"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/init(container:activityItems:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/customuiactivityviewcontroller\/init(container:activityitems:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivityViewController/postToken":{"role":"symbol","title":"postToken","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"postToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/postToken","kind":"symbol","type":"topic","url":"\/documentation\/divar\/customuiactivityviewcontroller\/posttoken"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivityViewController/previewCornerRadius":{"role":"symbol","title":"previewCornerRadius","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewCornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"The corner radius of the preview"}],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/previewCornerRadius","kind":"symbol","type":"topic","url":"\/documentation\/divar\/customuiactivityviewcontroller\/previewcornerradius"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivityViewController/previewNumberOfLines":{"role":"symbol","title":"previewNumberOfLines","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewNumberOfLines"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The number of lines to preview"}],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/previewNumberOfLines","kind":"symbol","type":"topic","url":"\/documentation\/divar\/customuiactivityviewcontroller\/previewnumberoflines"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivityViewController/previewFont":{"role":"symbol","title":"previewFont","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}],"abstract":[{"type":"text","text":"The font for the preview label"}],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/previewFont","kind":"symbol","type":"topic","url":"\/documentation\/divar\/customuiactivityviewcontroller\/previewfont"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivityViewController/previewPadding":{"role":"symbol","title":"previewPadding","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewPadding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"The padding around the preview"}],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/previewPadding","kind":"symbol","type":"topic","url":"\/documentation\/divar\/customuiactivityviewcontroller\/previewpadding"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivityViewController/viewDidAppear(_:)":{"role":"symbol","title":"viewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/viewDidAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"url":"\/documentation\/divar\/customuiactivityviewcontroller\/viewdidappear(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/CustomUIActivityViewController/fadeInDuration":{"role":"symbol","title":"fadeInDuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fadeInDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[{"type":"text","text":"The duration for the preview fading in"}],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/fadeInDuration","kind":"symbol","type":"topic","url":"\/documentation\/divar\/customuiactivityviewcontroller\/fadeinduration"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CustomUIActivityViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CustomUIActivityViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CustomUIActivityViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/viewDidAppear(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/viewDidLoad()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomUIActivityViewController\/viewWillDisappear(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIActivityViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomUIActivityViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIActivityViewController","preciseIdentifier":"c:objc(cs)UIActivityViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivityViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivityViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivityViewController~1viewWillDisappear(_:)\/title","value":"viewWillDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivityViewController~1viewWillDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillDisappear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivityViewController\/title","value":"CustomUIActivityViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivityViewController\/fragments","value":[{"kind":"identifier","text":"CustomUIActivityViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivityViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomUIActivityViewController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}