{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomPickerHandler"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/custompickerhandler"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/custompickerhandler"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPickerViewDataSource","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPickerViewDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/init(_:pickerRow:options:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/options","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/picker","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/pickerRow"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/numberOfComponents(in:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/pickerView(_:didSelectRow:inComponent:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/pickerView(_:numberOfRowsInComponent:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/pickerView(_:titleForRow:forComponent:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/pickerView(_:viewForRow:forComponent:reusing:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomPickerHandler"}],"title":"CustomPickerHandler","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)CustomPickerHandler","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"CustomPickerHandler"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/CustomPickerHandler/pickerView(_:viewForRow:forComponent:reusing:)":{"role":"symbol","title":"pickerView(_:viewForRow:forComponent:reusing:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pickerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewForRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reusing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/pickerView(_:viewForRow:forComponent:reusing:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pickerView:viewForRow:forComponent:reusingView:"}],"url":"\/documentation\/divar\/custompickerhandler\/pickerview(_:viewforrow:forcomponent:reusing:)"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/CustomPickerHandler":{"role":"symbol","title":"CustomPickerHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomPickerHandler"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomPickerHandler"}],"url":"\/documentation\/divar\/custompickerhandler"},"doc://com.Divar.DivarClient/objc(pl)UIPickerViewDataSource":{"type":"unresolvable","title":"UIPickerViewDataSource","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPickerViewDataSource"},"doc://com.Divar.DivarClient/documentation/Divar/CustomPickerHandler/options":{"role":"symbol","title":"options","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"options"},{"kind":"text","text":": [(id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")]?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/options","kind":"symbol","type":"topic","url":"\/documentation\/divar\/custompickerhandler\/options"},"doc://com.Divar.DivarClient/documentation/Divar/CustomPickerHandler/pickerRow":{"role":"symbol","title":"pickerRow","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pickerRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CustomPickerRow","preciseIdentifier":"s:5Divar15CustomPickerRowC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/pickerRow","kind":"symbol","type":"topic","url":"\/documentation\/divar\/custompickerhandler\/pickerrow"},"doc://com.Divar.DivarClient/documentation/Divar/CustomPickerHandler/numberOfComponents(in:)":{"role":"symbol","title":"numberOfComponents(in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfComponents"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/numberOfComponents(in:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"numberOfComponentsInPickerView:"}],"url":"\/documentation\/divar\/custompickerhandler\/numberofcomponents(in:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/objc(pl)UIPickerViewDelegate":{"type":"unresolvable","title":"UIPickerViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPickerViewDelegate"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/CustomPickerHandler/init(_:pickerRow:options:)":{"role":"symbol","title":"init(_:pickerRow:options:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pickerRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CustomPickerRow","preciseIdentifier":"s:5Divar15CustomPickerRowC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": [(id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")]?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/init(_:pickerRow:options:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/custompickerhandler\/init(_:pickerrow:options:)"},"doc://com.Divar.DivarClient/documentation/Divar/CustomPickerHandler/pickerView(_:numberOfRowsInComponent:)":{"role":"symbol","title":"pickerView(_:numberOfRowsInComponent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pickerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfRowsInComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/pickerView(_:numberOfRowsInComponent:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pickerView:numberOfRowsInComponent:"}],"url":"\/documentation\/divar\/custompickerhandler\/pickerview(_:numberofrowsincomponent:)"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/CustomPickerHandler/pickerView(_:titleForRow:forComponent:)":{"role":"symbol","title":"pickerView(_:titleForRow:forComponent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pickerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"titleForRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/pickerView(_:titleForRow:forComponent:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pickerView:titleForRow:forComponent:"}],"url":"\/documentation\/divar\/custompickerhandler\/pickerview(_:titleforrow:forcomponent:)"},"doc://com.Divar.DivarClient/documentation/Divar/CustomPickerHandler/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/divar\/custompickerhandler\/init"},"doc://com.Divar.DivarClient/documentation/Divar/CustomPickerHandler/pickerView(_:didSelectRow:inComponent:)":{"role":"symbol","title":"pickerView(_:didSelectRow:inComponent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pickerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/pickerView(_:didSelectRow:inComponent:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pickerView:didSelectRow:inComponent:"}],"url":"\/documentation\/divar\/custompickerhandler\/pickerview(_:didselectrow:incomponent:)"},"doc://com.Divar.DivarClient/documentation/Divar/CustomPickerHandler/picker":{"role":"symbol","title":"picker","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"picker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/picker","kind":"symbol","type":"topic","url":"\/documentation\/divar\/custompickerhandler\/picker"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CustomPickerHandler"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CustomPickerHandler"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CustomPickerHandler"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/init","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/numberOfComponents(in:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/pickerView(_:didSelectRow:inComponent:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/pickerView(_:numberOfRowsInComponent:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/pickerView(_:titleForRow:forComponent:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CustomPickerHandler\/pickerView(_:viewForRow:forComponent:reusing:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)UIPickerViewDataSource","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPickerViewDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomPickerHandler"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomPickerHandler~1pickerView(_:viewForRow:forComponent:reusing:)\/title","value":"pickerView:viewForRow:forComponent:reusingView:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomPickerHandler~1pickerView(_:viewForRow:forComponent:reusing:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pickerView:viewForRow:forComponent:reusingView:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomPickerHandler\/title","value":"CustomPickerHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomPickerHandler\/fragments","value":[{"kind":"identifier","text":"CustomPickerHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomPickerHandler~1numberOfComponents(in:)\/title","value":"numberOfComponentsInPickerView:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomPickerHandler~1numberOfComponents(in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"numberOfComponentsInPickerView:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomPickerHandler~1pickerView(_:numberOfRowsInComponent:)\/title","value":"pickerView:numberOfRowsInComponent:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomPickerHandler~1pickerView(_:numberOfRowsInComponent:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pickerView:numberOfRowsInComponent:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomPickerHandler~1pickerView(_:titleForRow:forComponent:)\/title","value":"pickerView:titleForRow:forComponent:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomPickerHandler~1pickerView(_:titleForRow:forComponent:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pickerView:titleForRow:forComponent:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomPickerHandler~1pickerView(_:didSelectRow:inComponent:)\/title","value":"pickerView:didSelectRow:inComponent:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CustomPickerHandler~1pickerView(_:didSelectRow:inComponent:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pickerView:didSelectRow:inComponent:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}