{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisablePageViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/disablepageviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/disablepageviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseSegmentedViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisableListViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedNavigationBarPresenterProtocol"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/init(container:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/actionDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/navigationBarItems"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/barButtonItemButtonTapped(sender:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/barButtonItemTapped(sender:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/requestData()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/DisableListViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/WidgetBasedNavigationBarPresenterProtocol-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisablePageViewController"}],"title":"DisablePageViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)DisablePageViewController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"DisablePageViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/DisablePageViewController/DisableListViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"DisableListViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/DisableListViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/disablepageviewcontroller\/disablelistviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/ShowMessageProtocol":{"role":"symbol","title":"ShowMessageProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowMessageProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowMessageProtocol"}],"url":"\/documentation\/divar\/showmessageprotocol"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/ErrorMessageHandler":{"role":"symbol","title":"ErrorMessageHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorMessageHandler"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorMessageHandler"}],"url":"\/documentation\/divar\/errormessagehandler"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/DisablePageViewController/navigationBarItems":{"role":"symbol","title":"navigationBarItems","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationBarItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Widgets_NavigationBar","preciseIdentifier":"s:19DivarInterfaceSwift21Widgets_NavigationBarV"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/navigationBarItems","kind":"symbol","type":"topic","url":"\/documentation\/divar\/disablepageviewcontroller\/navigationbaritems"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/documentation/Divar/DisablePageViewController/barButtonItemButtonTapped(sender:)":{"role":"symbol","title":"barButtonItemButtonTapped(sender:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barButtonItemButtonTapped"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/barButtonItemButtonTapped(sender:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"barButtonItemButtonTappedWithSender:"}],"url":"\/documentation\/divar\/disablepageviewcontroller\/barbuttonitembuttontapped(sender:)"},"doc://com.Divar.DivarClient/documentation/Divar/DisablePageViewController":{"role":"symbol","title":"DisablePageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisablePageViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DisablePageViewController"}],"url":"\/documentation\/divar\/disablepageviewcontroller"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/DisablePageViewController/actionDelegate":{"role":"symbol","title":"actionDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WidgetBasedActionDelegate","preciseIdentifier":"s:5Divar25WidgetBasedActionDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/actionDelegate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/disablepageviewcontroller\/actiondelegate"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/documentation/Divar/DisablePageViewController/requestData()":{"role":"symbol","title":"requestData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestData"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/requestData()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/disablepageviewcontroller\/requestdata()"},"doc://com.Divar.DivarClient/documentation/Divar/DisablePageViewController/barButtonItemTapped(sender:)":{"role":"symbol","title":"barButtonItemTapped(sender:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barButtonItemTapped"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/barButtonItemTapped(sender:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"barButtonItemTappedWithSender:"}],"url":"\/documentation\/divar\/disablepageviewcontroller\/barbuttonitemtapped(sender:)"},"doc://com.Divar.DivarClient/documentation/Divar/DisablePageViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/disablepageviewcontroller\/init(coder:)"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/DisablePageViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/disablepageviewcontroller\/viewdidload()"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/documentation/Divar/ShowErrorProtocol":{"role":"symbol","title":"ShowErrorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowErrorProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowErrorProtocol"}],"url":"\/documentation\/divar\/showerrorprotocol"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/documentation/Divar/PaymentSystemProtocol":{"role":"symbol","title":"PaymentSystemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSystemProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaymentSystemProtocol"}],"url":"\/documentation\/divar\/paymentsystemprotocol"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/TooltipPresenter":{"role":"symbol","title":"TooltipPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TooltipPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TooltipPresenter"}],"url":"\/documentation\/divar\/tooltippresenter"},"doc://com.Divar.DivarClient/documentation/Divar/DisablePageViewController/init(container:)":{"role":"symbol","title":"init(container:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DisablePageViewControllerDIContainer","preciseIdentifier":"s:5Divar36DisablePageViewControllerDIContainera"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/init(container:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/disablepageviewcontroller\/init(container:)"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedNavigationBarPresenterProtocol":{"role":"symbol","title":"WidgetBasedNavigationBarPresenterProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedNavigationBarPresenterProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedNavigationBarPresenterProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedNavigationBarPresenterProtocol"}],"url":"\/documentation\/divar\/widgetbasednavigationbarpresenterprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/DisableListViewControllerDelegate":{"role":"symbol","title":"DisableListViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisableListViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisableListViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DisableListViewControllerDelegate"}],"url":"\/documentation\/divar\/disablelistviewcontrollerdelegate"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/BaseSegmentedViewController":{"role":"symbol","title":"BaseSegmentedViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseSegmentedViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseSegmentedViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseSegmentedViewController"}],"url":"\/documentation\/divar\/basesegmentedviewcontroller"},"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/DisablePageViewController/WidgetBasedNavigationBarPresenterProtocol-Implementations":{"role":"collectionGroup","title":"WidgetBasedNavigationBarPresenterProtocol Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/WidgetBasedNavigationBarPresenterProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/disablepageviewcontroller\/widgetbasednavigationbarpresenterprotocol-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DisablePageViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DisablePageViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DisablePageViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/barButtonItemButtonTapped(sender:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/barButtonItemTapped(sender:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseSegmentedViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisablePageViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseSegmentedViewController","preciseIdentifier":"c:@M@Divar@objc(cs)BaseSegmentedViewController","text":"BaseSegmentedViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DisablePageViewController~1barButtonItemButtonTapped(sender:)\/title","value":"barButtonItemButtonTappedWithSender:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DisablePageViewController~1barButtonItemButtonTapped(sender:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"barButtonItemButtonTappedWithSender:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DisablePageViewController\/title","value":"DisablePageViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DisablePageViewController\/fragments","value":[{"kind":"identifier","text":"DisablePageViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DisablePageViewController~1barButtonItemTapped(sender:)\/title","value":"barButtonItemTappedWithSender:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DisablePageViewController~1barButtonItemTapped(sender:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"barButtonItemTappedWithSender:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DisablePageViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DisablePageViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DisablePageViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DisablePageViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseSegmentedViewController\/title","value":"BaseSegmentedViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseSegmentedViewController\/fragments","value":[{"kind":"identifier","text":"BaseSegmentedViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}