{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DistrictMultiPolygon"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/districtmultipolygon"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/districtmultipolygon"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)MKMultiPolygon"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)MKAnnotation","doc:\/\/com.Divar.DivarClient\/objc(pl)MKGeoJSONObject","doc:\/\/com.Divar.DivarClient\/objc(pl)MKOverlay","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictMultiPolygon","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictMultiPolygon\/init(districts:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictMultiPolygon\/districts","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictMultiPolygon\/isSelected"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"DistrictMultiPolygon"}],"role":"symbol","title":"DistrictMultiPolygon","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DistrictMultiPolygon"}],"symbolKind":"class","externalID":"c:@M@Divar@objc(cs)DistrictMultiPolygon","modules":[{"name":"Divar"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/DistrictMultiPolygon/districts":{"role":"symbol","title":"districts","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"districts"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DistrictPolygon","preciseIdentifier":"c:@M@Divar@objc(cs)DistrictPolygon"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictMultiPolygon\/districts","kind":"symbol","type":"topic","url":"\/documentation\/divar\/districtmultipolygon\/districts"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/DistrictMultiPolygon/init(districts:)":{"role":"symbol","title":"init(districts:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"districts"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DistrictPolygon","preciseIdentifier":"c:@M@Divar@objc(cs)DistrictPolygon"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictMultiPolygon\/init(districts:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/districtmultipolygon\/init(districts:)"},"doc://com.Divar.DivarClient/documentation/Divar/DistrictMultiPolygon/isSelected":{"role":"symbol","title":"isSelected","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSelected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictMultiPolygon\/isSelected","kind":"symbol","type":"topic","url":"\/documentation\/divar\/districtmultipolygon\/isselected"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/objc(pl)MKAnnotation":{"type":"unresolvable","title":"MapKit.MKAnnotation","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)MKAnnotation"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/objc(pl)MKOverlay":{"type":"unresolvable","title":"MapKit.MKOverlay","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)MKOverlay"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/objc(cs)MKMultiPolygon":{"type":"unresolvable","title":"MKMultiPolygon","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)MKMultiPolygon"},"doc://com.Divar.DivarClient/documentation/Divar/DistrictMultiPolygon":{"role":"symbol","title":"DistrictMultiPolygon","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DistrictMultiPolygon"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictMultiPolygon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DistrictMultiPolygon"}],"url":"\/documentation\/divar\/districtmultipolygon"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/objc(pl)MKGeoJSONObject":{"type":"unresolvable","title":"MapKit.MKGeoJSONObject","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)MKGeoJSONObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DistrictMultiPolygon"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DistrictMultiPolygon"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DistrictMultiPolygon"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)MKMultiPolygon"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DistrictMultiPolygon"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"MKMultiPolygon","preciseIdentifier":"c:objc(cs)MKMultiPolygon"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictMultiPolygon\/title","value":"DistrictMultiPolygon"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictMultiPolygon\/fragments","value":[{"kind":"identifier","text":"DistrictMultiPolygon"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}