{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DistrictPolygon"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/districtpolygon"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/districtpolygon"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)MKPolygon"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)MKAnnotation","doc:\/\/com.Divar.DivarClient\/objc(pl)MKGeoJSONObject","doc:\/\/com.Divar.DivarClient\/objc(pl)MKOverlay","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictPolygon","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictPolygon\/id","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictPolygon\/isSelected","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictPolygon\/name"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictPolygon\/contains(_:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictPolygon\/polygonForFeature(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DistrictPolygon"}],"title":"DistrictPolygon","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)DistrictPolygon","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"DistrictPolygon"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/DistrictPolygon/contains(_:)":{"role":"symbol","title":"contains(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contains"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapPoint","preciseIdentifier":"c:@SA@MKMapPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictPolygon\/contains(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/districtpolygon\/contains(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/DistrictPolygon/id":{"role":"symbol","title":"id","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictPolygon\/id","kind":"symbol","type":"topic","url":"\/documentation\/divar\/districtpolygon\/id"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/DistrictPolygon":{"role":"symbol","title":"DistrictPolygon","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DistrictPolygon"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictPolygon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DistrictPolygon"}],"url":"\/documentation\/divar\/districtpolygon"},"doc://com.Divar.DivarClient/documentation/Divar/DistrictPolygon/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictPolygon\/name","kind":"symbol","type":"topic","url":"\/documentation\/divar\/districtpolygon\/name"},"doc://com.Divar.DivarClient/objc(pl)MKGeoJSONObject":{"type":"unresolvable","title":"MapKit.MKGeoJSONObject","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)MKGeoJSONObject"},"doc://com.Divar.DivarClient/objc(pl)MKOverlay":{"type":"unresolvable","title":"MapKit.MKOverlay","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)MKOverlay"},"doc://com.Divar.DivarClient/documentation/Divar/DistrictPolygon/isSelected":{"role":"symbol","title":"isSelected","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSelected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictPolygon\/isSelected","kind":"symbol","type":"topic","url":"\/documentation\/divar\/districtpolygon\/isselected"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/objc(pl)MKAnnotation":{"type":"unresolvable","title":"MapKit.MKAnnotation","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)MKAnnotation"},"doc://com.Divar.DivarClient/documentation/Divar/DistrictPolygon/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictPolygon\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/divar\/districtpolygon\/init"},"doc://com.Divar.DivarClient/objc(cs)MKPolygon":{"type":"unresolvable","title":"MKPolygon","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)MKPolygon"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/DistrictPolygon/polygonForFeature(_:)":{"role":"symbol","title":"polygonForFeature(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygonForFeature"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Naghshe_Feature","preciseIdentifier":"s:19DivarInterfaceSwift15Naghshe_FeatureV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"DistrictPolygon","preciseIdentifier":"c:@M@Divar@objc(cs)DistrictPolygon"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictPolygon\/polygonForFeature(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/districtpolygon\/polygonforfeature(_:)"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DistrictPolygon"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DistrictPolygon"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DistrictPolygon"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictPolygon\/init"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)MKPolygon"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DistrictPolygon"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"MKPolygon","preciseIdentifier":"c:objc(cs)MKPolygon"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictPolygon\/title","value":"DistrictPolygon"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictPolygon\/fragments","value":[{"kind":"identifier","text":"DistrictPolygon"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}