{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DivarSplashView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/divarsplashview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/divarsplashview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/objc(pl)CAAnimationDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)CALayerDelegate","doc:\/\/com.Divar.DivarClient\/6Sonnat23WithInitializerProtocolP","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearance","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UICoordinateSpace","doc:\/\/com.Divar.DivarClient\/objc(pl)UIDynamicItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItemContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UILargeContentViewerItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/init(bezierPath:backgroundColor:logoColor:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/init(bezierPath:backgroundWithGradientFromTopColor:bottomColor:logoColor:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/init(coder:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/animationCompletionHandler","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/durationAnimation","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/gradientLayer","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/logoAnimation","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/sizeScale"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/animationDidStop(_:finished:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/configureLayerWithLogo(from:withGradientFromTopColor:bottomColor:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/createGradientLayerWithGradient(fromTopColor:bottomColor:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/getLayerFrom(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/layerSizeRect()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/mutableLogoPath()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/startAnimation(completionHandler:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DivarSplashView"}],"title":"DivarSplashView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)DivarSplashView","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"DivarSplashView"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearance"},"doc://com.Divar.DivarClient/documentation/Divar/DivarSplashView/sizeScale":{"role":"symbol","title":"sizeScale","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeScale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/sizeScale","kind":"symbol","type":"topic","url":"\/documentation\/divar\/divarsplashview\/sizescale"},"doc://com.Divar.DivarClient/documentation/Divar/DivarSplashView/mutableLogoPath()":{"role":"symbol","title":"mutableLogoPath()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mutableLogoPath"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CGMutablePath","preciseIdentifier":"c:@T@CGMutablePathRef"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/mutableLogoPath()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/divarsplashview\/mutablelogopath()"},"doc://com.Divar.DivarClient/documentation/Divar/DivarSplashView/animationCompletionHandler":{"role":"symbol","title":"animationCompletionHandler","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationCompletionHandler"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/animationCompletionHandler","kind":"symbol","type":"topic","url":"\/documentation\/divar\/divarsplashview\/animationcompletionhandler"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.Divar.DivarClient/documentation/Divar/DivarSplashView/startAnimation(completionHandler:)":{"role":"symbol","title":"startAnimation(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startAnimation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/startAnimation(completionHandler:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/divarsplashview\/startanimation(completionhandler:)"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/DivarSplashView/getLayerFrom(_:)":{"role":"symbol","title":"getLayerFrom(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLayerFrom"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CAShapeLayer","preciseIdentifier":"c:objc(cs)CAShapeLayer"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/getLayerFrom(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/divarsplashview\/getlayerfrom(_:)"},"doc://com.Divar.DivarClient/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItemContainer"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/DivarSplashView/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/divarsplashview\/init(coder:)"},"doc://com.Divar.DivarClient/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAccessibilityIdentification"},"doc://com.Divar.DivarClient/documentation/Divar/DivarSplashView/durationAnimation":{"role":"symbol","title":"durationAnimation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"durationAnimation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/durationAnimation","kind":"symbol","type":"topic","url":"\/documentation\/divar\/divarsplashview\/durationanimation"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/documentation/Divar/DivarSplashView/configureLayerWithLogo(from:withGradientFromTopColor:bottomColor:)":{"role":"symbol","title":"configureLayerWithLogo(from:withGradientFromTopColor:bottomColor:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configureLayerWithLogo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withGradientFromTopColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bottomColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CAGradientLayer","preciseIdentifier":"c:objc(cs)CAGradientLayer"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/configureLayerWithLogo(from:withGradientFromTopColor:bottomColor:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/divarsplashview\/configurelayerwithlogo(from:withgradientfromtopcolor:bottomcolor:)"},"doc://com.Divar.DivarClient/documentation/Divar/DivarSplashView/init(bezierPath:backgroundWithGradientFromTopColor:bottomColor:logoColor:)":{"role":"symbol","title":"init(bezierPath:backgroundWithGradientFromTopColor:bottomColor:logoColor:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bezierPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath"},{"kind":"text","text":", "},{"kind":"externalParam","text":"backgroundWithGradientFromTopColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bottomColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"logoColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/init(bezierPath:backgroundWithGradientFromTopColor:bottomColor:logoColor:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/divarsplashview\/init(bezierpath:backgroundwithgradientfromtopcolor:bottomcolor:logocolor:)"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)UIView"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UILargeContentViewerItem"},"doc://com.Divar.DivarClient/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItem"},"doc://com.Divar.DivarClient/documentation/Divar/DivarSplashView/init(bezierPath:backgroundColor:logoColor:)":{"role":"symbol","title":"init(bezierPath:backgroundColor:logoColor:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bezierPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath"},{"kind":"text","text":", "},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"logoColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/init(bezierPath:backgroundColor:logoColor:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/divarsplashview\/init(bezierpath:backgroundcolor:logocolor:)"},"doc://com.Divar.DivarClient/documentation/Divar/DivarSplashView/animationDidStop(_:finished:)":{"role":"symbol","title":"animationDidStop(_:finished:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationDidStop"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CAAnimation","preciseIdentifier":"c:objc(cs)CAAnimation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"finished"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/animationDidStop(_:finished:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animationDidStop:finished:"}],"url":"\/documentation\/divar\/divarsplashview\/animationdidstop(_:finished:)"},"doc://com.Divar.DivarClient/documentation/Divar/DivarSplashView/logoAnimation":{"role":"symbol","title":"logoAnimation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logoAnimation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CAAnimation","preciseIdentifier":"c:objc(cs)CAAnimation"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/logoAnimation","kind":"symbol","type":"topic","url":"\/documentation\/divar\/divarsplashview\/logoanimation"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)CALayerDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/DivarSplashView":{"role":"symbol","title":"DivarSplashView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DivarSplashView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DivarSplashView"}],"url":"\/documentation\/divar\/divarsplashview"},"doc://com.Divar.DivarClient/documentation/Divar/DivarSplashView/layerSizeRect()":{"role":"symbol","title":"layerSizeRect()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layerSizeRect"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/layerSizeRect()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/divarsplashview\/layersizerect()"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/DivarSplashView/gradientLayer":{"role":"symbol","title":"gradientLayer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gradientLayer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CALayer","preciseIdentifier":"c:objc(cs)CALayer"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/gradientLayer","kind":"symbol","type":"topic","url":"\/documentation\/divar\/divarsplashview\/gradientlayer"},"doc://com.Divar.DivarClient/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIDynamicItem"},"doc://com.Divar.DivarClient/documentation/Divar/DivarSplashView/createGradientLayerWithGradient(fromTopColor:bottomColor:)":{"role":"symbol","title":"createGradientLayerWithGradient(fromTopColor:bottomColor:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createGradientLayerWithGradient"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromTopColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bottomColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CAGradientLayer","preciseIdentifier":"c:objc(cs)CAGradientLayer"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/createGradientLayerWithGradient(fromTopColor:bottomColor:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/divarsplashview\/creategradientlayerwithgradient(fromtopcolor:bottomcolor:)"},"doc://com.Divar.DivarClient/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UICoordinateSpace"},"doc://com.Divar.DivarClient/6Sonnat23WithInitializerProtocolP":{"type":"unresolvable","title":"Sonnat.WithInitializerProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat23WithInitializerProtocolP"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/objc(pl)CAAnimationDelegate":{"type":"unresolvable","title":"CAAnimationDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)CAAnimationDelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DivarSplashView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DivarSplashView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DivarSplashView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/animationDidStop(_:finished:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DivarSplashView\/init(coder:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)CAAnimationDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DivarSplashView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DivarSplashView~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DivarSplashView~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DivarSplashView~1animationDidStop(_:finished:)\/title","value":"animationDidStop:finished:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DivarSplashView~1animationDidStop(_:finished:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animationDidStop:finished:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DivarSplashView\/title","value":"DivarSplashView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DivarSplashView\/fragments","value":[{"kind":"identifier","text":"DivarSplashView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}