{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Environment"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/environment"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/environment"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/EnvironmentProtocol","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/getLocation(action:)-swift.method"]},{"title":"Type Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/OSName","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/OSVersion","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/appName","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/appStartTime","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/buildNumber","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/bundleIdentifier","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/cachedLocation","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/careersInfo","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/devicModel","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/deviceBrand","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/deviceId","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/deviceLocale","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/deviceResolution","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/divarVersion","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/freeDiskSpaceInBytes","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/freeMemoryInBytes","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/hasCachedLocation","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/isDarkMode","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/isLowMemoryState","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/isRooted","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/isSimulator","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/phoneISO","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/screenPPI","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/timezone","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/totalDiskSpaceInBytes","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/totalDiskSpaceInGB","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/totalMemoryInBytes","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/usedDiskSpaceInBytes","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/usedMemoryInBytes","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/versionName"]},{"title":"Type Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/getLocation(action:)-swift.type.method","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/userAgent()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Environment"}],"title":"Environment","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)Environment","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"Environment"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/Environment/screenPPI":{"role":"symbol","title":"screenPPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"screenPPI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/screenPPI","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/screenppi"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/isSimulator":{"role":"symbol","title":"isSimulator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSimulator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/isSimulator","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/issimulator"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/devicModel":{"role":"symbol","title":"devicModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"devicModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/devicModel","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/devicmodel"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/freeDiskSpaceInBytes":{"role":"symbol","title":"freeDiskSpaceInBytes","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"freeDiskSpaceInBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/freeDiskSpaceInBytes","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/freediskspaceinbytes"},"doc://com.Divar.DivarClient/documentation/Divar/EnvironmentProtocol":{"role":"symbol","title":"EnvironmentProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnvironmentProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/EnvironmentProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EnvironmentProtocol"}],"url":"\/documentation\/divar\/environmentprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/divarVersion":{"role":"symbol","title":"divarVersion","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"divarVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/divarVersion","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/divarversion"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/buildNumber":{"role":"symbol","title":"buildNumber","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/buildNumber","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/buildnumber"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/usedMemoryInBytes":{"role":"symbol","title":"usedMemoryInBytes","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"usedMemoryInBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/usedMemoryInBytes","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/usedmemoryinbytes"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/appName":{"role":"symbol","title":"appName","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/appName","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/appname"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/hasCachedLocation":{"role":"symbol","title":"hasCachedLocation","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasCachedLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/hasCachedLocation","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/hascachedlocation"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/freeMemoryInBytes":{"role":"symbol","title":"freeMemoryInBytes","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"freeMemoryInBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/freeMemoryInBytes","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/freememoryinbytes"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/careersInfo":{"role":"symbol","title":"careersInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"careersInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ActionLog_ClientMetaInfo","preciseIdentifier":"s:19DivarInterfaceSwift24ActionLog_ClientMetaInfoV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"MobileOperatorInfo","preciseIdentifier":"s:19DivarInterfaceSwift24ActionLog_ClientMetaInfoV014MobileOperatorH0V"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/careersInfo","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/careersinfo"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/deviceResolution":{"role":"symbol","title":"deviceResolution","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceResolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/deviceResolution","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/deviceresolution"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/cachedLocation":{"role":"symbol","title":"cachedLocation","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cachedLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/cachedLocation","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/cachedlocation"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/deviceId":{"role":"symbol","title":"deviceId","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/deviceId","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/deviceid"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/deviceBrand":{"role":"symbol","title":"deviceBrand","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceBrand"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/deviceBrand","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/devicebrand"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/OSVersion":{"role":"symbol","title":"OSVersion","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"OSVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/OSVersion","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/osversion"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/deviceLocale":{"role":"symbol","title":"deviceLocale","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceLocale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/deviceLocale","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/devicelocale"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/getLocation(action:)-swift.method":{"role":"symbol","title":"getLocation(action:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/getLocation(action:)-swift.method","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/getlocation(action:)-swift.method"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/totalDiskSpaceInGB":{"role":"symbol","title":"totalDiskSpaceInGB","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalDiskSpaceInGB"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/totalDiskSpaceInGB","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/totaldiskspaceingb"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/versionName":{"role":"symbol","title":"versionName","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"versionName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/versionName","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/versionname"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/isDarkMode":{"role":"symbol","title":"isDarkMode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDarkMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/isDarkMode","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/isdarkmode"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/getLocation(action:)-swift.type.method":{"role":"symbol","title":"getLocation(action:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/getLocation(action:)-swift.type.method","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/getlocation(action:)-swift.type.method"},"doc://com.Divar.DivarClient/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/OSName":{"role":"symbol","title":"OSName","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"OSName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/OSName","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/osname"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/appStartTime":{"role":"symbol","title":"appStartTime","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appStartTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/appStartTime","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/appstarttime"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/timezone":{"role":"symbol","title":"timezone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timezone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/timezone","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/timezone"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/phoneISO":{"role":"symbol","title":"phoneISO","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"phoneISO"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/phoneISO","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/phoneiso"},"doc://com.Divar.DivarClient/documentation/Divar/Environment":{"role":"symbol","title":"Environment","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Environment"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Environment"}],"url":"\/documentation\/divar\/environment"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/divar\/environment\/init"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/usedDiskSpaceInBytes":{"role":"symbol","title":"usedDiskSpaceInBytes","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"usedDiskSpaceInBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/usedDiskSpaceInBytes","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/useddiskspaceinbytes"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/totalMemoryInBytes":{"role":"symbol","title":"totalMemoryInBytes","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalMemoryInBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/totalMemoryInBytes","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/totalmemoryinbytes"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/isLowMemoryState":{"role":"symbol","title":"isLowMemoryState","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLowMemoryState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/isLowMemoryState","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/islowmemorystate"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/isRooted":{"role":"symbol","title":"isRooted","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRooted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/isRooted","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/isrooted"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/userAgent()":{"role":"symbol","title":"userAgent()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userAgent"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/userAgent()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/useragent()"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/totalDiskSpaceInBytes":{"role":"symbol","title":"totalDiskSpaceInBytes","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalDiskSpaceInBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/totalDiskSpaceInBytes","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/totaldiskspaceinbytes"},"doc://com.Divar.DivarClient/documentation/Divar/Environment/bundleIdentifier":{"role":"symbol","title":"bundleIdentifier","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bundleIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/bundleIdentifier","kind":"symbol","type":"topic","url":"\/documentation\/divar\/environment\/bundleidentifier"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"Environment"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Environment"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Environment"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Environment\/init"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"Environment"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1Environment\/title","value":"Environment"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1Environment\/fragments","value":[{"kind":"identifier","text":"Environment"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}