{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeatureRowCollectionViewCell"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/featurerowcollectionviewcell"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/featurerowcollectionviewcell"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/objc(pl)CALayerDelegate","doc:\/\/com.Divar.DivarClient\/6Sonnat12ReusableCellP","doc:\/\/com.Divar.DivarClient\/6Sonnat23WithInitializerProtocolP","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearance","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UICoordinateSpace","doc:\/\/com.Divar.DivarClient\/objc(pl)UIDynamicItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItemContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UILargeContentViewerItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCellConfigurable"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/contentRightConstraint","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/divider","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/dividerRightConstraint","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/imageView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/imageWidthConstraint","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/indicatorImage","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/isHighlighted","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/leftConstraint","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/rightConstraint","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/titleLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/awakeFromNib()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/fill(with:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/prepareCell(with:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeatureRowCollectionViewCell"}],"title":"FeatureRowCollectionViewCell","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)FeatureRowCollectionViewCell","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"FeatureRowCollectionViewCell"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/FeatureRowCollectionViewCell/isHighlighted":{"role":"symbol","title":"isHighlighted","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHighlighted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/isHighlighted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"highlighted"}],"url":"\/documentation\/divar\/featurerowcollectionviewcell\/ishighlighted"},"doc://com.Divar.DivarClient/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)CALayerDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/FeatureRowCollectionViewCell/indicatorImage":{"role":"symbol","title":"indicatorImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"indicatorImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SonnatImageView","preciseIdentifier":"c:@M@Sonnat@objc(cs)SonnatImageView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/indicatorImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"indicatorImage"}],"url":"\/documentation\/divar\/featurerowcollectionviewcell\/indicatorimage"},"doc://com.Divar.DivarClient/documentation/Divar/FeatureRowCollectionViewCell/fill(with:)":{"role":"symbol","title":"fill(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fill"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_FeatureRowData","preciseIdentifier":"s:19DivarInterfaceSwift22Widgets_FeatureRowDataV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/fill(with:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/featurerowcollectionviewcell\/fill(with:)"},"doc://com.Divar.DivarClient/documentation/Divar/FeatureRowCollectionViewCell":{"role":"symbol","title":"FeatureRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeatureRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeatureRowCollectionViewCell"}],"url":"\/documentation\/divar\/featurerowcollectionviewcell"},"doc://com.Divar.DivarClient/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.Divar.DivarClient/documentation/Divar/FeatureRowCollectionViewCell/leftConstraint":{"role":"symbol","title":"leftConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/leftConstraint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leftConstraint"}],"url":"\/documentation\/divar\/featurerowcollectionviewcell\/leftconstraint"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/6Sonnat12ReusableCellP":{"type":"unresolvable","title":"Sonnat.ReusableCell","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat12ReusableCellP"},"doc://com.Divar.DivarClient/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UICoordinateSpace"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/FeatureRowCollectionViewCell/dividerRightConstraint":{"role":"symbol","title":"dividerRightConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dividerRightConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/dividerRightConstraint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dividerRightConstraint"}],"url":"\/documentation\/divar\/featurerowcollectionviewcell\/dividerrightconstraint"},"doc://com.Divar.DivarClient/documentation/Divar/FeatureRowCollectionViewCell/prepareCell(with:)":{"role":"symbol","title":"prepareCell(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareCell"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Widget","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_WidgetV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/prepareCell(with:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/featurerowcollectionviewcell\/preparecell(with:)"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetCellConfigurable":{"role":"symbol","title":"WidgetCellConfigurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetCellConfigurable"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCellConfigurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetCellConfigurable"}],"url":"\/documentation\/divar\/widgetcellconfigurable"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItemContainer"},"doc://com.Divar.DivarClient/documentation/Divar/FeatureRowCollectionViewCell/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/featurerowcollectionviewcell\/initwithcoder:"},"doc://com.Divar.DivarClient/documentation/Divar/FeatureRowCollectionViewCell/imageWidthConstraint":{"role":"symbol","title":"imageWidthConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageWidthConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/imageWidthConstraint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageWidthConstraint"}],"url":"\/documentation\/divar\/featurerowcollectionviewcell\/imagewidthconstraint"},"doc://com.Divar.DivarClient/documentation/Divar/FeatureRowCollectionViewCell/divider":{"role":"symbol","title":"divider","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"divider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/divider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"divider"}],"url":"\/documentation\/divar\/featurerowcollectionviewcell\/divider"},"doc://com.Divar.DivarClient/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItem"},"doc://com.Divar.DivarClient/documentation/Divar/FeatureRowCollectionViewCell/rightConstraint":{"role":"symbol","title":"rightConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/rightConstraint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rightConstraint"}],"url":"\/documentation\/divar\/featurerowcollectionviewcell\/rightconstraint"},"doc://com.Divar.DivarClient/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIDynamicItem"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetCell":{"role":"symbol","title":"WidgetCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetCell"}],"url":"\/documentation\/divar\/widgetcell"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearance"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/FeatureRowCollectionViewCell/titleLabel":{"role":"symbol","title":"titleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/titleLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleLabel"}],"url":"\/documentation\/divar\/featurerowcollectionviewcell\/titlelabel"},"doc://com.Divar.DivarClient/documentation/Divar/FeatureRowCollectionViewCell/imageView":{"role":"symbol","title":"imageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SonnatImageView","preciseIdentifier":"c:@M@Sonnat@objc(cs)SonnatImageView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/imageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageView"}],"url":"\/documentation\/divar\/featurerowcollectionviewcell\/imageview"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAccessibilityIdentification"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/FeatureRowCollectionViewCell/awakeFromNib()":{"role":"symbol","title":"awakeFromNib()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/awakeFromNib()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"awakeFromNib"}],"url":"\/documentation\/divar\/featurerowcollectionviewcell\/awakefromnib()"},"doc://com.Divar.DivarClient/documentation/Divar/FeatureRowCollectionViewCell/initWithFrame:":{"role":"symbol","title":"initWithFrame:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/initWithFrame:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/divar\/featurerowcollectionviewcell\/initwithframe:"},"doc://com.Divar.DivarClient/6Sonnat23WithInitializerProtocolP":{"type":"unresolvable","title":"Sonnat.WithInitializerProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat23WithInitializerProtocolP"},"doc://com.Divar.DivarClient/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UILargeContentViewerItem"},"doc://com.Divar.DivarClient/documentation/Divar/FeatureRowCollectionViewCell/contentRightConstraint":{"role":"symbol","title":"contentRightConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentRightConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/contentRightConstraint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contentRightConstraint"}],"url":"\/documentation\/divar\/featurerowcollectionviewcell\/contentrightconstraint"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FeatureRowCollectionViewCell"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FeatureRowCollectionViewCell"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FeatureRowCollectionViewCell"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/contentRightConstraint","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/divider","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/dividerRightConstraint","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/imageView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/imageWidthConstraint","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/indicatorImage","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/isHighlighted","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/leftConstraint","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/rightConstraint","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/titleLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/awakeFromNib()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/initWithCoder:","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell\/initWithFrame:"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeatureRowCollectionViewCell"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCell","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetCell","text":"WidgetCell"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell~1isHighlighted\/title","value":"highlighted"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell~1isHighlighted\/fragments","value":[{"kind":"identifier","text":"highlighted"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell~1indicatorImage\/title","value":"indicatorImage"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell~1indicatorImage\/fragments","value":[{"kind":"identifier","text":"indicatorImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell\/title","value":"FeatureRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"FeatureRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell~1leftConstraint\/title","value":"leftConstraint"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell~1leftConstraint\/fragments","value":[{"kind":"identifier","text":"leftConstraint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell~1dividerRightConstraint\/title","value":"dividerRightConstraint"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell~1dividerRightConstraint\/fragments","value":[{"kind":"identifier","text":"dividerRightConstraint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell~1imageWidthConstraint\/title","value":"imageWidthConstraint"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell~1imageWidthConstraint\/fragments","value":[{"kind":"identifier","text":"imageWidthConstraint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell~1divider\/title","value":"divider"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell~1divider\/fragments","value":[{"kind":"identifier","text":"divider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell~1rightConstraint\/title","value":"rightConstraint"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell~1rightConstraint\/fragments","value":[{"kind":"identifier","text":"rightConstraint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetCell\/title","value":"WidgetCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetCell\/fragments","value":[{"kind":"identifier","text":"WidgetCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell~1titleLabel\/title","value":"titleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell~1titleLabel\/fragments","value":[{"kind":"identifier","text":"titleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell~1imageView\/title","value":"imageView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell~1imageView\/fragments","value":[{"kind":"identifier","text":"imageView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell~1awakeFromNib()\/title","value":"awakeFromNib"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell~1awakeFromNib()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"awakeFromNib"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell~1contentRightConstraint\/title","value":"contentRightConstraint"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell~1contentRightConstraint\/fragments","value":[{"kind":"identifier","text":"contentRightConstraint"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}