{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeedbackAlertViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/feedbackalertviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/feedbackalertviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UICollectionViewDataSource","doc:\/\/com.Divar.DivarClient\/objc(pl)UICollectionViewDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UICollectionViewDelegateFlowLayout","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIScrollViewDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/init(title:allowTapToDismiss:allowDragToDismiss:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/allowsDragToDismiss-4g799","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/allowsTapToDismiss-2ghe7","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/collectionView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/cornerRadius-74a4r","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/delegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/isSelected","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/longFormHeight-37kgv","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/numberOfSelectedStars","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/panScrollable","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/shouldRoundTopCorners-2l5pq","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/submitButton","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/titleLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/PanModalPresentable-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/UICollectionViewDataSource-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/UICollectionViewDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/UICollectionViewDelegateFlowLayout-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeedbackAlertViewController"}],"title":"FeedbackAlertViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)FeedbackAlertViewController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"FeedbackAlertViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIScrollViewDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController/allowsTapToDismiss-2ghe7":{"role":"symbol","title":"allowsTapToDismiss","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsTapToDismiss"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/allowsTapToDismiss-2ghe7","kind":"symbol","type":"topic","url":"\/documentation\/divar\/feedbackalertviewcontroller\/allowstaptodismiss-2ghe7"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable":{"role":"symbol","title":"PanModalPresentable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresentable"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresentable"}],"url":"\/documentation\/divar\/panmodalpresentable"},"doc://com.Divar.DivarClient/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)UIViewController"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController/numberOfSelectedStars":{"role":"symbol","title":"numberOfSelectedStars","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfSelectedStars"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/numberOfSelectedStars","kind":"symbol","type":"topic","url":"\/documentation\/divar\/feedbackalertviewcontroller\/numberofselectedstars"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController/submitButton":{"role":"symbol","title":"submitButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"submitButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SecondaryButton","preciseIdentifier":"c:@M@Divar@objc(cs)SecondaryButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/submitButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"submitButton"}],"url":"\/documentation\/divar\/feedbackalertviewcontroller\/submitbutton"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController/PanModalPresentable-Implementations":{"role":"collectionGroup","title":"PanModalPresentable Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/PanModalPresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/feedbackalertviewcontroller\/panmodalpresentable-implementations"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController/UICollectionViewDataSource-Implementations":{"role":"collectionGroup","title":"UICollectionViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/UICollectionViewDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/feedbackalertviewcontroller\/uicollectionviewdatasource-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController/collectionView":{"role":"symbol","title":"collectionView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/collectionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView"}],"url":"\/documentation\/divar\/feedbackalertviewcontroller\/collectionview"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController/cornerRadius-74a4r":{"role":"symbol","title":"cornerRadius","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/cornerRadius-74a4r","kind":"symbol","type":"topic","url":"\/documentation\/divar\/feedbackalertviewcontroller\/cornerradius-74a4r"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController/titleLabel":{"role":"symbol","title":"titleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/titleLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleLabel"}],"url":"\/documentation\/divar\/feedbackalertviewcontroller\/titlelabel"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController/init(title:allowTapToDismiss:allowDragToDismiss:)":{"role":"symbol","title":"init(title:allowTapToDismiss:allowDragToDismiss:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowTapToDismiss"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowDragToDismiss"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/init(title:allowTapToDismiss:allowDragToDismiss:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/feedbackalertviewcontroller\/init(title:allowtaptodismiss:allowdragtodismiss:)"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController/longFormHeight-37kgv":{"role":"symbol","title":"longFormHeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"longFormHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PanModalHeight","preciseIdentifier":"s:5Divar14PanModalHeightO"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/longFormHeight-37kgv","kind":"symbol","type":"topic","url":"\/documentation\/divar\/feedbackalertviewcontroller\/longformheight-37kgv"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FeedbackAlertViewControllerDelegate","preciseIdentifier":"s:5Divar35FeedbackAlertViewControllerDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/feedbackalertviewcontroller\/delegate"},"doc://com.Divar.DivarClient/objc(pl)UICollectionViewDelegate":{"type":"unresolvable","title":"UIKit.UICollectionViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UICollectionViewDelegate"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController/UICollectionViewDelegate-Implementations":{"role":"collectionGroup","title":"UICollectionViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/UICollectionViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/feedbackalertviewcontroller\/uicollectionviewdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/feedbackalertviewcontroller\/viewdidload()"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/feedbackalertviewcontroller\/init(coder:)"},"doc://com.Divar.DivarClient/objc(pl)UICollectionViewDataSource":{"type":"unresolvable","title":"UIKit.UICollectionViewDataSource","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UICollectionViewDataSource"},"doc://com.Divar.DivarClient/objc(pl)UICollectionViewDelegateFlowLayout":{"type":"unresolvable","title":"UIKit.UICollectionViewDelegateFlowLayout","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UICollectionViewDelegateFlowLayout"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController/shouldRoundTopCorners-2l5pq":{"role":"symbol","title":"shouldRoundTopCorners","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldRoundTopCorners"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/shouldRoundTopCorners-2l5pq","kind":"symbol","type":"topic","url":"\/documentation\/divar\/feedbackalertviewcontroller\/shouldroundtopcorners-2l5pq"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController":{"role":"symbol","title":"FeedbackAlertViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeedbackAlertViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeedbackAlertViewController"}],"url":"\/documentation\/divar\/feedbackalertviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController/UICollectionViewDelegateFlowLayout-Implementations":{"role":"collectionGroup","title":"UICollectionViewDelegateFlowLayout Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/UICollectionViewDelegateFlowLayout-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/feedbackalertviewcontroller\/uicollectionviewdelegateflowlayout-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController/isSelected":{"role":"symbol","title":"isSelected","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSelected"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/isSelected","kind":"symbol","type":"topic","url":"\/documentation\/divar\/feedbackalertviewcontroller\/isselected"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController/allowsDragToDismiss-4g799":{"role":"symbol","title":"allowsDragToDismiss","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsDragToDismiss"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/allowsDragToDismiss-4g799","kind":"symbol","type":"topic","url":"\/documentation\/divar\/feedbackalertviewcontroller\/allowsdragtodismiss-4g799"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController/panScrollable":{"role":"symbol","title":"panScrollable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"panScrollable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/panScrollable","kind":"symbol","type":"topic","url":"\/documentation\/divar\/feedbackalertviewcontroller\/panscrollable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FeedbackAlertViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FeedbackAlertViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FeedbackAlertViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/collectionView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/submitButton","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/titleLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/UICollectionViewDataSource-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/UICollectionViewDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController\/UICollectionViewDelegateFlowLayout-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeedbackAlertViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController~1submitButton\/title","value":"submitButton"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController~1submitButton\/fragments","value":[{"kind":"identifier","text":"submitButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController~1collectionView\/title","value":"collectionView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController~1collectionView\/fragments","value":[{"kind":"identifier","text":"collectionView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController~1titleLabel\/title","value":"titleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController~1titleLabel\/fragments","value":[{"kind":"identifier","text":"titleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController\/title","value":"FeedbackAlertViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController\/fragments","value":[{"kind":"identifier","text":"FeedbackAlertViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}