{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FilterCategorySelectorController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/filtercategoryselectorcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/filtercategoryselectorcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/6Eureka17RowControllerTypeP","doc:\/\/com.Divar.DivarClient\/6Eureka22TypedRowControllerTypeP","doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIScrollViewDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDataSource","doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/init(_:categories:parentCategorySlug:currentCategorySlug:isFiltering:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/categories","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/categorySlugTree","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/currentCategorySlug","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/delegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/isFiltering","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/level","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/onDismissCallback","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/parentCategorySlug","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/rootTreshhold","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/row","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/tableView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/getChildren(for:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/getParentSlug(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/makeCategorySlugTree(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/UITableViewDataSource-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/UITableViewDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FilterCategorySelectorController"}],"title":"FilterCategorySelectorController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)FilterCategorySelectorController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"FilterCategorySelectorController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/documentation/Divar/FilterCategorySelectorController/categorySlugTree":{"role":"symbol","title":"categorySlugTree","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"categorySlugTree"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/categorySlugTree","kind":"symbol","type":"topic","url":"\/documentation\/divar\/filtercategoryselectorcontroller\/categoryslugtree"},"doc://com.Divar.DivarClient/documentation/Divar/FilterCategorySelectorController/makeCategorySlugTree(_:)":{"role":"symbol","title":"makeCategorySlugTree(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeCategorySlugTree"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/makeCategorySlugTree(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/filtercategoryselectorcontroller\/makecategoryslugtree(_:)"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/documentation/Divar/FilterCategorySelectorController/UITableViewDelegate-Implementations":{"role":"collectionGroup","title":"UITableViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/UITableViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/filtercategoryselectorcontroller\/uitableviewdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/FilterCategorySelectorController/currentCategorySlug":{"role":"symbol","title":"currentCategorySlug","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentCategorySlug"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/currentCategorySlug","kind":"symbol","type":"topic","url":"\/documentation\/divar\/filtercategoryselectorcontroller\/currentcategoryslug"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/6Eureka22TypedRowControllerTypeP":{"type":"unresolvable","title":"Eureka.TypedRowControllerType","identifier":"doc:\/\/com.Divar.DivarClient\/6Eureka22TypedRowControllerTypeP"},"doc://com.Divar.DivarClient/documentation/Divar/FilterCategorySelectorController/getParentSlug(_:)":{"role":"symbol","title":"getParentSlug(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getParentSlug"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/getParentSlug(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/filtercategoryselectorcontroller\/getparentslug(_:)"},"doc://com.Divar.DivarClient/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)UIViewController"},"doc://com.Divar.DivarClient/documentation/Divar/FilterCategorySelectorController/parentCategorySlug":{"role":"symbol","title":"parentCategorySlug","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parentCategorySlug"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/parentCategorySlug","kind":"symbol","type":"topic","url":"\/documentation\/divar\/filtercategoryselectorcontroller\/parentcategoryslug"},"doc://com.Divar.DivarClient/6Eureka17RowControllerTypeP":{"type":"unresolvable","title":"Eureka.RowControllerType","identifier":"doc:\/\/com.Divar.DivarClient\/6Eureka17RowControllerTypeP"},"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/FilterCategorySelectorController/tableView":{"role":"symbol","title":"tableView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/tableView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView"}],"url":"\/documentation\/divar\/filtercategoryselectorcontroller\/tableview"},"doc://com.Divar.DivarClient/objc(pl)UITableViewDataSource":{"type":"unresolvable","title":"UIKit.UITableViewDataSource","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDataSource"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/FilterCategorySelectorController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/filtercategoryselectorcontroller\/viewdidload()"},"doc://com.Divar.DivarClient/documentation/Divar/FilterCategorySelectorController":{"role":"symbol","title":"FilterCategorySelectorController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FilterCategorySelectorController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FilterCategorySelectorController"}],"url":"\/documentation\/divar\/filtercategoryselectorcontroller"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/documentation/Divar/FilterCategorySelectorController/row":{"role":"symbol","title":"row","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"row"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RowOf","preciseIdentifier":"s:6Eureka5RowOfC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"PostCategory","preciseIdentifier":"s:5Divar12PostCategoryV"},{"kind":"text","text":">!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/row","kind":"symbol","type":"topic","url":"\/documentation\/divar\/filtercategoryselectorcontroller\/row"},"doc://com.Divar.DivarClient/documentation/Divar/FilterCategorySelectorController/rootTreshhold":{"role":"symbol","title":"rootTreshhold","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootTreshhold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/rootTreshhold","kind":"symbol","type":"topic","url":"\/documentation\/divar\/filtercategoryselectorcontroller\/roottreshhold"},"doc://com.Divar.DivarClient/documentation/Divar/FilterCategorySelectorController/init(_:categories:parentCategorySlug:currentCategorySlug:isFiltering:)":{"role":"symbol","title":"init(_:categories:parentCategorySlug:currentCategorySlug:isFiltering:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"categories"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PostCategory","preciseIdentifier":"s:5Divar12PostCategoryV"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"parentCategorySlug"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"currentCategorySlug"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isFiltering"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/init(_:categories:parentCategorySlug:currentCategorySlug:isFiltering:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/filtercategoryselectorcontroller\/init(_:categories:parentcategoryslug:currentcategoryslug:isfiltering:)"},"doc://com.Divar.DivarClient/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIScrollViewDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/FilterCategorySelectorController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FilterCategorySelectorControllerDelegate","preciseIdentifier":"s:5Divar40FilterCategorySelectorControllerDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/filtercategoryselectorcontroller\/delegate"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/documentation/Divar/FilterCategorySelectorController/UITableViewDataSource-Implementations":{"role":"collectionGroup","title":"UITableViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/UITableViewDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/filtercategoryselectorcontroller\/uitableviewdatasource-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/FilterCategorySelectorController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/divar\/filtercategoryselectorcontroller\/initwithnibname:bundle:"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/FilterCategorySelectorController/isFiltering":{"role":"symbol","title":"isFiltering","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFiltering"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/isFiltering","kind":"symbol","type":"topic","url":"\/documentation\/divar\/filtercategoryselectorcontroller\/isfiltering"},"doc://com.Divar.DivarClient/documentation/Divar/FilterCategorySelectorController/categories":{"role":"symbol","title":"categories","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"categories"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PostCategory","preciseIdentifier":"s:5Divar12PostCategoryV"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/categories","kind":"symbol","type":"topic","url":"\/documentation\/divar\/filtercategoryselectorcontroller\/categories"},"doc://com.Divar.DivarClient/documentation/Divar/FilterCategorySelectorController/getChildren(for:)":{"role":"symbol","title":"getChildren(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getChildren"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"PostCategory","preciseIdentifier":"s:5Divar12PostCategoryV"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/getChildren(for:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/filtercategoryselectorcontroller\/getchildren(for:)"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/FilterCategorySelectorController/onDismissCallback":{"role":"symbol","title":"onDismissCallback","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDismissCallback"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/onDismissCallback","kind":"symbol","type":"topic","url":"\/documentation\/divar\/filtercategoryselectorcontroller\/ondismisscallback"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/objc(pl)UITableViewDelegate":{"type":"unresolvable","title":"UIKit.UITableViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDelegate"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/documentation/Divar/FilterCategorySelectorController/level":{"role":"symbol","title":"level","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"level"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/level","kind":"symbol","type":"topic","url":"\/documentation\/divar\/filtercategoryselectorcontroller\/level"},"doc://com.Divar.DivarClient/documentation/Divar/FilterCategorySelectorController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/filtercategoryselectorcontroller\/initwithcoder:"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FilterCategorySelectorController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FilterCategorySelectorController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FilterCategorySelectorController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/tableView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/initWithCoder:","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/initWithNibName:bundle:","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/UITableViewDataSource-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FilterCategorySelectorController\/UITableViewDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FilterCategorySelectorController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FilterCategorySelectorController~1tableView\/title","value":"tableView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FilterCategorySelectorController~1tableView\/fragments","value":[{"kind":"identifier","text":"tableView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FilterCategorySelectorController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FilterCategorySelectorController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FilterCategorySelectorController\/title","value":"FilterCategorySelectorController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FilterCategorySelectorController\/fragments","value":[{"kind":"identifier","text":"FilterCategorySelectorController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}