{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Formatter"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/formatter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/formatter"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/@M@Charts@objc(pl)ChartAxisValueFormatter","doc:\/\/com.Divar.DivarClient\/6Eureka17FormatterProtocolP","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Formatter","interfaceLanguage":"swift"},"topicSections":[{"title":"Structures","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Formatter\/Date"]},{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Formatter\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Formatter\/formatter"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Formatter\/stringForValue(_:axis:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Formatter\/withSeparator"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Formatter\/FormatterProtocol-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Formatter"}],"title":"Formatter","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)Formatter","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"Formatter"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/Formatter/stringForValue(_:axis:)":{"role":"symbol","title":"stringForValue(_:axis:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stringForValue"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"axis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AxisBase","preciseIdentifier":"c:@M@Charts@objc(cs)ChartAxisBase"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Formatter\/stringForValue(_:axis:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stringForValue:axis:"}],"url":"\/documentation\/divar\/formatter\/stringforvalue(_:axis:)"},"doc://com.Divar.DivarClient/@M@Charts@objc(pl)ChartAxisValueFormatter":{"type":"unresolvable","title":"ChartAxisValueFormatter","identifier":"doc:\/\/com.Divar.DivarClient\/@M@Charts@objc(pl)ChartAxisValueFormatter"},"doc://com.Divar.DivarClient/documentation/Divar/Formatter":{"role":"symbol","title":"Formatter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Formatter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Formatter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Formatter"}],"url":"\/documentation\/divar\/formatter"},"doc://com.Divar.DivarClient/documentation/Divar/Formatter/FormatterProtocol-Implementations":{"role":"collectionGroup","title":"FormatterProtocol Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Formatter\/FormatterProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/formatter\/formatterprotocol-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/Formatter/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Formatter\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/divar\/formatter\/init()"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/6Eureka17FormatterProtocolP":{"type":"unresolvable","title":"Eureka.FormatterProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/6Eureka17FormatterProtocolP"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/Formatter/withSeparator":{"role":"symbol","title":"withSeparator","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"withSeparator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NumberFormatter","preciseIdentifier":"c:objc(cs)NSNumberFormatter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Formatter\/withSeparator","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formatter\/withseparator"},"doc://com.Divar.DivarClient/documentation/Divar/Formatter/formatter":{"role":"symbol","title":"formatter","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"formatter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NumberFormatter","preciseIdentifier":"c:objc(cs)NSNumberFormatter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Formatter\/formatter","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formatter\/formatter"},"doc://com.Divar.DivarClient/documentation/Divar/Formatter/Date":{"role":"symbol","title":"Formatter.Date","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Date"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Formatter\/Date","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Date"}],"url":"\/documentation\/divar\/formatter\/date"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"Formatter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Formatter"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Formatter"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Formatter\/init()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Formatter\/stringForValue(_:axis:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/@M@Charts@objc(pl)ChartAxisValueFormatter"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"Formatter"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1Formatter~1stringForValue(_:axis:)\/title","value":"stringForValue:axis:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1Formatter~1stringForValue(_:axis:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stringForValue:axis:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1Formatter\/title","value":"Formatter"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1Formatter\/fragments","value":[{"kind":"identifier","text":"Formatter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1Formatter~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1Formatter~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}