{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormFlowController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/formflowcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/formflowcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentFormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerFormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JobsFormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceFormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateFormFlowController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormActionDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CategoryHierarchyControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CityMultiSelectViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormActionHandlerProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LoginRequiredProtocol","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchFilterViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedActionDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/init(container:documentForPersonal:documentForDealer:formID:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/documentForBusiness","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/documentForPersonal","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/formID","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/iVFlowDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/imageGeneratorService","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/videoExportPresetPredictorService","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/videoExporter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/videoInfoAttainmentService"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/handleAction(action:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialAddUserTransactionViewController(with:payload:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialBuyBulkLadderViewController(with:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialCategorySelectorViewController(property:delegate:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialOfflineFormViewController(schema:data:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialPersonalSubmitViewController(editID:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialPersonalSubmitViewController(with:editID:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialSchemaPageViewController(with:payload:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialScreenWidgetViewController(schema:data:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialSearchFilterViewController(filterSet:inputSuggestionKey:delegate:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialSearchFilterViewController(with:filterSet:inputSuggestionKey:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialViewController()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialWidgetBasedFilterViewController(schema:requestModel:for:delegate:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialWidgetBasedFilterViewController(schema:worker:for:delegate:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openCarAgentSubmitNextPage(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openCarConciergeManagement(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openConfirmationTransactionOffer(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openDealerRegisterNextPage(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openDealerSubmitNextPage(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openDigitalRegisteration(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openIVCollectionAssetSelectorViewController(pickerDelegate:selectorViewModelConfiguration:selectedItemViewModelConfiguration:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openIVCollectionSelectorViewController(configuration:delegate:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openIVVideoRecorderViewController(configuration:delegate:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openJobsSubmitNextPage(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openMarketplaceFinalizeEditStore(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openMarketplaceFinalizeRegister(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openMarketplaceRegisterStoreNextPage(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openMarketplaceSubmitNextPage(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openPersonalSubmitNextPage(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openPostManagement(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openPriceFormNextPage(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openRealEstateSubmitNextPage(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openRealEstateSubscriptionPurchase(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openRegisterIndependentAgentNextPage(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openSchemaPageNextPage(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/performSchemaPageAction(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/AbstractFormActionDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/FormActionHandlerProtocol-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormFlowController"}],"title":"FormFlowController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)FormFlowController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"FormFlowController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/iVFlowDelegate":{"role":"symbol","title":"iVFlowDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iVFlowDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormFlowControllerToIVFlowController","preciseIdentifier":"s:5Divar026FormFlowControllerToIVFlowD0P"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/iVFlowDelegate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/ivflowdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/initialPersonalSubmitViewController(with:editID:)":{"role":"symbol","title":"initialPersonalSubmitViewController(with:editID:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialPersonalSubmitViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"editID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialPersonalSubmitViewController(with:editID:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/initialpersonalsubmitviewcontroller(with:editid:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/openPersonalSubmitNextPage(_:)":{"role":"symbol","title":"openPersonalSubmitNextPage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openPersonalSubmitNextPage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SubmitRequestStruct","preciseIdentifier":"s:5Divar19SubmitRequestStructV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openPersonalSubmitNextPage(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/openpersonalsubmitnextpage(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/PriceFlowController":{"role":"symbol","title":"PriceFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PriceFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PriceFlowController"}],"url":"\/documentation\/divar\/priceflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/LoginRequiredProtocol":{"role":"symbol","title":"LoginRequiredProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoginRequiredProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LoginRequiredProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LoginRequiredProtocol"}],"url":"\/documentation\/divar\/loginrequiredprotocol"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedActionDelegate":{"role":"symbol","title":"WidgetBasedActionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedActionDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedActionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedActionDelegate"}],"url":"\/documentation\/divar\/widgetbasedactiondelegate"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/openCarAgentSubmitNextPage(_:)":{"role":"symbol","title":"openCarAgentSubmitNextPage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openCarAgentSubmitNextPage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SubmitRequestStruct","preciseIdentifier":"s:5Divar19SubmitRequestStructV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openCarAgentSubmitNextPage(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/opencaragentsubmitnextpage(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/PostCreateViewControllerDelegate":{"role":"symbol","title":"PostCreateViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostCreateViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostCreateViewControllerDelegate"}],"url":"\/documentation\/divar\/postcreateviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/RateViewControllerDelegate":{"role":"symbol","title":"RateViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RateViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RateViewControllerDelegate"}],"url":"\/documentation\/divar\/rateviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/openPriceFormNextPage(_:)":{"role":"symbol","title":"openPriceFormNextPage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openPriceFormNextPage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SubmitRequestStruct","preciseIdentifier":"s:5Divar19SubmitRequestStructV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openPriceFormNextPage(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/openpriceformnextpage(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/SearchFilterViewControllerDelegate":{"role":"symbol","title":"SearchFilterViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchFilterViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchFilterViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchFilterViewControllerDelegate"}],"url":"\/documentation\/divar\/searchfilterviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/openSchemaPageNextPage(_:)":{"role":"symbol","title":"openSchemaPageNextPage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openSchemaPageNextPage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SubmitRequestStruct","preciseIdentifier":"s:5Divar19SubmitRequestStructV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openSchemaPageNextPage(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/openschemapagenextpage(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/openDealerRegisterNextPage(_:)":{"role":"symbol","title":"openDealerRegisterNextPage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openDealerRegisterNextPage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SubmitRequestStruct","preciseIdentifier":"s:5Divar19SubmitRequestStructV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openDealerRegisterNextPage(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/opendealerregisternextpage(_:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/initialViewController()":{"role":"symbol","title":"initialViewController()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialViewController"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialViewController()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/initialviewcontroller()"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/initialScreenWidgetViewController(schema:data:)":{"role":"symbol","title":"initialScreenWidgetViewController(schema:data:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialScreenWidgetViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"schema"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"ScreenWidgetViewController","preciseIdentifier":"c:@M@Divar@objc(cs)ScreenWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialScreenWidgetViewController(schema:data:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/initialscreenwidgetviewcontroller(schema:data:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/videoExporter":{"role":"symbol","title":"videoExporter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoExporter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IVVideoExporterService","preciseIdentifier":"s:5Divar22IVVideoExporterServiceP"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/videoExporter","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/videoexporter"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController":{"role":"symbol","title":"BaseFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseFlowController"}],"url":"\/documentation\/divar\/baseflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/documentForBusiness":{"role":"symbol","title":"documentForBusiness","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentForBusiness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentHelperProtocol","preciseIdentifier":"s:5Divar22DocumentHelperProtocolP"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/documentForBusiness","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/documentforbusiness"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/openConfirmationTransactionOffer(_:)":{"role":"symbol","title":"openConfirmationTransactionOffer(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openConfirmationTransactionOffer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SubmitRequestStruct","preciseIdentifier":"s:5Divar19SubmitRequestStructV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openConfirmationTransactionOffer(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/openconfirmationtransactionoffer(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/CityMultiSelectViewControllerDelegate":{"role":"symbol","title":"CityMultiSelectViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CityMultiSelectViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CityMultiSelectViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CityMultiSelectViewControllerDelegate"}],"url":"\/documentation\/divar\/citymultiselectviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/openIVVideoRecorderViewController(configuration:delegate:)":{"role":"symbol","title":"openIVVideoRecorderViewController(configuration:delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openIVVideoRecorderViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IVVideoRecorderViewModelConfiguration","preciseIdentifier":"s:5Divar37IVVideoRecorderViewModelConfigurationP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IVVideoRecorderViewModelDelegate","preciseIdentifier":"s:5Divar32IVVideoRecorderViewModelDelegateP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openIVVideoRecorderViewController(configuration:delegate:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/openivvideorecorderviewcontroller(configuration:delegate:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/videoInfoAttainmentService":{"role":"symbol","title":"videoInfoAttainmentService","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoInfoAttainmentService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IVVideoInfoAttainmentService","preciseIdentifier":"s:5Divar28IVVideoInfoAttainmentServiceP"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/videoInfoAttainmentService","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/videoinfoattainmentservice"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/initialPersonalSubmitViewController(editID:)":{"role":"symbol","title":"initialPersonalSubmitViewController(editID:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialPersonalSubmitViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"editID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialPersonalSubmitViewController(editID:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/initialpersonalsubmitviewcontroller(editid:)"},"doc://com.Divar.DivarClient/documentation/Divar/DealerFormFlowController":{"role":"symbol","title":"DealerFormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DealerFormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerFormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DealerFormFlowController"}],"url":"\/documentation\/divar\/dealerformflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/FormActionHandlerProtocol-Implementations":{"role":"collectionGroup","title":"FormActionHandlerProtocol Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/FormActionHandlerProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/formactionhandlerprotocol-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/initialSearchFilterViewController(with:filterSet:inputSuggestionKey:)":{"role":"symbol","title":"initialSearchFilterViewController(with:filterSet:inputSuggestionKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialSearchFilterViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"filterSet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchFilterHistory","preciseIdentifier":"s:5Divar19SearchFilterHistoryV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inputSuggestionKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialSearchFilterViewController(with:filterSet:inputSuggestionKey:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/initialsearchfilterviewcontroller(with:filterset:inputsuggestionkey:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormActionHandlerProtocol":{"role":"symbol","title":"FormActionHandlerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormActionHandlerProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormActionHandlerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FormActionHandlerProtocol"}],"url":"\/documentation\/divar\/formactionhandlerprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/MarketplaceFormFlowController":{"role":"symbol","title":"MarketplaceFormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketplaceFormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceFormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketplaceFormFlowController"}],"url":"\/documentation\/divar\/marketplaceformflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CategoryHierarchyControllerDelegate":{"role":"symbol","title":"CategoryHierarchyControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CategoryHierarchyControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CategoryHierarchyControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CategoryHierarchyControllerDelegate"}],"url":"\/documentation\/divar\/categoryhierarchycontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/openIVCollectionAssetSelectorViewController(pickerDelegate:selectorViewModelConfiguration:selectedItemViewModelConfiguration:)":{"role":"symbol","title":"openIVCollectionAssetSelectorViewController(pickerDelegate:selectorViewModelConfiguration:selectedItemViewModelConfiguration:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openIVCollectionAssetSelectorViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pickerDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IVCollectionAssetSelectorViewModelDelegate","preciseIdentifier":"s:5Divar42IVCollectionAssetSelectorViewModelDelegateP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"selectorViewModelConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IVCollectionAssetSelectorViewModelConfiguration","preciseIdentifier":"s:5Divar47IVCollectionAssetSelectorViewModelConfigurationP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"selectedItemViewModelConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IVCollectionAssetSelectorSelectedItemViewModelConfiguration","preciseIdentifier":"s:5Divar59IVCollectionAssetSelectorSelectedItemViewModelConfigurationP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openIVCollectionAssetSelectorViewController(pickerDelegate:selectorViewModelConfiguration:selectedItemViewModelConfiguration:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/openivcollectionassetselectorviewcontroller(pickerdelegate:selectorviewmodelconfiguration:selecteditemviewmodelconfiguration:)"},"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormActionDelegate":{"role":"symbol","title":"AbstractFormActionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractFormActionDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormActionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AbstractFormActionDelegate"}],"url":"\/documentation\/divar\/abstractformactiondelegate"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/initialSchemaPageViewController(with:payload:)":{"role":"symbol","title":"initialSchemaPageViewController(with:payload:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialSchemaPageViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"payload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_OpenSchemaPagePayload","preciseIdentifier":"s:19DivarInterfaceSwift29Widgets_OpenSchemaPagePayloadV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialSchemaPageViewController(with:payload:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/initialschemapageviewcontroller(with:payload:)"},"doc://com.Divar.DivarClient/documentation/Divar/LandlineVerificationFlowControllerDelegate":{"role":"symbol","title":"LandlineVerificationFlowControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandlineVerificationFlowControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandlineVerificationFlowControllerDelegate"}],"url":"\/documentation\/divar\/landlineverificationflowcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewControllerDelegate":{"role":"symbol","title":"PostArchiveViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostArchiveViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostArchiveViewControllerDelegate"}],"url":"\/documentation\/divar\/postarchiveviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/initialOfflineFormViewController(schema:data:)":{"role":"symbol","title":"initialOfflineFormViewController(schema:data:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialOfflineFormViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"schema"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"OfflineFormViewController","preciseIdentifier":"c:@M@Divar@objc(cs)OfflineFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialOfflineFormViewController(schema:data:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/initialofflineformviewcontroller(schema:data:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/initialCategorySelectorViewController(property:delegate:)":{"role":"symbol","title":"initialCategorySelectorViewController(property:delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialCategorySelectorViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"property"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CategoryHierarchyControllerDelegate","preciseIdentifier":"s:5Divar35CategoryHierarchyControllerDelegateP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialCategorySelectorViewController(property:delegate:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/initialcategoryselectorviewcontroller(property:delegate:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/openMarketplaceFinalizeRegister(_:)":{"role":"symbol","title":"openMarketplaceFinalizeRegister(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openMarketplaceFinalizeRegister"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SubmitRequestStruct","preciseIdentifier":"s:5Divar19SubmitRequestStructV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openMarketplaceFinalizeRegister(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/openmarketplacefinalizeregister(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/openRegisterIndependentAgentNextPage(_:)":{"role":"symbol","title":"openRegisterIndependentAgentNextPage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openRegisterIndependentAgentNextPage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SubmitRequestStruct","preciseIdentifier":"s:5Divar19SubmitRequestStructV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openRegisterIndependentAgentNextPage(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/openregisterindependentagentnextpage(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/initialWidgetBasedFilterViewController(schema:requestModel:for:delegate:)":{"role":"symbol","title":"initialWidgetBasedFilterViewController(schema:requestModel:for:delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialWidgetBasedFilterViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"schema"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"requestModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WidgetBasedFilterRequest","preciseIdentifier":"s:5Divar24WidgetBasedFilterRequestP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WidgetTag","preciseIdentifier":"s:5Divar9WidgetTagV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WidgetBasedFilterViewControllerDelegate","preciseIdentifier":"s:5Divar39WidgetBasedFilterViewControllerDelegateP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialWidgetBasedFilterViewController(schema:requestModel:for:delegate:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/initialwidgetbasedfilterviewcontroller(schema:requestmodel:for:delegate:)"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/init(container:documentForPersonal:documentForDealer:formID:)":{"role":"symbol","title":"init(container:documentForPersonal:documentForDealer:formID:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseFlowDIContainer","preciseIdentifier":"s:5Divar19BaseFlowDIContainera"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentForPersonal"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentHelperProtocol","preciseIdentifier":"s:5Divar22DocumentHelperProtocolP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentForDealer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentHelperProtocol","preciseIdentifier":"s:5Divar22DocumentHelperProtocolP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"formID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/init(container:documentForPersonal:documentForDealer:formID:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/init(container:documentforpersonal:documentfordealer:formid:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/initialBuyBulkLadderViewController(with:)":{"role":"symbol","title":"initialBuyBulkLadderViewController(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialBuyBulkLadderViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialBuyBulkLadderViewController(with:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/initialbuybulkladderviewcontroller(with:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/formID":{"role":"symbol","title":"formID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"formID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/formID","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/formid"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/openDigitalRegisteration(_:)":{"role":"symbol","title":"openDigitalRegisteration(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openDigitalRegisteration"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SubmitRequestStruct","preciseIdentifier":"s:5Divar19SubmitRequestStructV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openDigitalRegisteration(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/opendigitalregisteration(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/JobsFormFlowController":{"role":"symbol","title":"JobsFormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JobsFormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JobsFormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JobsFormFlowController"}],"url":"\/documentation\/divar\/jobsformflowcontroller"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/openIVCollectionSelectorViewController(configuration:delegate:)":{"role":"symbol","title":"openIVCollectionSelectorViewController(configuration:delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openIVCollectionSelectorViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IVCollectionSelectorViewModelInitConfiguration","preciseIdentifier":"s:5Divar46IVCollectionSelectorViewModelInitConfigurationP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IVCollectionSelectorViewModelDelegate","preciseIdentifier":"s:5Divar37IVCollectionSelectorViewModelDelegateP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openIVCollectionSelectorViewController(configuration:delegate:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/openivcollectionselectorviewcontroller(configuration:delegate:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/openPostManagement(_:)":{"role":"symbol","title":"openPostManagement(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openPostManagement"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SubmitRequestStruct","preciseIdentifier":"s:5Divar19SubmitRequestStructV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openPostManagement(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/openpostmanagement(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/openJobsSubmitNextPage(_:)":{"role":"symbol","title":"openJobsSubmitNextPage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openJobsSubmitNextPage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SubmitRequestStruct","preciseIdentifier":"s:5Divar19SubmitRequestStructV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openJobsSubmitNextPage(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/openjobssubmitnextpage(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/documentForPersonal":{"role":"symbol","title":"documentForPersonal","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentForPersonal"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentHelperProtocol","preciseIdentifier":"s:5Divar22DocumentHelperProtocolP"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/documentForPersonal","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/documentforpersonal"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/initialWidgetBasedFilterViewController(schema:worker:for:delegate:)":{"role":"symbol","title":"initialWidgetBasedFilterViewController(schema:worker:for:delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialWidgetBasedFilterViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"schema"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"worker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WidgetBasedWorkerProtocol","preciseIdentifier":"s:5Divar25WidgetBasedWorkerProtocolP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WidgetTag","preciseIdentifier":"s:5Divar9WidgetTagV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WidgetBasedFilterViewControllerDelegate","preciseIdentifier":"s:5Divar39WidgetBasedFilterViewControllerDelegateP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialWidgetBasedFilterViewController(schema:worker:for:delegate:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/initialwidgetbasedfilterviewcontroller(schema:worker:for:delegate:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/imageGeneratorService":{"role":"symbol","title":"imageGeneratorService","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageGeneratorService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IVPickedDataImageGeneratorService","preciseIdentifier":"s:5Divar33IVPickedDataImageGeneratorServiceP"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/imageGeneratorService","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/imagegeneratorservice"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/openMarketplaceRegisterStoreNextPage(_:)":{"role":"symbol","title":"openMarketplaceRegisterStoreNextPage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openMarketplaceRegisterStoreNextPage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SubmitRequestStruct","preciseIdentifier":"s:5Divar19SubmitRequestStructV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openMarketplaceRegisterStoreNextPage(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/openmarketplaceregisterstorenextpage(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/performSchemaPageAction(_:)":{"role":"symbol","title":"performSchemaPageAction(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"performSchemaPageAction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SubmitRequestStruct","preciseIdentifier":"s:5Divar19SubmitRequestStructV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/performSchemaPageAction(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/performschemapageaction(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/initialAddUserTransactionViewController(with:payload:)":{"role":"symbol","title":"initialAddUserTransactionViewController(with:payload:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialAddUserTransactionViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"payload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_TransactionAddUserPayload","preciseIdentifier":"s:19DivarInterfaceSwift33Widgets_TransactionAddUserPayloadV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialAddUserTransactionViewController(with:payload:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/initialaddusertransactionviewcontroller(with:payload:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/openMarketplaceFinalizeEditStore(_:)":{"role":"symbol","title":"openMarketplaceFinalizeEditStore(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openMarketplaceFinalizeEditStore"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SubmitRequestStruct","preciseIdentifier":"s:5Divar19SubmitRequestStructV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openMarketplaceFinalizeEditStore(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/openmarketplacefinalizeeditstore(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/openRealEstateSubmitNextPage(_:)":{"role":"symbol","title":"openRealEstateSubmitNextPage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openRealEstateSubmitNextPage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SubmitRequestStruct","preciseIdentifier":"s:5Divar19SubmitRequestStructV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openRealEstateSubmitNextPage(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/openrealestatesubmitnextpage(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController":{"role":"symbol","title":"FormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FormFlowController"}],"url":"\/documentation\/divar\/formflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/openDealerSubmitNextPage(_:)":{"role":"symbol","title":"openDealerSubmitNextPage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openDealerSubmitNextPage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SubmitRequestStruct","preciseIdentifier":"s:5Divar19SubmitRequestStructV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openDealerSubmitNextPage(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/opendealersubmitnextpage(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/openCarConciergeManagement(_:)":{"role":"symbol","title":"openCarConciergeManagement(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openCarConciergeManagement"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SubmitRequestStruct","preciseIdentifier":"s:5Divar19SubmitRequestStructV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openCarConciergeManagement(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/opencarconciergemanagement(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/RealEstateFormFlowController":{"role":"symbol","title":"RealEstateFormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RealEstateFormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateFormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RealEstateFormFlowController"}],"url":"\/documentation\/divar\/realestateformflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarAgentFormFlowController":{"role":"symbol","title":"CarAgentFormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarAgentFormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentFormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarAgentFormFlowController"}],"url":"\/documentation\/divar\/caragentformflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/AbstractFormActionDelegate-Implementations":{"role":"collectionGroup","title":"AbstractFormActionDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/AbstractFormActionDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/abstractformactiondelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/openMarketplaceSubmitNextPage(_:)":{"role":"symbol","title":"openMarketplaceSubmitNextPage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openMarketplaceSubmitNextPage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SubmitRequestStruct","preciseIdentifier":"s:5Divar19SubmitRequestStructV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openMarketplaceSubmitNextPage(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/openmarketplacesubmitnextpage(_:)"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/openRealEstateSubscriptionPurchase(_:)":{"role":"symbol","title":"openRealEstateSubscriptionPurchase(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openRealEstateSubscriptionPurchase"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SubmitRequestStruct","preciseIdentifier":"s:5Divar19SubmitRequestStructV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/openRealEstateSubscriptionPurchase(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/openrealestatesubscriptionpurchase(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/initialSearchFilterViewController(filterSet:inputSuggestionKey:delegate:)":{"role":"symbol","title":"initialSearchFilterViewController(filterSet:inputSuggestionKey:delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialSearchFilterViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"filterSet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchFilterHistory","preciseIdentifier":"s:5Divar19SearchFilterHistoryV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inputSuggestionKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchFilterViewControllerDelegate","preciseIdentifier":"s:5Divar34SearchFilterViewControllerDelegateP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/initialSearchFilterViewController(filterSet:inputSuggestionKey:delegate:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/initialsearchfilterviewcontroller(filterset:inputsuggestionkey:delegate:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/videoExportPresetPredictorService":{"role":"symbol","title":"videoExportPresetPredictorService","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoExportPresetPredictorService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IVVideoExportPresetPredictorService","preciseIdentifier":"s:5Divar35IVVideoExportPresetPredictorServiceP"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/videoExportPresetPredictorService","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/videoexportpresetpredictorservice"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController/handleAction(action:)":{"role":"symbol","title":"handleAction(action:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController\/handleAction(action:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/formflowcontroller\/handleaction(action:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FormFlowController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FormFlowController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FormFlowController"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentFormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerFormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JobsFormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceFormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateFormFlowController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormFlowController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","preciseIdentifier":"c:@M@Divar@objc(cs)BaseFlowController","text":"BaseFlowController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceFlowController\/title","value":"PriceFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceFlowController\/fragments","value":[{"kind":"identifier","text":"PriceFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/title","value":"BaseFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/fragments","value":[{"kind":"identifier","text":"BaseFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerFormFlowController\/title","value":"DealerFormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerFormFlowController\/fragments","value":[{"kind":"identifier","text":"DealerFormFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceFormFlowController\/title","value":"MarketplaceFormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceFormFlowController\/fragments","value":[{"kind":"identifier","text":"MarketplaceFormFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JobsFormFlowController\/title","value":"JobsFormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JobsFormFlowController\/fragments","value":[{"kind":"identifier","text":"JobsFormFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FormFlowController\/title","value":"FormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FormFlowController\/fragments","value":[{"kind":"identifier","text":"FormFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateFormFlowController\/title","value":"RealEstateFormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateFormFlowController\/fragments","value":[{"kind":"identifier","text":"RealEstateFormFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentFormFlowController\/title","value":"CarAgentFormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentFormFlowController\/fragments","value":[{"kind":"identifier","text":"CarAgentFormFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}