{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormActionHandlerProtocol"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/formactionhandlerprotocol"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentFormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarPriceFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerFormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JobsFormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceFormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateFormFlowController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormActionHandlerProtocol","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormActionHandlerProtocol\/openEditPost(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormActionHandlerProtocol\/openPersonalSubmit(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormActionHandlerProtocol\/openSchemaPage(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormActionHandlerProtocol\/openTransactionAddUserPage(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormActionHandlerProtocol\/submitWithoutPromotion(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormActionHandlerProtocol"}],"title":"FormActionHandlerProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar25FormActionHandlerProtocolP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"FormActionHandlerProtocol"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/CarPriceFlowController":{"role":"symbol","title":"CarPriceFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarPriceFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarPriceFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarPriceFlowController"}],"url":"\/documentation\/divar\/carpriceflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/FormActionHandlerProtocol/openTransactionAddUserPage(_:)":{"role":"symbol","title":"openTransactionAddUserPage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openTransactionAddUserPage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormActionHandlerProtocol\/openTransactionAddUserPage(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/formactionhandlerprotocol\/opentransactionadduserpage(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/PriceFlowController":{"role":"symbol","title":"PriceFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PriceFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PriceFlowController"}],"url":"\/documentation\/divar\/priceflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/FormActionHandlerProtocol":{"role":"symbol","title":"FormActionHandlerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormActionHandlerProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormActionHandlerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FormActionHandlerProtocol"}],"url":"\/documentation\/divar\/formactionhandlerprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController":{"role":"symbol","title":"FormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FormFlowController"}],"url":"\/documentation\/divar\/formflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/FormActionHandlerProtocol/openPersonalSubmit(_:)":{"role":"symbol","title":"openPersonalSubmit(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openPersonalSubmit"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormActionHandlerProtocol\/openPersonalSubmit(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/formactionhandlerprotocol\/openpersonalsubmit(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/CarAgentFormFlowController":{"role":"symbol","title":"CarAgentFormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarAgentFormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentFormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarAgentFormFlowController"}],"url":"\/documentation\/divar\/caragentformflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/JobsFormFlowController":{"role":"symbol","title":"JobsFormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JobsFormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JobsFormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JobsFormFlowController"}],"url":"\/documentation\/divar\/jobsformflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/FormActionHandlerProtocol/openEditPost(_:)":{"role":"symbol","title":"openEditPost(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openEditPost"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormActionHandlerProtocol\/openEditPost(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/formactionhandlerprotocol\/openeditpost(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/FormActionHandlerProtocol/submitWithoutPromotion(_:)":{"role":"symbol","title":"submitWithoutPromotion(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"submitWithoutPromotion"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormActionHandlerProtocol\/submitWithoutPromotion(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/formactionhandlerprotocol\/submitwithoutpromotion(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/MarketplaceFormFlowController":{"role":"symbol","title":"MarketplaceFormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketplaceFormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceFormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketplaceFormFlowController"}],"url":"\/documentation\/divar\/marketplaceformflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/FormActionHandlerProtocol/openSchemaPage(_:)":{"role":"symbol","title":"openSchemaPage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openSchemaPage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormActionHandlerProtocol\/openSchemaPage(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/formactionhandlerprotocol\/openschemapage(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/RealEstateFormFlowController":{"role":"symbol","title":"RealEstateFormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RealEstateFormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateFormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RealEstateFormFlowController"}],"url":"\/documentation\/divar\/realestateformflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/DealerFormFlowController":{"role":"symbol","title":"DealerFormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DealerFormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerFormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DealerFormFlowController"}],"url":"\/documentation\/divar\/dealerformflowcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarPriceFlowController\/title","value":"CarPriceFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarPriceFlowController\/fragments","value":[{"kind":"identifier","text":"CarPriceFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceFlowController\/title","value":"PriceFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceFlowController\/fragments","value":[{"kind":"identifier","text":"PriceFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FormFlowController\/title","value":"FormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FormFlowController\/fragments","value":[{"kind":"identifier","text":"FormFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentFormFlowController\/title","value":"CarAgentFormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentFormFlowController\/fragments","value":[{"kind":"identifier","text":"CarAgentFormFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JobsFormFlowController\/title","value":"JobsFormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JobsFormFlowController\/fragments","value":[{"kind":"identifier","text":"JobsFormFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceFormFlowController\/title","value":"MarketplaceFormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceFormFlowController\/fragments","value":[{"kind":"identifier","text":"MarketplaceFormFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateFormFlowController\/title","value":"RealEstateFormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateFormFlowController\/fragments","value":[{"kind":"identifier","text":"RealEstateFormFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerFormFlowController\/title","value":"DealerFormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerFormFlowController\/fragments","value":[{"kind":"identifier","text":"DealerFormFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}