{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeneralBulkLadderViewControllerDelegate"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/generalbulkladderviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BulkLadderBaseFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentBulkLadderFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateBulkLadderFlowController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GeneralBulkLadderViewControllerDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GeneralBulkLadderViewControllerDelegate\/bulkLadderViewController(shouldOpenFilterWith:request:for:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeneralBulkLadderViewControllerDelegate"}],"title":"GeneralBulkLadderViewControllerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar39GeneralBulkLadderViewControllerDelegateP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"GeneralBulkLadderViewControllerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/RealEstateBulkLadderFlowController":{"role":"symbol","title":"RealEstateBulkLadderFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RealEstateBulkLadderFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateBulkLadderFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RealEstateBulkLadderFlowController"}],"url":"\/documentation\/divar\/realestatebulkladderflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/GeneralBulkLadderViewControllerDelegate":{"role":"symbol","title":"GeneralBulkLadderViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeneralBulkLadderViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GeneralBulkLadderViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GeneralBulkLadderViewControllerDelegate"}],"url":"\/documentation\/divar\/generalbulkladderviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/CarAgentBulkLadderFlowController":{"role":"symbol","title":"CarAgentBulkLadderFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarAgentBulkLadderFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentBulkLadderFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarAgentBulkLadderFlowController"}],"url":"\/documentation\/divar\/caragentbulkladderflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/GeneralBulkLadderViewControllerDelegate/bulkLadderViewController(shouldOpenFilterWith:request:for:)":{"role":"symbol","title":"bulkLadderViewController(shouldOpenFilterWith:request:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bulkLadderViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"shouldOpenFilterWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"request"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WidgetBasedFilterRequest","preciseIdentifier":"s:5Divar24WidgetBasedFilterRequestP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WidgetTag","preciseIdentifier":"s:5Divar9WidgetTagV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GeneralBulkLadderViewControllerDelegate\/bulkLadderViewController(shouldOpenFilterWith:request:for:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/generalbulkladderviewcontrollerdelegate\/bulkladderviewcontroller(shouldopenfilterwith:request:for:)"},"doc://com.Divar.DivarClient/documentation/Divar/BulkLadderBaseFlowController":{"role":"symbol","title":"BulkLadderBaseFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BulkLadderBaseFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BulkLadderBaseFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BulkLadderBaseFlowController"}],"url":"\/documentation\/divar\/bulkladderbaseflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateBulkLadderFlowController\/title","value":"RealEstateBulkLadderFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateBulkLadderFlowController\/fragments","value":[{"kind":"identifier","text":"RealEstateBulkLadderFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentBulkLadderFlowController\/title","value":"CarAgentBulkLadderFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentBulkLadderFlowController\/fragments","value":[{"kind":"identifier","text":"CarAgentBulkLadderFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BulkLadderBaseFlowController\/title","value":"BulkLadderBaseFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BulkLadderBaseFlowController\/fragments","value":[{"kind":"identifier","text":"BulkLadderBaseFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}