{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HorizontalCollectionFlowLayout"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/horizontalcollectionflowlayout"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/horizontalcollectionflowlayout"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UICollectionViewFlowLayout"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListFlowLayout"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HorizontalCollectionFlowLayout","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HorizontalCollectionFlowLayout\/flipsHorizontallyInOppositeLayoutDirection","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HorizontalCollectionFlowLayout\/marginX","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HorizontalCollectionFlowLayout\/paddingX","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HorizontalCollectionFlowLayout\/paddingY"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HorizontalCollectionFlowLayout\/awakeFromNib()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HorizontalCollectionFlowLayout\/prepare()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HorizontalCollectionFlowLayout"}],"title":"HorizontalCollectionFlowLayout","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)HorizontalCollectionFlowLayout","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"HorizontalCollectionFlowLayout"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/HorizontalCollectionFlowLayout/prepare()":{"role":"symbol","title":"prepare()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepare"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HorizontalCollectionFlowLayout\/prepare()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prepareLayout"}],"url":"\/documentation\/divar\/horizontalcollectionflowlayout\/prepare()"},"doc://com.Divar.DivarClient/documentation/Divar/HorizontalCollectionFlowLayout/awakeFromNib()":{"role":"symbol","title":"awakeFromNib()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HorizontalCollectionFlowLayout\/awakeFromNib()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"awakeFromNib"}],"url":"\/documentation\/divar\/horizontalcollectionflowlayout\/awakefromnib()"},"doc://com.Divar.DivarClient/documentation/Divar/TagListFlowLayout":{"role":"symbol","title":"TagListFlowLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListFlowLayout"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListFlowLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagListFlowLayout"}],"url":"\/documentation\/divar\/taglistflowlayout"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/objc(cs)UICollectionViewFlowLayout":{"type":"unresolvable","title":"UICollectionViewFlowLayout","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)UICollectionViewFlowLayout"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/HorizontalCollectionFlowLayout/paddingY":{"role":"symbol","title":"paddingY","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paddingY"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HorizontalCollectionFlowLayout\/paddingY","kind":"symbol","type":"topic","url":"\/documentation\/divar\/horizontalcollectionflowlayout\/paddingy"},"doc://com.Divar.DivarClient/documentation/Divar/HorizontalCollectionFlowLayout/flipsHorizontallyInOppositeLayoutDirection":{"role":"symbol","title":"flipsHorizontallyInOppositeLayoutDirection","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"flipsHorizontallyInOppositeLayoutDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HorizontalCollectionFlowLayout\/flipsHorizontallyInOppositeLayoutDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"flipsHorizontallyInOppositeLayoutDirection"}],"url":"\/documentation\/divar\/horizontalcollectionflowlayout\/flipshorizontallyinoppositelayoutdirection"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/HorizontalCollectionFlowLayout/paddingX":{"role":"symbol","title":"paddingX","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paddingX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HorizontalCollectionFlowLayout\/paddingX","kind":"symbol","type":"topic","url":"\/documentation\/divar\/horizontalcollectionflowlayout\/paddingx"},"doc://com.Divar.DivarClient/documentation/Divar/HorizontalCollectionFlowLayout/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HorizontalCollectionFlowLayout\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/divar\/horizontalcollectionflowlayout\/init"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/HorizontalCollectionFlowLayout":{"role":"symbol","title":"HorizontalCollectionFlowLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HorizontalCollectionFlowLayout"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HorizontalCollectionFlowLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HorizontalCollectionFlowLayout"}],"url":"\/documentation\/divar\/horizontalcollectionflowlayout"},"doc://com.Divar.DivarClient/documentation/Divar/HorizontalCollectionFlowLayout/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HorizontalCollectionFlowLayout\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/horizontalcollectionflowlayout\/initwithcoder:"},"doc://com.Divar.DivarClient/documentation/Divar/HorizontalCollectionFlowLayout/marginX":{"role":"symbol","title":"marginX","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"marginX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HorizontalCollectionFlowLayout\/marginX","kind":"symbol","type":"topic","url":"\/documentation\/divar\/horizontalcollectionflowlayout\/marginx"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HorizontalCollectionFlowLayout"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HorizontalCollectionFlowLayout"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HorizontalCollectionFlowLayout"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HorizontalCollectionFlowLayout\/flipsHorizontallyInOppositeLayoutDirection"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HorizontalCollectionFlowLayout\/awakeFromNib()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HorizontalCollectionFlowLayout\/init","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HorizontalCollectionFlowLayout\/initWithCoder:","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/HorizontalCollectionFlowLayout\/prepare()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UICollectionViewFlowLayout"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListFlowLayout"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HorizontalCollectionFlowLayout"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UICollectionViewFlowLayout","preciseIdentifier":"c:objc(cs)UICollectionViewFlowLayout"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1HorizontalCollectionFlowLayout~1prepare()\/title","value":"prepareLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1HorizontalCollectionFlowLayout~1prepare()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1HorizontalCollectionFlowLayout~1awakeFromNib()\/title","value":"awakeFromNib"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1HorizontalCollectionFlowLayout~1awakeFromNib()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"awakeFromNib"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListFlowLayout\/title","value":"TagListFlowLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListFlowLayout\/fragments","value":[{"kind":"identifier","text":"TagListFlowLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1HorizontalCollectionFlowLayout~1flipsHorizontallyInOppositeLayoutDirection\/title","value":"flipsHorizontallyInOppositeLayoutDirection"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1HorizontalCollectionFlowLayout~1flipsHorizontallyInOppositeLayoutDirection\/fragments","value":[{"kind":"identifier","text":"flipsHorizontallyInOppositeLayoutDirection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1HorizontalCollectionFlowLayout\/title","value":"HorizontalCollectionFlowLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1HorizontalCollectionFlowLayout\/fragments","value":[{"kind":"identifier","text":"HorizontalCollectionFlowLayout"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}