{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImagePickerImageSelectionCell"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/imagepickerimageselectioncell"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/imagepickerimageselectioncell"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UICollectionViewCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/objc(pl)CALayerDelegate","doc:\/\/com.Divar.DivarClient\/6Sonnat12ReusableCellP","doc:\/\/com.Divar.DivarClient\/6Sonnat23WithInitializerProtocolP","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearance","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UICoordinateSpace","doc:\/\/com.Divar.DivarClient\/objc(pl)UIDynamicItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItemContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UILargeContentViewerItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/delegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/editBtn","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/imageView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/indexPath","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/selectionIcon","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/selectionView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/awakeFromNib()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/editAction(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/fill(delegate:indexPath:isSelected:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/layoutSubviews()"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"ImagePickerImageSelectionCell"}],"role":"symbol","title":"ImagePickerImageSelectionCell","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImagePickerImageSelectionCell"}],"symbolKind":"class","externalID":"c:@M@Divar@objc(cs)ImagePickerImageSelectionCell","modules":[{"name":"Divar"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use IV Module Instead"}]}],"references":{"doc://com.Divar.DivarClient/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAccessibilityIdentification"},"doc://com.Divar.DivarClient/documentation/Divar/ImagePickerImageSelectionCell/editBtn":{"deprecated":true,"role":"symbol","title":"editBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"editBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/editBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"editBtn"}],"url":"\/documentation\/divar\/imagepickerimageselectioncell\/editbtn"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UILargeContentViewerItem"},"doc://com.Divar.DivarClient/documentation/Divar/ImagePickerImageSelectionCell/selectionView":{"deprecated":true,"role":"symbol","title":"selectionView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/selectionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectionView"}],"url":"\/documentation\/divar\/imagepickerimageselectioncell\/selectionview"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIDynamicItem"},"doc://com.Divar.DivarClient/documentation/Divar/ImagePickerImageSelectionCell/editAction(_:)":{"deprecated":true,"role":"symbol","title":"editAction(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"editAction"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/editAction(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"editAction:"}],"url":"\/documentation\/divar\/imagepickerimageselectioncell\/editaction(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/ImagePickerImageSelectionCell/fill(delegate:indexPath:isSelected:)":{"role":"symbol","title":"fill(delegate:indexPath:isSelected:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fill"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImagePickerImageSelectionCellDelegate","preciseIdentifier":"s:5Divar011ImagePickerB21SelectionCellDelegateP"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isSelected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/fill(delegate:indexPath:isSelected:)","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/divar\/imagepickerimageselectioncell\/fill(delegate:indexpath:isselected:)"},"doc://com.Divar.DivarClient/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.Divar.DivarClient/documentation/Divar/ImagePickerImageSelectionCell/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImagePickerImageSelectionCellDelegate","preciseIdentifier":"s:5Divar011ImagePickerB21SelectionCellDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/delegate","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/divar\/imagepickerimageselectioncell\/delegate"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItemContainer"},"doc://com.Divar.DivarClient/6Sonnat23WithInitializerProtocolP":{"type":"unresolvable","title":"Sonnat.WithInitializerProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat23WithInitializerProtocolP"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/documentation/Divar/ImagePickerImageSelectionCell/initWithFrame:":{"role":"symbol","title":"initWithFrame:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/initWithFrame:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/divar\/imagepickerimageselectioncell\/initwithframe:"},"doc://com.Divar.DivarClient/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)CALayerDelegate"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItem"},"doc://com.Divar.DivarClient/documentation/Divar/ImagePickerImageSelectionCell/indexPath":{"role":"symbol","title":"indexPath","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/indexPath","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/divar\/imagepickerimageselectioncell\/indexpath"},"doc://com.Divar.DivarClient/documentation/Divar/ImagePickerImageSelectionCell/layoutSubviews()":{"deprecated":true,"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/divar\/imagepickerimageselectioncell\/layoutsubviews()"},"doc://com.Divar.DivarClient/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearance"},"doc://com.Divar.DivarClient/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UICoordinateSpace"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/objc(cs)UICollectionViewCell":{"type":"unresolvable","title":"UICollectionViewCell","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)UICollectionViewCell"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/6Sonnat12ReusableCellP":{"type":"unresolvable","title":"Sonnat.ReusableCell","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat12ReusableCellP"},"doc://com.Divar.DivarClient/documentation/Divar/ImagePickerImageSelectionCell/selectionIcon":{"deprecated":true,"role":"symbol","title":"selectionIcon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectionIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SonnatImageView","preciseIdentifier":"c:@M@Sonnat@objc(cs)SonnatImageView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/selectionIcon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectionIcon"}],"url":"\/documentation\/divar\/imagepickerimageselectioncell\/selectionicon"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/documentation/Divar/ImagePickerImageSelectionCell/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/imagepickerimageselectioncell\/initwithcoder:"},"doc://com.Divar.DivarClient/documentation/Divar/ImagePickerImageSelectionCell":{"deprecated":true,"role":"symbol","title":"ImagePickerImageSelectionCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImagePickerImageSelectionCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImagePickerImageSelectionCell"}],"url":"\/documentation\/divar\/imagepickerimageselectioncell"},"doc://com.Divar.DivarClient/documentation/Divar/ImagePickerImageSelectionCell/awakeFromNib()":{"deprecated":true,"role":"symbol","title":"awakeFromNib()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/awakeFromNib()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"awakeFromNib"}],"url":"\/documentation\/divar\/imagepickerimageselectioncell\/awakefromnib()"},"doc://com.Divar.DivarClient/documentation/Divar/ImagePickerImageSelectionCell/imageView":{"deprecated":true,"role":"symbol","title":"imageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SonnatImageView","preciseIdentifier":"c:@M@Sonnat@objc(cs)SonnatImageView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/imageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageView"}],"url":"\/documentation\/divar\/imagepickerimageselectioncell\/imageview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ImagePickerImageSelectionCell"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ImagePickerImageSelectionCell"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ImagePickerImageSelectionCell"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/editBtn","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/imageView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/selectionIcon","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/selectionView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/awakeFromNib()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/editAction(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/initWithCoder:","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/initWithFrame:","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImagePickerImageSelectionCell\/layoutSubviews()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UICollectionViewCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImagePickerImageSelectionCell"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelectionCell~1editBtn\/title","value":"editBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelectionCell~1editBtn\/fragments","value":[{"kind":"identifier","text":"editBtn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelectionCell~1selectionView\/title","value":"selectionView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelectionCell~1selectionView\/fragments","value":[{"kind":"identifier","text":"selectionView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelectionCell~1editAction(_:)\/title","value":"editAction:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelectionCell~1editAction(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"editAction:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelectionCell~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelectionCell~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelectionCell~1selectionIcon\/title","value":"selectionIcon"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelectionCell~1selectionIcon\/fragments","value":[{"kind":"identifier","text":"selectionIcon"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelectionCell\/title","value":"ImagePickerImageSelectionCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelectionCell\/fragments","value":[{"kind":"identifier","text":"ImagePickerImageSelectionCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelectionCell~1awakeFromNib()\/title","value":"awakeFromNib"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelectionCell~1awakeFromNib()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"awakeFromNib"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelectionCell~1imageView\/title","value":"imageView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImagePickerImageSelectionCell~1imageView\/fragments","value":[{"kind":"identifier","text":"imageView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}