{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InAppLinkActionHandler"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/inapplinkactionhandler"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LinkFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OpenPageFlowController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InAppLinkActionHandler","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InAppLinkActionHandler\/openLink(_:)-gzrw","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InAppLinkActionHandler\/openWebPageAlert(_:)-gp64"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InAppLinkActionHandler"}],"title":"InAppLinkActionHandler","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar22InAppLinkActionHandlerP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"InAppLinkActionHandler"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/LinkFlowController":{"role":"symbol","title":"LinkFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LinkFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LinkFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LinkFlowController"}],"url":"\/documentation\/divar\/linkflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/InAppLinkActionHandler/openWebPageAlert(_:)-gp64":{"defaultImplementations":1,"role":"symbol","title":"openWebPageAlert(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openWebPageAlert"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InAppLinkActionHandler\/openWebPageAlert(_:)-gp64","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/inapplinkactionhandler\/openwebpagealert(_:)-gp64"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/InAppLinkActionHandler/openLink(_:)-gzrw":{"defaultImplementations":1,"role":"symbol","title":"openLink(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openLink"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InAppLinkActionHandler\/openLink(_:)-gzrw","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/inapplinkactionhandler\/openlink(_:)-gzrw"},"doc://com.Divar.DivarClient/documentation/Divar/OpenPageFlowController":{"role":"symbol","title":"OpenPageFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenPageFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OpenPageFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenPageFlowController"}],"url":"\/documentation\/divar\/openpageflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/InAppLinkActionHandler":{"role":"symbol","title":"InAppLinkActionHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InAppLinkActionHandler"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InAppLinkActionHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InAppLinkActionHandler"}],"url":"\/documentation\/divar\/inapplinkactionhandler"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LinkFlowController\/title","value":"LinkFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LinkFlowController\/fragments","value":[{"kind":"identifier","text":"LinkFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OpenPageFlowController\/title","value":"OpenPageFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OpenPageFlowController\/fragments","value":[{"kind":"identifier","text":"OpenPageFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}