{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InputAreaViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/inputareaviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/inputareaviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioRecorderViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatAttachmentActionOptionProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ComponentProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIScrollViewDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITextViewDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/init(container:conversation:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/attachmentButton","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/conversation","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/delegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/heightConstraint","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/isAttachingFileAllowed","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/isAttachingVideoAllowed","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/isEditingMessage","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/isRecording","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/lastSendTypingeventDate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/messageVC","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/parentVeiwController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/post","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/recordingView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/recordingViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/sendButton","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/textView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/topDivider"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/attachmentButtonAction(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/prepareForEditWarnedMessage(text:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/prepareForMessagePreviewBar(isShowingMessagePreview:message:type:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/sendButtonAction(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/setHeight(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/startRecording(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/stopRecording()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/viewDidLoad()"]},{"title":"Enumerations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/SendButtonState"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/AudioRecorderViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/ChatAttachmentActionOptionProtocol-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/UIGestureRecognizerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/UITextViewDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InputAreaViewController"}],"title":"InputAreaViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)InputAreaViewController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"InputAreaViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/stopRecording()":{"role":"symbol","title":"stopRecording()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopRecording"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/stopRecording()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/inputareaviewcontroller\/stoprecording()"},"doc://com.Divar.DivarClient/documentation/Divar/ShowMessageProtocol":{"role":"symbol","title":"ShowMessageProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowMessageProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowMessageProtocol"}],"url":"\/documentation\/divar\/showmessageprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/ChatAttachmentActionOptionProtocol":{"role":"symbol","title":"ChatAttachmentActionOptionProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatAttachmentActionOptionProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatAttachmentActionOptionProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatAttachmentActionOptionProtocol"}],"url":"\/documentation\/divar\/chatattachmentactionoptionprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController":{"role":"symbol","title":"BaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseViewController"}],"url":"\/documentation\/divar\/baseviewcontroller"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/objc(pl)UIGestureRecognizerDelegate":{"type":"unresolvable","title":"UIKit.UIGestureRecognizerDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIGestureRecognizerDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/TooltipPresenter":{"role":"symbol","title":"TooltipPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TooltipPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TooltipPresenter"}],"url":"\/documentation\/divar\/tooltippresenter"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/messageVC":{"role":"symbol","title":"messageVC","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagingViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MessagingViewController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/messageVC","kind":"symbol","type":"topic","url":"\/documentation\/divar\/inputareaviewcontroller\/messagevc"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/sendButton":{"role":"symbol","title":"sendButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/sendButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendButton"}],"url":"\/documentation\/divar\/inputareaviewcontroller\/sendbutton"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageInputAreaViewControllerDelegate","preciseIdentifier":"s:5Divar38MessageInputAreaViewControllerDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/inputareaviewcontroller\/delegate"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/topDivider":{"role":"symbol","title":"topDivider","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topDivider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/topDivider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"topDivider"}],"url":"\/documentation\/divar\/inputareaviewcontroller\/topdivider"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/setHeight(_:)":{"role":"symbol","title":"setHeight(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setHeight"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/setHeight(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/inputareaviewcontroller\/setheight(_:)"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/ErrorMessageHandler":{"role":"symbol","title":"ErrorMessageHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorMessageHandler"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorMessageHandler"}],"url":"\/documentation\/divar\/errormessagehandler"},"doc://com.Divar.DivarClient/documentation/Divar/PaymentSystemProtocol":{"role":"symbol","title":"PaymentSystemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSystemProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaymentSystemProtocol"}],"url":"\/documentation\/divar\/paymentsystemprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/init(container:conversation:)":{"role":"symbol","title":"init(container:conversation:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InputAreaViewControllerDIContainer","preciseIdentifier":"s:5Divar34InputAreaViewControllerDIContainera"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatConversationTable","preciseIdentifier":"s:5Divar21ChatConversationTableV"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/init(container:conversation:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/inputareaviewcontroller\/init(container:conversation:)"},"doc://com.Divar.DivarClient/documentation/Divar/ShowErrorProtocol":{"role":"symbol","title":"ShowErrorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowErrorProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowErrorProtocol"}],"url":"\/documentation\/divar\/showerrorprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/prepareForMessagePreviewBar(isShowingMessagePreview:message:type:)":{"role":"symbol","title":"prepareForMessagePreviewBar(isShowingMessagePreview:message:type:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareForMessagePreviewBar"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isShowingMessagePreview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagePreviewBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MessagePreviewBarViewController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"MessagePreviewType","preciseIdentifier":"s:5Divar31MessagePreviewBarViewControllerC0bC4TypeO"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/prepareForMessagePreviewBar(isShowingMessagePreview:message:type:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/inputareaviewcontroller\/prepareformessagepreviewbar(isshowingmessagepreview:message:type:)"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/inputareaviewcontroller\/viewdidload()"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/sendButtonAction(_:)":{"role":"symbol","title":"sendButtonAction(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendButtonAction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/sendButtonAction(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendButtonAction:"}],"url":"\/documentation\/divar\/inputareaviewcontroller\/sendbuttonaction(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/startRecording(_:)":{"role":"symbol","title":"startRecording(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startRecording"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/startRecording(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startRecording:"}],"url":"\/documentation\/divar\/inputareaviewcontroller\/startrecording(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/isAttachingVideoAllowed":{"role":"symbol","title":"isAttachingVideoAllowed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAttachingVideoAllowed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/isAttachingVideoAllowed","kind":"symbol","type":"topic","url":"\/documentation\/divar\/inputareaviewcontroller\/isattachingvideoallowed"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/UIGestureRecognizerDelegate-Implementations":{"role":"collectionGroup","title":"UIGestureRecognizerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/UIGestureRecognizerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/inputareaviewcontroller\/uigesturerecognizerdelegate-implementations"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/ComponentProtocol":{"role":"symbol","title":"ComponentProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComponentProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ComponentProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ComponentProtocol"}],"url":"\/documentation\/divar\/componentprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/AudioRecorderViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"AudioRecorderViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/AudioRecorderViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/inputareaviewcontroller\/audiorecorderviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/attachmentButtonAction(_:)":{"role":"symbol","title":"attachmentButtonAction(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachmentButtonAction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/attachmentButtonAction(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"attachmentButtonAction:"}],"url":"\/documentation\/divar\/inputareaviewcontroller\/attachmentbuttonaction(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/parentVeiwController":{"role":"symbol","title":"parentVeiwController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parentVeiwController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageHandlingType","preciseIdentifier":"s:5Divar19MessageHandlingTypea"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/parentVeiwController","kind":"symbol","type":"topic","url":"\/documentation\/divar\/inputareaviewcontroller\/parentveiwcontroller"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/AudioRecorderViewControllerDelegate":{"role":"symbol","title":"AudioRecorderViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioRecorderViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AudioRecorderViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AudioRecorderViewControllerDelegate"}],"url":"\/documentation\/divar\/audiorecorderviewcontrollerdelegate"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/textView":{"role":"symbol","title":"textView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/textView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textView"}],"url":"\/documentation\/divar\/inputareaviewcontroller\/textview"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController":{"role":"symbol","title":"InputAreaViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InputAreaViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InputAreaViewController"}],"url":"\/documentation\/divar\/inputareaviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/recordingView":{"role":"symbol","title":"recordingView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordingView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/recordingView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"recordingView"}],"url":"\/documentation\/divar\/inputareaviewcontroller\/recordingview"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/isRecording":{"role":"symbol","title":"isRecording","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRecording"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/isRecording","kind":"symbol","type":"topic","url":"\/documentation\/divar\/inputareaviewcontroller\/isrecording"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/isAttachingFileAllowed":{"role":"symbol","title":"isAttachingFileAllowed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAttachingFileAllowed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/isAttachingFileAllowed","kind":"symbol","type":"topic","url":"\/documentation\/divar\/inputareaviewcontroller\/isattachingfileallowed"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/lastSendTypingeventDate":{"role":"symbol","title":"lastSendTypingeventDate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastSendTypingeventDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/lastSendTypingeventDate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/inputareaviewcontroller\/lastsendtypingeventdate"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/ChatAttachmentActionOptionProtocol-Implementations":{"role":"collectionGroup","title":"ChatAttachmentActionOptionProtocol Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/ChatAttachmentActionOptionProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/inputareaviewcontroller\/chatattachmentactionoptionprotocol-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/inputareaviewcontroller\/init(coder:)"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/recordingViewController":{"role":"symbol","title":"recordingViewController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordingViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VoiceRecorderViewController","preciseIdentifier":"c:@M@Divar@objc(cs)VoiceRecorderViewController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/recordingViewController","kind":"symbol","type":"topic","url":"\/documentation\/divar\/inputareaviewcontroller\/recordingviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/isEditingMessage":{"role":"symbol","title":"isEditingMessage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEditingMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/isEditingMessage","kind":"symbol","type":"topic","url":"\/documentation\/divar\/inputareaviewcontroller\/iseditingmessage"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/attachmentButton":{"role":"symbol","title":"attachmentButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachmentButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/attachmentButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"attachmentButton"}],"url":"\/documentation\/divar\/inputareaviewcontroller\/attachmentbutton"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/post":{"role":"symbol","title":"post","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"post"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostViewStructure","preciseIdentifier":"s:5Divar17PostViewStructureV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/post","kind":"symbol","type":"topic","url":"\/documentation\/divar\/inputareaviewcontroller\/post"},"doc://com.Divar.DivarClient/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIScrollViewDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/SendButtonState":{"role":"symbol","title":"InputAreaViewController.SendButtonState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SendButtonState"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/SendButtonState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SendButtonState"}],"url":"\/documentation\/divar\/inputareaviewcontroller\/sendbuttonstate"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/heightConstraint":{"role":"symbol","title":"heightConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"heightConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/heightConstraint","kind":"symbol","type":"topic","url":"\/documentation\/divar\/inputareaviewcontroller\/heightconstraint"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/prepareForEditWarnedMessage(text:)":{"role":"symbol","title":"prepareForEditWarnedMessage(text:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareForEditWarnedMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/prepareForEditWarnedMessage(text:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/inputareaviewcontroller\/prepareforeditwarnedmessage(text:)"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/conversation":{"role":"symbol","title":"conversation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatConversationTable","preciseIdentifier":"s:5Divar21ChatConversationTableV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/conversation","kind":"symbol","type":"topic","url":"\/documentation\/divar\/inputareaviewcontroller\/conversation"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/UITextViewDelegate-Implementations":{"role":"collectionGroup","title":"UITextViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/UITextViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/inputareaviewcontroller\/uitextviewdelegate-implementations"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/objc(pl)UITextViewDelegate":{"type":"unresolvable","title":"UIKit.UITextViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITextViewDelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"InputAreaViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"InputAreaViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"InputAreaViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/attachmentButton","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/recordingView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/sendButton","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/textView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/topDivider"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/attachmentButtonAction(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/sendButtonAction(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/startRecording(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/UIGestureRecognizerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/UITextViewDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"InputAreaViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController","preciseIdentifier":"c:@M@Divar@objc(cs)BaseViewController","text":"BaseViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController\/title","value":"BaseViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController\/fragments","value":[{"kind":"identifier","text":"BaseViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController~1sendButton\/title","value":"sendButton"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController~1sendButton\/fragments","value":[{"kind":"identifier","text":"sendButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController~1topDivider\/title","value":"topDivider"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController~1topDivider\/fragments","value":[{"kind":"identifier","text":"topDivider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController~1sendButtonAction(_:)\/title","value":"sendButtonAction:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController~1sendButtonAction(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendButtonAction:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController~1startRecording(_:)\/title","value":"startRecording:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController~1startRecording(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startRecording:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController~1attachmentButtonAction(_:)\/title","value":"attachmentButtonAction:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController~1attachmentButtonAction(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"attachmentButtonAction:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController~1textView\/title","value":"textView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController~1textView\/fragments","value":[{"kind":"identifier","text":"textView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController\/title","value":"InputAreaViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController\/fragments","value":[{"kind":"identifier","text":"InputAreaViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController~1recordingView\/title","value":"recordingView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController~1recordingView\/fragments","value":[{"kind":"identifier","text":"recordingView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController~1attachmentButton\/title","value":"attachmentButton"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController~1attachmentButton\/fragments","value":[{"kind":"identifier","text":"attachmentButton"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}