{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSCoreLocalStorageProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"JSExport","preciseIdentifier":"c:objc(pl)JSExport"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/jscorelocalstorageprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/jscorelocalstorageprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)JSExport"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreLocalStorage-swift.class"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreLocalStorageProtocol","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreLocalStorageProtocol\/getItem(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreLocalStorageProtocol\/setItem(_:_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSCoreLocalStorageProtocol"}],"title":"JSCoreLocalStorageProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)JSCoreLocalStorage","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"JSCoreLocalStorageProtocol"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/objc(pl)JSExport":{"type":"unresolvable","title":"JSExport","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)JSExport"},"doc://com.Divar.DivarClient/documentation/Divar/JSCoreLocalStorage-swift.class":{"role":"symbol","title":"JSCoreLocalStorage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSCoreLocalStorage"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreLocalStorage-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JSCoreLocalStorage"}],"url":"\/documentation\/divar\/jscorelocalstorage-swift.class"},"doc://com.Divar.DivarClient/documentation/Divar/JSCoreLocalStorageProtocol/getItem(_:)":{"navigatorTitle":[{"kind":"identifier","text":"getItem:"}],"role":"symbol","title":"getItem(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getItem"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreLocalStorageProtocol\/getItem(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/jscorelocalstorageprotocol\/getitem(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/JSCoreLocalStorageProtocol/setItem(_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"setItem::"}],"role":"symbol","title":"setItem(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setItem"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreLocalStorageProtocol\/setItem(_:_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/jscorelocalstorageprotocol\/setitem(_:_:)"},"doc://com.Divar.DivarClient/documentation/Divar/JSCoreLocalStorageProtocol":{"role":"symbol","title":"JSCoreLocalStorageProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSCoreLocalStorageProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreLocalStorageProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JSCoreLocalStorageProtocol"}],"url":"\/documentation\/divar\/jscorelocalstorageprotocol"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"JSCoreLocalStorage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JSCoreLocalStorage"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"JSCoreLocalStorage"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreLocalStorageProtocol\/getItem(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreLocalStorageProtocol\/setItem(_:_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)JSExport"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreLocalStorage-swift.class"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSCoreLocalStorage"},{"kind":"text","text":"<"},{"kind":"keyword","text":"JSExport"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreLocalStorage-swift.class\/title","value":"JSCoreLocalStorage"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreLocalStorage-swift.class\/fragments","value":[{"kind":"identifier","text":"JSCoreLocalStorage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreLocalStorageProtocol~1getItem(_:)\/title","value":"getItem:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreLocalStorageProtocol~1getItem(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreLocalStorageProtocol~1setItem(_:_:)\/title","value":"setItem::"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreLocalStorageProtocol~1setItem(_:_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setItem::"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreLocalStorageProtocol\/title","value":"JSCoreLocalStorage"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreLocalStorageProtocol\/fragments","value":[{"kind":"identifier","text":"JSCoreLocalStorage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}