{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSCoreWindowProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"JSExport","preciseIdentifier":"c:objc(pl)JSExport"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/jscorewindowprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/jscorewindowprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)JSExport"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreWindow-swift.class"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreWindowProtocol","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreWindowProtocol\/clearTimeout(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreWindowProtocol\/localStorage()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreWindowProtocol\/setInterval(_:_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreWindowProtocol\/setTimeout(_:_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSCoreWindowProtocol"}],"title":"JSCoreWindowProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)JSCoreWindow","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"JSCoreWindowProtocol"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/JSCoreWindowProtocol/setTimeout(_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"setTimeout::"}],"role":"symbol","title":"setTimeout(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTimeout"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"JSValue","preciseIdentifier":"c:objc(cs)JSValue"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreWindowProtocol\/setTimeout(_:_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/jscorewindowprotocol\/settimeout(_:_:)"},"doc://com.Divar.DivarClient/documentation/Divar/JSCoreWindow-swift.class":{"role":"symbol","title":"JSCoreWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSCoreWindow"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreWindow-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JSCoreWindow"}],"url":"\/documentation\/divar\/jscorewindow-swift.class"},"doc://com.Divar.DivarClient/documentation/Divar/JSCoreWindowProtocol":{"role":"symbol","title":"JSCoreWindowProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSCoreWindowProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreWindowProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JSCoreWindowProtocol"}],"url":"\/documentation\/divar\/jscorewindowprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/JSCoreWindowProtocol/setInterval(_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"setInterval::"}],"role":"symbol","title":"setInterval(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setInterval"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"JSValue","preciseIdentifier":"c:objc(cs)JSValue"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreWindowProtocol\/setInterval(_:_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/jscorewindowprotocol\/setinterval(_:_:)"},"doc://com.Divar.DivarClient/documentation/Divar/JSCoreWindowProtocol/localStorage()":{"navigatorTitle":[{"kind":"identifier","text":"localStorage"}],"role":"symbol","title":"localStorage()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"localStorage"},{"kind":"text","text":"() -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreWindowProtocol\/localStorage()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/jscorewindowprotocol\/localstorage()"},"doc://com.Divar.DivarClient/documentation/Divar/JSCoreWindowProtocol/clearTimeout(_:)":{"navigatorTitle":[{"kind":"identifier","text":"clearTimeout:"}],"role":"symbol","title":"clearTimeout(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearTimeout"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreWindowProtocol\/clearTimeout(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/jscorewindowprotocol\/cleartimeout(_:)"},"doc://com.Divar.DivarClient/objc(pl)JSExport":{"type":"unresolvable","title":"JSExport","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)JSExport"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"JSCoreWindow"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JSCoreWindow"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"JSCoreWindow"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreWindowProtocol\/clearTimeout(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreWindowProtocol\/localStorage()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreWindowProtocol\/setInterval(_:_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreWindowProtocol\/setTimeout(_:_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)JSExport"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreWindow-swift.class"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSCoreWindow"},{"kind":"text","text":"<"},{"kind":"keyword","text":"JSExport"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreWindowProtocol~1setTimeout(_:_:)\/title","value":"setTimeout::"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreWindowProtocol~1setTimeout(_:_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setTimeout::"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreWindow-swift.class\/title","value":"JSCoreWindow"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreWindow-swift.class\/fragments","value":[{"kind":"identifier","text":"JSCoreWindow"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreWindowProtocol\/title","value":"JSCoreWindow"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreWindowProtocol\/fragments","value":[{"kind":"identifier","text":"JSCoreWindow"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreWindowProtocol~1setInterval(_:_:)\/title","value":"setInterval::"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreWindowProtocol~1setInterval(_:_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setInterval::"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreWindowProtocol~1localStorage()\/title","value":"localStorage"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreWindowProtocol~1localStorage()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"localStorage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreWindowProtocol~1clearTimeout(_:)\/title","value":"clearTimeout:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreWindowProtocol~1clearTimeout(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"clearTimeout:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}