{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSCoreLocalStorage"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/jscorelocalstorage-swift.class"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/jscorelocalstorage-swift.class"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreLocalStorageProtocol","doc:\/\/com.Divar.DivarClient\/objc(pl)JSExport","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreLocalStorage-swift.class","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreLocalStorage-swift.class\/init(urlSession:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreLocalStorage-swift.class\/extend(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSCoreLocalStorage"}],"title":"JSCoreLocalStorage","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)JSCoreLocalStorage","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"JSCoreLocalStorage"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/JSCoreLocalStorage-swift.class/init(urlSession:)":{"role":"symbol","title":"init(urlSession:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"urlSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreLocalStorage-swift.class\/init(urlSession:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithURLSession:"}],"url":"\/documentation\/divar\/jscorelocalstorage-swift.class\/init(urlsession:)"},"doc://com.Divar.DivarClient/documentation/Divar/JSCoreLocalStorage-swift.class/extend(_:)":{"role":"symbol","title":"extend(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"extend"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreLocalStorage-swift.class\/extend(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"extend:"}],"url":"\/documentation\/divar\/jscorelocalstorage-swift.class\/extend(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/JSCoreLocalStorage-swift.class":{"role":"symbol","title":"JSCoreLocalStorage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSCoreLocalStorage"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreLocalStorage-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JSCoreLocalStorage"}],"url":"\/documentation\/divar\/jscorelocalstorage-swift.class"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/objc(pl)JSExport":{"type":"unresolvable","title":"JavaScriptCore.JSExport","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)JSExport"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/JSCoreLocalStorageProtocol":{"role":"symbol","title":"JSCoreLocalStorageProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSCoreLocalStorageProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreLocalStorageProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JSCoreLocalStorageProtocol"}],"url":"\/documentation\/divar\/jscorelocalstorageprotocol"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"JSCoreLocalStorage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JSCoreLocalStorage"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"JSCoreLocalStorage"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreLocalStorage-swift.class\/extend(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreLocalStorage-swift.class\/init(urlSession:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JSCoreLocalStorageProtocol"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSCoreLocalStorage"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreLocalStorage-swift.class~1init(urlSession:)\/title","value":"initWithURLSession:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreLocalStorage-swift.class~1init(urlSession:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithURLSession:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreLocalStorage-swift.class~1extend(_:)\/title","value":"extend:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreLocalStorage-swift.class~1extend(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"extend:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreLocalStorage-swift.class\/title","value":"JSCoreLocalStorage"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreLocalStorage-swift.class\/fragments","value":[{"kind":"identifier","text":"JSCoreLocalStorage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreLocalStorageProtocol\/title","value":"JSCoreLocalStorage"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JSCoreLocalStorageProtocol\/fragments","value":[{"kind":"identifier","text":"JSCoreLocalStorage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}