{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandlineVerificationFlowControllerDelegate"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/landlineverificationflowcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AgentManagementFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BrowseFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BulkLadderBaseFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentBulkLadderFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentFormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarInspectionFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarLandingPageFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarPriceFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarSpecsFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerFormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealershipGetContactFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeaturedPostsFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JobsFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JobsFormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/KalaDetailsFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandingPageFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LinkFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MFMessageFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceFormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplacePriceFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceQuickEditPostFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceRegisterFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NationalIdVerificationFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OpenPageFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OperatorManagementFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostDetailsFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateBulkLadderFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateFormFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SaleAssistantFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SettingsFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShahkarLandlineVerificationFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SubmitPromotionFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TestPhoneNumberFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransactionFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UserRegisterFlowController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowControllerDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowControllerDelegate\/landlineConfirmedSuccessfully(in:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandlineVerificationFlowControllerDelegate"}],"title":"LandlineVerificationFlowControllerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar42LandlineVerificationFlowControllerDelegateP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"LandlineVerificationFlowControllerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/TestPhoneNumberFlowController":{"role":"symbol","title":"TestPhoneNumberFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TestPhoneNumberFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TestPhoneNumberFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TestPhoneNumberFlowController"}],"url":"\/documentation\/divar\/testphonenumberflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarPriceFlowController":{"role":"symbol","title":"CarPriceFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarPriceFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarPriceFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarPriceFlowController"}],"url":"\/documentation\/divar\/carpriceflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MarketplaceRegisterFlowController":{"role":"symbol","title":"MarketplaceRegisterFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketplaceRegisterFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceRegisterFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketplaceRegisterFlowController"}],"url":"\/documentation\/divar\/marketplaceregisterflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BulkLadderBaseFlowController":{"role":"symbol","title":"BulkLadderBaseFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BulkLadderBaseFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BulkLadderBaseFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BulkLadderBaseFlowController"}],"url":"\/documentation\/divar\/bulkladderbaseflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/RealEstateFormFlowController":{"role":"symbol","title":"RealEstateFormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RealEstateFormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateFormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RealEstateFormFlowController"}],"url":"\/documentation\/divar\/realestateformflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SaleAssistantFlowController":{"role":"symbol","title":"SaleAssistantFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SaleAssistantFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SaleAssistantFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SaleAssistantFlowController"}],"url":"\/documentation\/divar\/saleassistantflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarSpecsFlowController":{"role":"symbol","title":"CarSpecsFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarSpecsFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarSpecsFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarSpecsFlowController"}],"url":"\/documentation\/divar\/carspecsflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarAgentBulkLadderFlowController":{"role":"symbol","title":"CarAgentBulkLadderFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarAgentBulkLadderFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentBulkLadderFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarAgentBulkLadderFlowController"}],"url":"\/documentation\/divar\/caragentbulkladderflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/UserRegisterFlowController":{"role":"symbol","title":"UserRegisterFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserRegisterFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UserRegisterFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserRegisterFlowController"}],"url":"\/documentation\/divar\/userregisterflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SubmitPromotionFlowController":{"role":"symbol","title":"SubmitPromotionFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubmitPromotionFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SubmitPromotionFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SubmitPromotionFlowController"}],"url":"\/documentation\/divar\/submitpromotionflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/LinkFlowController":{"role":"symbol","title":"LinkFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LinkFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LinkFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LinkFlowController"}],"url":"\/documentation\/divar\/linkflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/NationalIdVerificationFlowController":{"role":"symbol","title":"NationalIdVerificationFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NationalIdVerificationFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NationalIdVerificationFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NationalIdVerificationFlowController"}],"url":"\/documentation\/divar\/nationalidverificationflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarInspectionFlowController":{"role":"symbol","title":"CarInspectionFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarInspectionFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarInspectionFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarInspectionFlowController"}],"url":"\/documentation\/divar\/carinspectionflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MarketplacePriceFlowController":{"role":"symbol","title":"MarketplacePriceFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketplacePriceFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplacePriceFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketplacePriceFlowController"}],"url":"\/documentation\/divar\/marketplacepriceflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MarketPlaceFlowController":{"role":"symbol","title":"MarketPlaceFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketPlaceFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketPlaceFlowController"}],"url":"\/documentation\/divar\/marketplaceflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/LandlineVerificationFlowControllerDelegate/landlineConfirmedSuccessfully(in:)":{"role":"symbol","title":"landlineConfirmedSuccessfully(in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"landlineConfirmedSuccessfully"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LandlineVerificationFlowController","preciseIdentifier":"c:@M@Divar@objc(cs)LandlineVerificationFlowController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowControllerDelegate\/landlineConfirmedSuccessfully(in:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/landlineverificationflowcontrollerdelegate\/landlineconfirmedsuccessfully(in:)"},"doc://com.Divar.DivarClient/documentation/Divar/CarLandingPageFlowController":{"role":"symbol","title":"CarLandingPageFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarLandingPageFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarLandingPageFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarLandingPageFlowController"}],"url":"\/documentation\/divar\/carlandingpageflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MFMessageFlowController":{"role":"symbol","title":"MFMessageFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MFMessageFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MFMessageFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MFMessageFlowController"}],"url":"\/documentation\/divar\/mfmessageflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatFlowController":{"role":"symbol","title":"ChatFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatFlowController"}],"url":"\/documentation\/divar\/chatflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MarketplaceQuickEditPostFlowController":{"role":"symbol","title":"MarketplaceQuickEditPostFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketplaceQuickEditPostFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceQuickEditPostFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketplaceQuickEditPostFlowController"}],"url":"\/documentation\/divar\/marketplacequickeditpostflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/JobsFormFlowController":{"role":"symbol","title":"JobsFormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JobsFormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JobsFormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JobsFormFlowController"}],"url":"\/documentation\/divar\/jobsformflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/LandlineVerificationFlowControllerDelegate":{"role":"symbol","title":"LandlineVerificationFlowControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandlineVerificationFlowControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandlineVerificationFlowControllerDelegate"}],"url":"\/documentation\/divar\/landlineverificationflowcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/SettingsFlowController":{"role":"symbol","title":"SettingsFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SettingsFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SettingsFlowController"}],"url":"\/documentation\/divar\/settingsflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/LandingPageFlowController":{"role":"symbol","title":"LandingPageFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandingPageFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandingPageFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandingPageFlowController"}],"url":"\/documentation\/divar\/landingpageflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/RealEstateFlowController":{"role":"symbol","title":"RealEstateFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RealEstateFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RealEstateFlowController"}],"url":"\/documentation\/divar\/realestateflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/IVFlowController":{"role":"symbol","title":"IVFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IVFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/IVFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IVFlowController"}],"url":"\/documentation\/divar\/ivflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/KalaDetailsFlowController":{"role":"symbol","title":"KalaDetailsFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KalaDetailsFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/KalaDetailsFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KalaDetailsFlowController"}],"url":"\/documentation\/divar\/kaladetailsflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PriceFlowController":{"role":"symbol","title":"PriceFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PriceFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PriceFlowController"}],"url":"\/documentation\/divar\/priceflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarAgentFormFlowController":{"role":"symbol","title":"CarAgentFormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarAgentFormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentFormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarAgentFormFlowController"}],"url":"\/documentation\/divar\/caragentformflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AgentManagementFlowController":{"role":"symbol","title":"AgentManagementFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgentManagementFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AgentManagementFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgentManagementFlowController"}],"url":"\/documentation\/divar\/agentmanagementflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/FeaturedPostsFlowController":{"role":"symbol","title":"FeaturedPostsFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeaturedPostsFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeaturedPostsFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeaturedPostsFlowController"}],"url":"\/documentation\/divar\/featuredpostsflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/LandlineVerificationFlowController":{"role":"symbol","title":"LandlineVerificationFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandlineVerificationFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandlineVerificationFlowController"}],"url":"\/documentation\/divar\/landlineverificationflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostManageFlowController":{"role":"symbol","title":"PostManageFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostManageFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostManageFlowController"}],"url":"\/documentation\/divar\/postmanageflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/RealEstateBulkLadderFlowController":{"role":"symbol","title":"RealEstateBulkLadderFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RealEstateBulkLadderFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateBulkLadderFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RealEstateBulkLadderFlowController"}],"url":"\/documentation\/divar\/realestatebulkladderflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderFlowController":{"role":"symbol","title":"MyDivarHolderFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyDivarHolderFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MyDivarHolderFlowController"}],"url":"\/documentation\/divar\/mydivarholderflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ShahkarLandlineVerificationFlowController":{"role":"symbol","title":"ShahkarLandlineVerificationFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShahkarLandlineVerificationFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShahkarLandlineVerificationFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShahkarLandlineVerificationFlowController"}],"url":"\/documentation\/divar\/shahkarlandlineverificationflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController":{"role":"symbol","title":"BaseFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseFlowController"}],"url":"\/documentation\/divar\/baseflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/OpenPageFlowController":{"role":"symbol","title":"OpenPageFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenPageFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OpenPageFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenPageFlowController"}],"url":"\/documentation\/divar\/openpageflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/TransactionFlowController":{"role":"symbol","title":"TransactionFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransactionFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransactionFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TransactionFlowController"}],"url":"\/documentation\/divar\/transactionflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarBusinessFlowController":{"role":"symbol","title":"CarBusinessFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarBusinessFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarBusinessFlowController"}],"url":"\/documentation\/divar\/carbusinessflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/DealerFormFlowController":{"role":"symbol","title":"DealerFormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DealerFormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerFormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DealerFormFlowController"}],"url":"\/documentation\/divar\/dealerformflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostListFlowController":{"role":"symbol","title":"PostListFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostListFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostListFlowController"}],"url":"\/documentation\/divar\/postlistflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/FormFlowController":{"role":"symbol","title":"FormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FormFlowController"}],"url":"\/documentation\/divar\/formflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/DealershipGetContactFlowController":{"role":"symbol","title":"DealershipGetContactFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DealershipGetContactFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealershipGetContactFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DealershipGetContactFlowController"}],"url":"\/documentation\/divar\/dealershipgetcontactflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/DealerFlowController":{"role":"symbol","title":"DealerFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DealerFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DealerFlowController"}],"url":"\/documentation\/divar\/dealerflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MarketplaceFormFlowController":{"role":"symbol","title":"MarketplaceFormFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketplaceFormFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceFormFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketplaceFormFlowController"}],"url":"\/documentation\/divar\/marketplaceformflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarAgentFlowController":{"role":"symbol","title":"CarAgentFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarAgentFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarAgentFlowController"}],"url":"\/documentation\/divar\/caragentflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BrowseFlowController":{"role":"symbol","title":"BrowseFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrowseFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BrowseFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BrowseFlowController"}],"url":"\/documentation\/divar\/browseflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/JobsFlowController":{"role":"symbol","title":"JobsFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JobsFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JobsFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JobsFlowController"}],"url":"\/documentation\/divar\/jobsflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/OperatorManagementFlowController":{"role":"symbol","title":"OperatorManagementFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OperatorManagementFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OperatorManagementFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OperatorManagementFlowController"}],"url":"\/documentation\/divar\/operatormanagementflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostDetailsFlowController":{"role":"symbol","title":"PostDetailsFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostDetailsFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostDetailsFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostDetailsFlowController"}],"url":"\/documentation\/divar\/postdetailsflowcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TestPhoneNumberFlowController\/title","value":"TestPhoneNumberFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TestPhoneNumberFlowController\/fragments","value":[{"kind":"identifier","text":"TestPhoneNumberFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarPriceFlowController\/title","value":"CarPriceFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarPriceFlowController\/fragments","value":[{"kind":"identifier","text":"CarPriceFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceRegisterFlowController\/title","value":"MarketplaceRegisterFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceRegisterFlowController\/fragments","value":[{"kind":"identifier","text":"MarketplaceRegisterFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BulkLadderBaseFlowController\/title","value":"BulkLadderBaseFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BulkLadderBaseFlowController\/fragments","value":[{"kind":"identifier","text":"BulkLadderBaseFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateFormFlowController\/title","value":"RealEstateFormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateFormFlowController\/fragments","value":[{"kind":"identifier","text":"RealEstateFormFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SaleAssistantFlowController\/title","value":"SaleAssistantFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SaleAssistantFlowController\/fragments","value":[{"kind":"identifier","text":"SaleAssistantFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarSpecsFlowController\/title","value":"CarSpecsFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarSpecsFlowController\/fragments","value":[{"kind":"identifier","text":"CarSpecsFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentBulkLadderFlowController\/title","value":"CarAgentBulkLadderFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentBulkLadderFlowController\/fragments","value":[{"kind":"identifier","text":"CarAgentBulkLadderFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1UserRegisterFlowController\/title","value":"UserRegisterFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1UserRegisterFlowController\/fragments","value":[{"kind":"identifier","text":"UserRegisterFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SubmitPromotionFlowController\/title","value":"SubmitPromotionFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SubmitPromotionFlowController\/fragments","value":[{"kind":"identifier","text":"SubmitPromotionFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LinkFlowController\/title","value":"LinkFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LinkFlowController\/fragments","value":[{"kind":"identifier","text":"LinkFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NationalIdVerificationFlowController\/title","value":"NationalIdVerificationFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NationalIdVerificationFlowController\/fragments","value":[{"kind":"identifier","text":"NationalIdVerificationFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarInspectionFlowController\/title","value":"CarInspectionFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarInspectionFlowController\/fragments","value":[{"kind":"identifier","text":"CarInspectionFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplacePriceFlowController\/title","value":"MarketplacePriceFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplacePriceFlowController\/fragments","value":[{"kind":"identifier","text":"MarketplacePriceFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketPlaceFlowController\/title","value":"MarketPlaceFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketPlaceFlowController\/fragments","value":[{"kind":"identifier","text":"MarketPlaceFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarLandingPageFlowController\/title","value":"CarLandingPageFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarLandingPageFlowController\/fragments","value":[{"kind":"identifier","text":"CarLandingPageFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MFMessageFlowController\/title","value":"MFMessageFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MFMessageFlowController\/fragments","value":[{"kind":"identifier","text":"MFMessageFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatFlowController\/title","value":"ChatFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatFlowController\/fragments","value":[{"kind":"identifier","text":"ChatFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceQuickEditPostFlowController\/title","value":"MarketplaceQuickEditPostFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceQuickEditPostFlowController\/fragments","value":[{"kind":"identifier","text":"MarketplaceQuickEditPostFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JobsFormFlowController\/title","value":"JobsFormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JobsFormFlowController\/fragments","value":[{"kind":"identifier","text":"JobsFormFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SettingsFlowController\/title","value":"SettingsFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SettingsFlowController\/fragments","value":[{"kind":"identifier","text":"SettingsFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandingPageFlowController\/title","value":"LandingPageFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandingPageFlowController\/fragments","value":[{"kind":"identifier","text":"LandingPageFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateFlowController\/title","value":"RealEstateFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateFlowController\/fragments","value":[{"kind":"identifier","text":"RealEstateFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1IVFlowController\/title","value":"IVFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1IVFlowController\/fragments","value":[{"kind":"identifier","text":"IVFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1KalaDetailsFlowController\/title","value":"KalaDetailsFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1KalaDetailsFlowController\/fragments","value":[{"kind":"identifier","text":"KalaDetailsFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceFlowController\/title","value":"PriceFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceFlowController\/fragments","value":[{"kind":"identifier","text":"PriceFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentFormFlowController\/title","value":"CarAgentFormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentFormFlowController\/fragments","value":[{"kind":"identifier","text":"CarAgentFormFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AgentManagementFlowController\/title","value":"AgentManagementFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AgentManagementFlowController\/fragments","value":[{"kind":"identifier","text":"AgentManagementFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeaturedPostsFlowController\/title","value":"FeaturedPostsFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeaturedPostsFlowController\/fragments","value":[{"kind":"identifier","text":"FeaturedPostsFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandlineVerificationFlowController\/title","value":"LandlineVerificationFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandlineVerificationFlowController\/fragments","value":[{"kind":"identifier","text":"LandlineVerificationFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostManageFlowController\/title","value":"PostManageFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostManageFlowController\/fragments","value":[{"kind":"identifier","text":"PostManageFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateBulkLadderFlowController\/title","value":"RealEstateBulkLadderFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateBulkLadderFlowController\/fragments","value":[{"kind":"identifier","text":"RealEstateBulkLadderFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MyDivarHolderFlowController\/title","value":"MyDivarHolderFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MyDivarHolderFlowController\/fragments","value":[{"kind":"identifier","text":"MyDivarHolderFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ShahkarLandlineVerificationFlowController\/title","value":"ShahkarLandlineVerificationFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ShahkarLandlineVerificationFlowController\/fragments","value":[{"kind":"identifier","text":"ShahkarLandlineVerificationFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/title","value":"BaseFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/fragments","value":[{"kind":"identifier","text":"BaseFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OpenPageFlowController\/title","value":"OpenPageFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OpenPageFlowController\/fragments","value":[{"kind":"identifier","text":"OpenPageFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TransactionFlowController\/title","value":"TransactionFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TransactionFlowController\/fragments","value":[{"kind":"identifier","text":"TransactionFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarBusinessFlowController\/title","value":"CarBusinessFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarBusinessFlowController\/fragments","value":[{"kind":"identifier","text":"CarBusinessFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerFormFlowController\/title","value":"DealerFormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerFormFlowController\/fragments","value":[{"kind":"identifier","text":"DealerFormFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListFlowController\/title","value":"PostListFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListFlowController\/fragments","value":[{"kind":"identifier","text":"PostListFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FormFlowController\/title","value":"FormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FormFlowController\/fragments","value":[{"kind":"identifier","text":"FormFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealershipGetContactFlowController\/title","value":"DealershipGetContactFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealershipGetContactFlowController\/fragments","value":[{"kind":"identifier","text":"DealershipGetContactFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerFlowController\/title","value":"DealerFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerFlowController\/fragments","value":[{"kind":"identifier","text":"DealerFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceFormFlowController\/title","value":"MarketplaceFormFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceFormFlowController\/fragments","value":[{"kind":"identifier","text":"MarketplaceFormFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentFlowController\/title","value":"CarAgentFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentFlowController\/fragments","value":[{"kind":"identifier","text":"CarAgentFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BrowseFlowController\/title","value":"BrowseFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BrowseFlowController\/fragments","value":[{"kind":"identifier","text":"BrowseFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JobsFlowController\/title","value":"JobsFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JobsFlowController\/fragments","value":[{"kind":"identifier","text":"JobsFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OperatorManagementFlowController\/title","value":"OperatorManagementFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OperatorManagementFlowController\/fragments","value":[{"kind":"identifier","text":"OperatorManagementFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostDetailsFlowController\/title","value":"PostDetailsFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostDetailsFlowController\/fragments","value":[{"kind":"identifier","text":"PostDetailsFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}