{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandingActionHandler"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/landingactionhandler"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarLandingPageFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandingPageFlowController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandingActionHandler","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandingActionHandler\/openDealershipManagement(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandingActionHandler\/openMarketplaceLandingPage(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandingActionHandler"}],"title":"LandingActionHandler","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar20LandingActionHandlerP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"LandingActionHandler"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/LandingActionHandler":{"role":"symbol","title":"LandingActionHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandingActionHandler"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandingActionHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandingActionHandler"}],"url":"\/documentation\/divar\/landingactionhandler"},"doc://com.Divar.DivarClient/documentation/Divar/LandingActionHandler/openDealershipManagement(_:)":{"role":"symbol","title":"openDealershipManagement(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openDealershipManagement"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandingActionHandler\/openDealershipManagement(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/landingactionhandler\/opendealershipmanagement(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/LandingPageFlowController":{"role":"symbol","title":"LandingPageFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandingPageFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandingPageFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandingPageFlowController"}],"url":"\/documentation\/divar\/landingpageflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarLandingPageFlowController":{"role":"symbol","title":"CarLandingPageFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarLandingPageFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarLandingPageFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarLandingPageFlowController"}],"url":"\/documentation\/divar\/carlandingpageflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/LandingActionHandler/openMarketplaceLandingPage(_:)":{"role":"symbol","title":"openMarketplaceLandingPage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openMarketplaceLandingPage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandingActionHandler\/openMarketplaceLandingPage(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/landingactionhandler\/openmarketplacelandingpage(_:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandingPageFlowController\/title","value":"LandingPageFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandingPageFlowController\/fragments","value":[{"kind":"identifier","text":"LandingPageFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarLandingPageFlowController\/title","value":"CarLandingPageFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarLandingPageFlowController\/fragments","value":[{"kind":"identifier","text":"CarLandingPageFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}