{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/locationmanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/locationmanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)CLLocationManagerDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationManager","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationManager\/authorizationStatus"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationManager\/locationManager(_:didChangeAuthorization:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationManager\/locationManager(_:didFailWithError:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationManager\/locationManager(_:didUpdateLocations:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationManager\/requestAuthorize(completion:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationManager\/requestLocation(accuracy:completion:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationManager\/sharedInstance"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationManager"}],"title":"LocationManager","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)LocationManager","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"LocationManager"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/LocationManager/requestLocation(accuracy:completion:)":{"role":"symbol","title":"requestLocation(accuracy:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestLocation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accuracy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationAccuracy","preciseIdentifier":"c:@T@CLLocationAccuracy"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationManager\/requestLocation(accuracy:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/locationmanager\/requestlocation(accuracy:completion:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/LocationManager":{"role":"symbol","title":"LocationManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationManager"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationManager"}],"url":"\/documentation\/divar\/locationmanager"},"doc://com.Divar.DivarClient/documentation/Divar/LocationManager/authorizationStatus":{"role":"symbol","title":"authorizationStatus","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizationStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLAuthorizationStatus","preciseIdentifier":"c:@E@CLAuthorizationStatus"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationManager\/authorizationStatus","kind":"symbol","type":"topic","url":"\/documentation\/divar\/locationmanager\/authorizationstatus"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/LocationManager/locationManager(_:didFailWithError:)":{"role":"symbol","title":"locationManager(_:didFailWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationManager\/locationManager(_:didFailWithError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"locationManager:didFailWithError:"}],"url":"\/documentation\/divar\/locationmanager\/locationmanager(_:didfailwitherror:)"},"doc://com.Divar.DivarClient/documentation/Divar/LocationManager/sharedInstance":{"role":"symbol","title":"sharedInstance","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedInstance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LocationManager","preciseIdentifier":"c:@M@Divar@objc(cs)LocationManager"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationManager\/sharedInstance","kind":"symbol","type":"topic","url":"\/documentation\/divar\/locationmanager\/sharedinstance"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/objc(pl)CLLocationManagerDelegate":{"type":"unresolvable","title":"CLLocationManagerDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)CLLocationManagerDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/LocationManager/requestAuthorize(completion:)":{"role":"symbol","title":"requestAuthorize(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestAuthorize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationManager\/requestAuthorize(completion:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/locationmanager\/requestauthorize(completion:)"},"doc://com.Divar.DivarClient/documentation/Divar/LocationManager/locationManager(_:didUpdateLocations:)":{"role":"symbol","title":"locationManager(_:didUpdateLocations:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateLocations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationManager\/locationManager(_:didUpdateLocations:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"locationManager:didUpdateLocations:"}],"url":"\/documentation\/divar\/locationmanager\/locationmanager(_:didupdatelocations:)"},"doc://com.Divar.DivarClient/documentation/Divar/LocationManager/locationManager(_:didChangeAuthorization:)":{"role":"symbol","title":"locationManager(_:didChangeAuthorization:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeAuthorization"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLAuthorizationStatus","preciseIdentifier":"c:@E@CLAuthorizationStatus"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationManager\/locationManager(_:didChangeAuthorization:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"locationManager:didChangeAuthorizationStatus:"}],"url":"\/documentation\/divar\/locationmanager\/locationmanager(_:didchangeauthorization:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"LocationManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LocationManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"LocationManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationManager\/locationManager(_:didChangeAuthorization:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationManager\/locationManager(_:didFailWithError:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LocationManager\/locationManager(_:didUpdateLocations:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)CLLocationManagerDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LocationManager\/title","value":"LocationManager"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LocationManager\/fragments","value":[{"kind":"identifier","text":"LocationManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LocationManager~1locationManager(_:didFailWithError:)\/title","value":"locationManager:didFailWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LocationManager~1locationManager(_:didFailWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationManager:didFailWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LocationManager~1locationManager(_:didUpdateLocations:)\/title","value":"locationManager:didUpdateLocations:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LocationManager~1locationManager(_:didUpdateLocations:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationManager:didUpdateLocations:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LocationManager~1locationManager(_:didChangeAuthorization:)\/title","value":"locationManager:didChangeAuthorizationStatus:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LocationManager~1locationManager(_:didChangeAuthorization:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationManager:didChangeAuthorizationStatus:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}