{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MainFlowController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/mainflowcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/mainflowcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UITabBarController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedBackViewProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FirstTimeViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostChatNavigator","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITabBarControllerDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UITabBarDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/init(container:introConfig:payload:personalDocumentHelper:businessDocumentHelper:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/businessDocumentHelper","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/chatFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/checkForUpdate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/configUser","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/connectionChangeHandler","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/container","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/feedBackHandler","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/firstPass","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/introConfig","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/notificationToken","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/payload","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/personalDocumentHelper","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/registerationHandler","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/serviceNetwork","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/splashView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/changeSelectedTab(to:distanceVC:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/currentTabName(for:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/forceUpdate(url:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/handleChatNewMessage(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/handlePayload(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/observeNotifications()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/performAction(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/reloadTabs()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/socketConnectionChanged(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/traitCollectionDidChange(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/updateProfileBadge()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/userRegisterationChanged(notification:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/viewDidAppear(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/FeedBackViewProtocol-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/FirstTimeViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/PostChatNavigator-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/UITabBarControllerDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MainFlowController"}],"title":"MainFlowController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)MainFlowController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"MainFlowController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/changeSelectedTab(to:distanceVC:)":{"role":"symbol","title":"changeSelectedTab(to:distanceVC:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeSelectedTab"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"distanceVC"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/changeSelectedTab(to:distanceVC:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/changeselectedtab(to:distancevc:)"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/mainflowcontroller\/init(coder:)"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/performAction(_:)":{"role":"symbol","title":"performAction(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"performAction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UniversalPayload","preciseIdentifier":"s:5Divar16UniversalPayloadV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/performAction(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/performaction(_:)"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/objc(pl)UITabBarControllerDelegate":{"type":"unresolvable","title":"UITabBarControllerDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITabBarControllerDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/container":{"role":"symbol","title":"container","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MainFlowControllerDIContainer","preciseIdentifier":"s:5Divar29MainFlowControllerDIContainera"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/container","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/container"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController":{"role":"symbol","title":"MainFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MainFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MainFlowController"}],"url":"\/documentation\/divar\/mainflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/feedBackHandler":{"role":"symbol","title":"feedBackHandler","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"feedBackHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FeedBackHandler","preciseIdentifier":"s:5Divar15FeedBackHandlerC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/feedBackHandler","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/feedbackhandler"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/serviceNetwork":{"role":"symbol","title":"serviceNetwork","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"serviceNetwork"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ServiceNetworkManagerProtocol","preciseIdentifier":"s:5Divar29ServiceNetworkManagerProtocolP"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/serviceNetwork","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/servicenetwork"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/connectionChangeHandler":{"role":"symbol","title":"connectionChangeHandler","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionChangeHandler"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/connectionChangeHandler","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/connectionchangehandler"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/objc(pl)UITabBarDelegate":{"type":"unresolvable","title":"UIKit.UITabBarDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITabBarDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/payload":{"role":"symbol","title":"payload","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"payload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UniversalPayload","preciseIdentifier":"s:5Divar16UniversalPayloadV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/payload","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/payload"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/businessDocumentHelper":{"role":"symbol","title":"businessDocumentHelper","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"businessDocumentHelper"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentHelper","preciseIdentifier":"s:5Divar14DocumentHelperC"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/businessDocumentHelper","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/businessdocumenthelper"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/currentTabName(for:)":{"role":"symbol","title":"currentTabName(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentTabName"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/currentTabName(for:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/currenttabname(for:)"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/FirstTimeViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"FirstTimeViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/FirstTimeViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/firsttimeviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/viewDidAppear(_:)":{"role":"symbol","title":"viewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/viewDidAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"url":"\/documentation\/divar\/mainflowcontroller\/viewdidappear(_:)"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/FirstTimeViewControllerDelegate":{"role":"symbol","title":"FirstTimeViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FirstTimeViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FirstTimeViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FirstTimeViewControllerDelegate"}],"url":"\/documentation\/divar\/firsttimeviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/forceUpdate(url:)":{"role":"symbol","title":"forceUpdate(url:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"forceUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/forceUpdate(url:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/forceupdate(url:)"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/socketConnectionChanged(_:)":{"role":"symbol","title":"socketConnectionChanged(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"socketConnectionChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/socketConnectionChanged(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"socketConnectionChanged:"}],"url":"\/documentation\/divar\/mainflowcontroller\/socketconnectionchanged(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/traitCollectionDidChange(_:)":{"role":"symbol","title":"traitCollectionDidChange(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"traitCollectionDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/traitCollectionDidChange(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"traitCollectionDidChange:"}],"url":"\/documentation\/divar\/mainflowcontroller\/traitcollectiondidchange(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/notificationToken":{"role":"symbol","title":"notificationToken","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"notificationToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/notificationToken","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/notificationtoken"},"doc://com.Divar.DivarClient/documentation/Divar/FeedBackViewProtocol":{"role":"symbol","title":"FeedBackViewProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeedBackViewProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedBackViewProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeedBackViewProtocol"}],"url":"\/documentation\/divar\/feedbackviewprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/UITabBarControllerDelegate-Implementations":{"role":"collectionGroup","title":"UITabBarControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/UITabBarControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/uitabbarcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/splashView":{"role":"symbol","title":"splashView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"splashView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DivarSplashView","preciseIdentifier":"c:@M@Divar@objc(cs)DivarSplashView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/splashView","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/splashview"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/personalDocumentHelper":{"role":"symbol","title":"personalDocumentHelper","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"personalDocumentHelper"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentHelper","preciseIdentifier":"s:5Divar14DocumentHelperC"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/personalDocumentHelper","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/personaldocumenthelper"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/reloadTabs()":{"role":"symbol","title":"reloadTabs()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reloadTabs"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/reloadTabs()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/reloadtabs()"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/PostChatNavigator-Implementations":{"role":"collectionGroup","title":"PostChatNavigator Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/PostChatNavigator-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/postchatnavigator-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/configUser":{"role":"symbol","title":"configUser","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/configUser","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/configuser"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/chatFlowController":{"role":"symbol","title":"chatFlowController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatFlowController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatFlowController","preciseIdentifier":"c:@M@Divar@objc(cs)ChatFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/chatFlowController","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/chatflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/mainflowcontroller\/viewdidload()"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/introConfig":{"role":"symbol","title":"introConfig","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"introConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IntroConfig","preciseIdentifier":"s:5Divar11IntroConfigV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/introConfig","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/introconfig"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/observeNotifications()":{"role":"symbol","title":"observeNotifications()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeNotifications"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/observeNotifications()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/observenotifications()"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/firstPass":{"role":"symbol","title":"firstPass","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstPass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/firstPass","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/firstpass"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/updateProfileBadge()":{"role":"symbol","title":"updateProfileBadge()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateProfileBadge"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/updateProfileBadge()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateProfileBadge"}],"url":"\/documentation\/divar\/mainflowcontroller\/updateprofilebadge()"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/documentation/Divar/PostChatNavigator":{"role":"symbol","title":"PostChatNavigator","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostChatNavigator"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostChatNavigator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostChatNavigator"}],"url":"\/documentation\/divar\/postchatnavigator"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/checkForUpdate":{"role":"symbol","title":"checkForUpdate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkForUpdate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/checkForUpdate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/checkforupdate"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/userRegisterationChanged(notification:)":{"role":"symbol","title":"userRegisterationChanged(notification:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userRegisterationChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"notification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/userRegisterationChanged(notification:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userRegisterationChangedWithNotification:"}],"url":"\/documentation\/divar\/mainflowcontroller\/userregisterationchanged(notification:)"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/handleChatNewMessage(_:)":{"role":"symbol","title":"handleChatNewMessage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleChatNewMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/handleChatNewMessage(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"handleChatNewMessage:"}],"url":"\/documentation\/divar\/mainflowcontroller\/handlechatnewmessage(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/init(container:introConfig:payload:personalDocumentHelper:businessDocumentHelper:)":{"role":"symbol","title":"init(container:introConfig:payload:personalDocumentHelper:businessDocumentHelper:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MainFlowControllerDIContainer","preciseIdentifier":"s:5Divar29MainFlowControllerDIContainera"},{"kind":"text","text":", "},{"kind":"externalParam","text":"introConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IntroConfig","preciseIdentifier":"s:5Divar11IntroConfigV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"payload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UniversalPayload","preciseIdentifier":"s:5Divar16UniversalPayloadV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"personalDocumentHelper"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentHelper","preciseIdentifier":"s:5Divar14DocumentHelperC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"businessDocumentHelper"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentHelper","preciseIdentifier":"s:5Divar14DocumentHelperC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/init(container:introConfig:payload:personalDocumentHelper:businessDocumentHelper:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/init(container:introconfig:payload:personaldocumenthelper:businessdocumenthelper:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/FeedBackViewProtocol-Implementations":{"role":"collectionGroup","title":"FeedBackViewProtocol Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/FeedBackViewProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/feedbackviewprotocol-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/registerationHandler":{"role":"symbol","title":"registerationHandler","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerationHandler"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/registerationHandler","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/registerationhandler"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/objc(cs)UITabBarController":{"type":"unresolvable","title":"UITabBarController","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)UITabBarController"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController/handlePayload(_:)":{"role":"symbol","title":"handlePayload(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handlePayload"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UniversalPayload","preciseIdentifier":"s:5Divar16UniversalPayloadV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/handlePayload(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mainflowcontroller\/handlepayload(_:)"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MainFlowController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MainFlowController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MainFlowController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/handleChatNewMessage(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/socketConnectionChanged(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/traitCollectionDidChange(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/updateProfileBadge()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/userRegisterationChanged(notification:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/viewDidAppear(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController\/UITabBarControllerDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UITabBarController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)UITabBarControllerDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MainFlowController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UITabBarController","preciseIdentifier":"c:objc(cs)UITabBarController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController\/title","value":"MainFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController\/fragments","value":[{"kind":"identifier","text":"MainFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController~1viewDidAppear(_:)\/title","value":"viewDidAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController~1socketConnectionChanged(_:)\/title","value":"socketConnectionChanged:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController~1socketConnectionChanged(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"socketConnectionChanged:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController~1traitCollectionDidChange(_:)\/title","value":"traitCollectionDidChange:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController~1traitCollectionDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"traitCollectionDidChange:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController~1updateProfileBadge()\/title","value":"updateProfileBadge"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController~1updateProfileBadge()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateProfileBadge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController~1userRegisterationChanged(notification:)\/title","value":"userRegisterationChangedWithNotification:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController~1userRegisterationChanged(notification:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userRegisterationChangedWithNotification:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController~1handleChatNewMessage(_:)\/title","value":"handleChatNewMessage:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController~1handleChatNewMessage(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleChatNewMessage:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}