{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketPlaceFlowController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/marketplaceflowcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/marketplaceflowcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CategoryHierarchyControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CityMultiSelectViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LoginRequiredProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceActionHandler","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchFilterViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedActionDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/cancelPromotion(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/finalizeMarketplaceEditStore(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/finalizeMarketplaceRegisterStore(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/marketplaceFreeSubscription(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/marketplaceRemoveAssistant(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/openMakretplacePrize(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/openMarketplaceAssistantPage(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/openMarketplaceBulkLadder(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/openMarketplaceFeaturesList(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/openMarketplaceGetContact(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/openMarketplacePostFeedbackOptions(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/openMarketplacePostsManagementPage(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/openMarketplaceRegisterPage(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/openMarketplaceStoreStatsPage(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/openMarketplaceStoresList(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/openMarketplaceSubscriptionStatus(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/openMarketplaceViewPostFeedbackPage(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/postponeRegisterStore(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/shareStoreLanding(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketPlaceFlowController"}],"title":"MarketPlaceFlowController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)MarketPlaceFlowController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"MarketPlaceFlowController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedActionDelegate":{"role":"symbol","title":"WidgetBasedActionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedActionDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedActionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedActionDelegate"}],"url":"\/documentation\/divar\/widgetbasedactiondelegate"},"doc://com.Divar.DivarClient/documentation/Divar/MarketPlaceFlowController/cancelPromotion(_:)":{"role":"symbol","title":"cancelPromotion(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelPromotion"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/cancelPromotion(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/marketplaceflowcontroller\/cancelpromotion(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/MarketPlaceFlowController":{"role":"symbol","title":"MarketPlaceFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketPlaceFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketPlaceFlowController"}],"url":"\/documentation\/divar\/marketplaceflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MarketPlaceFlowController/openMarketplaceRegisterPage(_:)":{"role":"symbol","title":"openMarketplaceRegisterPage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openMarketplaceRegisterPage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/openMarketplaceRegisterPage(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/marketplaceflowcontroller\/openmarketplaceregisterpage(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewControllerDelegate":{"role":"symbol","title":"PostArchiveViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostArchiveViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostArchiveViewControllerDelegate"}],"url":"\/documentation\/divar\/postarchiveviewcontrollerdelegate"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/LoginRequiredProtocol":{"role":"symbol","title":"LoginRequiredProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoginRequiredProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LoginRequiredProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LoginRequiredProtocol"}],"url":"\/documentation\/divar\/loginrequiredprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/MarketPlaceFlowController/openMarketplacePostFeedbackOptions(_:)":{"role":"symbol","title":"openMarketplacePostFeedbackOptions(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openMarketplacePostFeedbackOptions"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/openMarketplacePostFeedbackOptions(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/marketplaceflowcontroller\/openmarketplacepostfeedbackoptions(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/MarketPlaceFlowController/openMarketplaceStoresList(_:)":{"role":"symbol","title":"openMarketplaceStoresList(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openMarketplaceStoresList"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/openMarketplaceStoresList(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/marketplaceflowcontroller\/openmarketplacestoreslist(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/MarketPlaceFlowController/openMarketplaceSubscriptionStatus(_:)":{"role":"symbol","title":"openMarketplaceSubscriptionStatus(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openMarketplaceSubscriptionStatus"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/openMarketplaceSubscriptionStatus(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/marketplaceflowcontroller\/openmarketplacesubscriptionstatus(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/MarketPlaceFlowController/openMarketplaceGetContact(_:)":{"role":"symbol","title":"openMarketplaceGetContact(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openMarketplaceGetContact"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/openMarketplaceGetContact(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/marketplaceflowcontroller\/openmarketplacegetcontact(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/MarketPlaceFlowController/finalizeMarketplaceRegisterStore(_:)":{"role":"symbol","title":"finalizeMarketplaceRegisterStore(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalizeMarketplaceRegisterStore"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/finalizeMarketplaceRegisterStore(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/marketplaceflowcontroller\/finalizemarketplaceregisterstore(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/RateViewControllerDelegate":{"role":"symbol","title":"RateViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RateViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RateViewControllerDelegate"}],"url":"\/documentation\/divar\/rateviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/CategoryHierarchyControllerDelegate":{"role":"symbol","title":"CategoryHierarchyControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CategoryHierarchyControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CategoryHierarchyControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CategoryHierarchyControllerDelegate"}],"url":"\/documentation\/divar\/categoryhierarchycontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/PostCreateViewControllerDelegate":{"role":"symbol","title":"PostCreateViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostCreateViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostCreateViewControllerDelegate"}],"url":"\/documentation\/divar\/postcreateviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/MarketPlaceFlowController/shareStoreLanding(_:)":{"role":"symbol","title":"shareStoreLanding(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shareStoreLanding"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/shareStoreLanding(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/marketplaceflowcontroller\/sharestorelanding(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/MarketPlaceFlowController/openMarketplaceStoreStatsPage(_:)":{"role":"symbol","title":"openMarketplaceStoreStatsPage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openMarketplaceStoreStatsPage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/openMarketplaceStoreStatsPage(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/marketplaceflowcontroller\/openmarketplacestorestatspage(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/MarketPlaceFlowController/openMarketplaceViewPostFeedbackPage(_:)":{"role":"symbol","title":"openMarketplaceViewPostFeedbackPage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openMarketplaceViewPostFeedbackPage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/openMarketplaceViewPostFeedbackPage(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/marketplaceflowcontroller\/openmarketplaceviewpostfeedbackpage(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/LandlineVerificationFlowControllerDelegate":{"role":"symbol","title":"LandlineVerificationFlowControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandlineVerificationFlowControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandlineVerificationFlowControllerDelegate"}],"url":"\/documentation\/divar\/landlineverificationflowcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/MarketPlaceFlowController/marketplaceRemoveAssistant(_:)":{"role":"symbol","title":"marketplaceRemoveAssistant(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"marketplaceRemoveAssistant"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/marketplaceRemoveAssistant(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/marketplaceflowcontroller\/marketplaceremoveassistant(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController":{"role":"symbol","title":"BaseFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseFlowController"}],"url":"\/documentation\/divar\/baseflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MarketPlaceFlowController/openMakretplacePrize(_:)":{"role":"symbol","title":"openMakretplacePrize(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openMakretplacePrize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/openMakretplacePrize(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/marketplaceflowcontroller\/openmakretplaceprize(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/MarketPlaceFlowController/openMarketplaceBulkLadder(_:)":{"role":"symbol","title":"openMarketplaceBulkLadder(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openMarketplaceBulkLadder"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/openMarketplaceBulkLadder(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/marketplaceflowcontroller\/openmarketplacebulkladder(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/CityMultiSelectViewControllerDelegate":{"role":"symbol","title":"CityMultiSelectViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CityMultiSelectViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CityMultiSelectViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CityMultiSelectViewControllerDelegate"}],"url":"\/documentation\/divar\/citymultiselectviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/SearchFilterViewControllerDelegate":{"role":"symbol","title":"SearchFilterViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchFilterViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchFilterViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchFilterViewControllerDelegate"}],"url":"\/documentation\/divar\/searchfilterviewcontrollerdelegate"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/MarketPlaceFlowController/openMarketplaceFeaturesList(_:)":{"role":"symbol","title":"openMarketplaceFeaturesList(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openMarketplaceFeaturesList"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/openMarketplaceFeaturesList(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/marketplaceflowcontroller\/openmarketplacefeatureslist(_:)"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/MarketPlaceFlowController/openMarketplaceAssistantPage(_:)":{"role":"symbol","title":"openMarketplaceAssistantPage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openMarketplaceAssistantPage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/openMarketplaceAssistantPage(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/marketplaceflowcontroller\/openmarketplaceassistantpage(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/MarketPlaceFlowController/marketplaceFreeSubscription(_:)":{"role":"symbol","title":"marketplaceFreeSubscription(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"marketplaceFreeSubscription"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/marketplaceFreeSubscription(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/marketplaceflowcontroller\/marketplacefreesubscription(_:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/MarketPlaceActionHandler":{"role":"symbol","title":"MarketPlaceActionHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketPlaceActionHandler"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceActionHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketPlaceActionHandler"}],"url":"\/documentation\/divar\/marketplaceactionhandler"},"doc://com.Divar.DivarClient/documentation/Divar/MarketPlaceFlowController/finalizeMarketplaceEditStore(_:)":{"role":"symbol","title":"finalizeMarketplaceEditStore(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalizeMarketplaceEditStore"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/finalizeMarketplaceEditStore(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/marketplaceflowcontroller\/finalizemarketplaceeditstore(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/MarketPlaceFlowController/postponeRegisterStore(_:)":{"role":"symbol","title":"postponeRegisterStore(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postponeRegisterStore"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/postponeRegisterStore(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/marketplaceflowcontroller\/postponeregisterstore(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/MarketPlaceFlowController/openMarketplacePostsManagementPage(_:)":{"role":"symbol","title":"openMarketplacePostsManagementPage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openMarketplacePostsManagementPage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketPlaceFlowController\/openMarketplacePostsManagementPage(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/marketplaceflowcontroller\/openmarketplacepostsmanagementpage(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MarketPlaceFlowController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MarketPlaceFlowController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MarketPlaceFlowController"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketPlaceFlowController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","preciseIdentifier":"c:@M@Divar@objc(cs)BaseFlowController","text":"BaseFlowController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketPlaceFlowController\/title","value":"MarketPlaceFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketPlaceFlowController\/fragments","value":[{"kind":"identifier","text":"MarketPlaceFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/title","value":"BaseFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/fragments","value":[{"kind":"identifier","text":"BaseFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}