{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/messagingviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/messagingviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CallLogCellDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatCacheRequestHelper","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FileMessageCellDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PhotoMessageCellDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PlayAudioDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PrivacyCellDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)QLPreviewControllerDataSource","doc:\/\/com.Divar.DivarClient\/objc(pl)QLPreviewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RefreshableProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextMessageCellDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIScrollViewDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoMessageCellDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceMessageCellProtocol"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/init(container:conversationID:configuration:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/announcements","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/announcementsFilter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/audioPlayer","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/changedContentOffsetY","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/configuration","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/container","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/conversation","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/conversationID","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/conversationMessages","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/dataSource","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/delegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/filePreviewInfo","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/firstUnreadMessage","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/highlightingIndexPath","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/isAllowedToRequestMoreMessages","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/isConversationLoaded","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/isInPreviewMode","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/isShowingPostchi","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/loadMoreDataWorkItem","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/loadTimeLastSeenTimeUUID","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/messageShouldGoTo","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/messagesFilter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/parentVeiwController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/playerStatus","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/post","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/tableView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/cell(item:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/clearData()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/getLastReadMessage()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/getMessagesCompleted(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/goToReplyMessageIfNeeded()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/gotToMessage(id:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/hideKeyboardOutsideTap()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/highlightCell(indexPath:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/loadMoreMessagesIfNeeded(_:onConversationIsLoaded:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/previewFile(url:showSaveButton:title:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/registerCells()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/reloadMessageRow(for:animated:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/scrollToEndIfNeeded(extraHeight:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/setNeedsRefreshData()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/viewDidDisappear(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/viewDidLoad()"]},{"title":"Enumerations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/CellType","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/Content","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/SectionType"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/CallLogCellDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/ChatCacheRequestHelper-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/FileMessageCellDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/PhotoMessageCellDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/PlayAudioDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/PrivacyCellDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/QLPreviewControllerDataSource-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/QLPreviewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/RefreshableProtocol-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/TextMessageCellDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/UIScrollViewDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/UITableViewDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/VideoMessageCellDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/VoiceMessageCellProtocol-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingViewController"}],"title":"MessagingViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)MessagingViewController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"MessagingViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/firstUnreadMessage":{"role":"symbol","title":"firstUnreadMessage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstUnreadMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/firstUnreadMessage","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/firstunreadmessage"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/cell(item:)":{"role":"symbol","title":"cell(item:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cell"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CellType","preciseIdentifier":"s:5Divar23MessagingViewControllerC8CellTypeO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/cell(item:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/cell(item:)"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/conversationID":{"role":"symbol","title":"conversationID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/conversationID","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/conversationid"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/dataSource":{"role":"symbol","title":"dataSource","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableViewDiffableDataSource","preciseIdentifier":"s:5UIKit29UITableViewDiffableDataSourceC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"SectionType","preciseIdentifier":"s:5Divar23MessagingViewControllerC11SectionTypeO"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"CellType","preciseIdentifier":"s:5Divar23MessagingViewControllerC8CellTypeO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/dataSource","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/datasource"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/VoiceMessageCellProtocol-Implementations":{"role":"collectionGroup","title":"VoiceMessageCellProtocol Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/VoiceMessageCellProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/voicemessagecellprotocol-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/registerCells()":{"role":"symbol","title":"registerCells()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerCells"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/registerCells()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/registercells()"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/tableView":{"role":"symbol","title":"tableView","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/tableView","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/tableview"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/hideKeyboardOutsideTap()":{"role":"symbol","title":"hideKeyboardOutsideTap()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideKeyboardOutsideTap"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/hideKeyboardOutsideTap()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/hidekeyboardoutsidetap()"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/audioPlayer":{"role":"symbol","title":"audioPlayer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioPlayManager","preciseIdentifier":"c:@M@Divar@objc(cs)AudioPlayManager"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/audioPlayer","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/audioplayer"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/isAllowedToRequestMoreMessages":{"role":"symbol","title":"isAllowedToRequestMoreMessages","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAllowedToRequestMoreMessages"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/isAllowedToRequestMoreMessages","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/isallowedtorequestmoremessages"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/filePreviewInfo":{"role":"symbol","title":"filePreviewInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"filePreviewInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileInfo","preciseIdentifier":"c:@M@Divar@objc(cs)FileInfo"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/filePreviewInfo","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/filepreviewinfo"},"doc://com.Divar.DivarClient/objc(pl)QLPreviewControllerDataSource":{"type":"unresolvable","title":"QuickLook.QLPreviewControllerDataSource","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)QLPreviewControllerDataSource"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/PhotoMessageCellDelegate-Implementations":{"role":"collectionGroup","title":"PhotoMessageCellDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/PhotoMessageCellDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/photomessagecelldelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/ChatCacheRequestHelper":{"role":"symbol","title":"ChatCacheRequestHelper","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatCacheRequestHelper"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatCacheRequestHelper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatCacheRequestHelper"}],"url":"\/documentation\/divar\/chatcacherequesthelper"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/UITableViewDelegate-Implementations":{"role":"collectionGroup","title":"UITableViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/UITableViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/uitableviewdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController":{"role":"symbol","title":"MessagingViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagingViewController"}],"url":"\/documentation\/divar\/messagingviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/init(container:conversationID:configuration:)":{"role":"symbol","title":"init(container:conversationID:configuration:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagingViewControllerDIContainer","preciseIdentifier":"s:5Divar34MessagingViewControllerDIContainera"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IntroConfig","preciseIdentifier":"s:5Divar11IntroConfigV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/init(container:conversationID:configuration:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/init(container:conversationid:configuration:)"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/FileMessageCellDelegate-Implementations":{"role":"collectionGroup","title":"FileMessageCellDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/FileMessageCellDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/filemessagecelldelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/RefreshableProtocol":{"role":"symbol","title":"RefreshableProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RefreshableProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RefreshableProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RefreshableProtocol"}],"url":"\/documentation\/divar\/refreshableprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/CallLogCellDelegate-Implementations":{"role":"collectionGroup","title":"CallLogCellDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/CallLogCellDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/calllogcelldelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/messagingviewcontroller\/viewdidload()"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/goToReplyMessageIfNeeded()":{"role":"symbol","title":"goToReplyMessageIfNeeded()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"goToReplyMessageIfNeeded"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/goToReplyMessageIfNeeded()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/gotoreplymessageifneeded()"},"doc://com.Divar.DivarClient/documentation/Divar/ShowMessageProtocol":{"role":"symbol","title":"ShowMessageProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowMessageProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowMessageProtocol"}],"url":"\/documentation\/divar\/showmessageprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceMessageCellProtocol":{"role":"symbol","title":"VoiceMessageCellProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoiceMessageCellProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceMessageCellProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VoiceMessageCellProtocol"}],"url":"\/documentation\/divar\/voicemessagecellprotocol"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/CellType":{"role":"symbol","title":"MessagingViewController.CellType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CellType"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/CellType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CellType"}],"url":"\/documentation\/divar\/messagingviewcontroller\/celltype"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/container":{"role":"symbol","title":"container","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagingViewControllerDIContainer","preciseIdentifier":"s:5Divar34MessagingViewControllerDIContainera"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/container","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/container"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/changedContentOffsetY":{"role":"symbol","title":"changedContentOffsetY","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedContentOffsetY"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/changedContentOffsetY","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/changedcontentoffsety"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagingViewControllerDelegate","preciseIdentifier":"s:5Divar31MessagingViewControllerDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/delegate"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/messagesFilter":{"role":"symbol","title":"messagesFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagesFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"QueryFilter","preciseIdentifier":"s:5Divar11QueryFilterV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/messagesFilter","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/messagesfilter"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/isShowingPostchi":{"role":"symbol","title":"isShowingPostchi","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isShowingPostchi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/isShowingPostchi","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/isshowingpostchi"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/playerStatus":{"role":"symbol","title":"playerStatus","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioPlayerStatus","preciseIdentifier":"s:5Divar17AudioPlayerStatusO"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/playerStatus","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/playerstatus"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/gotToMessage(id:)":{"role":"symbol","title":"gotToMessage(id:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gotToMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/gotToMessage(id:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/gottomessage(id:)"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/PlayAudioDelegate-Implementations":{"role":"collectionGroup","title":"PlayAudioDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/PlayAudioDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/playaudiodelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/highlightingIndexPath":{"role":"symbol","title":"highlightingIndexPath","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightingIndexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/highlightingIndexPath","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/highlightingindexpath"},"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController":{"role":"symbol","title":"BaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseViewController"}],"url":"\/documentation\/divar\/baseviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/loadMoreDataWorkItem":{"role":"symbol","title":"loadMoreDataWorkItem","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadMoreDataWorkItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DispatchWorkItem","preciseIdentifier":"s:8Dispatch0A8WorkItemC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/loadMoreDataWorkItem","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/loadmoredataworkitem"},"doc://com.Divar.DivarClient/objc(pl)QLPreviewControllerDelegate":{"type":"unresolvable","title":"QuickLook.QLPreviewControllerDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)QLPreviewControllerDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/getLastReadMessage()":{"role":"symbol","title":"getLastReadMessage()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLastReadMessage"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/getLastReadMessage()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/getlastreadmessage()"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/conversationMessages":{"role":"symbol","title":"conversationMessages","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationMessages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/conversationMessages","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/conversationmessages"},"doc://com.Divar.DivarClient/documentation/Divar/VideoMessageCellDelegate":{"role":"symbol","title":"VideoMessageCellDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoMessageCellDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoMessageCellDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoMessageCellDelegate"}],"url":"\/documentation\/divar\/videomessagecelldelegate"},"doc://com.Divar.DivarClient/objc(pl)UITableViewDelegate":{"type":"unresolvable","title":"UIKit.UITableViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDelegate"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/loadTimeLastSeenTimeUUID":{"role":"symbol","title":"loadTimeLastSeenTimeUUID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadTimeLastSeenTimeUUID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/loadTimeLastSeenTimeUUID","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/loadtimelastseentimeuuid"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/VideoMessageCellDelegate-Implementations":{"role":"collectionGroup","title":"VideoMessageCellDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/VideoMessageCellDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/videomessagecelldelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/UIScrollViewDelegate-Implementations":{"role":"collectionGroup","title":"UIScrollViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/UIScrollViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/uiscrollviewdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/messageShouldGoTo":{"role":"symbol","title":"messageShouldGoTo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageShouldGoTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/messageShouldGoTo","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/messageshouldgoto"},"doc://com.Divar.DivarClient/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIScrollViewDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/conversation":{"role":"symbol","title":"conversation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatConversationTable","preciseIdentifier":"s:5Divar21ChatConversationTableV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/conversation","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/conversation"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/highlightCell(indexPath:)":{"role":"symbol","title":"highlightCell(indexPath:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightCell"},{"kind":"text","text":"("},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/highlightCell(indexPath:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/highlightcell(indexpath:)"},"doc://com.Divar.DivarClient/documentation/Divar/ErrorMessageHandler":{"role":"symbol","title":"ErrorMessageHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorMessageHandler"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorMessageHandler"}],"url":"\/documentation\/divar\/errormessagehandler"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/getMessagesCompleted(_:)":{"role":"symbol","title":"getMessagesCompleted(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMessagesCompleted"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/getMessagesCompleted(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getMessagesCompleted:"}],"url":"\/documentation\/divar\/messagingviewcontroller\/getmessagescompleted(_:)"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/loadMoreMessagesIfNeeded(_:onConversationIsLoaded:)":{"role":"symbol","title":"loadMoreMessagesIfNeeded(_:onConversationIsLoaded:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadMoreMessagesIfNeeded"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RequestCompletionHandlerType","preciseIdentifier":"s:5Divar28RequestCompletionHandlerTypea"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ChatGetMessageResponseStructure","preciseIdentifier":"s:5Divar31ChatGetMessageResponseStructureV"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"onConversationIsLoaded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CompletionHandlerType","preciseIdentifier":"s:5Divar21CompletionHandlerTypea"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/loadMoreMessagesIfNeeded(_:onConversationIsLoaded:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/loadmoremessagesifneeded(_:onconversationisloaded:)"},"doc://com.Divar.DivarClient/documentation/Divar/PaymentSystemProtocol":{"role":"symbol","title":"PaymentSystemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSystemProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaymentSystemProtocol"}],"url":"\/documentation\/divar\/paymentsystemprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/post":{"role":"symbol","title":"post","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"post"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostViewStructure","preciseIdentifier":"s:5Divar17PostViewStructureV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/post","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/post"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/setNeedsRefreshData()":{"role":"symbol","title":"setNeedsRefreshData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setNeedsRefreshData"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/setNeedsRefreshData()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/setneedsrefreshdata()"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/scrollToEndIfNeeded(extraHeight:)":{"role":"symbol","title":"scrollToEndIfNeeded(extraHeight:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollToEndIfNeeded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"extraHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/scrollToEndIfNeeded(extraHeight:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/scrolltoendifneeded(extraheight:)"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/announcements":{"role":"symbol","title":"announcements","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"announcements"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatAnnouncementTable","preciseIdentifier":"s:5Divar21ChatAnnouncementTableV"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/announcements","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/announcements"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/clearData()":{"role":"symbol","title":"clearData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearData"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/clearData()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/cleardata()"},"doc://com.Divar.DivarClient/documentation/Divar/ShowErrorProtocol":{"role":"symbol","title":"ShowErrorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowErrorProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowErrorProtocol"}],"url":"\/documentation\/divar\/showerrorprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/isInPreviewMode":{"role":"symbol","title":"isInPreviewMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInPreviewMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/isInPreviewMode","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/isinpreviewmode"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/configuration":{"role":"symbol","title":"configuration","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IntroConfig","preciseIdentifier":"s:5Divar11IntroConfigV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/configuration","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/configuration"},"doc://com.Divar.DivarClient/documentation/Divar/FileMessageCellDelegate":{"role":"symbol","title":"FileMessageCellDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileMessageCellDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FileMessageCellDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FileMessageCellDelegate"}],"url":"\/documentation\/divar\/filemessagecelldelegate"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/previewFile(url:showSaveButton:title:)":{"role":"symbol","title":"previewFile(url:showSaveButton:title:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewFile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"showSaveButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/previewFile(url:showSaveButton:title:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/previewfile(url:showsavebutton:title:)"},"doc://com.Divar.DivarClient/documentation/Divar/TooltipPresenter":{"role":"symbol","title":"TooltipPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TooltipPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TooltipPresenter"}],"url":"\/documentation\/divar\/tooltippresenter"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/SectionType":{"role":"symbol","title":"MessagingViewController.SectionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SectionType"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/SectionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SectionType"}],"url":"\/documentation\/divar\/messagingviewcontroller\/sectiontype"},"doc://com.Divar.DivarClient/documentation/Divar/PlayAudioDelegate":{"role":"symbol","title":"PlayAudioDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayAudioDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PlayAudioDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlayAudioDelegate"}],"url":"\/documentation\/divar\/playaudiodelegate"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/messagingviewcontroller\/init(coder:)"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/announcementsFilter":{"role":"symbol","title":"announcementsFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"announcementsFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"QueryFilter","preciseIdentifier":"s:5Divar11QueryFilterV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/announcementsFilter","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/announcementsfilter"},"doc://com.Divar.DivarClient/documentation/Divar/PrivacyCellDelegate":{"role":"symbol","title":"PrivacyCellDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrivacyCellDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PrivacyCellDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PrivacyCellDelegate"}],"url":"\/documentation\/divar\/privacycelldelegate"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/ChatCacheRequestHelper-Implementations":{"role":"collectionGroup","title":"ChatCacheRequestHelper Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/ChatCacheRequestHelper-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/chatcacherequesthelper-implementations"},"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/PrivacyCellDelegate-Implementations":{"role":"collectionGroup","title":"PrivacyCellDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/PrivacyCellDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/privacycelldelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/reloadMessageRow(for:animated:)":{"role":"symbol","title":"reloadMessageRow(for:animated:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reloadMessageRow"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/reloadMessageRow(for:animated:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/reloadmessagerow(for:animated:)"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/isConversationLoaded":{"role":"symbol","title":"isConversationLoaded","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isConversationLoaded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/isConversationLoaded","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/isconversationloaded"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/QLPreviewControllerDataSource-Implementations":{"role":"collectionGroup","title":"QLPreviewControllerDataSource Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/QLPreviewControllerDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/qlpreviewcontrollerdatasource-implementations"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PhotoMessageCellDelegate":{"role":"symbol","title":"PhotoMessageCellDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PhotoMessageCellDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PhotoMessageCellDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PhotoMessageCellDelegate"}],"url":"\/documentation\/divar\/photomessagecelldelegate"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/RefreshableProtocol-Implementations":{"role":"collectionGroup","title":"RefreshableProtocol Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/RefreshableProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/refreshableprotocol-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/Content":{"role":"symbol","title":"MessagingViewController.Content","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Content"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/Content","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Content"}],"url":"\/documentation\/divar\/messagingviewcontroller\/content"},"doc://com.Divar.DivarClient/documentation/Divar/CallLogCellDelegate":{"role":"symbol","title":"CallLogCellDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallLogCellDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CallLogCellDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallLogCellDelegate"}],"url":"\/documentation\/divar\/calllogcelldelegate"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/documentation/Divar/TextMessageCellDelegate":{"role":"symbol","title":"TextMessageCellDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextMessageCellDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextMessageCellDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TextMessageCellDelegate"}],"url":"\/documentation\/divar\/textmessagecelldelegate"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/viewDidDisappear(_:)":{"role":"symbol","title":"viewDidDisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/viewDidDisappear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidDisappear:"}],"url":"\/documentation\/divar\/messagingviewcontroller\/viewdiddisappear(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/TextMessageCellDelegate-Implementations":{"role":"collectionGroup","title":"TextMessageCellDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/TextMessageCellDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/textmessagecelldelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/parentVeiwController":{"role":"symbol","title":"parentVeiwController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parentVeiwController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageHandlingType","preciseIdentifier":"s:5Divar19MessageHandlingTypea"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/parentVeiwController","kind":"symbol","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/parentveiwcontroller"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController/QLPreviewControllerDelegate-Implementations":{"role":"collectionGroup","title":"QLPreviewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/QLPreviewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/messagingviewcontroller\/qlpreviewcontrollerdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MessagingViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MessagingViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MessagingViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/getMessagesCompleted(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/viewDidDisappear(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/QLPreviewControllerDataSource-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/QLPreviewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/UIScrollViewDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController\/UITableViewDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController","preciseIdentifier":"c:@M@Divar@objc(cs)BaseViewController","text":"BaseViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController\/title","value":"MessagingViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController\/fragments","value":[{"kind":"identifier","text":"MessagingViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController\/title","value":"BaseViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController\/fragments","value":[{"kind":"identifier","text":"BaseViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController~1getMessagesCompleted(_:)\/title","value":"getMessagesCompleted:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController~1getMessagesCompleted(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMessagesCompleted:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController~1viewDidDisappear(_:)\/title","value":"viewDidDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController~1viewDidDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidDisappear:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}