{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MetricKitConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/metrickitconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/metrickitconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppConfiguration","doc:\/\/com.Divar.DivarClient\/objc(pl)MXMetricManagerSubscriber","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MetricKitConfiguration","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MetricKitConfiguration\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MetricKitConfiguration\/metricManager"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MetricKitConfiguration\/config(data:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MetricKitConfiguration\/didReceive(_:)-86zt6","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MetricKitConfiguration\/didReceive(_:)-z3jm"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"MetricKitConfiguration"}],"role":"symbol","title":"MetricKitConfiguration","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MetricKitConfiguration"}],"symbolKind":"class","externalID":"c:@M@Divar@objc(cs)MetricKitConfiguration","modules":[{"name":"Divar"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/AppConfiguration":{"role":"symbol","title":"AppConfiguration","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppConfiguration"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AppConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppConfiguration"}],"url":"\/documentation\/divar\/appconfiguration"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/MetricKitConfiguration/metricManager":{"role":"symbol","title":"metricManager","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metricManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MXMetricManager","preciseIdentifier":"c:objc(cs)MXMetricManager"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MetricKitConfiguration\/metricManager","kind":"symbol","type":"topic","url":"\/documentation\/divar\/metrickitconfiguration\/metricmanager"},"doc://com.Divar.DivarClient/objc(pl)MXMetricManagerSubscriber":{"type":"unresolvable","title":"MXMetricManagerSubscriber","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)MXMetricManagerSubscriber"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/MetricKitConfiguration":{"role":"symbol","title":"MetricKitConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MetricKitConfiguration"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MetricKitConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MetricKitConfiguration"}],"url":"\/documentation\/divar\/metrickitconfiguration"},"doc://com.Divar.DivarClient/documentation/Divar/MetricKitConfiguration/didReceive(_:)-86zt6":{"role":"symbol","title":"didReceive(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceive"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"MXMetricPayload","preciseIdentifier":"c:objc(cs)MXMetricPayload"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MetricKitConfiguration\/didReceive(_:)-86zt6","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didReceiveMetricPayloads:"}],"url":"\/documentation\/divar\/metrickitconfiguration\/didreceive(_:)-86zt6"},"doc://com.Divar.DivarClient/documentation/Divar/MetricKitConfiguration/didReceive(_:)-z3jm":{"role":"symbol","title":"didReceive(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceive"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"MXDiagnosticPayload","preciseIdentifier":"c:objc(cs)MXDiagnosticPayload"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MetricKitConfiguration\/didReceive(_:)-z3jm","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didReceiveDiagnosticPayloads:"}],"url":"\/documentation\/divar\/metrickitconfiguration\/didreceive(_:)-z3jm"},"doc://com.Divar.DivarClient/documentation/Divar/MetricKitConfiguration/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MetricKitConfiguration\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/divar\/metrickitconfiguration\/init()"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/MetricKitConfiguration/config(data:)":{"role":"symbol","title":"config(data:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"config"},{"kind":"text","text":"("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IntroConfig","preciseIdentifier":"s:5Divar11IntroConfigV"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MetricKitConfiguration\/config(data:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/metrickitconfiguration\/config(data:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MetricKitConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MetricKitConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MetricKitConfiguration"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MetricKitConfiguration\/didReceive(_:)-86zt6","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MetricKitConfiguration\/didReceive(_:)-z3jm","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MetricKitConfiguration\/init()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)MXMetricManagerSubscriber"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MetricKitConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MetricKitConfiguration\/title","value":"MetricKitConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MetricKitConfiguration\/fragments","value":[{"kind":"identifier","text":"MetricKitConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MetricKitConfiguration~1didReceive(_:)-86zt6\/title","value":"didReceiveMetricPayloads:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MetricKitConfiguration~1didReceive(_:)-86zt6\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveMetricPayloads:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MetricKitConfiguration~1didReceive(_:)-z3jm\/title","value":"didReceiveDiagnosticPayloads:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MetricKitConfiguration~1didReceive(_:)-z3jm\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveDiagnosticPayloads:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MetricKitConfiguration~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MetricKitConfiguration~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}