{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyDivarHolderFlowController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/mydivarholderflowcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/mydivarholderflowcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CategoryHierarchyControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CityMultiSelectViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LoginRequiredProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarActionHandler","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyPostsViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NotesViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RecentVisitsViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchFilterViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedActionDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/initialBookmarkAndNotesViewController(with:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/initialMyPostsViewController(with:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/initialRecentPostsViewController(with:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/initialViewController()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/presentBookmark()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/presentMyPosts()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/presentNotes()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/presentRecentPosts()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/BookmarksViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/MyDivarActionHandler-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/MyDivarHolderViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/MyPostsViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/NotesViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/RecentVisitsViewControllerDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyDivarHolderFlowController"}],"title":"MyDivarHolderFlowController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)MyDivarHolderFlowController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"MyDivarHolderFlowController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderFlowController/presentBookmark()":{"role":"symbol","title":"presentBookmark()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentBookmark"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/presentBookmark()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mydivarholderflowcontroller\/presentbookmark()"},"doc://com.Divar.DivarClient/documentation/Divar/SearchFilterViewControllerDelegate":{"role":"symbol","title":"SearchFilterViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchFilterViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchFilterViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchFilterViewControllerDelegate"}],"url":"\/documentation\/divar\/searchfilterviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/LoginRequiredProtocol":{"role":"symbol","title":"LoginRequiredProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoginRequiredProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LoginRequiredProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LoginRequiredProtocol"}],"url":"\/documentation\/divar\/loginrequiredprotocol"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderFlowController/initialRecentPostsViewController(with:)":{"role":"symbol","title":"initialRecentPostsViewController(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialRecentPostsViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/initialRecentPostsViewController(with:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mydivarholderflowcontroller\/initialrecentpostsviewcontroller(with:)"},"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderFlowController/MyPostsViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"MyPostsViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/MyPostsViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/mydivarholderflowcontroller\/mypostsviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderFlowController":{"role":"symbol","title":"MyDivarHolderFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyDivarHolderFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MyDivarHolderFlowController"}],"url":"\/documentation\/divar\/mydivarholderflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderFlowController/NotesViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"NotesViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/NotesViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/mydivarholderflowcontroller\/notesviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/LandlineVerificationFlowControllerDelegate":{"role":"symbol","title":"LandlineVerificationFlowControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandlineVerificationFlowControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandlineVerificationFlowControllerDelegate"}],"url":"\/documentation\/divar\/landlineverificationflowcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderFlowController/MyDivarHolderViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"MyDivarHolderViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/MyDivarHolderViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/mydivarholderflowcontroller\/mydivarholderviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderFlowController/BookmarksViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"BookmarksViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/BookmarksViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/mydivarholderflowcontroller\/bookmarksviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PostCreateViewControllerDelegate":{"role":"symbol","title":"PostCreateViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostCreateViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostCreateViewControllerDelegate"}],"url":"\/documentation\/divar\/postcreateviewcontrollerdelegate"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderFlowController/presentMyPosts()":{"role":"symbol","title":"presentMyPosts()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentMyPosts"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/presentMyPosts()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mydivarholderflowcontroller\/presentmyposts()"},"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderFlowController/initialBookmarkAndNotesViewController(with:)":{"role":"symbol","title":"initialBookmarkAndNotesViewController(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialBookmarkAndNotesViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/initialBookmarkAndNotesViewController(with:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mydivarholderflowcontroller\/initialbookmarkandnotesviewcontroller(with:)"},"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderFlowController/MyDivarActionHandler-Implementations":{"role":"collectionGroup","title":"MyDivarActionHandler Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/MyDivarActionHandler-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/mydivarholderflowcontroller\/mydivaractionhandler-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/RecentVisitsViewControllerDelegate":{"role":"symbol","title":"RecentVisitsViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecentVisitsViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RecentVisitsViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RecentVisitsViewControllerDelegate"}],"url":"\/documentation\/divar\/recentvisitsviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/CityMultiSelectViewControllerDelegate":{"role":"symbol","title":"CityMultiSelectViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CityMultiSelectViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CityMultiSelectViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CityMultiSelectViewControllerDelegate"}],"url":"\/documentation\/divar\/citymultiselectviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarksViewControllerDelegate":{"role":"symbol","title":"BookmarksViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BookmarksViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarksViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BookmarksViewControllerDelegate"}],"url":"\/documentation\/divar\/bookmarksviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/MyPostsViewControllerDelegate":{"role":"symbol","title":"MyPostsViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyPostsViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyPostsViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MyPostsViewControllerDelegate"}],"url":"\/documentation\/divar\/mypostsviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderFlowController/presentRecentPosts()":{"role":"symbol","title":"presentRecentPosts()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentRecentPosts"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/presentRecentPosts()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mydivarholderflowcontroller\/presentrecentposts()"},"doc://com.Divar.DivarClient/documentation/Divar/NotesViewControllerDelegate":{"role":"symbol","title":"NotesViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotesViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NotesViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NotesViewControllerDelegate"}],"url":"\/documentation\/divar\/notesviewcontrollerdelegate"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedActionDelegate":{"role":"symbol","title":"WidgetBasedActionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedActionDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedActionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedActionDelegate"}],"url":"\/documentation\/divar\/widgetbasedactiondelegate"},"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderFlowController/initialMyPostsViewController(with:)":{"role":"symbol","title":"initialMyPostsViewController(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialMyPostsViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/initialMyPostsViewController(with:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mydivarholderflowcontroller\/initialmypostsviewcontroller(with:)"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewControllerDelegate":{"role":"symbol","title":"PostArchiveViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostArchiveViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostArchiveViewControllerDelegate"}],"url":"\/documentation\/divar\/postarchiveviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/RateViewControllerDelegate":{"role":"symbol","title":"RateViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RateViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RateViewControllerDelegate"}],"url":"\/documentation\/divar\/rateviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderFlowController/presentNotes()":{"role":"symbol","title":"presentNotes()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentNotes"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/presentNotes()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mydivarholderflowcontroller\/presentnotes()"},"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderFlowController/RecentVisitsViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"RecentVisitsViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/RecentVisitsViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/mydivarholderflowcontroller\/recentvisitsviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/MyDivarActionHandler":{"role":"symbol","title":"MyDivarActionHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyDivarActionHandler"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarActionHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MyDivarActionHandler"}],"url":"\/documentation\/divar\/mydivaractionhandler"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderViewControllerDelegate":{"role":"symbol","title":"MyDivarHolderViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyDivarHolderViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MyDivarHolderViewControllerDelegate"}],"url":"\/documentation\/divar\/mydivarholderviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/CategoryHierarchyControllerDelegate":{"role":"symbol","title":"CategoryHierarchyControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CategoryHierarchyControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CategoryHierarchyControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CategoryHierarchyControllerDelegate"}],"url":"\/documentation\/divar\/categoryhierarchycontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController":{"role":"symbol","title":"BaseFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseFlowController"}],"url":"\/documentation\/divar\/baseflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderFlowController/initialViewController()":{"role":"symbol","title":"initialViewController()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialViewController"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderFlowController\/initialViewController()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/mydivarholderflowcontroller\/initialviewcontroller()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MyDivarHolderFlowController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MyDivarHolderFlowController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MyDivarHolderFlowController"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyDivarHolderFlowController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","preciseIdentifier":"c:@M@Divar@objc(cs)BaseFlowController","text":"BaseFlowController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MyDivarHolderFlowController\/title","value":"MyDivarHolderFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MyDivarHolderFlowController\/fragments","value":[{"kind":"identifier","text":"MyDivarHolderFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/title","value":"BaseFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/fragments","value":[{"kind":"identifier","text":"BaseFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}