{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NationalIdVerificationFlowController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/nationalidverificationflowcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/nationalidverificationflowcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CategoryHierarchyControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CityMultiSelectViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LoginRequiredProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberInputViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchFilterViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedActionDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NationalIdVerificationFlowController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NationalIdVerificationFlowController\/init(container:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NationalIdVerificationFlowController\/delegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NationalIdVerificationFlowController\/handler"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NationalIdVerificationFlowController\/dismiss(animated:completion:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NationalIdVerificationFlowController\/initial(with:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NationalIdVerificationFlowController\/initialViewController()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NationalIdVerificationFlowController\/NumberInputViewControllerDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NationalIdVerificationFlowController"}],"title":"NationalIdVerificationFlowController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)NationalIdVerificationFlowController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"NationalIdVerificationFlowController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/LoginRequiredProtocol":{"role":"symbol","title":"LoginRequiredProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoginRequiredProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LoginRequiredProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LoginRequiredProtocol"}],"url":"\/documentation\/divar\/loginrequiredprotocol"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFlowController":{"role":"symbol","title":"BaseFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseFlowController"}],"url":"\/documentation\/divar\/baseflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedActionDelegate":{"role":"symbol","title":"WidgetBasedActionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedActionDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedActionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedActionDelegate"}],"url":"\/documentation\/divar\/widgetbasedactiondelegate"},"doc://com.Divar.DivarClient/documentation/Divar/LandlineVerificationFlowControllerDelegate":{"role":"symbol","title":"LandlineVerificationFlowControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandlineVerificationFlowControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandlineVerificationFlowControllerDelegate"}],"url":"\/documentation\/divar\/landlineverificationflowcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/NationalIdVerificationFlowController":{"role":"symbol","title":"NationalIdVerificationFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NationalIdVerificationFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NationalIdVerificationFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NationalIdVerificationFlowController"}],"url":"\/documentation\/divar\/nationalidverificationflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/RateViewControllerDelegate":{"role":"symbol","title":"RateViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RateViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RateViewControllerDelegate"}],"url":"\/documentation\/divar\/rateviewcontrollerdelegate"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/NationalIdVerificationFlowController/NumberInputViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"NumberInputViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NationalIdVerificationFlowController\/NumberInputViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/nationalidverificationflowcontroller\/numberinputviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/NationalIdVerificationFlowController/init(container:)":{"role":"symbol","title":"init(container:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseFlowDIContainer","preciseIdentifier":"s:5Divar19BaseFlowDIContainera"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NationalIdVerificationFlowController\/init(container:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/nationalidverificationflowcontroller\/init(container:)"},"doc://com.Divar.DivarClient/documentation/Divar/NationalIdVerificationFlowController/dismiss(animated:completion:)":{"role":"symbol","title":"dismiss(animated:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismiss"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NationalIdVerificationFlowController\/dismiss(animated:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/nationalidverificationflowcontroller\/dismiss(animated:completion:)"},"doc://com.Divar.DivarClient/documentation/Divar/NationalIdVerificationFlowController/handler":{"role":"symbol","title":"handler","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"handler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NumberInputProtocol","preciseIdentifier":"s:5Divar19NumberInputProtocolP"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NationalIdVerificationFlowController\/handler","kind":"symbol","type":"topic","url":"\/documentation\/divar\/nationalidverificationflowcontroller\/handler"},"doc://com.Divar.DivarClient/documentation/Divar/NationalIdVerificationFlowController/initial(with:)":{"role":"symbol","title":"initial(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initial"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NationalIdVerificationFlowController\/initial(with:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/nationalidverificationflowcontroller\/initial(with:)"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewControllerDelegate":{"role":"symbol","title":"PostArchiveViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostArchiveViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostArchiveViewControllerDelegate"}],"url":"\/documentation\/divar\/postarchiveviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/NationalIdVerificationFlowController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NationalIdVerificationFlowControllerDelegate","preciseIdentifier":"s:5Divar44NationalIdVerificationFlowControllerDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NationalIdVerificationFlowController\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/nationalidverificationflowcontroller\/delegate"},"doc://com.Divar.DivarClient/documentation/Divar/PostCreateViewControllerDelegate":{"role":"symbol","title":"PostCreateViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostCreateViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostCreateViewControllerDelegate"}],"url":"\/documentation\/divar\/postcreateviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/CategoryHierarchyControllerDelegate":{"role":"symbol","title":"CategoryHierarchyControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CategoryHierarchyControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CategoryHierarchyControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CategoryHierarchyControllerDelegate"}],"url":"\/documentation\/divar\/categoryhierarchycontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/NumberInputViewControllerDelegate":{"role":"symbol","title":"NumberInputViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NumberInputViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberInputViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NumberInputViewControllerDelegate"}],"url":"\/documentation\/divar\/numberinputviewcontrollerdelegate"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/CityMultiSelectViewControllerDelegate":{"role":"symbol","title":"CityMultiSelectViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CityMultiSelectViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CityMultiSelectViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CityMultiSelectViewControllerDelegate"}],"url":"\/documentation\/divar\/citymultiselectviewcontrollerdelegate"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/SearchFilterViewControllerDelegate":{"role":"symbol","title":"SearchFilterViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchFilterViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchFilterViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchFilterViewControllerDelegate"}],"url":"\/documentation\/divar\/searchfilterviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/NationalIdVerificationFlowController/initialViewController()":{"role":"symbol","title":"initialViewController()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialViewController"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NationalIdVerificationFlowController\/initialViewController()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/nationalidverificationflowcontroller\/initialviewcontroller()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"NationalIdVerificationFlowController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"NationalIdVerificationFlowController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"NationalIdVerificationFlowController"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"NationalIdVerificationFlowController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFlowController","preciseIdentifier":"c:@M@Divar@objc(cs)BaseFlowController","text":"BaseFlowController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/title","value":"BaseFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFlowController\/fragments","value":[{"kind":"identifier","text":"BaseFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NationalIdVerificationFlowController\/title","value":"NationalIdVerificationFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NationalIdVerificationFlowController\/fragments","value":[{"kind":"identifier","text":"NationalIdVerificationFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}