{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NumberInputViewControllerDelegate"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/numberinputviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NationalIdVerificationFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShahkarLandlineVerificationFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UserRegisterFlowController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberInputViewControllerDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberInputViewControllerDelegate\/numberEnteredSuccessfully(_:with:needsVerify:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NumberInputViewControllerDelegate"}],"title":"NumberInputViewControllerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar33NumberInputViewControllerDelegateP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"NumberInputViewControllerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/NumberInputViewControllerDelegate":{"role":"symbol","title":"NumberInputViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NumberInputViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberInputViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NumberInputViewControllerDelegate"}],"url":"\/documentation\/divar\/numberinputviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/LandlineVerificationFlowController":{"role":"symbol","title":"LandlineVerificationFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandlineVerificationFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandlineVerificationFlowController"}],"url":"\/documentation\/divar\/landlineverificationflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/UserRegisterFlowController":{"role":"symbol","title":"UserRegisterFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserRegisterFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UserRegisterFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserRegisterFlowController"}],"url":"\/documentation\/divar\/userregisterflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/NationalIdVerificationFlowController":{"role":"symbol","title":"NationalIdVerificationFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NationalIdVerificationFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NationalIdVerificationFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NationalIdVerificationFlowController"}],"url":"\/documentation\/divar\/nationalidverificationflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/NumberInputViewControllerDelegate/numberEnteredSuccessfully(_:with:needsVerify:)":{"role":"symbol","title":"numberEnteredSuccessfully(_:with:needsVerify:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberEnteredSuccessfully"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NumberInputViewController","preciseIdentifier":"c:@M@Divar@objc(cs)NumberInputViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"needsVerify"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberInputViewControllerDelegate\/numberEnteredSuccessfully(_:with:needsVerify:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/numberinputviewcontrollerdelegate\/numberenteredsuccessfully(_:with:needsverify:)"},"doc://com.Divar.DivarClient/documentation/Divar/ShahkarLandlineVerificationFlowController":{"role":"symbol","title":"ShahkarLandlineVerificationFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShahkarLandlineVerificationFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShahkarLandlineVerificationFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShahkarLandlineVerificationFlowController"}],"url":"\/documentation\/divar\/shahkarlandlineverificationflowcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandlineVerificationFlowController\/title","value":"LandlineVerificationFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandlineVerificationFlowController\/fragments","value":[{"kind":"identifier","text":"LandlineVerificationFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1UserRegisterFlowController\/title","value":"UserRegisterFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1UserRegisterFlowController\/fragments","value":[{"kind":"identifier","text":"UserRegisterFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NationalIdVerificationFlowController\/title","value":"NationalIdVerificationFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NationalIdVerificationFlowController\/fragments","value":[{"kind":"identifier","text":"NationalIdVerificationFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ShahkarLandlineVerificationFlowController\/title","value":"ShahkarLandlineVerificationFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ShahkarLandlineVerificationFlowController\/fragments","value":[{"kind":"identifier","text":"ShahkarLandlineVerificationFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}