{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresentable"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/panmodalpresentable"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AlertViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetEurekaViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedBottomSheetViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/allowsDragToDismiss-68ufa","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/allowsExtendedPanScrolling-82iir","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/allowsTapToDismiss-72zai","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/anchorModalToLongForm-1gm59","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/banner-7394","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/bottomLayoutOffset","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/bottomYPos","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/cornerRadius-ejcm","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/hasBanner","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/isHapticFeedbackEnabled-62hgc","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/isUserInteractionEnabled-9kmvx","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/longFormHeight-7ftwp","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/longFormYPos","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/panModalBackgroundColor-m5ub","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/panScrollable","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/presentedVC","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/scrollIndicatorInsets-6nhbf","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/shortFormHeight-8jyj","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/shortFormYPos","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/shouldRoundTopCorners-31n83","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/showDragIndicator-39y43","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/springDamping-97rm6","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/topLayoutOffset","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/topOffset-7ltll","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/transitionAnimationOptions-43fsa","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/transitionDuration-4s7uk"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/panModalAnimate(_:_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/panModalDidDismiss()-75255","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/panModalPerformUpdates(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/panModalSetNeedsLayoutUpdate()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/panModalTransition(to:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/panModalWillDismiss()-8zrm7","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/shouldPrioritize(panModalGestureRecognizer:)-15bkk","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/shouldRespond(to:)-74baa","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/shouldTransition(to:)-72n1n","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/topMargin(from:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/willRespond(to:)-4i11m","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/willTransition(to:)-5ip8n"]},{"title":"Type Aliases","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/AnimationBlockType","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/AnimationCompletionType","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/LayoutType"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresentable"}],"title":"PanModalPresentable","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar19PanModalPresentableP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"PanModalPresentable"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/presentedVC":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" inherits "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"presentedVC","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentedVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PanModalPresentationController","preciseIdentifier":"c:@M@Divar@objc(cs)PanModalPresentationController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/presentedVC","kind":"symbol","type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/presentedvc"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable":{"role":"symbol","title":"PanModalPresentable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresentable"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresentable"}],"url":"\/documentation\/divar\/panmodalpresentable"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/shortFormYPos":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" inherits "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"shortFormYPos","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shortFormYPos"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/shortFormYPos","kind":"symbol","type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/shortformypos"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/showDragIndicator-39y43":{"defaultImplementations":1,"role":"symbol","title":"showDragIndicator","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showDragIndicator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/showDragIndicator-39y43","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/showdragindicator-39y43"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/shouldRespond(to:)-74baa":{"defaultImplementations":1,"role":"symbol","title":"shouldRespond(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldRespond"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPanGestureRecognizer","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/shouldRespond(to:)-74baa","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/shouldrespond(to:)-74baa"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/allowsDragToDismiss-68ufa":{"defaultImplementations":1,"role":"symbol","title":"allowsDragToDismiss","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsDragToDismiss"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/allowsDragToDismiss-68ufa","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/allowsdragtodismiss-68ufa"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/panModalDidDismiss()-75255":{"defaultImplementations":1,"role":"symbol","title":"panModalDidDismiss()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"panModalDidDismiss"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/panModalDidDismiss()-75255","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/panmodaldiddismiss()-75255"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/transitionDuration-4s7uk":{"defaultImplementations":1,"role":"symbol","title":"transitionDuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitionDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/transitionDuration-4s7uk","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/transitionduration-4s7uk"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/willTransition(to:)-5ip8n":{"defaultImplementations":1,"role":"symbol","title":"willTransition(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PanModalPresentationController","preciseIdentifier":"c:@M@Divar@objc(cs)PanModalPresentationController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"PresentationState","preciseIdentifier":"s:5Divar30PanModalPresentationControllerC0D5StateO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/willTransition(to:)-5ip8n","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/willtransition(to:)-5ip8n"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/isHapticFeedbackEnabled-62hgc":{"defaultImplementations":1,"role":"symbol","title":"isHapticFeedbackEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHapticFeedbackEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/isHapticFeedbackEnabled-62hgc","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/ishapticfeedbackenabled-62hgc"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetEurekaViewController":{"role":"symbol","title":"BottomSheetEurekaViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BottomSheetEurekaViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetEurekaViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BottomSheetEurekaViewController"}],"url":"\/documentation\/divar\/bottomsheeteurekaviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/AnimationCompletionType":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" inherits "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"PanModalPresentable.AnimationCompletionType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimationCompletionType"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/AnimationCompletionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnimationCompletionType"}],"url":"\/documentation\/divar\/panmodalpresentable\/animationcompletiontype"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/springDamping-97rm6":{"defaultImplementations":1,"role":"symbol","title":"springDamping","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"springDamping"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/springDamping-97rm6","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/springdamping-97rm6"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/shouldTransition(to:)-72n1n":{"defaultImplementations":1,"role":"symbol","title":"shouldTransition(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PanModalPresentationController","preciseIdentifier":"c:@M@Divar@objc(cs)PanModalPresentationController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"PresentationState","preciseIdentifier":"s:5Divar30PanModalPresentationControllerC0D5StateO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/shouldTransition(to:)-72n1n","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/shouldtransition(to:)-72n1n"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/topOffset-7ltll":{"defaultImplementations":1,"role":"symbol","title":"topOffset","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/topOffset-7ltll","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/topoffset-7ltll"},"doc://com.Divar.DivarClient/documentation/Divar/FeedbackAlertViewController":{"role":"symbol","title":"FeedbackAlertViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeedbackAlertViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeedbackAlertViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeedbackAlertViewController"}],"url":"\/documentation\/divar\/feedbackalertviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetViewController":{"role":"symbol","title":"BottomSheetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BottomSheetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BottomSheetViewController"}],"url":"\/documentation\/divar\/bottomsheetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/panModalWillDismiss()-8zrm7":{"defaultImplementations":1,"role":"symbol","title":"panModalWillDismiss()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"panModalWillDismiss"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/panModalWillDismiss()-8zrm7","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/panmodalwilldismiss()-8zrm7"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/cornerRadius-ejcm":{"defaultImplementations":1,"role":"symbol","title":"cornerRadius","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/cornerRadius-ejcm","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/cornerradius-ejcm"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/hasBanner":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" inherits "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"hasBanner","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasBanner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/hasBanner","kind":"symbol","type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/hasbanner"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/longFormHeight-7ftwp":{"defaultImplementations":1,"role":"symbol","title":"longFormHeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"longFormHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PanModalHeight","preciseIdentifier":"s:5Divar14PanModalHeightO"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/longFormHeight-7ftwp","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/longformheight-7ftwp"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/shouldRoundTopCorners-31n83":{"defaultImplementations":1,"role":"symbol","title":"shouldRoundTopCorners","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldRoundTopCorners"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/shouldRoundTopCorners-31n83","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/shouldroundtopcorners-31n83"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/anchorModalToLongForm-1gm59":{"defaultImplementations":1,"role":"symbol","title":"anchorModalToLongForm","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorModalToLongForm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/anchorModalToLongForm-1gm59","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/anchormodaltolongform-1gm59"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/shortFormHeight-8jyj":{"defaultImplementations":1,"role":"symbol","title":"shortFormHeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shortFormHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PanModalHeight","preciseIdentifier":"s:5Divar14PanModalHeightO"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/shortFormHeight-8jyj","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/shortformheight-8jyj"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/shouldPrioritize(panModalGestureRecognizer:)-15bkk":{"defaultImplementations":1,"role":"symbol","title":"shouldPrioritize(panModalGestureRecognizer:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldPrioritize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"panModalGestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPanGestureRecognizer","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/shouldPrioritize(panModalGestureRecognizer:)-15bkk","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/shouldprioritize(panmodalgesturerecognizer:)-15bkk"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/panModalBackgroundColor-m5ub":{"defaultImplementations":1,"role":"symbol","title":"panModalBackgroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"panModalBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/panModalBackgroundColor-m5ub","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/panmodalbackgroundcolor-m5ub"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/topMargin(from:)":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" inherits "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"topMargin(from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"topMargin"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PanModalHeight","preciseIdentifier":"s:5Divar14PanModalHeightO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/topMargin(from:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/topmargin(from:)"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/panModalAnimate(_:_:)":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" inherits "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"panModalAnimate(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"panModalAnimate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AnimationBlockType","preciseIdentifier":"s:5Divar19PanModalPresentablePAASo16UIViewControllerCRbzrlE18AnimationBlockTypea"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"AnimationCompletionType","preciseIdentifier":"s:5Divar19PanModalPresentablePAASo16UIViewControllerCRbzrlE23AnimationCompletionTypea"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/panModalAnimate(_:_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/panmodalanimate(_:_:)"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/isUserInteractionEnabled-9kmvx":{"defaultImplementations":1,"role":"symbol","title":"isUserInteractionEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isUserInteractionEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/isUserInteractionEnabled-9kmvx","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/isuserinteractionenabled-9kmvx"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/LayoutType":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" inherits "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"PanModalPresentable.LayoutType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"LayoutType"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/LayoutType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LayoutType"}],"url":"\/documentation\/divar\/panmodalpresentable\/layouttype"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/scrollIndicatorInsets-6nhbf":{"defaultImplementations":1,"role":"symbol","title":"scrollIndicatorInsets","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollIndicatorInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/scrollIndicatorInsets-6nhbf","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/scrollindicatorinsets-6nhbf"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/panModalSetNeedsLayoutUpdate()":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" inherits "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"panModalSetNeedsLayoutUpdate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"panModalSetNeedsLayoutUpdate"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/panModalSetNeedsLayoutUpdate()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/panmodalsetneedslayoutupdate()"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/banner-7394":{"defaultImplementations":1,"role":"symbol","title":"banner","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"banner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PanModalBannerCompatible","preciseIdentifier":"s:5Divar24PanModalBannerCompatibleP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/banner-7394","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/banner-7394"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/allowsTapToDismiss-72zai":{"defaultImplementations":1,"role":"symbol","title":"allowsTapToDismiss","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsTapToDismiss"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/allowsTapToDismiss-72zai","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/allowstaptodismiss-72zai"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/topLayoutOffset":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" inherits "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"topLayoutOffset","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topLayoutOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/topLayoutOffset","kind":"symbol","type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/toplayoutoffset"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedBottomSheetViewController":{"role":"symbol","title":"WidgetBasedBottomSheetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedBottomSheetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedBottomSheetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedBottomSheetViewController"}],"url":"\/documentation\/divar\/widgetbasedbottomsheetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/allowsExtendedPanScrolling-82iir":{"defaultImplementations":1,"role":"symbol","title":"allowsExtendedPanScrolling","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsExtendedPanScrolling"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/allowsExtendedPanScrolling-82iir","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/allowsextendedpanscrolling-82iir"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/bottomLayoutOffset":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" inherits "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"bottomLayoutOffset","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomLayoutOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/bottomLayoutOffset","kind":"symbol","type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/bottomlayoutoffset"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/transitionAnimationOptions-43fsa":{"defaultImplementations":1,"role":"symbol","title":"transitionAnimationOptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitionAnimationOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"AnimationOptions","preciseIdentifier":"c:@E@UIViewAnimationOptions"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/transitionAnimationOptions-43fsa","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/transitionanimationoptions-43fsa"},"doc://com.Divar.DivarClient/documentation/Divar/AlertViewController":{"role":"symbol","title":"AlertViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlertViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AlertViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AlertViewController"}],"url":"\/documentation\/divar\/alertviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/AnimationBlockType":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" inherits "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"PanModalPresentable.AnimationBlockType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimationBlockType"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/AnimationBlockType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnimationBlockType"}],"url":"\/documentation\/divar\/panmodalpresentable\/animationblocktype"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/panModalTransition(to:)":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" inherits "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"panModalTransition(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"panModalTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PanModalPresentationController","preciseIdentifier":"c:@M@Divar@objc(cs)PanModalPresentationController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"PresentationState","preciseIdentifier":"s:5Divar30PanModalPresentationControllerC0D5StateO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/panModalTransition(to:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/panmodaltransition(to:)"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/panModalPerformUpdates(_:)":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" inherits "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"panModalPerformUpdates(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"panModalPerformUpdates"},{"kind":"text","text":"(() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/panModalPerformUpdates(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/panmodalperformupdates(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/longFormYPos":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" inherits "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"longFormYPos","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"longFormYPos"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/longFormYPos","kind":"symbol","type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/longformypos"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/panScrollable":{"role":"symbol","title":"panScrollable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"panScrollable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/panScrollable","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/panscrollable"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/bottomYPos":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" inherits "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"bottomYPos","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomYPos"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/bottomYPos","kind":"symbol","type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/bottomypos"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentable/willRespond(to:)-4i11m":{"defaultImplementations":1,"role":"symbol","title":"willRespond(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willRespond"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPanGestureRecognizer","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentable\/willRespond(to:)-4i11m","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/panmodalpresentable\/willrespond(to:)-4i11m"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetEurekaViewController\/title","value":"BottomSheetEurekaViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetEurekaViewController\/fragments","value":[{"kind":"identifier","text":"BottomSheetEurekaViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController\/title","value":"FeedbackAlertViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeedbackAlertViewController\/fragments","value":[{"kind":"identifier","text":"FeedbackAlertViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetViewController\/title","value":"BottomSheetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetViewController\/fragments","value":[{"kind":"identifier","text":"BottomSheetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedBottomSheetViewController\/title","value":"WidgetBasedBottomSheetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedBottomSheetViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedBottomSheetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AlertViewController\/title","value":"AlertViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AlertViewController\/fragments","value":[{"kind":"identifier","text":"AlertViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}