{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresentationController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/panmodalpresentationcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/panmodalpresentationcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIPresentationController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController","interfaceLanguage":"swift"},"topicSections":[{"title":"Structures","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/Constants"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/presentedView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/containerViewWillLayoutSubviews()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/dismissalTransitionWillBegin()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/performUpdates(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/presentationTransitionDidEnd(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/presentationTransitionWillBegin()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/setNeedsLayoutUpdate()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/transition(to:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/viewWillTransition(to:with:)"]},{"title":"Enumerations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/PresentationState"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/UIGestureRecognizerDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresentationController"}],"title":"PanModalPresentationController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)PanModalPresentationController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"PanModalPresentationController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/objc(pl)UIGestureRecognizerDelegate":{"type":"unresolvable","title":"UIKit.UIGestureRecognizerDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIGestureRecognizerDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationController/transition(to:)":{"role":"symbol","title":"transition(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PresentationState","preciseIdentifier":"s:5Divar30PanModalPresentationControllerC0D5StateO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/transition(to:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/panmodalpresentationcontroller\/transition(to:)"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationController/Constants":{"role":"symbol","title":"PanModalPresentationController.Constants","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Constants"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/Constants","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Constants"}],"url":"\/documentation\/divar\/panmodalpresentationcontroller\/constants"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationController/presentedView":{"role":"symbol","title":"presentedView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentedView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/presentedView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentedView"}],"url":"\/documentation\/divar\/panmodalpresentationcontroller\/presentedview"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationController/initWithPresentedViewController:presentingViewController:":{"role":"symbol","title":"initWithPresentedViewController:presentingViewController:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPresentedViewController:presentingViewController:"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/initWithPresentedViewController:presentingViewController:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithPresentedViewController:presentingViewController:"}],"url":"\/documentation\/divar\/panmodalpresentationcontroller\/initwithpresentedviewcontroller:presentingviewcontroller:"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationController":{"role":"symbol","title":"PanModalPresentationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresentationController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresentationController"}],"url":"\/documentation\/divar\/panmodalpresentationcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationController/UIGestureRecognizerDelegate-Implementations":{"role":"collectionGroup","title":"UIGestureRecognizerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/UIGestureRecognizerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/panmodalpresentationcontroller\/uigesturerecognizerdelegate-implementations"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationController/PresentationState":{"role":"symbol","title":"PanModalPresentationController.PresentationState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationState"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/PresentationState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PresentationState"}],"url":"\/documentation\/divar\/panmodalpresentationcontroller\/presentationstate"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationController/containerViewWillLayoutSubviews()":{"role":"symbol","title":"containerViewWillLayoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"containerViewWillLayoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/containerViewWillLayoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"containerViewWillLayoutSubviews"}],"url":"\/documentation\/divar\/panmodalpresentationcontroller\/containerviewwilllayoutsubviews()"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationController/presentationTransitionDidEnd(_:)":{"role":"symbol","title":"presentationTransitionDidEnd(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationTransitionDidEnd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/presentationTransitionDidEnd(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentationTransitionDidEnd:"}],"url":"\/documentation\/divar\/panmodalpresentationcontroller\/presentationtransitiondidend(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationController/setNeedsLayoutUpdate()":{"role":"symbol","title":"setNeedsLayoutUpdate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setNeedsLayoutUpdate"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/setNeedsLayoutUpdate()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/panmodalpresentationcontroller\/setneedslayoutupdate()"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationController/dismissalTransitionWillBegin()":{"role":"symbol","title":"dismissalTransitionWillBegin()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissalTransitionWillBegin"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/dismissalTransitionWillBegin()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dismissalTransitionWillBegin"}],"url":"\/documentation\/divar\/panmodalpresentationcontroller\/dismissaltransitionwillbegin()"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationController/presentationTransitionWillBegin()":{"role":"symbol","title":"presentationTransitionWillBegin()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationTransitionWillBegin"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/presentationTransitionWillBegin()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentationTransitionWillBegin"}],"url":"\/documentation\/divar\/panmodalpresentationcontroller\/presentationtransitionwillbegin()"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationController/performUpdates(_:)":{"role":"symbol","title":"performUpdates(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"performUpdates"},{"kind":"text","text":"(() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/performUpdates(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/panmodalpresentationcontroller\/performupdates(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationController/viewWillTransition(to:with:)":{"role":"symbol","title":"viewWillTransition(to:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewControllerTransitionCoordinator","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Update presented view size in response to size class changes"}],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/viewWillTransition(to:with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillTransitionToSize:withTransitionCoordinator:"}],"url":"\/documentation\/divar\/panmodalpresentationcontroller\/viewwilltransition(to:with:)"},"doc://com.Divar.DivarClient/objc(cs)UIPresentationController":{"type":"unresolvable","title":"UIPresentationController","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)UIPresentationController"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PanModalPresentationController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PanModalPresentationController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PanModalPresentationController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/presentedView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/containerViewWillLayoutSubviews()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/dismissalTransitionWillBegin()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/initWithPresentedViewController:presentingViewController:","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/presentationTransitionDidEnd(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/presentationTransitionWillBegin()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/viewWillTransition(to:with:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationController\/UIGestureRecognizerDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIPresentationController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresentationController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationController~1presentedView\/title","value":"presentedView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationController~1presentedView\/fragments","value":[{"kind":"identifier","text":"presentedView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationController\/title","value":"PanModalPresentationController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationController\/fragments","value":[{"kind":"identifier","text":"PanModalPresentationController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationController~1containerViewWillLayoutSubviews()\/title","value":"containerViewWillLayoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationController~1containerViewWillLayoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"containerViewWillLayoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationController~1presentationTransitionDidEnd(_:)\/title","value":"presentationTransitionDidEnd:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationController~1presentationTransitionDidEnd(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentationTransitionDidEnd:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationController~1dismissalTransitionWillBegin()\/title","value":"dismissalTransitionWillBegin"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationController~1dismissalTransitionWillBegin()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismissalTransitionWillBegin"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationController~1presentationTransitionWillBegin()\/title","value":"presentationTransitionWillBegin"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationController~1presentationTransitionWillBegin()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentationTransitionWillBegin"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationController~1viewWillTransition(to:with:)\/title","value":"viewWillTransitionToSize:withTransitionCoordinator:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationController~1viewWillTransition(to:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillTransitionToSize:withTransitionCoordinator:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}