{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersianNumberFormatter"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/persiannumberformatter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/persiannumberformatter"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)NSNumberFormatter"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/6Eureka17FormatterProtocolP","doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSCopying","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PersianNumberFormatter","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PersianNumberFormatter\/init()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PersianNumberFormatter\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PersianNumberFormatter\/init(valueHolder:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PersianNumberFormatter\/getNewPosition(forPosition:inTextInput:oldValue:newValue:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PersianNumberFormatter\/getObjectValue(_:for:errorDescription:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersianNumberFormatter"}],"title":"PersianNumberFormatter","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)PersianNumberFormatter","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"PersianNumberFormatter"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/objc(cs)NSNumberFormatter":{"type":"unresolvable","title":"NSNumberFormatter","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)NSNumberFormatter"},"doc://com.Divar.DivarClient/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCopying"},"doc://com.Divar.DivarClient/documentation/Divar/PersianNumberFormatter/getObjectValue(_:for:errorDescription:)":{"role":"symbol","title":"getObjectValue(_:for:errorDescription:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getObjectValue"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"AnyObject","preciseIdentifier":"s:s9AnyObjecta"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":"?>?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PersianNumberFormatter\/getObjectValue(_:for:errorDescription:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getObjectValue:forString:errorDescription:"}],"url":"\/documentation\/divar\/persiannumberformatter\/getobjectvalue(_:for:errordescription:)"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/PersianNumberFormatter":{"role":"symbol","title":"PersianNumberFormatter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersianNumberFormatter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PersianNumberFormatter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PersianNumberFormatter"}],"url":"\/documentation\/divar\/persiannumberformatter"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/PersianNumberFormatter/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PersianNumberFormatter\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/divar\/persiannumberformatter\/init()"},"doc://com.Divar.DivarClient/documentation/Divar/PersianNumberFormatter/init(valueHolder:)":{"role":"symbol","title":"init(valueHolder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"valueHolder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PersianNumberFormatter\/init(valueHolder:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/persiannumberformatter\/init(valueholder:)"},"doc://com.Divar.DivarClient/6Eureka17FormatterProtocolP":{"type":"unresolvable","title":"Eureka.FormatterProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/6Eureka17FormatterProtocolP"},"doc://com.Divar.DivarClient/documentation/Divar/PersianNumberFormatter/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PersianNumberFormatter\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/persiannumberformatter\/init(coder:)"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/PersianNumberFormatter/getNewPosition(forPosition:inTextInput:oldValue:newValue:)":{"role":"symbol","title":"getNewPosition(forPosition:inTextInput:oldValue:newValue:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getNewPosition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextPosition","preciseIdentifier":"c:objc(cs)UITextPosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inTextInput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextInput","preciseIdentifier":"c:objc(pl)UITextInput"},{"kind":"text","text":", "},{"kind":"externalParam","text":"oldValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"newValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UITextPosition","preciseIdentifier":"c:objc(cs)UITextPosition"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PersianNumberFormatter\/getNewPosition(forPosition:inTextInput:oldValue:newValue:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/persiannumberformatter\/getnewposition(forposition:intextinput:oldvalue:newvalue:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PersianNumberFormatter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PersianNumberFormatter"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PersianNumberFormatter"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PersianNumberFormatter\/getObjectValue(_:for:errorDescription:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PersianNumberFormatter\/init()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PersianNumberFormatter\/init(coder:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)NSNumberFormatter"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersianNumberFormatter"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSNumberFormatter","preciseIdentifier":"c:objc(cs)NSNumberFormatter"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PersianNumberFormatter~1getObjectValue(_:for:errorDescription:)\/title","value":"getObjectValue:forString:errorDescription:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PersianNumberFormatter~1getObjectValue(_:for:errorDescription:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getObjectValue:forString:errorDescription:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PersianNumberFormatter\/title","value":"PersianNumberFormatter"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PersianNumberFormatter\/fragments","value":[{"kind":"identifier","text":"PersianNumberFormatter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PersianNumberFormatter~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PersianNumberFormatter~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PersianNumberFormatter~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PersianNumberFormatter~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}