{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostArchiveViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/postarchiveviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/postarchiveviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostReportDescriptionViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleMultiBaseViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UserRegisterFlowControllerDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/init(container:cancelPayload:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/init(container:post:type:slug:offlineData:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/bottomConstraint","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/buttonBar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/carInspectionDescription","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/carInspectionTitle","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/delegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/headerVC","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/manageToken","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/multiSelectItem","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/offlineData","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/postTitle","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/reasonsVC","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/selectedItem","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/slug","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/stackView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/token","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/type"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/creatSMView(with:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/dismiss(animated:completion:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/getButtonTitle()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/getConfig()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/getDescString()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/getHeaderString()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/handleActionAfterLogin()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/loadData()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/logArchive(questionTag:answer:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/sendArchiveReason(_:questionTag:answer:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/setDelegate(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/setPageTitle()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/viewDidLoad()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/willMove(toParent:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/PostReportDescriptionViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/SingleMultiBaseViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/TwinButtonsViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/UserRegisterFlowControllerDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostArchiveViewController"}],"title":"PostArchiveViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)PostArchiveViewController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"PostArchiveViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/postarchiveviewcontroller\/init(coder:)"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/PostReportDescriptionViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"PostReportDescriptionViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/PostReportDescriptionViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/postreportdescriptionviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController":{"role":"symbol","title":"PostArchiveViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostArchiveViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostArchiveViewController"}],"url":"\/documentation\/divar\/postarchiveviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/selectedItem":{"role":"symbol","title":"selectedItem","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SingleMultiModel","preciseIdentifier":"s:5Divar16SingleMultiModelV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/selectedItem","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/selecteditem"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostArchiveViewControllerDelegate","preciseIdentifier":"s:5Divar33PostArchiveViewControllerDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/delegate"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/stackView":{"role":"symbol","title":"stackView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/stackView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stackView"}],"url":"\/documentation\/divar\/postarchiveviewcontroller\/stackview"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/reasonsVC":{"role":"symbol","title":"reasonsVC","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reasonsVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SingleMultiBaseViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SingleMultiBaseViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/reasonsVC","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/reasonsvc"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/TwinButtonsViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"TwinButtonsViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/TwinButtonsViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/twinbuttonsviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController":{"role":"symbol","title":"BaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseViewController"}],"url":"\/documentation\/divar\/baseviewcontroller"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/dismiss(animated:completion:)":{"role":"symbol","title":"dismiss(animated:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismiss"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/dismiss(animated:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dismissViewControllerAnimated:completion:"}],"url":"\/documentation\/divar\/postarchiveviewcontroller\/dismiss(animated:completion:)"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/getButtonTitle()":{"role":"symbol","title":"getButtonTitle()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getButtonTitle"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/getButtonTitle()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/getbuttontitle()"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/init(container:post:type:slug:offlineData:)":{"role":"symbol","title":"init(container:post:type:slug:offlineData:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostArchiveViewControllerDIContainer","preciseIdentifier":"s:5Divar36PostArchiveViewControllerDIContainera"},{"kind":"text","text":", "},{"kind":"externalParam","text":"post"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostViewStructure","preciseIdentifier":"s:5Divar17PostViewStructureV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ReportingType","preciseIdentifier":"s:5Divar13ReportingTypeO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"slug"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"offlineData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SingleMultiModel","preciseIdentifier":"s:5Divar16SingleMultiModelV"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/init(container:post:type:slug:offlineData:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/init(container:post:type:slug:offlinedata:)"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/PaymentSystemProtocol":{"role":"symbol","title":"PaymentSystemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSystemProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaymentSystemProtocol"}],"url":"\/documentation\/divar\/paymentsystemprotocol"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/buttonBar":{"role":"symbol","title":"buttonBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TwinButtonsViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TwinButtonsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/buttonBar","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/buttonbar"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/sendArchiveReason(_:questionTag:answer:)":{"role":"symbol","title":"sendArchiveReason(_:questionTag:answer:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendArchiveReason"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"questionTag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"answer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/sendArchiveReason(_:questionTag:answer:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/sendarchivereason(_:questiontag:answer:)"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/init(container:cancelPayload:)":{"role":"symbol","title":"init(container:cancelPayload:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostArchiveViewControllerDIContainer","preciseIdentifier":"s:5Divar36PostArchiveViewControllerDIContainera"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cancelPayload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_CarInspectionCancellationPayload","preciseIdentifier":"s:19DivarInterfaceSwift40Widgets_CarInspectionCancellationPayloadV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/init(container:cancelPayload:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/init(container:cancelpayload:)"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/logArchive(questionTag:answer:)":{"role":"symbol","title":"logArchive(questionTag:answer:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logArchive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"questionTag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"answer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/logArchive(questionTag:answer:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/logarchive(questiontag:answer:)"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/getConfig()":{"role":"symbol","title":"getConfig()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getConfig"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SingleMultiBaseViewControllerConfig","preciseIdentifier":"s:5Divar35SingleMultiBaseViewControllerConfigP"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/getConfig()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/getconfig()"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/carInspectionTitle":{"role":"symbol","title":"carInspectionTitle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"carInspectionTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/carInspectionTitle","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/carinspectiontitle"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/SingleMultiBaseViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"SingleMultiBaseViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/SingleMultiBaseViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/singlemultibaseviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/postTitle":{"role":"symbol","title":"postTitle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"postTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/postTitle","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/posttitle"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/carInspectionDescription":{"role":"symbol","title":"carInspectionDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"carInspectionDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/carInspectionDescription","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/carinspectiondescription"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/bottomConstraint":{"role":"symbol","title":"bottomConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/bottomConstraint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bottomConstraint"}],"url":"\/documentation\/divar\/postarchiveviewcontroller\/bottomconstraint"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/slug":{"role":"symbol","title":"slug","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"slug"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/slug","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/slug"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/token":{"role":"symbol","title":"token","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/token","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/token"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/manageToken":{"role":"symbol","title":"manageToken","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"manageToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/manageToken","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/managetoken"},"doc://com.Divar.DivarClient/documentation/Divar/SingleMultiBaseViewControllerDelegate":{"role":"symbol","title":"SingleMultiBaseViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleMultiBaseViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleMultiBaseViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SingleMultiBaseViewControllerDelegate"}],"url":"\/documentation\/divar\/singlemultibaseviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/postarchiveviewcontroller\/viewdidload()"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/handleActionAfterLogin()":{"role":"symbol","title":"handleActionAfterLogin()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleActionAfterLogin"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/handleActionAfterLogin()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/handleactionafterlogin()"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/getDescString()":{"role":"symbol","title":"getDescString()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDescString"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/getDescString()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/getdescstring()"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/getHeaderString()":{"role":"symbol","title":"getHeaderString()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getHeaderString"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/getHeaderString()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/getheaderstring()"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/setPageTitle()":{"role":"symbol","title":"setPageTitle()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPageTitle"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/setPageTitle()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/setpagetitle()"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/documentation/Divar/ShowErrorProtocol":{"role":"symbol","title":"ShowErrorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowErrorProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowErrorProtocol"}],"url":"\/documentation\/divar\/showerrorprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/ErrorMessageHandler":{"role":"symbol","title":"ErrorMessageHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorMessageHandler"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorMessageHandler"}],"url":"\/documentation\/divar\/errormessagehandler"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/setDelegate(_:)":{"role":"symbol","title":"setDelegate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PostArchiveViewControllerDelegate","preciseIdentifier":"s:5Divar33PostArchiveViewControllerDelegateP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/setDelegate(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/setdelegate(_:)"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/creatSMView(with:)":{"role":"symbol","title":"creatSMView(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"creatSMView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SingleMultiModel","preciseIdentifier":"s:5Divar16SingleMultiModelV"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/creatSMView(with:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/creatsmview(with:)"},"doc://com.Divar.DivarClient/documentation/Divar/UserRegisterFlowControllerDelegate":{"role":"symbol","title":"UserRegisterFlowControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserRegisterFlowControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UserRegisterFlowControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserRegisterFlowControllerDelegate"}],"url":"\/documentation\/divar\/userregisterflowcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ReportingType","preciseIdentifier":"s:5Divar13ReportingTypeO"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/type","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/type"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/headerVC":{"role":"symbol","title":"headerVC","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HeaderBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)HeaderBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/headerVC","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/headervc"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewControllerDelegate":{"role":"symbol","title":"TwinButtonsViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TwinButtonsViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TwinButtonsViewControllerDelegate"}],"url":"\/documentation\/divar\/twinbuttonsviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/PostReportDescriptionViewControllerDelegate":{"role":"symbol","title":"PostReportDescriptionViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostReportDescriptionViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostReportDescriptionViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostReportDescriptionViewControllerDelegate"}],"url":"\/documentation\/divar\/postreportdescriptionviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/offlineData":{"role":"symbol","title":"offlineData","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"offlineData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SingleMultiModel","preciseIdentifier":"s:5Divar16SingleMultiModelV"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/offlineData","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/offlinedata"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/multiSelectItem":{"role":"symbol","title":"multiSelectItem","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiSelectItem"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SingleMultiModel","preciseIdentifier":"s:5Divar16SingleMultiModelV"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/multiSelectItem","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/multiselectitem"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/loadData()":{"role":"symbol","title":"loadData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadData"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/loadData()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/loaddata()"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/UserRegisterFlowControllerDelegate-Implementations":{"role":"collectionGroup","title":"UserRegisterFlowControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/UserRegisterFlowControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/postarchiveviewcontroller\/userregisterflowcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController/willMove(toParent:)":{"role":"symbol","title":"willMove(toParent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willMove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toParent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/willMove(toParent:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"willMoveToParentViewController:"}],"url":"\/documentation\/divar\/postarchiveviewcontroller\/willmove(toparent:)"},"doc://com.Divar.DivarClient/documentation/Divar/TooltipPresenter":{"role":"symbol","title":"TooltipPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TooltipPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TooltipPresenter"}],"url":"\/documentation\/divar\/tooltippresenter"},"doc://com.Divar.DivarClient/documentation/Divar/ShowMessageProtocol":{"role":"symbol","title":"ShowMessageProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowMessageProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowMessageProtocol"}],"url":"\/documentation\/divar\/showmessageprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PostArchiveViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PostArchiveViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PostArchiveViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/bottomConstraint","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/stackView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/dismiss(animated:completion:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/viewDidLoad()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController\/willMove(toParent:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostArchiveViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController","preciseIdentifier":"c:@M@Divar@objc(cs)BaseViewController","text":"BaseViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController\/title","value":"PostArchiveViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController\/fragments","value":[{"kind":"identifier","text":"PostArchiveViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController~1stackView\/title","value":"stackView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController~1stackView\/fragments","value":[{"kind":"identifier","text":"stackView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController\/title","value":"BaseViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController\/fragments","value":[{"kind":"identifier","text":"BaseViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController~1dismiss(animated:completion:)\/title","value":"dismissViewControllerAnimated:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController~1dismiss(animated:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismissViewControllerAnimated:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController~1bottomConstraint\/title","value":"bottomConstraint"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController~1bottomConstraint\/fragments","value":[{"kind":"identifier","text":"bottomConstraint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController~1willMove(toParent:)\/title","value":"willMoveToParentViewController:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController~1willMove(toParent:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willMoveToParentViewController:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}