{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostChatNavigator"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/postchatnavigator"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostDetailsFlowController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostChatNavigator","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostChatNavigator\/loginRequiredProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostChatNavigator\/postChatNavigatorContainer","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostChatNavigator\/presentingNavigationController"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostChatNavigator\/openPostChat(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostChatNavigator"}],"title":"PostChatNavigator","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar17PostChatNavigatorP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"PostChatNavigator"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PostChatNavigator":{"role":"symbol","title":"PostChatNavigator","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostChatNavigator"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostChatNavigator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostChatNavigator"}],"url":"\/documentation\/divar\/postchatnavigator"},"doc://com.Divar.DivarClient/documentation/Divar/PostChatNavigator/openPostChat(_:)":{"role":"symbol","title":"openPostChat(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openPostChat"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostChatNavigator\/openPostChat(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postchatnavigator\/openpostchat(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/PostChatNavigator/postChatNavigatorContainer":{"role":"symbol","title":"postChatNavigatorContainer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"postChatNavigatorContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostChatNavigatorDIContainer","preciseIdentifier":"s:5Divar28PostChatNavigatorDIContainera"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostChatNavigator\/postChatNavigatorContainer","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/postchatnavigator\/postchatnavigatorcontainer"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PostChatNavigator/presentingNavigationController":{"role":"symbol","title":"presentingNavigationController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentingNavigationController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostChatNavigator\/presentingNavigationController","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/postchatnavigator\/presentingnavigationcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostChatNavigator/loginRequiredProtocol":{"role":"symbol","title":"loginRequiredProtocol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"loginRequiredProtocol"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LoginRequiredProtocol","preciseIdentifier":"s:5Divar21LoginRequiredProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostChatNavigator\/loginRequiredProtocol","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/postchatnavigator\/loginrequiredprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/MainFlowController":{"role":"symbol","title":"MainFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MainFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MainFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MainFlowController"}],"url":"\/documentation\/divar\/mainflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostDetailsFlowController":{"role":"symbol","title":"PostDetailsFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostDetailsFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostDetailsFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostDetailsFlowController"}],"url":"\/documentation\/divar\/postdetailsflowcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController\/title","value":"MainFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MainFlowController\/fragments","value":[{"kind":"identifier","text":"MainFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostDetailsFlowController\/title","value":"PostDetailsFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostDetailsFlowController\/fragments","value":[{"kind":"identifier","text":"PostDetailsFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}