{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostsViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/postsviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/postsviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ComponentProtocol","doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/6Sonnat32FlowLayoutWithAnimationsDelegateP","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UICollectionViewDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIScrollViewDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UIScrollViewDirectionDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCellDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/init(viewModel:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/delegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/scrollingDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/setupPullAndScroll","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/setupUI"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/append(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/clearAll()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/load(with:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/makeDataSource()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/refresh()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/reload()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/scrollToTop()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/setupInfiniteScroll()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/setupPullToRefresh()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/viewDidLoad()"]},{"title":"Enumerations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/Section"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/FlowLayoutWithAnimationsDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/UICollectionViewDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/UIScrollViewDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/UIScrollViewDirectionDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/WidgetCellDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostsViewController"}],"title":"PostsViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)PostsViewController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"PostsViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController/setupInfiniteScroll()":{"role":"symbol","title":"setupInfiniteScroll()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupInfiniteScroll"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/setupInfiniteScroll()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postsviewcontroller\/setupinfinitescroll()"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController/Section":{"role":"symbol","title":"PostsViewController.Section","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Section"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/Section","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Section"}],"url":"\/documentation\/divar\/postsviewcontroller\/section"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/postsviewcontroller\/viewdidload()"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController/setupUI":{"role":"symbol","title":"setupUI","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupUI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/setupUI","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postsviewcontroller\/setupui"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIScrollViewDelegate"},"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostsViewControllerDelegate","preciseIdentifier":"s:5Divar27PostsViewControllerDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postsviewcontroller\/delegate"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController/append(_:)":{"role":"symbol","title":"append(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"append"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"PostModel","preciseIdentifier":"s:5Divar9PostModelV"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/append(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postsviewcontroller\/append(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController":{"role":"symbol","title":"PostsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostsViewController"}],"url":"\/documentation\/divar\/postsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController/WidgetCellDelegate-Implementations":{"role":"collectionGroup","title":"WidgetCellDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/WidgetCellDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/postsviewcontroller\/widgetcelldelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController/clearAll()":{"role":"symbol","title":"clearAll()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearAll"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/clearAll()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postsviewcontroller\/clearall()"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController/scrollingDelegate":{"role":"symbol","title":"scrollingDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollingDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ListScrollingDelegate","preciseIdentifier":"s:5Divar21ListScrollingDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/scrollingDelegate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postsviewcontroller\/scrollingdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController/UIScrollViewDirectionDelegate-Implementations":{"role":"collectionGroup","title":"UIScrollViewDirectionDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/UIScrollViewDirectionDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/postsviewcontroller\/uiscrollviewdirectiondelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/UIScrollViewDirectionDelegate":{"role":"symbol","title":"UIScrollViewDirectionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIScrollViewDirectionDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UIScrollViewDirectionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIScrollViewDirectionDelegate"}],"url":"\/documentation\/divar\/uiscrollviewdirectiondelegate"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController/FlowLayoutWithAnimationsDelegate-Implementations":{"role":"collectionGroup","title":"FlowLayoutWithAnimationsDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/FlowLayoutWithAnimationsDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/postsviewcontroller\/flowlayoutwithanimationsdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController/refresh()":{"role":"symbol","title":"refresh()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/refresh()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"refresh"}],"url":"\/documentation\/divar\/postsviewcontroller\/refresh()"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController/setupPullAndScroll":{"role":"symbol","title":"setupPullAndScroll","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupPullAndScroll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/setupPullAndScroll","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postsviewcontroller\/setuppullandscroll"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController/load(with:)":{"role":"symbol","title":"load(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"load"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PostModel","preciseIdentifier":"s:5Divar9PostModelV"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/load(with:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postsviewcontroller\/load(with:)"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/6Sonnat32FlowLayoutWithAnimationsDelegateP":{"type":"unresolvable","title":"Sonnat.FlowLayoutWithAnimationsDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat32FlowLayoutWithAnimationsDelegateP"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetCellDelegate":{"role":"symbol","title":"WidgetCellDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetCellDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCellDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetCellDelegate"}],"url":"\/documentation\/divar\/widgetcelldelegate"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController/reload()":{"role":"symbol","title":"reload()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reload"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/reload()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postsviewcontroller\/reload()"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)UIViewController"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController/UICollectionViewDelegate-Implementations":{"role":"collectionGroup","title":"UICollectionViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/UICollectionViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/postsviewcontroller\/uicollectionviewdelegate-implementations"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController/init(viewModel:)":{"role":"symbol","title":"init(viewModel:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"viewModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostsViewModelProtocol","preciseIdentifier":"s:5Divar22PostsViewModelProtocolP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/init(viewModel:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postsviewcontroller\/init(viewmodel:)"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController/scrollToTop()":{"role":"symbol","title":"scrollToTop()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollToTop"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/scrollToTop()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postsviewcontroller\/scrolltotop()"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController/setupPullToRefresh()":{"role":"symbol","title":"setupPullToRefresh()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupPullToRefresh"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/setupPullToRefresh()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postsviewcontroller\/setuppulltorefresh()"},"doc://com.Divar.DivarClient/documentation/Divar/ComponentProtocol":{"role":"symbol","title":"ComponentProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComponentProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ComponentProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ComponentProtocol"}],"url":"\/documentation\/divar\/componentprotocol"},"doc://com.Divar.DivarClient/objc(pl)UICollectionViewDelegate":{"type":"unresolvable","title":"UIKit.UICollectionViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UICollectionViewDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController/makeDataSource()":{"role":"symbol","title":"makeDataSource()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeDataSource"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UICollectionViewDiffableDataSource","preciseIdentifier":"s:5UIKit34UICollectionViewDiffableDataSourceC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Section","preciseIdentifier":"s:5Divar19PostsViewControllerC7SectionO"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"PostModel","preciseIdentifier":"s:5Divar9PostModelV"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/makeDataSource()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postsviewcontroller\/makedatasource()"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController/UIScrollViewDelegate-Implementations":{"role":"collectionGroup","title":"UIScrollViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/UIScrollViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/postsviewcontroller\/uiscrollviewdelegate-implementations"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/postsviewcontroller\/init(coder:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PostsViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PostsViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PostsViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/refresh()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/UICollectionViewDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController\/UIScrollViewDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostsViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostsViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostsViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostsViewController\/title","value":"PostsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostsViewController\/fragments","value":[{"kind":"identifier","text":"PostsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostsViewController~1refresh()\/title","value":"refresh"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostsViewController~1refresh()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refresh"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostsViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostsViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}