{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostchiTableViewCell"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/postchitableviewcell"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/postchitableviewcell"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UITableViewCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/objc(pl)CALayerDelegate","doc:\/\/com.Divar.DivarClient\/6Sonnat12ReusableCellP","doc:\/\/com.Divar.DivarClient\/6Sonnat23WithInitializerProtocolP","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearance","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UICoordinateSpace","doc:\/\/com.Divar.DivarClient\/objc(pl)UIDynamicItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItemContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UILargeContentViewerItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/message","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/messageImageView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/messageSubtitleLabel","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/messageTitleLabel","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/postchiLastSeenID","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/seenStatusImageView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/timeLabel","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/title"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/awakeFromNib()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/fill(with:postchiLastSeenID:title:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/traitCollectionDidChange(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostchiTableViewCell"}],"title":"PostchiTableViewCell","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)PostchiTableViewCell","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"PostchiTableViewCell"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PostchiTableViewCell/timeLabel":{"role":"symbol","title":"timeLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/timeLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"timeLabel"}],"url":"\/documentation\/divar\/postchitableviewcell\/timelabel"},"doc://com.Divar.DivarClient/documentation/Divar/PostchiTableViewCell/seenStatusImageView":{"role":"symbol","title":"seenStatusImageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"seenStatusImageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SonnatImageView","preciseIdentifier":"c:@M@Sonnat@objc(cs)SonnatImageView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/seenStatusImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"seenStatusImageView"}],"url":"\/documentation\/divar\/postchitableviewcell\/seenstatusimageview"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIDynamicItem"},"doc://com.Divar.DivarClient/6Sonnat23WithInitializerProtocolP":{"type":"unresolvable","title":"Sonnat.WithInitializerProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat23WithInitializerProtocolP"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/documentation/Divar/PostchiTableViewCell/messageImageView":{"role":"symbol","title":"messageImageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageImageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SonnatImageView","preciseIdentifier":"c:@M@Sonnat@objc(cs)SonnatImageView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/messageImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageImageView"}],"url":"\/documentation\/divar\/postchitableviewcell\/messageimageview"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/PostchiTableViewCell/traitCollectionDidChange(_:)":{"role":"symbol","title":"traitCollectionDidChange(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"traitCollectionDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/traitCollectionDidChange(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"traitCollectionDidChange:"}],"url":"\/documentation\/divar\/postchitableviewcell\/traitcollectiondidchange(_:)"},"doc://com.Divar.DivarClient/objc(pl)UIGestureRecognizerDelegate":{"type":"unresolvable","title":"UIKit.UIGestureRecognizerDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIGestureRecognizerDelegate"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItemContainer"},"doc://com.Divar.DivarClient/documentation/Divar/PostchiTableViewCell/fill(with:postchiLastSeenID:title:)":{"role":"symbol","title":"fill(with:postchiLastSeenID:title:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fill"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"postchiLastSeenID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/fill(with:postchiLastSeenID:title:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postchitableviewcell\/fill(with:postchilastseenid:title:)"},"doc://com.Divar.DivarClient/documentation/Divar/PostchiTableViewCell/initWithStyle:reuseIdentifier:":{"role":"symbol","title":"initWithStyle:reuseIdentifier:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/initWithStyle:reuseIdentifier:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"url":"\/documentation\/divar\/postchitableviewcell\/initwithstyle:reuseidentifier:"},"doc://com.Divar.DivarClient/documentation/Divar/PostchiTableViewCell/messageTitleLabel":{"role":"symbol","title":"messageTitleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageTitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/messageTitleLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageTitleLabel"}],"url":"\/documentation\/divar\/postchitableviewcell\/messagetitlelabel"},"doc://com.Divar.DivarClient/documentation/Divar/PostchiTableViewCell/awakeFromNib()":{"role":"symbol","title":"awakeFromNib()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/awakeFromNib()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"awakeFromNib"}],"url":"\/documentation\/divar\/postchitableviewcell\/awakefromnib()"},"doc://com.Divar.DivarClient/documentation/Divar/PostchiTableViewCell/title":{"role":"symbol","title":"title","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/title","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postchitableviewcell\/title"},"doc://com.Divar.DivarClient/documentation/Divar/PostchiTableViewCell/postchiLastSeenID":{"role":"symbol","title":"postchiLastSeenID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"postchiLastSeenID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/postchiLastSeenID","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postchitableviewcell\/postchilastseenid"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UILargeContentViewerItem"},"doc://com.Divar.DivarClient/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UICoordinateSpace"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/6Sonnat12ReusableCellP":{"type":"unresolvable","title":"Sonnat.ReusableCell","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat12ReusableCellP"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/PostchiTableViewCell":{"role":"symbol","title":"PostchiTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostchiTableViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostchiTableViewCell"}],"url":"\/documentation\/divar\/postchitableviewcell"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PostchiTableViewCell/message":{"role":"symbol","title":"message","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/message","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postchitableviewcell\/message"},"doc://com.Divar.DivarClient/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)CALayerDelegate"},"doc://com.Divar.DivarClient/objc(cs)UITableViewCell":{"type":"unresolvable","title":"UITableViewCell","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)UITableViewCell"},"doc://com.Divar.DivarClient/documentation/Divar/PostchiTableViewCell/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/postchitableviewcell\/initwithcoder:"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItem"},"doc://com.Divar.DivarClient/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAccessibilityIdentification"},"doc://com.Divar.DivarClient/documentation/Divar/PostchiTableViewCell/messageSubtitleLabel":{"role":"symbol","title":"messageSubtitleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageSubtitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MDHTMLLabel","preciseIdentifier":"c:objc(cs)MDHTMLLabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/messageSubtitleLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageSubtitleLabel"}],"url":"\/documentation\/divar\/postchitableviewcell\/messagesubtitlelabel"},"doc://com.Divar.DivarClient/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.Divar.DivarClient/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearance"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PostchiTableViewCell"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PostchiTableViewCell"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PostchiTableViewCell"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/messageImageView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/messageSubtitleLabel","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/messageTitleLabel","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/seenStatusImageView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/timeLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/awakeFromNib()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/initWithCoder:","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/initWithStyle:reuseIdentifier:","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostchiTableViewCell\/traitCollectionDidChange(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UITableViewCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostchiTableViewCell"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostchiTableViewCell~1timeLabel\/title","value":"timeLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostchiTableViewCell~1timeLabel\/fragments","value":[{"kind":"identifier","text":"timeLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostchiTableViewCell~1seenStatusImageView\/title","value":"seenStatusImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostchiTableViewCell~1seenStatusImageView\/fragments","value":[{"kind":"identifier","text":"seenStatusImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostchiTableViewCell~1messageImageView\/title","value":"messageImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostchiTableViewCell~1messageImageView\/fragments","value":[{"kind":"identifier","text":"messageImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostchiTableViewCell~1traitCollectionDidChange(_:)\/title","value":"traitCollectionDidChange:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostchiTableViewCell~1traitCollectionDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"traitCollectionDidChange:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostchiTableViewCell~1messageTitleLabel\/title","value":"messageTitleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostchiTableViewCell~1messageTitleLabel\/fragments","value":[{"kind":"identifier","text":"messageTitleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostchiTableViewCell~1awakeFromNib()\/title","value":"awakeFromNib"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostchiTableViewCell~1awakeFromNib()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"awakeFromNib"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostchiTableViewCell\/title","value":"PostchiTableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostchiTableViewCell\/fragments","value":[{"kind":"identifier","text":"PostchiTableViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostchiTableViewCell~1messageSubtitleLabel\/title","value":"messageSubtitleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostchiTableViewCell~1messageSubtitleLabel\/fragments","value":[{"kind":"identifier","text":"messageSubtitleLabel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}