{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostListViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/postlistviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/postlistviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ListScrollingDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Searchable","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","doc:\/\/com.Divar.DivarClient\/6Sonnat27CategoryCarouselBarDelegateP","doc:\/\/com.Divar.DivarClient\/6Sonnat16ChipViewDelegateP","doc:\/\/com.Divar.DivarClient\/6Sonnat17SearchBoxDelegateP","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UpdateViewControllerDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/init(viewModel:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/carouselView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/chipView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/cityFilterView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/isSearchActive","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/listStack","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/postListTabbedVC","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/searchBox","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/searchStack","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/searchVC","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/stickyCategories"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/fillCategoryCarousel(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/handleUpdate()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/normalMode()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/reload()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/reload(filterSet:isFromSearch:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/scrollToTop()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/searchBoxSearchButtonClicked(searchText:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/searchingMode()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/selectCarouselItem(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/setupSearchController()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/showSmartSuggestions(_:forceExpand:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/tagListDidSelect(item:index:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/taglistDidRemove(item:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/updateNoCatPage(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/updateQuery(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/CategoryCarouselBarDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/ChipViewDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/ListScrollingDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/PostsViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/SearchBoxDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/UpdateViewControllerDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostListViewController"}],"title":"PostListViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)PostListViewController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"PostListViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/cityFilterView":{"role":"symbol","title":"cityFilterView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cityFilterView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CityFilterView","preciseIdentifier":"c:@M@Divar@objc(cs)CityFilterView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/cityFilterView","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/cityfilterview"},"doc://com.Divar.DivarClient/documentation/Divar/ShowMessageProtocol":{"role":"symbol","title":"ShowMessageProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowMessageProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowMessageProtocol"}],"url":"\/documentation\/divar\/showmessageprotocol"},"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/ListScrollingDelegate":{"role":"symbol","title":"ListScrollingDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListScrollingDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ListScrollingDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ListScrollingDelegate"}],"url":"\/documentation\/divar\/listscrollingdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/searchBox":{"role":"symbol","title":"searchBox","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBox"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchBox","preciseIdentifier":"c:@M@Sonnat@objc(cs)SearchBox"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/searchBox","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/searchbox"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/searchVC":{"role":"symbol","title":"searchVC","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SearchViewController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/searchVC","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/searchvc"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/setupSearchController()":{"role":"symbol","title":"setupSearchController()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupSearchController"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/setupSearchController()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/setupsearchcontroller()"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/listStack":{"role":"symbol","title":"listStack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"listStack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/listStack","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/liststack"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/postListTabbedVC":{"role":"symbol","title":"postListTabbedVC","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"postListTabbedVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostListTabbedViewController","preciseIdentifier":"c:@M@Divar@objc(cs)PostListTabbedViewController"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/postListTabbedVC","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/postlisttabbedvc"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/searchingMode()":{"role":"symbol","title":"searchingMode()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchingMode"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/searchingMode()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/searchingmode()"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/CategoryCarouselBarDelegate-Implementations":{"role":"collectionGroup","title":"CategoryCarouselBarDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/CategoryCarouselBarDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/categorycarouselbardelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/searchStack":{"role":"symbol","title":"searchStack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchStack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/searchStack","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/searchstack"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/init(viewModel:)":{"role":"symbol","title":"init(viewModel:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"viewModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostListViewModelProtocol","preciseIdentifier":"s:5Divar25PostListViewModelProtocolP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/init(viewModel:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/init(viewmodel:)"},"doc://com.Divar.DivarClient/documentation/Divar/TooltipPresenter":{"role":"symbol","title":"TooltipPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TooltipPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TooltipPresenter"}],"url":"\/documentation\/divar\/tooltippresenter"},"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController":{"role":"symbol","title":"BaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseViewController"}],"url":"\/documentation\/divar\/baseviewcontroller"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/documentation/Divar/Searchable":{"role":"symbol","title":"Searchable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Searchable"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Searchable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Searchable"}],"url":"\/documentation\/divar\/searchable"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/handleUpdate()":{"role":"symbol","title":"handleUpdate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleUpdate"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/handleUpdate()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/handleupdate()"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/ListScrollingDelegate-Implementations":{"role":"collectionGroup","title":"ListScrollingDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/ListScrollingDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/listscrollingdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/postlistviewcontroller\/init(coder:)"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/normalMode()":{"role":"symbol","title":"normalMode()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"normalMode"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/normalMode()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/normalmode()"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/stickyCategories":{"role":"symbol","title":"stickyCategories","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stickyCategories"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"StickyCategory","preciseIdentifier":"s:5Divar14StickyCategoryV"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/stickyCategories","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/stickycategories"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/tagListDidSelect(item:index:)":{"role":"symbol","title":"tagListDidSelect(item:index:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagListDidSelect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagListItem","preciseIdentifier":"s:5Divar11TagListItemP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/tagListDidSelect(item:index:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/taglistdidselect(item:index:)"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/6Sonnat27CategoryCarouselBarDelegateP":{"type":"unresolvable","title":"Sonnat.CategoryCarouselBarDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat27CategoryCarouselBarDelegateP"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/documentation/Divar/UpdateViewControllerDelegate":{"role":"symbol","title":"UpdateViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UpdateViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UpdateViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UpdateViewControllerDelegate"}],"url":"\/documentation\/divar\/updateviewcontrollerdelegate"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/showSmartSuggestions(_:forceExpand:)":{"role":"symbol","title":"showSmartSuggestions(_:forceExpand:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showSmartSuggestions"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"TagListSuggestion","preciseIdentifier":"s:5Divar17TagListSuggestionV"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"forceExpand"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/showSmartSuggestions(_:forceExpand:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/showsmartsuggestions(_:forceexpand:)"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/reload()":{"role":"symbol","title":"reload()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reload"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/reload()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/reload()"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/reload(filterSet:isFromSearch:)":{"role":"symbol","title":"reload(filterSet:isFromSearch:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reload"},{"kind":"text","text":"("},{"kind":"externalParam","text":"filterSet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchFilterHistory","preciseIdentifier":"s:5Divar19SearchFilterHistoryV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isFromSearch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/reload(filterSet:isFromSearch:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/reload(filterset:isfromsearch:)"},"doc://com.Divar.DivarClient/6Sonnat16ChipViewDelegateP":{"type":"unresolvable","title":"Sonnat.ChipViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat16ChipViewDelegateP"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewControllerDelegate":{"role":"symbol","title":"PostsViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostsViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostsViewControllerDelegate"}],"url":"\/documentation\/divar\/postsviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/ChipViewDelegate-Implementations":{"role":"collectionGroup","title":"ChipViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/ChipViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/chipviewdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/scrollToTop()":{"role":"symbol","title":"scrollToTop()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollToTop"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/scrollToTop()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/scrolltotop()"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/fillCategoryCarousel(_:)":{"role":"symbol","title":"fillCategoryCarousel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fillCategoryCarousel"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"StickyCategory","preciseIdentifier":"s:5Divar14StickyCategoryV"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/fillCategoryCarousel(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/fillcategorycarousel(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/updateQuery(_:)":{"role":"symbol","title":"updateQuery(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateQuery"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/updateQuery(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/updatequery(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/ShowErrorProtocol":{"role":"symbol","title":"ShowErrorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowErrorProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowErrorProtocol"}],"url":"\/documentation\/divar\/showerrorprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/taglistDidRemove(item:)":{"role":"symbol","title":"taglistDidRemove(item:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"taglistDidRemove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagListItem","preciseIdentifier":"s:5Divar11TagListItemP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/taglistDidRemove(item:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/taglistdidremove(item:)"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/selectCarouselItem(_:)":{"role":"symbol","title":"selectCarouselItem(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectCarouselItem"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/selectCarouselItem(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/selectcarouselitem(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/searchBoxSearchButtonClicked(searchText:)":{"role":"symbol","title":"searchBoxSearchButtonClicked(searchText:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBoxSearchButtonClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"searchText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/searchBoxSearchButtonClicked(searchText:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/searchboxsearchbuttonclicked(searchtext:)"},"doc://com.Divar.DivarClient/6Sonnat17SearchBoxDelegateP":{"type":"unresolvable","title":"Sonnat.SearchBoxDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat17SearchBoxDelegateP"},"doc://com.Divar.DivarClient/documentation/Divar/PaymentSystemProtocol":{"role":"symbol","title":"PaymentSystemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSystemProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaymentSystemProtocol"}],"url":"\/documentation\/divar\/paymentsystemprotocol"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController":{"role":"symbol","title":"PostListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostListViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostListViewController"}],"url":"\/documentation\/divar\/postlistviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/PostsViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"PostsViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/PostsViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/postsviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/updateNoCatPage(_:)":{"role":"symbol","title":"updateNoCatPage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateNoCatPage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/updateNoCatPage(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/updatenocatpage(_:)"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/SearchBoxDelegate-Implementations":{"role":"collectionGroup","title":"SearchBoxDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/SearchBoxDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/searchboxdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/ErrorMessageHandler":{"role":"symbol","title":"ErrorMessageHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorMessageHandler"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorMessageHandler"}],"url":"\/documentation\/divar\/errormessagehandler"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/isSearchActive":{"role":"symbol","title":"isSearchActive","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSearchActive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/isSearchActive","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/issearchactive"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/UpdateViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"UpdateViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/UpdateViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/updateviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/chipView":{"role":"symbol","title":"chipView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chipView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChipView","preciseIdentifier":"s:6Sonnat8ChipViewC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"TagListSuggestion","preciseIdentifier":"s:5Divar17TagListSuggestionV"},{"kind":"text","text":">!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/chipView","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/chipview"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/carouselView":{"role":"symbol","title":"carouselView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"carouselView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CategoryCarouselBar","preciseIdentifier":"c:@M@Sonnat@objc(cs)CategoryCarouselBar"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/carouselView","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlistviewcontroller\/carouselview"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/postlistviewcontroller\/viewdidload()"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PostListViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PostListViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PostListViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostListViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController","preciseIdentifier":"c:@M@Divar@objc(cs)BaseViewController","text":"BaseViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController\/title","value":"BaseViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController\/fragments","value":[{"kind":"identifier","text":"BaseViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListViewController\/title","value":"PostListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListViewController\/fragments","value":[{"kind":"identifier","text":"PostListViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}