{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostListViewModelDelegate"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/postlistviewmodeldelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BrowseFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeaturedPostsFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListFlowController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewModelDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewModelDelegate\/postListViewModel(_:didRequestCategorySelectorWith:)-5uljs","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewModelDelegate\/postListViewModel(_:didRequestFilterSetEditor:inputSuggestionKey:)-6nf39","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewModelDelegate\/postListViewModel(_:didRequestFilteringCities:)-9oaeh","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewModelDelegate\/postListViewModel(_:didRequestFilteringPosts:)-3yz6b","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewModelDelegate\/postListViewModel(_:didRequestPerformWidgetAction:)-53uhm","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewModelDelegate\/postListViewModel(_:didRequestWidgetAction:)-5uum8","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewModelDelegate\/postListViewModel(_:didSelectPost:from:)-3xk0h"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostListViewModelDelegate"}],"title":"PostListViewModelDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar25PostListViewModelDelegateP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"PostListViewModelDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PostListViewModelDelegate/postListViewModel(_:didSelectPost:from:)-3xk0h":{"defaultImplementations":1,"role":"symbol","title":"postListViewModel(_:didSelectPost:from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postListViewModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PostListViewModel","preciseIdentifier":"s:5Divar17PostListViewModelC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectPost"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostModel","preciseIdentifier":"s:5Divar9PostModelV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostViewSource","preciseIdentifier":"s:5Divar14PostViewSourceO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewModelDelegate\/postListViewModel(_:didSelectPost:from:)-3xk0h","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/postlistviewmodeldelegate\/postlistviewmodel(_:didselectpost:from:)-3xk0h"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewModelDelegate/postListViewModel(_:didRequestFilteringPosts:)-3yz6b":{"defaultImplementations":1,"role":"symbol","title":"postListViewModel(_:didRequestFilteringPosts:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postListViewModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PostListViewModel","preciseIdentifier":"s:5Divar17PostListViewModelC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestFilteringPosts"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchFilterHistory","preciseIdentifier":"s:5Divar19SearchFilterHistoryV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewModelDelegate\/postListViewModel(_:didRequestFilteringPosts:)-3yz6b","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/postlistviewmodeldelegate\/postlistviewmodel(_:didrequestfilteringposts:)-3yz6b"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewModelDelegate/postListViewModel(_:didRequestFilteringCities:)-9oaeh":{"defaultImplementations":1,"role":"symbol","title":"postListViewModel(_:didRequestFilteringCities:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postListViewModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PostListViewModel","preciseIdentifier":"s:5Divar17PostListViewModelC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestFilteringCities"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewModelDelegate\/postListViewModel(_:didRequestFilteringCities:)-9oaeh","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/postlistviewmodeldelegate\/postlistviewmodel(_:didrequestfilteringcities:)-9oaeh"},"doc://com.Divar.DivarClient/documentation/Divar/PostListFlowController":{"role":"symbol","title":"PostListFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostListFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostListFlowController"}],"url":"\/documentation\/divar\/postlistflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewModelDelegate/postListViewModel(_:didRequestCategorySelectorWith:)-5uljs":{"defaultImplementations":1,"role":"symbol","title":"postListViewModel(_:didRequestCategorySelectorWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postListViewModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PostListViewModel","preciseIdentifier":"s:5Divar17PostListViewModelC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestCategorySelectorWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewModelDelegate\/postListViewModel(_:didRequestCategorySelectorWith:)-5uljs","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/postlistviewmodeldelegate\/postlistviewmodel(_:didrequestcategoryselectorwith:)-5uljs"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewModelDelegate/postListViewModel(_:didRequestWidgetAction:)-5uum8":{"defaultImplementations":1,"role":"symbol","title":"postListViewModel(_:didRequestWidgetAction:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postListViewModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PostListViewModel","preciseIdentifier":"s:5Divar17PostListViewModelC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestWidgetAction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewModelDelegate\/postListViewModel(_:didRequestWidgetAction:)-5uum8","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/postlistviewmodeldelegate\/postlistviewmodel(_:didrequestwidgetaction:)-5uum8"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewModelDelegate/postListViewModel(_:didRequestFilterSetEditor:inputSuggestionKey:)-6nf39":{"defaultImplementations":1,"role":"symbol","title":"postListViewModel(_:didRequestFilterSetEditor:inputSuggestionKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postListViewModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PostListViewModel","preciseIdentifier":"s:5Divar17PostListViewModelC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestFilterSetEditor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchFilterHistory","preciseIdentifier":"s:5Divar19SearchFilterHistoryV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inputSuggestionKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewModelDelegate\/postListViewModel(_:didRequestFilterSetEditor:inputSuggestionKey:)-6nf39","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/postlistviewmodeldelegate\/postlistviewmodel(_:didrequestfilterseteditor:inputsuggestionkey:)-6nf39"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewModelDelegate":{"role":"symbol","title":"PostListViewModelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostListViewModelDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewModelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostListViewModelDelegate"}],"url":"\/documentation\/divar\/postlistviewmodeldelegate"},"doc://com.Divar.DivarClient/documentation/Divar/FeaturedPostsFlowController":{"role":"symbol","title":"FeaturedPostsFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeaturedPostsFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeaturedPostsFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeaturedPostsFlowController"}],"url":"\/documentation\/divar\/featuredpostsflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BrowseFlowController":{"role":"symbol","title":"BrowseFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrowseFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BrowseFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BrowseFlowController"}],"url":"\/documentation\/divar\/browseflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostListViewModelDelegate/postListViewModel(_:didRequestPerformWidgetAction:)-53uhm":{"defaultImplementations":1,"role":"symbol","title":"postListViewModel(_:didRequestPerformWidgetAction:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postListViewModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PostListViewModel","preciseIdentifier":"s:5Divar17PostListViewModelC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestPerformWidgetAction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Widget","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_WidgetV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListViewModelDelegate\/postListViewModel(_:didRequestPerformWidgetAction:)-53uhm","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/postlistviewmodeldelegate\/postlistviewmodel(_:didrequestperformwidgetaction:)-53uhm"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListFlowController\/title","value":"PostListFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListFlowController\/fragments","value":[{"kind":"identifier","text":"PostListFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeaturedPostsFlowController\/title","value":"FeaturedPostsFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeaturedPostsFlowController\/fragments","value":[{"kind":"identifier","text":"FeaturedPostsFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BrowseFlowController\/title","value":"BrowseFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BrowseFlowController\/fragments","value":[{"kind":"identifier","text":"BrowseFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}