{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QuickLookViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/quicklookviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/quicklookviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)QLPreviewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/objc(pl)QLPreviewControllerDataSource","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/init(fileInfo:index:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/cacheDirectory","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/fileInfo","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/fileStaticURLs","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/index","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/loadingURL"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/numberOfPreviewItems(in:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/previewController(_:previewItemAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/viewDidLoad()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/viewWillAppear(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QuickLookViewController"}],"title":"QuickLookViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)QuickLookViewController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"QuickLookViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/documentation/Divar/QuickLookViewController/fileInfo":{"role":"symbol","title":"fileInfo","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"FileInfo","preciseIdentifier":"c:@M@Divar@objc(cs)FileInfo"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/fileInfo","kind":"symbol","type":"topic","url":"\/documentation\/divar\/quicklookviewcontroller\/fileinfo"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/QuickLookViewController/loadingURL":{"role":"symbol","title":"loadingURL","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadingURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/loadingURL","kind":"symbol","type":"topic","url":"\/documentation\/divar\/quicklookviewcontroller\/loadingurl"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/documentation/Divar/QuickLookViewController":{"role":"symbol","title":"QuickLookViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QuickLookViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QuickLookViewController"}],"url":"\/documentation\/divar\/quicklookviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/QuickLookViewController/viewWillAppear(_:)":{"role":"symbol","title":"viewWillAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/viewWillAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"url":"\/documentation\/divar\/quicklookviewcontroller\/viewwillappear(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/QuickLookViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/quicklookviewcontroller\/viewdidload()"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/QuickLookViewController/fileStaticURLs":{"role":"symbol","title":"fileStaticURLs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileStaticURLs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/fileStaticURLs","kind":"symbol","type":"topic","url":"\/documentation\/divar\/quicklookviewcontroller\/filestaticurls"},"doc://com.Divar.DivarClient/objc(pl)QLPreviewControllerDataSource":{"type":"unresolvable","title":"QLPreviewControllerDataSource","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)QLPreviewControllerDataSource"},"doc://com.Divar.DivarClient/documentation/Divar/QuickLookViewController/init(fileInfo:index:)":{"role":"symbol","title":"init(fileInfo:index:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fileInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"FileInfo","preciseIdentifier":"c:@M@Divar@objc(cs)FileInfo"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/init(fileInfo:index:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/quicklookviewcontroller\/init(fileinfo:index:)"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/documentation/Divar/QuickLookViewController/previewController(_:previewItemAt:)":{"role":"symbol","title":"previewController(_:previewItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previewItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"QLPreviewItem","preciseIdentifier":"c:objc(pl)QLPreviewItem"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/previewController(_:previewItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"previewController:previewItemAtIndex:"}],"url":"\/documentation\/divar\/quicklookviewcontroller\/previewcontroller(_:previewitemat:)"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/documentation/Divar/QuickLookViewController/index":{"role":"symbol","title":"index","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/index","kind":"symbol","type":"topic","url":"\/documentation\/divar\/quicklookviewcontroller\/index"},"doc://com.Divar.DivarClient/documentation/Divar/QuickLookViewController/numberOfPreviewItems(in:)":{"role":"symbol","title":"numberOfPreviewItems(in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfPreviewItems"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/numberOfPreviewItems(in:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"numberOfPreviewItemsInPreviewController:"}],"url":"\/documentation\/divar\/quicklookviewcontroller\/numberofpreviewitems(in:)"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/objc(cs)QLPreviewController":{"type":"unresolvable","title":"QLPreviewController","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)QLPreviewController"},"doc://com.Divar.DivarClient/documentation/Divar/QuickLookViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/quicklookviewcontroller\/init(coder:)"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/QuickLookViewController/cacheDirectory":{"role":"symbol","title":"cacheDirectory","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheDirectory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/cacheDirectory","kind":"symbol","type":"topic","url":"\/documentation\/divar\/quicklookviewcontroller\/cachedirectory"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"QuickLookViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"QuickLookViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"QuickLookViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/numberOfPreviewItems(in:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/previewController(_:previewItemAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/viewDidLoad()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/QuickLookViewController\/viewWillAppear(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)QLPreviewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)QLPreviewControllerDataSource"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"QuickLookViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1QuickLookViewController\/title","value":"QuickLookViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1QuickLookViewController\/fragments","value":[{"kind":"identifier","text":"QuickLookViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1QuickLookViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1QuickLookViewController~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1QuickLookViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1QuickLookViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1QuickLookViewController~1previewController(_:previewItemAt:)\/title","value":"previewController:previewItemAtIndex:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1QuickLookViewController~1previewController(_:previewItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"previewController:previewItemAtIndex:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1QuickLookViewController~1numberOfPreviewItems(in:)\/title","value":"numberOfPreviewItemsInPreviewController:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1QuickLookViewController~1numberOfPreviewItems(in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"numberOfPreviewItemsInPreviewController:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1QuickLookViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1QuickLookViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}