{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RangeSelectTableViewCell"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/rangeselecttableviewcell"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/rangeselecttableviewcell"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UITableViewCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostfixTextFieldProtocol","doc:\/\/com.Divar.DivarClient\/objc(pl)CALayerDelegate","doc:\/\/com.Divar.DivarClient\/6Sonnat12ReusableCellP","doc:\/\/com.Divar.DivarClient\/6Sonnat23WithInitializerProtocolP","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearance","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UICoordinateSpace","doc:\/\/com.Divar.DivarClient\/objc(pl)UIDynamicItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItemContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UILargeContentViewerItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UITextFieldDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/actionSheet","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/currentValue","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/delegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/key","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/label","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/otherValuesTitle","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/pricePostFixLabel","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/textField","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/titleTextfieldConstraint","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/toolbarTitle"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/awakeFromNib()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/bottomSheetCase(string:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/donePressed(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/isBottomSheetCase(string:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/setupKeyboard(property:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/textFieldDidChange(_:)"]},{"title":"Enumerations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/RangeSelectValue"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/PostfixTextFieldProtocol-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/UITextFieldDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RangeSelectTableViewCell"}],"title":"RangeSelectTableViewCell","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)RangeSelectTableViewCell","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"RangeSelectTableViewCell"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell/PostfixTextFieldProtocol-Implementations":{"role":"collectionGroup","title":"PostfixTextFieldProtocol Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/PostfixTextFieldProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/rangeselecttableviewcell\/postfixtextfieldprotocol-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RangeSelectCellDelegate","preciseIdentifier":"s:5Divar23RangeSelectCellDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/rangeselecttableviewcell\/delegate"},"doc://com.Divar.DivarClient/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItem"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UICoordinateSpace"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell/RangeSelectValue":{"role":"symbol","title":"RangeSelectTableViewCell.RangeSelectValue","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RangeSelectValue"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/RangeSelectValue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RangeSelectValue"}],"url":"\/documentation\/divar\/rangeselecttableviewcell\/rangeselectvalue"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell":{"role":"symbol","title":"RangeSelectTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RangeSelectTableViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RangeSelectTableViewCell"}],"url":"\/documentation\/divar\/rangeselecttableviewcell"},"doc://com.Divar.DivarClient/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearance"},"doc://com.Divar.DivarClient/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)CALayerDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell/UITextFieldDelegate-Implementations":{"role":"collectionGroup","title":"UITextFieldDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/UITextFieldDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/rangeselecttableviewcell\/uitextfielddelegate-implementations"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/objc(pl)UIGestureRecognizerDelegate":{"type":"unresolvable","title":"UIKit.UIGestureRecognizerDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIGestureRecognizerDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell/label":{"role":"symbol","title":"label","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"label"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/label","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"label"}],"url":"\/documentation\/divar\/rangeselecttableviewcell\/label"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/PostfixTextFieldProtocol":{"role":"symbol","title":"PostfixTextFieldProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostfixTextFieldProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostfixTextFieldProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostfixTextFieldProtocol"}],"url":"\/documentation\/divar\/postfixtextfieldprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell/bottomSheetCase(string:)":{"role":"symbol","title":"bottomSheetCase(string:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomSheetCase"},{"kind":"text","text":"("},{"kind":"externalParam","text":"string"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/bottomSheetCase(string:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/rangeselecttableviewcell\/bottomsheetcase(string:)"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItemContainer"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/6Sonnat23WithInitializerProtocolP":{"type":"unresolvable","title":"Sonnat.WithInitializerProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat23WithInitializerProtocolP"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell/key":{"role":"symbol","title":"key","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/key","kind":"symbol","type":"topic","url":"\/documentation\/divar\/rangeselecttableviewcell\/key"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell/otherValuesTitle":{"role":"symbol","title":"otherValuesTitle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"otherValuesTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/otherValuesTitle","kind":"symbol","type":"topic","url":"\/documentation\/divar\/rangeselecttableviewcell\/othervaluestitle"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell/awakeFromNib()":{"role":"symbol","title":"awakeFromNib()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/awakeFromNib()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"awakeFromNib"}],"url":"\/documentation\/divar\/rangeselecttableviewcell\/awakefromnib()"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/6Sonnat12ReusableCellP":{"type":"unresolvable","title":"Sonnat.ReusableCell","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat12ReusableCellP"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell/titleTextfieldConstraint":{"role":"symbol","title":"titleTextfieldConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleTextfieldConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/titleTextfieldConstraint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleTextfieldConstraint"}],"url":"\/documentation\/divar\/rangeselecttableviewcell\/titletextfieldconstraint"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell/pricePostFixLabel":{"role":"symbol","title":"pricePostFixLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pricePostFixLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/pricePostFixLabel","kind":"symbol","type":"topic","url":"\/documentation\/divar\/rangeselecttableviewcell\/pricepostfixlabel"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell/isBottomSheetCase(string:)":{"role":"symbol","title":"isBottomSheetCase(string:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isBottomSheetCase"},{"kind":"text","text":"("},{"kind":"externalParam","text":"string"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/isBottomSheetCase(string:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/rangeselecttableviewcell\/isbottomsheetcase(string:)"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell/donePressed(_:)":{"role":"symbol","title":"donePressed(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"donePressed"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/donePressed(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"donePressed:"}],"url":"\/documentation\/divar\/rangeselecttableviewcell\/donepressed(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell/currentValue":{"role":"symbol","title":"currentValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RangeSelectValue","preciseIdentifier":"s:5Divar24RangeSelectTableViewCellC0bC5ValueO"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/currentValue","kind":"symbol","type":"topic","url":"\/documentation\/divar\/rangeselecttableviewcell\/currentvalue"},"doc://com.Divar.DivarClient/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIDynamicItem"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell/textField":{"role":"symbol","title":"textField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostfixTextField","preciseIdentifier":"c:@M@Divar@objc(cs)PostfixTextField"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/textField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textField"}],"url":"\/documentation\/divar\/rangeselecttableviewcell\/textfield"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell/setupKeyboard(property:)":{"role":"symbol","title":"setupKeyboard(property:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupKeyboard"},{"kind":"text","text":"("},{"kind":"externalParam","text":"property"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/setupKeyboard(property:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/rangeselecttableviewcell\/setupkeyboard(property:)"},"doc://com.Divar.DivarClient/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAccessibilityIdentification"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell/actionSheet":{"role":"symbol","title":"actionSheet","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionSheet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BottomSheetViewController","preciseIdentifier":"c:@M@Divar@objc(cs)BottomSheetViewController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/actionSheet","kind":"symbol","type":"topic","url":"\/documentation\/divar\/rangeselecttableviewcell\/actionsheet"},"doc://com.Divar.DivarClient/objc(cs)UITableViewCell":{"type":"unresolvable","title":"UITableViewCell","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)UITableViewCell"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell/toolbarTitle":{"role":"symbol","title":"toolbarTitle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"toolbarTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/toolbarTitle","kind":"symbol","type":"topic","url":"\/documentation\/divar\/rangeselecttableviewcell\/toolbartitle"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/objc(pl)UITextFieldDelegate":{"type":"unresolvable","title":"UIKit.UITextFieldDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITextFieldDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell/initWithStyle:reuseIdentifier:":{"role":"symbol","title":"initWithStyle:reuseIdentifier:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/initWithStyle:reuseIdentifier:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"url":"\/documentation\/divar\/rangeselecttableviewcell\/initwithstyle:reuseidentifier:"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell/textFieldDidChange(_:)":{"role":"symbol","title":"textFieldDidChange(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/textFieldDidChange(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldDidChange:"}],"url":"\/documentation\/divar\/rangeselecttableviewcell\/textfielddidchange(_:)"},"doc://com.Divar.DivarClient/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UILargeContentViewerItem"},"doc://com.Divar.DivarClient/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.Divar.DivarClient/documentation/Divar/RangeSelectTableViewCell/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/rangeselecttableviewcell\/initwithcoder:"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"RangeSelectTableViewCell"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"RangeSelectTableViewCell"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"RangeSelectTableViewCell"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/label","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/textField","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/titleTextfieldConstraint"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/awakeFromNib()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/donePressed(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/initWithCoder:","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/initWithStyle:reuseIdentifier:","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/textFieldDidChange(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RangeSelectTableViewCell\/UITextFieldDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UITableViewCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"RangeSelectTableViewCell"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RangeSelectTableViewCell\/title","value":"RangeSelectTableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RangeSelectTableViewCell\/fragments","value":[{"kind":"identifier","text":"RangeSelectTableViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RangeSelectTableViewCell~1label\/title","value":"label"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RangeSelectTableViewCell~1label\/fragments","value":[{"kind":"identifier","text":"label"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RangeSelectTableViewCell~1awakeFromNib()\/title","value":"awakeFromNib"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RangeSelectTableViewCell~1awakeFromNib()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"awakeFromNib"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RangeSelectTableViewCell~1titleTextfieldConstraint\/title","value":"titleTextfieldConstraint"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RangeSelectTableViewCell~1titleTextfieldConstraint\/fragments","value":[{"kind":"identifier","text":"titleTextfieldConstraint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RangeSelectTableViewCell~1donePressed(_:)\/title","value":"donePressed:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RangeSelectTableViewCell~1donePressed(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"donePressed:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RangeSelectTableViewCell~1textField\/title","value":"textField"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RangeSelectTableViewCell~1textField\/fragments","value":[{"kind":"identifier","text":"textField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RangeSelectTableViewCell~1textFieldDidChange(_:)\/title","value":"textFieldDidChange:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RangeSelectTableViewCell~1textFieldDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldDidChange:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}