{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RateRowView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/raterowview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/raterowview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Connectable","doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/objc(pl)CALayerDelegate","doc:\/\/com.Divar.DivarClient\/6Sonnat23WithInitializerProtocolP","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearance","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UICoordinateSpace","doc:\/\/com.Divar.DivarClient\/objc(pl)UIDynamicItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItemContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UILargeContentViewerItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/init(frame:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/angryImageView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/didTapRate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/emojisListImageView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/happyImageView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/neutralImageView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/sadImageView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/satisfiedImageView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/selectRate"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/angryImageTap()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/awakeFromNib()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/config()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/happyImageTap()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/neutralImageTap()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/resetEmoji()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/sadImageTap()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/satisfiedImageTap()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RateRowView"}],"title":"RateRowView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)RateRowView","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"RateRowView"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/RateRowView/resetEmoji()":{"role":"symbol","title":"resetEmoji()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetEmoji"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/resetEmoji()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/raterowview\/resetemoji()"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/RateRowView/didTapRate":{"role":"symbol","title":"didTapRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapRate"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Widgets_RateScore","preciseIdentifier":"s:19DivarInterfaceSwift17Widgets_RateScoreV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Score","preciseIdentifier":"s:19DivarInterfaceSwift17Widgets_RateScoreV0F0O"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/didTapRate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/raterowview\/didtaprate"},"doc://com.Divar.DivarClient/documentation/Divar/RateRowView/emojisListImageView":{"role":"symbol","title":"emojisListImageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"emojisListImageView"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SonnatImageView","preciseIdentifier":"c:@M@Sonnat@objc(cs)SonnatImageView"},{"kind":"text","text":"]!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/emojisListImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"emojisListImageView"}],"url":"\/documentation\/divar\/raterowview\/emojislistimageview"},"doc://com.Divar.DivarClient/documentation/Divar/RateRowView/satisfiedImageTap()":{"role":"symbol","title":"satisfiedImageTap()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"satisfiedImageTap"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/satisfiedImageTap()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"satisfiedImageTap"}],"url":"\/documentation\/divar\/raterowview\/satisfiedimagetap()"},"doc://com.Divar.DivarClient/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/RateRowView/angryImageView":{"role":"symbol","title":"angryImageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"angryImageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SonnatImageView","preciseIdentifier":"c:@M@Sonnat@objc(cs)SonnatImageView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/angryImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"angryImageView"}],"url":"\/documentation\/divar\/raterowview\/angryimageview"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/RateRowView/init(frame:)":{"role":"symbol","title":"init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/init(frame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/divar\/raterowview\/init(frame:)"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/documentation/Divar/RateRowView/sadImageView":{"role":"symbol","title":"sadImageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sadImageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SonnatImageView","preciseIdentifier":"c:@M@Sonnat@objc(cs)SonnatImageView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/sadImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sadImageView"}],"url":"\/documentation\/divar\/raterowview\/sadimageview"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItemContainer"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)CALayerDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/RateRowView/satisfiedImageView":{"role":"symbol","title":"satisfiedImageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"satisfiedImageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SonnatImageView","preciseIdentifier":"c:@M@Sonnat@objc(cs)SonnatImageView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/satisfiedImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"satisfiedImageView"}],"url":"\/documentation\/divar\/raterowview\/satisfiedimageview"},"doc://com.Divar.DivarClient/documentation/Divar/RateRowView/angryImageTap()":{"role":"symbol","title":"angryImageTap()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"angryImageTap"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/angryImageTap()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"angryImageTap"}],"url":"\/documentation\/divar\/raterowview\/angryimagetap()"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItem"},"doc://com.Divar.DivarClient/6Sonnat23WithInitializerProtocolP":{"type":"unresolvable","title":"Sonnat.WithInitializerProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat23WithInitializerProtocolP"},"doc://com.Divar.DivarClient/documentation/Divar/RateRowView/awakeFromNib()":{"role":"symbol","title":"awakeFromNib()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/awakeFromNib()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"awakeFromNib"}],"url":"\/documentation\/divar\/raterowview\/awakefromnib()"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/documentation/Divar/RateRowView/neutralImageView":{"role":"symbol","title":"neutralImageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"neutralImageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SonnatImageView","preciseIdentifier":"c:@M@Sonnat@objc(cs)SonnatImageView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/neutralImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"neutralImageView"}],"url":"\/documentation\/divar\/raterowview\/neutralimageview"},"doc://com.Divar.DivarClient/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UILargeContentViewerItem"},"doc://com.Divar.DivarClient/documentation/Divar/RateRowView/selectRate":{"role":"symbol","title":"selectRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_RateScore","preciseIdentifier":"s:19DivarInterfaceSwift17Widgets_RateScoreV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Score","preciseIdentifier":"s:19DivarInterfaceSwift17Widgets_RateScoreV0F0O"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/selectRate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/raterowview\/selectrate"},"doc://com.Divar.DivarClient/documentation/Divar/RateRowView/happyImageView":{"role":"symbol","title":"happyImageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"happyImageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SonnatImageView","preciseIdentifier":"c:@M@Sonnat@objc(cs)SonnatImageView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/happyImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"happyImageView"}],"url":"\/documentation\/divar\/raterowview\/happyimageview"},"doc://com.Divar.DivarClient/documentation/Divar/RateRowView/happyImageTap()":{"role":"symbol","title":"happyImageTap()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"happyImageTap"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/happyImageTap()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"happyImageTap"}],"url":"\/documentation\/divar\/raterowview\/happyimagetap()"},"doc://com.Divar.DivarClient/documentation/Divar/RateRowView/sadImageTap()":{"role":"symbol","title":"sadImageTap()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sadImageTap"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/sadImageTap()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sadImageTap"}],"url":"\/documentation\/divar\/raterowview\/sadimagetap()"},"doc://com.Divar.DivarClient/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIDynamicItem"},"doc://com.Divar.DivarClient/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)UIView"},"doc://com.Divar.DivarClient/documentation/Divar/RateRowView/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/raterowview\/init(coder:)"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearance"},"doc://com.Divar.DivarClient/documentation/Divar/RateRowView/config()":{"role":"symbol","title":"config()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"config"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/config()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/raterowview\/config()"},"doc://com.Divar.DivarClient/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UICoordinateSpace"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/RateRowView/neutralImageTap()":{"role":"symbol","title":"neutralImageTap()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"neutralImageTap"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/neutralImageTap()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"neutralImageTap"}],"url":"\/documentation\/divar\/raterowview\/neutralimagetap()"},"doc://com.Divar.DivarClient/documentation/Divar/RateRowView":{"role":"symbol","title":"RateRowView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RateRowView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RateRowView"}],"url":"\/documentation\/divar\/raterowview"},"doc://com.Divar.DivarClient/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAccessibilityIdentification"},"doc://com.Divar.DivarClient/documentation/Divar/Connectable":{"role":"symbol","title":"Connectable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Connectable"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Connectable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Connectable"}],"url":"\/documentation\/divar\/connectable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"RateRowView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"RateRowView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"RateRowView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/angryImageView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/emojisListImageView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/happyImageView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/neutralImageView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/sadImageView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/satisfiedImageView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/angryImageTap()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/awakeFromNib()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/happyImageTap()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/init(frame:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/neutralImageTap()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/sadImageTap()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView\/satisfiedImageTap()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"RateRowView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1emojisListImageView\/title","value":"emojisListImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1emojisListImageView\/fragments","value":[{"kind":"identifier","text":"emojisListImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1satisfiedImageTap()\/title","value":"satisfiedImageTap"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1satisfiedImageTap()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"satisfiedImageTap"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1angryImageView\/title","value":"angryImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1angryImageView\/fragments","value":[{"kind":"identifier","text":"angryImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1init(frame:)\/title","value":"initWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1sadImageView\/title","value":"sadImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1sadImageView\/fragments","value":[{"kind":"identifier","text":"sadImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1satisfiedImageView\/title","value":"satisfiedImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1satisfiedImageView\/fragments","value":[{"kind":"identifier","text":"satisfiedImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1angryImageTap()\/title","value":"angryImageTap"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1angryImageTap()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"angryImageTap"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1awakeFromNib()\/title","value":"awakeFromNib"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1awakeFromNib()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"awakeFromNib"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1neutralImageView\/title","value":"neutralImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1neutralImageView\/fragments","value":[{"kind":"identifier","text":"neutralImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1happyImageView\/title","value":"happyImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1happyImageView\/fragments","value":[{"kind":"identifier","text":"happyImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1happyImageTap()\/title","value":"happyImageTap"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1happyImageTap()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"happyImageTap"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1sadImageTap()\/title","value":"sadImageTap"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1sadImageTap()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sadImageTap"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1neutralImageTap()\/title","value":"neutralImageTap"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView~1neutralImageTap()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"neutralImageTap"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView\/title","value":"RateRowView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView\/fragments","value":[{"kind":"identifier","text":"RateRowView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}