{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RefreshableProtocol"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/refreshableprotocol"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetContactViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BusinessGetContactViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisableListViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FinalizeMarketplaceRegister","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandscapeWidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MobileZeroPriceViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyPostsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OfflinePageViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostPaymentViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SelectablePostsListViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SettingsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostDetailsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostPreviewViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedSegmentedViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RefreshableProtocol","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RefreshableProtocol\/refreshData()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RefreshableProtocol"}],"title":"RefreshableProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar19RefreshableProtocolP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"RefreshableProtocol"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController":{"role":"symbol","title":"AdvancedWidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdvancedWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdvancedWidgetViewController"}],"url":"\/documentation\/divar\/advancedwidgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostPaymentViewController":{"role":"symbol","title":"PostPaymentViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostPaymentViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostPaymentViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostPaymentViewController"}],"url":"\/documentation\/divar\/postpaymentviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/OfflinePageViewController":{"role":"symbol","title":"OfflinePageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflinePageViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OfflinePageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OfflinePageViewController"}],"url":"\/documentation\/divar\/offlinepageviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SettingsViewController":{"role":"symbol","title":"SettingsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SettingsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SettingsViewController"}],"url":"\/documentation\/divar\/settingsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MobileZeroPriceViewController":{"role":"symbol","title":"MobileZeroPriceViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MobileZeroPriceViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MobileZeroPriceViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MobileZeroPriceViewController"}],"url":"\/documentation\/divar\/mobilezeropriceviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/DisableListViewController":{"role":"symbol","title":"DisableListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisableListViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisableListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DisableListViewController"}],"url":"\/documentation\/divar\/disablelistviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BusinessGetContactViewController":{"role":"symbol","title":"BusinessGetContactViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BusinessGetContactViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BusinessGetContactViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BusinessGetContactViewController"}],"url":"\/documentation\/divar\/businessgetcontactviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/FinalizeMarketplaceRegister":{"role":"symbol","title":"FinalizeMarketplaceRegister","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FinalizeMarketplaceRegister"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FinalizeMarketplaceRegister","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FinalizeMarketplaceRegister"}],"url":"\/documentation\/divar\/finalizemarketplaceregister"},"doc://com.Divar.DivarClient/documentation/Divar/RefreshableProtocol/refreshData()":{"role":"symbol","title":"refreshData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshData"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RefreshableProtocol\/refreshData()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/refreshableprotocol\/refreshdata()"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedSegmentedViewController":{"role":"symbol","title":"WidgetBasedSegmentedViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedSegmentedViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedSegmentedViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedSegmentedViewController"}],"url":"\/documentation\/divar\/widgetbasedsegmentedviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MyPostsViewController":{"role":"symbol","title":"MyPostsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyPostsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyPostsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MyPostsViewController"}],"url":"\/documentation\/divar\/mypostsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController":{"role":"symbol","title":"ZeroPriceViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZeroPriceViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZeroPriceViewController"}],"url":"\/documentation\/divar\/zeropriceviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/RefreshableProtocol":{"role":"symbol","title":"RefreshableProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RefreshableProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RefreshableProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RefreshableProtocol"}],"url":"\/documentation\/divar\/refreshableprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController":{"role":"symbol","title":"WidgetBasedViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedViewController"}],"url":"\/documentation\/divar\/widgetbasedviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MyDivarHolderViewController":{"role":"symbol","title":"MyDivarHolderViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyDivarHolderViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MyDivarHolderViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MyDivarHolderViewController"}],"url":"\/documentation\/divar\/mydivarholderviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/LandscapeWidgetViewController":{"role":"symbol","title":"LandscapeWidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandscapeWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandscapeWidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandscapeWidgetViewController"}],"url":"\/documentation\/divar\/landscapewidgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedPostPreviewViewController":{"role":"symbol","title":"WidgetBasedPostPreviewViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedPostPreviewViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostPreviewViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedPostPreviewViewController"}],"url":"\/documentation\/divar\/widgetbasedpostpreviewviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetContactViewController":{"role":"symbol","title":"BottomSheetContactViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BottomSheetContactViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetContactViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BottomSheetContactViewController"}],"url":"\/documentation\/divar\/bottomsheetcontactviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetViewController":{"role":"symbol","title":"WidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetViewController"}],"url":"\/documentation\/divar\/widgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MessagingViewController":{"role":"symbol","title":"MessagingViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagingViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagingViewController"}],"url":"\/documentation\/divar\/messagingviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SelectablePostsListViewController":{"conformance":{"constraints":[{"type":"codeVoice","code":"SelectableItemType"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"SelectablePostsListItem"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"SelectablePostsListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SelectablePostsListViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SelectablePostsListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SelectablePostsListViewController"}],"url":"\/documentation\/divar\/selectablepostslistviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController":{"role":"symbol","title":"ChatViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatViewController"}],"url":"\/documentation\/divar\/chatviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedPostDetailsViewController":{"role":"symbol","title":"WidgetBasedPostDetailsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedPostDetailsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostDetailsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedPostDetailsViewController"}],"url":"\/documentation\/divar\/widgetbasedpostdetailsviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController\/title","value":"AdvancedWidgetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController\/fragments","value":[{"kind":"identifier","text":"AdvancedWidgetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostPaymentViewController\/title","value":"PostPaymentViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostPaymentViewController\/fragments","value":[{"kind":"identifier","text":"PostPaymentViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OfflinePageViewController\/title","value":"OfflinePageViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OfflinePageViewController\/fragments","value":[{"kind":"identifier","text":"OfflinePageViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SettingsViewController\/title","value":"SettingsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SettingsViewController\/fragments","value":[{"kind":"identifier","text":"SettingsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MobileZeroPriceViewController\/title","value":"MobileZeroPriceViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MobileZeroPriceViewController\/fragments","value":[{"kind":"identifier","text":"MobileZeroPriceViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DisableListViewController\/title","value":"DisableListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DisableListViewController\/fragments","value":[{"kind":"identifier","text":"DisableListViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BusinessGetContactViewController\/title","value":"BusinessGetContactViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BusinessGetContactViewController\/fragments","value":[{"kind":"identifier","text":"BusinessGetContactViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedSegmentedViewController\/title","value":"WidgetBasedSegmentedViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedSegmentedViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedSegmentedViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MyPostsViewController\/title","value":"MyPostsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MyPostsViewController\/fragments","value":[{"kind":"identifier","text":"MyPostsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ZeroPriceViewController\/title","value":"ZeroPriceViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ZeroPriceViewController\/fragments","value":[{"kind":"identifier","text":"ZeroPriceViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedViewController\/title","value":"WidgetBasedViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MyDivarHolderViewController\/title","value":"MyDivarHolderViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MyDivarHolderViewController\/fragments","value":[{"kind":"identifier","text":"MyDivarHolderViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandscapeWidgetViewController\/title","value":"LandscapeWidgetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandscapeWidgetViewController\/fragments","value":[{"kind":"identifier","text":"LandscapeWidgetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedPostPreviewViewController\/title","value":"WidgetBasedPostPreviewViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedPostPreviewViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedPostPreviewViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetContactViewController\/title","value":"BottomSheetContactViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetContactViewController\/fragments","value":[{"kind":"identifier","text":"BottomSheetContactViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController\/title","value":"MessagingViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagingViewController\/fragments","value":[{"kind":"identifier","text":"MessagingViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/title","value":"ChatViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/fragments","value":[{"kind":"identifier","text":"ChatViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedPostDetailsViewController\/title","value":"WidgetBasedPostDetailsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedPostDetailsViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedPostDetailsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}