{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReusableCellDequeuable"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/reusablecelldequeuable"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedCollectionView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedTableView"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ReusableCellDequeuable","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ReusableCellDequeuable\/dequeueReusableCell(for:)-91826","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ReusableCellDequeuable\/dequeueReusableCell(of:for:)-2c47b","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ReusableCellDequeuable\/unsafeDequeueReusableCell(for:)-1ikay","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ReusableCellDequeuable\/unsafeDequeueReusableCell(of:for:)-77jmw"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReusableCellDequeuable"}],"title":"ReusableCellDequeuable","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar22ReusableCellDequeuableP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"ReusableCellDequeuable"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ReusableCellDequeuable/unsafeDequeueReusableCell(of:for:)-77jmw":{"defaultImplementations":2,"role":"symbol","title":"unsafeDequeueReusableCell(of:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsafeDequeueReusableCell"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:5Divar22ReusableCellDequeuableP013unsafeDequeuebC02of3forqd__qd__m_10Foundation9IndexPathVtlF1TL_qd__mfp"},{"kind":"text","text":".Type, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:5Divar22ReusableCellDequeuableP013unsafeDequeuebC02of3forqd__qd__m_10Foundation9IndexPathVtlF1TL_qd__mfp"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ReusableCellDequeuable\/unsafeDequeueReusableCell(of:for:)-77jmw","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/reusablecelldequeuable\/unsafedequeuereusablecell(of:for:)-77jmw"},"doc://com.Divar.DivarClient/documentation/Divar/ReusableCellDequeuable/dequeueReusableCell(for:)-91826":{"defaultImplementations":2,"role":"symbol","title":"dequeueReusableCell(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dequeueReusableCell"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:5Divar22ReusableCellDequeuableP07dequeuebC03forqd__Sg10Foundation9IndexPathV_tlF1TL_qd__mfp"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ReusableCellDequeuable\/dequeueReusableCell(for:)-91826","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/reusablecelldequeuable\/dequeuereusablecell(for:)-91826"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/ReusableCellDequeuable/dequeueReusableCell(of:for:)-2c47b":{"defaultImplementations":2,"role":"symbol","title":"dequeueReusableCell(of:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dequeueReusableCell"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:5Divar22ReusableCellDequeuableP07dequeuebC02of3forqd__Sgqd__m_10Foundation9IndexPathVtlF1TL_qd__mfp"},{"kind":"text","text":".Type, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:5Divar22ReusableCellDequeuableP07dequeuebC02of3forqd__Sgqd__m_10Foundation9IndexPathVtlF1TL_qd__mfp"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ReusableCellDequeuable\/dequeueReusableCell(of:for:)-2c47b","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/reusablecelldequeuable\/dequeuereusablecell(of:for:)-2c47b"},"doc://com.Divar.DivarClient/documentation/Divar/ReusableCellDequeuable/unsafeDequeueReusableCell(for:)-1ikay":{"defaultImplementations":2,"role":"symbol","title":"unsafeDequeueReusableCell(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsafeDequeueReusableCell"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:5Divar22ReusableCellDequeuableP013unsafeDequeuebC03forqd__10Foundation9IndexPathV_tlF1TL_qd__mfp"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ReusableCellDequeuable\/unsafeDequeueReusableCell(for:)-1ikay","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/reusablecelldequeuable\/unsafedequeuereusablecell(for:)-1ikay"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedTableView":{"role":"symbol","title":"AdvancedTableView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdvancedTableView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedTableView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdvancedTableView"}],"url":"\/documentation\/divar\/advancedtableview"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedCollectionView":{"role":"symbol","title":"AdvancedCollectionView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdvancedCollectionView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedCollectionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdvancedCollectionView"}],"url":"\/documentation\/divar\/advancedcollectionview"},"doc://com.Divar.DivarClient/documentation/Divar/ReusableCellDequeuable":{"role":"symbol","title":"ReusableCellDequeuable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReusableCellDequeuable"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ReusableCellDequeuable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReusableCellDequeuable"}],"url":"\/documentation\/divar\/reusablecelldequeuable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedTableView\/title","value":"AdvancedTableView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedTableView\/fragments","value":[{"kind":"identifier","text":"AdvancedTableView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedCollectionView\/title","value":"AdvancedCollectionView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedCollectionView\/fragments","value":[{"kind":"identifier","text":"AdvancedCollectionView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}