{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SavedPostListType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/savedpostlisttype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/savedpostlisttype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/SY","doc:\/\/com.Divar.DivarClient\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType\/bookmarks","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType\/myPosts","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType\/notes","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType\/recents"]},{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType\/Equatable-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SavedPostListType"}],"title":"SavedPostListType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@Divar@E@SavedPostListType","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"SavedPostListType"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/SavedPostListType/notes":{"role":"symbol","title":"SavedPostListType.notes","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notes"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType\/notes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SavedPostListTypeNotes"}],"url":"\/documentation\/divar\/savedpostlisttype\/notes"},"doc://com.Divar.DivarClient/documentation/Divar/SavedPostListType/bookmarks":{"role":"symbol","title":"SavedPostListType.bookmarks","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bookmarks"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType\/bookmarks","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SavedPostListTypeBookmarks"}],"url":"\/documentation\/divar\/savedpostlisttype\/bookmarks"},"doc://com.Divar.DivarClient/documentation/Divar/SavedPostListType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/savedpostlisttype\/init(rawvalue:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.Divar.DivarClient\/SY"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/SavedPostListType/myPosts":{"role":"symbol","title":"SavedPostListType.myPosts","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"myPosts"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType\/myPosts","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SavedPostListTypeMyPosts"}],"url":"\/documentation\/divar\/savedpostlisttype\/myposts"},"doc://com.Divar.DivarClient/documentation/Divar/SavedPostListType":{"role":"symbol","title":"SavedPostListType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SavedPostListType"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SavedPostListType"}],"url":"\/documentation\/divar\/savedpostlisttype"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/SavedPostListType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/savedpostlisttype\/equatable-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/SavedPostListType/recents":{"role":"symbol","title":"SavedPostListType.recents","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"recents"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType\/recents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SavedPostListTypeRecents"}],"url":"\/documentation\/divar\/savedpostlisttype\/recents"},"doc://com.Divar.DivarClient/documentation/Divar/SavedPostListType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/savedpostlisttype\/rawrepresentable-implementations"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SavedPostListType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SavedPostListType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SavedPostListType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType\/bookmarks","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType\/myPosts","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType\/notes","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SavedPostListType\/recents"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SavedPostListType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SavedPostListType~1notes\/title","value":"SavedPostListTypeNotes"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SavedPostListType~1notes\/fragments","value":[{"kind":"identifier","text":"SavedPostListTypeNotes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SavedPostListType~1bookmarks\/title","value":"SavedPostListTypeBookmarks"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SavedPostListType~1bookmarks\/fragments","value":[{"kind":"identifier","text":"SavedPostListTypeBookmarks"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SavedPostListType~1myPosts\/title","value":"SavedPostListTypeMyPosts"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SavedPostListType~1myPosts\/fragments","value":[{"kind":"identifier","text":"SavedPostListTypeMyPosts"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SavedPostListType\/title","value":"SavedPostListType"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SavedPostListType\/fragments","value":[{"kind":"identifier","text":"SavedPostListType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SavedPostListType~1recents\/title","value":"SavedPostListTypeRecents"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SavedPostListType~1recents\/fragments","value":[{"kind":"identifier","text":"SavedPostListTypeRecents"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}