{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScrollingStackView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/scrollingstackview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/scrollingstackview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIScrollView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/objc(pl)CALayerDelegate","doc:\/\/com.Divar.DivarClient\/6Sonnat23WithInitializerProtocolP","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearance","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UICoordinateSpace","doc:\/\/com.Divar.DivarClient\/objc(pl)UIDynamicItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItemContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItemScrollableContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UILargeContentViewerItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/init(arrangedSubviews:axis:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/init(axis:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/init(frame:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/alignment","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/arrangedSubviews","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/axis","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/directionalLayoutMargins","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/distribution","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/isBaselineRelativeArrangement","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/isLayoutMarginsRelativeArrangement","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/layoutMargins","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/spacing","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/stackView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/addArrangedSubview(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/customSpacing(after:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/insertArrangedSubview(_:at:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/removeArrangedSubview(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/setCustomSpacing(_:after:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/spacingUseDefault","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/spacingUseSystem"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScrollingStackView"}],"title":"ScrollingStackView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)ScrollingStackView","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"ScrollingStackView"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/ScrollingStackView/layoutMargins":{"role":"symbol","title":"layoutMargins","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutMargins"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/layoutMargins","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutMargins"}],"url":"\/documentation\/divar\/scrollingstackview\/layoutmargins"},"doc://com.Divar.DivarClient/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UICoordinateSpace"},"doc://com.Divar.DivarClient/documentation/Divar/ScrollingStackView/arrangedSubviews":{"role":"symbol","title":"arrangedSubviews","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"arrangedSubviews"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/arrangedSubviews","kind":"symbol","type":"topic","url":"\/documentation\/divar\/scrollingstackview\/arrangedsubviews"},"doc://com.Divar.DivarClient/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIDynamicItem"},"doc://com.Divar.DivarClient/documentation/Divar/ScrollingStackView/addArrangedSubview(_:)":{"role":"symbol","title":"addArrangedSubview(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addArrangedSubview"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/addArrangedSubview(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/scrollingstackview\/addarrangedsubview(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/ScrollingStackView/setCustomSpacing(_:after:)":{"role":"symbol","title":"setCustomSpacing(_:after:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCustomSpacing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"after"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/setCustomSpacing(_:after:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/scrollingstackview\/setcustomspacing(_:after:)"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/documentation/Divar/ScrollingStackView/spacingUseDefault":{"role":"symbol","title":"spacingUseDefault","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"spacingUseDefault"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/spacingUseDefault","kind":"symbol","type":"topic","url":"\/documentation\/divar\/scrollingstackview\/spacingusedefault"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/ScrollingStackView/insertArrangedSubview(_:at:)":{"role":"symbol","title":"insertArrangedSubview(_:at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertArrangedSubview"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/insertArrangedSubview(_:at:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/scrollingstackview\/insertarrangedsubview(_:at:)"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)CALayerDelegate"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/objc(cs)UIScrollView":{"type":"unresolvable","title":"UIScrollView","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)UIScrollView"},"doc://com.Divar.DivarClient/documentation/Divar/ScrollingStackView/removeArrangedSubview(_:)":{"role":"symbol","title":"removeArrangedSubview(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeArrangedSubview"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/removeArrangedSubview(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/scrollingstackview\/removearrangedsubview(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/ScrollingStackView/isBaselineRelativeArrangement":{"role":"symbol","title":"isBaselineRelativeArrangement","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isBaselineRelativeArrangement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/isBaselineRelativeArrangement","kind":"symbol","type":"topic","url":"\/documentation\/divar\/scrollingstackview\/isbaselinerelativearrangement"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/ScrollingStackView/distribution":{"role":"symbol","title":"distribution","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"distribution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Distribution","preciseIdentifier":"c:@E@UIStackViewDistribution"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/distribution","kind":"symbol","type":"topic","url":"\/documentation\/divar\/scrollingstackview\/distribution"},"doc://com.Divar.DivarClient/documentation/Divar/ScrollingStackView/init(axis:)":{"role":"symbol","title":"init(axis:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"axis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Axis","preciseIdentifier":"c:@E@UILayoutConstraintAxis"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/init(axis:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/scrollingstackview\/init(axis:)"},"doc://com.Divar.DivarClient/documentation/Divar/ScrollingStackView/directionalLayoutMargins":{"role":"symbol","title":"directionalLayoutMargins","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"directionalLayoutMargins"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDirectionalEdgeInsets","preciseIdentifier":"c:@S@NSDirectionalEdgeInsets"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/directionalLayoutMargins","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"directionalLayoutMargins"}],"url":"\/documentation\/divar\/scrollingstackview\/directionallayoutmargins"},"doc://com.Divar.DivarClient/documentation/Divar/ScrollingStackView/customSpacing(after:)":{"role":"symbol","title":"customSpacing(after:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"customSpacing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"after"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/customSpacing(after:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/scrollingstackview\/customspacing(after:)"},"doc://com.Divar.DivarClient/documentation/Divar/ScrollingStackView/stackView":{"role":"symbol","title":"stackView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/stackView","kind":"symbol","type":"topic","url":"\/documentation\/divar\/scrollingstackview\/stackview"},"doc://com.Divar.DivarClient/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearance"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/ScrollingStackView/init(frame:)":{"role":"symbol","title":"init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/init(frame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/divar\/scrollingstackview\/init(frame:)"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/ScrollingStackView/isLayoutMarginsRelativeArrangement":{"role":"symbol","title":"isLayoutMarginsRelativeArrangement","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLayoutMarginsRelativeArrangement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/isLayoutMarginsRelativeArrangement","kind":"symbol","type":"topic","url":"\/documentation\/divar\/scrollingstackview\/islayoutmarginsrelativearrangement"},"doc://com.Divar.DivarClient/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItemContainer"},"doc://com.Divar.DivarClient/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItem"},"doc://com.Divar.DivarClient/objc(pl)UIFocusItemScrollableContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemScrollableContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItemScrollableContainer"},"doc://com.Divar.DivarClient/documentation/Divar/ScrollingStackView/axis":{"role":"symbol","title":"axis","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"axis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Axis","preciseIdentifier":"c:@E@UILayoutConstraintAxis"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/axis","kind":"symbol","type":"topic","url":"\/documentation\/divar\/scrollingstackview\/axis"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UILargeContentViewerItem"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/ScrollingStackView/alignment":{"role":"symbol","title":"alignment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"alignment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Alignment","preciseIdentifier":"c:@E@UIStackViewAlignment"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/alignment","kind":"symbol","type":"topic","url":"\/documentation\/divar\/scrollingstackview\/alignment"},"doc://com.Divar.DivarClient/documentation/Divar/ScrollingStackView/spacingUseSystem":{"role":"symbol","title":"spacingUseSystem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"spacingUseSystem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/spacingUseSystem","kind":"symbol","type":"topic","url":"\/documentation\/divar\/scrollingstackview\/spacingusesystem"},"doc://com.Divar.DivarClient/documentation/Divar/ScrollingStackView/init(arrangedSubviews:axis:)":{"role":"symbol","title":"init(arrangedSubviews:axis:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"arrangedSubviews"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"axis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Axis","preciseIdentifier":"c:@E@UILayoutConstraintAxis"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/init(arrangedSubviews:axis:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/scrollingstackview\/init(arrangedsubviews:axis:)"},"doc://com.Divar.DivarClient/documentation/Divar/ScrollingStackView/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/scrollingstackview\/init(coder:)"},"doc://com.Divar.DivarClient/documentation/Divar/ScrollingStackView/spacing":{"role":"symbol","title":"spacing","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"spacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/spacing","kind":"symbol","type":"topic","url":"\/documentation\/divar\/scrollingstackview\/spacing"},"doc://com.Divar.DivarClient/6Sonnat23WithInitializerProtocolP":{"type":"unresolvable","title":"Sonnat.WithInitializerProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat23WithInitializerProtocolP"},"doc://com.Divar.DivarClient/documentation/Divar/ScrollingStackView":{"role":"symbol","title":"ScrollingStackView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScrollingStackView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScrollingStackView"}],"url":"\/documentation\/divar\/scrollingstackview"},"doc://com.Divar.DivarClient/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAccessibilityIdentification"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ScrollingStackView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ScrollingStackView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ScrollingStackView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/directionalLayoutMargins","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/layoutMargins"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/init(frame:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIScrollView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScrollingStackView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScrollingStackView~1layoutMargins\/title","value":"layoutMargins"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScrollingStackView~1layoutMargins\/fragments","value":[{"kind":"identifier","text":"layoutMargins"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScrollingStackView~1directionalLayoutMargins\/title","value":"directionalLayoutMargins"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScrollingStackView~1directionalLayoutMargins\/fragments","value":[{"kind":"identifier","text":"directionalLayoutMargins"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScrollingStackView~1init(frame:)\/title","value":"initWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScrollingStackView~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScrollingStackView~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScrollingStackView~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScrollingStackView\/title","value":"ScrollingStackView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScrollingStackView\/fragments","value":[{"kind":"identifier","text":"ScrollingStackView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}