{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleHierarchyBaseController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/singlehierarchybasecontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/singlehierarchybasecontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CategoryHierarchyController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ComponentProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Searchable","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","doc:\/\/com.Divar.DivarClient\/6Sonnat17SearchBoxDelegateP","doc:\/\/com.Divar.DivarClient\/6Sonnat21SuggestionRowProtocolP","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIScrollViewDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDataSource","doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/init(container:property:hierarchyData:type:header:suggestion:legendPayload:shortcutChildren:prevoiuseSuggestionItems:previousSources:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/hierarchyData","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/isSearchActive","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/legendTitlePayload","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/mainHierarchyData","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/onDismissCallback","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/previousSources","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/prevoiuseSuggestionItems","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/property","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/searchBox","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/shortcutChildren","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/suggestion","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/tableView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/type","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/viewState-swift.property"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/brandDidSelect(item:source:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/createCategoryCell(indexPath:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/createShortcutCell(indexPath:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/createSuggestionCell(indexPath:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/findShortCut(data:shortCut:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/registerCell()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/search(with:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/setupSearchController()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/setupTableView()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/viewDidLoad()"]},{"title":"Enumerations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/HierarchyType","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/ViewState-swift.enum"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/SearchBoxDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/SuggestionRowProtocol-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/UITableViewDataSource-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/UITableViewDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleHierarchyBaseController"}],"title":"SingleHierarchyBaseController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)SingleHierarchyBaseController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"SingleHierarchyBaseController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ErrorMessageHandler":{"role":"symbol","title":"ErrorMessageHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorMessageHandler"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorMessageHandler"}],"url":"\/documentation\/divar\/errormessagehandler"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/hierarchyData":{"role":"symbol","title":"hierarchyData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hierarchyData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIOptionsDataStruct","preciseIdentifier":"s:5Divar19UIOptionsDataStructV"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/hierarchyData","kind":"symbol","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/hierarchydata"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/UITableViewDelegate-Implementations":{"role":"collectionGroup","title":"UITableViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/UITableViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/uitableviewdelegate-implementations"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HierarchyType","preciseIdentifier":"s:5Divar29SingleHierarchyBaseControllerC0C4TypeO"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/type","kind":"symbol","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/type"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/search(with:)":{"role":"symbol","title":"search(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"search"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/search(with:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/search(with:)"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/findShortCut(data:shortCut:)":{"role":"symbol","title":"findShortCut(data:shortCut:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"findShortCut"},{"kind":"text","text":"("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIOptionsDataStruct","preciseIdentifier":"s:5Divar19UIOptionsDataStructV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shortCut"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIOptionBrandShortcut","preciseIdentifier":"s:5Divar21UIOptionBrandShortcutV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIOptionsDataStruct","preciseIdentifier":"s:5Divar19UIOptionsDataStructV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/findShortCut(data:shortCut:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/findshortcut(data:shortcut:)"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/legendTitlePayload":{"role":"symbol","title":"legendTitlePayload","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"legendTitlePayload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIOptionLegendTitle","preciseIdentifier":"s:5Divar19UIOptionLegendTitleV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/legendTitlePayload","kind":"symbol","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/legendtitlepayload"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/property":{"role":"symbol","title":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"property"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/property","kind":"symbol","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/property"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/singlehierarchybasecontroller\/init(coder:)"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/createSuggestionCell(indexPath:)":{"role":"symbol","title":"createSuggestionCell(indexPath:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createSuggestionCell"},{"kind":"text","text":"("},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/createSuggestionCell(indexPath:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/createsuggestioncell(indexpath:)"},"doc://com.Divar.DivarClient/documentation/Divar/ShowErrorProtocol":{"role":"symbol","title":"ShowErrorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowErrorProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowErrorProtocol"}],"url":"\/documentation\/divar\/showerrorprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/createCategoryCell(indexPath:)":{"role":"symbol","title":"createCategoryCell(indexPath:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createCategoryCell"},{"kind":"text","text":"("},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/createCategoryCell(indexPath:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/createcategorycell(indexpath:)"},"doc://com.Divar.DivarClient/documentation/Divar/CategoryHierarchyController":{"role":"symbol","title":"CategoryHierarchyController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CategoryHierarchyController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CategoryHierarchyController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CategoryHierarchyController"}],"url":"\/documentation\/divar\/categoryhierarchycontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/setupTableView()":{"role":"symbol","title":"setupTableView()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupTableView"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/setupTableView()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/setuptableview()"},"doc://com.Divar.DivarClient/documentation/Divar/TooltipPresenter":{"role":"symbol","title":"TooltipPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TooltipPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TooltipPresenter"}],"url":"\/documentation\/divar\/tooltippresenter"},"doc://com.Divar.DivarClient/objc(pl)UITableViewDataSource":{"type":"unresolvable","title":"UIKit.UITableViewDataSource","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDataSource"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/UITableViewDataSource-Implementations":{"role":"collectionGroup","title":"UITableViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/UITableViewDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/uitableviewdatasource-implementations"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/6Sonnat17SearchBoxDelegateP":{"type":"unresolvable","title":"Sonnat.SearchBoxDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat17SearchBoxDelegateP"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/init(container:property:hierarchyData:type:header:suggestion:legendPayload:shortcutChildren:prevoiuseSuggestionItems:previousSources:)":{"role":"symbol","title":"init(container:property:hierarchyData:type:header:suggestion:legendPayload:shortcutChildren:prevoiuseSuggestionItems:previousSources:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SingleHierarchyBaseControllerDIContainer","preciseIdentifier":"s:5Divar40SingleHierarchyBaseControllerDIContainera"},{"kind":"text","text":", "},{"kind":"externalParam","text":"property"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"hierarchyData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIOptionsDataStruct","preciseIdentifier":"s:5Divar19UIOptionsDataStructV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HierarchyType","preciseIdentifier":"s:5Divar29SingleHierarchyBaseControllerC0C4TypeO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"header"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"suggestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIOptionBrandSuggestion","preciseIdentifier":"s:5Divar23UIOptionBrandSuggestionV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"legendPayload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIOptionLegendTitle","preciseIdentifier":"s:5Divar19UIOptionLegendTitleV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"shortcutChildren"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIOptionBrandShortcut","preciseIdentifier":"s:5Divar21UIOptionBrandShortcutV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"prevoiuseSuggestionItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIOptionSuggestionItem","preciseIdentifier":"s:5Divar22UIOptionSuggestionItemV"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"previousSources"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ActionLog_SingleSelectedHierarchyItemSelectionActionInfo","preciseIdentifier":"s:19DivarInterfaceSwift046ActionLog_SingleSelectedHierarchyItemSelectionD4InfoV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Source","preciseIdentifier":"s:19DivarInterfaceSwift046ActionLog_SingleSelectedHierarchyItemSelectionD4InfoV6SourceO"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/init(container:property:hierarchyData:type:header:suggestion:legendPayload:shortcutChildren:prevoiuseSuggestionItems:previousSources:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/init(container:property:hierarchydata:type:header:suggestion:legendpayload:shortcutchildren:prevoiusesuggestionitems:previoussources:)"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/isSearchActive":{"role":"symbol","title":"isSearchActive","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSearchActive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/isSearchActive","kind":"symbol","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/issearchactive"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/prevoiuseSuggestionItems":{"role":"symbol","title":"prevoiuseSuggestionItems","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prevoiuseSuggestionItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIOptionSuggestionItem","preciseIdentifier":"s:5Divar22UIOptionSuggestionItemV"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/prevoiuseSuggestionItems","kind":"symbol","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/prevoiusesuggestionitems"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/createShortcutCell(indexPath:)":{"role":"symbol","title":"createShortcutCell(indexPath:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createShortcutCell"},{"kind":"text","text":"("},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/createShortcutCell(indexPath:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/createshortcutcell(indexpath:)"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/brandDidSelect(item:source:)":{"role":"symbol","title":"brandDidSelect(item:source:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"brandDidSelect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIOptionsDataStruct","preciseIdentifier":"s:5Divar19UIOptionsDataStructV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActionLog_SingleSelectedHierarchyItemSelectionActionInfo","preciseIdentifier":"s:19DivarInterfaceSwift046ActionLog_SingleSelectedHierarchyItemSelectionD4InfoV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Source","preciseIdentifier":"s:19DivarInterfaceSwift046ActionLog_SingleSelectedHierarchyItemSelectionD4InfoV6SourceO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/brandDidSelect(item:source:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/branddidselect(item:source:)"},"doc://com.Divar.DivarClient/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIScrollViewDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/onDismissCallback":{"role":"symbol","title":"onDismissCallback","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDismissCallback"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/onDismissCallback","kind":"symbol","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/ondismisscallback"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController":{"role":"symbol","title":"SingleHierarchyBaseController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleHierarchyBaseController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SingleHierarchyBaseController"}],"url":"\/documentation\/divar\/singlehierarchybasecontroller"},"doc://com.Divar.DivarClient/objc(pl)UITableViewDelegate":{"type":"unresolvable","title":"UIKit.UITableViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDelegate"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/Searchable":{"role":"symbol","title":"Searchable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Searchable"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Searchable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Searchable"}],"url":"\/documentation\/divar\/searchable"},"doc://com.Divar.DivarClient/documentation/Divar/ShowMessageProtocol":{"role":"symbol","title":"ShowMessageProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowMessageProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowMessageProtocol"}],"url":"\/documentation\/divar\/showmessageprotocol"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/registerCell()":{"role":"symbol","title":"registerCell()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerCell"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/registerCell()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/registercell()"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/previousSources":{"role":"symbol","title":"previousSources","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previousSources"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ActionLog_SingleSelectedHierarchyItemSelectionActionInfo","preciseIdentifier":"s:19DivarInterfaceSwift046ActionLog_SingleSelectedHierarchyItemSelectionD4InfoV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Source","preciseIdentifier":"s:19DivarInterfaceSwift046ActionLog_SingleSelectedHierarchyItemSelectionD4InfoV6SourceO"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/previousSources","kind":"symbol","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/previoussources"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/SuggestionRowProtocol-Implementations":{"role":"collectionGroup","title":"SuggestionRowProtocol Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/SuggestionRowProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/suggestionrowprotocol-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/mainHierarchyData":{"role":"symbol","title":"mainHierarchyData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mainHierarchyData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIOptionsDataStruct","preciseIdentifier":"s:5Divar19UIOptionsDataStructV"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/mainHierarchyData","kind":"symbol","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/mainhierarchydata"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/shortcutChildren":{"role":"symbol","title":"shortcutChildren","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shortcutChildren"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIOptionsDataStruct","preciseIdentifier":"s:5Divar19UIOptionsDataStructV"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/shortcutChildren","kind":"symbol","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/shortcutchildren"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/viewState-swift.property":{"role":"symbol","title":"viewState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ViewState","preciseIdentifier":"s:5Divar29SingleHierarchyBaseControllerC9ViewStateO"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/viewState-swift.property","kind":"symbol","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/viewstate-swift.property"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/singlehierarchybasecontroller\/viewdidload()"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/searchBox":{"role":"symbol","title":"searchBox","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBox"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchBox","preciseIdentifier":"c:@M@Sonnat@objc(cs)SearchBox"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/searchBox","kind":"symbol","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/searchbox"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/SearchBoxDelegate-Implementations":{"role":"collectionGroup","title":"SearchBoxDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/SearchBoxDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/searchboxdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/setupSearchController()":{"role":"symbol","title":"setupSearchController()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupSearchController"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/setupSearchController()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/setupsearchcontroller()"},"doc://com.Divar.DivarClient/6Sonnat21SuggestionRowProtocolP":{"type":"unresolvable","title":"Sonnat.SuggestionRowProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat21SuggestionRowProtocolP"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyController":{"role":"symbol","title":"SingleHierarchyController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleHierarchyController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SingleHierarchyController"}],"url":"\/documentation\/divar\/singlehierarchycontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/ViewState-swift.enum":{"role":"symbol","title":"SingleHierarchyBaseController.ViewState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewState"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/ViewState-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ViewState"}],"url":"\/documentation\/divar\/singlehierarchybasecontroller\/viewstate-swift.enum"},"doc://com.Divar.DivarClient/documentation/Divar/ComponentProtocol":{"role":"symbol","title":"ComponentProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComponentProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ComponentProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ComponentProtocol"}],"url":"\/documentation\/divar\/componentprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/tableView":{"role":"symbol","title":"tableView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/tableView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView"}],"url":"\/documentation\/divar\/singlehierarchybasecontroller\/tableview"},"doc://com.Divar.DivarClient/documentation/Divar/PaymentSystemProtocol":{"role":"symbol","title":"PaymentSystemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSystemProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaymentSystemProtocol"}],"url":"\/documentation\/divar\/paymentsystemprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController":{"role":"symbol","title":"BaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseViewController"}],"url":"\/documentation\/divar\/baseviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/suggestion":{"role":"symbol","title":"suggestion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"suggestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIOptionBrandSuggestion","preciseIdentifier":"s:5Divar23UIOptionBrandSuggestionV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/suggestion","kind":"symbol","type":"topic","url":"\/documentation\/divar\/singlehierarchybasecontroller\/suggestion"},"doc://com.Divar.DivarClient/documentation/Divar/SingleHierarchyBaseController/HierarchyType":{"role":"symbol","title":"SingleHierarchyBaseController.HierarchyType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HierarchyType"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/HierarchyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HierarchyType"}],"url":"\/documentation\/divar\/singlehierarchybasecontroller\/hierarchytype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SingleHierarchyBaseController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SingleHierarchyBaseController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SingleHierarchyBaseController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/tableView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/UITableViewDataSource-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyBaseController\/UITableViewDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CategoryHierarchyController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SingleHierarchyController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleHierarchyBaseController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController","preciseIdentifier":"c:@M@Divar@objc(cs)BaseViewController","text":"BaseViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleHierarchyBaseController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleHierarchyBaseController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CategoryHierarchyController\/title","value":"CategoryHierarchyController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CategoryHierarchyController\/fragments","value":[{"kind":"identifier","text":"CategoryHierarchyController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleHierarchyBaseController\/title","value":"SingleHierarchyBaseController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleHierarchyBaseController\/fragments","value":[{"kind":"identifier","text":"SingleHierarchyBaseController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleHierarchyBaseController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleHierarchyBaseController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleHierarchyController\/title","value":"SingleHierarchyController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleHierarchyController\/fragments","value":[{"kind":"identifier","text":"SingleHierarchyController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleHierarchyBaseController~1tableView\/title","value":"tableView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SingleHierarchyBaseController~1tableView\/fragments","value":[{"kind":"identifier","text":"tableView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController\/title","value":"BaseViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController\/fragments","value":[{"kind":"identifier","text":"BaseViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}