{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SwitchTableViewCellDelegate"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/switchtableviewcelldelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatSettingsController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SwitchTableViewCellDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SwitchTableViewCellDelegate\/switchCell(_:switchValueDidChange:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SwitchTableViewCellDelegate"}],"title":"SwitchTableViewCellDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar27SwitchTableViewCellDelegateP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"SwitchTableViewCellDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/SwitchTableViewCellDelegate/switchCell(_:switchValueDidChange:)":{"role":"symbol","title":"switchCell(_:switchValueDidChange:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchCell"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SwitchTableViewCell","preciseIdentifier":"c:@M@Divar@objc(cs)SwitchTableViewCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"switchValueDidChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SwitchTableViewCellDelegate\/switchCell(_:switchValueDidChange:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/switchtableviewcelldelegate\/switchcell(_:switchvaluedidchange:)"},"doc://com.Divar.DivarClient/documentation/Divar/SwitchTableViewCellDelegate":{"role":"symbol","title":"SwitchTableViewCellDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SwitchTableViewCellDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SwitchTableViewCellDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SwitchTableViewCellDelegate"}],"url":"\/documentation\/divar\/switchtableviewcelldelegate"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController":{"role":"symbol","title":"TransformablePriceViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransformablePriceViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TransformablePriceViewController"}],"url":"\/documentation\/divar\/transformablepriceviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatSettingsController":{"role":"symbol","title":"ChatSettingsController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatSettingsController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatSettingsController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatSettingsController"}],"url":"\/documentation\/divar\/chatsettingscontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TransformablePriceViewController\/title","value":"TransformablePriceViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TransformablePriceViewController\/fragments","value":[{"kind":"identifier","text":"TransformablePriceViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatSettingsController\/title","value":"ChatSettingsController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatSettingsController\/fragments","value":[{"kind":"identifier","text":"ChatSettingsController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}