{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListMultilineFlowLayout"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/taglistmultilineflowlayout"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/taglistmultilineflowlayout"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UICollectionViewFlowLayout"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/cellHeight","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/cellSpacing","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/flipsHorizontallyInOppositeLayoutDirection","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/marginX","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/paddingX","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/paddingY","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/previousSize","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/textFont"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/awakeFromNib()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/layoutAttributesForElements(in:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/prepare()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListMultilineFlowLayout"}],"title":"TagListMultilineFlowLayout","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)TagListMultilineFlowLayout","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"TagListMultilineFlowLayout"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/TagListMultilineFlowLayout/marginX":{"role":"symbol","title":"marginX","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"marginX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/marginX","kind":"symbol","type":"topic","url":"\/documentation\/divar\/taglistmultilineflowlayout\/marginx"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/TagListMultilineFlowLayout/previousSize":{"role":"symbol","title":"previousSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previousSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/previousSize","kind":"symbol","type":"topic","url":"\/documentation\/divar\/taglistmultilineflowlayout\/previoussize"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/TagListMultilineFlowLayout/paddingY":{"role":"symbol","title":"paddingY","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paddingY"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/paddingY","kind":"symbol","type":"topic","url":"\/documentation\/divar\/taglistmultilineflowlayout\/paddingy"},"doc://com.Divar.DivarClient/documentation/Divar/TagListMultilineFlowLayout":{"role":"symbol","title":"TagListMultilineFlowLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListMultilineFlowLayout"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagListMultilineFlowLayout"}],"url":"\/documentation\/divar\/taglistmultilineflowlayout"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/documentation/Divar/TagListMultilineFlowLayout/layoutAttributesForElements(in:)":{"role":"symbol","title":"layoutAttributesForElements(in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutAttributesForElements"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"UICollectionViewLayoutAttributes","preciseIdentifier":"c:objc(cs)UICollectionViewLayoutAttributes"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/layoutAttributesForElements(in:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutAttributesForElementsInRect:"}],"url":"\/documentation\/divar\/taglistmultilineflowlayout\/layoutattributesforelements(in:)"},"doc://com.Divar.DivarClient/documentation/Divar/TagListMultilineFlowLayout/awakeFromNib()":{"role":"symbol","title":"awakeFromNib()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/awakeFromNib()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"awakeFromNib"}],"url":"\/documentation\/divar\/taglistmultilineflowlayout\/awakefromnib()"},"doc://com.Divar.DivarClient/documentation/Divar/TagListMultilineFlowLayout/cellHeight":{"role":"symbol","title":"cellHeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/cellHeight","kind":"symbol","type":"topic","url":"\/documentation\/divar\/taglistmultilineflowlayout\/cellheight"},"doc://com.Divar.DivarClient/documentation/Divar/TagListMultilineFlowLayout/cellSpacing":{"role":"symbol","title":"cellSpacing","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellSpacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/cellSpacing","kind":"symbol","type":"topic","url":"\/documentation\/divar\/taglistmultilineflowlayout\/cellspacing"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/TagListMultilineFlowLayout/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/taglistmultilineflowlayout\/initwithcoder:"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/TagListMultilineFlowLayout/paddingX":{"role":"symbol","title":"paddingX","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paddingX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/paddingX","kind":"symbol","type":"topic","url":"\/documentation\/divar\/taglistmultilineflowlayout\/paddingx"},"doc://com.Divar.DivarClient/objc(cs)UICollectionViewFlowLayout":{"type":"unresolvable","title":"UICollectionViewFlowLayout","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)UICollectionViewFlowLayout"},"doc://com.Divar.DivarClient/documentation/Divar/TagListMultilineFlowLayout/flipsHorizontallyInOppositeLayoutDirection":{"role":"symbol","title":"flipsHorizontallyInOppositeLayoutDirection","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"flipsHorizontallyInOppositeLayoutDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/flipsHorizontallyInOppositeLayoutDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"flipsHorizontallyInOppositeLayoutDirection"}],"url":"\/documentation\/divar\/taglistmultilineflowlayout\/flipshorizontallyinoppositelayoutdirection"},"doc://com.Divar.DivarClient/documentation/Divar/TagListMultilineFlowLayout/prepare()":{"role":"symbol","title":"prepare()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepare"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/prepare()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prepareLayout"}],"url":"\/documentation\/divar\/taglistmultilineflowlayout\/prepare()"},"doc://com.Divar.DivarClient/documentation/Divar/TagListMultilineFlowLayout/textFont":{"role":"symbol","title":"textFont","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/textFont","kind":"symbol","type":"topic","url":"\/documentation\/divar\/taglistmultilineflowlayout\/textfont"},"doc://com.Divar.DivarClient/documentation/Divar/TagListMultilineFlowLayout/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/divar\/taglistmultilineflowlayout\/init"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TagListMultilineFlowLayout"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TagListMultilineFlowLayout"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TagListMultilineFlowLayout"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/flipsHorizontallyInOppositeLayoutDirection"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/awakeFromNib()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/init","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/initWithCoder:","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/layoutAttributesForElements(in:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListMultilineFlowLayout\/prepare()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UICollectionViewFlowLayout"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListMultilineFlowLayout"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UICollectionViewFlowLayout","preciseIdentifier":"c:objc(cs)UICollectionViewFlowLayout"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListMultilineFlowLayout\/title","value":"TagListMultilineFlowLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListMultilineFlowLayout\/fragments","value":[{"kind":"identifier","text":"TagListMultilineFlowLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListMultilineFlowLayout~1layoutAttributesForElements(in:)\/title","value":"layoutAttributesForElementsInRect:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListMultilineFlowLayout~1layoutAttributesForElements(in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutAttributesForElementsInRect:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListMultilineFlowLayout~1awakeFromNib()\/title","value":"awakeFromNib"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListMultilineFlowLayout~1awakeFromNib()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"awakeFromNib"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListMultilineFlowLayout~1flipsHorizontallyInOppositeLayoutDirection\/title","value":"flipsHorizontallyInOppositeLayoutDirection"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListMultilineFlowLayout~1flipsHorizontallyInOppositeLayoutDirection\/fragments","value":[{"kind":"identifier","text":"flipsHorizontallyInOppositeLayoutDirection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListMultilineFlowLayout~1prepare()\/title","value":"prepareLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListMultilineFlowLayout~1prepare()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareLayout"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}