{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListDelegateAndDataSource"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/taglistdelegateanddatasource"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/taglistdelegateanddatasource"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/objc(pl)UICollectionViewDataSource","doc:\/\/com.Divar.DivarClient\/objc(pl)UICollectionViewDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UICollectionViewDelegateFlowLayout","doc:\/\/com.Divar.DivarClient\/objc(pl)UIScrollViewDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListDelegateAndDataSource","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListDelegateAndDataSource\/init(with:cellFont:isMultiline:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListDelegateAndDataSource\/list","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListDelegateAndDataSource\/marginX","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListDelegateAndDataSource\/paddingX","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListDelegateAndDataSource\/paddingY"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListDelegateAndDataSource\/collectionView(_:cellForItemAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListDelegateAndDataSource\/collectionView(_:layout:sizeForItemAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListDelegateAndDataSource\/collectionView(_:numberOfItemsInSection:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListDelegateAndDataSource"}],"title":"TagListDelegateAndDataSource","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)TagListDelegateAndDataSource","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"TagListDelegateAndDataSource"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIScrollViewDelegate"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/TagListDelegateAndDataSource/paddingY":{"role":"symbol","title":"paddingY","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"paddingY"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListDelegateAndDataSource\/paddingY","kind":"symbol","type":"topic","url":"\/documentation\/divar\/taglistdelegateanddatasource\/paddingy"},"doc://com.Divar.DivarClient/documentation/Divar/TagListDelegateAndDataSource/paddingX":{"role":"symbol","title":"paddingX","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"paddingX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListDelegateAndDataSource\/paddingX","kind":"symbol","type":"topic","url":"\/documentation\/divar\/taglistdelegateanddatasource\/paddingx"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/TagListDelegateAndDataSource/collectionView(_:cellForItemAt:)":{"role":"symbol","title":"collectionView(_:cellForItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellForItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListDelegateAndDataSource\/collectionView(_:cellForItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}],"url":"\/documentation\/divar\/taglistdelegateanddatasource\/collectionview(_:cellforitemat:)"},"doc://com.Divar.DivarClient/documentation/Divar/TagListDelegateAndDataSource/init(with:cellFont:isMultiline:)":{"role":"symbol","title":"init(with:cellFont:isMultiline:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isMultiline"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListDelegateAndDataSource\/init(with:cellFont:isMultiline:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/taglistdelegateanddatasource\/init(with:cellfont:ismultiline:)"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/objc(pl)UICollectionViewDelegate":{"type":"unresolvable","title":"UIKit.UICollectionViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UICollectionViewDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/TagListDelegateAndDataSource/list":{"role":"symbol","title":"list","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"list"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Base_Tag","preciseIdentifier":"s:19DivarInterfaceSwift8Base_TagV"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListDelegateAndDataSource\/list","kind":"symbol","type":"topic","url":"\/documentation\/divar\/taglistdelegateanddatasource\/list"},"doc://com.Divar.DivarClient/documentation/Divar/TagListDelegateAndDataSource/collectionView(_:numberOfItemsInSection:)":{"role":"symbol","title":"collectionView(_:numberOfItemsInSection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfItemsInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListDelegateAndDataSource\/collectionView(_:numberOfItemsInSection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:numberOfItemsInSection:"}],"url":"\/documentation\/divar\/taglistdelegateanddatasource\/collectionview(_:numberofitemsinsection:)"},"doc://com.Divar.DivarClient/documentation/Divar/TagListDelegateAndDataSource/marginX":{"role":"symbol","title":"marginX","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"marginX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListDelegateAndDataSource\/marginX","kind":"symbol","type":"topic","url":"\/documentation\/divar\/taglistdelegateanddatasource\/marginx"},"doc://com.Divar.DivarClient/objc(pl)UICollectionViewDataSource":{"type":"unresolvable","title":"UICollectionViewDataSource","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UICollectionViewDataSource"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/TagListDelegateAndDataSource/collectionView(_:layout:sizeForItemAt:)":{"role":"symbol","title":"collectionView(_:layout:sizeForItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sizeForItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListDelegateAndDataSource\/collectionView(_:layout:sizeForItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:layout:sizeForItemAtIndexPath:"}],"url":"\/documentation\/divar\/taglistdelegateanddatasource\/collectionview(_:layout:sizeforitemat:)"},"doc://com.Divar.DivarClient/documentation/Divar/TagListDelegateAndDataSource":{"role":"symbol","title":"TagListDelegateAndDataSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListDelegateAndDataSource"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListDelegateAndDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagListDelegateAndDataSource"}],"url":"\/documentation\/divar\/taglistdelegateanddatasource"},"doc://com.Divar.DivarClient/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"},"doc://com.Divar.DivarClient/objc(pl)UICollectionViewDelegateFlowLayout":{"type":"unresolvable","title":"UICollectionViewDelegateFlowLayout","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UICollectionViewDelegateFlowLayout"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TagListDelegateAndDataSource"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TagListDelegateAndDataSource"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TagListDelegateAndDataSource"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListDelegateAndDataSource\/collectionView(_:cellForItemAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListDelegateAndDataSource\/collectionView(_:layout:sizeForItemAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListDelegateAndDataSource\/collectionView(_:numberOfItemsInSection:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)UICollectionViewDataSource","doc:\/\/com.Divar.DivarClient\/objc(pl)UICollectionViewDelegateFlowLayout"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListDelegateAndDataSource"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListDelegateAndDataSource~1collectionView(_:cellForItemAt:)\/title","value":"collectionView:cellForItemAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListDelegateAndDataSource~1collectionView(_:cellForItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListDelegateAndDataSource~1collectionView(_:numberOfItemsInSection:)\/title","value":"collectionView:numberOfItemsInSection:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListDelegateAndDataSource~1collectionView(_:numberOfItemsInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:numberOfItemsInSection:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListDelegateAndDataSource~1collectionView(_:layout:sizeForItemAt:)\/title","value":"collectionView:layout:sizeForItemAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListDelegateAndDataSource~1collectionView(_:layout:sizeForItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:layout:sizeForItemAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListDelegateAndDataSource\/title","value":"TagListDelegateAndDataSource"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListDelegateAndDataSource\/fragments","value":[{"kind":"identifier","text":"TagListDelegateAndDataSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}