{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListViewControllerDelegate"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/taglistviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BrandMultiHierarchyViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CityMultiSelectViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FinalizeMarketplaceRegister","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GeneralBulkLadderViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandscapeWidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDistrictSelectorViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListViewControllerDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListViewControllerDelegate\/tagDidSelect(tag:index:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListViewControllerDelegate\/taglistCell(_:tag:didRemoveItemAtIndex:)-4668t"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListViewControllerDelegate"}],"title":"TagListViewControllerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar29TagListViewControllerDelegateP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"TagListViewControllerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/GeneralBulkLadderViewController":{"conformance":{"constraints":[{"type":"codeVoice","code":"PageResponseType"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"_Extractor"},{"type":"text","text":", "},{"type":"codeVoice","code":"PageResponseType"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Message"},{"type":"text","text":", "},{"type":"codeVoice","code":"SubmitResponseType"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"_Extractor"},{"type":"text","text":", and "},{"type":"codeVoice","code":"SubmitResponseType"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Message"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"GeneralBulkLadderViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeneralBulkLadderViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GeneralBulkLadderViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GeneralBulkLadderViewController"}],"url":"\/documentation\/divar\/generalbulkladderviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/LandscapeWidgetViewController":{"role":"symbol","title":"LandscapeWidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandscapeWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandscapeWidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandscapeWidgetViewController"}],"url":"\/documentation\/divar\/landscapewidgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/TagListViewControllerDelegate/taglistCell(_:tag:didRemoveItemAtIndex:)-4668t":{"defaultImplementations":1,"role":"symbol","title":"taglistCell(_:tag:didRemoveItemAtIndex:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"taglistCell"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TagListCell","preciseIdentifier":"c:@M@Divar@objc(cs)TagListCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagListItem","preciseIdentifier":"s:5Divar11TagListItemP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRemoveItemAtIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListViewControllerDelegate\/taglistCell(_:tag:didRemoveItemAtIndex:)-4668t","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/taglistviewcontrollerdelegate\/taglistcell(_:tag:didremoveitematindex:)-4668t"},"doc://com.Divar.DivarClient/documentation/Divar/ChatViewController":{"role":"symbol","title":"ChatViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatViewController"}],"url":"\/documentation\/divar\/chatviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/FinalizeMarketplaceRegister":{"role":"symbol","title":"FinalizeMarketplaceRegister","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FinalizeMarketplaceRegister"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FinalizeMarketplaceRegister","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FinalizeMarketplaceRegister"}],"url":"\/documentation\/divar\/finalizemarketplaceregister"},"doc://com.Divar.DivarClient/documentation/Divar/CityMultiSelectViewController":{"role":"symbol","title":"CityMultiSelectViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CityMultiSelectViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CityMultiSelectViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CityMultiSelectViewController"}],"url":"\/documentation\/divar\/citymultiselectviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetViewController":{"conformance":{"constraints":[{"type":"codeVoice","code":"ResponseType"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"_Extractor"},{"type":"text","text":" and "},{"type":"codeVoice","code":"Message"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"WidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetViewController"}],"url":"\/documentation\/divar\/widgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController":{"role":"symbol","title":"AdvancedWidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdvancedWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdvancedWidgetViewController"}],"url":"\/documentation\/divar\/advancedwidgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MapDistrictSelectorViewController":{"role":"symbol","title":"MapDistrictSelectorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapDistrictSelectorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapDistrictSelectorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapDistrictSelectorViewController"}],"url":"\/documentation\/divar\/mapdistrictselectorviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/TagListViewControllerDelegate/tagDidSelect(tag:index:)":{"role":"symbol","title":"tagDidSelect(tag:index:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagDidSelect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagListItem","preciseIdentifier":"s:5Divar11TagListItemP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListViewControllerDelegate\/tagDidSelect(tag:index:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/taglistviewcontrollerdelegate\/tagdidselect(tag:index:)"},"doc://com.Divar.DivarClient/documentation/Divar/BrandMultiHierarchyViewController":{"role":"symbol","title":"BrandMultiHierarchyViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrandMultiHierarchyViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BrandMultiHierarchyViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BrandMultiHierarchyViewController"}],"url":"\/documentation\/divar\/brandmultihierarchyviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/TagListViewControllerDelegate":{"role":"symbol","title":"TagListViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagListViewControllerDelegate"}],"url":"\/documentation\/divar\/taglistviewcontrollerdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandscapeWidgetViewController\/title","value":"LandscapeWidgetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandscapeWidgetViewController\/fragments","value":[{"kind":"identifier","text":"LandscapeWidgetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/title","value":"ChatViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChatViewController\/fragments","value":[{"kind":"identifier","text":"ChatViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CityMultiSelectViewController\/title","value":"CityMultiSelectViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CityMultiSelectViewController\/fragments","value":[{"kind":"identifier","text":"CityMultiSelectViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController\/title","value":"AdvancedWidgetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController\/fragments","value":[{"kind":"identifier","text":"AdvancedWidgetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDistrictSelectorViewController\/title","value":"MapDistrictSelectorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapDistrictSelectorViewController\/fragments","value":[{"kind":"identifier","text":"MapDistrictSelectorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BrandMultiHierarchyViewController\/title","value":"BrandMultiHierarchyViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BrandMultiHierarchyViewController\/fragments","value":[{"kind":"identifier","text":"BrandMultiHierarchyViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}