{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextFieldViewDelegate"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/textfieldviewdelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberInputViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldHintView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldViewDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldViewDelegate\/textFieldDidChangeSelection(_:)-6lotc","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldViewDelegate\/textFieldValueChanges(_:shouldChangeCharactersIn:replacementString:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextFieldViewDelegate"}],"title":"TextFieldViewDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar21TextFieldViewDelegateP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"TextFieldViewDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/TextFieldViewDelegate/textFieldValueChanges(_:shouldChangeCharactersIn:replacementString:)":{"role":"symbol","title":"textFieldValueChanges(_:shouldChangeCharactersIn:replacementString:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldValueChanges"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldChangeCharactersIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replacementString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldViewDelegate\/textFieldValueChanges(_:shouldChangeCharactersIn:replacementString:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/textfieldviewdelegate\/textfieldvaluechanges(_:shouldchangecharactersin:replacementstring:)"},"doc://com.Divar.DivarClient/documentation/Divar/TextFieldViewDelegate/textFieldDidChangeSelection(_:)-6lotc":{"defaultImplementations":1,"role":"symbol","title":"textFieldDidChangeSelection(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldDidChangeSelection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldViewDelegate\/textFieldDidChangeSelection(_:)-6lotc","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/textfieldviewdelegate\/textfielddidchangeselection(_:)-6lotc"},"doc://com.Divar.DivarClient/documentation/Divar/NumberInputViewController":{"role":"symbol","title":"NumberInputViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NumberInputViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberInputViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NumberInputViewController"}],"url":"\/documentation\/divar\/numberinputviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/TextFieldViewDelegate":{"role":"symbol","title":"TextFieldViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextFieldViewDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TextFieldViewDelegate"}],"url":"\/documentation\/divar\/textfieldviewdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/TextFieldHintView":{"role":"symbol","title":"TextFieldHintView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextFieldHintView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldHintView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TextFieldHintView"}],"url":"\/documentation\/divar\/textfieldhintview"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController":{"role":"symbol","title":"VerificationCodeInputViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VerificationCodeInputViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VerificationCodeInputViewController"}],"url":"\/documentation\/divar\/verificationcodeinputviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NumberInputViewController\/title","value":"NumberInputViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NumberInputViewController\/fragments","value":[{"kind":"identifier","text":"NumberInputViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TextFieldHintView\/title","value":"TextFieldHintView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TextFieldHintView\/fragments","value":[{"kind":"identifier","text":"TextFieldHintView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VerificationCodeInputViewController\/title","value":"VerificationCodeInputViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VerificationCodeInputViewController\/fragments","value":[{"kind":"identifier","text":"VerificationCodeInputViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}