{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransformablePriceViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/transformablepriceviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/transformablepriceviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ComponentProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","doc:\/\/com.Divar.DivarClient\/6Eureka17RowControllerTypeP","doc:\/\/com.Divar.DivarClient\/6Eureka22TypedRowControllerTypeP","doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SwitchTableViewCellDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIScrollViewDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDataSource","doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UITextFieldDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WideButtonViewControllerDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Structures","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/DataDispatcher","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/SwitchStateWorkItemKey"]},{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/init(property:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/buttonBar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/delegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/finalValue","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/isTransformedCellExpanded","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/onDismissCallback","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/row","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/schema","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/stackView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/submitState","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/switchState","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/switchStateWotkItems","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/tableView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/tableViewDataSource","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/uncheckedFinalValue"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/accessoryToolbar()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/beginValidation(showError:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/bound(for:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/cell(for:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/disableSwitch(didUserDisabledTransforming:isOnFieldEmpty:disableRow:shouldDisableSwitch:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/enableSwitch(didUserEnabledTransforming:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/errorMessages(dispacher:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/errorNumberFormatter(decimalSeparator:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/expandTranformableCells()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/findDataSourceIndexByIdentifier(indentifier:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/formatNumberWithSchemaValueHolder(for:number:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/generateDataSourceForDefaultCells(switchEnabled:isCellEnabled:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/generateDataSourceForExchangedCells()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/generateDisabledTransformDescription(isOnFieldEmpty:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/generateInitialDataSource()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/inferSwitchVisibiltyStateFromFinalValues()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/mergeFinalValuesWithUncheckedValues()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/mergeUncheckedValuesWithFinalValues()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/removeTransformedValues()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/shouldGenerateTransformedCells()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/transformEnglishNumberToIRRCurrencyFormattedString(from:seperator:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/unExpandTranformableCells(isOnFieldEmpty:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/updateSwitchDescriptionTransformedDisabled(message:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/updateTextFieldCellSubtitle(for:with:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/updateTextFieldText(for:textField:newPrice:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/validateRentAndCredit(isTransformableEnabled:rentValue:creditValue:showError:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/validateTransformedDependency(rentValue:creditValue:transformedRentValue:transformedCreditValue:showError:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/validateTransformedRentAndTransformedCredit(rentValue:creditValue:transformedRentValue:transformedCreditValue:showError:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/viewDidLoad()"]},{"title":"Enumerations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/TextFieldSubtitleError"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/SwitchTableViewCellDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/UITableViewDataSource-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/UITableViewDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/UITextFieldDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/WideButtonViewControllerDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransformablePriceViewController"}],"title":"TransformablePriceViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)TransformablePriceViewController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"TransformablePriceViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController":{"role":"symbol","title":"BaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseViewController"}],"url":"\/documentation\/divar\/baseviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/SwitchTableViewCellDelegate-Implementations":{"role":"collectionGroup","title":"SwitchTableViewCellDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/SwitchTableViewCellDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/switchtableviewcelldelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/SwitchTableViewCellDelegate":{"role":"symbol","title":"SwitchTableViewCellDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SwitchTableViewCellDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SwitchTableViewCellDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SwitchTableViewCellDelegate"}],"url":"\/documentation\/divar\/switchtableviewcelldelegate"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/generateInitialDataSource()":{"role":"symbol","title":"generateInitialDataSource()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateInitialDataSource"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"TransformablePrice","preciseIdentifier":"s:5Divar18TransformablePriceO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Model","preciseIdentifier":"s:5Divar18TransformablePriceO5ModelO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"DataSource","preciseIdentifier":"s:5Divar18TransformablePriceO5ModelO10DataSourceO"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/generateInitialDataSource()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/generateinitialdatasource()"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/buttonBar":{"role":"symbol","title":"buttonBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WideButtonViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WideButtonViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/buttonBar","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/buttonbar"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/UITextFieldDelegate-Implementations":{"role":"collectionGroup","title":"UITextFieldDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/UITextFieldDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/uitextfielddelegate-implementations"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/validateTransformedRentAndTransformedCredit(rentValue:creditValue:transformedRentValue:transformedCreditValue:showError:)":{"role":"symbol","title":"validateTransformedRentAndTransformedCredit(rentValue:creditValue:transformedRentValue:transformedCreditValue:showError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validateTransformedRentAndTransformedCredit"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rentValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"creditValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"transformedRentValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"transformedCreditValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"showError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/validateTransformedRentAndTransformedCredit(rentValue:creditValue:transformedRentValue:transformedCreditValue:showError:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/validatetransformedrentandtransformedcredit(rentvalue:creditvalue:transformedrentvalue:transformedcreditvalue:showerror:)"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/tableViewDataSource":{"role":"symbol","title":"tableViewDataSource","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableViewDataSource"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"TransformablePrice","preciseIdentifier":"s:5Divar18TransformablePriceO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Model","preciseIdentifier":"s:5Divar18TransformablePriceO5ModelO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"DataSource","preciseIdentifier":"s:5Divar18TransformablePriceO5ModelO10DataSourceO"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/tableViewDataSource","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/tableviewdatasource"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/row":{"role":"symbol","title":"row","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"row"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RowOf","preciseIdentifier":"s:6Eureka5RowOfC"},{"kind":"text","text":"<["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":"?]>!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/row","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/row"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/SwitchStateWorkItemKey":{"role":"symbol","title":"TransformablePriceViewController.SwitchStateWorkItemKey","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SwitchStateWorkItemKey"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/SwitchStateWorkItemKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SwitchStateWorkItemKey"}],"url":"\/documentation\/divar\/transformablepriceviewcontroller\/switchstateworkitemkey"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/init(property:)":{"role":"symbol","title":"init(property:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"property"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/init(property:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/init(property:)"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/disableSwitch(didUserDisabledTransforming:isOnFieldEmpty:disableRow:shouldDisableSwitch:)":{"role":"symbol","title":"disableSwitch(didUserDisabledTransforming:isOnFieldEmpty:disableRow:shouldDisableSwitch:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableSwitch"},{"kind":"text","text":"("},{"kind":"externalParam","text":"didUserDisabledTransforming"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isOnFieldEmpty"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"disableRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldDisableSwitch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/disableSwitch(didUserDisabledTransforming:isOnFieldEmpty:disableRow:shouldDisableSwitch:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/disableswitch(diduserdisabledtransforming:isonfieldempty:disablerow:shoulddisableswitch:)"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/mergeUncheckedValuesWithFinalValues()":{"role":"symbol","title":"mergeUncheckedValuesWithFinalValues()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mergeUncheckedValuesWithFinalValues"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/mergeUncheckedValuesWithFinalValues()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/mergeuncheckedvalueswithfinalvalues()"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/WideButtonViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"WideButtonViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/WideButtonViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/widebuttonviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/ShowMessageProtocol":{"role":"symbol","title":"ShowMessageProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowMessageProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowMessageProtocol"}],"url":"\/documentation\/divar\/showmessageprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/schema":{"role":"symbol","title":"schema","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"schema"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Schema","preciseIdentifier":"s:5Divar6SchemaV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/schema","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/schema"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/inferSwitchVisibiltyStateFromFinalValues()":{"role":"symbol","title":"inferSwitchVisibiltyStateFromFinalValues()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"inferSwitchVisibiltyStateFromFinalValues"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/inferSwitchVisibiltyStateFromFinalValues()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/inferswitchvisibiltystatefromfinalvalues()"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/validateTransformedDependency(rentValue:creditValue:transformedRentValue:transformedCreditValue:showError:)":{"role":"symbol","title":"validateTransformedDependency(rentValue:creditValue:transformedRentValue:transformedCreditValue:showError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validateTransformedDependency"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rentValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"creditValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"transformedRentValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"transformedCreditValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"showError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/validateTransformedDependency(rentValue:creditValue:transformedRentValue:transformedCreditValue:showError:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/validatetransformeddependency(rentvalue:creditvalue:transformedrentvalue:transformedcreditvalue:showerror:)"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/submitState":{"role":"symbol","title":"submitState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"submitState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TransformablePrice","preciseIdentifier":"s:5Divar18TransformablePriceO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"States","preciseIdentifier":"s:5Divar18TransformablePriceO6StatesO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"SubmitState","preciseIdentifier":"s:5Divar18TransformablePriceO6StatesO11SubmitStateV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/submitState","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/submitstate"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/finalValue":{"role":"symbol","title":"finalValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalValue"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":"?]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/finalValue","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/finalvalue"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/updateTextFieldText(for:textField:newPrice:)":{"role":"symbol","title":"updateTextFieldText(for:textField:newPrice:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateTextFieldText"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TransformablePrice","preciseIdentifier":"s:5Divar18TransformablePriceO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Model","preciseIdentifier":"s:5Divar18TransformablePriceO5ModelO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Identifiers","preciseIdentifier":"s:5Divar18TransformablePriceO5ModelO11IdentifiersO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newPrice"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/updateTextFieldText(for:textField:newPrice:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/updatetextfieldtext(for:textfield:newprice:)"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/6Eureka17RowControllerTypeP":{"type":"unresolvable","title":"Eureka.RowControllerType","identifier":"doc:\/\/com.Divar.DivarClient\/6Eureka17RowControllerTypeP"},"doc://com.Divar.DivarClient/6Eureka22TypedRowControllerTypeP":{"type":"unresolvable","title":"Eureka.TypedRowControllerType","identifier":"doc:\/\/com.Divar.DivarClient\/6Eureka22TypedRowControllerTypeP"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/formatNumberWithSchemaValueHolder(for:number:)":{"role":"symbol","title":"formatNumberWithSchemaValueHolder(for:number:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"formatNumberWithSchemaValueHolder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TransformablePrice","preciseIdentifier":"s:5Divar18TransformablePriceO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Model","preciseIdentifier":"s:5Divar18TransformablePriceO5ModelO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Identifiers","preciseIdentifier":"s:5Divar18TransformablePriceO5ModelO11IdentifiersO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"number"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/formatNumberWithSchemaValueHolder(for:number:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/formatnumberwithschemavalueholder(for:number:)"},"doc://com.Divar.DivarClient/documentation/Divar/ShowErrorProtocol":{"role":"symbol","title":"ShowErrorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowErrorProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowErrorProtocol"}],"url":"\/documentation\/divar\/showerrorprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TransformablePriceViewControllerDelegate","preciseIdentifier":"s:5Divar40TransformablePriceViewControllerDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/delegate"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/unExpandTranformableCells(isOnFieldEmpty:)":{"role":"symbol","title":"unExpandTranformableCells(isOnFieldEmpty:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unExpandTranformableCells"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isOnFieldEmpty"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/unExpandTranformableCells(isOnFieldEmpty:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/unexpandtranformablecells(isonfieldempty:)"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/beginValidation(showError:)":{"role":"symbol","title":"beginValidation(showError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"beginValidation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"showError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/beginValidation(showError:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/beginvalidation(showerror:)"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/generateDisabledTransformDescription(isOnFieldEmpty:)":{"role":"symbol","title":"generateDisabledTransformDescription(isOnFieldEmpty:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateDisabledTransformDescription"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isOnFieldEmpty"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TransformablePrice","preciseIdentifier":"s:5Divar18TransformablePriceO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Model","preciseIdentifier":"s:5Divar18TransformablePriceO5ModelO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"DataSource","preciseIdentifier":"s:5Divar18TransformablePriceO5ModelO10DataSourceO"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/generateDisabledTransformDescription(isOnFieldEmpty:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/generatedisabledtransformdescription(isonfieldempty:)"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/UITableViewDataSource-Implementations":{"role":"collectionGroup","title":"UITableViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/UITableViewDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/uitableviewdatasource-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/TextFieldSubtitleError":{"role":"symbol","title":"TransformablePriceViewController.TextFieldSubtitleError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextFieldSubtitleError"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/TextFieldSubtitleError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TextFieldSubtitleError"}],"url":"\/documentation\/divar\/transformablepriceviewcontroller\/textfieldsubtitleerror"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/generateDataSourceForDefaultCells(switchEnabled:isCellEnabled:)":{"role":"symbol","title":"generateDataSourceForDefaultCells(switchEnabled:isCellEnabled:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateDataSourceForDefaultCells"},{"kind":"text","text":"("},{"kind":"externalParam","text":"switchEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isCellEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"TransformablePrice","preciseIdentifier":"s:5Divar18TransformablePriceO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Model","preciseIdentifier":"s:5Divar18TransformablePriceO5ModelO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"DataSource","preciseIdentifier":"s:5Divar18TransformablePriceO5ModelO10DataSourceO"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/generateDataSourceForDefaultCells(switchEnabled:isCellEnabled:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/generatedatasourcefordefaultcells(switchenabled:iscellenabled:)"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/DataDispatcher":{"role":"symbol","title":"TransformablePriceViewController.DataDispatcher","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataDispatcher"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/DataDispatcher","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DataDispatcher"}],"url":"\/documentation\/divar\/transformablepriceviewcontroller\/datadispatcher"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/documentation/Divar/PaymentSystemProtocol":{"role":"symbol","title":"PaymentSystemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSystemProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaymentSystemProtocol"}],"url":"\/documentation\/divar\/paymentsystemprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/uncheckedFinalValue":{"role":"symbol","title":"uncheckedFinalValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uncheckedFinalValue"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"TransformablePrice","preciseIdentifier":"s:5Divar18TransformablePriceO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Model","preciseIdentifier":"s:5Divar18TransformablePriceO5ModelO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Identifiers","preciseIdentifier":"s:5Divar18TransformablePriceO5ModelO11IdentifiersO"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":"?]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/uncheckedFinalValue","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/uncheckedfinalvalue"},"doc://com.Divar.DivarClient/documentation/Divar/TooltipPresenter":{"role":"symbol","title":"TooltipPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TooltipPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TooltipPresenter"}],"url":"\/documentation\/divar\/tooltippresenter"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/documentation/Divar/ErrorMessageHandler":{"role":"symbol","title":"ErrorMessageHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorMessageHandler"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorMessageHandler"}],"url":"\/documentation\/divar\/errormessagehandler"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/bound(for:)":{"role":"symbol","title":"bound(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bound"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TransformablePrice","preciseIdentifier":"s:5Divar18TransformablePriceO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Validator","preciseIdentifier":"s:5Divar18TransformablePriceO9ValidatorO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Bound","preciseIdentifier":"s:5Divar18TransformablePriceO9ValidatorO5BoundV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/bound(for:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/bound(for:)"},"doc://com.Divar.DivarClient/documentation/Divar/ComponentProtocol":{"role":"symbol","title":"ComponentProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComponentProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ComponentProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ComponentProtocol"}],"url":"\/documentation\/divar\/componentprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/WideButtonViewControllerDelegate":{"role":"symbol","title":"WideButtonViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WideButtonViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WideButtonViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WideButtonViewControllerDelegate"}],"url":"\/documentation\/divar\/widebuttonviewcontrollerdelegate"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIScrollViewDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/stackView":{"role":"symbol","title":"stackView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/stackView","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/stackview"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/findDataSourceIndexByIdentifier(indentifier:)":{"role":"symbol","title":"findDataSourceIndexByIdentifier(indentifier:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"findDataSourceIndexByIdentifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"indentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TransformablePrice","preciseIdentifier":"s:5Divar18TransformablePriceO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Model","preciseIdentifier":"s:5Divar18TransformablePriceO5ModelO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Identifiers","preciseIdentifier":"s:5Divar18TransformablePriceO5ModelO11IdentifiersO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/findDataSourceIndexByIdentifier(indentifier:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/finddatasourceindexbyidentifier(indentifier:)"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/UITableViewDelegate-Implementations":{"role":"collectionGroup","title":"UITableViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/UITableViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/uitableviewdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController":{"role":"symbol","title":"TransformablePriceViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransformablePriceViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TransformablePriceViewController"}],"url":"\/documentation\/divar\/transformablepriceviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/switchStateWotkItems":{"role":"symbol","title":"switchStateWotkItems","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchStateWotkItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SwitchStateWorkItemKey","preciseIdentifier":"s:5Divar32TransformablePriceViewControllerC22SwitchStateWorkItemKeyV"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/switchStateWotkItems","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/switchstatewotkitems"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/transformablepriceviewcontroller\/init(coder:)"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/updateSwitchDescriptionTransformedDisabled(message:)":{"role":"symbol","title":"updateSwitchDescriptionTransformedDisabled(message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateSwitchDescriptionTransformedDisabled"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/updateSwitchDescriptionTransformedDisabled(message:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/updateswitchdescriptiontransformeddisabled(message:)"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/removeTransformedValues()":{"role":"symbol","title":"removeTransformedValues()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeTransformedValues"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/removeTransformedValues()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/removetransformedvalues()"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/validateRentAndCredit(isTransformableEnabled:rentValue:creditValue:showError:)":{"role":"symbol","title":"validateRentAndCredit(isTransformableEnabled:rentValue:creditValue:showError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validateRentAndCredit"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isTransformableEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rentValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"creditValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"showError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/validateRentAndCredit(isTransformableEnabled:rentValue:creditValue:showError:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/validaterentandcredit(istransformableenabled:rentvalue:creditvalue:showerror:)"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/onDismissCallback":{"role":"symbol","title":"onDismissCallback","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDismissCallback"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/onDismissCallback","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/ondismisscallback"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/tableView":{"role":"symbol","title":"tableView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/tableView","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/tableview"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/cell(for:)":{"role":"symbol","title":"cell(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cell"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TransformablePrice","preciseIdentifier":"s:5Divar18TransformablePriceO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Model","preciseIdentifier":"s:5Divar18TransformablePriceO5ModelO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Identifiers","preciseIdentifier":"s:5Divar18TransformablePriceO5ModelO11IdentifiersO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:5Divar32TransformablePriceViewControllerC4cell3forxSgAA0bC0O5ModelO11IdentifiersO_tlF1TL_xmfp"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/cell(for:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/cell(for:)"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/errorMessages(dispacher:)":{"role":"symbol","title":"errorMessages(dispacher:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dispacher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DataDispatcher","preciseIdentifier":"s:5Divar32TransformablePriceViewControllerC14DataDispatcherV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TransformablePrice","preciseIdentifier":"s:5Divar18TransformablePriceO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Validator","preciseIdentifier":"s:5Divar18TransformablePriceO9ValidatorO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ErrorMessages","preciseIdentifier":"s:5Divar18TransformablePriceO9ValidatorO13ErrorMessagesV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/errorMessages(dispacher:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/errormessages(dispacher:)"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/enableSwitch(didUserEnabledTransforming:)":{"role":"symbol","title":"enableSwitch(didUserEnabledTransforming:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableSwitch"},{"kind":"text","text":"("},{"kind":"externalParam","text":"didUserEnabledTransforming"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/enableSwitch(didUserEnabledTransforming:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/enableswitch(diduserenabledtransforming:)"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/updateTextFieldCellSubtitle(for:with:)":{"role":"symbol","title":"updateTextFieldCellSubtitle(for:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateTextFieldCellSubtitle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TransformablePrice","preciseIdentifier":"s:5Divar18TransformablePriceO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Model","preciseIdentifier":"s:5Divar18TransformablePriceO5ModelO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Identifiers","preciseIdentifier":"s:5Divar18TransformablePriceO5ModelO11IdentifiersO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TextFieldSubtitleError","preciseIdentifier":"s:5Divar32TransformablePriceViewControllerC22TextFieldSubtitleErrorO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/updateTextFieldCellSubtitle(for:with:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/updatetextfieldcellsubtitle(for:with:)"},"doc://com.Divar.DivarClient/objc(pl)UITextFieldDelegate":{"type":"unresolvable","title":"UIKit.UITextFieldDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITextFieldDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/errorNumberFormatter(decimalSeparator:)":{"role":"symbol","title":"errorNumberFormatter(decimalSeparator:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorNumberFormatter"},{"kind":"text","text":"("},{"kind":"externalParam","text":"decimalSeparator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NumberFormatter","preciseIdentifier":"c:objc(cs)NSNumberFormatter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/errorNumberFormatter(decimalSeparator:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/errornumberformatter(decimalseparator:)"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/generateDataSourceForExchangedCells()":{"role":"symbol","title":"generateDataSourceForExchangedCells()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateDataSourceForExchangedCells"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"TransformablePrice","preciseIdentifier":"s:5Divar18TransformablePriceO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Model","preciseIdentifier":"s:5Divar18TransformablePriceO5ModelO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"DataSource","preciseIdentifier":"s:5Divar18TransformablePriceO5ModelO10DataSourceO"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/generateDataSourceForExchangedCells()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/generatedatasourceforexchangedcells()"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/accessoryToolbar()":{"role":"symbol","title":"accessoryToolbar()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessoryToolbar"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/accessoryToolbar()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/accessorytoolbar()"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/transformablepriceviewcontroller\/viewdidload()"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/mergeFinalValuesWithUncheckedValues()":{"role":"symbol","title":"mergeFinalValuesWithUncheckedValues()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mergeFinalValuesWithUncheckedValues"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/mergeFinalValuesWithUncheckedValues()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/mergefinalvalueswithuncheckedvalues()"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/expandTranformableCells()":{"role":"symbol","title":"expandTranformableCells()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"expandTranformableCells"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/expandTranformableCells()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/expandtranformablecells()"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/shouldGenerateTransformedCells()":{"role":"symbol","title":"shouldGenerateTransformedCells()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldGenerateTransformedCells"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/shouldGenerateTransformedCells()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/shouldgeneratetransformedcells()"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/objc(pl)UITableViewDataSource":{"type":"unresolvable","title":"UIKit.UITableViewDataSource","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDataSource"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/transformEnglishNumberToIRRCurrencyFormattedString(from:seperator:)":{"role":"symbol","title":"transformEnglishNumberToIRRCurrencyFormattedString(from:seperator:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformEnglishNumberToIRRCurrencyFormattedString"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":", "},{"kind":"externalParam","text":"seperator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/transformEnglishNumberToIRRCurrencyFormattedString(from:seperator:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/transformenglishnumbertoirrcurrencyformattedstring(from:seperator:)"},"doc://com.Divar.DivarClient/objc(pl)UITableViewDelegate":{"type":"unresolvable","title":"UIKit.UITableViewDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITableViewDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/isTransformedCellExpanded":{"role":"symbol","title":"isTransformedCellExpanded","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isTransformedCellExpanded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/isTransformedCellExpanded","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/istransformedcellexpanded"},"doc://com.Divar.DivarClient/documentation/Divar/TransformablePriceViewController/switchState":{"role":"symbol","title":"switchState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TransformablePrice","preciseIdentifier":"s:5Divar18TransformablePriceO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"States","preciseIdentifier":"s:5Divar18TransformablePriceO6StatesO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"SwitchState","preciseIdentifier":"s:5Divar18TransformablePriceO6StatesO11SwitchStateV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/switchState","kind":"symbol","type":"topic","url":"\/documentation\/divar\/transformablepriceviewcontroller\/switchstate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TransformablePriceViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TransformablePriceViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TransformablePriceViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/UITableViewDataSource-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/UITableViewDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TransformablePriceViewController\/UITextFieldDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransformablePriceViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController","preciseIdentifier":"c:@M@Divar@objc(cs)BaseViewController","text":"BaseViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController\/title","value":"BaseViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController\/fragments","value":[{"kind":"identifier","text":"BaseViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TransformablePriceViewController\/title","value":"TransformablePriceViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TransformablePriceViewController\/fragments","value":[{"kind":"identifier","text":"TransformablePriceViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TransformablePriceViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TransformablePriceViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TransformablePriceViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TransformablePriceViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}