{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TwinButtonsViewControllerDelegate"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/twinbuttonsviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddEditAgentViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddSalesmanViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddStoreManagerViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddUserTransactionFormViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddVRViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BeforeRegisterTermsAndConditionsVC","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BooleanRateFormViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetContactViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BusinessGetContactViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BusinessSubscriptionViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BuyBulkLadderViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentBuyLadderPackageViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentBuyPackageViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentSubmitViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarInspectionRegisterViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarInspectionSubmitViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CreateAndEditOperatorViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubmitViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/EditMarketplaceStoreViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FinalizeMarketplaceRegister","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JobsSubmitViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandscapeWidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketpalceFeedbackViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceEditAssistantViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceQuickEditPostVC","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceSubmitViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceSubscriptionViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MobileZeroPriceViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OfflineFormViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OfflinePageViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostReportDescriptionViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateRegistrationViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateSubmitViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RegisterAgentViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RegisterDealerViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RegisterMarketplaceViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SchemaFormViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScreenWidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchFilterViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SendFeedbackViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UsedPriceFormViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ValidatorRowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoPreviewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedFilterViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostDetailsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostPreviewViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewControllerDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewControllerDelegate\/primaryButtonClicked(_:action:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewControllerDelegate\/secondaryButtonClicked(_:action:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TwinButtonsViewControllerDelegate"}],"title":"TwinButtonsViewControllerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar33TwinButtonsViewControllerDelegateP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"TwinButtonsViewControllerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/AddStoreManagerViewController":{"role":"symbol","title":"AddStoreManagerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddStoreManagerViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddStoreManagerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddStoreManagerViewController"}],"url":"\/documentation\/divar\/addstoremanagerviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewControllerDelegate":{"role":"symbol","title":"TwinButtonsViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TwinButtonsViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TwinButtonsViewControllerDelegate"}],"url":"\/documentation\/divar\/twinbuttonsviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewControllerDelegate/primaryButtonClicked(_:action:)":{"role":"symbol","title":"primaryButtonClicked(_:action:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryButtonClicked"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TwinButtonsViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TwinButtonsViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewControllerDelegate\/primaryButtonClicked(_:action:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/twinbuttonsviewcontrollerdelegate\/primarybuttonclicked(_:action:)"},"doc://com.Divar.DivarClient/documentation/Divar/RealEstateRegistrationViewController":{"role":"symbol","title":"RealEstateRegistrationViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RealEstateRegistrationViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateRegistrationViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RealEstateRegistrationViewController"}],"url":"\/documentation\/divar\/realestateregistrationviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BooleanRateFormViewController":{"role":"symbol","title":"BooleanRateFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BooleanRateFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BooleanRateFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BooleanRateFormViewController"}],"url":"\/documentation\/divar\/booleanrateformviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/VideoPreviewController":{"role":"symbol","title":"VideoPreviewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPreviewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoPreviewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoPreviewController"}],"url":"\/documentation\/divar\/videopreviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedFilterViewController":{"role":"symbol","title":"WidgetBasedFilterViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedFilterViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedFilterViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedFilterViewController"}],"url":"\/documentation\/divar\/widgetbasedfilterviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/NoteViewController":{"role":"symbol","title":"NoteViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NoteViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NoteViewController"}],"url":"\/documentation\/divar\/noteviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController":{"role":"symbol","title":"AdvancedWidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdvancedWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdvancedWidgetViewController"}],"url":"\/documentation\/divar\/advancedwidgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AddVRViewController":{"role":"symbol","title":"AddVRViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddVRViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddVRViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddVRViewController"}],"url":"\/documentation\/divar\/addvrviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MobileZeroPriceViewController":{"role":"symbol","title":"MobileZeroPriceViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MobileZeroPriceViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MobileZeroPriceViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MobileZeroPriceViewController"}],"url":"\/documentation\/divar\/mobilezeropriceviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController":{"role":"symbol","title":"VerificationCodeInputViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VerificationCodeInputViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VerificationCodeInputViewController"}],"url":"\/documentation\/divar\/verificationcodeinputviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/RegisterDealerViewController":{"role":"symbol","title":"RegisterDealerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RegisterDealerViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RegisterDealerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RegisterDealerViewController"}],"url":"\/documentation\/divar\/registerdealerviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/NoteWithBottomBarViewController":{"role":"symbol","title":"NoteWithBottomBarViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NoteWithBottomBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteWithBottomBarViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NoteWithBottomBarViewController"}],"url":"\/documentation\/divar\/notewithbottombarviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostReportDescriptionViewController":{"role":"symbol","title":"PostReportDescriptionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostReportDescriptionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostReportDescriptionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostReportDescriptionViewController"}],"url":"\/documentation\/divar\/postreportdescriptionviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/RegisterAgentViewController":{"role":"symbol","title":"RegisterAgentViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RegisterAgentViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RegisterAgentViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RegisterAgentViewController"}],"url":"\/documentation\/divar\/registeragentviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/RealEstateSubmitViewController":{"role":"symbol","title":"RealEstateSubmitViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RealEstateSubmitViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateSubmitViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RealEstateSubmitViewController"}],"url":"\/documentation\/divar\/realestatesubmitviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedPostPreviewViewController":{"role":"symbol","title":"WidgetBasedPostPreviewViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedPostPreviewViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostPreviewViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedPostPreviewViewController"}],"url":"\/documentation\/divar\/widgetbasedpostpreviewviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostArchiveViewController":{"role":"symbol","title":"PostArchiveViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostArchiveViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostArchiveViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostArchiveViewController"}],"url":"\/documentation\/divar\/postarchiveviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ScreenWidgetViewController":{"role":"symbol","title":"ScreenWidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScreenWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScreenWidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScreenWidgetViewController"}],"url":"\/documentation\/divar\/screenwidgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostCreateViewController":{"role":"symbol","title":"PostCreateViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostCreateViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCreateViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostCreateViewController"}],"url":"\/documentation\/divar\/postcreateviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/UsedPriceFormViewController":{"role":"symbol","title":"UsedPriceFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsedPriceFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UsedPriceFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UsedPriceFormViewController"}],"url":"\/documentation\/divar\/usedpriceformviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/DealerSubmitViewController":{"role":"symbol","title":"DealerSubmitViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DealerSubmitViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubmitViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DealerSubmitViewController"}],"url":"\/documentation\/divar\/dealersubmitviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MarketplaceSubmitViewController":{"role":"symbol","title":"MarketplaceSubmitViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketplaceSubmitViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceSubmitViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketplaceSubmitViewController"}],"url":"\/documentation\/divar\/marketplacesubmitviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseFormController":{"role":"symbol","title":"BaseFormController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFormController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseFormController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseFormController"}],"url":"\/documentation\/divar\/baseformcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MarketplaceSubscriptionViewController":{"role":"symbol","title":"MarketplaceSubscriptionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketplaceSubscriptionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceSubscriptionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketplaceSubscriptionViewController"}],"url":"\/documentation\/divar\/marketplacesubscriptionviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedPostDetailsViewController":{"role":"symbol","title":"WidgetBasedPostDetailsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedPostDetailsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostDetailsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedPostDetailsViewController"}],"url":"\/documentation\/divar\/widgetbasedpostdetailsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SendFeedbackViewController":{"role":"symbol","title":"SendFeedbackViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SendFeedbackViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SendFeedbackViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SendFeedbackViewController"}],"url":"\/documentation\/divar\/sendfeedbackviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarInspectionSubmitViewController":{"role":"symbol","title":"CarInspectionSubmitViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarInspectionSubmitViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarInspectionSubmitViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarInspectionSubmitViewController"}],"url":"\/documentation\/divar\/carinspectionsubmitviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SearchFilterViewController":{"role":"symbol","title":"SearchFilterViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchFilterViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchFilterViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchFilterViewController"}],"url":"\/documentation\/divar\/searchfilterviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BusinessSubscriptionViewController":{"role":"symbol","title":"BusinessSubscriptionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BusinessSubscriptionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BusinessSubscriptionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BusinessSubscriptionViewController"}],"url":"\/documentation\/divar\/businesssubscriptionviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetViewController":{"role":"symbol","title":"WidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetViewController"}],"url":"\/documentation\/divar\/widgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/RegisterMarketplaceViewController":{"role":"symbol","title":"RegisterMarketplaceViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RegisterMarketplaceViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RegisterMarketplaceViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RegisterMarketplaceViewController"}],"url":"\/documentation\/divar\/registermarketplaceviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/AddUserTransactionFormViewController":{"role":"symbol","title":"AddUserTransactionFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddUserTransactionFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddUserTransactionFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddUserTransactionFormViewController"}],"url":"\/documentation\/divar\/addusertransactionformviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetContactViewController":{"role":"symbol","title":"BottomSheetContactViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BottomSheetContactViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetContactViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BottomSheetContactViewController"}],"url":"\/documentation\/divar\/bottomsheetcontactviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MarketpalceFeedbackViewController":{"role":"symbol","title":"MarketpalceFeedbackViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketpalceFeedbackViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketpalceFeedbackViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketpalceFeedbackViewController"}],"url":"\/documentation\/divar\/marketpalcefeedbackviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController":{"role":"symbol","title":"ZeroPriceViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZeroPriceViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZeroPriceViewController"}],"url":"\/documentation\/divar\/zeropriceviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/LandscapeWidgetViewController":{"role":"symbol","title":"LandscapeWidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandscapeWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandscapeWidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandscapeWidgetViewController"}],"url":"\/documentation\/divar\/landscapewidgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MarketplaceEditAssistantViewController":{"role":"symbol","title":"MarketplaceEditAssistantViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketplaceEditAssistantViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceEditAssistantViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketplaceEditAssistantViewController"}],"url":"\/documentation\/divar\/marketplaceeditassistantviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MarketplaceQuickEditPostVC":{"role":"symbol","title":"MarketplaceQuickEditPostVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketplaceQuickEditPostVC"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MarketplaceQuickEditPostVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarketplaceQuickEditPostVC"}],"url":"\/documentation\/divar\/marketplacequickeditpostvc"},"doc://com.Divar.DivarClient/documentation/Divar/EditMarketplaceStoreViewController":{"role":"symbol","title":"EditMarketplaceStoreViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EditMarketplaceStoreViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/EditMarketplaceStoreViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EditMarketplaceStoreViewController"}],"url":"\/documentation\/divar\/editmarketplacestoreviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/OfflinePageViewController":{"role":"symbol","title":"OfflinePageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflinePageViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OfflinePageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OfflinePageViewController"}],"url":"\/documentation\/divar\/offlinepageviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/OfflineFormViewController":{"role":"symbol","title":"OfflineFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OfflineFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OfflineFormViewController"}],"url":"\/documentation\/divar\/offlineformviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ValidatorRowController":{"role":"symbol","title":"ValidatorRowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidatorRowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ValidatorRowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ValidatorRowController"}],"url":"\/documentation\/divar\/validatorrowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CreateAndEditOperatorViewController":{"role":"symbol","title":"CreateAndEditOperatorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateAndEditOperatorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CreateAndEditOperatorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CreateAndEditOperatorViewController"}],"url":"\/documentation\/divar\/createandeditoperatorviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/JobsSubmitViewController":{"role":"symbol","title":"JobsSubmitViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JobsSubmitViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/JobsSubmitViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JobsSubmitViewController"}],"url":"\/documentation\/divar\/jobssubmitviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarInspectionRegisterViewController":{"role":"symbol","title":"CarInspectionRegisterViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarInspectionRegisterViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarInspectionRegisterViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarInspectionRegisterViewController"}],"url":"\/documentation\/divar\/carinspectionregisterviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarAgentBuyPackageViewController":{"role":"symbol","title":"CarAgentBuyPackageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarAgentBuyPackageViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentBuyPackageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarAgentBuyPackageViewController"}],"url":"\/documentation\/divar\/caragentbuypackageviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController":{"role":"symbol","title":"WidgetBasedViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedViewController"}],"url":"\/documentation\/divar\/widgetbasedviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AddEditAgentViewController":{"role":"symbol","title":"AddEditAgentViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddEditAgentViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddEditAgentViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddEditAgentViewController"}],"url":"\/documentation\/divar\/addeditagentviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SchemaFormViewController":{"role":"symbol","title":"SchemaFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SchemaFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SchemaFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SchemaFormViewController"}],"url":"\/documentation\/divar\/schemaformviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AddSalesmanViewController":{"role":"symbol","title":"AddSalesmanViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddSalesmanViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddSalesmanViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddSalesmanViewController"}],"url":"\/documentation\/divar\/addsalesmanviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarAgentBuyLadderPackageViewController":{"role":"symbol","title":"CarAgentBuyLadderPackageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarAgentBuyLadderPackageViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentBuyLadderPackageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarAgentBuyLadderPackageViewController"}],"url":"\/documentation\/divar\/caragentbuyladderpackageviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BusinessGetContactViewController":{"role":"symbol","title":"BusinessGetContactViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BusinessGetContactViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BusinessGetContactViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BusinessGetContactViewController"}],"url":"\/documentation\/divar\/businessgetcontactviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BuyBulkLadderViewController":{"role":"symbol","title":"BuyBulkLadderViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BuyBulkLadderViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BuyBulkLadderViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BuyBulkLadderViewController"}],"url":"\/documentation\/divar\/buybulkladderviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewControllerDelegate/secondaryButtonClicked(_:action:)":{"role":"symbol","title":"secondaryButtonClicked(_:action:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondaryButtonClicked"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TwinButtonsViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TwinButtonsViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewControllerDelegate\/secondaryButtonClicked(_:action:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/twinbuttonsviewcontrollerdelegate\/secondarybuttonclicked(_:action:)"},"doc://com.Divar.DivarClient/documentation/Divar/BeforeRegisterTermsAndConditionsVC":{"role":"symbol","title":"BeforeRegisterTermsAndConditionsVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BeforeRegisterTermsAndConditionsVC"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BeforeRegisterTermsAndConditionsVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BeforeRegisterTermsAndConditionsVC"}],"url":"\/documentation\/divar\/beforeregistertermsandconditionsvc"},"doc://com.Divar.DivarClient/documentation/Divar/FinalizeMarketplaceRegister":{"role":"symbol","title":"FinalizeMarketplaceRegister","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FinalizeMarketplaceRegister"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FinalizeMarketplaceRegister","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FinalizeMarketplaceRegister"}],"url":"\/documentation\/divar\/finalizemarketplaceregister"},"doc://com.Divar.DivarClient/documentation/Divar/CarAgentSubmitViewController":{"role":"symbol","title":"CarAgentSubmitViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarAgentSubmitViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentSubmitViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarAgentSubmitViewController"}],"url":"\/documentation\/divar\/caragentsubmitviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddStoreManagerViewController\/title","value":"AddStoreManagerViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddStoreManagerViewController\/fragments","value":[{"kind":"identifier","text":"AddStoreManagerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateRegistrationViewController\/title","value":"RealEstateRegistrationViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateRegistrationViewController\/fragments","value":[{"kind":"identifier","text":"RealEstateRegistrationViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BooleanRateFormViewController\/title","value":"BooleanRateFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BooleanRateFormViewController\/fragments","value":[{"kind":"identifier","text":"BooleanRateFormViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VideoPreviewController\/title","value":"VideoPreviewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VideoPreviewController\/fragments","value":[{"kind":"identifier","text":"VideoPreviewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedFilterViewController\/title","value":"WidgetBasedFilterViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedFilterViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedFilterViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteViewController\/title","value":"NoteViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteViewController\/fragments","value":[{"kind":"identifier","text":"NoteViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController\/title","value":"AdvancedWidgetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController\/fragments","value":[{"kind":"identifier","text":"AdvancedWidgetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddVRViewController\/title","value":"AddVRViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddVRViewController\/fragments","value":[{"kind":"identifier","text":"AddVRViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MobileZeroPriceViewController\/title","value":"MobileZeroPriceViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MobileZeroPriceViewController\/fragments","value":[{"kind":"identifier","text":"MobileZeroPriceViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VerificationCodeInputViewController\/title","value":"VerificationCodeInputViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VerificationCodeInputViewController\/fragments","value":[{"kind":"identifier","text":"VerificationCodeInputViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RegisterDealerViewController\/title","value":"RegisterDealerViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RegisterDealerViewController\/fragments","value":[{"kind":"identifier","text":"RegisterDealerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteWithBottomBarViewController\/title","value":"NoteWithBottomBarViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteWithBottomBarViewController\/fragments","value":[{"kind":"identifier","text":"NoteWithBottomBarViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostReportDescriptionViewController\/title","value":"PostReportDescriptionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostReportDescriptionViewController\/fragments","value":[{"kind":"identifier","text":"PostReportDescriptionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RegisterAgentViewController\/title","value":"RegisterAgentViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RegisterAgentViewController\/fragments","value":[{"kind":"identifier","text":"RegisterAgentViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateSubmitViewController\/title","value":"RealEstateSubmitViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateSubmitViewController\/fragments","value":[{"kind":"identifier","text":"RealEstateSubmitViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedPostPreviewViewController\/title","value":"WidgetBasedPostPreviewViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedPostPreviewViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedPostPreviewViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController\/title","value":"PostArchiveViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostArchiveViewController\/fragments","value":[{"kind":"identifier","text":"PostArchiveViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScreenWidgetViewController\/title","value":"ScreenWidgetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScreenWidgetViewController\/fragments","value":[{"kind":"identifier","text":"ScreenWidgetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostCreateViewController\/title","value":"PostCreateViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostCreateViewController\/fragments","value":[{"kind":"identifier","text":"PostCreateViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1UsedPriceFormViewController\/title","value":"UsedPriceFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1UsedPriceFormViewController\/fragments","value":[{"kind":"identifier","text":"UsedPriceFormViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubmitViewController\/title","value":"DealerSubmitViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubmitViewController\/fragments","value":[{"kind":"identifier","text":"DealerSubmitViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceSubmitViewController\/title","value":"MarketplaceSubmitViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceSubmitViewController\/fragments","value":[{"kind":"identifier","text":"MarketplaceSubmitViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFormController\/title","value":"BaseFormController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseFormController\/fragments","value":[{"kind":"identifier","text":"BaseFormController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceSubscriptionViewController\/title","value":"MarketplaceSubscriptionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceSubscriptionViewController\/fragments","value":[{"kind":"identifier","text":"MarketplaceSubscriptionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedPostDetailsViewController\/title","value":"WidgetBasedPostDetailsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedPostDetailsViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedPostDetailsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SendFeedbackViewController\/title","value":"SendFeedbackViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SendFeedbackViewController\/fragments","value":[{"kind":"identifier","text":"SendFeedbackViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarInspectionSubmitViewController\/title","value":"CarInspectionSubmitViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarInspectionSubmitViewController\/fragments","value":[{"kind":"identifier","text":"CarInspectionSubmitViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchFilterViewController\/title","value":"SearchFilterViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchFilterViewController\/fragments","value":[{"kind":"identifier","text":"SearchFilterViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BusinessSubscriptionViewController\/title","value":"BusinessSubscriptionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BusinessSubscriptionViewController\/fragments","value":[{"kind":"identifier","text":"BusinessSubscriptionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RegisterMarketplaceViewController\/title","value":"RegisterMarketplaceViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RegisterMarketplaceViewController\/fragments","value":[{"kind":"identifier","text":"RegisterMarketplaceViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddUserTransactionFormViewController\/title","value":"AddUserTransactionFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddUserTransactionFormViewController\/fragments","value":[{"kind":"identifier","text":"AddUserTransactionFormViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetContactViewController\/title","value":"BottomSheetContactViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetContactViewController\/fragments","value":[{"kind":"identifier","text":"BottomSheetContactViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketpalceFeedbackViewController\/title","value":"MarketpalceFeedbackViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketpalceFeedbackViewController\/fragments","value":[{"kind":"identifier","text":"MarketpalceFeedbackViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ZeroPriceViewController\/title","value":"ZeroPriceViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ZeroPriceViewController\/fragments","value":[{"kind":"identifier","text":"ZeroPriceViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandscapeWidgetViewController\/title","value":"LandscapeWidgetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandscapeWidgetViewController\/fragments","value":[{"kind":"identifier","text":"LandscapeWidgetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceEditAssistantViewController\/title","value":"MarketplaceEditAssistantViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceEditAssistantViewController\/fragments","value":[{"kind":"identifier","text":"MarketplaceEditAssistantViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceQuickEditPostVC\/title","value":"MarketplaceQuickEditPostVC"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MarketplaceQuickEditPostVC\/fragments","value":[{"kind":"identifier","text":"MarketplaceQuickEditPostVC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1EditMarketplaceStoreViewController\/title","value":"EditMarketplaceStoreViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1EditMarketplaceStoreViewController\/fragments","value":[{"kind":"identifier","text":"EditMarketplaceStoreViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OfflinePageViewController\/title","value":"OfflinePageViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OfflinePageViewController\/fragments","value":[{"kind":"identifier","text":"OfflinePageViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OfflineFormViewController\/title","value":"OfflineFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OfflineFormViewController\/fragments","value":[{"kind":"identifier","text":"OfflineFormViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ValidatorRowController\/title","value":"ValidatorRowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ValidatorRowController\/fragments","value":[{"kind":"identifier","text":"ValidatorRowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CreateAndEditOperatorViewController\/title","value":"CreateAndEditOperatorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CreateAndEditOperatorViewController\/fragments","value":[{"kind":"identifier","text":"CreateAndEditOperatorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JobsSubmitViewController\/title","value":"JobsSubmitViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1JobsSubmitViewController\/fragments","value":[{"kind":"identifier","text":"JobsSubmitViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarInspectionRegisterViewController\/title","value":"CarInspectionRegisterViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarInspectionRegisterViewController\/fragments","value":[{"kind":"identifier","text":"CarInspectionRegisterViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentBuyPackageViewController\/title","value":"CarAgentBuyPackageViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentBuyPackageViewController\/fragments","value":[{"kind":"identifier","text":"CarAgentBuyPackageViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedViewController\/title","value":"WidgetBasedViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddEditAgentViewController\/title","value":"AddEditAgentViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddEditAgentViewController\/fragments","value":[{"kind":"identifier","text":"AddEditAgentViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SchemaFormViewController\/title","value":"SchemaFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SchemaFormViewController\/fragments","value":[{"kind":"identifier","text":"SchemaFormViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddSalesmanViewController\/title","value":"AddSalesmanViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddSalesmanViewController\/fragments","value":[{"kind":"identifier","text":"AddSalesmanViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentBuyLadderPackageViewController\/title","value":"CarAgentBuyLadderPackageViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentBuyLadderPackageViewController\/fragments","value":[{"kind":"identifier","text":"CarAgentBuyLadderPackageViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BusinessGetContactViewController\/title","value":"BusinessGetContactViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BusinessGetContactViewController\/fragments","value":[{"kind":"identifier","text":"BusinessGetContactViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BuyBulkLadderViewController\/title","value":"BuyBulkLadderViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BuyBulkLadderViewController\/fragments","value":[{"kind":"identifier","text":"BuyBulkLadderViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BeforeRegisterTermsAndConditionsVC\/title","value":"BeforeRegisterTermsAndConditionsVC"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BeforeRegisterTermsAndConditionsVC\/fragments","value":[{"kind":"identifier","text":"BeforeRegisterTermsAndConditionsVC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentSubmitViewController\/title","value":"CarAgentSubmitViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentSubmitViewController\/fragments","value":[{"kind":"identifier","text":"CarAgentSubmitViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}