{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TwinButtonsViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/twinbuttonsviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/twinbuttonsviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ButtonComponentProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ComponentProtocol","doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/init(config:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/delegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/isPrimaryEnabled","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/isSecondaryEnabled","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/primaryButton","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/primaryEnabled","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/secondaryButton","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/secondaryEnabled"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/primaryButtonAction(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/secondaryButtonAction(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/setConfig(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/setConfig(stickyWidget:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/traitCollectionDidChange(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/viewDidLoad()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TwinButtonsViewController"}],"title":"TwinButtonsViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)TwinButtonsViewController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"TwinButtonsViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewController/isPrimaryEnabled":{"role":"symbol","title":"isPrimaryEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPrimaryEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/isPrimaryEnabled","kind":"symbol","type":"topic","url":"\/documentation\/divar\/twinbuttonsviewcontroller\/isprimaryenabled"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewController/traitCollectionDidChange(_:)":{"role":"symbol","title":"traitCollectionDidChange(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"traitCollectionDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/traitCollectionDidChange(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"traitCollectionDidChange:"}],"url":"\/documentation\/divar\/twinbuttonsviewcontroller\/traitcollectiondidchange(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewController/init(config:)":{"role":"symbol","title":"init(config:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TwinButtonsConfig","preciseIdentifier":"s:5Divar17TwinButtonsConfigV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/init(config:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/twinbuttonsviewcontroller\/init(config:)"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewController/secondaryButton":{"role":"symbol","title":"secondaryButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondaryButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/secondaryButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"secondaryButton"}],"url":"\/documentation\/divar\/twinbuttonsviewcontroller\/secondarybutton"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/twinbuttonsviewcontroller\/viewdidload()"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TwinButtonsViewControllerDelegate","preciseIdentifier":"s:5Divar33TwinButtonsViewControllerDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/twinbuttonsviewcontroller\/delegate"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/ComponentProtocol":{"role":"symbol","title":"ComponentProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComponentProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ComponentProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ComponentProtocol"}],"url":"\/documentation\/divar\/componentprotocol"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewController/secondaryEnabled":{"role":"symbol","title":"secondaryEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondaryEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/secondaryEnabled","kind":"symbol","type":"topic","url":"\/documentation\/divar\/twinbuttonsviewcontroller\/secondaryenabled"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewController/primaryButton":{"role":"symbol","title":"primaryButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/primaryButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"primaryButton"}],"url":"\/documentation\/divar\/twinbuttonsviewcontroller\/primarybutton"},"doc://com.Divar.DivarClient/documentation/Divar/ButtonComponentProtocol":{"role":"symbol","title":"ButtonComponentProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ButtonComponentProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ButtonComponentProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ButtonComponentProtocol"}],"url":"\/documentation\/divar\/buttoncomponentprotocol"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewController/secondaryButtonAction(_:)":{"role":"symbol","title":"secondaryButtonAction(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondaryButtonAction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/secondaryButtonAction(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"secondaryButtonAction:"}],"url":"\/documentation\/divar\/twinbuttonsviewcontroller\/secondarybuttonaction(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewController/setConfig(_:)":{"role":"symbol","title":"setConfig(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setConfig"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TwinButtonsConfig","preciseIdentifier":"s:5Divar17TwinButtonsConfigV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/setConfig(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/twinbuttonsviewcontroller\/setconfig(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewController/primaryButtonAction(_:)":{"role":"symbol","title":"primaryButtonAction(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryButtonAction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/primaryButtonAction(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"primaryButtonAction:"}],"url":"\/documentation\/divar\/twinbuttonsviewcontroller\/primarybuttonaction(_:)"},"doc://com.Divar.DivarClient/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)UIViewController"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewController":{"role":"symbol","title":"TwinButtonsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TwinButtonsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TwinButtonsViewController"}],"url":"\/documentation\/divar\/twinbuttonsviewcontroller"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewController/primaryEnabled":{"role":"symbol","title":"primaryEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/primaryEnabled","kind":"symbol","type":"topic","url":"\/documentation\/divar\/twinbuttonsviewcontroller\/primaryenabled"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewController/setConfig(stickyWidget:)":{"role":"symbol","title":"setConfig(stickyWidget:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setConfig"},{"kind":"text","text":"("},{"kind":"externalParam","text":"stickyWidget"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StickyWidgetActionWrapper","preciseIdentifier":"s:5Divar25StickyWidgetActionWrapperV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/setConfig(stickyWidget:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/twinbuttonsviewcontroller\/setconfig(stickywidget:)"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/twinbuttonsviewcontroller\/init(coder:)"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewController/isSecondaryEnabled":{"role":"symbol","title":"isSecondaryEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSecondaryEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/isSecondaryEnabled","kind":"symbol","type":"topic","url":"\/documentation\/divar\/twinbuttonsviewcontroller\/issecondaryenabled"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TwinButtonsViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TwinButtonsViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TwinButtonsViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/primaryButton","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/secondaryButton"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/primaryButtonAction(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/secondaryButtonAction(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/traitCollectionDidChange(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TwinButtonsViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TwinButtonsViewController~1traitCollectionDidChange(_:)\/title","value":"traitCollectionDidChange:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TwinButtonsViewController~1traitCollectionDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"traitCollectionDidChange:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TwinButtonsViewController~1secondaryButton\/title","value":"secondaryButton"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TwinButtonsViewController~1secondaryButton\/fragments","value":[{"kind":"identifier","text":"secondaryButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TwinButtonsViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TwinButtonsViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TwinButtonsViewController~1primaryButton\/title","value":"primaryButton"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TwinButtonsViewController~1primaryButton\/fragments","value":[{"kind":"identifier","text":"primaryButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TwinButtonsViewController~1secondaryButtonAction(_:)\/title","value":"secondaryButtonAction:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TwinButtonsViewController~1secondaryButtonAction(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"secondaryButtonAction:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TwinButtonsViewController~1primaryButtonAction(_:)\/title","value":"primaryButtonAction:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TwinButtonsViewController~1primaryButtonAction(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"primaryButtonAction:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TwinButtonsViewController\/title","value":"TwinButtonsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TwinButtonsViewController\/fragments","value":[{"kind":"identifier","text":"TwinButtonsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TwinButtonsViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TwinButtonsViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}