{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIScrollViewDirectionDelegate"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/uiscrollviewdirectiondelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandscapeWidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UIScrollViewDirectionDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UIScrollViewDirectionDelegate\/scrollView(_:didChangeHorizontalScrollingDirection:)-1cn9p","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UIScrollViewDirectionDelegate\/scrollView(_:didChangeVerticalScrollDirection:)-12mtm","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UIScrollViewDirectionDelegate\/scrollViewDirectionChangeSensitivity(_:)-6y3mz"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIScrollViewDirectionDelegate"}],"title":"UIScrollViewDirectionDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar29UIScrollViewDirectionDelegateP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"UIScrollViewDirectionDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController":{"role":"symbol","title":"PostsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostsViewController"}],"url":"\/documentation\/divar\/postsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/UIScrollViewDirectionDelegate/scrollView(_:didChangeVerticalScrollDirection:)-12mtm":{"defaultImplementations":1,"role":"symbol","title":"scrollView(_:didChangeVerticalScrollDirection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeVerticalScrollDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VerticalScrollingDirection","preciseIdentifier":"s:5Divar26VerticalScrollingDirectionO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UIScrollViewDirectionDelegate\/scrollView(_:didChangeVerticalScrollDirection:)-12mtm","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/uiscrollviewdirectiondelegate\/scrollview(_:didchangeverticalscrolldirection:)-12mtm"},"doc://com.Divar.DivarClient/documentation/Divar/UIScrollViewDirectionDelegate/scrollViewDirectionChangeSensitivity(_:)-6y3mz":{"defaultImplementations":1,"role":"symbol","title":"scrollViewDirectionChangeSensitivity(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDirectionChangeSensitivity"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"DirectionChangeSensitivity","preciseIdentifier":"s:5Divar26DirectionChangeSensitivityO"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UIScrollViewDirectionDelegate\/scrollViewDirectionChangeSensitivity(_:)-6y3mz","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/uiscrollviewdirectiondelegate\/scrollviewdirectionchangesensitivity(_:)-6y3mz"},"doc://com.Divar.DivarClient/documentation/Divar/UIScrollViewDirectionDelegate/scrollView(_:didChangeHorizontalScrollingDirection:)-1cn9p":{"defaultImplementations":1,"role":"symbol","title":"scrollView(_:didChangeHorizontalScrollingDirection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeHorizontalScrollingDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HorizontalScrollingDirection","preciseIdentifier":"s:5Divar28HorizontalScrollingDirectionO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UIScrollViewDirectionDelegate\/scrollView(_:didChangeHorizontalScrollingDirection:)-1cn9p","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/uiscrollviewdirectiondelegate\/scrollview(_:didchangehorizontalscrollingdirection:)-1cn9p"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/UIScrollViewDirectionDelegate":{"role":"symbol","title":"UIScrollViewDirectionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIScrollViewDirectionDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UIScrollViewDirectionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIScrollViewDirectionDelegate"}],"url":"\/documentation\/divar\/uiscrollviewdirectiondelegate"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController":{"role":"symbol","title":"AdvancedWidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdvancedWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdvancedWidgetViewController"}],"url":"\/documentation\/divar\/advancedwidgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/LandscapeWidgetViewController":{"role":"symbol","title":"LandscapeWidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandscapeWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandscapeWidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandscapeWidgetViewController"}],"url":"\/documentation\/divar\/landscapewidgetviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostsViewController\/title","value":"PostsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostsViewController\/fragments","value":[{"kind":"identifier","text":"PostsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController\/title","value":"AdvancedWidgetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController\/fragments","value":[{"kind":"identifier","text":"AdvancedWidgetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandscapeWidgetViewController\/title","value":"LandscapeWidgetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandscapeWidgetViewController\/fragments","value":[{"kind":"identifier","text":"LandscapeWidgetViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}