{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsedPriceFormViewControllerDelegate"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/usedpriceformviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarPriceFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceFlowController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UsedPriceFormViewControllerDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UsedPriceFormViewControllerDelegate\/lastPageCalled(with:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsedPriceFormViewControllerDelegate"}],"title":"UsedPriceFormViewControllerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar35UsedPriceFormViewControllerDelegateP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"UsedPriceFormViewControllerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/UsedPriceFormViewControllerDelegate/lastPageCalled(with:)":{"role":"symbol","title":"lastPageCalled(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastPageCalled"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UsedPriceFormViewControllerDelegate\/lastPageCalled(with:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/usedpriceformviewcontrollerdelegate\/lastpagecalled(with:)"},"doc://com.Divar.DivarClient/documentation/Divar/CarPriceFlowController":{"role":"symbol","title":"CarPriceFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarPriceFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarPriceFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarPriceFlowController"}],"url":"\/documentation\/divar\/carpriceflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PriceFlowController":{"role":"symbol","title":"PriceFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PriceFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PriceFlowController"}],"url":"\/documentation\/divar\/priceflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/UsedPriceFormViewControllerDelegate":{"role":"symbol","title":"UsedPriceFormViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsedPriceFormViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UsedPriceFormViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UsedPriceFormViewControllerDelegate"}],"url":"\/documentation\/divar\/usedpriceformviewcontrollerdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarPriceFlowController\/title","value":"CarPriceFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarPriceFlowController\/fragments","value":[{"kind":"identifier","text":"CarPriceFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceFlowController\/title","value":"PriceFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceFlowController\/fragments","value":[{"kind":"identifier","text":"PriceFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}