{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VerificationCodeInputViewControllerDelegate"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/verificationcodeinputviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FinalizeMarketplaceRegister","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShahkarLandlineVerificationFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UserRegisterFlowController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewControllerDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewControllerDelegate\/verificationCodeEnteredSuccessfully(_:with:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VerificationCodeInputViewControllerDelegate"}],"title":"VerificationCodeInputViewControllerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar43VerificationCodeInputViewControllerDelegateP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"VerificationCodeInputViewControllerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/ShahkarLandlineVerificationFlowController":{"role":"symbol","title":"ShahkarLandlineVerificationFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShahkarLandlineVerificationFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShahkarLandlineVerificationFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShahkarLandlineVerificationFlowController"}],"url":"\/documentation\/divar\/shahkarlandlineverificationflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/FinalizeMarketplaceRegister":{"role":"symbol","title":"FinalizeMarketplaceRegister","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FinalizeMarketplaceRegister"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FinalizeMarketplaceRegister","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FinalizeMarketplaceRegister"}],"url":"\/documentation\/divar\/finalizemarketplaceregister"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewControllerDelegate/verificationCodeEnteredSuccessfully(_:with:)":{"role":"symbol","title":"verificationCodeEnteredSuccessfully(_:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"verificationCodeEnteredSuccessfully"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"VerificationCodeInputViewController","preciseIdentifier":"c:@M@Divar@objc(cs)VerificationCodeInputViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewControllerDelegate\/verificationCodeEnteredSuccessfully(_:with:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontrollerdelegate\/verificationcodeenteredsuccessfully(_:with:)"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewControllerDelegate":{"role":"symbol","title":"VerificationCodeInputViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VerificationCodeInputViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VerificationCodeInputViewControllerDelegate"}],"url":"\/documentation\/divar\/verificationcodeinputviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/LandlineVerificationFlowController":{"role":"symbol","title":"LandlineVerificationFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandlineVerificationFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandlineVerificationFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandlineVerificationFlowController"}],"url":"\/documentation\/divar\/landlineverificationflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/UserRegisterFlowController":{"role":"symbol","title":"UserRegisterFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserRegisterFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UserRegisterFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserRegisterFlowController"}],"url":"\/documentation\/divar\/userregisterflowcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ShahkarLandlineVerificationFlowController\/title","value":"ShahkarLandlineVerificationFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ShahkarLandlineVerificationFlowController\/fragments","value":[{"kind":"identifier","text":"ShahkarLandlineVerificationFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandlineVerificationFlowController\/title","value":"LandlineVerificationFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandlineVerificationFlowController\/fragments","value":[{"kind":"identifier","text":"LandlineVerificationFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1UserRegisterFlowController\/title","value":"UserRegisterFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1UserRegisterFlowController\/fragments","value":[{"kind":"identifier","text":"UserRegisterFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}