{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VerificationCodeInputViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/verificationcodeinputviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/verificationcodeinputviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","doc:\/\/com.Divar.DivarClient\/6Sonnat19SubtitleRowDelegateP","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SplitButtonBarViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldViewDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/init(handler:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/bottomConstraint","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/bottomStack","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/countDownTimer","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/delegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/descriptionView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/dummyHeightConstraint","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/dummyView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/mainScrollView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/remainingBaseTime","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/remainingTime","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/requestDate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/stickyButton","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/textFieldView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/titleView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/tosSubtitleRow","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/twinButton","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/verificationCodeInput"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/accessoryToolbar()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/changeBottomStackData(from:to:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/enableButtons(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/handleKeyboardStatus(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/resetRequestDate()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/sendVerificationCode()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/textFieldValueChanges(_:shouldChangeCharactersIn:replacementString:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/timerTicks()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/validateTextField(withText:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/SplitButtonBarViewControllerDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/SubtitleRowDelegate-Implementations","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/TwinButtonsViewControllerDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VerificationCodeInputViewController"}],"title":"VerificationCodeInputViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)VerificationCodeInputViewController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"VerificationCodeInputViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/titleView":{"role":"symbol","title":"titleView","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TitleView","preciseIdentifier":"c:@M@Divar@objc(cs)TitleView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/titleView","kind":"symbol","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/titleview"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/bottomConstraint":{"role":"symbol","title":"bottomConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/bottomConstraint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bottomConstraint"}],"url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/bottomconstraint"},"doc://com.Divar.DivarClient/documentation/Divar/ShowMessageProtocol":{"role":"symbol","title":"ShowMessageProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowMessageProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowMessageProtocol"}],"url":"\/documentation\/divar\/showmessageprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/ErrorMessageHandler":{"role":"symbol","title":"ErrorMessageHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorMessageHandler"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorMessageHandler"}],"url":"\/documentation\/divar\/errormessagehandler"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/SubtitleRowDelegate-Implementations":{"role":"collectionGroup","title":"SubtitleRowDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/SubtitleRowDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/subtitlerowdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController":{"role":"symbol","title":"VerificationCodeInputViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VerificationCodeInputViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VerificationCodeInputViewController"}],"url":"\/documentation\/divar\/verificationcodeinputviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/accessoryToolbar()":{"role":"symbol","title":"accessoryToolbar()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessoryToolbar"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/accessoryToolbar()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/accessorytoolbar()"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/timerTicks()":{"role":"symbol","title":"timerTicks()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"timerTicks"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/timerTicks()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/timerticks()"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/init(handler:)":{"role":"symbol","title":"init(handler:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VerificationCodeInputProtocol","preciseIdentifier":"s:5Divar29VerificationCodeInputProtocolP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/init(handler:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/init(handler:)"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/resetRequestDate()":{"role":"symbol","title":"resetRequestDate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetRequestDate"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/resetRequestDate()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/resetrequestdate()"},"doc://com.Divar.DivarClient/6Sonnat19SubtitleRowDelegateP":{"type":"unresolvable","title":"Sonnat.SubtitleRowDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat19SubtitleRowDelegateP"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/dummyView":{"role":"symbol","title":"dummyView","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dummyView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/dummyView","kind":"symbol","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/dummyview"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/verificationCodeInput":{"role":"symbol","title":"verificationCodeInput","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"verificationCodeInput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VerificationCodeInputProtocol","preciseIdentifier":"s:5Divar29VerificationCodeInputProtocolP"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/verificationCodeInput","kind":"symbol","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/verificationcodeinput"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/descriptionView":{"role":"symbol","title":"descriptionView","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"descriptionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DescriptionView","preciseIdentifier":"c:@M@Divar@objc(cs)DescriptionView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/descriptionView","kind":"symbol","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/descriptionview"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/SplitButtonBarViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"SplitButtonBarViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/SplitButtonBarViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/splitbuttonbarviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/twinButton":{"role":"symbol","title":"twinButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"twinButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TwinButtonsViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TwinButtonsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/twinButton","kind":"symbol","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/twinbutton"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/dummyHeightConstraint":{"role":"symbol","title":"dummyHeightConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dummyHeightConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/dummyHeightConstraint","kind":"symbol","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/dummyheightconstraint"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/stickyButton":{"role":"symbol","title":"stickyButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stickyButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SplitButtonBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SplitButtonBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/stickyButton","kind":"symbol","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/stickybutton"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/handleKeyboardStatus(_:)":{"role":"symbol","title":"handleKeyboardStatus(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleKeyboardStatus"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/handleKeyboardStatus(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"handleKeyboardStatus:"}],"url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/handlekeyboardstatus(_:)"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/enableButtons(_:)":{"role":"symbol","title":"enableButtons(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableButtons"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/enableButtons(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/enablebuttons(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewControllerDelegate":{"role":"symbol","title":"TwinButtonsViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TwinButtonsViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TwinButtonsViewControllerDelegate"}],"url":"\/documentation\/divar\/twinbuttonsviewcontrollerdelegate"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController":{"role":"symbol","title":"BaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseViewController"}],"url":"\/documentation\/divar\/baseviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/mainScrollView":{"role":"symbol","title":"mainScrollView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mainScrollView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ScrollingStackView","preciseIdentifier":"c:@M@Divar@objc(cs)ScrollingStackView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/mainScrollView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mainScrollView"}],"url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/mainscrollview"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/textFieldValueChanges(_:shouldChangeCharactersIn:replacementString:)":{"role":"symbol","title":"textFieldValueChanges(_:shouldChangeCharactersIn:replacementString:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldValueChanges"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldChangeCharactersIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replacementString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/textFieldValueChanges(_:shouldChangeCharactersIn:replacementString:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/textfieldvaluechanges(_:shouldchangecharactersin:replacementstring:)"},"doc://com.Divar.DivarClient/documentation/Divar/SplitButtonBarViewControllerDelegate":{"role":"symbol","title":"SplitButtonBarViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SplitButtonBarViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SplitButtonBarViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SplitButtonBarViewControllerDelegate"}],"url":"\/documentation\/divar\/splitbuttonbarviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/PaymentSystemProtocol":{"role":"symbol","title":"PaymentSystemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSystemProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaymentSystemProtocol"}],"url":"\/documentation\/divar\/paymentsystemprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/TwinButtonsViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"TwinButtonsViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/TwinButtonsViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/twinbuttonsviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/viewdidload()"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/documentation/Divar/ShowErrorProtocol":{"role":"symbol","title":"ShowErrorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowErrorProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowErrorProtocol"}],"url":"\/documentation\/divar\/showerrorprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/changeBottomStackData(from:to:)":{"role":"symbol","title":"changeBottomStackData(from:to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeBottomStackData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ComponentViewContorller","preciseIdentifier":"s:5Divar23ComponentViewContorllera"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ComponentViewContorller","preciseIdentifier":"s:5Divar23ComponentViewContorllera"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/changeBottomStackData(from:to:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/changebottomstackdata(from:to:)"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/tosSubtitleRow":{"role":"symbol","title":"tosSubtitleRow","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"tosSubtitleRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SubtitleRow","preciseIdentifier":"c:@M@Sonnat@objc(cs)SubtitleRow"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/tosSubtitleRow","kind":"symbol","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/tossubtitlerow"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/textFieldView":{"role":"symbol","title":"textFieldView","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TextFieldView","preciseIdentifier":"c:@M@Divar@objc(cs)TextFieldView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/textFieldView","kind":"symbol","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/textfieldview"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/validateTextField(withText:)":{"role":"symbol","title":"validateTextField(withText:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validateTextField"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/validateTextField(withText:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/validatetextfield(withtext:)"},"doc://com.Divar.DivarClient/documentation/Divar/TooltipPresenter":{"role":"symbol","title":"TooltipPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TooltipPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TooltipPresenter"}],"url":"\/documentation\/divar\/tooltippresenter"},"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/documentation/Divar/TextFieldViewDelegate":{"role":"symbol","title":"TextFieldViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextFieldViewDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TextFieldViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TextFieldViewDelegate"}],"url":"\/documentation\/divar\/textfieldviewdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/sendVerificationCode()":{"role":"symbol","title":"sendVerificationCode()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendVerificationCode"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/sendVerificationCode()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/sendverificationcode()"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/init(coder:)"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/countDownTimer":{"role":"symbol","title":"countDownTimer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"countDownTimer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SwiftTimer","preciseIdentifier":"s:5Divar10SwiftTimerC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/countDownTimer","kind":"symbol","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/countdowntimer"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/remainingBaseTime":{"role":"symbol","title":"remainingBaseTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remainingBaseTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/remainingBaseTime","kind":"symbol","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/remainingbasetime"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/bottomStack":{"role":"symbol","title":"bottomStack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomStack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/bottomStack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bottomStack"}],"url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/bottomstack"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/requestDate":{"role":"symbol","title":"requestDate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/requestDate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/requestdate"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/remainingTime":{"role":"symbol","title":"remainingTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remainingTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/remainingTime","kind":"symbol","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/remainingtime"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/VerificationCodeInputViewController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VerificationCodeInputViewControllerDelegate","preciseIdentifier":"s:5Divar43VerificationCodeInputViewControllerDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/verificationcodeinputviewcontroller\/delegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"VerificationCodeInputViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"VerificationCodeInputViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"VerificationCodeInputViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/bottomConstraint","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/bottomStack","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/mainScrollView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/handleKeyboardStatus(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VerificationCodeInputViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"VerificationCodeInputViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController","preciseIdentifier":"c:@M@Divar@objc(cs)BaseViewController","text":"BaseViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VerificationCodeInputViewController~1bottomConstraint\/title","value":"bottomConstraint"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VerificationCodeInputViewController~1bottomConstraint\/fragments","value":[{"kind":"identifier","text":"bottomConstraint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VerificationCodeInputViewController\/title","value":"VerificationCodeInputViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VerificationCodeInputViewController\/fragments","value":[{"kind":"identifier","text":"VerificationCodeInputViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VerificationCodeInputViewController~1handleKeyboardStatus(_:)\/title","value":"handleKeyboardStatus:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VerificationCodeInputViewController~1handleKeyboardStatus(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleKeyboardStatus:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController\/title","value":"BaseViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController\/fragments","value":[{"kind":"identifier","text":"BaseViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VerificationCodeInputViewController~1mainScrollView\/title","value":"mainScrollView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VerificationCodeInputViewController~1mainScrollView\/fragments","value":[{"kind":"identifier","text":"mainScrollView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VerificationCodeInputViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VerificationCodeInputViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VerificationCodeInputViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VerificationCodeInputViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VerificationCodeInputViewController~1bottomStack\/title","value":"bottomStack"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VerificationCodeInputViewController~1bottomStack\/fragments","value":[{"kind":"identifier","text":"bottomStack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}