{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoiceRecorderViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/voicerecorderviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/voicerecorderviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)AVAudioPlayerDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)AVAudioRecorderDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/init(size:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/audioRecorderDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/blinkingView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/counter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/duration","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/eraseButton","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/outPutUrl","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/player","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/recorder","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/sizeOfTheView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/timer"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/audioPlayerDidFinishPlaying(_:successfully:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/cleanup()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/dismissVoice(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/handleTimerLabel()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/killTimer()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/playRecording()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/saveAudio()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/startAnimating(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/startRecording()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/stopRecording()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/updateControls()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/viewDidAppear(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/viewDidLoad()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoiceRecorderViewController"}],"title":"VoiceRecorderViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)VoiceRecorderViewController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"VoiceRecorderViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController":{"role":"symbol","title":"VoiceRecorderViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoiceRecorderViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VoiceRecorderViewController"}],"url":"\/documentation\/divar\/voicerecorderviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController/init(size:)":{"role":"symbol","title":"init(size:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/init(size:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/voicerecorderviewcontroller\/init(size:)"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController/blinkingView":{"role":"symbol","title":"blinkingView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"blinkingView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/blinkingView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"blinkingView"}],"url":"\/documentation\/divar\/voicerecorderviewcontroller\/blinkingview"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController/stopRecording()":{"role":"symbol","title":"stopRecording()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopRecording"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/stopRecording()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopRecording"}],"url":"\/documentation\/divar\/voicerecorderviewcontroller\/stoprecording()"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController/viewDidAppear(_:)":{"role":"symbol","title":"viewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/viewDidAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"url":"\/documentation\/divar\/voicerecorderviewcontroller\/viewdidappear(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController/startAnimating(_:)":{"role":"symbol","title":"startAnimating(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startAnimating"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/startAnimating(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/voicerecorderviewcontroller\/startanimating(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController/sizeOfTheView":{"role":"symbol","title":"sizeOfTheView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeOfTheView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/sizeOfTheView","kind":"symbol","type":"topic","url":"\/documentation\/divar\/voicerecorderviewcontroller\/sizeoftheview"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController/saveAudio()":{"role":"symbol","title":"saveAudio()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"saveAudio"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/saveAudio()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/voicerecorderviewcontroller\/saveaudio()"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController/audioRecorderDelegate":{"role":"symbol","title":"audioRecorderDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioRecorderDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioRecorderViewControllerDelegate","preciseIdentifier":"s:5Divar35AudioRecorderViewControllerDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/audioRecorderDelegate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/voicerecorderviewcontroller\/audiorecorderdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController/counter":{"role":"symbol","title":"counter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"counter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/counter","kind":"symbol","type":"topic","url":"\/documentation\/divar\/voicerecorderviewcontroller\/counter"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController/outPutUrl":{"role":"symbol","title":"outPutUrl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"outPutUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/outPutUrl","kind":"symbol","type":"topic","url":"\/documentation\/divar\/voicerecorderviewcontroller\/outputurl"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController/killTimer()":{"role":"symbol","title":"killTimer()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"killTimer"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/killTimer()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/voicerecorderviewcontroller\/killtimer()"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController/audioPlayerDidFinishPlaying(_:successfully:)":{"role":"symbol","title":"audioPlayerDidFinishPlaying(_:successfully:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayerDidFinishPlaying"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVAudioPlayer","preciseIdentifier":"c:objc(cs)AVAudioPlayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"successfully"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/audioPlayerDidFinishPlaying(_:successfully:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioPlayerDidFinishPlaying:successfully:"}],"url":"\/documentation\/divar\/voicerecorderviewcontroller\/audioplayerdidfinishplaying(_:successfully:)"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/voicerecorderviewcontroller\/viewdidload()"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController/recorder":{"role":"symbol","title":"recorder","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recorder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVAudioRecorder","preciseIdentifier":"c:objc(cs)AVAudioRecorder"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/recorder","kind":"symbol","type":"topic","url":"\/documentation\/divar\/voicerecorderviewcontroller\/recorder"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController/dismissVoice(_:)":{"role":"symbol","title":"dismissVoice(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissVoice"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/dismissVoice(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dismissVoice:"}],"url":"\/documentation\/divar\/voicerecorderviewcontroller\/dismissvoice(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController/eraseButton":{"role":"symbol","title":"eraseButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eraseButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/eraseButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"eraseButton"}],"url":"\/documentation\/divar\/voicerecorderviewcontroller\/erasebutton"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController/playRecording()":{"role":"symbol","title":"playRecording()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playRecording"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/playRecording()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/voicerecorderviewcontroller\/playrecording()"},"doc://com.Divar.DivarClient/objc(pl)AVAudioRecorderDelegate":{"type":"unresolvable","title":"AVAudioRecorderDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)AVAudioRecorderDelegate"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController/timer":{"role":"symbol","title":"timer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Timer","preciseIdentifier":"c:objc(cs)NSTimer"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/timer","kind":"symbol","type":"topic","url":"\/documentation\/divar\/voicerecorderviewcontroller\/timer"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController/cleanup()":{"role":"symbol","title":"cleanup()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cleanup"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/cleanup()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/voicerecorderviewcontroller\/cleanup()"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController/player":{"role":"symbol","title":"player","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVAudioPlayer","preciseIdentifier":"c:objc(cs)AVAudioPlayer"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/player","kind":"symbol","type":"topic","url":"\/documentation\/divar\/voicerecorderviewcontroller\/player"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController/startRecording()":{"role":"symbol","title":"startRecording()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startRecording"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/startRecording()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/voicerecorderviewcontroller\/startrecording()"},"doc://com.Divar.DivarClient/objc(pl)AVAudioPlayerDelegate":{"type":"unresolvable","title":"AVAudioPlayerDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)AVAudioPlayerDelegate"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/voicerecorderviewcontroller\/init(coder:)"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController/handleTimerLabel()":{"role":"symbol","title":"handleTimerLabel()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleTimerLabel"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/handleTimerLabel()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"handleTimerLabel"}],"url":"\/documentation\/divar\/voicerecorderviewcontroller\/handletimerlabel()"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController/duration":{"role":"symbol","title":"duration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/duration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"duration"}],"url":"\/documentation\/divar\/voicerecorderviewcontroller\/duration"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)UIViewController"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController/updateControls()":{"role":"symbol","title":"updateControls()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateControls"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/updateControls()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/voicerecorderviewcontroller\/updatecontrols()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"VoiceRecorderViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"VoiceRecorderViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"VoiceRecorderViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/blinkingView","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/duration","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/eraseButton"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/audioPlayerDidFinishPlaying(_:successfully:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/dismissVoice(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/handleTimerLabel()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/stopRecording()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/viewDidAppear(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)AVAudioPlayerDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)AVAudioRecorderDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoiceRecorderViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VoiceRecorderViewController\/title","value":"VoiceRecorderViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VoiceRecorderViewController\/fragments","value":[{"kind":"identifier","text":"VoiceRecorderViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VoiceRecorderViewController~1blinkingView\/title","value":"blinkingView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VoiceRecorderViewController~1blinkingView\/fragments","value":[{"kind":"identifier","text":"blinkingView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VoiceRecorderViewController~1stopRecording()\/title","value":"stopRecording"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VoiceRecorderViewController~1stopRecording()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopRecording"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VoiceRecorderViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VoiceRecorderViewController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VoiceRecorderViewController~1audioPlayerDidFinishPlaying(_:successfully:)\/title","value":"audioPlayerDidFinishPlaying:successfully:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VoiceRecorderViewController~1audioPlayerDidFinishPlaying(_:successfully:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"audioPlayerDidFinishPlaying:successfully:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VoiceRecorderViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VoiceRecorderViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VoiceRecorderViewController~1dismissVoice(_:)\/title","value":"dismissVoice:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VoiceRecorderViewController~1dismissVoice(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismissVoice:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VoiceRecorderViewController~1eraseButton\/title","value":"eraseButton"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VoiceRecorderViewController~1eraseButton\/fragments","value":[{"kind":"identifier","text":"eraseButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VoiceRecorderViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VoiceRecorderViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VoiceRecorderViewController~1handleTimerLabel()\/title","value":"handleTimerLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VoiceRecorderViewController~1handleTimerLabel()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleTimerLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VoiceRecorderViewController~1duration\/title","value":"duration"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VoiceRecorderViewController~1duration\/fragments","value":[{"kind":"identifier","text":"duration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}