{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedFilterViewControllerDelegate"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/widgetbasedfilterviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BulkLadderBaseFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentBulkLadderFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OpenPageFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateBulkLadderFlowController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedFilterViewControllerDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedFilterViewControllerDelegate\/widgetBasedFilterViewController(_:data:tag:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedFilterViewControllerDelegate"}],"title":"WidgetBasedFilterViewControllerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar39WidgetBasedFilterViewControllerDelegateP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"WidgetBasedFilterViewControllerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/OpenPageFlowController":{"role":"symbol","title":"OpenPageFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenPageFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OpenPageFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenPageFlowController"}],"url":"\/documentation\/divar\/openpageflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarAgentBulkLadderFlowController":{"role":"symbol","title":"CarAgentBulkLadderFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarAgentBulkLadderFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarAgentBulkLadderFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarAgentBulkLadderFlowController"}],"url":"\/documentation\/divar\/caragentbulkladderflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/RealEstateBulkLadderFlowController":{"role":"symbol","title":"RealEstateBulkLadderFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RealEstateBulkLadderFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RealEstateBulkLadderFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RealEstateBulkLadderFlowController"}],"url":"\/documentation\/divar\/realestatebulkladderflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedFilterViewControllerDelegate/widgetBasedFilterViewController(_:data:tag:)":{"role":"symbol","title":"widgetBasedFilterViewController(_:data:tag:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedFilterViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedFilterViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedFilterViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WidgetTag","preciseIdentifier":"s:5Divar9WidgetTagV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedFilterViewControllerDelegate\/widgetBasedFilterViewController(_:data:tag:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/widgetbasedfilterviewcontrollerdelegate\/widgetbasedfilterviewcontroller(_:data:tag:)"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedFilterViewControllerDelegate":{"role":"symbol","title":"WidgetBasedFilterViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedFilterViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedFilterViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedFilterViewControllerDelegate"}],"url":"\/documentation\/divar\/widgetbasedfilterviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/BulkLadderBaseFlowController":{"role":"symbol","title":"BulkLadderBaseFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BulkLadderBaseFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BulkLadderBaseFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BulkLadderBaseFlowController"}],"url":"\/documentation\/divar\/bulkladderbaseflowcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OpenPageFlowController\/title","value":"OpenPageFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OpenPageFlowController\/fragments","value":[{"kind":"identifier","text":"OpenPageFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentBulkLadderFlowController\/title","value":"CarAgentBulkLadderFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarAgentBulkLadderFlowController\/fragments","value":[{"kind":"identifier","text":"CarAgentBulkLadderFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateBulkLadderFlowController\/title","value":"RealEstateBulkLadderFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RealEstateBulkLadderFlowController\/fragments","value":[{"kind":"identifier","text":"RealEstateBulkLadderFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BulkLadderBaseFlowController\/title","value":"BulkLadderBaseFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BulkLadderBaseFlowController\/fragments","value":[{"kind":"identifier","text":"BulkLadderBaseFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}