{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/widgetbasedviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/widgetbasedviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetContactViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BusinessGetContactViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MobileZeroPriceViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OfflinePageViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostDetailsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostPreviewViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ClaimPostProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LoginRequiredProtocol","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RefreshableProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SplitButtonBarViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UserRegisterFlowControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WideButtonViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewControllerProtocol"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/init()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/init(coder:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/actionDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/claimToken","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/splitButtonBar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/stackHolder","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/twinButtonsBar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/wideButtonBar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/widgetCollection"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/buttonClicked(_:action:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/primaryButtonClicked(_:action:)-744lx","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/primaryButtonClicked(_:action:)-9cob","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/refreshData()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/removeAllStickyWidgets()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/secondaryButtonClicked(_:action:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/setWidgets(hidden:for:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/setupBottomStackView(for:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/setupStackHolder()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/viewDidLoad()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/widgetBasedCollectionViewController(_:canStartInfiniteScroll:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/widgetBasedCollectionViewController(_:didEndDisplaying:forIndexPath:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/widgetBasedCollectionViewController(_:didStartInfiniteScroll:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/widgetBasedCollectionViewController(_:didStartPullToRefresh:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/widgetBasedCollectionViewController(_:internalStateChangeWith:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/widgetBasedCollectionViewController(_:willDisplay:forIndexPath:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/UserRegisterFlowControllerDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedViewController"}],"title":"WidgetBasedViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)WidgetBasedViewController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"WidgetBasedViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/twinButtonsBar":{"role":"symbol","title":"twinButtonsBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"twinButtonsBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TwinButtonsViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TwinButtonsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/twinButtonsBar","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetbasedviewcontroller\/twinbuttonsbar"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/wideButtonBar":{"role":"symbol","title":"wideButtonBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"wideButtonBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WideButtonViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WideButtonViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/wideButtonBar","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetbasedviewcontroller\/widebuttonbar"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetViewController":{"role":"symbol","title":"WidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetViewController"}],"url":"\/documentation\/divar\/widgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/RefreshableProtocol":{"role":"symbol","title":"RefreshableProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RefreshableProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RefreshableProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RefreshableProtocol"}],"url":"\/documentation\/divar\/refreshableprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/secondaryButtonClicked(_:action:)":{"role":"symbol","title":"secondaryButtonClicked(_:action:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondaryButtonClicked"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TwinButtonsViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TwinButtonsViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/secondaryButtonClicked(_:action:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetbasedviewcontroller\/secondarybuttonclicked(_:action:)"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/widgetbasedviewcontroller\/viewdidload()"},"doc://com.Divar.DivarClient/documentation/Divar/WideButtonViewControllerDelegate":{"role":"symbol","title":"WideButtonViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WideButtonViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WideButtonViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WideButtonViewControllerDelegate"}],"url":"\/documentation\/divar\/widebuttonviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/splitButtonBar":{"role":"symbol","title":"splitButtonBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"splitButtonBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SplitButtonBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SplitButtonBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/splitButtonBar","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetbasedviewcontroller\/splitbuttonbar"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/widgetBasedCollectionViewController(_:didStartInfiniteScroll:)":{"role":"symbol","title":"widgetBasedCollectionViewController(_:didStartInfiniteScroll:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartInfiniteScroll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdvancedCollectionView","preciseIdentifier":"c:@M@Divar@objc(cs)AdvancedCollectionView"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/widgetBasedCollectionViewController(_:didStartInfiniteScroll:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetbasedviewcontroller\/widgetbasedcollectionviewcontroller(_:didstartinfinitescroll:)"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/setupStackHolder()":{"role":"symbol","title":"setupStackHolder()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupStackHolder"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/setupStackHolder()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetbasedviewcontroller\/setupstackholder()"},"doc://com.Divar.DivarClient/documentation/Divar/ErrorMessageHandler":{"role":"symbol","title":"ErrorMessageHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorMessageHandler"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorMessageHandler"}],"url":"\/documentation\/divar\/errormessagehandler"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/ShowMessageProtocol":{"role":"symbol","title":"ShowMessageProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowMessageProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowMessageProtocol"}],"url":"\/documentation\/divar\/showmessageprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/actionDelegate":{"role":"symbol","title":"actionDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WidgetBasedActionDelegate","preciseIdentifier":"s:5Divar25WidgetBasedActionDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/actionDelegate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetbasedviewcontroller\/actiondelegate"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewControllerDelegate":{"role":"symbol","title":"WidgetBasedCollectionViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedCollectionViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedCollectionViewControllerDelegate"}],"url":"\/documentation\/divar\/widgetbasedcollectionviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/widgetBasedCollectionViewController(_:internalStateChangeWith:)":{"role":"symbol","title":"widgetBasedCollectionViewController(_:internalStateChangeWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"internalStateChangeWith"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/widgetBasedCollectionViewController(_:internalStateChangeWith:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetbasedviewcontroller\/widgetbasedcollectionviewcontroller(_:internalstatechangewith:)"},"doc://com.Divar.DivarClient/documentation/Divar/LoginRequiredProtocol":{"role":"symbol","title":"LoginRequiredProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoginRequiredProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LoginRequiredProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LoginRequiredProtocol"}],"url":"\/documentation\/divar\/loginrequiredprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/widgetBasedCollectionViewController(_:didStartPullToRefresh:)":{"role":"symbol","title":"widgetBasedCollectionViewController(_:didStartPullToRefresh:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartPullToRefresh"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/widgetBasedCollectionViewController(_:didStartPullToRefresh:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetbasedviewcontroller\/widgetbasedcollectionviewcontroller(_:didstartpulltorefresh:)"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController":{"role":"symbol","title":"WidgetBasedViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedViewController"}],"url":"\/documentation\/divar\/widgetbasedviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/claimToken":{"role":"symbol","title":"claimToken","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"claimToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/claimToken","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetbasedviewcontroller\/claimtoken"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedPostPreviewViewController":{"role":"symbol","title":"WidgetBasedPostPreviewViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedPostPreviewViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostPreviewViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedPostPreviewViewController"}],"url":"\/documentation\/divar\/widgetbasedpostpreviewviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/divar\/widgetbasedviewcontroller\/init()"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/documentation/Divar/OfflinePageViewController":{"role":"symbol","title":"OfflinePageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflinePageViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OfflinePageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OfflinePageViewController"}],"url":"\/documentation\/divar\/offlinepageviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedPostDetailsViewController":{"role":"symbol","title":"WidgetBasedPostDetailsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedPostDetailsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostDetailsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedPostDetailsViewController"}],"url":"\/documentation\/divar\/widgetbasedpostdetailsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/buttonClicked(_:action:)":{"role":"symbol","title":"buttonClicked(_:action:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonClicked"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WideButtonViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WideButtonViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/buttonClicked(_:action:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetbasedviewcontroller\/buttonclicked(_:action:)"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/documentation/Divar/MobileZeroPriceViewController":{"role":"symbol","title":"MobileZeroPriceViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MobileZeroPriceViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MobileZeroPriceViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MobileZeroPriceViewController"}],"url":"\/documentation\/divar\/mobilezeropriceviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController":{"role":"symbol","title":"BaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseViewController"}],"url":"\/documentation\/divar\/baseviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/primaryButtonClicked(_:action:)-744lx":{"role":"symbol","title":"primaryButtonClicked(_:action:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryButtonClicked"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SplitButtonBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)SplitButtonBarViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/primaryButtonClicked(_:action:)-744lx","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetbasedviewcontroller\/primarybuttonclicked(_:action:)-744lx"},"doc://com.Divar.DivarClient/documentation/Divar/ClaimPostProtocol":{"role":"symbol","title":"ClaimPostProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClaimPostProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ClaimPostProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClaimPostProtocol"}],"url":"\/documentation\/divar\/claimpostprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/primaryButtonClicked(_:action:)-9cob":{"role":"symbol","title":"primaryButtonClicked(_:action:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryButtonClicked"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TwinButtonsViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TwinButtonsViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/primaryButtonClicked(_:action:)-9cob","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetbasedviewcontroller\/primarybuttonclicked(_:action:)-9cob"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/widgetCollection":{"role":"symbol","title":"widgetCollection","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetCollection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/widgetCollection","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetbasedviewcontroller\/widgetcollection"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/stackHolder":{"role":"symbol","title":"stackHolder","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stackHolder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/stackHolder","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetbasedviewcontroller\/stackholder"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewControllerDelegate":{"role":"symbol","title":"TwinButtonsViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TwinButtonsViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TwinButtonsViewControllerDelegate"}],"url":"\/documentation\/divar\/twinbuttonsviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/widgetBasedCollectionViewController(_:willDisplay:forIndexPath:)":{"role":"symbol","title":"widgetBasedCollectionViewController(_:willDisplay:forIndexPath:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willDisplay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Widget","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_WidgetV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forIndexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/widgetBasedCollectionViewController(_:willDisplay:forIndexPath:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetbasedviewcontroller\/widgetbasedcollectionviewcontroller(_:willdisplay:forindexpath:)"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/UserRegisterFlowControllerDelegate-Implementations":{"role":"collectionGroup","title":"UserRegisterFlowControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/UserRegisterFlowControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/widgetbasedviewcontroller\/userregisterflowcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController":{"role":"symbol","title":"ZeroPriceViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZeroPriceViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZeroPriceViewController"}],"url":"\/documentation\/divar\/zeropriceviewcontroller"},"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetContactViewController":{"role":"symbol","title":"BottomSheetContactViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BottomSheetContactViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetContactViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BottomSheetContactViewController"}],"url":"\/documentation\/divar\/bottomsheetcontactviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/refreshData()":{"role":"symbol","title":"refreshData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshData"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/refreshData()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetbasedviewcontroller\/refreshdata()"},"doc://com.Divar.DivarClient/documentation/Divar/UserRegisterFlowControllerDelegate":{"role":"symbol","title":"UserRegisterFlowControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserRegisterFlowControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UserRegisterFlowControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserRegisterFlowControllerDelegate"}],"url":"\/documentation\/divar\/userregisterflowcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController":{"role":"symbol","title":"AdvancedWidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdvancedWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdvancedWidgetViewController"}],"url":"\/documentation\/divar\/advancedwidgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/widgetBasedCollectionViewController(_:didEndDisplaying:forIndexPath:)":{"role":"symbol","title":"widgetBasedCollectionViewController(_:didEndDisplaying:forIndexPath:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEndDisplaying"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Widget","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_WidgetV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forIndexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/widgetBasedCollectionViewController(_:didEndDisplaying:forIndexPath:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetbasedviewcontroller\/widgetbasedcollectionviewcontroller(_:didenddisplaying:forindexpath:)"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/setupBottomStackView(for:)":{"role":"symbol","title":"setupBottomStackView(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupBottomStackView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StickyWidgetActionWrapper","preciseIdentifier":"s:5Divar25StickyWidgetActionWrapperV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/setupBottomStackView(for:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetbasedviewcontroller\/setupbottomstackview(for:)"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewControllerProtocol":{"role":"symbol","title":"WidgetBasedViewControllerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedViewControllerProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewControllerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedViewControllerProtocol"}],"url":"\/documentation\/divar\/widgetbasedviewcontrollerprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/widgetbasedviewcontroller\/init(coder:)"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/removeAllStickyWidgets()":{"role":"symbol","title":"removeAllStickyWidgets()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAllStickyWidgets"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/removeAllStickyWidgets()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetbasedviewcontroller\/removeallstickywidgets()"},"doc://com.Divar.DivarClient/documentation/Divar/BusinessGetContactViewController":{"role":"symbol","title":"BusinessGetContactViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BusinessGetContactViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BusinessGetContactViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BusinessGetContactViewController"}],"url":"\/documentation\/divar\/businessgetcontactviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/widgetBasedCollectionViewController(_:canStartInfiniteScroll:)":{"role":"symbol","title":"widgetBasedCollectionViewController(_:canStartInfiniteScroll:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"canStartInfiniteScroll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdvancedCollectionView","preciseIdentifier":"c:@M@Divar@objc(cs)AdvancedCollectionView"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/widgetBasedCollectionViewController(_:canStartInfiniteScroll:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetbasedviewcontroller\/widgetbasedcollectionviewcontroller(_:canstartinfinitescroll:)"},"doc://com.Divar.DivarClient/documentation/Divar/SplitButtonBarViewControllerDelegate":{"role":"symbol","title":"SplitButtonBarViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SplitButtonBarViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SplitButtonBarViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SplitButtonBarViewControllerDelegate"}],"url":"\/documentation\/divar\/splitbuttonbarviewcontrollerdelegate"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/PaymentSystemProtocol":{"role":"symbol","title":"PaymentSystemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSystemProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaymentSystemProtocol"}],"url":"\/documentation\/divar\/paymentsystemprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/ShowErrorProtocol":{"role":"symbol","title":"ShowErrorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowErrorProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowErrorProtocol"}],"url":"\/documentation\/divar\/showerrorprotocol"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController/setWidgets(hidden:for:)":{"role":"symbol","title":"setWidgets(hidden:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setWidgets"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hidden"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_StickyWidget","preciseIdentifier":"s:19DivarInterfaceSwift20Widgets_StickyWidgetV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/setWidgets(hidden:for:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetbasedviewcontroller\/setwidgets(hidden:for:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/TooltipPresenter":{"role":"symbol","title":"TooltipPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TooltipPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TooltipPresenter"}],"url":"\/documentation\/divar\/tooltippresenter"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"WidgetBasedViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"WidgetBasedViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"WidgetBasedViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/init()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetContactViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BusinessGetContactViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MobileZeroPriceViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OfflinePageViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostDetailsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostPreviewViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController","preciseIdentifier":"c:@M@Divar@objc(cs)BaseViewController","text":"BaseViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedViewController\/title","value":"WidgetBasedViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedPostPreviewViewController\/title","value":"WidgetBasedPostPreviewViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedPostPreviewViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedPostPreviewViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedViewController~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedViewController~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OfflinePageViewController\/title","value":"OfflinePageViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OfflinePageViewController\/fragments","value":[{"kind":"identifier","text":"OfflinePageViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedPostDetailsViewController\/title","value":"WidgetBasedPostDetailsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedPostDetailsViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedPostDetailsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MobileZeroPriceViewController\/title","value":"MobileZeroPriceViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MobileZeroPriceViewController\/fragments","value":[{"kind":"identifier","text":"MobileZeroPriceViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController\/title","value":"BaseViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController\/fragments","value":[{"kind":"identifier","text":"BaseViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ZeroPriceViewController\/title","value":"ZeroPriceViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ZeroPriceViewController\/fragments","value":[{"kind":"identifier","text":"ZeroPriceViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetContactViewController\/title","value":"BottomSheetContactViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetContactViewController\/fragments","value":[{"kind":"identifier","text":"BottomSheetContactViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController\/title","value":"AdvancedWidgetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController\/fragments","value":[{"kind":"identifier","text":"AdvancedWidgetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BusinessGetContactViewController\/title","value":"BusinessGetContactViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BusinessGetContactViewController\/fragments","value":[{"kind":"identifier","text":"BusinessGetContactViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}