{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetCell"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/widgetcell"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/widgetcell"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UICollectionViewCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BannerRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BlockingViewCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BooleanRateRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChipViewRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionTextRow","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/EvaluationRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/EventRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GaugeChartCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GroupFeatureRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GroupInfoRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImageCarouselCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImageSliderCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InfoRowExpandableCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LegendTitleRow","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LineChartRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoticePreviewCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceEstimationCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceRowCollectionCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RentSliderCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScoreRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchResultCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SecondaryButtonCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SectionDividerCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SelectorRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/StatefulRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/StepIndicatorRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SubscriptionRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SubtitleRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SuggestionRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TabbedLineChartCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TitleRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ToolboxCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UnexpandableRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WideButtonBarCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCellConfigurable"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/objc(pl)CALayerDelegate","doc:\/\/com.Divar.DivarClient\/6Sonnat12ReusableCellP","doc:\/\/com.Divar.DivarClient\/6Sonnat23WithInitializerProtocolP","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearance","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UICoordinateSpace","doc:\/\/com.Divar.DivarClient\/objc(pl)UIDynamicItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItemContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UILargeContentViewerItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCell","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCell\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCell\/prepareForReuse()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetCell"}],"title":"WidgetCell","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)WidgetCell","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"WidgetCell"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/UnexpandableRowCollectionViewCell":{"role":"symbol","title":"UnexpandableRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnexpandableRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UnexpandableRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UnexpandableRowCollectionViewCell"}],"url":"\/documentation\/divar\/unexpandablerowcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/TagListCollectionViewCell":{"role":"symbol","title":"TagListCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagListCollectionViewCell"}],"url":"\/documentation\/divar\/taglistcollectionviewcell"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/documentation/Divar/RentSliderCollectionViewCell":{"role":"symbol","title":"RentSliderCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RentSliderCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RentSliderCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RentSliderCollectionViewCell"}],"url":"\/documentation\/divar\/rentslidercollectionviewcell"},"doc://com.Divar.DivarClient/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAccessibilityIdentification"},"doc://com.Divar.DivarClient/documentation/Divar/GroupFeatureRowCollectionViewCell":{"role":"symbol","title":"GroupFeatureRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupFeatureRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GroupFeatureRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupFeatureRowCollectionViewCell"}],"url":"\/documentation\/divar\/groupfeaturerowcollectionviewcell"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/documentation/Divar/PriceRowCollectionCell":{"role":"symbol","title":"PriceRowCollectionCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PriceRowCollectionCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceRowCollectionCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PriceRowCollectionCell"}],"url":"\/documentation\/divar\/pricerowcollectioncell"},"doc://com.Divar.DivarClient/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)CALayerDelegate"},"doc://com.Divar.DivarClient/documentation/Divar/TabbedLineChartCollectionViewCell":{"role":"symbol","title":"TabbedLineChartCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TabbedLineChartCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TabbedLineChartCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TabbedLineChartCollectionViewCell"}],"url":"\/documentation\/divar\/tabbedlinechartcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/SuggestionRowCollectionViewCell":{"role":"symbol","title":"SuggestionRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SuggestionRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SuggestionRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SuggestionRowCollectionViewCell"}],"url":"\/documentation\/divar\/suggestionrowcollectionviewcell"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetCell/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WidgetCellDelegate","preciseIdentifier":"s:5Divar18WidgetCellDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCell\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetcell\/delegate"},"doc://com.Divar.DivarClient/documentation/Divar/GaugeChartCollectionViewCell":{"role":"symbol","title":"GaugeChartCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GaugeChartCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GaugeChartCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GaugeChartCollectionViewCell"}],"url":"\/documentation\/divar\/gaugechartcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/TitleRowCollectionViewCell":{"role":"symbol","title":"TitleRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TitleRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TitleRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TitleRowCollectionViewCell"}],"url":"\/documentation\/divar\/titlerowcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/LegendTitleRow":{"role":"symbol","title":"LegendTitleRow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LegendTitleRow"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LegendTitleRow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LegendTitleRow"}],"url":"\/documentation\/divar\/legendtitlerow"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetCell/initWithFrame:":{"role":"symbol","title":"initWithFrame:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCell\/initWithFrame:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/divar\/widgetcell\/initwithframe:"},"doc://com.Divar.DivarClient/documentation/Divar/FeatureRowCollectionViewCell":{"role":"symbol","title":"FeatureRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeatureRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeatureRowCollectionViewCell"}],"url":"\/documentation\/divar\/featurerowcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/ImageCarouselCollectionViewCell":{"role":"symbol","title":"ImageCarouselCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageCarouselCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImageCarouselCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageCarouselCollectionViewCell"}],"url":"\/documentation\/divar\/imagecarouselcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetCell":{"role":"symbol","title":"WidgetCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetCell"}],"url":"\/documentation\/divar\/widgetcell"},"doc://com.Divar.DivarClient/documentation/Divar/PostCell":{"role":"symbol","title":"PostCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostCell"}],"abstract":[{"type":"text","text":"This cell was refactored to use sonnnat "},{"type":"codeVoice","code":"PostRow"},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"xib"},{"type":"text","text":" is not needed anymore, but on "},{"type":"codeVoice","code":"WidgetBasedCollectionViewController"},{"type":"text","text":" we register all the cells from their nib names,"},{"type":"text","text":" "},{"type":"text","text":"Deleting "},{"type":"codeVoice","code":"PostRow.xib"},{"type":"text","text":" will cause crash, until we fix that registering procedure."}],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostCell"}],"url":"\/documentation\/divar\/postcell"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/documentation/Divar/PriceEstimationCollectionViewCell":{"role":"symbol","title":"PriceEstimationCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PriceEstimationCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceEstimationCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PriceEstimationCollectionViewCell"}],"url":"\/documentation\/divar\/priceestimationcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/ToolboxCollectionViewCell":{"role":"symbol","title":"ToolboxCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ToolboxCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ToolboxCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ToolboxCollectionViewCell"}],"url":"\/documentation\/divar\/toolboxcollectionviewcell"},"doc://com.Divar.DivarClient/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UILargeContentViewerItem"},"doc://com.Divar.DivarClient/documentation/Divar/WideButtonBarCollectionViewCell":{"role":"symbol","title":"WideButtonBarCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WideButtonBarCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WideButtonBarCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WideButtonBarCollectionViewCell"}],"url":"\/documentation\/divar\/widebuttonbarcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/MapRowCollectionViewCell":{"role":"symbol","title":"MapRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapRowCollectionViewCell"}],"url":"\/documentation\/divar\/maprowcollectionviewcell"},"doc://com.Divar.DivarClient/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItem"},"doc://com.Divar.DivarClient/documentation/Divar/SearchResultCollectionViewCell":{"role":"symbol","title":"SearchResultCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchResultCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchResultCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchResultCollectionViewCell"}],"url":"\/documentation\/divar\/searchresultcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/BooleanRateRowCollectionViewCell":{"role":"symbol","title":"BooleanRateRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BooleanRateRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BooleanRateRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BooleanRateRowCollectionViewCell"}],"url":"\/documentation\/divar\/booleanraterowcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/StatefulRowCollectionViewCell":{"role":"symbol","title":"StatefulRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatefulRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/StatefulRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatefulRowCollectionViewCell"}],"url":"\/documentation\/divar\/statefulrowcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetCell/prepareForReuse()":{"role":"symbol","title":"prepareForReuse()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareForReuse"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCell\/prepareForReuse()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prepareForReuse"}],"url":"\/documentation\/divar\/widgetcell\/prepareforreuse()"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetCellConfigurable":{"role":"symbol","title":"WidgetCellConfigurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetCellConfigurable"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCellConfigurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetCellConfigurable"}],"url":"\/documentation\/divar\/widgetcellconfigurable"},"doc://com.Divar.DivarClient/documentation/Divar/LineChartRowCollectionViewCell":{"role":"symbol","title":"LineChartRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineChartRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LineChartRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LineChartRowCollectionViewCell"}],"url":"\/documentation\/divar\/linechartrowcollectionviewcell"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/SubscriptionRowCollectionViewCell":{"role":"symbol","title":"SubscriptionRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubscriptionRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SubscriptionRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SubscriptionRowCollectionViewCell"}],"url":"\/documentation\/divar\/subscriptionrowcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/SectionDividerCollectionViewCell":{"role":"symbol","title":"SectionDividerCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SectionDividerCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SectionDividerCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SectionDividerCollectionViewCell"}],"url":"\/documentation\/divar\/sectiondividercollectionviewcell"},"doc://com.Divar.DivarClient/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusItemContainer"},"doc://com.Divar.DivarClient/documentation/Divar/BlockingViewCollectionViewCell":{"role":"symbol","title":"BlockingViewCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BlockingViewCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BlockingViewCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BlockingViewCollectionViewCell"}],"url":"\/documentation\/divar\/blockingviewcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/SubtitleRowCollectionViewCell":{"role":"symbol","title":"SubtitleRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubtitleRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SubtitleRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SubtitleRowCollectionViewCell"}],"url":"\/documentation\/divar\/subtitlerowcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/ScoreRowCollectionViewCell":{"role":"symbol","title":"ScoreRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScoreRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScoreRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScoreRowCollectionViewCell"}],"url":"\/documentation\/divar\/scorerowcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/GroupInfoRowCollectionViewCell":{"role":"symbol","title":"GroupInfoRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupInfoRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GroupInfoRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupInfoRowCollectionViewCell"}],"url":"\/documentation\/divar\/groupinforowcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/InfoRowExpandableCollectionViewCell":{"role":"symbol","title":"InfoRowExpandableCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InfoRowExpandableCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InfoRowExpandableCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InfoRowExpandableCollectionViewCell"}],"url":"\/documentation\/divar\/inforowexpandablecollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/RateRowCollectionViewCell":{"role":"symbol","title":"RateRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RateRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RateRowCollectionViewCell"}],"url":"\/documentation\/divar\/raterowcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/BannerRowCollectionViewCell":{"role":"symbol","title":"BannerRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BannerRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BannerRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BannerRowCollectionViewCell"}],"url":"\/documentation\/divar\/bannerrowcollectionviewcell"},"doc://com.Divar.DivarClient/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIDynamicItem"},"doc://com.Divar.DivarClient/documentation/Divar/StepIndicatorRowCollectionViewCell":{"role":"symbol","title":"StepIndicatorRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StepIndicatorRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/StepIndicatorRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StepIndicatorRowCollectionViewCell"}],"url":"\/documentation\/divar\/stepindicatorrowcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/NoteRowCollectionViewCell":{"role":"symbol","title":"NoteRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NoteRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NoteRowCollectionViewCell"}],"url":"\/documentation\/divar\/noterowcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/ChipViewRowCollectionViewCell":{"role":"symbol","title":"ChipViewRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChipViewRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChipViewRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChipViewRowCollectionViewCell"}],"url":"\/documentation\/divar\/chipviewrowcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UICoordinateSpace"},"doc://com.Divar.DivarClient/documentation/Divar/SecondaryButtonCollectionViewCell":{"role":"symbol","title":"SecondaryButtonCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SecondaryButtonCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SecondaryButtonCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SecondaryButtonCollectionViewCell"}],"url":"\/documentation\/divar\/secondarybuttoncollectionviewcell"},"doc://com.Divar.DivarClient/6Sonnat23WithInitializerProtocolP":{"type":"unresolvable","title":"Sonnat.WithInitializerProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat23WithInitializerProtocolP"},"doc://com.Divar.DivarClient/documentation/Divar/SelectorRowCollectionViewCell":{"role":"symbol","title":"SelectorRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SelectorRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SelectorRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SelectorRowCollectionViewCell"}],"url":"\/documentation\/divar\/selectorrowcollectionviewcell"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/6Sonnat12ReusableCellP":{"type":"unresolvable","title":"Sonnat.ReusableCell","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat12ReusableCellP"},"doc://com.Divar.DivarClient/documentation/Divar/EvaluationRowCollectionViewCell":{"role":"symbol","title":"EvaluationRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EvaluationRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/EvaluationRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EvaluationRowCollectionViewCell"}],"url":"\/documentation\/divar\/evaluationrowcollectionviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/DescriptionTextRow":{"role":"symbol","title":"DescriptionTextRow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DescriptionTextRow"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionTextRow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DescriptionTextRow"}],"url":"\/documentation\/divar\/descriptiontextrow"},"doc://com.Divar.DivarClient/documentation/Divar/NoticePreviewCollectionViewCell":{"role":"symbol","title":"NoticePreviewCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NoticePreviewCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoticePreviewCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NoticePreviewCollectionViewCell"}],"url":"\/documentation\/divar\/noticepreviewcollectionviewcell"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/objc(cs)UICollectionViewCell":{"type":"unresolvable","title":"UICollectionViewCell","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)UICollectionViewCell"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/ImageSliderCollectionViewCell":{"role":"symbol","title":"ImageSliderCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSliderCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImageSliderCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageSliderCollectionViewCell"}],"url":"\/documentation\/divar\/imageslidercollectionviewcell"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetCell/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCell\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/widgetcell\/initwithcoder:"},"doc://com.Divar.DivarClient/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearance"},"doc://com.Divar.DivarClient/documentation/Divar/EventRowCollectionViewCell":{"role":"symbol","title":"EventRowCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventRowCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/EventRowCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EventRowCollectionViewCell"}],"url":"\/documentation\/divar\/eventrowcollectionviewcell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"WidgetCell"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"WidgetCell"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"WidgetCell"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCell\/initWithCoder:","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCell\/initWithFrame:","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCell\/prepareForReuse()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UICollectionViewCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BannerRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BlockingViewCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BooleanRateRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChipViewRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DescriptionTextRow","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/EvaluationRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/EventRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FeatureRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GaugeChartCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GroupFeatureRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GroupInfoRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImageCarouselCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ImageSliderCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InfoRowExpandableCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LegendTitleRow","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LineChartRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MapRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoticePreviewCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceEstimationCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceRowCollectionCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RentSliderCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScoreRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SearchResultCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SecondaryButtonCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SectionDividerCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SelectorRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/StatefulRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/StepIndicatorRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SubscriptionRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SubtitleRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SuggestionRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TabbedLineChartCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TagListCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TitleRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ToolboxCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UnexpandableRowCollectionViewCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WideButtonBarCollectionViewCell"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetCell"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1UnexpandableRowCollectionViewCell\/title","value":"UnexpandableRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1UnexpandableRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"UnexpandableRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListCollectionViewCell\/title","value":"TagListCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TagListCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"TagListCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RentSliderCollectionViewCell\/title","value":"RentSliderCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RentSliderCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"RentSliderCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GroupFeatureRowCollectionViewCell\/title","value":"GroupFeatureRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GroupFeatureRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"GroupFeatureRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceRowCollectionCell\/title","value":"PriceRowCollectionCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceRowCollectionCell\/fragments","value":[{"kind":"identifier","text":"PriceRowCollectionCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TabbedLineChartCollectionViewCell\/title","value":"TabbedLineChartCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TabbedLineChartCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"TabbedLineChartCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SuggestionRowCollectionViewCell\/title","value":"SuggestionRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SuggestionRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"SuggestionRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GaugeChartCollectionViewCell\/title","value":"GaugeChartCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GaugeChartCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"GaugeChartCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TitleRowCollectionViewCell\/title","value":"TitleRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TitleRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"TitleRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LegendTitleRow\/title","value":"LegendTitleRow"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LegendTitleRow\/fragments","value":[{"kind":"identifier","text":"LegendTitleRow"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell\/title","value":"FeatureRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1FeatureRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"FeatureRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImageCarouselCollectionViewCell\/title","value":"ImageCarouselCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImageCarouselCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"ImageCarouselCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetCell\/title","value":"WidgetCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetCell\/fragments","value":[{"kind":"identifier","text":"WidgetCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostCell\/title","value":"PostCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostCell\/fragments","value":[{"kind":"identifier","text":"PostCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceEstimationCollectionViewCell\/title","value":"PriceEstimationCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceEstimationCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"PriceEstimationCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ToolboxCollectionViewCell\/title","value":"ToolboxCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ToolboxCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"ToolboxCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WideButtonBarCollectionViewCell\/title","value":"WideButtonBarCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WideButtonBarCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"WideButtonBarCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapRowCollectionViewCell\/title","value":"MapRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MapRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"MapRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchResultCollectionViewCell\/title","value":"SearchResultCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SearchResultCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"SearchResultCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BooleanRateRowCollectionViewCell\/title","value":"BooleanRateRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BooleanRateRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"BooleanRateRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1StatefulRowCollectionViewCell\/title","value":"StatefulRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1StatefulRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"StatefulRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetCell~1prepareForReuse()\/title","value":"prepareForReuse"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetCell~1prepareForReuse()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareForReuse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LineChartRowCollectionViewCell\/title","value":"LineChartRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LineChartRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"LineChartRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SubscriptionRowCollectionViewCell\/title","value":"SubscriptionRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SubscriptionRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"SubscriptionRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SectionDividerCollectionViewCell\/title","value":"SectionDividerCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SectionDividerCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"SectionDividerCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BlockingViewCollectionViewCell\/title","value":"BlockingViewCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BlockingViewCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"BlockingViewCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SubtitleRowCollectionViewCell\/title","value":"SubtitleRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SubtitleRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"SubtitleRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScoreRowCollectionViewCell\/title","value":"ScoreRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScoreRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"ScoreRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GroupInfoRowCollectionViewCell\/title","value":"GroupInfoRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GroupInfoRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"GroupInfoRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InfoRowExpandableCollectionViewCell\/title","value":"InfoRowExpandableCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InfoRowExpandableCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"InfoRowExpandableCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowCollectionViewCell\/title","value":"RateRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"RateRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BannerRowCollectionViewCell\/title","value":"BannerRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BannerRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"BannerRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1StepIndicatorRowCollectionViewCell\/title","value":"StepIndicatorRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1StepIndicatorRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"StepIndicatorRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteRowCollectionViewCell\/title","value":"NoteRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"NoteRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChipViewRowCollectionViewCell\/title","value":"ChipViewRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ChipViewRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"ChipViewRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SecondaryButtonCollectionViewCell\/title","value":"SecondaryButtonCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SecondaryButtonCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"SecondaryButtonCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SelectorRowCollectionViewCell\/title","value":"SelectorRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SelectorRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"SelectorRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1EvaluationRowCollectionViewCell\/title","value":"EvaluationRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1EvaluationRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"EvaluationRowCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DescriptionTextRow\/title","value":"DescriptionTextRow"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DescriptionTextRow\/fragments","value":[{"kind":"identifier","text":"DescriptionTextRow"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoticePreviewCollectionViewCell\/title","value":"NoticePreviewCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoticePreviewCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"NoticePreviewCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImageSliderCollectionViewCell\/title","value":"ImageSliderCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ImageSliderCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"ImageSliderCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1EventRowCollectionViewCell\/title","value":"EventRowCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1EventRowCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"EventRowCollectionViewCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}