{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedNavigationBarPresenterProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/widgetbasednavigationbarpresenterprotocol"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FinalizeMarketplaceRegister","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandscapeWidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SegmentedBulkLadderViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedSegmentedViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedNavigationBarPresenterProtocol","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedNavigationBarPresenterProtocol\/barButtonItemButtonTappedSelector","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedNavigationBarPresenterProtocol\/barButtonItemTappedSelector","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedNavigationBarPresenterProtocol\/isDarkMode","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedNavigationBarPresenterProtocol\/navigationBarItems"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedNavigationBarPresenterProtocol\/setupNavigationBarItems(data:)-2yc96"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedNavigationBarPresenterProtocol"}],"title":"WidgetBasedNavigationBarPresenterProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar41WidgetBasedNavigationBarPresenterProtocolP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"WidgetBasedNavigationBarPresenterProtocol"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedNavigationBarPresenterProtocol/isDarkMode":{"role":"symbol","title":"isDarkMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDarkMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedNavigationBarPresenterProtocol\/isDarkMode","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/widgetbasednavigationbarpresenterprotocol\/isdarkmode"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedNavigationBarPresenterProtocol":{"role":"symbol","title":"WidgetBasedNavigationBarPresenterProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedNavigationBarPresenterProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedNavigationBarPresenterProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedNavigationBarPresenterProtocol"}],"url":"\/documentation\/divar\/widgetbasednavigationbarpresenterprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/FinalizeMarketplaceRegister":{"role":"symbol","title":"FinalizeMarketplaceRegister","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FinalizeMarketplaceRegister"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FinalizeMarketplaceRegister","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FinalizeMarketplaceRegister"}],"url":"\/documentation\/divar\/finalizemarketplaceregister"},"doc://com.Divar.DivarClient/documentation/Divar/DisablePageViewController":{"role":"symbol","title":"DisablePageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisablePageViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DisablePageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DisablePageViewController"}],"url":"\/documentation\/divar\/disablepageviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SegmentedBulkLadderViewController":{"conformance":{"constraints":[{"type":"codeVoice","code":"TabbarPageResponse"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"_Extractor"},{"type":"text","text":", "},{"type":"codeVoice","code":"TabbarPageResponse"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Message"},{"type":"text","text":", "},{"type":"codeVoice","code":"PageResponseType"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"_Extractor"},{"type":"text","text":", "},{"type":"codeVoice","code":"PageResponseType"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Message"},{"type":"text","text":", "},{"type":"codeVoice","code":"SubmitResponseType"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"_Extractor"},{"type":"text","text":", "},{"type":"codeVoice","code":"SubmitResponseType"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Message"},{"type":"text","text":", "},{"type":"codeVoice","code":"SinglePage"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"_Extractor"},{"type":"text","text":", and "},{"type":"codeVoice","code":"SinglePage"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Message"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"SegmentedBulkLadderViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SegmentedBulkLadderViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SegmentedBulkLadderViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SegmentedBulkLadderViewController"}],"url":"\/documentation\/divar\/segmentedbulkladderviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedSegmentedViewController":{"role":"symbol","title":"WidgetBasedSegmentedViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedSegmentedViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedSegmentedViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedSegmentedViewController"}],"url":"\/documentation\/divar\/widgetbasedsegmentedviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedNavigationBarPresenterProtocol/setupNavigationBarItems(data:)-2yc96":{"defaultImplementations":1,"role":"symbol","title":"setupNavigationBarItems(data:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupNavigationBarItems"},{"kind":"text","text":"("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Widgets_NavigationBar","preciseIdentifier":"s:19DivarInterfaceSwift21Widgets_NavigationBarV"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedNavigationBarPresenterProtocol\/setupNavigationBarItems(data:)-2yc96","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/widgetbasednavigationbarpresenterprotocol\/setupnavigationbaritems(data:)-2yc96"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedNavigationBarPresenterProtocol/barButtonItemTappedSelector":{"role":"symbol","title":"barButtonItemTappedSelector","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"barButtonItemTappedSelector"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedNavigationBarPresenterProtocol\/barButtonItemTappedSelector","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/widgetbasednavigationbarpresenterprotocol\/barbuttonitemtappedselector"},"doc://com.Divar.DivarClient/objc(cs)UIViewController":{"type":"unresolvable","title":"UIKit.UIViewController","identifier":"doc:\/\/com.Divar.DivarClient\/objc(cs)UIViewController"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetViewController":{"conformance":{"constraints":[{"type":"codeVoice","code":"ResponseType"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"_Extractor"},{"type":"text","text":" and "},{"type":"codeVoice","code":"Message"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"WidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetViewController"}],"url":"\/documentation\/divar\/widgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedNavigationBarPresenterProtocol/barButtonItemButtonTappedSelector":{"role":"symbol","title":"barButtonItemButtonTappedSelector","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"barButtonItemButtonTappedSelector"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedNavigationBarPresenterProtocol\/barButtonItemButtonTappedSelector","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/widgetbasednavigationbarpresenterprotocol\/barbuttonitembuttontappedselector"},"doc://com.Divar.DivarClient/documentation/Divar/LandscapeWidgetViewController":{"role":"symbol","title":"LandscapeWidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandscapeWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandscapeWidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandscapeWidgetViewController"}],"url":"\/documentation\/divar\/landscapewidgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedNavigationBarPresenterProtocol/navigationBarItems":{"role":"symbol","title":"navigationBarItems","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationBarItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Widgets_NavigationBar","preciseIdentifier":"s:19DivarInterfaceSwift21Widgets_NavigationBarV"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedNavigationBarPresenterProtocol\/navigationBarItems","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/widgetbasednavigationbarpresenterprotocol\/navigationbaritems"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController":{"role":"symbol","title":"AdvancedWidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdvancedWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdvancedWidgetViewController"}],"url":"\/documentation\/divar\/advancedwidgetviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DisablePageViewController\/title","value":"DisablePageViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DisablePageViewController\/fragments","value":[{"kind":"identifier","text":"DisablePageViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedSegmentedViewController\/title","value":"WidgetBasedSegmentedViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedSegmentedViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedSegmentedViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandscapeWidgetViewController\/title","value":"LandscapeWidgetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandscapeWidgetViewController\/fragments","value":[{"kind":"identifier","text":"LandscapeWidgetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController\/title","value":"AdvancedWidgetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController\/fragments","value":[{"kind":"identifier","text":"AdvancedWidgetViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}