{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetCellDelegate"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/widgetcelldelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AlakBaseCell","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCellDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCellDelegate\/callParent(action:widget:)-5az89","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCellDelegate\/callParent(action:widget:actionLogCoordinator:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCellDelegate\/internalStateChanges(widget:parameters:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCellDelegate\/reloadSelf(_:newWidget:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetCellDelegate"}],"title":"WidgetCellDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar18WidgetCellDelegateP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"WidgetCellDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/WidgetCellDelegate/internalStateChanges(widget:parameters:)":{"role":"symbol","title":"internalStateChanges(widget:parameters:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalStateChanges"},{"kind":"text","text":"("},{"kind":"externalParam","text":"widget"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Widget","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_WidgetV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"parameters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCellDelegate\/internalStateChanges(widget:parameters:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/widgetcelldelegate\/internalstatechanges(widget:parameters:)"},"doc://com.Divar.DivarClient/documentation/Divar/AlakBaseCell":{"role":"symbol","title":"AlakBaseCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlakBaseCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AlakBaseCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AlakBaseCell"}],"url":"\/documentation\/divar\/alakbasecell"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetCellDelegate/callParent(action:widget:)-5az89":{"defaultImplementations":1,"role":"symbol","title":"callParent(action:widget:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"callParent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CustomAction","preciseIdentifier":"s:5Divar12CustomActionV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"widget"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Widget","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_WidgetV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCellDelegate\/callParent(action:widget:)-5az89","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/widgetcelldelegate\/callparent(action:widget:)-5az89"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PostsViewController":{"role":"symbol","title":"PostsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostsViewController"}],"url":"\/documentation\/divar\/postsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetCellDelegate/callParent(action:widget:actionLogCoordinator:)":{"role":"symbol","title":"callParent(action:widget:actionLogCoordinator:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"callParent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Action","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_ActionV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"widget"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Widget","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_WidgetV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"actionLogCoordinator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActionLog_ActionLogCoordinator","preciseIdentifier":"s:19DivarInterfaceSwift010ActionLog_dE11CoordinatorV"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCellDelegate\/callParent(action:widget:actionLogCoordinator:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/widgetcelldelegate\/callparent(action:widget:actionlogcoordinator:)"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetCellDelegate":{"role":"symbol","title":"WidgetCellDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetCellDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCellDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetCellDelegate"}],"url":"\/documentation\/divar\/widgetcelldelegate"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetCellDelegate/reloadSelf(_:newWidget:)":{"role":"symbol","title":"reloadSelf(_:newWidget:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reloadSelf"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetCell","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newWidget"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Widget","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_WidgetV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetCellDelegate\/reloadSelf(_:newWidget:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/widgetcelldelegate\/reloadself(_:newwidget:)"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewController":{"role":"symbol","title":"WidgetBasedCollectionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedCollectionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedCollectionViewController"}],"url":"\/documentation\/divar\/widgetbasedcollectionviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostsViewController\/title","value":"PostsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostsViewController\/fragments","value":[{"kind":"identifier","text":"PostsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedCollectionViewController\/title","value":"WidgetBasedCollectionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedCollectionViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedCollectionViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}