{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedCollectionViewControllerDelegate"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/widgetbasedcollectionviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetContactViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BusinessGetContactViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FinalizeMarketplaceRegister","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandscapeWidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MobileZeroPriceViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OfflinePageViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SelectablePostsListViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostDetailsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostPreviewViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate\/actionDelegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate\/widgetBasedCollectionViewController(_:canStartInfiniteScroll:)-1vkth","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate\/widgetBasedCollectionViewController(_:didDeselectItemAt:withData:)-6ipxh","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate\/widgetBasedCollectionViewController(_:didEndDisplaying:forIndexPath:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate\/widgetBasedCollectionViewController(_:didSelectItemAt:withData:)-4tpd4","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate\/widgetBasedCollectionViewController(_:didStartInfiniteScroll:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate\/widgetBasedCollectionViewController(_:didStartPullToRefresh:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate\/widgetBasedCollectionViewController(_:internalStateChangeWith:)-4e0ub","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate\/widgetBasedCollectionViewController(_:shouldSelectItemAt:withData:)-67sen","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate\/widgetBasedCollectionViewController(_:willDisplay:forIndexPath:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedCollectionViewControllerDelegate"}],"title":"WidgetBasedCollectionViewControllerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:5Divar43WidgetBasedCollectionViewControllerDelegateP","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"WidgetBasedCollectionViewControllerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/OfflinePageViewController":{"role":"symbol","title":"OfflinePageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflinePageViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/OfflinePageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OfflinePageViewController"}],"url":"\/documentation\/divar\/offlinepageviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/FinalizeMarketplaceRegister":{"role":"symbol","title":"FinalizeMarketplaceRegister","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FinalizeMarketplaceRegister"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/FinalizeMarketplaceRegister","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FinalizeMarketplaceRegister"}],"url":"\/documentation\/divar\/finalizemarketplaceregister"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedPostPreviewViewController":{"role":"symbol","title":"WidgetBasedPostPreviewViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedPostPreviewViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostPreviewViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedPostPreviewViewController"}],"url":"\/documentation\/divar\/widgetbasedpostpreviewviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController":{"role":"symbol","title":"AdvancedWidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdvancedWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdvancedWidgetViewController"}],"url":"\/documentation\/divar\/advancedwidgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/DealerSubscriptionViewController":{"role":"symbol","title":"DealerSubscriptionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DealerSubscriptionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DealerSubscriptionViewController"}],"url":"\/documentation\/divar\/dealersubscriptionviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewControllerDelegate/widgetBasedCollectionViewController(_:didDeselectItemAt:withData:)-6ipxh":{"defaultImplementations":1,"role":"symbol","title":"widgetBasedCollectionViewController(_:didDeselectItemAt:withData:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDeselectItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Widget","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_WidgetV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate\/widgetBasedCollectionViewController(_:didDeselectItemAt:withData:)-6ipxh","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/widgetbasedcollectionviewcontrollerdelegate\/widgetbasedcollectionviewcontroller(_:diddeselectitemat:withdata:)-6ipxh"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewControllerDelegate/actionDelegate":{"role":"symbol","title":"actionDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WidgetBasedActionDelegate","preciseIdentifier":"s:5Divar25WidgetBasedActionDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate\/actionDelegate","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/widgetbasedcollectionviewcontrollerdelegate\/actiondelegate"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewControllerDelegate/widgetBasedCollectionViewController(_:willDisplay:forIndexPath:)":{"role":"symbol","title":"widgetBasedCollectionViewController(_:willDisplay:forIndexPath:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willDisplay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Widget","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_WidgetV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forIndexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate\/widgetBasedCollectionViewController(_:willDisplay:forIndexPath:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/widgetbasedcollectionviewcontrollerdelegate\/widgetbasedcollectionviewcontroller(_:willdisplay:forindexpath:)"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController":{"role":"symbol","title":"ZeroPriceViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZeroPriceViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZeroPriceViewController"}],"url":"\/documentation\/divar\/zeropriceviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewControllerDelegate/widgetBasedCollectionViewController(_:canStartInfiniteScroll:)-1vkth":{"defaultImplementations":1,"role":"symbol","title":"widgetBasedCollectionViewController(_:canStartInfiniteScroll:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"canStartInfiniteScroll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdvancedCollectionView","preciseIdentifier":"c:@M@Divar@objc(cs)AdvancedCollectionView"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate\/widgetBasedCollectionViewController(_:canStartInfiniteScroll:)-1vkth","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/widgetbasedcollectionviewcontrollerdelegate\/widgetbasedcollectionviewcontroller(_:canstartinfinitescroll:)-1vkth"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewControllerDelegate/widgetBasedCollectionViewController(_:didEndDisplaying:forIndexPath:)":{"role":"symbol","title":"widgetBasedCollectionViewController(_:didEndDisplaying:forIndexPath:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEndDisplaying"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Widget","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_WidgetV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forIndexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate\/widgetBasedCollectionViewController(_:didEndDisplaying:forIndexPath:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/widgetbasedcollectionviewcontrollerdelegate\/widgetbasedcollectionviewcontroller(_:didenddisplaying:forindexpath:)"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewControllerDelegate/widgetBasedCollectionViewController(_:didStartInfiniteScroll:)":{"role":"symbol","title":"widgetBasedCollectionViewController(_:didStartInfiniteScroll:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartInfiniteScroll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdvancedCollectionView","preciseIdentifier":"c:@M@Divar@objc(cs)AdvancedCollectionView"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate\/widgetBasedCollectionViewController(_:didStartInfiniteScroll:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/widgetbasedcollectionviewcontrollerdelegate\/widgetbasedcollectionviewcontroller(_:didstartinfinitescroll:)"},"doc://com.Divar.DivarClient/documentation/Divar/MobileZeroPriceViewController":{"role":"symbol","title":"MobileZeroPriceViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MobileZeroPriceViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MobileZeroPriceViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MobileZeroPriceViewController"}],"url":"\/documentation\/divar\/mobilezeropriceviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewControllerDelegate/widgetBasedCollectionViewController(_:didStartPullToRefresh:)":{"role":"symbol","title":"widgetBasedCollectionViewController(_:didStartPullToRefresh:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartPullToRefresh"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate\/widgetBasedCollectionViewController(_:didStartPullToRefresh:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/widgetbasedcollectionviewcontrollerdelegate\/widgetbasedcollectionviewcontroller(_:didstartpulltorefresh:)"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController":{"role":"symbol","title":"WidgetBasedViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedViewController"}],"url":"\/documentation\/divar\/widgetbasedviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetViewController":{"role":"symbol","title":"WidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetViewController"}],"url":"\/documentation\/divar\/widgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewControllerDelegate/widgetBasedCollectionViewController(_:didSelectItemAt:withData:)-4tpd4":{"defaultImplementations":1,"role":"symbol","title":"widgetBasedCollectionViewController(_:didSelectItemAt:withData:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Widget","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_WidgetV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate\/widgetBasedCollectionViewController(_:didSelectItemAt:withData:)-4tpd4","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/widgetbasedcollectionviewcontrollerdelegate\/widgetbasedcollectionviewcontroller(_:didselectitemat:withdata:)-4tpd4"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedPostDetailsViewController":{"role":"symbol","title":"WidgetBasedPostDetailsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedPostDetailsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostDetailsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedPostDetailsViewController"}],"url":"\/documentation\/divar\/widgetbasedpostdetailsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BottomSheetContactViewController":{"role":"symbol","title":"BottomSheetContactViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BottomSheetContactViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BottomSheetContactViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BottomSheetContactViewController"}],"url":"\/documentation\/divar\/bottomsheetcontactviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewControllerDelegate":{"role":"symbol","title":"WidgetBasedCollectionViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedCollectionViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedCollectionViewControllerDelegate"}],"url":"\/documentation\/divar\/widgetbasedcollectionviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/SelectablePostsListViewController":{"conformance":{"constraints":[{"type":"codeVoice","code":"SelectableItemType"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"SelectablePostsListItem"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"SelectablePostsListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SelectablePostsListViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SelectablePostsListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SelectablePostsListViewController"}],"url":"\/documentation\/divar\/selectablepostslistviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewControllerDelegate/widgetBasedCollectionViewController(_:internalStateChangeWith:)-4e0ub":{"defaultImplementations":1,"role":"symbol","title":"widgetBasedCollectionViewController(_:internalStateChangeWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"internalStateChangeWith"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate\/widgetBasedCollectionViewController(_:internalStateChangeWith:)-4e0ub","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/widgetbasedcollectionviewcontrollerdelegate\/widgetbasedcollectionviewcontroller(_:internalstatechangewith:)-4e0ub"},"doc://com.Divar.DivarClient/documentation/Divar/BusinessGetContactViewController":{"role":"symbol","title":"BusinessGetContactViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BusinessGetContactViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BusinessGetContactViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BusinessGetContactViewController"}],"url":"\/documentation\/divar\/businessgetcontactviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/LandscapeWidgetViewController":{"role":"symbol","title":"LandscapeWidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LandscapeWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LandscapeWidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LandscapeWidgetViewController"}],"url":"\/documentation\/divar\/landscapewidgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewControllerDelegate/widgetBasedCollectionViewController(_:shouldSelectItemAt:withData:)-67sen":{"defaultImplementations":1,"role":"symbol","title":"widgetBasedCollectionViewController(_:shouldSelectItemAt:withData:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldSelectItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Widget","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_WidgetV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate\/widgetBasedCollectionViewController(_:shouldSelectItemAt:withData:)-67sen","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/widgetbasedcollectionviewcontrollerdelegate\/widgetbasedcollectionviewcontroller(_:shouldselectitemat:withdata:)-67sen"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OfflinePageViewController\/title","value":"OfflinePageViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1OfflinePageViewController\/fragments","value":[{"kind":"identifier","text":"OfflinePageViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedPostPreviewViewController\/title","value":"WidgetBasedPostPreviewViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedPostPreviewViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedPostPreviewViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController\/title","value":"AdvancedWidgetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController\/fragments","value":[{"kind":"identifier","text":"AdvancedWidgetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubscriptionViewController\/title","value":"DealerSubscriptionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubscriptionViewController\/fragments","value":[{"kind":"identifier","text":"DealerSubscriptionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ZeroPriceViewController\/title","value":"ZeroPriceViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ZeroPriceViewController\/fragments","value":[{"kind":"identifier","text":"ZeroPriceViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MobileZeroPriceViewController\/title","value":"MobileZeroPriceViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MobileZeroPriceViewController\/fragments","value":[{"kind":"identifier","text":"MobileZeroPriceViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedViewController\/title","value":"WidgetBasedViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedPostDetailsViewController\/title","value":"WidgetBasedPostDetailsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedPostDetailsViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedPostDetailsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetContactViewController\/title","value":"BottomSheetContactViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BottomSheetContactViewController\/fragments","value":[{"kind":"identifier","text":"BottomSheetContactViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BusinessGetContactViewController\/title","value":"BusinessGetContactViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BusinessGetContactViewController\/fragments","value":[{"kind":"identifier","text":"BusinessGetContactViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandscapeWidgetViewController\/title","value":"LandscapeWidgetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1LandscapeWidgetViewController\/fragments","value":[{"kind":"identifier","text":"LandscapeWidgetViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}