{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"XMLHttpRequestProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"JSExport","preciseIdentifier":"c:objc(pl)JSExport"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/xmlhttprequestprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/xmlhttprequestprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)JSExport"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequest-swift.class"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/onerror","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/onload","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/onreadystatechange","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/readyState","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/responseText","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/status"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/getAllResponseHeaders()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/getReponseHeader(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/open(_:_:_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/send(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/setRequestHeader(_:_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"XMLHttpRequestProtocol"}],"title":"XMLHttpRequestProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)XMLHttpRequest","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"XMLHttpRequestProtocol"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/XMLHttpRequestProtocol/onload":{"navigatorTitle":[{"kind":"identifier","text":"onload"}],"role":"symbol","title":"onload","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JSValue","preciseIdentifier":"c:objc(cs)JSValue"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/onload","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/xmlhttprequestprotocol\/onload"},"doc://com.Divar.DivarClient/documentation/Divar/XMLHttpRequestProtocol":{"role":"symbol","title":"XMLHttpRequestProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"XMLHttpRequestProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"XMLHttpRequestProtocol"}],"url":"\/documentation\/divar\/xmlhttprequestprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/XMLHttpRequestProtocol/send(_:)":{"navigatorTitle":[{"kind":"identifier","text":"send:"}],"role":"symbol","title":"send(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"send"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/send(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/xmlhttprequestprotocol\/send(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/XMLHttpRequest-swift.class":{"role":"symbol","title":"XMLHttpRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"XMLHttpRequest"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequest-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"XMLHttpRequest"}],"url":"\/documentation\/divar\/xmlhttprequest-swift.class"},"doc://com.Divar.DivarClient/documentation/Divar/XMLHttpRequestProtocol/setRequestHeader(_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"setRequestHeader::"}],"role":"symbol","title":"setRequestHeader(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRequestHeader"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/setRequestHeader(_:_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/xmlhttprequestprotocol\/setrequestheader(_:_:)"},"doc://com.Divar.DivarClient/documentation/Divar/XMLHttpRequestProtocol/readyState":{"navigatorTitle":[{"kind":"identifier","text":"readyState"}],"role":"symbol","title":"readyState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"readyState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/readyState","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/xmlhttprequestprotocol\/readystate"},"doc://com.Divar.DivarClient/documentation/Divar/XMLHttpRequestProtocol/responseText":{"navigatorTitle":[{"kind":"identifier","text":"responseText"}],"role":"symbol","title":"responseText","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"responseText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/responseText","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/xmlhttprequestprotocol\/responsetext"},"doc://com.Divar.DivarClient/documentation/Divar/XMLHttpRequestProtocol/status":{"navigatorTitle":[{"kind":"identifier","text":"status"}],"role":"symbol","title":"status","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/status","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/xmlhttprequestprotocol\/status"},"doc://com.Divar.DivarClient/documentation/Divar/XMLHttpRequestProtocol/getAllResponseHeaders()":{"navigatorTitle":[{"kind":"identifier","text":"getAllResponseHeaders"}],"role":"symbol","title":"getAllResponseHeaders()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAllResponseHeaders"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/getAllResponseHeaders()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/xmlhttprequestprotocol\/getallresponseheaders()"},"doc://com.Divar.DivarClient/documentation/Divar/XMLHttpRequestProtocol/getReponseHeader(_:)":{"navigatorTitle":[{"kind":"identifier","text":"getReponseHeader:"}],"role":"symbol","title":"getReponseHeader(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getReponseHeader"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/getReponseHeader(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/xmlhttprequestprotocol\/getreponseheader(_:)"},"doc://com.Divar.DivarClient/objc(pl)JSExport":{"type":"unresolvable","title":"JSExport","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)JSExport"},"doc://com.Divar.DivarClient/documentation/Divar/XMLHttpRequestProtocol/onreadystatechange":{"navigatorTitle":[{"kind":"identifier","text":"onreadystatechange"}],"role":"symbol","title":"onreadystatechange","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onreadystatechange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JSValue","preciseIdentifier":"c:objc(cs)JSValue"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/onreadystatechange","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/xmlhttprequestprotocol\/onreadystatechange"},"doc://com.Divar.DivarClient/documentation/Divar/XMLHttpRequestProtocol/onerror":{"navigatorTitle":[{"kind":"identifier","text":"onerror"}],"role":"symbol","title":"onerror","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onerror"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JSValue","preciseIdentifier":"c:objc(cs)JSValue"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/onerror","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/xmlhttprequestprotocol\/onerror"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/XMLHttpRequestProtocol/open(_:_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"open:::"}],"role":"symbol","title":"open(_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"open"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/open(_:_:_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/divar\/xmlhttprequestprotocol\/open(_:_:_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"XMLHttpRequest"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"XMLHttpRequest"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"XMLHttpRequest"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/onerror","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/onload","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/onreadystatechange","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/readyState","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/responseText","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/status"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/getAllResponseHeaders()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/getReponseHeader(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/open(_:_:_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/send(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequestProtocol\/setRequestHeader(_:_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/objc(pl)JSExport"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/XMLHttpRequest-swift.class"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"XMLHttpRequest"},{"kind":"text","text":"<"},{"kind":"keyword","text":"JSExport"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1onload\/title","value":"onload"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1onload\/fragments","value":[{"kind":"identifier","text":"onload"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol\/title","value":"XMLHttpRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol\/fragments","value":[{"kind":"identifier","text":"XMLHttpRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1send(_:)\/title","value":"send:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1send(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"send:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequest-swift.class\/title","value":"XMLHttpRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequest-swift.class\/fragments","value":[{"kind":"identifier","text":"XMLHttpRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1setRequestHeader(_:_:)\/title","value":"setRequestHeader::"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1setRequestHeader(_:_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setRequestHeader::"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1readyState\/title","value":"readyState"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1readyState\/fragments","value":[{"kind":"identifier","text":"readyState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1responseText\/title","value":"responseText"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1responseText\/fragments","value":[{"kind":"identifier","text":"responseText"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1status\/title","value":"status"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1status\/fragments","value":[{"kind":"identifier","text":"status"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1getAllResponseHeaders()\/title","value":"getAllResponseHeaders"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1getAllResponseHeaders()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAllResponseHeaders"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1getReponseHeader(_:)\/title","value":"getReponseHeader:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1getReponseHeader(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getReponseHeader:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1onreadystatechange\/title","value":"onreadystatechange"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1onreadystatechange\/fragments","value":[{"kind":"identifier","text":"onreadystatechange"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1onerror\/title","value":"onerror"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1onerror\/fragments","value":[{"kind":"identifier","text":"onerror"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1open(_:_:_:)\/title","value":"open:::"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1XMLHttpRequestProtocol~1open(_:_:_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"open:::"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}