{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZeroPriceViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/zeropriceviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/zeropriceviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ClaimPostProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding","doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LoginRequiredProtocol","doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RefreshableProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Searchable","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","doc:\/\/com.Divar.DivarClient\/6Sonnat17SearchBoxDelegateP","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SplitButtonBarViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/s7CVarArgP","doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP","doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP","doc:\/\/com.Divar.DivarClient\/SQ","doc:\/\/com.Divar.DivarClient\/SH","doc:\/\/com.Divar.DivarClient\/s8SendableP","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer","doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring","doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment","doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UserRegisterFlowControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WideButtonViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewControllerProtocol"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/init(dealerService:dataProvider:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/dealerService","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/isSearchActive","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/searchBox","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/stackHolder"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/addElement(with:widget:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/appendToPaginated(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/isPinned(with:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/reloadNeededCells(with:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/removeElement(with:widget:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/setupStackHolder()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/viewDidDisappear(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/viewDidLoad()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/viewWillAppear(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/widgetBasedCollectionViewController(_:didStartInfiniteScroll:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/widgetBasedCollectionViewController(_:didStartPullToRefresh:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/widgetBasedCollectionViewController(_:internalStateChangeWith:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/widgetList()"]},{"title":"Type Properties","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/pinedSlugs"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/SearchBoxDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZeroPriceViewController"}],"title":"ZeroPriceViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Divar@objc(cs)ZeroPriceViewController","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"ZeroPriceViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewController":{"role":"symbol","title":"WidgetBasedViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedViewController"}],"url":"\/documentation\/divar\/widgetbasedviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/WideButtonViewControllerDelegate":{"role":"symbol","title":"WideButtonViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WideButtonViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WideButtonViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WideButtonViewControllerDelegate"}],"url":"\/documentation\/divar\/widebuttonviewcontrollerdelegate"},"doc://com.Divar.DivarClient/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSObject"},"doc://com.Divar.DivarClient/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.Divar.DivarClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIContentContainer"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController":{"role":"symbol","title":"ZeroPriceViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZeroPriceViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZeroPriceViewController"}],"url":"\/documentation\/divar\/zeropriceviewcontroller"},"doc://com.Divar.DivarClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s23CustomStringConvertibleP"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController/widgetList()":{"role":"symbol","title":"widgetList()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetList"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"Widgets_Widget","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_WidgetV"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/widgetList()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/zeropriceviewcontroller\/widgetlist()"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/ClaimPostProtocol":{"role":"symbol","title":"ClaimPostProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClaimPostProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ClaimPostProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClaimPostProtocol"}],"url":"\/documentation\/divar\/claimpostprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController/reloadNeededCells(with:)":{"role":"symbol","title":"reloadNeededCells(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reloadNeededCells"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/reloadNeededCells(with:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/zeropriceviewcontroller\/reloadneededcells(with:)"},"doc://com.Divar.DivarClient/documentation/Divar/TooltipPresenter":{"role":"symbol","title":"TooltipPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TooltipPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TooltipPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TooltipPresenter"}],"url":"\/documentation\/divar\/tooltippresenter"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/divar\/zeropriceviewcontroller\/init(coder:)"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/divar\/zeropriceviewcontroller\/viewdidload()"},"doc://com.Divar.DivarClient/documentation/Divar/ErrorMessageHandler":{"role":"symbol","title":"ErrorMessageHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorMessageHandler"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ErrorMessageHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorMessageHandler"}],"url":"\/documentation\/divar\/errormessagehandler"},"doc://com.Divar.DivarClient/6Sonnat17SearchBoxDelegateP":{"type":"unresolvable","title":"Sonnat.SearchBoxDelegate","identifier":"doc:\/\/com.Divar.DivarClient\/6Sonnat17SearchBoxDelegateP"},"doc://com.Divar.DivarClient/documentation/Divar/LoginRequiredProtocol":{"role":"symbol","title":"LoginRequiredProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoginRequiredProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/LoginRequiredProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LoginRequiredProtocol"}],"url":"\/documentation\/divar\/loginrequiredprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/Searchable":{"role":"symbol","title":"Searchable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Searchable"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/Searchable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Searchable"}],"url":"\/documentation\/divar\/searchable"},"doc://com.Divar.DivarClient/documentation/Divar/ShowErrorProtocol":{"role":"symbol","title":"ShowErrorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowErrorProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowErrorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowErrorProtocol"}],"url":"\/documentation\/divar\/showerrorprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController/widgetBasedCollectionViewController(_:didStartPullToRefresh:)":{"role":"symbol","title":"widgetBasedCollectionViewController(_:didStartPullToRefresh:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartPullToRefresh"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/widgetBasedCollectionViewController(_:didStartPullToRefresh:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/zeropriceviewcontroller\/widgetbasedcollectionviewcontroller(_:didstartpulltorefresh:)"},"doc://com.Divar.DivarClient/documentation/Divar/ShowMessageProtocol":{"role":"symbol","title":"ShowMessageProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowMessageProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShowMessageProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowMessageProtocol"}],"url":"\/documentation\/divar\/showmessageprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedViewControllerProtocol":{"role":"symbol","title":"WidgetBasedViewControllerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedViewControllerProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewControllerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedViewControllerProtocol"}],"url":"\/documentation\/divar\/widgetbasedviewcontrollerprotocol"},"doc://com.Divar.DivarClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIAppearanceContainer"},"doc://com.Divar.DivarClient/documentation/Divar/PaymentSystemProtocol":{"role":"symbol","title":"PaymentSystemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSystemProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PaymentSystemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaymentSystemProtocol"}],"url":"\/documentation\/divar\/paymentsystemprotocol"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController/searchBox":{"role":"symbol","title":"searchBox","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBox"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchBox","preciseIdentifier":"c:@M@Sonnat@objc(cs)SearchBox"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/searchBox","kind":"symbol","type":"topic","url":"\/documentation\/divar\/zeropriceviewcontroller\/searchbox"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController/widgetBasedCollectionViewController(_:internalStateChangeWith:)":{"role":"symbol","title":"widgetBasedCollectionViewController(_:internalStateChangeWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"internalStateChangeWith"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/widgetBasedCollectionViewController(_:internalStateChangeWith:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/zeropriceviewcontroller\/widgetbasedcollectionviewcontroller(_:internalstatechangewith:)"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController/SearchBoxDelegate-Implementations":{"role":"collectionGroup","title":"SearchBoxDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/SearchBoxDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/zeropriceviewcontroller\/searchboxdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewControllerDelegate":{"role":"symbol","title":"TwinButtonsViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TwinButtonsViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TwinButtonsViewControllerDelegate"}],"url":"\/documentation\/divar\/twinbuttonsviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController/addElement(with:widget:)":{"role":"symbol","title":"addElement(with:widget:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addElement"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"widget"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Widget","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_WidgetV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/addElement(with:widget:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/zeropriceviewcontroller\/addelement(with:widget:)"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController/appendToPaginated(_:)":{"role":"symbol","title":"appendToPaginated(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendToPaginated"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"Widgets_Widget","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_WidgetV"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/appendToPaginated(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/zeropriceviewcontroller\/appendtopaginated(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController/pinedSlugs":{"role":"symbol","title":"pinedSlugs","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pinedSlugs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/pinedSlugs","kind":"symbol","type":"topic","url":"\/documentation\/divar\/zeropriceviewcontroller\/pinedslugs"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController/stackHolder":{"role":"symbol","title":"stackHolder","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stackHolder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/stackHolder","kind":"symbol","type":"topic","url":"\/documentation\/divar\/zeropriceviewcontroller\/stackholder"},"doc://com.Divar.DivarClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSCoding"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController/isPinned(with:)":{"role":"symbol","title":"isPinned(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPinned"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/isPinned(with:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/zeropriceviewcontroller\/ispinned(with:)"},"doc://com.Divar.DivarClient/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.Divar.DivarClient/documentation/Divar/UserRegisterFlowControllerDelegate":{"role":"symbol","title":"UserRegisterFlowControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserRegisterFlowControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/UserRegisterFlowControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserRegisterFlowControllerDelegate"}],"url":"\/documentation\/divar\/userregisterflowcontrollerdelegate"},"doc://com.Divar.DivarClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.Divar.DivarClient\/SQ"},"doc://com.Divar.DivarClient/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)NSExtensionRequestHandling"},"doc://com.Divar.DivarClient/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UITraitEnvironment"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController/setupStackHolder()":{"role":"symbol","title":"setupStackHolder()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupStackHolder"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/setupStackHolder()","kind":"symbol","type":"topic","url":"\/documentation\/divar\/zeropriceviewcontroller\/setupstackholder()"},"doc://com.Divar.DivarClient/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.Divar.DivarClient\/s8SendableP"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresenter":{"role":"symbol","title":"PanModalPresenter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresenter"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresenter"}],"url":"\/documentation\/divar\/panmodalpresenter"},"doc://com.Divar.DivarClient/documentation/Divar/RefreshableProtocol":{"role":"symbol","title":"RefreshableProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RefreshableProtocol"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RefreshableProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RefreshableProtocol"}],"url":"\/documentation\/divar\/refreshableprotocol"},"doc://com.Divar.DivarClient/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIUserActivityRestoring"},"doc://com.Divar.DivarClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.Divar.DivarClient\/SH"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController/viewDidDisappear(_:)":{"role":"symbol","title":"viewDidDisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/viewDidDisappear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidDisappear:"}],"url":"\/documentation\/divar\/zeropriceviewcontroller\/viewdiddisappear(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController/widgetBasedCollectionViewController(_:didStartInfiniteScroll:)":{"role":"symbol","title":"widgetBasedCollectionViewController(_:didStartInfiniteScroll:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartInfiniteScroll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdvancedCollectionView","preciseIdentifier":"c:@M@Divar@objc(cs)AdvancedCollectionView"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/widgetBasedCollectionViewController(_:didStartInfiniteScroll:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/zeropriceviewcontroller\/widgetbasedcollectionviewcontroller(_:didstartinfinitescroll:)"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewControllerDelegate":{"role":"symbol","title":"WidgetBasedCollectionViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedCollectionViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedCollectionViewControllerDelegate"}],"url":"\/documentation\/divar\/widgetbasedcollectionviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController/viewWillAppear(_:)":{"role":"symbol","title":"viewWillAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/viewWillAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"url":"\/documentation\/divar\/zeropriceviewcontroller\/viewwillappear(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController/init(dealerService:dataProvider:)":{"role":"symbol","title":"init(dealerService:dataProvider:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dealerService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DealerServiceProtocol","preciseIdentifier":"s:5Divar21DealerServiceProtocolP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dataProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DataProviderProtocol","preciseIdentifier":"s:5Divar20DataProviderProtocolP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/init(dealerService:dataProvider:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/zeropriceviewcontroller\/init(dealerservice:dataprovider:)"},"doc://com.Divar.DivarClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIStateRestoring"},"doc://com.Divar.DivarClient/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.Divar.DivarClient\/s7CVarArgP"},"doc://com.Divar.DivarClient/documentation/Divar/SplitButtonBarViewControllerDelegate":{"role":"symbol","title":"SplitButtonBarViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SplitButtonBarViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SplitButtonBarViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SplitButtonBarViewControllerDelegate"}],"url":"\/documentation\/divar\/splitbuttonbarviewcontrollerdelegate"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController/dealerService":{"role":"symbol","title":"dealerService","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dealerService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DealerServiceProtocol","preciseIdentifier":"s:5Divar21DealerServiceProtocolP"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/dealerService","kind":"symbol","type":"topic","url":"\/documentation\/divar\/zeropriceviewcontroller\/dealerservice"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController/isSearchActive":{"role":"symbol","title":"isSearchActive","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSearchActive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/isSearchActive","kind":"symbol","type":"topic","url":"\/documentation\/divar\/zeropriceviewcontroller\/issearchactive"},"doc://com.Divar.DivarClient/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIFocusEnvironment"},"doc://com.Divar.DivarClient/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.Divar.DivarClient\/objc(pl)UIResponderStandardEditActions"},"doc://com.Divar.DivarClient/documentation/Divar/ZeroPriceViewController/removeElement(with:widget:)":{"role":"symbol","title":"removeElement(with:widget:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeElement"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"widget"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Widgets_Widget","preciseIdentifier":"s:19DivarInterfaceSwift14Widgets_WidgetV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/removeElement(with:widget:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/zeropriceviewcontroller\/removeelement(with:widget:)"},"doc://com.Divar.DivarClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Divar.DivarClient\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZeroPriceViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZeroPriceViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZeroPriceViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/init(coder:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/viewDidDisappear(_:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/viewDidLoad()","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ZeroPriceViewController\/viewWillAppear(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZeroPriceViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedViewController","text":"WidgetBasedViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedViewController\/title","value":"WidgetBasedViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ZeroPriceViewController\/title","value":"ZeroPriceViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ZeroPriceViewController\/fragments","value":[{"kind":"identifier","text":"ZeroPriceViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ZeroPriceViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ZeroPriceViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ZeroPriceViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ZeroPriceViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ZeroPriceViewController~1viewDidDisappear(_:)\/title","value":"viewDidDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ZeroPriceViewController~1viewDidDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidDisappear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ZeroPriceViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ZeroPriceViewController~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}