{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initial"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"navigationController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController","text":"NavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostDetailsToken","preciseIdentifier":"s:5Divar16PostDetailsTokenO","text":"PostDetailsToken"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostViewSource","preciseIdentifier":"s:5Divar14PostViewSourceO","text":"PostViewSource"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController","preciseIdentifier":"c:@M@Divar@objc(cs)BaseViewController","text":"BaseViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/postdetailsflowcontroller\/initial(with:token:sourceview:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostDetailsFlowController\/initial(with:token:sourceView:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initial"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostDetailsToken","preciseIdentifier":"s:5Divar16PostDetailsTokenO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostViewSource","preciseIdentifier":"s:5Divar14PostViewSourceO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"BaseViewController","preciseIdentifier":"c:@M@Divar@objc(cs)BaseViewController"}],"title":"initial(with:token:sourceView:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:5Divar25PostDetailsFlowControllerC7initial4with5token10sourceViewAA04BasejE0CAA010NavigationE0C_AA0bC5TokenOAA0bJ6SourceOtF","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostDetailsFlowController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PostDetailsFlowController":{"role":"symbol","title":"PostDetailsFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostDetailsFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostDetailsFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostDetailsFlowController"}],"url":"\/documentation\/divar\/postdetailsflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostDetailsToken":{"role":"symbol","title":"PostDetailsToken","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostDetailsToken"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostDetailsToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostDetailsToken"}],"url":"\/documentation\/divar\/postdetailstoken"},"doc://com.Divar.DivarClient/documentation/Divar/PostViewSource":{"role":"symbol","title":"PostViewSource","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostViewSource"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostViewSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostViewSource"}],"url":"\/documentation\/divar\/postviewsource"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/BaseViewController":{"role":"symbol","title":"BaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BaseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseViewController"}],"url":"\/documentation\/divar\/baseviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/NavigationController":{"role":"symbol","title":"NavigationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NavigationController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NavigationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NavigationController"}],"url":"\/documentation\/divar\/navigationcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostDetailsFlowController/initial(with:token:sourceView:)":{"role":"symbol","title":"initial(with:token:sourceView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initial"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostDetailsToken","preciseIdentifier":"s:5Divar16PostDetailsTokenO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostViewSource","preciseIdentifier":"s:5Divar14PostViewSourceO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"BaseViewController","preciseIdentifier":"c:@M@Divar@objc(cs)BaseViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostDetailsFlowController\/initial(with:token:sourceView:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postdetailsflowcontroller\/initial(with:token:sourceview:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostDetailsFlowController\/title","value":"PostDetailsFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostDetailsFlowController\/fragments","value":[{"kind":"identifier","text":"PostDetailsFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController\/title","value":"BaseViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BaseViewController\/fragments","value":[{"kind":"identifier","text":"BaseViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NavigationController\/title","value":"NavigationController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NavigationController\/fragments","value":[{"kind":"identifier","text":"NavigationController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}