{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"callObserver"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"callObserver"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CXCallObserver","preciseIdentifier":"c:objc(cs)CXCallObserver"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callChanged"},{"kind":"text","text":" "},{"kind":"internalParam","text":"call"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CXCall","preciseIdentifier":"c:objc(cs)CXCall"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/getcontactviewcontroller\/callobserver(_:callchanged:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/getcontactviewcontroller\/callobserver(_:callchanged:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GetContactViewController\/callObserver(_:callChanged:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CXCallObserverDelegate.callObserver(_:callChanged:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"callObserver"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CXCallObserver","preciseIdentifier":"c:objc(cs)CXCallObserver"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CXCall","preciseIdentifier":"c:objc(cs)CXCall"},{"kind":"text","text":")"}],"title":"callObserver(_:callChanged:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@Divar@objc(cs)GetContactViewController(im)callObserver:callChanged:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"callObserver:callChanged:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GetContactViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GetContactViewController\/CXCallObserverDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/GetContactViewController/callObserver(_:callChanged:)":{"role":"symbol","title":"callObserver(_:callChanged:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"callObserver"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CXCallObserver","preciseIdentifier":"c:objc(cs)CXCallObserver"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CXCall","preciseIdentifier":"c:objc(cs)CXCall"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GetContactViewController\/callObserver(_:callChanged:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"callObserver:callChanged:"}],"url":"\/documentation\/divar\/getcontactviewcontroller\/callobserver(_:callchanged:)"},"doc://com.Divar.DivarClient/documentation/Divar/GetContactViewController/CXCallObserverDelegate-Implementations":{"role":"collectionGroup","title":"CXCallObserverDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GetContactViewController\/CXCallObserverDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/getcontactviewcontroller\/cxcallobserverdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/GetContactViewController":{"role":"symbol","title":"GetContactViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetContactViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GetContactViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GetContactViewController"}],"url":"\/documentation\/divar\/getcontactviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"callObserver:callChanged:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"callObserver:callChanged:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"callObserver:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CXCallObserver","preciseIdentifier":"c:objc(cs)CXCallObserver"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"callObserver"},{"kind":"text","text":" "},{"kind":"identifier","text":"callChanged:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CXCall","preciseIdentifier":"c:objc(cs)CXCall"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"call"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GetContactViewController~1callObserver(_:callChanged:)\/title","value":"callObserver:callChanged:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GetContactViewController~1callObserver(_:callChanged:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"callObserver:callChanged:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GetContactViewController\/title","value":"GetContactViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GetContactViewController\/fragments","value":[{"kind":"identifier","text":"GetContactViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}