{"variants":[{"paths":["\/documentation\/divar\/getcontactviewcontroller\/mfmailcomposeviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/getcontactviewcontroller\/mfmailcomposeviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GetContactViewController\/MFMailComposeViewControllerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GetContactViewController\/mailComposeController(_:didFinishWith:error:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"MFMailComposeViewControllerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GetContactViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/GetContactViewController":{"role":"symbol","title":"GetContactViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetContactViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GetContactViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GetContactViewController"}],"url":"\/documentation\/divar\/getcontactviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/GetContactViewController/mailComposeController(_:didFinishWith:error:)":{"role":"symbol","title":"mailComposeController(_:didFinishWith:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mailComposeController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MFMailComposeViewController","preciseIdentifier":"c:objc(cs)MFMailComposeViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MFMailComposeResult","preciseIdentifier":"c:@E@MFMailComposeResult"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GetContactViewController\/mailComposeController(_:didFinishWith:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mailComposeController:didFinishWithResult:error:"}],"url":"\/documentation\/divar\/getcontactviewcontroller\/mailcomposecontroller(_:didfinishwith:error:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/GetContactViewController\/mailComposeController(_:didFinishWith:error:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GetContactViewController\/title","value":"GetContactViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GetContactViewController\/fragments","value":[{"kind":"identifier","text":"GetContactViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GetContactViewController~1mailComposeController(_:didFinishWith:error:)\/title","value":"mailComposeController:didFinishWithResult:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1GetContactViewController~1mailComposeController(_:didFinishWith:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mailComposeController:didFinishWithResult:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}