{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dealerPaymentDidPerformPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionDetailsViewController","preciseIdentifier":"c:@M@Divar@objc(cs)DealerSubscriptionDetailsViewController","text":"DealerSubscriptionDetailsViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/carbusinessflowcontroller\/dealerpaymentdidperformpayment(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController\/dealerPaymentDidPerformPayment(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"DealerSubscriptionDetailsViewControllerDelegate.dealerPaymentDidPerformPayment(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"dealerPaymentDidPerformPayment(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dealerPaymentDidPerformPayment"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DealerSubscriptionDetailsViewController","preciseIdentifier":"c:@M@Divar@objc(cs)DealerSubscriptionDetailsViewController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar25CarBusinessFlowControllerC023dealerPaymentDidPerformG0yyAA029DealerSubscriptionDetailsViewE0CF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController\/DealerSubscriptionDetailsViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/DealerSubscriptionDetailsViewController":{"role":"symbol","title":"DealerSubscriptionDetailsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DealerSubscriptionDetailsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DealerSubscriptionDetailsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DealerSubscriptionDetailsViewController"}],"url":"\/documentation\/divar\/dealersubscriptiondetailsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarBusinessFlowController/DealerSubscriptionDetailsViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"DealerSubscriptionDetailsViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController\/DealerSubscriptionDetailsViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/carbusinessflowcontroller\/dealersubscriptiondetailsviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/CarBusinessFlowController":{"role":"symbol","title":"CarBusinessFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarBusinessFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarBusinessFlowController"}],"url":"\/documentation\/divar\/carbusinessflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/CarBusinessFlowController/dealerPaymentDidPerformPayment(_:)":{"role":"symbol","title":"dealerPaymentDidPerformPayment(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dealerPaymentDidPerformPayment"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DealerSubscriptionDetailsViewController","preciseIdentifier":"c:@M@Divar@objc(cs)DealerSubscriptionDetailsViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CarBusinessFlowController\/dealerPaymentDidPerformPayment(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/carbusinessflowcontroller\/dealerpaymentdidperformpayment(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubscriptionDetailsViewController\/title","value":"DealerSubscriptionDetailsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DealerSubscriptionDetailsViewController\/fragments","value":[{"kind":"identifier","text":"DealerSubscriptionDetailsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarBusinessFlowController\/title","value":"CarBusinessFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CarBusinessFlowController\/fragments","value":[{"kind":"identifier","text":"CarBusinessFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}