{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomBarVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TwinButtonsViewController","text":"TwinButtonsViewController"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/noteviewcontroller\/bottombarvc"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteViewController\/bottomBarVC","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomBarVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TwinButtonsViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TwinButtonsViewController"}],"title":"bottomBarVC","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar18NoteViewControllerC11bottomBarVCAA011TwinButtonscD0Cvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/NoteViewController":{"role":"symbol","title":"NoteViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NoteViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NoteViewController"}],"url":"\/documentation\/divar\/noteviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/TwinButtonsViewController":{"role":"symbol","title":"TwinButtonsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TwinButtonsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TwinButtonsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TwinButtonsViewController"}],"url":"\/documentation\/divar\/twinbuttonsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/NoteViewController/bottomBarVC":{"role":"symbol","title":"bottomBarVC","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomBarVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TwinButtonsViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TwinButtonsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteViewController\/bottomBarVC","kind":"symbol","type":"topic","url":"\/documentation\/divar\/noteviewcontroller\/bottombarvc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteViewController\/title","value":"NoteViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteViewController\/fragments","value":[{"kind":"identifier","text":"NoteViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TwinButtonsViewController\/title","value":"TwinButtonsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TwinButtonsViewController\/fragments","value":[{"kind":"identifier","text":"TwinButtonsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}