{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteNote"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/noteviewcontroller\/deletenote()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/noteviewcontroller\/deletenote()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteViewController\/deleteNote()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteNote"},{"kind":"text","text":"()"}],"title":"deleteNote()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Divar@objc(cs)NoteViewController(im)deleteNote","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"deleteNote"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/NoteViewController/deleteNote()":{"role":"symbol","title":"deleteNote()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteNote"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteViewController\/deleteNote()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteNote"}],"url":"\/documentation\/divar\/noteviewcontroller\/deletenote()"},"doc://com.Divar.DivarClient/documentation/Divar/NoteViewController":{"role":"symbol","title":"NoteViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NoteViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NoteViewController"}],"url":"\/documentation\/divar\/noteviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"deleteNote"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteNote"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"deleteNote"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteViewController~1deleteNote()\/title","value":"deleteNote"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteViewController~1deleteNote()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteNote"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteViewController\/title","value":"NoteViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteViewController\/fragments","value":[{"kind":"identifier","text":"NoteViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}