{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initSalePromotion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"navigationController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController","text":"NavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"saleToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/submitpromotionflowcontroller\/initsalepromotion(with:saletoken:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SubmitPromotionFlowController\/initSalePromotion(with:saleToken:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initSalePromotion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"saleToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"title":"initSalePromotion(with:saleToken:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:5Divar29SubmitPromotionFlowControllerC08initSaleC04with9saleTokenSo06UIViewE0CAA010NavigationE0C_SStF","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SubmitPromotionFlowController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/SubmitPromotionFlowController":{"role":"symbol","title":"SubmitPromotionFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubmitPromotionFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SubmitPromotionFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SubmitPromotionFlowController"}],"url":"\/documentation\/divar\/submitpromotionflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/SubmitPromotionFlowController/initSalePromotion(with:saleToken:)":{"role":"symbol","title":"initSalePromotion(with:saleToken:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initSalePromotion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavigationController","preciseIdentifier":"c:@M@Divar@objc(cs)NavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"saleToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/SubmitPromotionFlowController\/initSalePromotion(with:saleToken:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/submitpromotionflowcontroller\/initsalepromotion(with:saletoken:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/NavigationController":{"role":"symbol","title":"NavigationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NavigationController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NavigationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NavigationController"}],"url":"\/documentation\/divar\/navigationcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SubmitPromotionFlowController\/title","value":"SubmitPromotionFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1SubmitPromotionFlowController\/fragments","value":[{"kind":"identifier","text":"SubmitPromotionFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NavigationController\/title","value":"NavigationController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NavigationController\/fragments","value":[{"kind":"identifier","text":"NavigationController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}