{"variants":[{"paths":["\/documentation\/divar\/panmodalpresentationanimator\/uiviewcontrolleranimatedtransitioning-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/panmodalpresentationanimator\/uiviewcontrolleranimatedtransitioning-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationAnimator\/UIViewControllerAnimatedTransitioning-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationAnimator\/animateTransition(using:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationAnimator\/transitionDuration(using:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"UIViewControllerAnimatedTransitioning Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationAnimator"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationAnimator":{"role":"symbol","title":"PanModalPresentationAnimator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanModalPresentationAnimator"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationAnimator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanModalPresentationAnimator"}],"url":"\/documentation\/divar\/panmodalpresentationanimator"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationAnimator/animateTransition(using:)":{"role":"symbol","title":"animateTransition(using:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animateTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewControllerContextTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationAnimator\/animateTransition(using:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animateTransition:"}],"url":"\/documentation\/divar\/panmodalpresentationanimator\/animatetransition(using:)"},"doc://com.Divar.DivarClient/documentation/Divar/PanModalPresentationAnimator/transitionDuration(using:)":{"role":"symbol","title":"transitionDuration(using:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitionDuration"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewControllerContextTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationAnimator\/transitionDuration(using:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"transitionDuration:"}],"url":"\/documentation\/divar\/panmodalpresentationanimator\/transitionduration(using:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationAnimator\/animateTransition(using:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PanModalPresentationAnimator\/transitionDuration(using:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationAnimator\/title","value":"PanModalPresentationAnimator"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationAnimator\/fragments","value":[{"kind":"identifier","text":"PanModalPresentationAnimator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationAnimator~1animateTransition(using:)\/title","value":"animateTransition:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationAnimator~1animateTransition(using:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animateTransition:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationAnimator~1transitionDuration(using:)\/title","value":"transitionDuration:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PanModalPresentationAnimator~1transitionDuration(using:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"transitionDuration:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}