{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scoreView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScoreView","preciseIdentifier":"c:@M@Divar@objc(cs)ScoreView","text":"ScoreView"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/scorerowview\/scoreview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/scorerowview\/scoreview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScoreRowView\/scoreView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scoreView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ScoreView","preciseIdentifier":"c:@M@Divar@objc(cs)ScoreView"},{"kind":"text","text":"!"}],"title":"scoreView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)ScoreRowView(py)scoreView","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"scoreView"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScoreRowView"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/ScoreRowView":{"role":"symbol","title":"ScoreRowView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScoreRowView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScoreRowView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScoreRowView"}],"url":"\/documentation\/divar\/scorerowview"},"doc://com.Divar.DivarClient/documentation/Divar/ScoreRowView/scoreView":{"role":"symbol","title":"scoreView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scoreView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ScoreView","preciseIdentifier":"c:@M@Divar@objc(cs)ScoreView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScoreRowView\/scoreView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scoreView"}],"url":"\/documentation\/divar\/scorerowview\/scoreview"},"doc://com.Divar.DivarClient/documentation/Divar/ScoreView":{"role":"symbol","title":"ScoreView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScoreView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScoreView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScoreView"}],"url":"\/documentation\/divar\/scoreview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"scoreView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"scoreView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScoreView","preciseIdentifier":"c:@M@Divar@objc(cs)ScoreView","text":"ScoreView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"scoreView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScoreRowView\/title","value":"ScoreRowView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScoreRowView\/fragments","value":[{"kind":"identifier","text":"ScoreRowView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScoreRowView~1scoreView\/title","value":"scoreView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScoreRowView~1scoreView\/fragments","value":[{"kind":"identifier","text":"scoreView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScoreView\/title","value":"ScoreView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScoreView\/fragments","value":[{"kind":"identifier","text":"ScoreView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}