{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioRecorderStartedRecordingAudio"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"recorder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController","preciseIdentifier":"c:@M@Divar@objc(cs)VoiceRecorderViewController","text":"VoiceRecorderViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/inputareaviewcontroller\/audiorecorderstartedrecordingaudio(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/audioRecorderStartedRecordingAudio(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AudioRecorderViewControllerDelegate.audioRecorderStartedRecordingAudio(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"audioRecorderStartedRecordingAudio(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioRecorderStartedRecordingAudio"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"VoiceRecorderViewController","preciseIdentifier":"c:@M@Divar@objc(cs)VoiceRecorderViewController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar23InputAreaViewControllerC34audioRecorderStartedRecordingAudioyyAA05VoicegdE0CF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/AudioRecorderViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/audioRecorderStartedRecordingAudio(_:)":{"role":"symbol","title":"audioRecorderStartedRecordingAudio(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioRecorderStartedRecordingAudio"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"VoiceRecorderViewController","preciseIdentifier":"c:@M@Divar@objc(cs)VoiceRecorderViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/audioRecorderStartedRecordingAudio(_:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/inputareaviewcontroller\/audiorecorderstartedrecordingaudio(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/AudioRecorderViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"AudioRecorderViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/AudioRecorderViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/inputareaviewcontroller\/audiorecorderviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController":{"role":"symbol","title":"InputAreaViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InputAreaViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InputAreaViewController"}],"url":"\/documentation\/divar\/inputareaviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/VoiceRecorderViewController":{"role":"symbol","title":"VoiceRecorderViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoiceRecorderViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VoiceRecorderViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VoiceRecorderViewController"}],"url":"\/documentation\/divar\/voicerecorderviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController\/title","value":"InputAreaViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController\/fragments","value":[{"kind":"identifier","text":"InputAreaViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VoiceRecorderViewController\/title","value":"VoiceRecorderViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VoiceRecorderViewController\/fragments","value":[{"kind":"identifier","text":"VoiceRecorderViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}