{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareForMessagePreviewBar"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isShowingMessagePreview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV","text":"ChatConversationMessageTable"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagePreviewBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MessagePreviewBarViewController","text":"MessagePreviewBarViewController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagePreviewBarViewController\/MessagePreviewType","preciseIdentifier":"s:5Divar31MessagePreviewBarViewControllerC0bC4TypeO","text":"MessagePreviewType"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/inputareaviewcontroller\/prepareformessagepreviewbar(isshowingmessagepreview:message:type:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/prepareForMessagePreviewBar(isShowingMessagePreview:message:type:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareForMessagePreviewBar"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isShowingMessagePreview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagePreviewBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MessagePreviewBarViewController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"MessagePreviewType","preciseIdentifier":"s:5Divar31MessagePreviewBarViewControllerC0bC4TypeO"},{"kind":"text","text":"?)"}],"title":"prepareForMessagePreviewBar(isShowingMessagePreview:message:type:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:5Divar23InputAreaViewControllerC27prepareForMessagePreviewBar09isShowinghI07message4typeySb_AA016ChatConversationH5TableVSgAA0hijdE0C0hI4TypeOSgtF","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/prepareForMessagePreviewBar(isShowingMessagePreview:message:type:)":{"role":"symbol","title":"prepareForMessagePreviewBar(isShowingMessagePreview:message:type:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareForMessagePreviewBar"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isShowingMessagePreview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatConversationMessageTable","preciseIdentifier":"s:5Divar28ChatConversationMessageTableV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagePreviewBarViewController","preciseIdentifier":"c:@M@Divar@objc(cs)MessagePreviewBarViewController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"MessagePreviewType","preciseIdentifier":"s:5Divar31MessagePreviewBarViewControllerC0bC4TypeO"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/prepareForMessagePreviewBar(isShowingMessagePreview:message:type:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/inputareaviewcontroller\/prepareformessagepreviewbar(isshowingmessagepreview:message:type:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/MessagePreviewBarViewController":{"role":"symbol","title":"MessagePreviewBarViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagePreviewBarViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagePreviewBarViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagePreviewBarViewController"}],"url":"\/documentation\/divar\/messagepreviewbarviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/MessagePreviewBarViewController/MessagePreviewType":{"role":"symbol","title":"MessagePreviewBarViewController.MessagePreviewType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagePreviewType"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MessagePreviewBarViewController\/MessagePreviewType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagePreviewType"}],"url":"\/documentation\/divar\/messagepreviewbarviewcontroller\/messagepreviewtype"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController":{"role":"symbol","title":"InputAreaViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InputAreaViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InputAreaViewController"}],"url":"\/documentation\/divar\/inputareaviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/ChatConversationMessageTable":{"role":"symbol","title":"ChatConversationMessageTable","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatConversationMessageTable"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ChatConversationMessageTable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatConversationMessageTable"}],"url":"\/documentation\/divar\/chatconversationmessagetable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagePreviewBarViewController\/title","value":"MessagePreviewBarViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MessagePreviewBarViewController\/fragments","value":[{"kind":"identifier","text":"MessagePreviewBarViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController\/title","value":"InputAreaViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController\/fragments","value":[{"kind":"identifier","text":"InputAreaViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}