{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/inputareaviewcontroller\/sendbutton"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/inputareaviewcontroller\/sendbutton"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/sendButton","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"title":"sendButton","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)InputAreaViewController(py)sendButton","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"sendButton"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController":{"role":"symbol","title":"InputAreaViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InputAreaViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InputAreaViewController"}],"url":"\/documentation\/divar\/inputareaviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/InputAreaViewController/sendButton":{"role":"symbol","title":"sendButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/InputAreaViewController\/sendButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendButton"}],"url":"\/documentation\/divar\/inputareaviewcontroller\/sendbutton"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"sendButton"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"sendButton"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":" * "},{"kind":"identifier","text":"sendButton"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController\/title","value":"InputAreaViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController\/fragments","value":[{"kind":"identifier","text":"InputAreaViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController~1sendButton\/title","value":"sendButton"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1InputAreaViewController~1sendButton\/fragments","value":[{"kind":"identifier","text":"sendButton"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}