{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"payloads"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MXDiagnosticPayload","preciseIdentifier":"c:objc(cs)MXDiagnosticPayload"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/metrickitconfiguration\/didreceive(_:)-z3jm"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/metrickitconfiguration\/didreceive(_:)-z3jm"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MetricKitConfiguration\/didReceive(_:)-z3jm","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"MXMetricManagerSubscriber.didReceive(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"didReceiveDiagnosticPayloads:"}],"role":"symbol","title":"didReceive(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceive"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"MXDiagnosticPayload","preciseIdentifier":"c:objc(cs)MXDiagnosticPayload"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"c:@M@Divar@objc(cs)MetricKitConfiguration(im)didReceiveDiagnosticPayloads:","modules":[{"name":"Divar"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"14.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MetricKitConfiguration"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/MetricKitConfiguration/didReceive(_:)-z3jm":{"role":"symbol","title":"didReceive(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceive"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"MXDiagnosticPayload","preciseIdentifier":"c:objc(cs)MXDiagnosticPayload"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MetricKitConfiguration\/didReceive(_:)-z3jm","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didReceiveDiagnosticPayloads:"}],"url":"\/documentation\/divar\/metrickitconfiguration\/didreceive(_:)-z3jm"},"doc://com.Divar.DivarClient/documentation/Divar/MetricKitConfiguration":{"role":"symbol","title":"MetricKitConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MetricKitConfiguration"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/MetricKitConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MetricKitConfiguration"}],"url":"\/documentation\/divar\/metrickitconfiguration"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"14.0","deprecated":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didReceiveDiagnosticPayloads:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveDiagnosticPayloads:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didReceiveDiagnosticPayloads:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<MXDiagnosticPayload *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"payloads"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MetricKitConfiguration~1didReceive(_:)-z3jm\/title","value":"didReceiveDiagnosticPayloads:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MetricKitConfiguration~1didReceive(_:)-z3jm\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveDiagnosticPayloads:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MetricKitConfiguration\/title","value":"MetricKitConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1MetricKitConfiguration\/fragments","value":[{"kind":"identifier","text":"MetricKitConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}