{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteNote"},{"kind":"text","text":"("},{"kind":"externalParam","text":"postToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/notesviewcontroller\/deletenote(posttoken:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/notesviewcontroller\/deletenote(posttoken:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NotesViewController\/deleteNote(postToken:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteNote"},{"kind":"text","text":"("},{"kind":"externalParam","text":"postToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"deleteNote(postToken:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Divar@objc(cs)NotesViewController(im)deleteNoteWithPostToken:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"deleteNoteWithPostToken:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NotesViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/NotesViewController":{"role":"symbol","title":"NotesViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotesViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NotesViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NotesViewController"}],"url":"\/documentation\/divar\/notesviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/NotesViewController/deleteNote(postToken:)":{"role":"symbol","title":"deleteNote(postToken:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteNote"},{"kind":"text","text":"("},{"kind":"externalParam","text":"postToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NotesViewController\/deleteNote(postToken:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteNoteWithPostToken:"}],"url":"\/documentation\/divar\/notesviewcontroller\/deletenote(posttoken:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"deleteNoteWithPostToken:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteNoteWithPostToken:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"deleteNoteWithPostToken:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"postToken"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NotesViewController\/title","value":"NotesViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NotesViewController\/fragments","value":[{"kind":"identifier","text":"NotesViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NotesViewController~1deleteNote(postToken:)\/title","value":"deleteNoteWithPostToken:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NotesViewController~1deleteNote(postToken:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteNoteWithPostToken:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}