{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleLongPress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"gestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILongPressGestureRecognizer","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/notesviewcontroller\/handlelongpress(gesturerecognizer:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/notesviewcontroller\/handlelongpress(gesturerecognizer:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NotesViewController\/handleLongPress(gestureRecognizer:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleLongPress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"gestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILongPressGestureRecognizer","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer"},{"kind":"text","text":")"}],"title":"handleLongPress(gestureRecognizer:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Divar@objc(cs)NotesViewController(im)handleLongPressWithGestureRecognizer:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"handleLongPressWithGestureRecognizer:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NotesViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/NotesViewController/handleLongPress(gestureRecognizer:)":{"role":"symbol","title":"handleLongPress(gestureRecognizer:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleLongPress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"gestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILongPressGestureRecognizer","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NotesViewController\/handleLongPress(gestureRecognizer:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"handleLongPressWithGestureRecognizer:"}],"url":"\/documentation\/divar\/notesviewcontroller\/handlelongpress(gesturerecognizer:)"},"doc://com.Divar.DivarClient/documentation/Divar/NotesViewController":{"role":"symbol","title":"NotesViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotesViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NotesViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NotesViewController"}],"url":"\/documentation\/divar\/notesviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"handleLongPressWithGestureRecognizer:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleLongPressWithGestureRecognizer:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"handleLongPressWithGestureRecognizer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UILongPressGestureRecognizer","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NotesViewController~1handleLongPress(gestureRecognizer:)\/title","value":"handleLongPressWithGestureRecognizer:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NotesViewController~1handleLongPress(gestureRecognizer:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleLongPressWithGestureRecognizer:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NotesViewController\/title","value":"NotesViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NotesViewController\/fragments","value":[{"kind":"identifier","text":"NotesViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}