{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pickerView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewForRow"},{"kind":"text","text":" "},{"kind":"internalParam","text":"row"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forComponent"},{"kind":"text","text":" "},{"kind":"internalParam","text":"_"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reusing"},{"kind":"text","text":" "},{"kind":"internalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/pickerhandler\/pickerview(_:viewforrow:forcomponent:reusing:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/pickerhandler\/pickerview(_:viewforrow:forcomponent:reusing:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PickerHandler\/pickerView(_:viewForRow:forComponent:reusing:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIPickerViewDelegate.pickerView(_:viewForRow:forComponent:reusing:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pickerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewForRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reusing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"title":"pickerView(_:viewForRow:forComponent:reusing:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Divar@objc(cs)PickerHandler(im)pickerView:viewForRow:forComponent:reusingView:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"pickerView:viewForRow:forComponent:reusingView:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PickerHandler"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PickerHandler/pickerView(_:viewForRow:forComponent:reusing:)":{"role":"symbol","title":"pickerView(_:viewForRow:forComponent:reusing:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pickerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewForRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reusing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PickerHandler\/pickerView(_:viewForRow:forComponent:reusing:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pickerView:viewForRow:forComponent:reusingView:"}],"url":"\/documentation\/divar\/pickerhandler\/pickerview(_:viewforrow:forcomponent:reusing:)"},"doc://com.Divar.DivarClient/documentation/Divar/PickerHandler":{"role":"symbol","title":"PickerHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PickerHandler"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PickerHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PickerHandler"}],"url":"\/documentation\/divar\/pickerhandler"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"pickerView:viewForRow:forComponent:reusingView:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pickerView:viewForRow:forComponent:reusingView:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"pickerView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"_"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewForRow:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"row"},{"kind":"text","text":" "},{"kind":"identifier","text":"forComponent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"_"},{"kind":"text","text":" "},{"kind":"identifier","text":"reusingView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"view"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PickerHandler~1pickerView(_:viewForRow:forComponent:reusing:)\/title","value":"pickerView:viewForRow:forComponent:reusingView:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PickerHandler~1pickerView(_:viewForRow:forComponent:reusing:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pickerView:viewForRow:forComponent:reusingView:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PickerHandler\/title","value":"PickerHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PickerHandler\/fragments","value":[{"kind":"identifier","text":"PickerHandler"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}