{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabbedPageViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TabbedPageViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TabbedPageViewController","text":"TabbedPageViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSwitchTo"},{"kind":"text","text":" "},{"kind":"internalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"presentingViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/postlisttabbedviewcontroller\/tabbedpageviewcontroller(_:didswitchto:presentingviewcontroller:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListTabbedViewController\/tabbedPageViewController(_:didSwitchTo:presentingViewController:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"TabbedPageViewControllerDelegate.tabbedPageViewController(_:didSwitchTo:presentingViewController:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"tabbedPageViewController(_:didSwitchTo:presentingViewController:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabbedPageViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TabbedPageViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TabbedPageViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSwitchTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"presentingViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar28PostListTabbedViewControllerC010tabbedPageeF0_11didSwitchTo010presentingeF0yAA0dheF0C_SiSo06UIViewF0CtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListTabbedViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListTabbedViewController\/TabbedPageViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/TabbedPageViewController":{"role":"symbol","title":"TabbedPageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TabbedPageViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/TabbedPageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TabbedPageViewController"}],"url":"\/documentation\/divar\/tabbedpageviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostListTabbedViewController":{"role":"symbol","title":"PostListTabbedViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostListTabbedViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListTabbedViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostListTabbedViewController"}],"url":"\/documentation\/divar\/postlisttabbedviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostListTabbedViewController/tabbedPageViewController(_:didSwitchTo:presentingViewController:)":{"role":"symbol","title":"tabbedPageViewController(_:didSwitchTo:presentingViewController:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabbedPageViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TabbedPageViewController","preciseIdentifier":"c:@M@Divar@objc(cs)TabbedPageViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSwitchTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"presentingViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListTabbedViewController\/tabbedPageViewController(_:didSwitchTo:presentingViewController:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postlisttabbedviewcontroller\/tabbedpageviewcontroller(_:didswitchto:presentingviewcontroller:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PostListTabbedViewController/TabbedPageViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"TabbedPageViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostListTabbedViewController\/TabbedPageViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/postlisttabbedviewcontroller\/tabbedpageviewcontrollerdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TabbedPageViewController\/title","value":"TabbedPageViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1TabbedPageViewController\/fragments","value":[{"kind":"identifier","text":"TabbedPageViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListTabbedViewController\/title","value":"PostListTabbedViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostListTabbedViewController\/fragments","value":[{"kind":"identifier","text":"PostListTabbedViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}