{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rateView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView","preciseIdentifier":"c:@M@Divar@objc(cs)RateRowView","text":"RateRowView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/rateviewcontroller\/rateview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateViewController\/rateView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rateView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RateRowView","preciseIdentifier":"c:@M@Divar@objc(cs)RateRowView"}],"title":"rateView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar18RateViewControllerC04rateC0AA0b3RowC0Cvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/RateViewController":{"role":"symbol","title":"RateViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RateViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RateViewController"}],"url":"\/documentation\/divar\/rateviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/RateViewController/rateView":{"role":"symbol","title":"rateView","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rateView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RateRowView","preciseIdentifier":"c:@M@Divar@objc(cs)RateRowView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateViewController\/rateView","kind":"symbol","type":"topic","url":"\/documentation\/divar\/rateviewcontroller\/rateview"},"doc://com.Divar.DivarClient/documentation/Divar/RateRowView":{"role":"symbol","title":"RateRowView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RateRowView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/RateRowView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RateRowView"}],"url":"\/documentation\/divar\/raterowview"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateViewController\/title","value":"RateViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateViewController\/fragments","value":[{"kind":"identifier","text":"RateViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView\/title","value":"RateRowView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1RateRowView\/fragments","value":[{"kind":"identifier","text":"RateRowView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}