{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController","text":"WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartInfiniteScroll"},{"kind":"text","text":" "},{"kind":"internalParam","text":"collectionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedCollectionView","preciseIdentifier":"c:@M@Divar@objc(cs)AdvancedCollectionView","text":"AdvancedCollectionView"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/advancedwidgetviewcontroller\/widgetbasedcollectionviewcontroller(_:didstartinfinitescroll:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/widgetBasedCollectionViewController(_:didStartInfiniteScroll:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartInfiniteScroll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdvancedCollectionView","preciseIdentifier":"c:@M@Divar@objc(cs)AdvancedCollectionView"},{"kind":"text","text":"?)"}],"title":"widgetBasedCollectionViewController(_:didStartInfiniteScroll:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:5Divar28AdvancedWidgetViewControllerC021widgetBasedCollectiondE0_22didStartInfiniteScrollyAA0cghdE0C_AA0bhD0CSgtF","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController":{"role":"symbol","title":"AdvancedWidgetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdvancedWidgetViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdvancedWidgetViewController"}],"url":"\/documentation\/divar\/advancedwidgetviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedWidgetViewController/widgetBasedCollectionViewController(_:didStartInfiniteScroll:)":{"role":"symbol","title":"widgetBasedCollectionViewController(_:didStartInfiniteScroll:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetBasedCollectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartInfiniteScroll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdvancedCollectionView","preciseIdentifier":"c:@M@Divar@objc(cs)AdvancedCollectionView"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedWidgetViewController\/widgetBasedCollectionViewController(_:didStartInfiniteScroll:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/advancedwidgetviewcontroller\/widgetbasedcollectionviewcontroller(_:didstartinfinitescroll:)"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewController":{"role":"symbol","title":"WidgetBasedCollectionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedCollectionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedCollectionViewController"}],"url":"\/documentation\/divar\/widgetbasedcollectionviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedCollectionView":{"role":"symbol","title":"AdvancedCollectionView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdvancedCollectionView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedCollectionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdvancedCollectionView"}],"url":"\/documentation\/divar\/advancedcollectionview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController\/title","value":"AdvancedWidgetViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedWidgetViewController\/fragments","value":[{"kind":"identifier","text":"AdvancedWidgetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedCollectionViewController\/title","value":"WidgetBasedCollectionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedCollectionViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedCollectionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedCollectionView\/title","value":"AdvancedCollectionView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedCollectionView\/fragments","value":[{"kind":"identifier","text":"AdvancedCollectionView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}