{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationRow","preciseIdentifier":"c:@M@Sonnat@objc(cs)ConversationRow"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/conversationrowcell\/conversationrow"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/conversationrowcell\/conversationrow"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConversationRowCell\/conversationRow","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationRow","preciseIdentifier":"c:@M@Sonnat@objc(cs)ConversationRow"},{"kind":"text","text":"!"}],"title":"conversationRow","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)ConversationRowCell(py)conversationRow","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"conversationRow"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConversationRowCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ConversationRowCell/conversationRow":{"role":"symbol","title":"conversationRow","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationRow","preciseIdentifier":"c:@M@Sonnat@objc(cs)ConversationRow"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConversationRowCell\/conversationRow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"conversationRow"}],"url":"\/documentation\/divar\/conversationrowcell\/conversationrow"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/ConversationRowCell":{"role":"symbol","title":"ConversationRowCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationRowCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ConversationRowCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationRowCell"}],"url":"\/documentation\/divar\/conversationrowcell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"conversationRow"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"conversationRow"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"ConversationRow","preciseIdentifier":"c:objc(cs)ConversationRow"},{"kind":"text","text":" * "},{"kind":"identifier","text":"conversationRow"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ConversationRowCell~1conversationRow\/title","value":"conversationRow"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ConversationRowCell~1conversationRow\/fragments","value":[{"kind":"identifier","text":"conversationRow"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ConversationRowCell\/title","value":"ConversationRowCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ConversationRowCell\/fragments","value":[{"kind":"identifier","text":"ConversationRowCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}