{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraOverlay"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cameraOverlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView","preciseIdentifier":"c:@M@Divar@objc(cs)CameraOverlayView","text":"CameraOverlayView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestChangeFlashState"},{"kind":"text","text":" "},{"kind":"internalParam","text":"isOn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/videorecorder\/cameraoverlay(_:didrequestchangeflashstate:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoRecorder\/cameraOverlay(_:didRequestChangeFlashState:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CameraOverlayDelegate.cameraOverlay(_:didRequestChangeFlashState:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"cameraOverlay(_:didRequestChangeFlashState:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraOverlay"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CameraOverlayView","preciseIdentifier":"c:@M@Divar@objc(cs)CameraOverlayView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestChangeFlashState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar13VideoRecorderC13cameraOverlay_26didRequestChangeFlashStateyAA06CameraE4ViewC_SbtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoRecorder","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoRecorder\/CameraOverlayDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/VideoRecorder/CameraOverlayDelegate-Implementations":{"role":"collectionGroup","title":"CameraOverlayDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoRecorder\/CameraOverlayDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/videorecorder\/cameraoverlaydelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/CameraOverlayView":{"role":"symbol","title":"CameraOverlayView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraOverlayView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/CameraOverlayView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraOverlayView"}],"url":"\/documentation\/divar\/cameraoverlayview"},"doc://com.Divar.DivarClient/documentation/Divar/VideoRecorder/cameraOverlay(_:didRequestChangeFlashState:)":{"role":"symbol","title":"cameraOverlay(_:didRequestChangeFlashState:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraOverlay"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CameraOverlayView","preciseIdentifier":"c:@M@Divar@objc(cs)CameraOverlayView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestChangeFlashState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoRecorder\/cameraOverlay(_:didRequestChangeFlashState:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/videorecorder\/cameraoverlay(_:didrequestchangeflashstate:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/VideoRecorder":{"deprecated":true,"role":"symbol","title":"VideoRecorder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoRecorder"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/VideoRecorder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoRecorder"}],"url":"\/documentation\/divar\/videorecorder"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CameraOverlayView\/title","value":"CameraOverlayView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1CameraOverlayView\/fragments","value":[{"kind":"identifier","text":"CameraOverlayView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VideoRecorder\/title","value":"VideoRecorder"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1VideoRecorder\/fragments","value":[{"kind":"identifier","text":"VideoRecorder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}