{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectablePostsList"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController","text":"WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartInfiniteScroll"},{"kind":"text","text":" "},{"kind":"internalParam","text":"collectionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedCollectionView","preciseIdentifier":"c:@M@Divar@objc(cs)AdvancedCollectionView","text":"AdvancedCollectionView"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/bulkladderviewcontroller\/selectablepostslist(_:didstartinfinitescroll:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BulkLadderViewController\/selectablePostsList(_:didStartInfiniteScroll:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"SelectablePostsListViewControllerDelegate.selectablePostsList(_:didStartInfiniteScroll:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"conformance":{"constraints":[{"type":"codeVoice","code":"PageResponseType"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"_Extractor"},{"type":"text","text":", "},{"type":"codeVoice","code":"PageResponseType"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Message"},{"type":"text","text":", "},{"type":"codeVoice","code":"SubmitResponseType"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"_Extractor"},{"type":"text","text":", and "},{"type":"codeVoice","code":"SubmitResponseType"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Message"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"selectablePostsList(_:didStartInfiniteScroll:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectablePostsList"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartInfiniteScroll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdvancedCollectionView","preciseIdentifier":"c:@M@Divar@objc(cs)AdvancedCollectionView"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"s:5Divar24BulkLadderViewControllerC19selectablePostsList_22didStartInfiniteScrollyAA021WidgetBasedCollectiondE0C_AA08AdvancedoD0CSgtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BulkLadderViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BulkLadderViewController\/SelectablePostsListViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/BulkLadderViewController":{"role":"symbol","title":"BulkLadderViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BulkLadderViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BulkLadderViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BulkLadderViewController"}],"url":"\/documentation\/divar\/bulkladderviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AdvancedCollectionView":{"role":"symbol","title":"AdvancedCollectionView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdvancedCollectionView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AdvancedCollectionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdvancedCollectionView"}],"url":"\/documentation\/divar\/advancedcollectionview"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/BulkLadderViewController/selectablePostsList(_:didStartInfiniteScroll:)":{"conformance":{"constraints":[{"type":"codeVoice","code":"PageResponseType"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"_Extractor"},{"type":"text","text":", "},{"type":"codeVoice","code":"PageResponseType"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Message"},{"type":"text","text":", "},{"type":"codeVoice","code":"SubmitResponseType"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"_Extractor"},{"type":"text","text":", and "},{"type":"codeVoice","code":"SubmitResponseType"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Message"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"selectablePostsList(_:didStartInfiniteScroll:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectablePostsList"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WidgetBasedCollectionViewController","preciseIdentifier":"c:@M@Divar@objc(cs)WidgetBasedCollectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartInfiniteScroll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdvancedCollectionView","preciseIdentifier":"c:@M@Divar@objc(cs)AdvancedCollectionView"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BulkLadderViewController\/selectablePostsList(_:didStartInfiniteScroll:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/bulkladderviewcontroller\/selectablepostslist(_:didstartinfinitescroll:)"},"doc://com.Divar.DivarClient/documentation/Divar/BulkLadderViewController/SelectablePostsListViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"SelectablePostsListViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BulkLadderViewController\/SelectablePostsListViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/bulkladderviewcontroller\/selectablepostslistviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedCollectionViewController":{"role":"symbol","title":"WidgetBasedCollectionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedCollectionViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedCollectionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedCollectionViewController"}],"url":"\/documentation\/divar\/widgetbasedcollectionviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedCollectionView\/title","value":"AdvancedCollectionView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AdvancedCollectionView\/fragments","value":[{"kind":"identifier","text":"AdvancedCollectionView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedCollectionViewController\/title","value":"WidgetBasedCollectionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedCollectionViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedCollectionViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}