{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"directionalLayoutMargins"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDirectionalEdgeInsets","preciseIdentifier":"c:@S@NSDirectionalEdgeInsets"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/scrollingstackview\/directionallayoutmargins"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/scrollingstackview\/directionallayoutmargins"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/directionalLayoutMargins","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"directionalLayoutMargins"}],"role":"symbol","title":"directionalLayoutMargins","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"directionalLayoutMargins"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDirectionalEdgeInsets","preciseIdentifier":"c:@S@NSDirectionalEdgeInsets"}],"symbolKind":"property","externalID":"c:@CM@Divar@objc(cs)ScrollingStackView(py)directionalLayoutMargins","modules":[{"name":"Divar"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/ScrollingStackView":{"role":"symbol","title":"ScrollingStackView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScrollingStackView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScrollingStackView"}],"url":"\/documentation\/divar\/scrollingstackview"},"doc://com.Divar.DivarClient/documentation/Divar/ScrollingStackView/directionalLayoutMargins":{"role":"symbol","title":"directionalLayoutMargins","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"directionalLayoutMargins"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDirectionalEdgeInsets","preciseIdentifier":"c:@S@NSDirectionalEdgeInsets"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ScrollingStackView\/directionalLayoutMargins","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"directionalLayoutMargins"}],"url":"\/documentation\/divar\/scrollingstackview\/directionallayoutmargins"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"directionalLayoutMargins"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"directionalLayoutMargins"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSDirectionalEdgeInsets","preciseIdentifier":"c:@S@NSDirectionalEdgeInsets"},{"kind":"text","text":" "},{"kind":"identifier","text":"directionalLayoutMargins"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScrollingStackView\/title","value":"ScrollingStackView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScrollingStackView\/fragments","value":[{"kind":"identifier","text":"ScrollingStackView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScrollingStackView~1directionalLayoutMargins\/title","value":"directionalLayoutMargins"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ScrollingStackView~1directionalLayoutMargins\/fragments","value":[{"kind":"identifier","text":"directionalLayoutMargins"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}