{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"priceEvaluationView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/EvaluationView","preciseIdentifier":"c:@M@Divar@objc(cs)EvaluationView","text":"EvaluationView"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/priceevaluationtableviewcell\/priceevaluationview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/priceevaluationtableviewcell\/priceevaluationview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceEvaluationTableViewCell\/priceEvaluationView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"priceEvaluationView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EvaluationView","preciseIdentifier":"c:@M@Divar@objc(cs)EvaluationView"},{"kind":"text","text":"!"}],"title":"priceEvaluationView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Divar@objc(cs)PriceEvaluationTableViewCell(py)priceEvaluationView","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"priceEvaluationView"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceEvaluationTableViewCell"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PriceEvaluationTableViewCell":{"role":"symbol","title":"PriceEvaluationTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PriceEvaluationTableViewCell"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceEvaluationTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PriceEvaluationTableViewCell"}],"url":"\/documentation\/divar\/priceevaluationtableviewcell"},"doc://com.Divar.DivarClient/documentation/Divar/PriceEvaluationTableViewCell/priceEvaluationView":{"role":"symbol","title":"priceEvaluationView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"priceEvaluationView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EvaluationView","preciseIdentifier":"c:@M@Divar@objc(cs)EvaluationView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PriceEvaluationTableViewCell\/priceEvaluationView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"priceEvaluationView"}],"url":"\/documentation\/divar\/priceevaluationtableviewcell\/priceevaluationview"},"doc://com.Divar.DivarClient/documentation/Divar/EvaluationView":{"role":"symbol","title":"EvaluationView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EvaluationView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/EvaluationView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EvaluationView"}],"url":"\/documentation\/divar\/evaluationview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"priceEvaluationView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"priceEvaluationView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/EvaluationView","preciseIdentifier":"c:@M@Divar@objc(cs)EvaluationView","text":"EvaluationView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"priceEvaluationView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceEvaluationTableViewCell\/title","value":"PriceEvaluationTableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceEvaluationTableViewCell\/fragments","value":[{"kind":"identifier","text":"PriceEvaluationTableViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceEvaluationTableViewCell~1priceEvaluationView\/title","value":"priceEvaluationView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PriceEvaluationTableViewCell~1priceEvaluationView\/fragments","value":[{"kind":"identifier","text":"priceEvaluationView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1EvaluationView\/title","value":"EvaluationView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1EvaluationView\/fragments","value":[{"kind":"identifier","text":"EvaluationView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}