{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapViewDidChangeVisibleRegion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mapView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKMapView","preciseIdentifier":"c:objc(cs)MKMapView"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/districtedmapviewcontroller\/mapviewdidchangevisibleregion(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/districtedmapviewcontroller\/mapviewdidchangevisibleregion(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController\/mapViewDidChangeVisibleRegion(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"MKMapViewDelegate.mapViewDidChangeVisibleRegion(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"mapViewDidChangeVisibleRegion:"}],"role":"symbol","title":"mapViewDidChangeVisibleRegion(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapViewDidChangeVisibleRegion"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapView","preciseIdentifier":"c:objc(cs)MKMapView"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@Divar@objc(cs)DistrictedMapViewController(im)mapViewDidChangeVisibleRegion:","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController\/MKMapViewDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/DistrictedMapViewController":{"role":"symbol","title":"DistrictedMapViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DistrictedMapViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DistrictedMapViewController"}],"url":"\/documentation\/divar\/districtedmapviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/DistrictedMapViewController/MKMapViewDelegate-Implementations":{"role":"collectionGroup","title":"MKMapViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController\/MKMapViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/districtedmapviewcontroller\/mkmapviewdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/DistrictedMapViewController/mapViewDidChangeVisibleRegion(_:)":{"role":"symbol","title":"mapViewDidChangeVisibleRegion(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapViewDidChangeVisibleRegion"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapView","preciseIdentifier":"c:objc(cs)MKMapView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController\/mapViewDidChangeVisibleRegion(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mapViewDidChangeVisibleRegion:"}],"url":"\/documentation\/divar\/districtedmapviewcontroller\/mapviewdidchangevisibleregion(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"mapViewDidChangeVisibleRegion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mapViewDidChangeVisibleRegion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"mapViewDidChangeVisibleRegion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapView","preciseIdentifier":"c:objc(cs)MKMapView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"mapView"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictedMapViewController\/title","value":"DistrictedMapViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictedMapViewController\/fragments","value":[{"kind":"identifier","text":"DistrictedMapViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictedMapViewController~1mapViewDidChangeVisibleRegion(_:)\/title","value":"mapViewDidChangeVisibleRegion:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictedMapViewController~1mapViewDidChangeVisibleRegion(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mapViewDidChangeVisibleRegion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}