{"variants":[{"paths":["\/documentation\/divar\/districtedmapviewcontroller\/mkmapviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/districtedmapviewcontroller\/mkmapviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController\/MKMapViewDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController\/mapView(_:rendererFor:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController\/mapView(_:viewFor:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController\/mapViewDidChangeVisibleRegion(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"MKMapViewDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/DistrictedMapViewController":{"role":"symbol","title":"DistrictedMapViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DistrictedMapViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DistrictedMapViewController"}],"url":"\/documentation\/divar\/districtedmapviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/DistrictedMapViewController/mapView(_:rendererFor:)":{"role":"symbol","title":"mapView(_:rendererFor:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapView","preciseIdentifier":"c:objc(cs)MKMapView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rendererFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKOverlay","preciseIdentifier":"c:objc(pl)MKOverlay"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MKOverlayRenderer","preciseIdentifier":"c:objc(cs)MKOverlayRenderer"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController\/mapView(_:rendererFor:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mapView:rendererForOverlay:"}],"url":"\/documentation\/divar\/districtedmapviewcontroller\/mapview(_:rendererfor:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/DistrictedMapViewController/mapView(_:viewFor:)":{"role":"symbol","title":"mapView(_:viewFor:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapView","preciseIdentifier":"c:objc(cs)MKMapView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKAnnotation","preciseIdentifier":"c:objc(pl)MKAnnotation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MKAnnotationView","preciseIdentifier":"c:objc(cs)MKAnnotationView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController\/mapView(_:viewFor:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mapView:viewForAnnotation:"}],"url":"\/documentation\/divar\/districtedmapviewcontroller\/mapview(_:viewfor:)"},"doc://com.Divar.DivarClient/documentation/Divar/DistrictedMapViewController/mapViewDidChangeVisibleRegion(_:)":{"role":"symbol","title":"mapViewDidChangeVisibleRegion(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapViewDidChangeVisibleRegion"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapView","preciseIdentifier":"c:objc(cs)MKMapView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController\/mapViewDidChangeVisibleRegion(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mapViewDidChangeVisibleRegion:"}],"url":"\/documentation\/divar\/districtedmapviewcontroller\/mapviewdidchangevisibleregion(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController\/mapView(_:rendererFor:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController\/mapView(_:viewFor:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController\/mapViewDidChangeVisibleRegion(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictedMapViewController\/title","value":"DistrictedMapViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictedMapViewController\/fragments","value":[{"kind":"identifier","text":"DistrictedMapViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictedMapViewController~1mapView(_:rendererFor:)\/title","value":"mapView:rendererForOverlay:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictedMapViewController~1mapView(_:rendererFor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mapView:rendererForOverlay:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictedMapViewController~1mapView(_:viewFor:)\/title","value":"mapView:viewForAnnotation:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictedMapViewController~1mapView(_:viewFor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mapView:viewForAnnotation:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictedMapViewController~1mapViewDidChangeVisibleRegion(_:)\/title","value":"mapViewDidChangeVisibleRegion:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictedMapViewController~1mapViewDidChangeVisibleRegion(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mapViewDidChangeVisibleRegion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}