{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygons"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictPolygon","preciseIdentifier":"c:@M@Divar@objc(cs)DistrictPolygon","text":"DistrictPolygon"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/districtedmapviewcontroller\/polygons"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController\/polygons","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygons"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DistrictPolygon","preciseIdentifier":"c:@M@Divar@objc(cs)DistrictPolygon"},{"kind":"text","text":"]"}],"title":"polygons","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:5Divar27DistrictedMapViewControllerC8polygonsSayAA15DistrictPolygonCGvp","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/DistrictedMapViewController/polygons":{"role":"symbol","title":"polygons","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygons"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DistrictPolygon","preciseIdentifier":"c:@M@Divar@objc(cs)DistrictPolygon"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController\/polygons","kind":"symbol","type":"topic","url":"\/documentation\/divar\/districtedmapviewcontroller\/polygons"},"doc://com.Divar.DivarClient/documentation/Divar/DistrictedMapViewController":{"role":"symbol","title":"DistrictedMapViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DistrictedMapViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictedMapViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DistrictedMapViewController"}],"url":"\/documentation\/divar\/districtedmapviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/DistrictPolygon":{"role":"symbol","title":"DistrictPolygon","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DistrictPolygon"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/DistrictPolygon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DistrictPolygon"}],"url":"\/documentation\/divar\/districtpolygon"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictedMapViewController\/title","value":"DistrictedMapViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictedMapViewController\/fragments","value":[{"kind":"identifier","text":"DistrictedMapViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictPolygon\/title","value":"DistrictPolygon"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1DistrictPolygon\/fragments","value":[{"kind":"identifier","text":"DistrictPolygon"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}