{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didStartLoadingData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractFormViewController","text":"AbstractFormViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"slug"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/addvrviewcontroller\/didstartloadingdata(_:for:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddVRViewController\/didStartLoadingData(_:for:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didStartLoadingData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AbstractFormViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractFormViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"didStartLoadingData(_:for:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:5Divar19AddVRViewControllerC19didStartLoadingData_3foryAA016AbstractFormViewD0C_SSSgtF","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddVRViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/AbstractFormViewController":{"role":"symbol","title":"AbstractFormViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractFormViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AbstractFormViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AbstractFormViewController"}],"url":"\/documentation\/divar\/abstractformviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/AddVRViewController/didStartLoadingData(_:for:)":{"role":"symbol","title":"didStartLoadingData(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didStartLoadingData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AbstractFormViewController","preciseIdentifier":"c:@M@Divar@objc(cs)AbstractFormViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddVRViewController\/didStartLoadingData(_:for:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/addvrviewcontroller\/didstartloadingdata(_:for:)"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/AddVRViewController":{"role":"symbol","title":"AddVRViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddVRViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AddVRViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddVRViewController"}],"url":"\/documentation\/divar\/addvrviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController\/title","value":"AbstractFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AbstractFormViewController\/fragments","value":[{"kind":"identifier","text":"AbstractFormViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddVRViewController\/title","value":"AddVRViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AddVRViewController\/fragments","value":[{"kind":"identifier","text":"AddVRViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}