{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nationalIdConfirmedSuccessfully"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":" "},{"kind":"internalParam","text":"flow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NationalIdVerificationFlowController","preciseIdentifier":"c:@M@Divar@objc(cs)NationalIdVerificationFlowController","text":"NationalIdVerificationFlowController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/postmanageflowcontroller\/nationalidconfirmedsuccessfully(in:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController\/nationalIdConfirmedSuccessfully(in:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"NationalIdVerificationFlowControllerDelegate.nationalIdConfirmedSuccessfully(in:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"nationalIdConfirmedSuccessfully(in:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nationalIdConfirmedSuccessfully"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NationalIdVerificationFlowController","preciseIdentifier":"c:@M@Divar@objc(cs)NationalIdVerificationFlowController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar24PostManageFlowControllerC31nationalIdConfirmedSuccessfully2inyAA08Nationalg12VerificationdE0C_tF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController\/NationalIdVerificationFlowControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PostManageFlowController/NationalIdVerificationFlowControllerDelegate-Implementations":{"role":"collectionGroup","title":"NationalIdVerificationFlowControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController\/NationalIdVerificationFlowControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/postmanageflowcontroller\/nationalidverificationflowcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/PostManageFlowController/nationalIdConfirmedSuccessfully(in:)":{"role":"symbol","title":"nationalIdConfirmedSuccessfully(in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nationalIdConfirmedSuccessfully"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NationalIdVerificationFlowController","preciseIdentifier":"c:@M@Divar@objc(cs)NationalIdVerificationFlowController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController\/nationalIdConfirmedSuccessfully(in:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postmanageflowcontroller\/nationalidconfirmedsuccessfully(in:)"},"doc://com.Divar.DivarClient/documentation/Divar/NationalIdVerificationFlowController":{"role":"symbol","title":"NationalIdVerificationFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NationalIdVerificationFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NationalIdVerificationFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NationalIdVerificationFlowController"}],"url":"\/documentation\/divar\/nationalidverificationflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostManageFlowController":{"role":"symbol","title":"PostManageFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostManageFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostManageFlowController"}],"url":"\/documentation\/divar\/postmanageflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NationalIdVerificationFlowController\/title","value":"NationalIdVerificationFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NationalIdVerificationFlowController\/fragments","value":[{"kind":"identifier","text":"NationalIdVerificationFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostManageFlowController\/title","value":"PostManageFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostManageFlowController\/fragments","value":[{"kind":"identifier","text":"PostManageFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}