{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postPaymentDidRequestPaymentHistory"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"postPaymentVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostPaymentViewController","preciseIdentifier":"c:@M@Divar@objc(cs)PostPaymentViewController","text":"PostPaymentViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mngToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/postmanageflowcontroller\/postpaymentdidrequestpaymenthistory(_:mngtoken:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController\/postPaymentDidRequestPaymentHistory(_:mngToken:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"PostPaymentViewControllerDelegate.postPaymentDidRequestPaymentHistory(_:mngToken:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"postPaymentDidRequestPaymentHistory(_:mngToken:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postPaymentDidRequestPaymentHistory"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PostPaymentViewController","preciseIdentifier":"c:@M@Divar@objc(cs)PostPaymentViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mngToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar24PostManageFlowControllerC021postPaymentDidRequestG7History_8mngTokenyAA0bg4ViewE0C_SStF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController\/PostPaymentViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PostManageFlowController/PostPaymentViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"PostPaymentViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController\/PostPaymentViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/postmanageflowcontroller\/postpaymentviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/PostPaymentViewController":{"role":"symbol","title":"PostPaymentViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostPaymentViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostPaymentViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostPaymentViewController"}],"url":"\/documentation\/divar\/postpaymentviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostManageFlowController/postPaymentDidRequestPaymentHistory(_:mngToken:)":{"role":"symbol","title":"postPaymentDidRequestPaymentHistory(_:mngToken:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postPaymentDidRequestPaymentHistory"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PostPaymentViewController","preciseIdentifier":"c:@M@Divar@objc(cs)PostPaymentViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mngToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController\/postPaymentDidRequestPaymentHistory(_:mngToken:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postmanageflowcontroller\/postpaymentdidrequestpaymenthistory(_:mngtoken:)"},"doc://com.Divar.DivarClient/documentation/Divar/PostManageFlowController":{"role":"symbol","title":"PostManageFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostManageFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostManageFlowController"}],"url":"\/documentation\/divar\/postmanageflowcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostPaymentViewController\/title","value":"PostPaymentViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostPaymentViewController\/fragments","value":[{"kind":"identifier","text":"PostPaymentViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostManageFlowController\/title","value":"PostManageFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostManageFlowController\/fragments","value":[{"kind":"identifier","text":"PostManageFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}