{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"redeemCodeSucceded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostRedeemCodeController","preciseIdentifier":"c:@M@Divar@objc(cs)PostRedeemCodeController","text":"PostRedeemCodeController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/postmanageflowcontroller\/redeemcodesucceded(vc:message:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController\/redeemCodeSucceded(vc:message:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"PostRedeemCodeControllerDelegate.redeemCodeSucceded(vc:message:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"redeemCodeSucceded(vc:message:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"redeemCodeSucceded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostRedeemCodeController","preciseIdentifier":"c:@M@Divar@objc(cs)PostRedeemCodeController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar24PostManageFlowControllerC18redeemCodeSucceded2vc7messageyAA0b6RedeemgE0C_SStF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController\/PostRedeemCodeControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PostManageFlowController/redeemCodeSucceded(vc:message:)":{"role":"symbol","title":"redeemCodeSucceded(vc:message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"redeemCodeSucceded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PostRedeemCodeController","preciseIdentifier":"c:@M@Divar@objc(cs)PostRedeemCodeController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController\/redeemCodeSucceded(vc:message:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postmanageflowcontroller\/redeemcodesucceded(vc:message:)"},"doc://com.Divar.DivarClient/documentation/Divar/PostManageFlowController/PostRedeemCodeControllerDelegate-Implementations":{"role":"collectionGroup","title":"PostRedeemCodeControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController\/PostRedeemCodeControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/postmanageflowcontroller\/postredeemcodecontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/PostManageFlowController":{"role":"symbol","title":"PostManageFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostManageFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostManageFlowController"}],"url":"\/documentation\/divar\/postmanageflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/PostRedeemCodeController":{"role":"symbol","title":"PostRedeemCodeController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostRedeemCodeController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostRedeemCodeController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostRedeemCodeController"}],"url":"\/documentation\/divar\/postredeemcodecontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostManageFlowController\/title","value":"PostManageFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostManageFlowController\/fragments","value":[{"kind":"identifier","text":"PostManageFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostRedeemCodeController\/title","value":"PostRedeemCodeController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostRedeemCodeController\/fragments","value":[{"kind":"identifier","text":"PostRedeemCodeController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}