{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shahkarlandlineConfirmedSuccessfully"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":" "},{"kind":"internalParam","text":"flow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShahkarLandlineVerificationFlowController","preciseIdentifier":"c:@M@Divar@objc(cs)ShahkarLandlineVerificationFlowController","text":"ShahkarLandlineVerificationFlowController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/postmanageflowcontroller\/shahkarlandlineconfirmedsuccessfully(in:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController\/shahkarlandlineConfirmedSuccessfully(in:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ShahkarLandlineVerificationFlowControllerDelegate.shahkarlandlineConfirmedSuccessfully(in:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"shahkarlandlineConfirmedSuccessfully(in:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shahkarlandlineConfirmedSuccessfully"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ShahkarLandlineVerificationFlowController","preciseIdentifier":"c:@M@Divar@objc(cs)ShahkarLandlineVerificationFlowController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar24PostManageFlowControllerC36shahkarlandlineConfirmedSuccessfully2inyAA027ShahkarLandlineVerificationdE0C_tF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController\/ShahkarLandlineVerificationFlowControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/PostManageFlowController/ShahkarLandlineVerificationFlowControllerDelegate-Implementations":{"role":"collectionGroup","title":"ShahkarLandlineVerificationFlowControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController\/ShahkarLandlineVerificationFlowControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/postmanageflowcontroller\/shahkarlandlineverificationflowcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/PostManageFlowController":{"role":"symbol","title":"PostManageFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostManageFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostManageFlowController"}],"url":"\/documentation\/divar\/postmanageflowcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/PostManageFlowController/shahkarlandlineConfirmedSuccessfully(in:)":{"role":"symbol","title":"shahkarlandlineConfirmedSuccessfully(in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shahkarlandlineConfirmedSuccessfully"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ShahkarLandlineVerificationFlowController","preciseIdentifier":"c:@M@Divar@objc(cs)ShahkarLandlineVerificationFlowController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/PostManageFlowController\/shahkarlandlineConfirmedSuccessfully(in:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/postmanageflowcontroller\/shahkarlandlineconfirmedsuccessfully(in:)"},"doc://com.Divar.DivarClient/documentation/Divar/ShahkarLandlineVerificationFlowController":{"role":"symbol","title":"ShahkarLandlineVerificationFlowController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShahkarLandlineVerificationFlowController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/ShahkarLandlineVerificationFlowController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShahkarLandlineVerificationFlowController"}],"url":"\/documentation\/divar\/shahkarlandlineverificationflowcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostManageFlowController\/title","value":"PostManageFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1PostManageFlowController\/fragments","value":[{"kind":"identifier","text":"PostManageFlowController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ShahkarLandlineVerificationFlowController\/title","value":"ShahkarLandlineVerificationFlowController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1ShahkarLandlineVerificationFlowController\/fragments","value":[{"kind":"identifier","text":"ShahkarLandlineVerificationFlowController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}