{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleKeyboardStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"notification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/numberinputviewcontroller\/handlekeyboardstatus(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/numberinputviewcontroller\/handlekeyboardstatus(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberInputViewController\/handleKeyboardStatus(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleKeyboardStatus"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":")"}],"title":"handleKeyboardStatus(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Divar@objc(cs)NumberInputViewController(im)handleKeyboardStatus:","modules":[{"name":"Divar"}],"navigatorTitle":[{"kind":"identifier","text":"handleKeyboardStatus:"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberInputViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/NumberInputViewController/handleKeyboardStatus(_:)":{"role":"symbol","title":"handleKeyboardStatus(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleKeyboardStatus"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberInputViewController\/handleKeyboardStatus(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"handleKeyboardStatus:"}],"url":"\/documentation\/divar\/numberinputviewcontroller\/handlekeyboardstatus(_:)"},"doc://com.Divar.DivarClient/documentation/Divar/NumberInputViewController":{"role":"symbol","title":"NumberInputViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NumberInputViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NumberInputViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NumberInputViewController"}],"url":"\/documentation\/divar\/numberinputviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"handleKeyboardStatus:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleKeyboardStatus:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"handleKeyboardStatus:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"notification"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NumberInputViewController~1handleKeyboardStatus(_:)\/title","value":"handleKeyboardStatus:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NumberInputViewController~1handleKeyboardStatus(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleKeyboardStatus:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NumberInputViewController\/title","value":"NumberInputViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NumberInputViewController\/fragments","value":[{"kind":"identifier","text":"NumberInputViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}