{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bookmarkView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"didTap"},{"kind":"text","text":" "},{"kind":"internalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView","preciseIdentifier":"c:@M@Divar@objc(cs)BookmarkView","text":"BookmarkView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isBookmark"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/widgetbasedpostdetailsviewcontroller\/bookmarkview(didtap:isbookmark:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostDetailsViewController\/bookmarkView(didTap:isBookmark:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"BookmarkViewDelegate.bookmarkView(didTap:isBookmark:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"bookmarkView(didTap:isBookmark:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bookmarkView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"didTap"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BookmarkView","preciseIdentifier":"c:@M@Divar@objc(cs)BookmarkView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isBookmark"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:5Divar36WidgetBasedPostDetailsViewControllerC08bookmarkF06didTap10isBookmarkyAA0lF0C_SbtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostDetailsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostDetailsViewController\/BookmarkViewDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedPostDetailsViewController/BookmarkViewDelegate-Implementations":{"role":"collectionGroup","title":"BookmarkViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostDetailsViewController\/BookmarkViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/widgetbasedpostdetailsviewcontroller\/bookmarkviewdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedPostDetailsViewController":{"role":"symbol","title":"WidgetBasedPostDetailsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedPostDetailsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostDetailsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedPostDetailsViewController"}],"url":"\/documentation\/divar\/widgetbasedpostdetailsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar/BookmarkView":{"role":"symbol","title":"BookmarkView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BookmarkView"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/BookmarkView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BookmarkView"}],"url":"\/documentation\/divar\/bookmarkview"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedPostDetailsViewController/bookmarkView(didTap:isBookmark:)":{"role":"symbol","title":"bookmarkView(didTap:isBookmark:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bookmarkView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"didTap"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BookmarkView","preciseIdentifier":"c:@M@Divar@objc(cs)BookmarkView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isBookmark"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostDetailsViewController\/bookmarkView(didTap:isBookmark:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetbasedpostdetailsviewcontroller\/bookmarkview(didtap:isbookmark:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedPostDetailsViewController\/title","value":"WidgetBasedPostDetailsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedPostDetailsViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedPostDetailsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarkView\/title","value":"BookmarkView"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1BookmarkView\/fragments","value":[{"kind":"identifier","text":"BookmarkView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}