{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"noteViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteViewController","preciseIdentifier":"c:@M@Divar@objc(cs)NoteViewController","text":"NoteViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishChangingNote"},{"kind":"text","text":" "},{"kind":"internalParam","text":"note"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/divar\/widgetbasedpostdetailsviewcontroller\/noteviewcontroller(_:didfinishchangingnote:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostDetailsViewController\/noteViewController(_:didFinishChangingNote:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"NoteViewControllerDelegate.noteViewController(_:didFinishChangingNote:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"noteViewController(_:didFinishChangingNote:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"noteViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NoteViewController","preciseIdentifier":"c:@M@Divar@objc(cs)NoteViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishChangingNote"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"s:5Divar36WidgetBasedPostDetailsViewControllerC04notefG0_21didFinishChangingNoteyAA0lfG0C_SSSgtF","extendedModule":"Divar","modules":[{"name":"Divar"}]},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostDetailsViewController","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostDetailsViewController\/NoteViewControllerDelegate-Implementations"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedPostDetailsViewController/noteViewController(_:didFinishChangingNote:)":{"role":"symbol","title":"noteViewController(_:didFinishChangingNote:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"noteViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NoteViewController","preciseIdentifier":"c:@M@Divar@objc(cs)NoteViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishChangingNote"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostDetailsViewController\/noteViewController(_:didFinishChangingNote:)","kind":"symbol","type":"topic","url":"\/documentation\/divar\/widgetbasedpostdetailsviewcontroller\/noteviewcontroller(_:didfinishchangingnote:)"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedPostDetailsViewController":{"role":"symbol","title":"WidgetBasedPostDetailsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetBasedPostDetailsViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostDetailsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetBasedPostDetailsViewController"}],"url":"\/documentation\/divar\/widgetbasedpostdetailsviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/WidgetBasedPostDetailsViewController/NoteViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"NoteViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/WidgetBasedPostDetailsViewController\/NoteViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/divar\/widgetbasedpostdetailsviewcontroller\/noteviewcontrollerdelegate-implementations"},"doc://com.Divar.DivarClient/documentation/Divar/NoteViewController":{"role":"symbol","title":"NoteViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NoteViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/NoteViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NoteViewController"}],"url":"\/documentation\/divar\/noteviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedPostDetailsViewController\/title","value":"WidgetBasedPostDetailsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1WidgetBasedPostDetailsViewController\/fragments","value":[{"kind":"identifier","text":"WidgetBasedPostDetailsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteViewController\/title","value":"NoteViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1NoteViewController\/fragments","value":[{"kind":"identifier","text":"NoteViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}