{"variants":[{"paths":["\/documentation\/divar\/angoolakresponseheadereditorviewcontroller\/uitableviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/divar\/angoolakresponseheadereditorviewcontroller\/uitableviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseHeaderEditorViewController\/UITableViewDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseHeaderEditorViewController\/tableView(_:editingStyleForRowAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseHeaderEditorViewController\/tableView(_:trailingSwipeActionsConfigurationForRowAt:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Divar"}],"role":"collectionGroup","title":"UITableViewDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.Divar.DivarClient\/documentation\/Divar","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseHeaderEditorViewController"]]},"references":{"doc://com.Divar.DivarClient/documentation/Divar/AngoolakResponseHeaderEditorViewController/tableView(_:editingStyleForRowAt:)":{"role":"symbol","title":"tableView(_:editingStyleForRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"editingStyleForRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"EditingStyle","preciseIdentifier":"c:@E@UITableViewCellEditingStyle"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseHeaderEditorViewController\/tableView(_:editingStyleForRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:editingStyleForRowAtIndexPath:"}],"url":"\/documentation\/divar\/angoolakresponseheadereditorviewcontroller\/tableview(_:editingstyleforrowat:)"},"doc://com.Divar.DivarClient/documentation/Divar/AngoolakResponseHeaderEditorViewController":{"role":"symbol","title":"AngoolakResponseHeaderEditorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AngoolakResponseHeaderEditorViewController"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseHeaderEditorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AngoolakResponseHeaderEditorViewController"}],"url":"\/documentation\/divar\/angoolakresponseheadereditorviewcontroller"},"doc://com.Divar.DivarClient/documentation/Divar":{"role":"collection","title":"Divar","abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar","kind":"symbol","type":"topic","url":"\/documentation\/divar"},"doc://com.Divar.DivarClient/documentation/Divar/AngoolakResponseHeaderEditorViewController/tableView(_:trailingSwipeActionsConfigurationForRowAt:)":{"role":"symbol","title":"tableView(_:trailingSwipeActionsConfigurationForRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trailingSwipeActionsConfigurationForRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UISwipeActionsConfiguration","preciseIdentifier":"c:objc(cs)UISwipeActionsConfiguration"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseHeaderEditorViewController\/tableView(_:trailingSwipeActionsConfigurationForRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:trailingSwipeActionsConfigurationForRowAtIndexPath:"}],"url":"\/documentation\/divar\/angoolakresponseheadereditorviewcontroller\/tableview(_:trailingswipeactionsconfigurationforrowat:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseHeaderEditorViewController\/tableView(_:editingStyleForRowAt:)","doc:\/\/com.Divar.DivarClient\/documentation\/Divar\/AngoolakResponseHeaderEditorViewController\/tableView(_:trailingSwipeActionsConfigurationForRowAt:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakResponseHeaderEditorViewController~1tableView(_:editingStyleForRowAt:)\/title","value":"tableView:editingStyleForRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakResponseHeaderEditorViewController~1tableView(_:editingStyleForRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:editingStyleForRowAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakResponseHeaderEditorViewController\/title","value":"AngoolakResponseHeaderEditorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakResponseHeaderEditorViewController\/fragments","value":[{"kind":"identifier","text":"AngoolakResponseHeaderEditorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakResponseHeaderEditorViewController~1tableView(_:trailingSwipeActionsConfigurationForRowAt:)\/title","value":"tableView:trailingSwipeActionsConfigurationForRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.Divar.DivarClient~1documentation~1Divar~1AngoolakResponseHeaderEditorViewController~1tableView(_:trailingSwipeActionsConfigurationForRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:trailingSwipeActionsConfigurationForRowAtIndexPath:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}